import { Music } from '../../../models/music-model';

export const musicsJamesDeano: Music[] = [
  // Album : Le Fils du commissaire (2008) - James Deano
  {
    title: 'El Playboy',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Les Blancs ne savent pas danser',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Arrête de fuir',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: '11 du 9',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Sans exception',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Chercheur d\'énergie',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le Fils du commissaire',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ma vie de célibataire',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Drogué dur à la drogue douce',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Riz sauce rien',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Koh Lanta',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Les Femmes',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Les gens sont stressés',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tu t\'es vu quand t\'abuses',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Loin de la vérité',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le Son du cosmos',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Battle et fontaine',
    artist: 'James Deano',
    album: 'Le Fils du commissaire',
    coverUrl: '/musics_pictures/james-deano-le-fils-du-commissaire.jpg',
    releaseDate: '2008-06-09',
    rating: 0,
    duration: 235,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Putain de boucher (2011) - James Deano
  {
    title: 'Grâce à Dieu',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ailes d\'oiseau',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ça fait plaisir',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Travailler plus',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Les Frangins',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Allume les lights',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Je cherche une femme',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bien acquis',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tiéquart',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Libre comme l\'air',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Rien à déclarer',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Partir loin',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'J\'aime pas la house (par contre la techno...)',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Squatter les terrasses',
    artist: 'James Deano',
    album: 'Putain de boucher',
    coverUrl: '/musics_pictures/james-deano-putain-de-boucher.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
];

