import { Music } from '../../../models/music-model';

export const musicsSniper: Music[] = [
  // Album : Du rire aux larmes (2001) - Sniper
  {
    title: 'Intro',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 92,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Sniper processus',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 258,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Pris pour cible',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Faut de tout pour faire un monde',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 288,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Intro "Le crew est de sortie"',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 29,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le crew est de sortie',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 271,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Intro "Tribal poursuite"',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 41,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tribal poursuite',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 281,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La France (solo Tunisiano)',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 378,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Intro "Du rire aux larmes"',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 64,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Du rire aux larmes',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Aketo vs. Tunisiano',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La sentence',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 241,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Quand on te dit',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 236,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Aketo solo (solo Aketo)',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 255,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Fait divers',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La rumba',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 259,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'On s\'en sort bien',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/sniper-du-rire-aux-larmes.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Gravé dans la roche (2003) - Sniper
  {
    title: 'Intro',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 127,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Processus 2003',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 325,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Visions chaotiques',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 442,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Gravé dans la roche',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 285,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Pourquoi',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 307,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Recette maison',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 230,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Y\'a pas de mérite',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 246,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Sans (re)pères',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ce que j\'ai sur le cœur',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 312,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: '35 heures',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Hall Story',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 352,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Entre deux',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Trop vite (solo Blacko)',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 337,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Jeteur de pierres',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 377,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Interlude micro ouvert',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 109,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Panam All Starz',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/sniper-grave-dans-la-roche.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 468,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Trait pour trait (2006) - Sniper
  {
    title: 'S.N.I',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Dans mon monde',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Trait pour trait',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 270,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Eldorado',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 395,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Zamalia (solo Blacko)',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 257,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Génération Tanguy',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 282,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Donne tout',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 271,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La France (itinéraire d\'une polémique) (solo Tunisiano)',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 401,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Hommes de loi',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 331,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Il était une foi',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 338,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Radio',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 75,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Retour aux sources (solo Aketo)',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 325,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Elle',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 335,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Brûle',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 281,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Fallait que je te dise',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/sniper-trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 577,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
];

