
export const mangas = [
  {
    _type: 'manga',
    _id: 'AVQP8pBozTdbq0wiqMev',
    _score: 4,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Naruto',
        slug: 'naruto',
        authors: [
          {
            name: 'Masashi Kishimoto',
          },
        ],
        closeMangas: ['black_clover', 'satan_666'],
        country: 'Japan',
        description:
          "Naruto est un jeune ninja turbulent et orphelin. Seul depuis tout petit, il multiplie les bêtises en tout genre pour se faire remarquer mais n'en arrive qu'à se faire détester par le village de Konoha. Par le biais de son professeur Iruka et du traître Mizuki, il découvre que cette haine collective n'est autre que le fruit du démon qu'il abrite en lui. Kyubi, le démon renard à neuf queues ayant attaqué le village et scellé en lui par le 4ème Hokage. Mais loin de se laisser abattre, Naruto parvient à devenir un vrai ninja et part en missions accompagné du professeur Kakashi, de son amie Sakura et de son rival, Sasuke Uchiwa.",
        hasAnime: true,
        isFinished: true,
        keywords: 'ninja',
        lastUpdate: '05/10/2017',
        nbEpisodes: 500,
        type: 'Shonen',
        mainHero: {
          name: 'Naruto Uzumaki',
        },
        france: {
          editor: 'Kana',
          logo: '/mangas_pictures/naruto.jpg',
          nbBooks: 72,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 72,
          logo: '/mangas_pictures/japan/naruto.jpg',
          nbChapters: 700,
          publicationEnd: '2014',
          publicationStart: '1999',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMe2',
    _score: 4,
    _readTimes: 2,
    _source: {
      manga: {
        name: 'Kingdom',
        slug: 'kingdom',
        authors: [
          {
            name: 'Yasuhisa Hara',
          },
        ],
        closeMangas: [],
        country: 'Japan',
        description:
          "Des centaines d'années auparavant en Chine, Shin et Hyou sont deux paysans esclaves et le coeur rempli de rêves et d'espoir. Un seul objectif en tête, les deux garçons s'entraînent sans relâche pour devenir Grand Général dans l'armée et ainsi prouver leur force et faire résonner leur nom dans tout le pays. A la suite de la mort de Hyou, Shin jure d'accomplir ce dessein coûte que coûte en accompagnant le jeune Ei Sei qui tente de regagner son trône de roi de Qin, le plus grand état de Chine.",
        hasAnime: true,
        isFinished: false,
        keywords: 'war, general, qin, china',
        lastUpdate: '05/10/2017',
        nbEpisodes: 0,
        type: 'Seinen',
        mainHero: {
          name: 'Shin',
        },
        france: {
          editor: '',
          logo: '/mangas_pictures/kingdom.jpg',
          nbBooks: 75,
        },
        japan: {
          editor: 'Shueisha',
          magazine: 'Weekly Young Jump',
          nbBooks: 75,
          nbChapters: 532,
          publicationEnd: null,
          publicationStart: '2006',
          logo: '/mangas_pictures/japan/kingdom.jpg',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pCEzTdbq0wiqMe3',
    _score: 4.75,
    _readTimes: 10,
    _source: {
      manga: {
        name: 'Eyeshield 21',
        slug: 'eyeshield_21',
        authors: [
          {
            name: 'Riichirō Inagaki',
          },
          {
            name: 'Yusuke Murata',
          },
        ],
        closeMangas: [],
        description:
          "Sena Kobayakawa est un jeune lycéen petit et par-dessus tout, craintif. Souffre-douleur et préposé aux basses besognes des Caïds de sa classe, il est constamment en train de courir pour aller chercher ce qu'ils demandent. Un jour, Yoichi Hiruma, terreur du lycée et membre du club de football Américain avec son ami Kurita, s'aperçoit de son extraordinaire vitesse et cherche à tout prix à le recruter dans le club en tant que Running Back. Mais l'amie d'enfance de Sena, Mamori, n'est pas de cet avis.",
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'sport, american football',
        lastUpdate: '16/04/2016',
        nbEpisodes: 145,
        type: 'Shonen',
        mainHero: {
          name: 'Kobayakawa Sena',
        },
        france: {
          editor: 'Glénat',
          logo: '/mangas_pictures/eyeshield.jpg',
          nbBooks: 37,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: '/mangas_pictures/eyeshield21.jpg',
          nbBooks: 37,
          nbChapters: 333,
          publicationEnd: '2009',
          publicationStart: '2002',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJizTdbq0wiqMfG',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'My Hero Academia',
        slug: 'boku_no_hero_academia',
        authors: [
          {
            name: 'Horikoshi Kouhei',
          },
        ],
        closeMangas: ['black_clover'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: 'hero, super heroes',
        lastUpdate: '05/10/2017',
        nbEpisodes: 13,
        type: 'Shonen',
        mainHero: {
          name: 'Midoriya Izuku',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: '/mangas_pictures/my_hero_academia.jpg',
          nbBooks: 15,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: '/mangas_pictures/bokunoheroacademia.jpg',
          nbBooks: 15,
          nbChapters: 153,
          publicationEnd: null,
          publicationStart: '2014',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKSzTdbq0wiqMfK',
    _score: 3,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Black Clover',
        slug: 'black_clover',
        authors: [
          {
            name: 'Tabata Yuuki',
          },
        ],
        closeMangas: ['naruto', 'boku_no_hero_academia'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Aster',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 11,
          logo: '/mangas_pictures/black_clover.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 11,
          logo: '/mangas_pictures/japan/blackclover.jpg',
          nbChapters: 51,
          publicationEnd: null,
          publicationStart: '2015',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKszTdbq0wiqMfL',
    _score: 2.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Nisekoi',
        slug: 'nisekoi',
        authors: [
          {
            name: 'Komi Naoshi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Raku Ishijou',
        },
        france: {
          editor: '',
          logo: '/mangas_pictures/nisekoi.jpg',
          nbBooks: 25,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: '/mangas_pictures/nisekoi.jpg',
          nbBooks: 0,
          nbChapters: 212,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNEzTdbq0wiqMfZ',
    _score: 3.25,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Dreamland',
        slug: 'dreamland',
        authors: [
          {
            name: 'Reno Lemaire',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '05/10/2017',
        type: 'Shonen',
        mainHero: {
          name: 'Terrence Meyer',
        },
        france: {
          editor: 'Pika',
          logo: '/mangas_pictures/dreamland.jpg',
          nbBooks: 16,
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfp',
    _score: 2.75,
    _readTimes: 2,
    _source: {
      manga: {
        name: 'Saru Lock',
        slug: 'saru_lock',
        authors: [
          {
            name: 'Naoki Serizawa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Seinen',
        mainHero: {
          name: 'Yutaro Sarumaru',
        },
        france: {
          editor: '',
          logo: '/mangas_pictures/saru_lock.jpg',
          nbBooks: 22,
        },
        japan: {
          editor: '',
          logo: '/mangas_pictures/japan/sarulock.jpg',
          nbBooks: 22,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pSfzTdbq0wiqMf4',
    _score: 3,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Hi No Tori',
        slug: 'hi_no_tori',
        authors: [
          {
            name: 'Ozamu Tezuka',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Seinen',
        mainHero: {
          name: 'Hino',
        },
        france: {
          editor: '',
          logo: '/mangas_pictures/hi_no_tori.png',
          nbBooks: 21,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: '/mangas_pictures/japan/hinotori.jpg',
          nbBooks: 21,
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB3zTdbq0wiqMew',
    _score: 3.5,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Pretty Face',
        slug: 'pretty_face',
        authors: [
          {
            name: 'Yasuhiro Kanô',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Shonen',
        mainHero: {
          name: 'Masashi Rando',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          editor: 'Tonkam',
          logo: '/mangas_pictures/pretty_face.jpg',
          nbBooks: 6,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: '/mangas_pictures/',
          nbBooks: 6,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMe0',
    _score: 4.5,
    _readTimes: 15,
    _source: {
      manga: {
        name: 'Dragon Ball',
        slug: 'dragon_ball',
        authors: [
          {
            name: 'Akira Toriyama',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: '/mangas_pictures/dragon_ball.jpg',
        mainHero: {
          name: 'Sangoku',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 42,
          logo: '/mangas_pictures/dragon_ball.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 42,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pHuzTdbq0wiqMe-',
    _score: 3.75,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'OnePunch-Man',
        slug: 'one_punch_man',
        authors: [
          {
            name: 'Yûsuke Murata',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Saitama',
        },
        france: {
          editor: 'Kurokawa',
          nbBooks: 14,
          logo: '/mangas_pictures/one_punch_man.jpg',
        },
        japan: {
          magazine: 'Tonari no Young Jump',
          editor: 'Shueisha',
          nbBooks: 14,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 98,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pL5zTdbq0wiqMfT',
    _score: 2.75,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'GTO',
        authors: [
          {
            name: '',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Eiikichi Onizuka',
        },
        france: {
          editor: '',
          nbBooks: 25,
          logo: '/mangas_pictures/gto.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/gto.jpg',
          nbChapters: 0,
          publicationEnd: '2002',
          publicationStart: '1997',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMSzTdbq0wiqMfU',
    _score: 3.75,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Captain Tsubasa',
        slug: 'captain_tsubasa',
        frenchName: 'Olive Et Tom',
        authors: [
          {
            name: 'Yōichi Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'sport, football',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Tsubasa Ohzora',
        },
        france: {
          editor: '',
          nbBooks: 37,
          logo: '/mangas_pictures/captain_tsubasa.webp',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 37,
          logo: '/mangas_pictures/japan/captaintsubasa.jpg',
          nbChapters: 0,
          publicationEnd: '1988',
          publicationStart: '1981',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pN9zTdbq0wiqMfd',
    _score: 3.75,
    _readTimes: 2,
    _source: {
      manga: {
        name: 'Slam Dunk',
        slug: 'slam_dunk',
        authors: [
          {
            name: 'Takehiko Inoue',
          },
        ],
        closeMangas: ['Kuroko No Basket', 'Crows'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'basket, sport',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Hanamichi Sakuragi',
        },
        france: {
          editor: '',
          nbBooks: 31,
          logo: '/mangas_pictures/slam_dunk.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 31,
          logo: '/mangas_pictures/japan/slamdunk.jpg',
          nbChapters: 0,
          publicationEnd: '1996',
          publicationStart: '1990',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pPZzTdbq0wiqMfl',
    _score: 2.75,
    _readTimes: 1,
    _source: {
      manga: {
        name: "Darwin's Game",
        slug: 'darwin_game',
        authors: [
          {
            name: 'Flipf lops',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Sudo Kaname',
        },
        france: {
          editor: '',
          nbBooks: 8,
          logo: '/mangas_pictures/darwin_game.webp',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/darwinsgame.jpg',
          nbChapters: 21,
          publicationEnd: null,
          publicationStart: '2015',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfo',
    _score: 4.25,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Hikaru No Go',
        slug: 'hikaru_no_go',
        authors: [
          {
            name: 'Yumi Hotta',
          },
          {
            name: 'Tsugumi Ohba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: '/mangas_pictures/hikaru_no_go.jpg',
        mainHero: {
          name: 'Hikaru',
        },
        france: {
          editor: 'Tonkam',
          nbBooks: 23,
          logo: '/mangas_pictures/hikaru_no_go.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 23,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: '2003',
          publicationStart: '1998',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQ6zTdbq0wiqMfw',
    _score: 3.5,
    _readTimes: 10,
    _source: {
      manga: {
        name: 'Rave',
        slug: 'rave',
        authors: [
          {
            name: 'Hiro Mashima',
          },
        ],
        closeMangas: ['fairy_tail'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Haru Glory',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 35,
          logo: '/mangas_pictures/rave.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 35,
          logo: '/mangas_pictures/japan/rave.jpg',
          nbChapters: 0,
          publicationEnd: '2005',
          publicationStart: '1999',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pRfzTdbq0wiqMfz',
    _score: 3,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Kuroko No Basket',
        slug: 'kuroko_no_basket',
        authors: [
          {
            name: 'Tadatoshi Fujimaki',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'sport',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Kuroko',
        },
        france: {
          editor: '',
          nbBooks: 30,
          logo: '/mangas_pictures/kuroko_no_basket.webp',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/kurokonobasket.jpg',
          nbChapters: 0,
          publicationEnd: '2014',
          publicationStart: '2008',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pRozTdbq0wiqMf0',
    _score: 2.75,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Code:breaker',
        slug: 'code_breaker',
        authors: [
          {
            name: 'Akimine Kamijō',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: '/mangas_pictures/codebreaker.jpg',
        mainHero: {
          name: 'Rei Ôgami',
        },
        france: {
          editor: '',
          nbBooks: 26,
          logo: '/mangas_pictures/code_breaker.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/codebreaker.jpg',
          nbChapters: 200,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTMzTdbq0wiqMf7',
    _score: 2.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Reborn',
        slug: 'reborn',
        authors: [
          {
            name: 'Akira Amano',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: '/mangas_pictures/reborn.jpg',
        mainHero: {
          name: 'Reborn',
        },
        france: {
          editor: '',
          nbBooks: 42,
          logo: '/mangas_pictures/reborn.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/reborn.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB4zTdbq0wiqMex',
    _score: 4.75,
    _readTimes: 10,
    _source: {
      manga: {
        name: 'Bakuman',
        slug: 'bakuman',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsugumi Ōba',
          },
        ],
        closeMangas: [],
        description: 'manga, editor',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Mashiro Moritaka',
        },
        france: {
          editor: 'Kana',
          nbBooks: 20,
          logo: '/mangas_pictures/bakuman.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 20,
          logo: '/mangas_pictures/japan/bakuman.jpg',
          nbChapters: 822,
          publicationEnd: '2012',
          publicationStart: '2008',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMe1',
    _score: 3.75,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Jackals',
        slug: 'jackals',
        authors: [
          {
            name: 'Kim Byung Jin',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        logo: '/mangas_pictures/jackals.jpg',
        mainHero: {
          name: 'Alligator Nihol',
        },
        france: {
          editor: '',
          nbBooks: 6,
          logo: '/mangas_pictures/jackals.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 6,
          logo: '/mangas_pictures/japan/jackals.jpg',
          nbChapters: 56,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pGwzTdbq0wiqMe7',
    _score: 3.75,
    _readTimes: 3,
    _source: {
      manga: {
        name: 'Magi The Labyrinth of Magic',
        slug: 'magi',
        authors: [
          {
            name: 'Ohtaka Shinobu',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: '/mangas_pictures/magi.jpg',
        mainHero: {
          name: 'Aladin',
        },
        france: {
          editor: '',
          nbBooks: 37,
          logo: '/mangas_pictures/magi.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/magi.jpg',
          nbChapters: 300,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKIzTdbq0wiqMfH',
    _score: 4,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Yu Yu Hakusho',
        slug: 'yu_yu_hakusho',
        authors: [
          {
            name: 'Yoshihiro Togashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yusuke Urameshi',
        },
        france: {
          editor: 'Kana',
          nbBooks: 19,
          logo: '/mangas_pictures/yu_yu_hakusho.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/yuyuhakusho.jpg',
          nbChapters: 0,
          publicationEnd: '1994',
          publicationStart: '1990',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLgzTdbq0wiqMfP',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Fullmetal Alchemist',
        slug: 'full_metal_alchemist',
        authors: [
          {
            name: 'Hiromu Arakawa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Edward Elric',
        },
        france: {
          editor: '',
          nbBooks: 27,
          logo: '/mangas_pictures/fullmetal_alchemist.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/fullmetalalchemist.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLhzTdbq0wiqMfR',
    _score: 2.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Ginga Patrol Jako',
        slug: 'ginga_patrol_jako',
        authors: [
          {
            name: 'Akira Toriyama',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Jako',
        },
        france: {
          editor: '',
          nbBooks: 1,
          logo: '/mangas_pictures/jaco.webp',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/gingapatroljako.jpg',
          nbChapters: 12,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMWzTdbq0wiqMfV',
    _score: 3.5,
    _readTimes: 3,
    _source: {
      manga: {
        name: 'Gamble fish',
        slug: 'gamble_fish',
        authors: [
          {
            name: 'Aoyama Hiromi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Ecchi',
        mainHero: {
          name: 'Tomu Shirasagi',
        },
        france: {
          editor: '',
          nbBooks: 19,
          logo: '/mangas_pictures/gamble_fish.jpg',
          nbChapters: 167,
          publicationEnd: '2010',
          publicationStart: '2007',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMvzTdbq0wiqMfX',
    _score: 2.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Tonari no Seki-kun',
        slug: 'tonari_no_seki_kun',
        authors: [
          {
            name: 'Takuma Morishige',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Seki',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          editor: '',
          nbBooks: 12,
          logo: '/mangas_pictures/tonari_no_seki_kun.webp',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/tonarinosekikun.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNzzTdbq0wiqMfc',
    _score: 3.25,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Puella Magi Madoka Magica',
        slug: 'puella_magi_madoka_magica',
        authors: [
          {
            name: 'Hanokage',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        mainHero: {
          name: 'Madoka Kaname',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 3,
          logo: '/mangas_pictures/pmmm.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/puellamagimadokamagica.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pN_zTdbq0wiqMfe',
    _score: 3.25,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Nanatsu No Taizai',
        slug: 'nanatsu_no_taizai',
        authors: [
          {
            name: 'Suzuki Nakaba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'M',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 41,
          logo: '/mangas_pictures/nanatsu_no_taizai.webp',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/nanatsunotaizai.jpg',
          nbChapters: 167,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pO8zTdbq0wiqMfj',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Black Cat',
        slug: 'black_cat',
        authors: [
          {
            name: 'Kentaro Yabuki',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Train Heartnet',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 20,
          logo: '/mangas_pictures/black_cat.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/blackcat.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfr',
    _score: 3.25,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Shaman king',
        slug: 'shaman_king',
        authors: [
          {
            name: 'Hiroyuki Takei',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yo',
        },
        france: {
          editor: 'Kana',
          nbBooks: 32,
          logo: '/mangas_pictures/shaman_king.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/shamanking.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQjzTdbq0wiqMfu',
    _score: 2.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Doubt',
        slug: 'doubt',
        authors: [
          {
            name: 'Yoshiki Tonogai',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        mainHero: {
          name: 'Yū Aikawa',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 6,
          logo: '/mangas_pictures/doubt.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 6,
          logo: '/mangas_pictures/japan/doubt.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pR8zTdbq0wiqMf2',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Shokugeki no Soma',
        slug: 'shokugeki_no_soma',
        authors: [
          {
            name: 'Tsukuda Yuuto',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Souma Yukihira',
        },
        france: {
          editor: '',
          nbBooks: 36,
          logo: '/mangas_pictures/shokugeki_no_soma.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/shokugekinosoma.jpg',
          nbChapters: 161,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTbzTdbq0wiqMf8',
    _score: 2.75,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Blue Dragon : Ral Ω Grad',
        slug: 'blue_dragon',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsuneo Takano',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shu',
        },
        france: {
          editor: '',
          nbBooks: 4,
          logo: '/mangas_pictures/blue_dragon.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/bluedragon.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTzzTdbq0wiqMf9',
    _score: 2,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Blazing Ninjaman',
        slug: 'blazing_ninjaman',
        authors: [
          {
            name: '',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shinobi Mantaro',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 2,
          logo: '/mangas_pictures/blazing_ninjaman.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMez',
    _score: 5,
    _readTimes: 30,
    _source: {
      manga: {
        name: 'One Piece',
        slug: 'one_piece',
        authors: [
          {
            name: 'Eiichirō Oda',
          },
        ],
        closeMangas: [],
        description:
          "Luffy est un jeune garçon qui rêve de devenir un pirate, comme son idole Shanks. Par innatention, il mange un jour un fruit du démon qui le rend élastique mais lui confère l'impossibilité de nager. Après s'être fait sauver la vie par Shanks, il jure à ce dernier de devenir le Seigneur des Pirates et s'entraîne pendant 10 ans à utiliser son pouvoir. Il prend la mer à 17 ans pour trouver de valeureux compagnons, la tête pleine de rêves qu'il fera tout pour réaliser.",
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 737,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Monkey D. Luffy',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 110,
          logo: '/mangas_pictures/one_piece.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 81,
          logo: '/mangas_pictures/onepiece.jpg',
          nbChapters: 852,
          publicationEnd: null,
          publicationStart: '1997',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pCIzTdbq0wiqMe5',
    _score: 4.75,
    _readTimes: 15,
    _source: {
      manga: {
        name: 'Rurouni No Kenshin',
        slug: 'kenshin',
        frenchName: 'Kenshin le Vagabond',
        authors: [
          {
            name: 'Nobuhiro Watsuki',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'samourai, samurai, sword, vagabond',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Kenshin Himura',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 28,
          logo: '/mangas_pictures/kenshin.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 28,
          logo: '/mangas_pictures/japan/kenshinlevagabond.jpg',
          nbChapters: 0,
          publicationEnd: '1999',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMey',
    _score: 4.5,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Feng Shen Ji',
        slug: 'feng_shen_ji',
        authors: [
          {
            name: 'Zeng Jian He',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'gods, manhua',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Ah Gou',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          editor: '',
          nbBooks: 20,
          logo: '/mangas_pictures/feng_shen_ji.jpg',
        },
        china: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/china/fengshenji.svg',
          nbChapters: 180,
          publicationEnd: '2016',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pHSzTdbq0wiqMe9',
    _score: 4.25,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Toriko',
        slug: 'toriko',
        authors: [
          {
            name: 'Shimabukuro Mitsutoshi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'food, gourmet, animals',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Toriko',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          editor: '',
          nbBooks: 43,
          logo: '/mangas_pictures/toriko.webp',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 43,
          logo: '/mangas_pictures/japan/toriko.jpg',
          nbChapters: 366,
          publicationEnd: '2016',
          publicationStart: '2008',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pIezTdbq0wiqMfB',
    _score: 4,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Satan 666',
        slug: 'satan_666',
        authors: [
          {
            name: 'Seishi Kishimoto',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Jio Freed',
        },
        france: {
          editor: 'Kurokawa',
          nbBooks: 19,
          logo: '/mangas_pictures/satan_666.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 19,
          logo: '/mangas_pictures/japan/satan666.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJCzTdbq0wiqMfC',
    _score: 4,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Worst',
        slug: 'worst',
        authors: [
          {
            name: 'Hiroshi Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'furyo',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Hana Tsukihima',
        },
        france: {
          editor: '',
          nbBooks: 33,
          logo: '/mangas_pictures/worst.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/worst.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJizTdbq0wiqMfF',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Akame Ga Kill',
        slug: 'akame_ga_kill',
        authors: [
          {
            name: 'Takahiro',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Tatsumi',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 15,
          logo: '/mangas_pictures/akame_ga_kill.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/akamegakill.jpg',
          nbChapters: 69,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pK-zTdbq0wiqMfN',
    _score: 4.75,
    _readTimes: 15,
    _source: {
      manga: {
        name: 'Death Note',
        slug: 'death_note',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsugumi Ohba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Raito Yagami',
        },
        france: {
          editor: 'Kana',
          nbBooks: 13,
          logo: '/mangas_pictures/death_note.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 13,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLLzTdbq0wiqMfO',
    _score: 3.75,
    _readTimes: 3,
    _source: {
      manga: {
        name: 'Assassination Classroom',
        slug: 'assassination_classroom',
        authors: [
          {
            name: 'Matsui Yuusei',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Korosensei',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 22,
          logo: '/mangas_pictures/assassination_classroom.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/assassinationclassroom.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKMzTdbq0wiqMfI',
    _score: 3.25,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Karate Shoukoushi Kohinata Minoru',
        slug: 'karate_shoukoushi_kohinata_minoru',
        authors: [
          {
            name: 'Yasushi Baba',
          },
        ],
        closeMangas: ['Kenichi'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Kohinata Minoru',
        },
        france: {
          editor: '',
          nbBooks: 25,
          logo: '/mangas_pictures/minoru.webp',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/kohinataminoru.jpg',
          nbChapters: 388,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLgzTdbq0wiqMfQ',
    _score: 3.75,
    _readTimes: 2,
    _source: {
      manga: {
        name: 'Hunter X Hunter',
        slug: 'hunter_x_hunter',
        authors: [
          {
            name: 'Yoshihiro Togashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Gon Freecs',
        },
        france: {
          editor: 'Kana',
          nbBooks: 38,
          logo: '/mangas_pictures/hunter_x_hunter.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/hunterxhunter.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLtzTdbq0wiqMfS',
    _score: 3.75,
    _readTimes: 2,
    _source: {
      manga: {
        name: 'Beelzebub',
        slug: 'beelzebub',
        authors: [
          {
            name: 'Ryūhei Tamura',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Oga Tatsumi',
        },
        france: {
          editor: '',
          nbBooks: 28,
          logo: '/mangas_pictures/beelzebub.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/beelzebub.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMbzTdbq0wiqMfW',
    _score: 3.75,
    _readTimes: 2,
    _source: {
      manga: {
        name: 'Shingeki No Kyojin',
        slug: 'shingeki_no_kyojin',
        frenchName: "L'attaque des titans",
        authors: [
          {
            name: 'Isayama Hajime',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        mainHero: {
          name: 'Eren Jaeger',
        },
        france: {
          editor: '',
          nbBooks: 34,
          logo: '/mangas_pictures/shingeki_no_kyojin.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/japan/shingekinokyojin.jpg',
          nbChapters: 80,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNjzTdbq0wiqMfb',
    _score: 4,
    _readTimes: 3,
    _source: {
      manga: {
        name: 'Claymore',
        slug: 'claymore',
        authors: [
          {
            name: 'Yagu Norihiro',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        logo: '/mangas_pictures/',
        mainHero: {
          name: 'Claire',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 27,
          logo: '/mangas_pictures/claymore.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
        nbBooks: 0,
        nbChapters: 155,
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        publicationEnd: '',
        publicationStart: '',
        type: 'Shonen',
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pOUzTdbq0wiqMfg',
    _score: 4.25,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Ashita No Joe',
        slug: 'ashita_no_joe',
        frenchName: "Ashita No Joe",
        authors: [
          {
            name: 'Takamori Asao',
          },
        ],
        closeMangas: [],
        description: 'sport, boxe',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        logo: '/mangas_pictures/',
        mainHero: {
          name: 'Joe Yabuki',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 12,
          logo: '/mangas_pictures/ashita_no_joe.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
        nbBooks: 20,
        nbChapters: 108,
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        publicationEnd: '',
        publicationStart: '',
        type: 'Shonen',
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pOszTdbq0wiqMfh',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Gamaran',
        slug: 'gamaran',
        authors: [
          {
            name: 'Yōsuke Nakamaru',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        logo: '/mangas_pictures/',
        mainHero: {
          name: 'Gama',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 20,
          logo: '/mangas_pictures/gamaran.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
        nbBooks: 0,
        nbChapters: 0,
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        publicationEnd: '',
        publicationStart: '',
        type: 'Shonen',
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pO0zTdbq0wiqMfi',
    _score: 3,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Terra Formars',
        slug: 'terra_formars',
        authors: [
          {
            name: 'Yu Sagusa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shôkichi Komachi',
        },
        france: {
          editor: '',
          nbBooks: 22,
          logo: '/mangas_pictures/terra_formars.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 172,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pPezTdbq0wiqMfn',
    _score: 3,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'World Trigger',
        slug: 'world_trigger',
        authors: [
          {
            name: 'Daisuke Ashihara',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yûma Kuga',
        },
        france: {
          editor: '',
          nbBooks: 23,
          logo: '/mangas_pictures/world_trigger.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 129,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfq',
    _score: 3.5,
    _readTimes: 3,
    _source: {
      manga: {
        name: 'The Breaker',
        slug: 'the_breaker',
        authors: [
          {
            name: 'Jeon Geuk-Jin',
          },
          {
            name: 'Park Jin-Hwan',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Li Shioon',
        },
        france: {
          editor: '',
          nbBooks: 10,
          logo: '/mangas_pictures/the_breaker.jpg',
        },
        corea: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQizTdbq0wiqMft',
    _score: 2.75,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Asu No Yoichi',
        slug: 'asu_no_yoichi',
        authors: [
          {
            name: 'Yū Minamoto',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Ecchi',
        mainHero: {
          name: 'Yoichi Karasuma',
        },
        france: {
          editor: '',
          nbBooks: 4,
          logo: '/mangas_pictures/asu_no_yoichi.webp',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pCIzTdbq0wiqMe4',
    _score: 3.75,
    _readTimes: 3,
    _source: {
      manga: {
        name: "Ken-ichi, le disciple ultime",
        slug: 'kenichi',
        frenchName: 'Ken-ichi, le disciple ultime',
        authors: [
          {
            name: 'Matsuena Syun',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'martial arts, fight',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shirahama Kenichi',
        },
        france: {
          editor: 'Kurokawa',
          nbBooks: 61,
          logo: '/mangas_pictures/kenichi.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 61,
          logo: '/mangas_pictures/japan.jpg',
          nbChapters: 583,
          publicationEnd: '2014',
          publicationStart: '2002',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJGzTdbq0wiqMfD',
    _score: 4,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Yu-Gi-Oh!',
        slug: 'yu_gi_oh',
        authors: [
          {
            name: 'Kazuki Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yugi Muto',
        },
        france: {
          editor: 'Kana',
          nbBooks: 37,
          logo: '/mangas_pictures/yu_gi_oh.jpeg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 37,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pPdzTdbq0wiqMfm',
    _score: 4,
    _readTimes: 10,
    _source: {
      manga: {
        name: 'Bleach',
        slug: 'bleach',
        authors: [
          {
            name: 'Tite Kubo',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Ichigo Kurosaki',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 74,
          logo: '/mangas_pictures/bleach.webp',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 670,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTHzTdbq0wiqMf6',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Lui Ou Rien !',
        slug: 'lui_ou_rien',
        authors: [
          {
            name: 'Yū Watase',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: '/mangas_pictures/',
        mainHero: {
          name: 'Riiko Izawa',
        },
        japaneseEditor: '',
        frenchEditor: 'Glénat',
        france: {
          editor: '',
          nbBooks: 6,
          logo: '/mangas_pictures/lui_ou_rien.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 6,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJZzTdbq0wiqMfE',
    _score: 4.25,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'All You Need Is Kill',
        slug: 'all_you_need_is_kill',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsugumi Ohba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Keiji Kiriya',
        },
        france: {
          editor: 'Kazé',
          nbBooks: 2,
          logo: '/mangas_pictures/all_you_need_is_kill.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 2,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 17,
          publicationEnd: '2014',
          publicationStart: '2014',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNXzTdbq0wiqMfa',
    _score: 4,
    _readTimes: 5,
    _source: {
      manga: {
        name: 'Crows',
        slug: 'crows',
        authors: [
          {
            name: 'Hiroshi Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Boya Harumichi',
        },
        france: {
          editor: '',
          nbBooks: 26,
          logo: '/mangas_pictures/crows.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pORzTdbq0wiqMff',
    _score: 3.75,
    _readTimes: 2,
    _source: {
      manga: {
        name: 'Détective Conan',
        frenchName: 'Détective Conan',
        slug: 'detective_conan',
        authors: [
          {
            name: 'Gōshō Aoyama',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Shinichi Kudo',
        },
        france: {
          editor: 'Kana',
          nbBooks: 103,
          logo: '/mangas_pictures/detective_conan.jpg',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQezTdbq0wiqMfs',
    _score: 3.25,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Hinomaru Zumou',
        slug: 'hinomaru_zumou',
        authors: [
          {
            name: 'Kawada',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        logo: '/mangas_pictures/',
        mainHero: {
          name: 'Ushio Hinomaru',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          editor: '',
          nbBooks: 28,
          logo: '/mangas_pictures/hinomaru_zumou.jpeg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          nbChapters: 61,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pRczTdbq0wiqMfy',
    _score: 3,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Haikyū!!',
        slug: 'haikyu',
        authors: [
          {
            name: 'Haruichi Furudate',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: 'sport, volleyball, ',
        mainHero: {
          name: 'Shōyō Hinata',
        },
        france: {
          editor: '',
          nbBooks: 45,
          logo: '/mangas_pictures/haikyu.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'The Promised Neverland',
        slug: 'the_promised_neverland',
        authors: [
          {
            name: 'Kaiu Shirai',
          },
          {
            name: 'Posuka Demizu',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Emma',
        },
        france: {
          editor: '',
          nbBooks: 20,
          logo: '/mangas_pictures/promised_neverland.jpg',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 14,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 139,
          publicationEnd: null,
          publicationStart: '2016',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Gunnm',
        slug: 'gunnm',
        authors: [
          {
            name: 'Yukito Kishiro',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Gally',
        },
        france: {
          editor: '',
          nbBooks: 9,
          logo: '/mangas_pictures/gunnm.jpg',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 9,
          logo: '/mangas_pictures/france.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Hajime no Ippo',
        slug: 'hajime_no_ippo',
        authors: [
          {
            name: 'George Morikawa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Ippo Makunouchi',
        },
        france: {
          editor: '',
          nbBooks: 143,
          logo: '/mangas_pictures/hajime_no_ippo.jpg',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 143,
          logo: '/mangas_pictures/hajime_no_ippo.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 3.25,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Jujutsu Kaisen',
        slug: 'jujutsu_kaisen',
        authors: [
          {
            name: 'Gege Akutami',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Yuji Itadori',
        },
        france: {
          editor: '',
          nbBooks: 30,
          logo: '/mangas_pictures/jujutsu_kaisen.jpg',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 30,
          logo: '/mangas_pictures/jujutsu_kaisen.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Vagabond',
        slug: 'vagabond',
        authors: [
          {
            name: 'Takehiko Inoue',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Musashi Miyamoto',
        },
        france: {
          editor: '',
          nbBooks: 37,
          logo: '/mangas_pictures/vagabond.jpg',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 37,
          logo: '/mangas_pictures/vagabond.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Ken le Survivant',
        slug: 'ken_le_survivant',
        authors: [
          {
            name: 'Yoshihiro Togashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Ken le Survivant',
        },
        france: {
          editor: '',
          nbBooks: 27,
          logo: '/mangas_pictures/ken_le_survivant.jpg',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 27,
          logo: '/mangas_pictures/ken_le_survivant.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 3.5,
    _readTimes: 1,
    _source: {
      manga: {
        name: 'Gen d\'Hiroshima',
        slug: 'gen_d_hiroshima',
        authors: [
          {
            name: 'Kazuo Umezu',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Gen d\'Hiroshima',
        },
        france: {
          editor: '',
          nbBooks: 10,
          logo: '/mangas_pictures/gen_d_hiroshima.jpg',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 10,
          logo: '/mangas_pictures/gen_d_hiroshima.jpg',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
];
