import { Movie } from './movies_1';

export const moviesPage3: Movie[] = [
  {
    title: 'Kingsman: The Golden Circle',
    director: 'Matthew Vaughn',
    actors: [{ name: 'Taron Egerton' }],
    coverUrl: '/movies_pictures/kingsman_the_golden_circle.jpg',
    releaseDate: '2017-09-22',
    rating: 3,
    length: 141,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Death Note',
    director: 'Adam Wingard',
    actors: [{ name: 'Nat Wolff' }],
    coverUrl: '/movies_pictures/281716-death-note-0-150-0-225-crop.jpg',
    releaseDate: '2017-08-25',
    rating: 2.5,
    length: 101,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "The Hitman's Bodyguard",
    director: 'Patrick Hughes',
    actors: [{ name: 'Ryan Reynolds' }],
    coverUrl: '/movies_pictures/hitman_bodyguard.jpg',
    releaseDate: '2017-08-18',
    rating: 3,
    length: 118,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: "The Hitman's Bodyguard",
  },
  {
    title: 'Valerian and the City of a Thousand Planets',
    director: 'Luc Besson',
    actors: [{ name: 'Dane DeHaan' }],
    coverUrl:
      '/movies_pictures/269458-valerian-and-the-city-of-a-thousand-planets-0-150-0-225-crop.jpg',
    releaseDate: '2017-07-21',
    rating: 3.25,
    length: 137,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Atomic Blonde',
    director: 'David Leitch',
    actors: [{ name: 'Charlize Theron' }],
    coverUrl: '/movies_pictures/270477-atomic-blonde-0-150-0-225-crop.jpg',
    releaseDate: '2017-07-28',
    rating: 3,
    length: 115,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Baby Driver',
    director: 'Edgar Wright',
    actors: [{ name: 'Ansel Elgort' }],
    coverUrl: '/movies_pictures/268950-baby-driver-0-150-0-225-crop.jpg',
    releaseDate: '2017-06-28',
    rating: 4,
    length: 113,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Aftermath',
    director: 'Elliott Lester',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/aftermath.jpg',
    releaseDate: '2017-04-07',
    rating: 3.5,
    length: 94,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Il a Déjà Tes Yeux',
    director: 'Lucien Jean-Baptiste',
    actors: [{ name: 'Lucien Jean-Baptiste' }],
    coverUrl:
      '/movies_pictures/333161-he-even-has-your-eyes-0-150-0-225-crop.jpg',
    releaseDate: '2016-12-07',
    rating: 3,
    length: 98,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },

  {
    title: 'Un choix',
    director: 'Ross Katz',
    actors: [{ name: 'Benjamin Walker' }],
    coverUrl: '/movies_pictures/258147-the-choice-0-150-0-225-crop.jpg',
    releaseDate: '2016-02-05',
    rating: 3.75,
    length: 111,
    genre: 'Romance',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Swiss Army Man',
    director: 'Dan Kwan, Daniel Scheinert',
    actors: [{ name: 'Paul Dano' }],
    coverUrl: '/movies_pictures/swiss_army_man.jpg',
    releaseDate: '2016-07-01',
    rating: 3.25,
    length: 97,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "Comment c'est loin",
    director: 'Orelsan',
    actors: [{ name: 'Orelsan' }],
    coverUrl: '/movies_pictures/302633-comment-c-est-loin-0-150-0-225-crop.jpg',
    releaseDate: '2015-12-09',
    rating: 3.25,
    length: 95,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Creed',
    director: 'Ryan Coogler',
    actors: [{ name: 'Michael B. Jordan' }],
    coverUrl: '/movies_pictures/239260-creed-0-150-0-225-crop.jpg',
    releaseDate: '2015-11-25',
    rating: 4,
    length: 133,
    genre: 'Drama',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Demolition',
    director: 'Jean-Marc Vallée',
    actors: [{ name: 'Jake Gyllenhaal' }],
    coverUrl: '/movies_pictures/demolition.jpg',
    releaseDate: '2016-04-08',
    rating: 3.5,
    length: 101,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Visit',
    director: 'M. Night Shyamalan',
    actors: [{ name: 'Olivia DeJonge' }],
    coverUrl: '/movies_pictures/225437-the-visit-0-150-0-225-crop.jpg',
    releaseDate: '2015-09-11',
    rating: 2.5,
    length: 94,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '2015-09-11',
  },
  {
    title: 'Le Labyrinthe : La Terre Brûlée',
    director: 'Wes Ball',
    actors: [{ name: "Dylan O'Brien" }],
    coverUrl:
      '/movies_pictures/221232-maze-runner-the-scorch-trials-0-150-0-225-crop.jpg',
    releaseDate: '2015-09-18',
    rating: 2.5,
    length: 132,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Room',
    director: 'Lenny Abrahamson',
    actors: [{ name: 'Brie Larson' }],
    coverUrl: '/movies_pictures/room.jpg',
    releaseDate: '2016-01-22',
    rating: 3.5,
    length: 118,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Pixels',
    director: 'Chris Columbus',
    actors: [{ name: 'Adam Sandler' }],
    coverUrl: '/movies_pictures/181118-pixels-0-150-0-225-crop.jpg',
    releaseDate: '2015-07-24',
    rating: 3.25,
    length: 105,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'La rage au ventre',
    director: 'Antoine Fuqua',
    actors: [{ name: 'Jake Gyllenhaal' }],
    coverUrl: '/movies_pictures/234208-southpaw-0-150-0-225-crop.jpg',
    releaseDate: '2015-07-24',
    rating: 3.5,
    length: 124,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Diversion',
    director: 'Glenn Ficarra, John Requa',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/180414-focus-0-150-0-225-crop.jpg',
    releaseDate: '2015-02-27',
    rating: 3.75,
    length: 105,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Cinquante Nuances de Grey',
    director: 'Sam Taylor-Johnson',
    actors: [{ name: 'Dakota Johnson' }],
    coverUrl: '/movies_pictures/cinquante_nuances_de_grey.jpg',
    releaseDate: '2015-02-13',
    rating: 2,
    length: 125,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Knock Knock',
    director: 'Eli Roth',
    actors: [{ name: 'Keanu Reeves' }],
    coverUrl: '/movies_pictures/186877-knock-knock-0-150-0-225-crop.jpg',
    releaseDate: '2015-10-09',
    rating: 2.5,
    length: 99,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '2025-04-09',
  },
  {
    title: 'Kingsman : Services Secrets',
    director: 'Matthew Vaughn',
    actors: [{ name: 'Taron Egerton' }],
    coverUrl:
      '/movies_pictures/148200-kingsman-the-secret-service-0-150-0-225-crop.jpg',
    releaseDate: '2015-02-13',
    rating: 4.5,
    length: 129,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Interstellar',
    director: 'Christopher Nolan',
    actors: [{ name: 'Matthew McConaughey' }],
    coverUrl: '/movies_pictures/117621-interstellar-0-150-0-225-crop.jpg',
    releaseDate: '2014-11-07',
    rating: 3.5,
    length: 169,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Gone Girl',
    director: 'David Fincher',
    actors: [{ name: 'Ben Affleck' }],
    coverUrl: '/movies_pictures/149857-gone-girl-0-150-0-225-crop.jpg',
    releaseDate: '2014-10-03',
    rating: 3,
    length: 149,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Birdman',
    director: 'Alejandro G. Iñárritu',
    actors: [{ name: 'Michael Keaton' }],
    coverUrl: '/movies_pictures/139795-birdman-0-150-0-225-crop.jpg',
    releaseDate: '2014-10-17',
    rating: 3,
    length: 119,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },

  {
    title: 'Lucy',
    director: 'Luc Besson',
    actors: [{ name: 'Scarlett Johansson' }],
    coverUrl: '/movies_pictures/168860-lucy-0-150-0-225-crop.jpg',
    releaseDate: '2014-07-25',
    rating: 4.5,
    length: 89,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Le médaillon',
    director: 'Gordon Chan',
    actors: [{ name: 'Jackie Chan' }],
    coverUrl: '/movies_pictures/46064-the-medallion-0-1000-0-1500-crop.jpg',
    releaseDate: '2003-02-05',
    rating: 3,
    length: 88,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Smoking',
    director: 'Kevin Donovan',
    actors: [{ name: 'Jackie Chan' }],
    coverUrl: '/movies_pictures/45912-the-tuxedo-0-1000-0-1500-crop.jpg',
    releaseDate: '2002-02-05',
    rating: 3,
    length: 98,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Brice de Nice',
    director: 'James Huth',
    actors: [{ name: 'Jean Dujardin' }],
    coverUrl: '/movies_pictures/41053-the-brice-man-0-150-0-225-crop.jpg',
    releaseDate: '2005-02-02',
    rating: 3,
    length: 94,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Brick',
    director: 'Rian Johnson',
    actors: [{ name: 'Joseph Gordon-Levitt' }],
    coverUrl: '/movies_pictures/brick.jpg',
    releaseDate: '2005-01-20',
    rating: 3.25,
    length: 110,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '2025-07-15',
  },
  {
    title: 'La guerre des mondes',
    director: 'Steven Spielberg',
    actors: [{ name: 'Tom Cruise' }],
    coverUrl: '/movies_pictures/war_of_the_worlds.jpg',
    releaseDate: '2005-06-29',
    rating: 3.5,
    length: 116,
    genre: 'Science Fiction',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'La ligue des gentlemen extraordinaires',
    director: 'Stephen Norrington',
    actors: [{ name: 'Sean Connery' }],
    coverUrl: '/movies_pictures/league_of_extraordinary_gentlemen.jpg',
    releaseDate: '2003-07-11',
    rating: 3.75,
    length: 110,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'La tour Montparnasse infernale',
    director: 'Charles Nemes',
    actors: [{ name: 'Albert Dupontel' }],
    coverUrl: '/movies_pictures/la_tour_montparnasse_infernale.jpg',
    releaseDate: '2001-10-31',
    rating: 3.5,
    length: 90,
    genre: 'Comedy',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Spaceballs',
    director: 'Mel Brooks',
    actors: [{ name: 'Mel Brooks' }],
    coverUrl: '/movies_pictures/51203-spaceballs-0-150-0-225-crop.jpg',
    releaseDate: '1987-06-24',
    rating: 3.5,
    length: 96,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Les Incorruptibles',
    director: 'Brian De Palma',
    actors: [{ name: 'Kevin Costner' }],
    coverUrl:
      '/movies_pictures/bDcqwNTwhEDfQHFj7jpt18N6Giz-0-150-0-225-crop.jpg',
    releaseDate: '1987-06-03',
    rating: 3,
    length: 119,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Dirty Dancing',
    director: 'Emile Ardolino',
    actors: [{ name: 'Patrick Swayze' }],
    coverUrl: '/movies_pictures/51962-dirty-dancing-0-150-0-225-crop.jpg',
    releaseDate: '1987-08-21',
    rating: 3.5,
    length: 100,
    genre: 'Romance',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Over the Top : Le bras de fer',
    director: 'Menahem Golan',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/50772-over-the-top-0-150-0-225-crop.jpg',
    releaseDate: '1987-02-13',
    rating: 3.5,
    length: 93,
    genre: 'Drama',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Commando',
    director: 'Mark L. Lester',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/45703-commando-0-150-0-225-crop.jpg',
    releaseDate: '1985-10-04',
    rating: 3.25,
    length: 90,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Le flic de Beverly Hills',
    director: 'Martin Brest',
    actors: [{ name: 'Eddie Murphy' }],
    coverUrl: '/movies_pictures/le_flic_de_beverly_hills.jpg',
    releaseDate: '1984-12-05',
    rating: 3,
    length: 105,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Karate Kid',
    director: 'John G. Avildsen',
    actors: [{ name: 'Ralph Macchio' }],
    coverUrl: '/movies_pictures/50718-the-karate-kid-0-150-0-225-crop.jpg',
    releaseDate: '1984-06-22',
    rating: 3.25,
    length: 126,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Scarface',
    director: 'Brian De Palma',
    actors: [{ name: 'Al Pacino' }],
    coverUrl: '/movies_pictures/71wr6ah15sL._UF1000,1000_QL80_.jpg',
    releaseDate: '1983-12-09',
    rating: 3.25,
    length: 170,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Dead Zone',
    director: 'David Cronenberg',
    actors: [{ name: 'Christopher Walken' }],
    coverUrl: '/movies_pictures/45398-the-dead-zone-0-150-0-225-crop.jpg',
    releaseDate: '1983-10-21',
    rating: 3.5,
    length: 103,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
