import { Movie } from "./movies";

export const moviesPage3: Movie[] = [
  {
    title: "Justice League",
    director: "Zack Snyder",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies/justice_league.jpg",
    releaseDate: "2017-11-17",
    rating: 0,
    length: 120,
    genre: "Action",
  },
  {
    title: "Thor: Ragnarok",
    director: "Taika Waititi",
    actors: [{ name: "Chris Hemsworth" }],
    coverUrl: "/movies/thor_ragnarok.jpg",
    releaseDate: "2017-11-03",
    rating: 0,
    length: 130,
    genre: "Action",
  },
  {
    title: "Kingsman: The Golden Circle",
    director: "Matthew Vaughn",
    actors: [{ name: "Taron Egerton" }],
    coverUrl: "/movies/kingsman_golden_circle.jpg",
    releaseDate: "2017-09-22",
    rating: 0,
    length: 141,
    genre: "Action",
  },
  {
    title: "Death Note",
    director: "Adam Wingard",
    actors: [{ name: "Nat Wolff" }],
    coverUrl: "/movies/death_note_movie.jpg",
    releaseDate: "2017-08-25",
    rating: 0,
    length: 101,
    genre: "Thriller",
  },
  {
    title: "The Hitman's Bodyguard",
    director: "Patrick Hughes",
    actors: [{ name: "Ryan Reynolds" }],
    coverUrl: "/movies/hitmans_bodyguard.jpg",
    releaseDate: "2017-08-18",
    rating: 0,
    length: 118,
    genre: "Action",
  },
  {
    title: "Valerian and the City of a Thousand Planets",
    director: "Luc Besson",
    actors: [{ name: "Dane DeHaan" }],
    coverUrl: "/movies/valerian.jpg",
    releaseDate: "2017-07-21",
    rating: 0,
    length: 137,
    genre: "Science Fiction",
  },
  {
    title: "Spider-Man: Homecoming",
    director: "Jon Watts",
    actors: [{ name: "Tom Holland" }],
    coverUrl: "/movies/spider_man_homecoming.jpg",
    releaseDate: "2017-07-07",
    rating: 0,
    length: 133,
    genre: "Action",
  },
  {
    title: "Cars 3",
    director: "Brian Fee",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies/cars_3.jpg",
    releaseDate: "2016-06-16",
    rating: 0,
    length: 102,
    genre: "Animation",
  },
  {
    title: "Wonder Woman",
    director: "Patty Jenkins",
    actors: [{ name: "Gal Gadot" }],
    coverUrl: "/movies/wonder_woman.jpg",
    releaseDate: "2017-06-02",
    rating: 0,
    length: 141,
    genre: "Action",
  },
  {
    title: "Guardians of the Galaxy Vol. 2",
    director: "James Gunn",
    actors: [{ name: "Chris Pratt" }],
    coverUrl: "/movies/guardians_vol_2.jpg",
    releaseDate: "2017-05-05",
    rating: 0,
    length: 136,
    genre: "Action",
  },
  {
    title: "The Fate of the Furious",
    director: "F. Gary Gray",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/fate_furious.jpg",
    releaseDate: "2017-04-14",
    rating: 0,
    length: 136,
    genre: "Action",
  },
  {
    title: "The Boss Baby",
    director: "Tom McGrath",
    actors: [{ name: "Alec Baldwin" }],
    coverUrl: "/movies/boss_baby.jpg",
    releaseDate: "2017-03-31",
    rating: 0,
    length: 97,
    genre: "Animation",
  },
  {
    title: "Atomic Blonde",
    director: "David Leitch",
    actors: [{ name: "Charlize Theron" }],
    coverUrl: "/movies/atomic_blonde.jpg",
    releaseDate: "2017-07-28",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "Baby Driver",
    director: "Edgar Wright",
    actors: [{ name: "Ansel Elgort" }],
    coverUrl: "/movies/baby_driver.jpg",
    releaseDate: "2017-06-28",
    rating: 0,
    length: 113,
    genre: "Action",
  },
  {
    title: "Aftermath",
    director: "Elliott Lester",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/aftermath.jpg",
    releaseDate: "2017-04-07",
    rating: 0,
    length: 94,
    genre: "Drama",
  },
  {
    title: "Beauty and the Beast",
    director: "Bill Condon",
    actors: [{ name: "Emma Watson" }],
    coverUrl: "/movies/beauty_beast.jpg",
    releaseDate: "2017-03-17",
    rating: 0,
    length: 129,
    genre: "Fantasy",
  },
  {
    title: "Logan",
    director: "James Mangold",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/logan.jpg",
    releaseDate: "2017-03-03",
    rating: 0,
    length: 137,
    genre: "Action",
  },
  {
    title: "John Wick: Chapter 2",
    director: "Chad Stahelski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/john_wick_2.jpg",
    releaseDate: "2017-02-10",
    rating: 0,
    length: 122,
    genre: "Action",
  },
  {
    title: "Rogue One: A Star Wars Story",
    director: "Gareth Edwards",
    actors: [{ name: "Felicity Jones" }],
    coverUrl: "/movies/rogue_one.jpg",
    releaseDate: "2016-12-16",
    rating: 0,
    length: 133,
    genre: "Science Fiction",
  },
  {
    title: "Fantastic Beasts and Where to Find Them",
    director: "David Yates",
    actors: [{ name: "Eddie Redmayne" }],
    coverUrl: "/movies/fantastic_beasts.jpg",
    releaseDate: "2016-11-18",
    rating: 0,
    length: 133,
    genre: "Fantasy",
  },
  {
    title: "Doctor Strange",
    director: "Scott Derrickson",
    actors: [{ name: "Benedict Cumberbatch" }],
    coverUrl: "/movies/doctor_strange.jpg",
    releaseDate: "2016-11-04",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "Black Mirror: Shut Up and Dance",
    director: "James Watkins",
    actors: [{ name: "Alex Lawther" }],
    coverUrl: "/movies/black_mirror_shut_up.jpg",
    releaseDate: "2016-10-21",
    rating: 0,
    length: 52,
    genre: "Science Fiction",
  },
  {
    title: "Black Mirror: Nosedive",
    director: "Joe Wright",
    actors: [{ name: "Bryce Dallas Howard" }],
    coverUrl: "/movies/black_mirror_nosedive.jpg",
    releaseDate: "2016-10-21",
    rating: 0,
    length: 63,
    genre: "Science Fiction",
  },
  {
    title: "Moana",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Auli'i Cravalho" }],
    coverUrl: "/movies/moana.jpg",
    releaseDate: "2016-11-23",
    rating: 0,
    length: 107,
    genre: "Animation",
  },
  {
    title: "Jack Reacher: Never Go Back",
    director: "Edward Zwick",
    actors: [{ name: "Tom Cruise" }],
    coverUrl: "/movies/jack_reacher_2.jpg",
    releaseDate: "2016-10-21",
    rating: 0,
    length: 118,
    genre: "Action",
  },
  {
    title: "Split",
    director: "M. Night Shyamalan",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies/split.jpg",
    releaseDate: "2017-01-20",
    rating: 0,
    length: 117,
    genre: "Thriller",
  },
  {
    title: "La La Land",
    director: "Damien Chazelle",
    actors: [{ name: "Ryan Gosling" }],
    coverUrl: "/movies/la_la_land.jpg",
    releaseDate: "2016-12-09",
    rating: 0,
    length: 128,
    genre: "Romance",
  },
  {
    title: "He Even Has Your Eyes",
    director: "Lucien Jean-Baptiste",
    actors: [{ name: "Lucien Jean-Baptiste" }],
    coverUrl: "/movies/he_even_has_your_eyes.jpg",
    releaseDate: "2016-12-07",
    rating: 0,
    length: 98,
    genre: "Comedy",
  },
  {
    title: "Suicide Squad",
    director: "David Ayer",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/suicide_squad.jpg",
    releaseDate: "2016-08-05",
    rating: 0,
    length: 123,
    genre: "Action",
  },
  {
    title: "Jason Bourne",
    director: "Paul Greengrass",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/jason_bourne.jpg",
    releaseDate: "2016-07-29",
    rating: 0,
    length: 123,
    genre: "Action",
  },
  {
    title: "Now You See Me 2",
    director: "Jon M. Chu",
    actors: [{ name: "Jesse Eisenberg" }],
    coverUrl: "/movies/now_you_see_me_2.jpg",
    releaseDate: "2016-06-10",
    rating: 0,
    length: 129,
    genre: "Thriller",
  },
  {
    title: "X-Men: Apocalypse",
    director: "Bryan Singer",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies/xmen_apocalypse.jpg",
    releaseDate: "2016-05-27",
    rating: 0,
    length: 144,
    genre: "Action",
  },
  {
    title: "Captain America: Civil War",
    director: "Anthony Russo, Joe Russo",
    actors: [{ name: "Chris Evans" }],
    coverUrl: "/movies/captain_america_civil_war.jpg",
    releaseDate: "2016-05-06",
    rating: 0,
    length: 147,
    genre: "Action",
  },
  {
    title: "Batman v Superman: Dawn of Justice",
    director: "Zack Snyder",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies/batman_v_superman.jpg",
    releaseDate: "2016-03-25",
    rating: 0,
    length: 151,
    genre: "Action",
  },
  {
    title: "Allegiant",
    director: "Robert Schwentke",
    actors: [{ name: "Shailene Woodley" }],
    coverUrl: "/movies/allegiant.jpg",
    releaseDate: "2016-03-18",
    rating: 0,
    length: 121,
    genre: "Action",
  },
  {
    title: "Deadpool",
    director: "Tim Miller",
    actors: [{ name: "Ryan Reynolds" }],
    coverUrl: "/movies/deadpool.jpg",
    releaseDate: "2016-02-12",
    rating: 0,
    length: 108,
    genre: "Action",
  },
  {
    title: "The Choice",
    director: "Ross Katz",
    actors: [{ name: "Benjamin Walker" }],
    coverUrl: "/movies/the_choice.jpg",
    releaseDate: "2016-02-05",
    rating: 0,
    length: 111,
    genre: "Romance",
  },
  {
    title: "Swiss Army Man",
    director: "Dan Kwan, Daniel Scheinert",
    actors: [{ name: "Paul Dano" }],
    coverUrl: "/movies/swiss_army_man.jpg",
    releaseDate: "2016-07-01",
    rating: 0,
    length: 97,
    genre: "Comedy",
  },
  {
    title: "Star Wars: The Force Awakens",
    director: "J.J. Abrams",
    actors: [{ name: "Daisy Ridley" }],
    coverUrl: "/movies/star_wars_force_awakens.jpg",
    releaseDate: "2015-12-18",
    rating: 0,
    length: 138,
    genre: "Science Fiction",
  },
  {
    title: "Comment c'est loin",
    director: "Orelsan",
    actors: [{ name: "Orelsan" }],
    coverUrl: "/movies/comment_cest_loin.jpg",
    releaseDate: "2015-12-09",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Creed",
    director: "Ryan Coogler",
    actors: [{ name: "Michael B. Jordan" }],
    coverUrl: "/movies/creed.jpg",
    releaseDate: "2015-11-25",
    rating: 0,
    length: 133,
    genre: "Drama",
  },
  {
    title: "Spectre",
    director: "Sam Mendes",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies/spectre.jpg",
    releaseDate: "2015-11-06",
    rating: 0,
    length: 148,
    genre: "Action",
  },
  {
    title: "Demolition",
    director: "Jean-Marc Vallée",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies/demolition.jpg",
    releaseDate: "2016-04-08",
    rating: 0,
    length: 101,
    genre: "Drama",
  },
  {
    title: "The Visit",
    director: "M. Night Shyamalan",
    actors: [{ name: "Olivia DeJonge" }],
    coverUrl: "/movies/the_visit.jpg",
    releaseDate: "2015-09-11",
    rating: 0,
    length: 94,
    genre: "Horror",
  },
  {
    title: "Maze Runner: The Scorch Trials",
    director: "Wes Ball",
    actors: [{ name: "Dylan O'Brien" }],
    coverUrl: "/movies/maze_runner_scorch.jpg",
    releaseDate: "2015-09-18",
    rating: 0,
    length: 132,
    genre: "Action",
  },
  {
    title: "Room",
    director: "Lenny Abrahamson",
    actors: [{ name: "Brie Larson" }],
    coverUrl: "/movies/room.jpg",
    releaseDate: "2016-01-22",
    rating: 0,
    length: 118,
    genre: "Drama",
  },
  {
    title: "Fantastic Four",
    director: "Josh Trank",
    actors: [{ name: "Miles Teller" }],
    coverUrl: "/movies/fantastic_four.jpg",
    releaseDate: "2015-08-07",
    rating: 0,
    length: 100,
    genre: "Action",
  },
  {
    title: "Pixels",
    director: "Chris Columbus",
    actors: [{ name: "Adam Sandler" }],
    coverUrl: "/movies/pixels.jpg",
    releaseDate: "2015-07-24",
    rating: 0,
    length: 105,
    genre: "Comedy",
  },
  {
    title: "Ant-Man",
    director: "Peyton Reed",
    actors: [{ name: "Paul Rudd" }],
    coverUrl: "/movies/ant_man.jpg",
    releaseDate: "2015-07-17",
    rating: 0,
    length: 117,
    genre: "Action",
  },
  {
    title: "Terminator Genisys",
    director: "Alan Taylor",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/terminator_genisys.jpg",
    releaseDate: "2015-07-01",
    rating: 0,
    length: 126,
    genre: "Action",
  },
  {
    title: "Inside Out",
    director: "Pete Docter",
    actors: [{ name: "Amy Poehler" }],
    coverUrl: "/movies/inside_out.jpg",
    releaseDate: "2015-06-19",
    rating: 0,
    length: 95,
    genre: "Animation",
  },
  {
    title: "Avengers: Age of Ultron",
    director: "Joss Whedon",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/avengers_age_ultron.jpg",
    releaseDate: "2015-05-01",
    rating: 0,
    length: 141,
    genre: "Action",
  },
  {
    title: "Southpaw",
    director: "Antoine Fuqua",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies/southpaw.jpg",
    releaseDate: "2015-07-24",
    rating: 0,
    length: 124,
    genre: "Drama",
  },
  {
    title: "Insurgent",
    director: "Robert Schwentke",
    actors: [{ name: "Shailene Woodley" }],
    coverUrl: "/movies/insurgent.jpg",
    releaseDate: "2015-03-20",
    rating: 0,
    length: 119,
    genre: "Action",
  },
  {
    title: "Furious 7",
    director: "James Wan",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/furious_7.jpg",
    releaseDate: "2015-04-03",
    rating: 0,
    length: 137,
    genre: "Action",
  },
  {
    title: "Focus",
    director: "Glenn Ficarra, John Requa",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/focus.jpg",
    releaseDate: "2015-02-27",
    rating: 0,
    length: 105,
    genre: "Crime",
  },
  {
    title: "Fifty Shades of Grey",
    director: "Sam Taylor-Johnson",
    actors: [{ name: "Dakota Johnson" }],
    coverUrl: "/movies/fifty_shades_grey.jpg",
    releaseDate: "2015-02-13",
    rating: 0,
    length: 125,
    genre: "Drama",
  },
  {
    title: "Knock Knock",
    director: "Eli Roth",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/knock_knock.jpg",
    releaseDate: "2015-10-09",
    rating: 0,
    length: 99,
    genre: "Thriller",
  },
  {
    title: "Taken 3",
    director: "Olivier Megaton",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies/taken_3.jpg",
    releaseDate: "2015-01-09",
    rating: 0,
    length: 109,
    genre: "Action",
  },
  {
    title: "Black Mirror: White Christmas",
    director: "Carl Tibbetts",
    actors: [{ name: "Jon Hamm" }],
    coverUrl: "/movies/black_mirror_white_christmas.jpg",
    releaseDate: "2014-12-16",
    rating: 0,
    length: 74,
    genre: "Science Fiction",
  },
  {
    title: "Kingsman: The Secret Service",
    director: "Matthew Vaughn",
    actors: [{ name: "Taron Egerton" }],
    coverUrl: "/movies/kingsman_secret_service.jpg",
    releaseDate: "2015-02-13",
    rating: 0,
    length: 129,
    genre: "Action",
  },
  {
    title: "The Hunger Games: Mockingjay – Part 1",
    director: "Francis Lawrence",
    actors: [{ name: "Jennifer Lawrence" }],
    coverUrl: "/movies/hunger_games_mockingjay_1.jpg",
    releaseDate: "2014-11-21",
    rating: 0,
    length: 123,
    genre: "Action",
  },
  {
    title: "Interstellar",
    director: "Christopher Nolan",
    actors: [{ name: "Matthew McConaughey" }],
    coverUrl: "/movies/interstellar.jpg",
    releaseDate: "2014-11-07",
    rating: 0,
    length: 169,
    genre: "Science Fiction",
  },
  {
    title: "Big Hero 6",
    director: "Don Hall, Chris Williams",
    actors: [{ name: "Ryan Potter" }],
    coverUrl: "/movies/big_hero_6.jpg",
    releaseDate: "2014-11-07",
    rating: 0,
    length: 102,
    genre: "Animation",
  },
  {
    title: "Gone Girl",
    director: "David Fincher",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies/gone_girl.jpg",
    releaseDate: "2014-10-03",
    rating: 0,
    length: 149,
    genre: "Thriller",
  },
  {
    title: "John Wick",
    director: "Chad Stahelski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/john_wick.jpg",
    releaseDate: "2014-10-24",
    rating: 0,
    length: 101,
    genre: "Action",
  },
  {
    title: "The Maze Runner",
    director: "Wes Ball",
    actors: [{ name: "Dylan O'Brien" }],
    coverUrl: "/movies/maze_runner.jpg",
    releaseDate: "2014-09-19",
    rating: 0,
    length: 113,
    genre: "Action",
  },
  {
    title: "Birdman or (The Unexpected Virtue of Ignorance)",
    director: "Alejandro G. Iñárritu",
    actors: [{ name: "Michael Keaton" }],
    coverUrl: "/movies/birdman.jpg",
    releaseDate: "2014-10-17",
    rating: 0,
    length: 119,
    genre: "Drama",
  },
  {
    title: "Sin City: A Dame to Kill For",
    director: "Frank Miller, Robert Rodriguez",
    actors: [{ name: "Mickey Rourke" }],
    coverUrl: "/movies/sin_city_dame_kill.jpg",
    releaseDate: "2014-08-22",
    rating: 0,
    length: 102,
    genre: "Crime",
  },
  {
    title: "Guardians of the Galaxy",
    director: "James Gunn",
    actors: [{ name: "Chris Pratt" }],
    coverUrl: "/movies/guardians_galaxy.jpg",
    releaseDate: "2014-08-01",
    rating: 0,
    length: 121,
    genre: "Action",
  },
  {
    title: "Lucy",
    director: "Luc Besson",
    actors: [{ name: "Scarlett Johansson" }],
    coverUrl: "/movies/lucy.jpg",
    releaseDate: "2014-07-25",
    rating: 0,
    length: 89,
    genre: "Action",
  },
  {
    title: "Transformers: Age of Extinction",
    director: "Michael Bay",
    actors: [{ name: "Mark Wahlberg" }],
    coverUrl: "/movies/transformers_age_extinction.jpg",
    releaseDate: "2014-06-27",
    rating: 0,
    length: 165,
    genre: "Action",
  },
];