import { Movie } from './movies_1';

export const moviesAnimated2: Movie[] = [
  {
    title: 'Les Indestructibles',
    director: 'Brad Bird',
    actors: [{ name: 'Craig T. Nelson' }],
    coverUrl: '/movies_pictures/46806-the-incredibles-0-150-0-225-crop.jpg',
    releaseDate: '2004-11-05',
    rating: 4.5,
    length: 115,
    genre: 'Animation',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Les Indestructibles 2',
    director: 'Brad Bird',
    actors: [
      {
        name: 'Craig T. Nelson',
      },
    ],
    coverUrl: '/movies_pictures/184061-incredibles-2-0-150-0-225-crop.jpg',
    releaseDate: '2018-06-15',
    rating: 3.5,
    length: 118,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le monde de Nemo',
    director: 'Andrew Stanton',
    actors: [{ name: 'Albert Brooks' }],
    coverUrl: '/movies_pictures/monde_de_nemo.webp',
    releaseDate: '2003-05-30',
    rating: 3.5,
    length: 100,
    genre: 'Animation',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Monstres et Cie',
    director: 'Pete Docter',
    actors: [{ name: 'John Goodman' }],
    coverUrl: '/movies_pictures/monstres_et_compagnie.jpg',
    releaseDate: '2001-11-02',
    rating: 3.5,
    length: 92,
    genre: 'Animation',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Toy Story',
    director: 'John Lasseter',
    actors: [{ name: 'Tom Hanks' }],
    coverUrl: '/movies_pictures/51290-toy-story-0-150-0-225-crop.jpg',
    releaseDate: '1995-11-22',
    rating: 3.5,
    length: 81,
    genre: 'Animation',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Toy Story 2',
    director: 'John Lasseter',
    actors: [{ name: 'Tom Hanks' }],
    coverUrl: '/movies_pictures/51289-toy-story-2-0-150-0-225-crop.jpg',
    releaseDate: '1999-11-24',
    rating: 3.5,
    length: 92,
    genre: 'Animation',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Toy Story 3',
    director: 'Lee Unkrich',
    actors: [{ name: 'Tom Hanks' }],
    coverUrl: '/movies_pictures/46458-toy-story-3-0-150-0-225-crop.jpg',
    releaseDate: '2010-06-18',
    rating: 3,
    length: 103,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'South Park, le Film',
    director: 'Trey Parker',
    actors: [{ name: 'Trey Parker' }],
    coverUrl:
      '/movies_pictures/47125-south-park-bigger-longer-uncut-0-150-0-225-crop.jpg',
    releaseDate: '1999-06-30',
    rating: 3,
    length: 81,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Tarzan',
    director: 'Chris Buck, Kevin Lima',
    actors: [{ name: 'Tony Goldwyn' }],
    coverUrl: '/movies_pictures/tarzan.jpg',
    releaseDate: '1999-06-18',
    rating: 4.25,
    length: 88,
    genre: 'Animation',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Fourmiz',
    director: 'Eric Darnell, Tim Johnson',
    actors: [{ name: 'Woody Allen' }],
    coverUrl: '/movies_pictures/47511-antz-0-150-0-225-crop.jpg',
    releaseDate: '1998-10-02',
    rating: 3,
    length: 83,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Mulan',
    director: 'Tony Bancroft, Barry Cook',
    actors: [{ name: 'Ming-Na Wen' }],
    coverUrl: '/movies_pictures/266675-mulan-0-150-0-225-crop.jpg',
    releaseDate: '1998-06-19',
    rating: 3,
    length: 88,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Princesse Mononoké',
    director: 'Hayao Miyazaki',
    actors: [{ name: 'Yôji Matsuda' }],
    coverUrl:
      '/movies_pictures/mNqZOtJIQfFQPjo3hmYLIn8Qqhf-0-150-0-225-crop.jpg',
    releaseDate: '1997-07-12',
    rating: 3.25,
    length: 134,
    genre: 'Animation',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Hercule',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Tate Donovan' }],
    coverUrl: '/movies_pictures/44838-hercules-0-150-0-225-crop.jpg',
    releaseDate: '1997-06-27',
    rating: 3,
    length: 93,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Pocahontas',
    director: 'Mike Gabriel, Eric Goldberg',
    actors: [{ name: 'Irene Bedard' }],
    coverUrl: '/movies_pictures/pocahontas.jpg',
    releaseDate: '1995-06-23',
    rating: 3,
    length: 81,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Space Jam',
    director: 'Joe Pytka',
    actors: [{ name: 'Michael Jordan' }],
    coverUrl: '/movies_pictures/space_jam.jpg',
    releaseDate: '1996-11-15',
    rating: 3,
    length: 88,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le Roi Lion',
    director: 'Roger Allers, Rob Minkoff',
    actors: [{ name: 'Matthew Broderick' }],
    coverUrl: '/movies_pictures/le roi lion.jpg',
    releaseDate: '1994-06-24',
    rating: 3.25,
    length: 88,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Aladdin',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Scott Weinger' }],
    coverUrl: '/movies_pictures/aladdin_film.jpg',
    releaseDate: '1992-11-25',
    rating: 4.5,
    length: 90,
    genre: 'Animation',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'La petite sirène',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Jodi Benson' }],
    coverUrl: '/movies_pictures/la_petite_sirene.jpg',
    releaseDate: '1989-11-17',
    rating: 3,
    length: 83,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Peter Pan',
    director: 'Clyde Geronimi, Wilfred Jackson, Hamilton Luske',
    actors: [{ name: 'Bobby Driscoll' }],
    coverUrl: '/movies_pictures/45983-peter-pan-0-150-0-225-crop.jpg',
    releaseDate: '1953-02-05',
    rating: 3.25,
    length: 77,
    genre: 'Animation',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Pinocchio',
    director:
      'Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen',
    actors: [{ name: 'Dickie Jones' }],
    coverUrl: '/movies_pictures/45797-pinocchio-0-150-0-225-crop.jpg',
    releaseDate: '1940-02-07',
    rating: 2.75,
    length: 88,
    genre: 'Animation',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Megamind',
    director: 'Tom McGrath',
    actors: [{ name: 'Will Ferrell' }],
    coverUrl: '/movies_pictures/26476-megamind-0-150-0-225-crop.jpg',
    releaseDate: '2010-11-05',
    rating: 4.25,
    length: 95,
    genre: 'Animation',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Horton',
    director: 'Jimmy Hayward, Steve Martino',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl: '/movies_pictures/horton.jpg',
    releaseDate: '2008-03-14',
    rating: 2.75,
    length: 86,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Raya et le Dernier Dragon',
    director: 'Don Hall, Carlos López Estrada',
    actors: [
      {
        name: 'Kelly Marie Tran',
      },
    ],
    coverUrl:
      '/movies_pictures/457180-raya-and-the-last-dragon-0-150-0-225-crop.jpg',
    releaseDate: '2021-03-05',
    rating: 4,
    length: 107,
    genre: 'Animation',
    timesWatched: 3,
    lastViewedDate: '',
  },
];
