import { Movie } from "./movies";

export const moviesPage6: Movie[] = [
  {
    title: "OSS 117: Lost in Rio",
    director: "Michel Hazanavicius",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies/oss_117_lost_rio.jpg",
    releaseDate: "2009-04-15",
    rating: 0,
    length: 101,
    genre: "Comedy",
  },
  {
    title: "Fast & Furious",
    director: "Justin Lin",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/fast_furious.jpg",
    releaseDate: "2009-04-03",
    rating: 0,
    length: 107,
    genre: "Action",
  },
  {
    title: "Knowing",
    director: "Alex Proyas",
    actors: [{ name: "Nicolas Cage" }],
    coverUrl: "/movies/knowing.jpg",
    releaseDate: "2009-03-20",
    rating: 0,
    length: 121,
    genre: "Science Fiction",
  },
  {
    title: "Monsters vs Aliens",
    director: "Rob Letterman, Conrad Vernon",
    actors: [{ name: "Reese Witherspoon" }],
    coverUrl: "/movies/monsters_vs_aliens.jpg",
    releaseDate: "2009-03-27",
    rating: 0,
    length: 94,
    genre: "Animation",
  },
  {
    title: "17 Again",
    director: "Burr Steers",
    actors: [{ name: "Zac Efron" }],
    coverUrl: "/movies/17_again.jpg",
    releaseDate: "2009-04-17",
    rating: 0,
    length: 102,
    genre: "Comedy",
  },
  {
    title: "Watchmen",
    director: "Zack Snyder",
    actors: [{ name: "Jackie Earle Haley" }],
    coverUrl: "/movies/watchmen.jpg",
    releaseDate: "2009-03-06",
    rating: 0,
    length: 162,
    genre: "Action",
  },
  {
    title: "District 13: Ultimatum",
    director: "Patrick Alessandrin",
    actors: [{ name: "David Belle" }],
    coverUrl: "/movies/district_13_ultimatum.jpg",
    releaseDate: "2009-02-18",
    rating: 0,
    length: 101,
    genre: "Action",
  },
  {
    title: "Underworld: Rise of the Lycans",
    director: "Patrick Tatopoulos",
    actors: [{ name: "Michael Sheen" }],
    coverUrl: "/movies/underworld_rise_lycans.jpg",
    releaseDate: "2009-01-23",
    rating: 0,
    length: 92,
    genre: "Action",
  },
  {
    title: "I Love You Phillip Morris",
    director: "Glenn Ficarra, John Requa",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/i_love_you_phillip_morris.jpg",
    releaseDate: "2009-01-30",
    rating: 0,
    length: 98,
    genre: "Comedy",
  },
  {
    title: "(500) Days of Summer",
    director: "Marc Webb",
    actors: [{ name: "Joseph Gordon-Levitt" }],
    coverUrl: "/movies/500_days_summer.jpg",
    releaseDate: "2009-07-17",
    rating: 0,
    length: 95,
    genre: "Romance",
  },
  {
    title: "Seven Pounds",
    director: "Gabriele Muccino",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/seven_pounds.jpg",
    releaseDate: "2008-12-19",
    rating: 0,
    length: 123,
    genre: "Drama",
  },
  {
    title: "Yes Man",
    director: "Peyton Reed",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/yes_man.jpg",
    releaseDate: "2008-12-19",
    rating: 0,
    length: 104,
    genre: "Comedy",
  },
  {
    title: "Gran Torino",
    director: "Clint Eastwood",
    actors: [{ name: "Clint Eastwood" }],
    coverUrl: "/movies/gran_torino.jpg",
    releaseDate: "2008-12-12",
    rating: 0,
    length: 116,
    genre: "Drama",
  },
  {
    title: "Ong Bak 2",
    director: "Tony Jaa",
    actors: [{ name: "Tony Jaa" }],
    coverUrl: "/movies/ong_bak_2.jpg",
    releaseDate: "2008-12-05",
    rating: 0,
    length: 98,
    genre: "Action",
  },
  {
    title: "Transporter 3",
    director: "Olivier Megaton",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/transporter_3.jpg",
    releaseDate: "2008-11-26",
    rating: 0,
    length: 104,
    genre: "Action",
  },
  {
    title: "Twilight",
    director: "Catherine Hardwicke",
    actors: [{ name: "Kristen Stewart" }],
    coverUrl: "/movies/twilight.jpg",
    releaseDate: "2008-11-21",
    rating: 0,
    length: 122,
    genre: "Fantasy",
  },
  {
    title: "Quantum of Solace",
    director: "Marc Forster",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies/quantum_solace.jpg",
    releaseDate: "2008-11-14",
    rating: 0,
    length: 106,
    genre: "Action",
  },
  {
    title: "Eagle Eye",
    director: "D.J. Caruso",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies/eagle_eye.jpg",
    releaseDate: "2008-09-26",
    rating: 0,
    length: 118,
    genre: "Thriller",
  },
  {
    title: "Slumdog Millionaire",
    director: "Danny Boyle",
    actors: [{ name: "Dev Patel" }],
    coverUrl: "/movies/slumdog_millionaire.jpg",
    releaseDate: "2008-12-25",
    rating: 0,
    length: 120,
    genre: "Drama",
  },
  {
    title: "Death Race",
    director: "Paul W.S. Anderson",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/death_race.jpg",
    releaseDate: "2008-08-22",
    rating: 0,
    length: 105,
    genre: "Action",
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/dark_knight.jpg",
    releaseDate: "2008-07-18",
    rating: 0,
    length: 152,
    genre: "Action",
  },
  {
    title: "Hellboy II: The Golden Army",
    director: "Guillermo del Toro",
    actors: [{ name: "Ron Perlman" }],
    coverUrl: "/movies/hellboy_2.jpg",
    releaseDate: "2008-07-11",
    rating: 0,
    length: 120,
    genre: "Action",
  },
  {
    title: "Journey to the Center of the Earth",
    director: "Eric Brevig",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies/journey_center_earth.jpg",
    releaseDate: "2008-07-11",
    rating: 0,
    length: 93,
    genre: "Adventure",
  },
  {
    title: "Hancock",
    director: "Peter Berg",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/hancock.jpg",
    releaseDate: "2008-07-02",
    rating: 0,
    length: 92,
    genre: "Action",
  },
  {
    title: "WALL·E",
    director: "Andrew Stanton",
    actors: [{ name: "Ben Burtt" }],
    coverUrl: "/movies/walle.jpg",
    releaseDate: "2008-06-27",
    rating: 0,
    length: 98,
    genre: "Animation",
  },
  {
    title: "Wanted",
    director: "Timur Bekmambetov",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies/wanted.jpg",
    releaseDate: "2008-06-27",
    rating: 0,
    length: 110,
    genre: "Action",
  },
  {
    title: "The Incredible Hulk",
    director: "Louis Leterrier",
    actors: [{ name: "Edward Norton" }],
    coverUrl: "/movies/incredible_hulk.jpg",
    releaseDate: "2008-06-13",
    rating: 0,
    length: 112,
    genre: "Action",
  },
  {
    title: "You Don't Mess with the Zohan",
    director: "Dennis Dugan",
    actors: [{ name: "Adam Sandler" }],
    coverUrl: "/movies/zohan.jpg",
    releaseDate: "2008-06-06",
    rating: 0,
    length: 113,
    genre: "Comedy",
  },
  {
    title: "Kung Fu Panda",
    director: "Mark Osborne, John Stevenson",
    actors: [{ name: "Jack Black" }],
    coverUrl: "/movies/kung_fu_panda.jpg",
    releaseDate: "2008-06-06",
    rating: 0,
    length: 92,
    genre: "Animation",
  },
  {
    title: "Speed Racer",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Emile Hirsch" }],
    coverUrl: "/movies/speed_racer.jpg",
    releaseDate: "2008-05-09",
    rating: 0,
    length: 135,
    genre: "Action",
  },
  {
    title: "Iron Man",
    director: "Jon Favreau",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/iron_man.jpg",
    releaseDate: "2008-05-02",
    rating: 0,
    length: 126,
    genre: "Action",
  },
  {
    title: "What Happens in Vegas",
    director: "Tom Vaughan",
    actors: [{ name: "Ashton Kutcher" }],
    coverUrl: "/movies/what_happens_vegas.jpg",
    releaseDate: "2008-05-09",
    rating: 0,
    length: 99,
    genre: "Comedy",
  },
  {
    title: "The Wave",
    director: "Dennis Gansel",
    actors: [{ name: "Jürgen Vogel" }],
    coverUrl: "/movies/wave.jpg",
    releaseDate: "2008-03-13",
    rating: 0,
    length: 107,
    genre: "Drama",
  },
  {
    title: "Never Back Down",
    director: "Jeff Wadlow",
    actors: [{ name: "Sean Faris" }],
    coverUrl: "/movies/never_back_down.jpg",
    releaseDate: "2008-03-14",
    rating: 0,
    length: 110,
    genre: "Action",
  },
  {
    title: "Horton Hears a Who!",
    director: "Jimmy Hayward, Steve Martino",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/horton_hears_who.jpg",
    releaseDate: "2008-03-14",
    rating: 0,
    length: 86,
    genre: "Animation",
  },
  {
    title: "Taken",
    director: "Pierre Morel",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies/taken.jpg",
    releaseDate: "2008-02-27",
    rating: 0,
    length: 93,
    genre: "Action",
  },
  {
    title: "Step Up 2: The Streets",
    director: "Jon M. Chu",
    actors: [{ name: "Briana Evigan" }],
    coverUrl: "/movies/step_up_2.jpg",
    releaseDate: "2008-02-14",
    rating: 0,
    length: 98,
    genre: "Drama",
  },
  {
    title: "Jumper",
    director: "Doug Liman",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies/jumper.jpg",
    releaseDate: "2008-02-14",
    rating: 0,
    length: 88,
    genre: "Science Fiction",
  },
  {
    title: "Rambo",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rambo.jpg",
    releaseDate: "2008-01-25",
    rating: 0,
    length: 92,
    genre: "Action",
  },
  {
    title: "American Pie Presents: Beta House",
    director: "Andrew Waller",
    actors: [{ name: "John White" }],
    coverUrl: "/movies/american_pie_beta_house.jpg",
    releaseDate: "2007-12-26",
    rating: 0,
    length: 88,
    genre: "Comedy",
  },
  {
    title: "Aliens vs Predator: Requiem",
    director: "Colin Strause, Greg Strause",
    actors: [{ name: "Steven Pasquale" }],
    coverUrl: "/movies/aliens_vs_predator_requiem.jpg",
    releaseDate: "2007-12-25",
    rating: 0,
    length: 94,
    genre: "Action",
  },
  {
    title: "I Am Legend",
    director: "Francis Lawrence",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/i_am_legend.jpg",
    releaseDate: "2007-12-14",
    rating: 0,
    length: 101,
    genre: "Science Fiction",
  },
  {
    title: "Bee Movie",
    director: "Steve Hickner, Simon J. Smith",
    actors: [{ name: "Jerry Seinfeld" }],
    coverUrl: "/movies/bee_movie.jpg",
    releaseDate: "2007-11-02",
    rating: 0,
    length: 91,
    genre: "Animation",
  },
  {
    title: "Resident Evil: Extinction",
    director: "Russell Mulcahy",
    actors: [{ name: "Milla Jovovich" }],
    coverUrl: "/movies/resident_evil_extinction.jpg",
    releaseDate: "2007-09-21",
    rating: 0,
    length: 94,
    genre: "Action",
  },
  {
    title: "Paranormal Activity",
    director: "Oren Peli",
    actors: [{ name: "Katie Featherston" }],
    coverUrl: "/movies/paranormal_activity.jpg",
    releaseDate: "2007-10-14",
    rating: 0,
    length: 86,
    genre: "Horror",
  },
  {
    title: "Gone Baby Gone",
    director: "Ben Affleck",
    actors: [{ name: "Casey Affleck" }],
    coverUrl: "/movies/gone_baby_gone.jpg",
    releaseDate: "2007-10-19",
    rating: 0,
    length: 114,
    genre: "Crime",
  },
  {
    title: "Into the Wild",
    director: "Sean Penn",
    actors: [{ name: "Emile Hirsch" }],
    coverUrl: "/movies/into_wild.jpg",
    releaseDate: "2007-09-21",
    rating: 0,
    length: 148,
    genre: "Drama",
  },
  {
    title: "Juno",
    director: "Jason Reitman",
    actors: [{ name: "Ellen Page" }],
    coverUrl: "/movies/juno.jpg",
    releaseDate: "2007-12-25",
    rating: 0,
    length: 96,
    genre: "Comedy",
  },
  {
    title: "Rush Hour 3",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies/rush_hour_3.jpg",
    releaseDate: "2007-08-10",
    rating: 0,
    length: 91,
    genre: "Action",
  },
  {
    title: "The Bourne Ultimatum",
    director: "Paul Greengrass",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/bourne_ultimatum.jpg",
    releaseDate: "2007-08-03",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "The Simpsons Movie",
    director: "David Silverman",
    actors: [{ name: "Dan Castellaneta" }],
    coverUrl: "/movies/simpsons_movie.jpg",
    releaseDate: "2007-07-27",
    rating: 0,
    length: 87,
    genre: "Animation",
  },
  {
    title: "Harry Potter and the Order of the Phoenix",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_order_phoenix.jpg",
    releaseDate: "2007-07-11",
    rating: 0,
    length: 138,
    genre: "Fantasy",
  },
  {
    title: "Transformers",
    director: "Michael Bay",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies/transformers.jpg",
    releaseDate: "2007-07-03",
    rating: 0,
    length: 144,
    genre: "Action",
  },
  {
    title: "Ratatouille",
    director: "Brad Bird",
    actors: [{ name: "Patton Oswalt" }],
    coverUrl: "/movies/ratatouille.jpg",
    releaseDate: "2007-06-29",
    rating: 0,
    length: 111,
    genre: "Animation",
  },
  {
    title: "Live Free or Die Hard",
    director: "Len Wiseman",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/live_free_die_hard.jpg",
    releaseDate: "2007-06-27",
    rating: 0,
    length: 128,
    genre: "Action",
  },
  {
    title: "1408",
    director: "Mikael Håfström",
    actors: [{ name: "John Cusack" }],
    coverUrl: "/movies/1408.jpg",
    releaseDate: "2007-06-22",
    rating: 0,
    length: 104,
    genre: "Horror",
  },
  {
    title: "Fantastic Four: Rise of the Silver Surfer",
    director: "Tim Story",
    actors: [{ name: "Ioan Gruffudd" }],
    coverUrl: "/movies/fantastic_four_silver_surfer.jpg",
    releaseDate: "2007-06-15",
    rating: 0,
    length: 92,
    genre: "Action",
  },
  {
    title: "Evan Almighty",
    director: "Tom Shadyac",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies/evan_almighty.jpg",
    releaseDate: "2007-06-22",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Ocean's Thirteen",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/oceans_thirteen.jpg",
    releaseDate: "2007-06-08",
    rating: 0,
    length: 122,
    genre: "Crime",
  },
  {
    title: "No Country for Old Men",
    director: "Joel Coen, Ethan Coen",
    actors: [{ name: "Tommy Lee Jones" }],
    coverUrl: "/movies/no_country_old_men.jpg",
    releaseDate: "2007-11-09",
    rating: 3,
    length: 122,
    genre: "Crime",
  },
  {
    title: "Pirates of the Caribbean: At World's End",
    director: "Gore Verbinski",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/pirates_worlds_end.jpg",
    releaseDate: "2007-05-25",
    rating: 0,
    length: 169,
    genre: "Adventure",
  },
  {
    title: "Shrek the Third",
    director: "Chris Miller",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies/shrek_third.jpg",
    releaseDate: "2007-05-18",
    rating: 0,
    length: 93,
    genre: "Animation",
  },
  {
    title: "28 Weeks Later",
    director: "Juan Carlos Fresnadillo",
    actors: [{ name: "Robert Carlyle" }],
    coverUrl: "/movies/28_weeks_later.jpg",
    releaseDate: "2007-05-11",
    rating: 0,
    length: 100,
    genre: "Horror",
  },
  {
    title: "Spider-Man 3",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies/spiderman_3.jpg",
    releaseDate: "2007-05-04",
    rating: 0,
    length: 139,
    genre: "Action",
  },
  {
    title: "Perfect Stranger",
    director: "James Foley",
    actors: [{ name: "Halle Berry" }],
    coverUrl: "/movies/perfect_stranger.jpg",
    releaseDate: "2007-04-13",
    rating: 0,
    length: 109,
    genre: "Thriller",
  },
  {
    title: "Disturbia",
    director: "D.J. Caruso",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies/disturbia.jpg",
    releaseDate: "2007-04-13",
    rating: 0,
    length: 105,
    genre: "Thriller",
  },
  {
    title: "Superbad",
    director: "Greg Mottola",
    actors: [{ name: "Jonah Hill" }],
    coverUrl: "/movies/superbad.jpg",
    releaseDate: "2007-08-17",
    rating: 0,
    length: 113,
    genre: "Comedy",
  },
  {
    title: "Zodiac",
    director: "David Fincher",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies/zodiac.jpg",
    releaseDate: "2007-03-02",
    rating: 0,
    length: 157,
    genre: "Crime",
  },
  {
    title: "Taxi 4",
    director: "Gérard Krawczyk",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies/taxi_4.jpg",
    releaseDate: "2007-02-14",
    rating: 0,
    length: 91,
    genre: "Action",
  },
  {
    title: "Premonition",
    director: "Mennan Yapo",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/premonition.jpg",
    releaseDate: "2007-03-16",
    rating: 0,
    length: 96,
    genre: "Thriller",
  },
  {
    title: "Ghost Rider",
    director: "Mark Steven Johnson",
    actors: [{ name: "Nicolas Cage" }],
    coverUrl: "/movies/ghost_rider.jpg",
    releaseDate: "2007-02-16",
    rating: 0,
    length: 114,
    genre: "Action",
  },
  {
    title: "Freedom Writers",
    director: "Richard LaGravenese",
    actors: [{ name: "Hilary Swank" }],
    coverUrl: "/movies/freedom_writers.jpg",
    releaseDate: "2007-01-05",
    rating: 0,
    length: 123,
    genre: "Drama",
  },
];