import { Movie } from './movies_1';

export const moviesSagaPage4: Movie[] = [
  {
    title: 'La nuit au musée',
    director: 'Shawn Levy',
    actors: [{ name: 'Ben Stiller' }],
    coverUrl: '/movies_pictures/50941-night-at-the-museum-0-150-0-225-crop.jpg',
    releaseDate: '2006-12-22',
    rating: 3.5,
    length: 108,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'La Nuit au musée 2',
    director: 'Shawn Levy',
    actors: [{ name: 'Ben Stiller' }],
    coverUrl: '/movies_pictures/la_nuit_au_musee.jpg',
    releaseDate: '2009-05-22',
    rating: 3,
    length: 105,
    genre: 'Adventure',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Banlieue 13',
    director: 'Pierre Morel',
    actors: [{ name: 'David Belle' }],
    coverUrl: '/movies_pictures/46599-district-13-0-150-0-225-crop.jpg',
    releaseDate: '2004-11-10',
    rating: 3.75,
    length: 84,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Banlieue 13 : Ultimatum',
    director: 'Patrick Alessandrin',
    actors: [{ name: 'David Belle' }],
    coverUrl:
      '/movies_pictures/42437-district-13-ultimatum-0-150-0-225-crop.jpg',
    releaseDate: '2009-02-18',
    rating: 3,
    length: 101,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Resident Evil',
    director: 'Paul W.S. Anderson',
    actors: [{ name: 'Milla Jovovich' }],
    coverUrl: '/movies_pictures/resident_evil.jpg',
    releaseDate: '2002-03-15',
    rating: 3.75,
    length: 100,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Resident Evil : Apocalypse',
    director: 'Alexander Witt',
    actors: [{ name: 'Milla Jovovich' }],
    coverUrl:
      '/movies_pictures/50957-resident-evil-apocalypse-0-150-0-225-crop.jpg',
    releaseDate: '2004-09-10',
    rating: 3.75,
    length: 94,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Resident Evil : Extinction',
    director: 'Russell Mulcahy',
    actors: [{ name: 'Milla Jovovich' }],
    coverUrl:
      '/movies_pictures/47979-resident-evil-extinction-0-150-0-225-crop.jpg',
    releaseDate: '2007-09-21',
    rating: 3.5,
    length: 94,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Rush Hour',
    director: 'Brett Ratner',
    actors: [{ name: 'Jackie Chan' }],
    coverUrl: '/movies_pictures/50517-rush-hour-0-150-0-225-crop.jpg',
    releaseDate: '1998-09-18',
    rating: 4,
    length: 98,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Rush Hour 2',
    director: 'Brett Ratner',
    actors: [{ name: 'Jackie Chan' }],
    coverUrl: '/movies_pictures/48919-rush-hour-2-0-150-0-225-crop.jpg',
    releaseDate: '2001-08-03',
    rating: 3.5,
    length: 90,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Rush Hour 3',
    director: 'Brett Ratner',
    actors: [{ name: 'Jackie Chan' }],
    coverUrl: '/movies_pictures/48920-rush-hour-3-0-150-0-225-crop.jpg',
    releaseDate: '2007-08-10',
    rating: 3.5,
    length: 91,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: "Ocean's Eleven",
    director: 'Steven Soderbergh',
    actors: [{ name: 'George Clooney' }],
    coverUrl: '/movies_pictures/oceans_eleven.jpg',
    releaseDate: '2001-12-07',
    rating: 4.75,
    length: 116,
    genre: 'Crime',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: "Ocean's Twelve",
    director: 'Steven Soderbergh',
    actors: [{ name: 'George Clooney' }],
    coverUrl: '/movies_pictures/51888-ocean-s-twelve-0-150-0-225-crop.jpg',
    releaseDate: '2004-12-10',
    rating: 3.25,
    length: 125,
    genre: 'Crime',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: "Ocean's Thirteen",
    director: 'Steven Soderbergh',
    actors: [{ name: 'George Clooney' }],
    coverUrl: '/movies_pictures/51761-ocean-s-thirteen-0-150-0-225-crop.jpg',
    releaseDate: '2007-06-08',
    rating: 3.25,
    length: 122,
    genre: 'Crime',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: "Ocean's Eight",
    director: 'Gary Ross',
    actors: [
      {
        name: 'Sandra Bullock',
      },
    ],
    coverUrl:
      '/movies_pictures/283829-love-at-first-sight-0-150-0-225-crop.jpg',
    releaseDate: '2018-06-08',
    rating: 3,
    length: 110,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Pirates des Caraïbes : La malédiction du Black Pearl',
    director: 'Gore Verbinski',
    actors: [{ name: 'Johnny Depp' }],
    coverUrl:
      '/movies_pictures/2695-pirates-of-the-caribbean-the-curse-of-the-black-pearl-0-150-0-225-crop.jpg',
    releaseDate: '2003-07-09',
    rating: 3.75,
    length: 143,
    genre: 'Adventure',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Pirates des Caraïbes 2 : Le Secret du Coffre Maudit',
    director: 'Gore Verbinski',
    actors: [{ name: 'Johnny Depp' }],
    coverUrl:
      '/movies_pictures/51989-pirates-of-the-caribbean-dead-man-s-chest-0-150-0-225-crop.jpg',
    releaseDate: '2006-07-07',
    rating: 4.25,
    length: 151,
    genre: 'Adventure',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: "Pirates des Caraïbes 3 : Jusqu'au Bout du Monde",
    director: 'Gore Verbinski',
    actors: [{ name: 'Johnny Depp' }],
    coverUrl:
      '/movies_pictures/51773-pirates-of-the-caribbean-at-worlds-end-0-150-0-225-crop.jpg',
    releaseDate: '2007-05-25',
    rating: 3.25,
    length: 169,
    genre: 'Adventure',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Taxi',
    director: 'Gérard Pirès',
    actors: [{ name: 'Samy Naceri' }],
    coverUrl: '/movies_pictures/50324-taxi-0-150-0-225-crop.jpg',
    releaseDate: '1998-04-08',
    rating: 4.5,
    length: 86,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '2025-04-08',
  },
  {
    title: 'Taxi 2',
    director: 'Gérard Krawczyk',
    actors: [{ name: 'Samy Naceri' }],
    coverUrl: '/movies_pictures/50322-taxi-2-0-150-0-225-crop.jpg',
    releaseDate: '2000-03-31',
    rating: 3.5,
    length: 88,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Taxi 3',
    director: 'Gérard Krawczyk',
    actors: [{ name: 'Samy Naceri' }],
    coverUrl: '/movies_pictures/50320-taxi-3-0-150-0-225-crop.jpg',
    releaseDate: '2003-01-29',
    rating: 4,
    length: 84,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Taxi 4',
    director: 'Gérard Krawczyk',
    actors: [{ name: 'Samy Naceri' }],
    coverUrl: '/movies_pictures/50319-taxi-4-0-150-0-225-crop.jpg',
    releaseDate: '2007-02-14',
    rating: 4,
    length: 91,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Scary Movie',
    director: 'Keenen Ivory Wayans',
    actors: [{ name: 'Anna Faris' }],
    coverUrl: '/movies_pictures/49443-scary-movie-0-150-0-225-crop.jpg',
    releaseDate: '2000-07-07',
    rating: 4.25,
    length: 88,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Scary Movie 2',
    director: 'Keenen Ivory Wayans',
    actors: [{ name: 'Anna Faris' }],
    coverUrl: '/movies_pictures/49442-scary-movie-2-0-150-0-225-crop.jpg',
    releaseDate: '2001-07-04',
    rating: 3.5,
    length: 83,
    genre: 'Comedy',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Scary Movie 3',
    director: 'David Zucker',
    actors: [{ name: 'Anna Faris' }],
    coverUrl: '/movies_pictures/49434-scary-movie-3-0-150-0-225-crop.jpg',
    releaseDate: '2003-10-24',
    rating: 3.25,
    length: 84,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Scary Movie 4',
    director: 'David Zucker',
    actors: [{ name: 'Anna Faris' }],
    coverUrl: '/movies_pictures/49433-scary-movie-4-0-150-0-225-crop.jpg',
    releaseDate: '2006-04-14',
    rating: 3.25,
    length: 83,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Kill Bill: Vol. 1',
    director: 'Quentin Tarantino',
    actors: [{ name: 'Uma Thurman' }],
    coverUrl: '/movies_pictures/kill_bill.jpg',
    releaseDate: '2003-10-10',
    rating: 4.5,
    length: 111,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Kill Bill: Vol. 2',
    director: 'Quentin Tarantino',
    actors: [{ name: 'Uma Thurman' }],
    coverUrl: '/movies_pictures/kill_bill_2.jpg',
    releaseDate: '2004-04-16',
    rating: 4,
    length: 137,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Hellboy',
    director: 'Guillermo del Toro',
    actors: [{ name: 'Ron Perlman' }],
    coverUrl: '/movies_pictures/51012-hellboy-0-150-0-225-crop.jpg',
    releaseDate: '2004-04-02',
    rating: 4,
    length: 122,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: "Hellboy 2 : Les Légions d'Or Maudites",
    director: 'Guillermo del Toro',
    actors: [{ name: 'Ron Perlman' }],
    coverUrl:
      '/movies_pictures/45459-hellboy-ii-the-golden-army-0-150-0-225-crop.jpg',
    releaseDate: '2008-07-11',
    rating: 3.25,
    length: 120,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Les bronzés',
    director: 'Patrice Leconte',
    actors: [{ name: 'Josiane Balasko' }],
    coverUrl:
      '/movies_pictures/45526-french-fried-vacation-0-150-0-225-crop.jpg',
    releaseDate: '1978-12-20',
    rating: 2.5,
    length: 95,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Les bronzés font du ski',
    director: 'Patrice Leconte',
    actors: [{ name: 'Josiane Balasko' }],
    coverUrl:
      '/movies_pictures/29599-french-fried-vacation-2-the-bronzes-go-skiing-0-150-0-225-crop.jpg',
    releaseDate: '1979-12-19',
    rating: 3.25,
    length: 95,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Les Bronzés 3 : Amis pour la Vie',
    director: 'Patrice Leconte',
    actors: [{ name: 'Josiane Balasko' }],
    coverUrl:
      '/movies_pictures/38412-french-fried-vacation-3-0-150-0-225-crop.jpg',
    releaseDate: '2006-01-25',
    rating: 2.5,
    length: 95,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Le Transporteur',
    director: 'Louis Leterrier, Corey Yuen',
    actors: [{ name: 'Jason Statham' }],
    coverUrl: '/movies_pictures/49510-the-transporter-0-150-0-225-crop.jpg',
    releaseDate: '2002-10-11',
    rating: 3.75,
    length: 92,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Le Transporteur 2',
    director: 'Louis Leterrier',
    actors: [{ name: 'Jason Statham' }],
    coverUrl: '/movies_pictures/47259-transporter-2-0-150-0-225-crop.jpg',
    releaseDate: '2005-09-02',
    rating: 3.75,
    length: 87,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Le Transporteur 3',
    director: 'Olivier Megaton',
    actors: [{ name: 'Jason Statham' }],
    coverUrl: '/movies_pictures/43931-transporter-3-0-150-0-225-crop.jpg',
    releaseDate: '2008-11-26',
    rating: 3.25,
    length: 104,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'xXx',
    director: 'Rob Cohen',
    actors: [{ name: 'Vin Diesel' }],
    coverUrl: '/movies_pictures/48025-xxx-0-150-0-225-crop.jpg',
    releaseDate: '2002-08-09',
    rating: 3.5,
    length: 124,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'xXx² : The Next Level',
    director: 'Lee Tamahori',
    actors: [{ name: 'Ice Cube' }],
    coverUrl:
      '/movies_pictures/45074-xxx-state-of-the-union-0-150-0-225-crop.jpg',
    releaseDate: '2005-04-29',
    rating: 3.25,
    length: 101,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Sin City',
    director: 'Frank Miller, Robert Rodriguez',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/51865-sin-city-0-150-0-225-crop.jpg',
    releaseDate: '2005-04-01',
    rating: 3.5,
    length: 124,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "Sin City : J'ai Tué pour Elle",
    director: 'Frank Miller, Robert Rodriguez',
    actors: [{ name: 'Mickey Rourke' }],
    coverUrl:
      '/movies_pictures/51863-sin-city-a-dame-to-kill-for-0-150-0-225-crop.jpg',
    releaseDate: '2014-08-22',
    rating: 3.25,
    length: 102,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Blade',
    director: 'Stephen Norrington',
    actors: [{ name: 'Wesley Snipes' }],
    coverUrl: '/movies_pictures/27730-blade-0-150-0-225-crop.jpg',
    releaseDate: '1998-08-21',
    rating: 3.25,
    length: 120,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Blade II',
    director: 'Guillermo del Toro',
    actors: [{ name: 'Wesley Snipes' }],
    coverUrl: '/movies_pictures/27781-blade-ii-0-150-0-225-crop.jpg',
    releaseDate: '2002-03-22',
    rating: 3,
    length: 117,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Blade : Trinity',
    director: 'David S. Goyer',
    actors: [{ name: 'Wesley Snipes' }],
    coverUrl: '/movies_pictures/blade_trinity.jpg',
    releaseDate: '2004-12-08',
    rating: 3.25,
    length: 113,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
];
