import { Movie } from "./movies";

export const moviesPage10: Movie[] = [
  {
    title: "Space Jam",
    director: "Joe Pytka",
    actors: [{ name: "Michael Jordan" }],
    coverUrl: "/movies/space_jam.jpg",
    releaseDate: "1996-11-15",
    rating: 0,
    length: 88,
    genre: "Animation",
  },
  {
    title: "Independence Day: The ID4 Invasion",
    director: "Roland Emmerich",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/independence_day.jpg",
    releaseDate: "1996-07-03",
    rating: 0,
    length: 145,
    genre: "Science Fiction",
  },
  {
    title: "Independence Day",
    director: "Roland Emmerich",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/independence_day_alt.jpg",
    releaseDate: "1996-07-03",
    rating: 0,
    length: 145,
    genre: "Science Fiction",
  },
  {
    title: "Eraser",
    director: "Chuck Russell",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/eraser.jpg",
    releaseDate: "1996-06-21",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "The Quest",
    director: "Jean-Claude Van Damme",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies/quest.jpg",
    releaseDate: "1996-04-26",
    rating: 0,
    length: 95,
    genre: "Action",
  },
  {
    title: "Trainspotting",
    director: "Danny Boyle",
    actors: [{ name: "Ewan McGregor" }],
    coverUrl: "/movies/trainspotting.jpg",
    releaseDate: "1996-02-23",
    rating: 0,
    length: 93,
    genre: "Drama",
  },
  {
    title: "Jumanji",
    director: "Joe Johnston",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies/jumanji.jpg",
    releaseDate: "1995-12-15",
    rating: 0,
    length: 104,
    genre: "Adventure",
  },
  {
    title: "Toy Story",
    director: "John Lasseter",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/toy_story.jpg",
    releaseDate: "1995-11-22",
    rating: 0,
    length: 81,
    genre: "Animation",
  },
  {
    title: "Se7en",
    director: "David Fincher",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/se7en.jpg",
    releaseDate: "1995-09-22",
    rating: 0,
    length: 127,
    genre: "Crime",
  },
  {
    title: "The Net",
    director: "Irwin Winkler",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/net.jpg",
    releaseDate: "1995-07-28",
    rating: 0,
    length: 114,
    genre: "Thriller",
  },
  {
    title: "Waterworld",
    director: "Kevin Reynolds",
    actors: [{ name: "Kevin Costner" }],
    coverUrl: "/movies/waterworld.jpg",
    releaseDate: "1995-07-28",
    rating: 0,
    length: 135,
    genre: "Action",
  },
  {
    title: "Under Siege 2: Dark Territory",
    director: "Geoff Murphy",
    actors: [{ name: "Steven Seagal" }],
    coverUrl: "/movies/under_siege_2.jpg",
    releaseDate: "1995-07-14",
    rating: 0,
    length: 100,
    genre: "Action",
  },
  {
    title: "Judge Dredd",
    director: "Danny Cannon",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/judge_dredd.jpg",
    releaseDate: "1995-06-30",
    rating: 0,
    length: 96,
    genre: "Action",
  },
  {
    title: "Pocahontas",
    director: "Mike Gabriel, Eric Goldberg",
    actors: [{ name: "Irene Bedard" }],
    coverUrl: "/movies/pocahontas.jpg",
    releaseDate: "1995-06-23",
    rating: 0,
    length: 81,
    genre: "Animation",
  },
  {
    title: "Batman Forever",
    director: "Joel Schumacher",
    actors: [{ name: "Val Kilmer" }],
    coverUrl: "/movies/batman_forever.jpg",
    releaseDate: "1995-06-16",
    rating: 0,
    length: 121,
    genre: "Action",
  },
  {
    title: "Die Hard With a Vengeance",
    director: "John McTiernan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/die_hard_vengeance.jpg",
    releaseDate: "1995-05-19",
    rating: 0,
    length: 128,
    genre: "Action",
  },
  {
    title: "Bad Boys",
    director: "Michael Bay",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/bad_boys.jpg",
    releaseDate: "1995-04-07",
    rating: 0,
    length: 119,
    genre: "Action",
  },
  {
    title: "The Usual Suspects",
    director: "Bryan Singer",
    actors: [{ name: "Kevin Spacey" }],
    coverUrl: "/movies/usual_suspects.jpg",
    releaseDate: "1995-08-16",
    rating: 0,
    length: 106,
    genre: "Crime",
  },
  {
    title: "Street Fighter",
    director: "Steven E. de Souza",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies/street_fighter.jpg",
    releaseDate: "1994-12-23",
    rating: 0,
    length: 102,
    genre: "Action",
  },
  {
    title: "Little Indian, Big City",
    director: "Hervé Palud",
    actors: [{ name: "Thierry Lhermitte" }],
    coverUrl: "/movies/little_indian_big_city.jpg",
    releaseDate: "1994-12-14",
    rating: 0,
    length: 85,
    genre: "Comedy",
  },
  {
    title: "Dumb and Dumber",
    director: "Peter Farrelly, Bobby Farrelly",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/dumb_dumber.jpg",
    releaseDate: "1994-12-16",
    rating: 0,
    length: 107,
    genre: "Comedy",
  },
  {
    title: "Léon: The Professional",
    director: "Luc Besson",
    actors: [{ name: "Jean Reno" }],
    coverUrl: "/movies/leon_professional.jpg",
    releaseDate: "1994-11-18",
    rating: 0,
    length: 110,
    genre: "Action",
  },
  {
    title: "The Mask",
    director: "Chuck Russell",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/mask.jpg",
    releaseDate: "1994-07-29",
    rating: 0,
    length: 101,
    genre: "Comedy",
  },
  {
    title: "True Lies",
    director: "James Cameron",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/true_lies.jpg",
    releaseDate: "1994-07-15",
    rating: 0,
    length: 141,
    genre: "Action",
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/forrest_gump.jpg",
    releaseDate: "1994-07-06",
    rating: 0,
    length: 142,
    genre: "Drama",
  },
  {
    title: "The Lion King",
    director: "Roger Allers, Rob Minkoff",
    actors: [{ name: "Matthew Broderick" }],
    coverUrl: "/movies/lion_king.jpg",
    releaseDate: "1994-06-24",
    rating: 0,
    length: 88,
    genre: "Animation",
  },
  {
    title: "Speed",
    director: "Jan de Bont",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/speed.jpg",
    releaseDate: "1994-06-10",
    rating: 0,
    length: 116,
    genre: "Action",
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    actors: [{ name: "John Travolta" }],
    coverUrl: "/movies/pulp_fiction.jpg",
    releaseDate: "1994-10-14",
    rating: 0,
    length: 154,
    genre: "Crime",
  },
  {
    title: "Fear City: A Family-Style Comedy",
    director: "Alain Berbérian",
    actors: [{ name: "Patrick Timsit" }],
    coverUrl: "/movies/fear_city.jpg",
    releaseDate: "1994-03-16",
    rating: 0,
    length: 85,
    genre: "Comedy",
  },
  {
    title: "Mrs. Doubtfire",
    director: "Chris Columbus",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies/mrs_doubtfire.jpg",
    releaseDate: "1993-11-24",
    rating: 0,
    length: 125,
    genre: "Comedy",
  },
  {
    title: "Demolition Man",
    director: "Marco Brambilla",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/demolition_man.jpg",
    releaseDate: "1993-10-08",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "The Fugitive",
    director: "Andrew Davis",
    actors: [{ name: "Harrison Ford" }],
    coverUrl: "/movies/fugitive.jpg",
    releaseDate: "1993-08-06",
    rating: 0,
    length: 130,
    genre: "Action",
  },
  {
    title: "Last Action Hero",
    director: "John McTiernan",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/last_action_hero.jpg",
    releaseDate: "1993-06-18",
    rating: 0,
    length: 130,
    genre: "Action",
  },
  {
    title: "Jurassic Park",
    director: "Steven Spielberg",
    actors: [{ name: "Sam Neill" }],
    coverUrl: "/movies/jurassic_park.jpg",
    releaseDate: "1993-06-11",
    rating: 0,
    length: 127,
    genre: "Adventure",
  },
  {
    title: "Cliffhanger",
    director: "Renny Harlin",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/cliffhanger.jpg",
    releaseDate: "1993-05-28",
    rating: 0,
    length: 113,
    genre: "Action",
  },
  {
    title: "The Visitors",
    director: "Jean-Marie Poiré",
    actors: [{ name: "Jean Reno" }],
    coverUrl: "/movies/visitors.jpg",
    releaseDate: "1993-01-27",
    rating: 0,
    length: 107,
    genre: "Comedy",
  },
  {
    title: "Home Alone 2: Lost in New York",
    director: "Chris Columbus",
    actors: [{ name: "Macaulay Culkin" }],
    coverUrl: "/movies/home_alone_2.jpg",
    releaseDate: "1992-11-20",
    rating: 0,
    length: 120,
    genre: "Comedy",
  },
  {
    title: "Aladdin",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Scott Weinger" }],
    coverUrl: "/movies/aladdin.jpg",
    releaseDate: "1992-11-25",
    rating: 0,
    length: 90,
    genre: "Animation",
  },
  {
    title: "Under Siege",
    director: "Andrew Davis",
    actors: [{ name: "Steven Seagal" }],
    coverUrl: "/movies/under_siege.jpg",
    releaseDate: "1992-10-09",
    rating: 0,
    length: 103,
    genre: "Action",
  },
  {
    title: "Batman Returns",
    director: "Tim Burton",
    actors: [{ name: "Michael Keaton" }],
    coverUrl: "/movies/batman_returns.jpg",
    releaseDate: "1992-06-19",
    rating: 0,
    length: 126,
    genre: "Action",
  },
  {
    title: "Alien³",
    director: "David Fincher",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies/alien_3.jpg",
    releaseDate: "1992-05-22",
    rating: 0,
    length: 114,
    genre: "Science Fiction",
  },
  {
    title: "Lethal Weapon 3",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies/lethal_weapon_3.jpg",
    releaseDate: "1992-05-15",
    rating: 0,
    length: 118,
    genre: "Action",
  },
  {
    title: "Basic Instinct",
    director: "Paul Verhoeven",
    actors: [{ name: "Michael Douglas" }],
    coverUrl: "/movies/basic_instinct.jpg",
    releaseDate: "1992-03-20",
    rating: 0,
    length: 128,
    genre: "Thriller",
  },
  {
    title: "Reservoir Dogs",
    director: "Quentin Tarantino",
    actors: [{ name: "Harvey Keitel" }],
    coverUrl: "/movies/reservoir_dogs.jpg",
    releaseDate: "1992-10-23",
    rating: 0,
    length: 99,
    genre: "Crime",
  },
  {
    title: "The Last Boy Scout",
    director: "Tony Scott",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/last_boy_scout.jpg",
    releaseDate: "1991-12-13",
    rating: 0,
    length: 105,
    genre: "Action",
  },
  {
    title: "The Making of 'Terminator 2: Judgment Day'",
    director: "James Cameron",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/making_terminator_2.jpg",
    releaseDate: "1991-12-25",
    rating: 0,
    length: 60,
    genre: "Documentary",
  },
  {
    title: "Double Impact",
    director: "Sheldon Lettich",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies/double_impact.jpg",
    releaseDate: "1991-08-09",
    rating: 0,
    length: 110,
    genre: "Action",
  },
  {
    title: "Point Break",
    director: "Kathryn Bigelow",
    actors: [{ name: "Patrick Swayze" }],
    coverUrl: "/movies/point_break.jpg",
    releaseDate: "1991-07-12",
    rating: 0,
    length: 122,
    genre: "Action",
  },
  {
    title: "Terminator 2: Judgment Day",
    director: "James Cameron",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/terminator_2.jpg",
    releaseDate: "1991-07-03",
    rating: 0,
    length: 137,
    genre: "Action",
  },
  {
    title: "Predator 2",
    director: "Stephen Hopkins",
    actors: [{ name: "Danny Glover" }],
    coverUrl: "/movies/predator_2.jpg",
    releaseDate: "1990-11-21",
    rating: 0,
    length: 108,
    genre: "Action",
  },
  {
    title: "Rocky V",
    director: "John G. Avildsen",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rocky_5.jpg",
    releaseDate: "1990-11-16",
    rating: 0,
    length: 104,
    genre: "Drama",
  },
  {
    title: "Home Alone",
    director: "Chris Columbus",
    actors: [{ name: "Macaulay Culkin" }],
    coverUrl: "/movies/home_alone.jpg",
    releaseDate: "1990-11-16",
    rating: 0,
    length: 103,
    genre: "Comedy",
  },
  {
    title: "GoodFellas",
    director: "Martin Scorsese",
    actors: [{ name: "Robert De Niro" }],
    coverUrl: "/movies/goodfellas.jpg",
    releaseDate: "1990-09-19",
    rating: 0,
    length: 146,
    genre: "Crime",
  },
  {
    title: "Die Hard 2",
    director: "Renny Harlin",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/die_hard_2.jpg",
    releaseDate: "1990-07-04",
    rating: 0,
    length: 124,
    genre: "Action",
  },
  {
    title: "Total Recall",
    director: "Paul Verhoeven",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/total_recall.jpg",
    releaseDate: "1990-06-01",
    rating: 0,
    length: 113,
    genre: "Science Fiction",
  },
  {
    title: "Back to the Future Part III",
    director: "Robert Zemeckis",
    actors: [{ name: "Michael J. Fox" }],
    coverUrl: "/movies/back_future_3.jpg",
    releaseDate: "1990-05-25",
    rating: 0,
    length: 118,
    genre: "Science Fiction",
  },
  {
    title: "Pretty Woman",
    director: "Garry Marshall",
    actors: [{ name: "Julia Roberts" }],
    coverUrl: "/movies/pretty_woman.jpg",
    releaseDate: "1990-03-23",
    rating: 0,
    length: 119,
    genre: "Romance",
  },
  {
    title: "La Femme Nikita",
    director: "Luc Besson",
    actors: [{ name: "Anne Parillaud" }],
    coverUrl: "/movies/femme_nikita.jpg",
    releaseDate: "1990-02-21",
    rating: 0,
    length: 117,
    genre: "Action",
  },
  {
    title: "Tango & Cash",
    director: "Andrei Konchalovsky",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/tango_cash.jpg",
    releaseDate: "1989-12-22",
    rating: 0,
    length: 104,
    genre: "Action",
  },
  {
    title: "Back to the Future Part II",
    director: "Robert Zemeckis",
    actors: [{ name: "Michael J. Fox" }],
    coverUrl: "/movies/back_future_2.jpg",
    releaseDate: "1989-11-22",
    rating: 0,
    length: 108,
    genre: "Science Fiction",
  },
  {
    title: "The Little Mermaid",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Jodi Benson" }],
    coverUrl: "/movies/little_mermaid.jpg",
    releaseDate: "1989-11-17",
    rating: 0,
    length: 83,
    genre: "Animation",
  },
  {
    title: "Lethal Weapon 2",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies/lethal_weapon_2.jpg",
    releaseDate: "1989-07-07",
    rating: 0,
    length: 114,
    genre: "Action",
  },
  {
    title: "Batman",
    director: "Tim Burton",
    actors: [{ name: "Michael Keaton" }],
    coverUrl: "/movies/batman.jpg",
    releaseDate: "1989-06-23",
    rating: 0,
    length: 126,
    genre: "Action",
  },
  {
    title: "Dead Poets Society",
    director: "Peter Weir",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies/dead_poets_society.jpg",
    releaseDate: "1989-06-09",
    rating: 0,
    length: 128,
    genre: "Drama",
  },
  {
    title: "Kickboxer",
    director: "Mark DiSalle, David Worth",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies/kickboxer.jpg",
    releaseDate: "1989-04-20",
    rating: 0,
    length: 97,
    genre: "Action",
  },
  {
    title: "Die Hard",
    director: "John McTiernan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/die_hard.jpg",
    releaseDate: "1988-07-15",
    rating: 0,
    length: 132,
    genre: "Action",
  },
  {
    title: "Who Framed Roger Rabbit",
    director: "Robert Zemeckis",
    actors: [{ name: "Bob Hoskins" }],
    coverUrl: "/movies/who_framed_roger_rabbit.jpg",
    releaseDate: "1988-06-22",
    rating: 0,
    length: 104,
    genre: "Animation",
  },
  {
    title: "Rambo III",
    director: "Peter MacDonald",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rambo_3.jpg",
    releaseDate: "1988-05-25",
    rating: 0,
    length: 102,
    genre: "Action",
  },
  {
    title: "Bloodsport",
    director: "Newt Arnold",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies/bloodsport.jpg",
    releaseDate: "1988-02-26",
    rating: 0,
    length: 92,
    genre: "Action",
  },
  {
    title: "Good Morning, Vietnam",
    director: "Barry Levinson",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies/good_morning_vietnam.jpg",
    releaseDate: "1987-12-23",
    rating: 0,
    length: 121,
    genre: "Comedy",
  },
  {
    title: "The Running Man",
    director: "Paul Michael Glaser",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/running_man.jpg",
    releaseDate: "1987-11-13",
    rating: 0,
    length: 101,
    genre: "Science Fiction",
  },
  {
    title: "RoboCop",
    director: "Paul Verhoeven",
    actors: [{ name: "Peter Weller" }],
    coverUrl: "/movies/robocop.jpg",
    releaseDate: "1987-07-17",
    rating: 0,
    length: 102,
    genre: "Action",
  },
];