import { Movie } from './movies_1';

export const moviesLove1: Movie[] = [
  {
    title: 'Mon inconnue',
    director: 'Hugo Gélin',
    actors: [
      {
        name: 'François Civil',
      },
    ],
    coverUrl:
      '/movies_pictures/498516-love-at-second-sight-0-150-0-225-crop.jpg',
    releaseDate: '2019-01-30',
    rating: 4.5,
    length: 118,
    genre: 'Romance',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'The Princess Switch',
    director: 'Mike Rohl',
    actors: [
      {
        name: 'Vanessa Hudgens',
      },
    ],
    coverUrl:
      '/movies_pictures/485841-the-princess-switch-0-150-0-225-crop.jpg',
    releaseDate: '2018-11-16',
    rating: 3.25,
    length: 101,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Petits coups montés',
    director: 'Claire Scanlon',
    actors: [
      {
        name: 'Zoey Deutch',
      },
    ],
    coverUrl: '/movies_pictures/319550-set-it-up-0-150-0-225-crop.jpg',
    releaseDate: '2018-06-15',
    rating: 3,
    length: 105,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The life list',
    director: 'Liz W. Garcia',
    actors: [
      {
        name: 'Katherine Heigl',
      },
    ],
    coverUrl: '/movies_pictures/1138997-the-life-list-0-150-0-225-crop.jpg',
    releaseDate: '2024-07-18',
    rating: 3.5,
    length: 104,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '2025-03-08',
  },
  {
    title: 'Tout le Bleu du Ciel',
    director: 'João Canijo',
    actors: [
      {
        name: 'Rita Blanco',
      },
    ],
    coverUrl:
      '/movies_pictures/1307347-tout-le-bleu-du-ciel-2025-0-150-0-225-crop.jpg',
    releaseDate: '2022-09-08',
    rating: 3.5,
    length: 127,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-02-08',
  },
  {
    title: 'Nos coeurs meurtris',
    director: 'Elizabeth Allen Rosenbaum',
    actors: [
      {
        name: 'Sofia Carson',
      },
    ],
    coverUrl: '/movies_pictures/683195-purple-hearts-0-150-0-225-crop.jpg',
    releaseDate: '2022-07-29',
    rating: 4.25,
    length: 122,
    genre: 'Romance',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Au plaisir de se faire trahir',
    director: 'Diego Freitas',
    actors: [
      {
        name: 'Giovanna Lancellotti',
      },
    ],
    coverUrl: '/movies_pictures/1060546-burning-betrayal-0-150-0-225-crop.jpg',
    releaseDate: '2023-10-25',
    rating: 3,
    length: 104,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "La Probabilité statistique de l'amour au premier regard",
    director: 'Vanessa Caswill',
    actors: [
      {
        name: 'Haley Lu Richardson',
      },
    ],
    coverUrl: '/movies_pictures/1146306_300x450.webp',
    releaseDate: '2023-09-15',
    rating: 3,
    length: 91,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Ce sera toi',
    director: 'Alauda Ruiz de Azúa',
    actors: [
      {
        name: 'Silvia Alonso',
      },
    ],
    coverUrl: '/movies_pictures/735234-love-at-first-kiss-0-150-0-225-crop.jpg',
    releaseDate: '2023-02-10',
    rating: 3,
    length: 103,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Hello, goodbye and everything in between',
    director: 'Michael Lewen',
    actors: [
      {
        name: 'Talia Ryder',
      },
    ],
    coverUrl:
      '/movies_pictures/666928-hello-goodbye-and-everything-in-between-0-150-0-225-crop.jpg',
    releaseDate: '2022-07-06',
    rating: 3,
    length: 91,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Un Accord Parfait',
    director: 'Stuart McDonald',
    actors: [
      {
        name: 'Victoria Justice',
      },
    ],
    coverUrl: '/movies_pictures/839735-a-perfect-pairing-0-150-0-225-crop.jpg',
    releaseDate: '2022-05-19',
    rating: 3.5,
    length: 101,
    genre: 'Romance',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'The In-between',
    director: 'Arie Posin',
    actors: [
      {
        name: 'Joey King',
      },
    ],
    coverUrl: '/movies_pictures/735089-the-in-between-0-150-0-225-crop.jpg',
    releaseDate: '2022-02-11',
    rating: 3,
    length: 116,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'À Travers Ma Fenêtre',
    director: 'Marçal Forés',
    actors: [
      {
        name: 'Julio Peña',
      },
    ],
    coverUrl: '/movies_pictures/735239-through-my-window-0-150-0-225-crop.jpg',
    releaseDate: '2022-02-04',
    rating: 2.75,
    length: 113,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Love Hard',
    director: 'Hernán Jiménez',
    actors: [
      {
        name: 'Nina Dobrev',
      },
    ],
    coverUrl: '/movies_pictures/656542-love-hard-0-150-0-225-crop.jpg',
    releaseDate: '2021-11-05',
    rating: 3,
    length: 104,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "L'Amour complexe",
    director: 'Steven Tsuchida',
    actors: [
      {
        name: 'Christina Milian',
      },
    ],
    coverUrl: '/movies_pictures/704151-resort-to-love-0-150-0-225-crop.jpg',
    releaseDate: '2021-07-29',
    rating: 2.75,
    length: 101,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'La Belle et la Bête',
    director: 'Bill Condon',
    actors: [{ name: 'Emma Watson' }],
    coverUrl:
      '/movies_pictures/248708-beauty-and-the-beast-0-150-0-225-crop.jpg',
    releaseDate: '2017-03-17',
    rating: 3.5,
    length: 129,
    genre: 'Fantasy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Un choix',
    director: 'Ross Katz',
    actors: [{ name: 'Benjamin Walker' }],
    coverUrl: '/movies_pictures/258147-the-choice-0-150-0-225-crop.jpg',
    releaseDate: '2016-02-05',
    rating: 4,
    length: 111,
    genre: 'Romance',
    timesWatched: 3,
    lastViewedDate: '2025-02-05',
  },
  {
    title: "L'agence",
    director: 'George Nolfi',
    actors: [{ name: 'Matt Damon' }],
    coverUrl:
      '/movies_pictures/the-adjustment-bureau-original-1-0-150-0-225-crop.jpg',
    releaseDate: '2011-03-04',
    rating: 3.75,
    length: 106,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Un jour',
    director: 'Lone Scherfig',
    actors: [{ name: 'Anne Hathaway' }],
    coverUrl: '/movies_pictures/un_jour.jpg',
    releaseDate: '2011-08-19',
    rating: 3.5,
    length: 107,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Sex Friends',
    director: 'Ivan Reitman',
    actors: [{ name: 'Natalie Portman' }],
    coverUrl:
      '/movies_pictures/no-strings-attached-original-0-150-0-225-crop.jpg',
    releaseDate: '2011-01-21',
    rating: 3.75,
    length: 108,
    genre: 'Romance',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Love & autres drogues',
    director: 'Edward Zwick',
    actors: [{ name: 'Jake Gyllenhaal' }],
    coverUrl: '/movies_pictures/21801-love-other-drugs-0-150-0-225-crop.jpg',
    releaseDate: '2010-11-24',
    rating: 4,
    length: 112,
    genre: 'Romance',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Sexy Dance',
    director: 'Anne Fletcher',
    actors: [{ name: 'Channing Tatum' }],
    coverUrl: '/movies_pictures/46848-step-up-0-150-0-225-crop.jpg',
    releaseDate: '2006-08-11',
    rating: 3,
    length: 104,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Sexy Dance 2',
    director: 'Jon M. Chu',
    actors: [{ name: 'Briana Evigan' }],
    coverUrl: '/movies_pictures/47804-step-up-2-0-150-0-225-crop.jpg',
    releaseDate: '2008-02-14',
    rating: 3,
    length: 98,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Sexy Dance 3D',
    director: 'Jon M. Chu',
    actors: [{ name: 'Rick Malambri' }],
    coverUrl: '/movies_pictures/23784-step-up-3-0-150-0-225-crop.jpg',
    releaseDate: '2010-08-06',
    rating: 3.75,
    length: 107,
    genre: 'Drama',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: "L'Arnacœur",
    director: 'Pascal Chaumeil',
    actors: [{ name: 'Romain Duris' }],
    coverUrl: '/movies_pictures/23804-heartbreaker-0-150-0-225-crop.jpg',
    releaseDate: '2010-03-17',
    rating: 4,
    length: 105,
    genre: 'Romance',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Remember Me',
    director: 'Allen Coulter',
    actors: [{ name: 'Robert Pattinson' }],
    coverUrl: '/movies_pictures/37502-remember-me-0-150-0-225-crop.jpg',
    releaseDate: '2010-03-12',
    rating: 3.75,
    length: 113,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-04-12',
  },
  {
    title: "Valentine's Day",
    director: 'Garry Marshall',
    actors: [{ name: 'Julia Roberts' }],
    coverUrl: '/movies_pictures/valentine_day.jpg',
    releaseDate: '2010-02-12',
    rating: 3.25,
    length: 125,
    genre: 'Romance',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'La proposition',
    director: 'Anne Fletcher',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/40479-the-proposal-0-150-0-225-crop.jpg',
    releaseDate: '2009-06-19',
    rating: 3.25,
    length: 108,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: '17 ans encore',
    director: 'Burr Steers',
    actors: [{ name: 'Zac Efron' }],
    coverUrl: '/movies_pictures/41276-17-again-0-150-0-225-crop.jpg',
    releaseDate: '2009-04-17',
    rating: 3,
    length: 102,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: '(500) Jours Ensemble',
    director: 'Marc Webb',
    actors: [{ name: 'Joseph Gordon-Levitt' }],
    coverUrl: '/movies_pictures/39350--500-days-of-summer-0-150-0-225-crop.jpg',
    releaseDate: '2009-07-17',
    rating: 3,
    length: 95,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Jackpot',
    director: 'Tom Vaughan',
    actors: [{ name: 'Ashton Kutcher' }],
    coverUrl:
      '/movies_pictures/47414-what-happens-in-vegas--0-150-0-225-crop.jpg',
    releaseDate: '2008-05-09',
    rating: 3,
    length: 99,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Juno',
    director: 'Jason Reitman',
    actors: [{ name: 'Ellen Page' }],
    coverUrl: '/movies_pictures/48051-juno-0-150-0-225-crop.jpg',
    releaseDate: '2007-12-25',
    rating: 3,
    length: 96,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Orgueil et Préjugés',
    director: 'Joe Wright',
    actors: [{ name: 'Keira Knightley' }],
    coverUrl: '/movies_pictures/orgueil_et_prejuges.jpg',
    releaseDate: '2005-09-16',
    rating: 3.25,
    length: 129,
    genre: 'Romance',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Match Point',
    director: 'Woody Allen',
    actors: [{ name: 'Jonathan Rhys Meyers' }],
    coverUrl: '/movies_pictures/match_point.jpg',
    releaseDate: '2005-05-12',
    rating: 3.75,
    length: 124,
    genre: 'Thriller',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Hitch : Expert en Séduction',
    director: 'Andy Tennant',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/47699-hitch-0-150-0-225-crop.jpg',
    releaseDate: '2005-02-11',
    rating: 4.25,
    length: 118,
    genre: 'Comedy',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'First Daughter',
    director: 'Forest Whitaker',
    actors: [{ name: 'Katie Holmes' }],
    coverUrl: '/movies_pictures/43443-first-daughter-0-150-0-225-crop.jpg',
    releaseDate: '2004-09-24',
    rating: 3.25,
    length: 106,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
