import { Movie } from "./movies_1";

export const moviesPage9: Movie[] = [
  {
    title: "Ocean's Eleven",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies_pictures/oceans_eleven.jpg",
    releaseDate: "2001-12-07",
    rating: 0,
    length: 116,
    genre: "Crime",
    timesWatched: 15,
  },
  {
    title: "Tanguy",
    director: "Étienne Chatiliez",
    actors: [{ name: "Éric Berger" }],
    coverUrl: "/movies_pictures/50585-tanguy-0-150-0-225-crop.jpg",
    releaseDate: "2001-12-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 2,
  },
  {
    title: "The One",
    director: "James Wong",
    actors: [{ name: "Jet Li" }],
    coverUrl: "/movies_pictures/45888-the-one-0-150-0-225-crop.jpg",
    releaseDate: "2001-11-02",
    rating: 0,
    length: 87,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "Wasabi",
    director: "Gérard Krawczyk",
    actors: [{ name: "Jean Reno" }],
    coverUrl: "/movies_pictures/50516-wasabi-0-150-0-225-crop.jpg",
    releaseDate: "2001-10-31",
    rating: 0,
    length: 94,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Training Day",
    director: "Antoine Fuqua",
    actors: [{ name: "Denzel Washington" }],
    coverUrl: "/movies_pictures/50580-training-day-0-150-0-225-crop.jpg",
    releaseDate: "2001-10-05",
    rating: 0,
    length: 122,
    genre: "Crime",
    timesWatched: 5,
  },
  {
    title: "American Pie 2",
    director: "J.B. Rogers",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies_pictures/50101-american-pie-2-0-150-0-225-crop.jpg",
    releaseDate: "2001-08-10",
    rating: 0,
    length: 108,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Rush Hour 2",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies_pictures/48919-rush-hour-2-0-150-0-225-crop.jpg",
    releaseDate: "2001-08-03",
    rating: 0,
    length: 90,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Shaolin Soccer",
    director: "Stephen Chow",
    actors: [{ name: "Stephen Chow" }],
    coverUrl: "/movies_pictures/45025-shaolin-soccer-0-150-0-225-crop.jpg",
    releaseDate: "2001-07-12",
    rating: 0,
    length: 87,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Scary Movie 2",
    director: "Keenen Ivory Wayans",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies_pictures/49442-scary-movie-2-0-150-0-225-crop.jpg",
    releaseDate: "2001-07-04",
    rating: 0,
    length: 83,
    genre: "Comedy",
    timesWatched: 15,
  },

  {
    title: "Lara Croft : Tomb Raider",
    director: "Simon West",
    actors: [{ name: "Angelina Jolie" }],
    coverUrl: "/movies_pictures/50617-lara-croft-tomb-raider-0-150-0-225-crop.jpg",
    releaseDate: "2001-06-15",
    rating: 0,
    length: 100,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Mulholland Drive",
    director: "David Lynch",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies_pictures/mulholland_drive.jpg",
    releaseDate: "2001-10-12",
    rating: 0,
    length: 147,
    genre: "Mystery",
    timesWatched: 1,
  },
  {
    title: "Replicant",
    director: "Ringo Lam",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies_pictures/46077-replicant-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-04",
    rating: 0,
    length: 100,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Le Retour de la Momie",
    director: "Stephen Sommers",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies_pictures/50818-the-mummy-returns-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-04",
    rating: 0,
    length: 130,
    genre: "Adventure",
    timesWatched: 20,
  },
  {
    title: "Spy Kids",
    director: "Robert Rodriguez",
    actors: [{ name: "Alexa Vega" }],
    coverUrl: "/movies_pictures/spy_kids.jpg",
    releaseDate: "2001-03-30",
    rating: 0,
    length: 88,
    genre: "Adventure",
    timesWatched: 5,
  },
  {
    title: "Battle Royale",
    director: "Kinji Fukasaku",
    actors: [{ name: "Tatsuya Fujiwara" }],
    coverUrl: "/movies_pictures/49810-battle-royale-0-150-0-225-crop.jpg",
    releaseDate: "2000-12-16",
    rating: 0,
    length: 114,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Miss Détective",
    director: "Donald Petrie",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies_pictures/51006-miss-congeniality-0-150-0-225-crop.jpg",
    releaseDate: "2000-12-22",
    rating: 0,
    length: 111,
    genre: "Comedy",
    timesWatched: 1,
  },

  {
    title: "Incassable",
    director: "M. Night Shyamalan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/46866-unbreakable-0-150-0-225-crop.jpg",
    releaseDate: "2000-11-22",
    rating: 0,
    length: 106,
    genre: "Thriller",
    timesWatched: 10,
  },
  {
    title: "A l'aube du 6ème jour",
    director: "Roger Spottiswoode",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/a_l_aube_du_sixieme_jour.jpg",
    releaseDate: "2000-11-17",
    rating: 0,
    length: 123,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "Memento",
    director: "Christopher Nolan",
    actors: [{ name: "Guy Pearce" }],
    coverUrl: "/movies_pictures/memento-0-150-0-225-crop.jpg",
    releaseDate: "2000-09-05",
    rating: 0,
    length: 113,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Snatch",
    director: "Guy Ritchie",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies_pictures/snatch.jpg",
    releaseDate: "2000-09-01",
    rating: 0,
    length: 104,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "Scary Movie",
    director: "Keenen Ivory Wayans",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies_pictures/49443-scary-movie-0-150-0-225-crop.jpg",
    releaseDate: "2000-07-07",
    rating: 0,
    length: 88,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Requiem for a Dream",
    director: "Darren Aronofsky",
    actors: [{ name: "Ellen Burstyn" }],
    coverUrl: "/movies_pictures/requiem_for_a_dream.jpg",
    releaseDate: "2000-10-06",
    rating: 0,
    length: 102,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Gladiator",
    director: "Ridley Scott",
    actors: [{ name: "Russell Crowe" }],
    coverUrl: "/movies_pictures/51952-gladiator-2000-0-150-0-225-crop.jpg",
    releaseDate: "2000-05-05",
    rating: 0,
    length: 155,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Taxi 2",
    director: "Gérard Krawczyk",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies_pictures/50322-taxi-2-0-150-0-225-crop.jpg",
    releaseDate: "2000-03-31",
    rating: 0,
    length: 88,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Destination Finale",
    director: "James Wong",
    actors: [{ name: "Devon Sawa" }],
    coverUrl: "/movies_pictures/47068-final-destination-0-150-0-225-crop.jpg",
    releaseDate: "2000-03-17",
    rating: 0,
    length: 98,
    genre: "Horror",
    timesWatched: 5,
  },
  {
    title: "Mon voisin le tueur",
    director: "Jonathan Lynn",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/50554-the-whole-nine-yards-0-150-0-225-crop.jpg",
    releaseDate: "2000-02-18",
    rating: 0,
    length: 98,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "Scream 3",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies_pictures/49453-scream-3-0-150-0-225-crop.jpg",
    releaseDate: "2000-02-04",
    rating: 0,
    length: 116,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "La Ligne Verte",
    director: "Frank Darabont",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies_pictures/51613-the-green-mile-0-150-0-225-crop.jpg",
    releaseDate: "1999-12-10",
    rating: 0,
    length: 189,
    genre: "Drama",
    timesWatched: 5,
  },
  {
    title: "American Beauty",
    director: "Sam Mendes",
    actors: [{ name: "Kevin Spacey" }],
    coverUrl: "/movies_pictures/2703-american-beauty-0-150-0-225-crop.jpg",
    releaseDate: "1999-09-15",
    rating: 0,
    length: 122,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Sixième Sens",
    director: "M. Night Shyamalan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/51407-the-sixth-sense-0-150-0-225-crop.jpg",
    releaseDate: "1999-08-06",
    rating: 0,
    length: 107,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "American Pie",
    director: "Paul Weitz, Chris Weitz",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies_pictures/50521-american-pie-0-150-0-225-crop.jpg",
    releaseDate: "1999-07-09",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 20,
  },
  {
    title: "Wild Wild West",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/wild_wild_west.jpg",
    releaseDate: "1999-06-30",
    rating: 0,
    length: 106,
    genre: "Comedy",
    timesWatched: 20,
  },
  {
    title: "La Momie",
    director: "Stephen Sommers",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies_pictures/la_momie.jpg",
    releaseDate: "1999-05-07",
    rating: 0,
    length: 125,
    genre: "Adventure",
    timesWatched: 20,
  },
  {
    title: "Matrix",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies_pictures/51518-the-matrix-0-150-0-225-crop.jpg",
    releaseDate: "1999-03-31",
    rating: 0,
    length: 136,
    genre: "Science Fiction",
    timesWatched: 10,
  },
  {
    title: "Sex intentions",
    director: "Roger Kumble",
    actors: [{ name: "Sarah Michelle Gellar" }],
    coverUrl: "/movies_pictures/51356-cruel-intentions-0-150-0-225-crop.jpg",
    releaseDate: "1999-03-05",
    rating: 0,
    length: 97,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Rush Hour",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies_pictures/50517-rush-hour-0-150-0-225-crop.jpg",
    releaseDate: "1998-09-18",
    rating: 0,
    length: 98,
    genre: "Action",
    timesWatched: 30,
  },
  {
    title: "Blade",
    director: "Stephen Norrington",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies_pictures/27730-blade-0-150-0-225-crop.jpg",
    releaseDate: "1998-08-21",
    rating: 0,
    length: 120,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "L'arme fatale 4",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies_pictures/51209-lethal-weapon-4-0-150-0-225-crop.jpg",
    releaseDate: "1998-07-10",
    rating: 0,
    length: 127,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Armageddon",
    director: "Michael Bay",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/51955-armageddon-0-150-0-225-crop.jpg",
    releaseDate: "1998-07-01",
    rating: 0,
    length: 151,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "The Truman Show",
    director: "Peter Weir",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies_pictures/the-truman-show-0-150-0-225-crop.jpg",
    releaseDate: "1998-06-05",
    rating: 0,
    length: 103,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Godzilla",
    director: "Roland Emmerich",
    actors: [{ name: "Matthew Broderick" }],
    coverUrl: "/movies_pictures/51224-godzilla-0-150-0-225-crop.jpg",
    releaseDate: "1998-05-20",
    rating: 0,
    length: 139,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Le Dîner de Cons",
    director: "Francis Veber",
    actors: [{ name: "Thierry Lhermitte" }],
    coverUrl: "/movies_pictures/47176-the-dinner-game-0-150-0-225-crop.jpg",
    releaseDate: "1998-04-15",
    rating: 0,
    length: 80,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Taxi",
    director: "Gérard Pirès",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies_pictures/50324-taxi-0-150-0-225-crop.jpg",
    releaseDate: "1998-04-08",
    rating: 0,
    length: 86,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Code mercury",
    director: "Harold Becker",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/47583-mercury-rising-0-150-0-225-crop.jpg",
    releaseDate: "1998-04-03",
    rating: 0,
    length: 111,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "The Big Lebowski",
    director: "Joel Coen, Ethan Coen",
    actors: [{ name: "Jeff Bridges" }],
    coverUrl: "/movies_pictures/51935-the-big-lebowski-0-150-0-225-crop.jpg",
    releaseDate: "1998-03-06",
    rating: 0,
    length: 117,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Scream 2",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies_pictures/scream_2.jpg",
    releaseDate: "1997-12-12",
    rating: 0,
    length: 120,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Will Hunting",
    director: "Gus Van Sant",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies_pictures/51621-good-will-hunting-0-150-0-225-crop.jpg",
    releaseDate: "1997-12-05",
    rating: 0,
    length: 126,
    genre: "Drama",
    timesWatched: 15,
  },
  {
    title: "Alien : La Résurrection",
    director: "Jean-Pierre Jeunet",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies_pictures/47887-alien-resurrection-0-150-0-225-crop.jpg",
    releaseDate: "1997-11-26",
    rating: 0,
    length: 109,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "Je Sais ce que Vous Avez Fait l'Été Dernier",
    director: "Jim Gillespie",
    actors: [{ name: "Jennifer Love Hewitt" }],
    coverUrl: "/movies_pictures/49638-i-know-what-you-did-last-summer-0-150-0-225-crop.jpg",
    releaseDate: "1997-10-17",
    rating: 0,
    length: 101,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "L'Avocat du Diable",
    director: "Taylor Hackford",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies_pictures/50780-the-devil-s-advocate-0-150-0-225-crop.jpg",
    releaseDate: "1997-10-17",
    rating: 0,
    length: 144,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Men in Black",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/51514-men-in-black-0-150-0-225-crop.jpg",
    releaseDate: "1997-07-02",
    rating: 0,
    length: 98,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Le Cinquième Élément",
    director: "Luc Besson",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/le_cinquieme_element.jpg",
    releaseDate: "1997-05-09",
    rating: 0,
    length: 126,
    genre: "Science Fiction",
    timesWatched: 2,
  },
  {
    title: "Scream",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies_pictures/49455-scream-0-150-0-225-crop.jpg",
    releaseDate: "1996-12-20",
    rating: 0,
    length: 111,
    genre: "Horror",
    timesWatched: 2,
  },
];