import { Movie } from './movies_1';

export const moviesAnimated1: Movie[] = [
  {
    title: 'Dragons',
    director: 'Dean DeBlois, Chris Sanders',
    actors: [{ name: 'Jay Baruchel' }],
    coverUrl: '/movies_pictures/dragon.jpg',
    releaseDate: '2010-03-26',
    rating: 4,
    length: 98,
    genre: 'Animation',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Dragons 2',
    director: 'Dean DeBlois',
    actors: [{ name: 'Jay Baruchel' }],
    coverUrl:
      '/movies_pictures/69142-how-to-train-your-dragon-2-0-150-0-225-crop.jpg',
    releaseDate: '2014-06-13',
    rating: 3.5,
    length: 102,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Dragons 3: Le monde perdu',
    director: 'Dean DeBlois',
    actors: [
      {
        name: 'Jay Baruchel',
      },
    ],
    coverUrl:
      '/movies_pictures/123067-how-to-train-your-dragon-the-hidden-world-0-150-0-225-crop.jpg',
    releaseDate: '2019-02-22',
    rating: 3.5,
    length: 104,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    actors: [
      {
        name: 'Shameik Moore',
      },
    ],
    coverUrl:
      '/movies_pictures/251943-spider-man-into-the-spider-verse-0-150-0-225-crop.jpg',
    releaseDate: '2018-12-14',
    rating: 4,
    length: 117,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Spider-Man : À Travers le Spider-Verse',
    director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    actors: [
      {
        name: 'Shameik Moore',
      },
    ],
    coverUrl:
      '/movies_pictures/497631-spider-man-across-the-spider-verse-0-150-0-225-crop.jpg',
    releaseDate: '2023-06-02',
    rating: 4,
    length: 140,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les Mondes de Ralph',
    director: 'Rich Moore',
    actors: [{ name: 'John C. Reilly' }],
    coverUrl: '/movies_pictures/69154-wreck-it-ralph-0-150-0-225-crop.jpg',
    releaseDate: '2012-11-02',
    rating: 3.5,
    length: 101,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Ralph Breaks the Internet',
    director: 'Rich Moore, Phil Johnston',
    actors: [
      {
        name: 'John C. Reilly',
      },
    ],
    coverUrl:
      '/movies_pictures/338883-ralph-breaks-the-internet-0-150-0-225-crop.jpg',
    releaseDate: '2018-11-21',
    rating: 3.25,
    length: 112,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Super Mario Bros. le Film',
    director: 'Aaron Horvath, Michael Jelenic',
    actors: [
      {
        name: 'Chris Pratt',
      },
    ],
    coverUrl:
      '/movies_pictures/432302-the-super-mario-bros-movie-0-150-0-225-crop.jpg',
    releaseDate: '2023-04-05',
    rating: 4,
    length: 92,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Encanto',
    director: 'Jared Bush, Byron Howard',
    actors: [
      {
        name: 'Stephanie Beatriz',
      },
    ],
    coverUrl: '/movies_pictures/496592-encanto-0-150-0-225-crop.jpg',
    releaseDate: '2021-11-24',
    rating: 3.25,
    length: 102,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Cars',
    director: 'John Lasseter',
    actors: [{ name: 'Owen Wilson' }],
    coverUrl:
      '/movies_pictures/dWg33ektXuHmxjSjEulwDPTWbC2-0-150-0-225-crop.jpg',
    releaseDate: '2006-06-09',
    rating: 3.75,
    length: 117,
    genre: 'Animation',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Cars 3',
    director: 'Brian Fee',
    actors: [{ name: 'Owen Wilson' }],
    coverUrl: '/movies_pictures/184062-cars-3-0-150-0-225-crop.jpg',
    releaseDate: '2016-06-16',
    rating: 3.5,
    length: 102,
    genre: 'Animation',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Baby boss',
    director: 'Tom McGrath',
    actors: [{ name: 'Alec Baldwin' }],
    coverUrl: '/movies_pictures/223050-the-boss-baby-0-150-0-225-crop.jpg',
    releaseDate: '2017-03-31',
    rating: 3,
    length: 97,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Vaiana',
    director: 'Ron Clements, John Musker',
    actors: [{ name: "Auli'i Cravalho" }],
    coverUrl: '/movies_pictures/201909-moana-0-150-0-225-crop.jpg',
    releaseDate: '2016-11-23',
    rating: 3.25,
    length: 107,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Vice-Versa',
    director: 'Pete Docter',
    actors: [{ name: 'Amy Poehler' }],
    coverUrl: '/movies_pictures/113284-inside-out-0-150-0-225-crop.jpg',
    releaseDate: '2015-06-19',
    rating: 3.75,
    length: 95,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les Nouveaux Héros',
    director: 'Don Hall, Chris Williams',
    actors: [{ name: 'Ryan Potter' }],
    coverUrl: '/movies_pictures/les_nouveaux_heros.jpg',
    releaseDate: '2014-11-07',
    rating: 3.75,
    length: 102,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'La Reine des Neiges',
    director: 'Chris Buck, Jennifer Lee',
    actors: [{ name: 'Kristen Bell' }],
    coverUrl: '/movies_pictures/reine_des_neiges.jpg',
    releaseDate: '2013-11-27',
    rating: 3.25,
    length: 102,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Moi, Moche et Méchant',
    director: 'Pierre Coffin, Chris Renaud',
    actors: [{ name: 'Steve Carell' }],
    coverUrl: '/movies_pictures/39067-despicable-me-0-150-0-225-crop.jpg',
    releaseDate: '2010-07-09',
    rating: 3.25,
    length: 95,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Moi, Moche et Méchant 2',
    director: 'Pierre Coffin, Chris Renaud',
    actors: [{ name: 'Steve Carell' }],
    coverUrl: '/movies_pictures/moi_moi_mechant_2.jpg',
    releaseDate: '2013-07-03',
    rating: 3,
    length: 98,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les Cinq Légendes',
    director: 'Peter Ramsey',
    actors: [{ name: 'Chris Pine' }],
    coverUrl: '/movies_pictures/les_cinq_legendes.jpg',
    releaseDate: '2012-11-21',
    rating: 3.5,
    length: 97,
    genre: 'Animation',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: "L'Âge de Glace",
    director: 'Chris Wedge, Carlos Saldanha',
    actors: [{ name: 'Ray Romano' }],
    coverUrl: '/movies_pictures/51670-ice-age-0-150-0-225-crop.jpg',
    releaseDate: '2002-03-15',
    rating: 4.25,
    length: 81,
    genre: 'Animation',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: "L'Âge de Glace 2",
    director: 'Carlos Saldanha',
    actors: [{ name: 'Ray Romano' }],
    coverUrl: '/movies_pictures/age_de_glace_2.jpg',
    releaseDate: '2006-03-31',
    rating: 4,
    length: 91,
    genre: 'Animation',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: "L'Âge de Glace 3 : Le Temps des Dinosaures",
    director: 'Carlos Saldanha',
    actors: [{ name: 'Ray Romano' }],
    coverUrl:
      '/movies_pictures/47781-ice-age-dawn-of-the-dinosaurs-0-150-0-225-crop.jpg',
    releaseDate: '2009-07-01',
    rating: 4,
    length: 94,
    genre: 'Animation',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: "L'Âge de Glace 4 : La Dérive des Continents",
    director: 'Steve Martino, Mike Thurmeier',
    actors: [{ name: 'Ray Romano' }],
    coverUrl: '/movies_pictures/age_de_glace_4.jpg',
    releaseDate: '2012-07-13',
    rating: 3.75,
    length: 88,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Rebelle',
    director: 'Mark Andrews, Brenda Chapman',
    actors: [{ name: 'Kelly Macdonald' }],
    coverUrl: '/movies_pictures/rebelle.jpg',
    releaseDate: '2012-06-22',
    rating: 3,
    length: 93,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Arthur et les Minimoys',
    director: 'Luc Besson',
    actors: [{ name: 'Freddie Highmore' }],
    coverUrl:
      '/movies_pictures/46649-arthur-and-the-invisibles-0-150-0-225-crop.jpg',
    releaseDate: '2006-12-13',
    rating: 4.25,
    length: 94,
    genre: 'Fantasy',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Arthur et la Vengeance de Maltazard',
    director: 'Luc Besson',
    actors: [{ name: 'Freddie Highmore' }],
    coverUrl:
      '/movies_pictures/35270-arthur-and-the-revenge-of-maltazard-0-150-0-225-crop.jpg',
    releaseDate: '2009-12-02',
    rating: 3.25,
    length: 94,
    genre: 'Adventure',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Arthur 3 : La Guerre des Deux Mondes',
    director: 'Luc Besson',
    actors: [{ name: 'Freddie Highmore' }],
    coverUrl:
      '/movies_pictures/22170-arthur-3-the-war-of-the-two-worlds-0-150-0-225-crop.jpg',
    releaseDate: '2010-10-13',
    rating: 3.25,
    length: 101,
    genre: 'Adventure',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'La Princesse et la Grenouille',
    director: 'Ron Clements, John Musker',
    actors: [{ name: 'Anika Noni Rose' }],
    coverUrl:
      '/movies_pictures/bVRHirC6uIZL9VtRqYRxdedYnOG-0-150-0-225-crop.jpg',
    releaseDate: '2009-12-11',
    rating: 3,
    length: 97,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Tempête de Boulettes Géantes',
    director: 'Phil Lord, Christopher Miller',
    actors: [{ name: 'Bill Hader' }],
    coverUrl:
      '/movies_pictures/37696-cloudy-with-a-chance-of-meatballs-0-150-0-225-crop.jpg',
    releaseDate: '2009-09-18',
    rating: 3.25,
    length: 90,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Monstres contre Aliens',
    director: 'Rob Letterman, Conrad Vernon',
    actors: [{ name: 'Reese Witherspoon' }],
    coverUrl: '/movies_pictures/42315-monsters-vs-aliens-0-150-0-225-crop.jpg',
    releaseDate: '2009-03-27',
    rating: 4,
    length: 94,
    genre: 'Animation',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'WALL-E',
    director: 'Andrew Stanton',
    actors: [{ name: 'Ben Burtt' }],
    coverUrl: '/movies_pictures/45994-walle-0-150-0-225-crop.jpg',
    releaseDate: '2008-06-27',
    rating: 3.75,
    length: 98,
    genre: 'Animation',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Kung Fu Panda',
    director: 'Mark Osborne, John Stevenson',
    actors: [{ name: 'Jack Black' }],
    coverUrl:
      '/movies_pictures/mk3UyyaLyXhgIhmLji25OUPXvGR-0-150-0-225-crop.jpg',
    releaseDate: '2008-06-06',
    rating: 3.5,
    length: 92,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "Bee Movie : Drôle d'Abeille",
    director: 'Steve Hickner, Simon J. Smith',
    actors: [{ name: 'Jerry Seinfeld' }],
    coverUrl: '/movies_pictures/48791-bee-movie-0-150-0-225-crop.jpg',
    releaseDate: '2007-11-02',
    rating: 2.5,
    length: 91,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les Simpson, le Film',
    director: 'David Silverman',
    actors: [{ name: 'Dan Castellaneta' }],
    coverUrl: '/movies_pictures/2684-the-simpsons-movie-0-150-0-225-crop.jpg',
    releaseDate: '2007-07-27',
    rating: 4.5,
    length: 87,
    genre: 'Animation',
    timesWatched: 40,
    lastViewedDate: '',
  },
  {
    title: 'Ratatouille',
    director: 'Brad Bird',
    actors: [{ name: 'Patton Oswalt' }],
    coverUrl: '/movies_pictures/ratatouille.jpg',
    releaseDate: '2007-06-29',
    rating: 3.75,
    length: 111,
    genre: 'Animation',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Shrek',
    director: 'Andrew Adamson, Vicky Jenson',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/51344-shrek-0-150-0-225-crop.jpg',
    releaseDate: '2001-05-18',
    rating: 4,
    length: 90,
    genre: 'Animation',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Shrek 2',
    director: 'Andrew Adamson, Kelly Asbury, Conrad Vernon',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/shrek_2.jpg',
    releaseDate: '2004-05-19',
    rating: 3.5,
    length: 93,
    genre: 'Animation',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Shrek le Troisième',
    director: 'Chris Miller',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/shrek_3.jpg',
    releaseDate: '2007-05-18',
    rating: 3.25,
    length: 93,
    genre: 'Animation',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Shrek 4 : Il Était une Fois',
    director: 'Mike Mitchell',
    actors: [{ name: 'Mike Myers' }],
    coverUrl: '/movies_pictures/shrek_4.jpg',
    releaseDate: '2010-05-21',
    rating: 3,
    length: 93,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
