import { Movie } from './movies_1';

export const moviesPage6: Movie[] = [
  {
    title: 'Prédictions',
    director: 'Alex Proyas',
    actors: [{ name: 'Nicolas Cage' }],
    coverUrl: '/movies_pictures/43577-knowing-0-150-0-225-crop.jpg',
    releaseDate: '2009-03-20',
    rating: 3.25,
    length: 121,
    genre: 'Science Fiction',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'I Love You Phillip Morris',
    director: 'Glenn Ficarra, John Requa',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl: '/movies_pictures/i_love_you_philipp_morris.jpg',
    releaseDate: '2009-01-30',
    rating: 3.5,
    length: 98,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Sept Vies',
    director: 'Gabriele Muccino',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/45412-seven-pounds-0-150-0-225-crop.jpg',
    releaseDate: '2008-12-19',
    rating: 3.75,
    length: 123,
    genre: 'Drama',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Yes Man',
    director: 'Peyton Reed',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl: '/movies_pictures/yes-man-0-150-0-225-crop.jpg',
    releaseDate: '2008-12-19',
    rating: 3.25,
    length: 104,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Gran Torino',
    director: 'Clint Eastwood',
    actors: [{ name: 'Clint Eastwood' }],
    coverUrl: '/movies_pictures/gran_torino.jpg',
    releaseDate: '2008-12-12',
    rating: 3,
    length: 116,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Ong Bak 2',
    director: 'Tony Jaa',
    actors: [{ name: 'Tony Jaa' }],
    coverUrl: '/movies_pictures/41625-ong-bak-2-0-150-0-225-crop.jpg',
    releaseDate: '2008-12-05',
    rating: 2.5,
    length: 98,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },

  {
    title: 'Eagle Eye',
    director: 'D.J. Caruso',
    actors: [{ name: 'Shia LaBeouf' }],
    coverUrl: '/movies_pictures/44201-eagle-eye-0-150-0-225-crop.jpg',
    releaseDate: '2008-09-26',
    rating: 4.5,
    length: 118,
    genre: 'Thriller',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Slumdog Millionaire',
    director: 'Danny Boyle',
    actors: [{ name: 'Dev Patel' }],
    coverUrl: '/movies_pictures/44613-slumdog-millionaire-0-150-0-225-crop.jpg',
    releaseDate: '2008-12-25',
    rating: 4,
    length: 120,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Course à la mort',
    director: 'Paul W.S. Anderson',
    actors: [{ name: 'Jason Statham' }],
    coverUrl: '/movies_pictures/46186-death-race-0-150-0-225-crop.jpg',
    releaseDate: '2008-08-22',
    rating: 3.5,
    length: 105,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Voyage au Centre de la Terre',
    director: 'Eric Brevig',
    actors: [{ name: 'Brendan Fraser' }],
    coverUrl:
      '/movies_pictures/74826-journey-to-the-center-of-the-earth-0-150-0-225-crop.jpg',
    releaseDate: '2008-07-11',
    rating: 3.5,
    length: 93,
    genre: 'Adventure',
    timesWatched: 5,
    lastViewedDate: '2025-01-11',
  },
  {
    title: 'Wanted : Choisis ton Destin',
    director: 'Timur Bekmambetov',
    actors: [{ name: 'James McAvoy' }],
    coverUrl: '/movies_pictures/wanted.jpg',
    releaseDate: '2008-06-27',
    rating: 3,
    length: 110,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Rien que pour vos cheveux',
    director: 'Dennis Dugan',
    actors: [{ name: 'Adam Sandler' }],
    coverUrl: '/movies_pictures/dont-mess-with-the-zohan-0-150-0-225-crop.jpg',
    releaseDate: '2008-06-06',
    rating: 3.25,
    length: 113,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Speed Racer',
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: [{ name: 'Emile Hirsch' }],
    coverUrl: '/movies_pictures/48018-speed-racer-0-150-0-225-crop.jpg',
    releaseDate: '2008-05-09',
    rating: 3,
    length: 135,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'La vague',
    director: 'Dennis Gansel',
    actors: [{ name: 'Jürgen Vogel' }],
    coverUrl: '/movies_pictures/47981-the-wave-0-150-0-225-crop.jpg',
    releaseDate: '2008-03-13',
    rating: 3.25,
    length: 107,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Never Back Down',
    director: 'Jeff Wadlow',
    actors: [{ name: 'Sean Faris' }],
    coverUrl: '/movies_pictures/47713-never-back-down-0-150-0-225-crop.jpg',
    releaseDate: '2008-03-14',
    rating: 4,
    length: 110,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Jumper',
    director: 'Doug Liman',
    actors: [{ name: 'Hayden Christensen' }],
    coverUrl: '/movies_pictures/47842-jumper-0-150-0-225-crop.jpg',
    releaseDate: '2008-02-14',
    rating: 3.5,
    length: 88,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Je Suis une Légende',
    director: 'Francis Lawrence',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/48296-i-am-legend-0-150-0-225-crop.jpg',
    releaseDate: '2007-12-14',
    rating: 3.75,
    length: 101,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Paranormal Activity',
    director: 'Oren Peli',
    actors: [{ name: 'Katie Featherston' }],
    coverUrl: '/movies_pictures/paranormal_activity.jpg',
    releaseDate: '2007-10-14',
    rating: 2.5,
    length: 86,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Gone Baby Gone',
    director: 'Ben Affleck',
    actors: [{ name: 'Casey Affleck' }],
    coverUrl: '/movies_pictures/gone_baby_gone.jpg',
    releaseDate: '2007-10-19',
    rating: 3.5,
    length: 114,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Into the Wild',
    director: 'Sean Penn',
    actors: [{ name: 'Emile Hirsch' }],
    coverUrl: '/movies_pictures/48571-into-the-wild-0-150-0-225-crop.jpg',
    releaseDate: '2007-09-21',
    rating: 3.5,
    length: 148,
    genre: 'Drama',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'La chambre 1408',
    director: 'Mikael Håfström',
    actors: [{ name: 'John Cusack' }],
    coverUrl: '/movies_pictures/49944-1408-0-150-0-225-crop.jpg',
    releaseDate: '2007-06-22',
    rating: 3.25,
    length: 104,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Evan tout-puissant',
    director: 'Tom Shadyac',
    actors: [{ name: 'Steve Carell' }],
    coverUrl: '/movies_pictures/50146-evan-almighty-0-150-0-225-crop.jpg',
    releaseDate: '2007-06-22',
    rating: 2,
    length: 95,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'No Country for Old Men',
    director: 'Joel Coen, Ethan Coen',
    actors: [{ name: 'Tommy Lee Jones' }],
    coverUrl: '/movies_pictures/no_country_for_old_men.jpg',
    releaseDate: '2007-11-09',
    rating: 2.75,
    length: 122,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '2025-04-09',
  },
  {
    title: '28 Semaines Plus Tard',
    director: 'Juan Carlos Fresnadillo',
    actors: [{ name: 'Robert Carlyle' }],
    coverUrl: '/movies_pictures/28_jours_plus_tard.jpg',
    releaseDate: '2007-05-11',
    rating: 3,
    length: 100,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Dangereuse séduction',
    director: 'James Foley',
    actors: [{ name: 'Halle Berry' }],
    coverUrl: '/movies_pictures/48107-perfect-stranger-0-150-0-225-crop.jpg',
    releaseDate: '2007-04-13',
    rating: 3,
    length: 109,
    genre: 'Thriller',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Paranoïak',
    director: 'D.J. Caruso',
    actors: [{ name: 'Shia LaBeouf' }],
    coverUrl: '/movies_pictures/47835-disturbia-0-150-0-225-crop.jpg',
    releaseDate: '2007-04-13',
    rating: 3.25,
    length: 105,
    genre: 'Thriller',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Supergrave',
    director: 'Greg Mottola',
    actors: [{ name: 'Jonah Hill' }],
    coverUrl: '/movies_pictures/47776-superbad-0-150-0-225-crop.jpg',
    releaseDate: '2007-08-17',
    rating: 2.5,
    length: 113,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Zodiac',
    director: 'David Fincher',
    actors: [{ name: 'Jake Gyllenhaal' }],
    coverUrl: '/movies_pictures/zodiac.jpg',
    releaseDate: '2007-03-02',
    rating: 3,
    length: 157,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Premonition',
    director: 'Mennan Yapo',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/46675-premonition-0-150-0-225-crop.jpg',
    releaseDate: '2007-03-16',
    rating: 3.25,
    length: 96,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Ecrire pour exister',
    director: 'Richard LaGravenese',
    actors: [{ name: 'Hilary Swank' }],
    coverUrl: '/movies_pictures/50896-freedom-writers-0-150-0-225-crop.jpg',
    releaseDate: '2007-01-05',
    rating: 3.25,
    length: 123,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "L'effaceur",
    director: 'Chuck Russell',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/47324-eraser-0-150-0-225-crop.jpg',
    releaseDate: '1996-06-21',
    rating: 3.75,
    length: 115,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'La quête',
    director: 'Jean-Claude Van Damme',
    actors: [{ name: 'Jean-Claude Van Damme' }],
    coverUrl: '/movies_pictures/47342-the-quest-0-150-0-225-crop.jpg',
    releaseDate: '1996-04-26',
    rating: 3,
    length: 95,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Trainspotting',
    director: 'Danny Boyle',
    actors: [{ name: 'Ewan McGregor' }],
    coverUrl: '/movies_pictures/51497-trainspotting-0-150-0-225-crop.jpg',
    releaseDate: '1996-02-23',
    rating: 2.5,
    length: 93,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Jumanji',
    director: 'Joe Johnston',
    actors: [{ name: 'Robin Williams' }],
    coverUrl: '/movies_pictures/jumanji.jpg',
    releaseDate: '1995-12-15',
    rating: 3,
    length: 104,
    genre: 'Adventure',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Seven',
    director: 'David Fincher',
    actors: [{ name: 'Brad Pitt' }],
    coverUrl: '/movies_pictures/51345-se7en-0-150-0-225-crop.jpg',
    releaseDate: '1995-09-22',
    rating: 4,
    length: 127,
    genre: 'Crime',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'The Net',
    director: 'Irwin Winkler',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/50900-the-net-0-150-0-225-crop.jpg',
    releaseDate: '1995-07-28',
    rating: 3.25,
    length: 114,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Waterworld',
    director: 'Kevin Reynolds',
    actors: [{ name: 'Kevin Costner' }],
    coverUrl: '/movies_pictures/waterworld.jpg',
    releaseDate: '1995-07-28',
    rating: 3,
    length: 135,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Piège à grande vitesse',
    director: 'Geoff Murphy',
    actors: [{ name: 'Steven Seagal' }],
    coverUrl:
      '/movies_pictures/49707-under-siege-2-dark-territory-0-150-0-225-crop.jpg',
    releaseDate: '1995-07-14',
    rating: 3.25,
    length: 100,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Judge Dredd',
    director: 'Danny Cannon',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/judge_dredd.jpg',
    releaseDate: '1995-06-30',
    rating: 3.5,
    length: 96,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },

  {
    title: 'The Usual Suspects',
    director: 'Bryan Singer',
    actors: [{ name: 'Kevin Spacey' }],
    coverUrl: '/movies_pictures/51495-the-usual-suspects-0-150-0-225-crop.jpg',
    releaseDate: '1995-08-16',
    rating: 3.25,
    length: 106,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Street Fighter',
    director: 'Steven E. de Souza',
    actors: [{ name: 'Jean-Claude Van Damme' }],
    coverUrl: '/movies_pictures/45086-street-fighter-0-150-0-225-crop.jpg',
    releaseDate: '1994-12-23',
    rating: 2.75,
    length: 102,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Un indien dans la ville',
    director: 'Hervé Palud',
    actors: [{ name: 'Thierry Lhermitte' }],
    coverUrl:
      '/movies_pictures/45265-little-indian-big-city-0-150-0-225-crop.jpg',
    releaseDate: '1994-12-14',
    rating: 3.5,
    length: 85,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Dumb & Dumber',
    director: 'Peter Farrelly, Bobby Farrelly',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl:
      '/movies_pictures/st4P2TtPrAfNwu8HLXoPsPPii42-0-150-0-225-crop.jpg',
    releaseDate: '1994-12-16',
    rating: 3,
    length: 107,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
