import { Movie } from "./movies_1";

export const moviesBigSagas: Movie[] = [
  {
    title: "Harry Potter à l'école des sorciers",
    director: "Chris Columbus",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/harry_potter_ecole_des_sorciers.jpg",
    releaseDate: "2001-11-16",
    rating: 0,
    length: 152,
    genre: "Fantasy",
    timesWatched: 30,
  },
  {
    title: "Harry Potter et la chambre des secrets",
    director: "Chris Columbus",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/harry_potter_chambre_des_secrets.jpg",
    releaseDate: "2002-11-15",
    rating: 0,
    length: 161,
    genre: "Fantasy",
    timesWatched: 30,
  },
  {
    title: "Harry Potter et le prisonnier d'Azkaban",
    director: "Alfonso Cuarón",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/harry_potter_prisonnier_askaban.jpg",
    releaseDate: "2004-06-04",
    rating: 0,
    length: 142,
    genre: "Fantasy",
    timesWatched: 30,
  },
  {
    title: "Harry Potter et la coupe de feu",
    director: "Mike Newell",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/51450-harry-potter-and-the-goblet-of-fire-0-150-0-225-crop.jpg",
    releaseDate: "2005-11-18",
    rating: 0,
    length: 157,
    genre: "Fantasy",
    timesWatched: 20,
  },
  {
    title: "Harry Potter et l'ordre du phénix",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/harry_potter_ordre_du_phenix.jpg",
    releaseDate: "2007-07-11",
    rating: 0,
    length: 138,
    genre: "Fantasy",
    timesWatched: 20,
  },
  {
    title: "Harry Potter et le prince de sang-mêlé",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/51385-harry-potter-and-the-half-blood-prince-0-150-0-225-crop.jpg",
    releaseDate: "2009-07-15",
    rating: 0,
    length: 153,
    genre: "Fantasy",
    timesWatched: 15,
  },
  {
    title: "Harry Potter et les reliques de la mort - partie 1",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/harry-potter-and-the-deathly-hallows-part-i-original-0-150-0-225-crop.jpg",
    releaseDate: "2010-11-19",
    rating: 0,
    length: 146,
    genre: "Fantasy",
    timesWatched: 10,
  },
  {
    title: "Harry Potter et les reliques de la mort - partie 2",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies_pictures/validated/44580-harry-potter-and-the-deathly-hallows-part-2-0-150-0-225-crop.jpg",
    releaseDate: "2011-07-15",
    rating: 0,
    length: 130,
    genre: "Fantasy",
    timesWatched: 10,
  },
  {
    title: "Star Wars : Épisode 1 - La menace fantôme",
    director: "George Lucas",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies_pictures/validated/50711-star-wars-episode-i-the-phantom-menace-0-150-0-225-crop.jpg",
    releaseDate: "1999-05-19",
    rating: 0,
    length: 136,
    genre: "Science Fiction",
    timesWatched: 30,
  },
  {
    title: "Star Wars: Episode 2 - L'attaque des clones",
    director: "George Lucas",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies_pictures/validated/50710-star-wars-episode-ii-attack-of-the-clones-0-150-0-225-crop.jpg",
    releaseDate: "2002-05-16",
    rating: 0,
    length: 142,
    genre: "Science Fiction",
    timesWatched: 30,
  },
  {
    title: "Star Wars : Épisode 3 - La revanche des Sith",
    director: "George Lucas",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies_pictures/validated/50709-star-wars-episode-iii-revenge-of-the-sith-0-150-0-225-crop.jpg",
    releaseDate: "2005-05-19",
    rating: 0,
    length: 140,
    genre: "Science Fiction",
    timesWatched: 30,
  },
  {
    title: "Star Wars : Episode 4 - Un nouvel espoir",
    director: "George Lucas",
    actors: [{ name: "Mark Hamill" }],
    coverUrl: "/movies_pictures/validated/star_wars_nouvel_espoir.jpg",
    releaseDate: "1977-05-25",
    rating: 0,
    length: 121,
    genre: "Science Fiction",
    timesWatched: 10,
  },
  {
    title: "Star Wars : Episode 5 - L'empire contre-attaque",
    director: "Irvin Kershner",
    actors: [{ name: "Mark Hamill" }],
    coverUrl: "/movies_pictures/validated/star_wars_empire_contre_attaque.jpg",
    releaseDate: "1980-05-21",
    rating: 0,
    length: 124,
    genre: "Science Fiction",
    timesWatched: 15,
  },
  {
    title: "Star Wars : Episode 6 - Le retour du Jedi",
    director: "Richard Marquand",
    actors: [{ name: "Mark Hamill" }],
    coverUrl: "/movies_pictures/validated/star_wars_retour_du_jedi.jpg",
    releaseDate: "1983-05-25",
    rating: 0,
    length: 131,
    genre: "Science Fiction",
    timesWatched: 30,
  },
  {
    title: "Star Wars : Episode 7 - Le réveil de la Force",
    director: "J.J. Abrams",
    actors: [{ name: "Daisy Ridley" }],
    coverUrl: "/movies_pictures/validated/star_wars_le_reveil_de_la_force.jpg",
    releaseDate: "2015-12-18",
    rating: 0,
    length: 138,
    genre: "Science Fiction",
    timesWatched: 3,
  },
  {
    title: "Star Wars : Episode 8 - Le dernier Jedi",
    director: "Rian Johnson",
    actors: [
      {
        name: "Daisy Ridley",
      },
    ],
    coverUrl: "/movies_pictures/validated/star_wars_le_dernier_jedi.jpg",
    releaseDate: "2017-12-15",
    rating: 0,
    length: 0,
    genre: "Science Fiction",
    timesWatched: 2,
  },
  {
    title: "Star Wars : Episode 9 - L'ascension de Skywalker",
    director: "J.J. Abrams",
    actors: [
      {
        name: "Daisy Ridley",
      },
    ],
    coverUrl: "/movies_pictures/validated/131984-star-wars-the-rise-of-skywalker-0-150-0-225-crop.jpg",
    releaseDate: "2019-12-20",
    rating: 0,
    length: 0,
    genre: "Science Fiction",
    timesWatched: 2,
  },
  {
    title: "Solo: A Star Wars Story",
    director: "Ron Howard",
    actors: [
      {
        name: "Alden Ehrenreich",
      },
    ],
    coverUrl: "/movies_pictures/validated/278668-solo-a-star-wars-story-0-150-0-225-crop.jpg",
    releaseDate: "2018-05-25",
    rating: 0,
    length: 0,
    genre: "Science Fiction",
    timesWatched: 1,
  },
  {
    title: "Rogue One : A Star Wars Story",
    director: "Gareth Edwards",
    actors: [{ name: "Felicity Jones" }],
    coverUrl: "/movies_pictures/validated/258128-rogue-one-a-star-wars-story-0-150-0-225-crop.jpg",
    releaseDate: "2016-12-16",
    rating: 0,
    length: 133,
    genre: "Science Fiction",
    timesWatched: 1,
  },
  {
    title: "Fast and Furious",
    director: "Rob Cohen",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies_pictures/validated/46813-the-fast-and-the-furious-0-150-0-225-crop.jpg",
    releaseDate: "2001-06-22",
    rating: 0,
    length: 106,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "2 Fast 2 Furious",
    director: "John Singleton",
    actors: [{ name: "Paul Walker" }],
    coverUrl: "/movies_pictures/validated/51536-2-fast-2-furious-0-150-0-225-crop.jpg",
    releaseDate: "2003-06-06",
    rating: 0,
    length: 107,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Fast and Furious : Tokyo Drift",
    director: "Justin Lin",
    actors: [{ name: "Lucas Black" }],
    coverUrl: "/movies_pictures/validated/46986-the-fast-and-the-furious-tokyo-drift-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-16",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Fast & Furious 4",
    director: "Justin Lin",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies_pictures/validated/43582-fast-furious-0-150-0-225-crop.jpg",
    releaseDate: "2009-04-03",
    rating: 0,
    length: 107,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Fast & Furious 5",
    director: "Justin Lin",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies_pictures/validated/fast_furious_cinq.jpg",
    releaseDate: "2011-04-29",
    rating: 0,
    length: 130,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Fast & Furious 6",
    director: "Justin Lin",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies_pictures/validated/69453-fast-furious-6-0-150-0-225-crop.jpg",
    releaseDate: "2013-05-24",
    rating: 0,
    length: 130,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Fast & Furious 7",
    director: "James Wan",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies_pictures/validated/124133-furious-7-0-150-0-225-crop.jpg",
    releaseDate: "2015-04-03",
    rating: 0,
    length: 137,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Fast & Furious Presents: Hobbs & Shaw",
    director: "David Leitch",
    actors: [
      {
        name: "Dwayne Johnson",
      },
    ],
    coverUrl: "/movies_pictures/validated/318913-fast-furious-presents-hobbs-shaw-0-150-0-225-crop.jpg",
    releaseDate: "2019-08-02",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Fast & Furious 9",
    director: "Justin Lin",
    actors: [
      {
        name: "Vin Diesel",
      },
    ],
    coverUrl: "/movies_pictures/validated/fast_and_furious_9.jpg",
    releaseDate: "2021-06-25",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Fast & Furious X",
    director: "Louis Leterrier",
    actors: [
      {
        name: "Vin Diesel",
      },
    ],
    coverUrl: "/movies_pictures/validated/320481-fast-x-0-150-0-225-crop.jpg",
    releaseDate: "2023-05-19",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Rocky",
    director: "John G. Avildsen",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/rocky.jpg",
    releaseDate: "1976-11-21",
    rating: 0,
    length: 120,
    genre: "Drama",
    timesWatched: 5,
  },
  {
    title: "Rocky II",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/51089-rocky-ii-0-150-0-225-crop.jpg",
    releaseDate: "1979-06-15",
    rating: 0,
    length: 119,
    genre: "Drama",
    timesWatched: 3,
  },
  {
    title: "Rocky III",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/eX2RbfTV5figCysWEmC6ubmXIgm-0-150-0-225-crop.jpg",
    releaseDate: "1982-05-28",
    rating: 0,
    length: 99,
    genre: "Drama",
    timesWatched: 15,
  },
  {
    title: "Rocky IV",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/51082-rocky-iv-0-150-0-225-crop.jpg",
    releaseDate: "1985-11-27",
    rating: 0,
    length: 91,
    genre: "Drama",
    timesWatched: 30,
  },
  {
    title: "Rocky V",
    director: "John G. Avildsen",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/51081-rocky-v-0-150-0-225-crop.jpg",
    releaseDate: "1990-11-16",
    rating: 0,
    length: 104,
    genre: "Drama",
    timesWatched: 3,
  },
  {
    title: "Rocky Balboa",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/51134-rocky-balboa-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-20",
    rating: 0,
    length: 102,
    genre: "Drama",
    timesWatched: 20,
  },
  {
    title: "The Terminator",
    director: "James Cameron",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/the-terminator-original-0-150-0-225-crop.jpg",
    releaseDate: "1984-10-26",
    rating: 0,
    length: 107,
    genre: "Science Fiction",
    timesWatched: 3,
  },
  {
    title: "Terminator 2: Judgment Day",
    director: "James Cameron",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/terminator-2-judgment-day-original-0-150-0-225-crop.jpg",
    releaseDate: "1991-07-03",
    rating: 0,
    length: 137,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Terminator 3: Rise of the Machines",
    director: "Jonathan Mostow",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/51763-terminator-3-rise-of-the-machines-0-150-0-225-crop.jpg",
    releaseDate: "2003-07-02",
    rating: 0,
    length: 109,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Terminator Renaissance",
    director: "McG",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies_pictures/validated/51583-terminator-salvation-0-150-0-225-crop.jpg",
    releaseDate: "2009-05-21",
    rating: 0,
    length: 115,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Terminator Genisys",
    director: "Alan Taylor",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/73594-terminator-genisys-0-150-0-225-crop.jpg",
    releaseDate: "2015-07-01",
    rating: 0,
    length: 126,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Terminator: Dark Fate",
    director: "Tim Miller",
    actors: [
      {
        name: "Linda Hamilton",
      },
    ],
    coverUrl: "/movies_pictures/validated/217178-terminator-dark-fate-0-150-0-225-crop.jpg",
    releaseDate: "2019-11-01",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
]