import { Movie } from './movies_1';

export const moviesPage8: Movie[] = [
  {
    title: 'DodgeBall: Même pas mal',
    director: 'Rawson Marshall Thurber',
    actors: [{ name: 'Vince Vaughn' }],
    coverUrl: '/movies_pictures/dodgeball.jpg',
    releaseDate: '2004-06-18',
    rating: 3.75,
    length: 92,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Garfield',
    director: 'Peter Hewitt',
    actors: [{ name: 'Bill Murray' }],
    coverUrl: '/movies_pictures/47508-garfield-0-150-0-225-crop.jpg',
    releaseDate: '2004-06-11',
    rating: 3,
    length: 80,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Harold & Kumar Go to White Castle',
    director: 'Danny Leiner',
    actors: [{ name: 'John Cho' }],
    coverUrl: '/movies_pictures/harold_et_kumar_white_castle.jpg',
    releaseDate: '2004-07-30',
    rating: 3,
    length: 88,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'The Day After Tomorrow',
    director: 'Roland Emmerich',
    actors: [{ name: 'Dennis Quaid' }],
    coverUrl: '/movies_pictures/le_jour_d_apres.jpg',
    releaseDate: '2004-05-28',
    rating: 4.75,
    length: 124,
    genre: 'Science Fiction',
    timesWatched: 30,
    lastViewedDate: '2025-02-28',
  },
  {
    title: 'Van Helsing',
    director: 'Stephen Sommers',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl: '/movies_pictures/48113-van-helsing-0-150-0-225-crop.jpg',
    releaseDate: '2004-05-07',
    rating: 3.25,
    length: 131,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Man on Fire',
    director: 'Tony Scott',
    actors: [{ name: 'Denzel Washington' }],
    coverUrl: '/movies_pictures/man_on_fire.jpg',
    releaseDate: '2004-04-23',
    rating: 3.25,
    length: 146,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Shaun of the Dead',
    director: 'Edgar Wright',
    actors: [{ name: 'Simon Pegg' }],
    coverUrl: '/movies_pictures/shaun_of_the_dead.jpg',
    releaseDate: '2004-04-09',
    rating: 3,
    length: 99,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les choristes',
    director: 'Christophe Barratier',
    actors: [{ name: 'Gérard Jugnot' }],
    coverUrl: '/movies_pictures/les_choristes.jpg',
    releaseDate: '2004-03-17',
    rating: 3.75,
    length: 97,
    genre: 'Drama',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'EuroTrip',
    director: 'Jeff Schaffer',
    actors: [{ name: 'Scott Mechlowicz' }],
    coverUrl: '/movies_pictures/47243-eurotrip-0-150-0-225-crop.jpg',
    releaseDate: '2004-02-20',
    rating: 3.5,
    length: 93,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Les 11 commandements',
    director: 'François Desagnat, Thomas Sorriaux',
    actors: [{ name: 'François Desagnat' }],
    coverUrl: '/movies_pictures/40754-the-11-commandments-0-150-0-225-crop.jpg',
    releaseDate: '2004-02-11',
    rating: 3,
    length: 90,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'RRRrrrr!!!',
    director: 'Alain Chabat',
    actors: [{ name: 'Marion Cotillard' }],
    coverUrl: '/movies_pictures/38203-rrrrrrr--0-150-0-225-crop.jpg',
    releaseDate: '2004-01-28',
    rating: 3.75,
    length: 94,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Saw',
    director: 'James Wan',
    actors: [{ name: 'Cary Elwes' }],
    coverUrl: '/movies_pictures/saw.jpg',
    releaseDate: '2004-10-29',
    rating: 3.25,
    length: 103,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "L'effet papillon",
    director: 'Eric Bress, J. Mackye Gruber',
    actors: [{ name: 'Ashton Kutcher' }],
    coverUrl:
      '/movies_pictures/50654-the-butterfly-effect-0-150-0-225-crop.jpg',
    releaseDate: '2004-01-23',
    rating: 3.5,
    length: 113,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Oldboy',
    director: 'Park Chan-wook',
    actors: [{ name: 'Choi Min-sik' }],
    coverUrl: '/movies_pictures/51454-oldboy-0-150-0-225-crop.jpg',
    releaseDate: '2003-11-21',
    rating: 3.5,
    length: 120,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Bruce tout-puissant',
    director: 'Tom Shadyac',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl: '/movies_pictures/51749-bruce-almighty-0-150-0-225-crop.jpg',
    releaseDate: '2003-05-23',
    rating: 4.25,
    length: 101,
    genre: 'Comedy',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Moi, Cesar, 10 ans et demi, 1m39',
    director: 'Richard Berry',
    actors: [{ name: 'Richard Berry' }],
    coverUrl: '/movies_pictures/6543-i-cesar-0-150-0-225-crop.jpg',
    releaseDate: '2003-04-30',
    rating: 3,
    length: 95,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'En sursis',
    director: 'Andrzej Bartkowiak',
    actors: [{ name: 'Jet Li' }],
    coverUrl: '/movies_pictures/46051-cradle-2-the-grave-0-150-0-225-crop.jpg',
    releaseDate: '2003-02-28',
    rating: 3.75,
    length: 101,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'La Beuze',
    director: 'Éric Rochant',
    actors: [{ name: 'Vincent Lindon' }],
    coverUrl: '/movies_pictures/la_beuze.jpg',
    releaseDate: '2003-02-05',
    rating: 2.5,
    length: 95,
    genre: 'Drama',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Ong Bak',
    director: 'Prachya Pinkaew',
    actors: [{ name: 'Tony Jaa' }],
    coverUrl: '/movies_pictures/47277-ong-bak-0-150-0-225-crop.jpg',
    releaseDate: '2003-01-21',
    rating: 3.75,
    length: 108,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Attrape-moi si tu peux',
    director: 'Steven Spielberg',
    actors: [{ name: 'Leonardo DiCaprio' }],
    coverUrl: '/movies_pictures/51484-catch-me-if-you-can-0-150-0-225-crop.jpg',
    releaseDate: '2002-12-25',
    rating: 4.25,
    length: 141,
    genre: 'Crime',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Equilibrium',
    director: 'Kurt Wimmer',
    actors: [{ name: 'Christian Bale' }],
    coverUrl: '/movies_pictures/equilibrium-0-150-0-225-crop.jpg',
    releaseDate: '2002-12-06',
    rating: 3.25,
    length: 107,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Opération antisèche',
    director: 'Andrew Gurland',
    actors: [{ name: 'Trevor Fehrman' }],
    coverUrl: '/movies_pictures/41348-cheats-0-150-0-225-crop.jpg',
    releaseDate: '2002-09-13',
    rating: 3.25,
    length: 85,
    genre: 'Comedy',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: '28 jours plus tard',
    director: 'Danny Boyle',
    actors: [{ name: 'Cillian Murphy' }],
    coverUrl: '/movies_pictures/28_jours_plus_tard.jpg',
    releaseDate: '2002-11-01',
    rating: 3,
    length: 113,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le cercle : The ring',
    director: 'Gore Verbinski',
    actors: [{ name: 'Naomi Watts' }],
    coverUrl: '/movies_pictures/the-ring-0-150-0-225-crop.jpg',
    releaseDate: '2002-10-18',
    rating: 2.75,
    length: 115,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Phone Game',
    director: 'Joel Schumacher',
    actors: [{ name: 'Colin Farrell' }],
    coverUrl: '/movies_pictures/phone_game.jpg',
    releaseDate: '2002-09-10',
    rating: 3.25,
    length: 81,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Minority Report',
    director: 'Steven Spielberg',
    actors: [{ name: 'Tom Cruise' }],
    coverUrl: '/movies_pictures/minority_report.jpg',
    releaseDate: '2002-06-21',
    rating: 3.5,
    length: 145,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Calculs Meurtriers',
    director: 'Barbet Schroeder',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/44914-murder-by-numbers-0-150-0-225-crop.jpg',
    releaseDate: '2002-04-19',
    rating: 3.75,
    length: 120,
    genre: 'Thriller',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Panic Room',
    director: 'David Fincher',
    actors: [{ name: 'Jodie Foster' }],
    coverUrl: '/movies_pictures/panic_room.jpg',
    releaseDate: '2002-03-29',
    rating: 3.5,
    length: 112,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Rollerball',
    director: 'John McTiernan',
    actors: [{ name: 'Chris Klein' }],
    coverUrl: '/movies_pictures/45213-rollerball-0-150-0-225-crop.jpg',
    releaseDate: '2002-02-08',
    rating: 3.25,
    length: 98,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Dommage Collateral',
    director: 'Andrew Davis',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/46749-collateral-damage-0-150-0-225-crop.jpg',
    releaseDate: '2002-02-08',
    rating: 3.25,
    length: 108,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Astérix & Obélix : Mission Cléopâtre',
    director: 'Alain Chabat',
    actors: [{ name: 'Gérard Depardieu' }],
    coverUrl:
      '/movies_pictures/50024-asterix-obelix-mission-cleopatra-0-150-0-225-crop.jpg',
    releaseDate: '2002-01-30',
    rating: 5,
    length: 107,
    genre: 'Comedy',
    timesWatched: 50,
    lastViewedDate: '',
  },
  {
    title: "L'Avocat du Diable",
    director: 'Taylor Hackford',
    actors: [{ name: 'Keanu Reeves' }],
    coverUrl:
      '/movies_pictures/50780-the-devil-s-advocate-0-150-0-225-crop.jpg',
    releaseDate: '1997-10-17',
    rating: 3.25,
    length: 144,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le Cinquième Élément',
    director: 'Luc Besson',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/le_cinquieme_element.jpg',
    releaseDate: '1997-05-09',
    rating: 3.5,
    length: 126,
    genre: 'Science Fiction',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'American Beauty',
    director: 'Sam Mendes',
    actors: [{ name: 'Kevin Spacey' }],
    coverUrl: '/movies_pictures/2703-american-beauty-0-150-0-225-crop.jpg',
    releaseDate: '1999-09-15',
    rating: 3,
    length: 122,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Sixième Sens',
    director: 'M. Night Shyamalan',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/51407-the-sixth-sense-0-150-0-225-crop.jpg',
    releaseDate: '1999-08-06',
    rating: 3.25,
    length: 107,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },

  {
    title: 'Wild Wild West',
    director: 'Barry Sonnenfeld',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/wild_wild_west.jpg',
    releaseDate: '1999-06-30',
    rating: 3.5,
    length: 106,
    genre: 'Comedy',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Sex intentions',
    director: 'Roger Kumble',
    actors: [{ name: 'Sarah Michelle Gellar' }],
    coverUrl: '/movies_pictures/51356-cruel-intentions-0-150-0-225-crop.jpg',
    releaseDate: '1999-03-05',
    rating: 3,
    length: 97,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Armageddon',
    director: 'Michael Bay',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/51955-armageddon-0-150-0-225-crop.jpg',
    releaseDate: '1998-07-01',
    rating: 4.25,
    length: 151,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'The Truman Show',
    director: 'Peter Weir',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl: '/movies_pictures/the-truman-show-0-150-0-225-crop.jpg',
    releaseDate: '1998-06-05',
    rating: 3.75,
    length: 103,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Godzilla',
    director: 'Roland Emmerich',
    actors: [{ name: 'Matthew Broderick' }],
    coverUrl: '/movies_pictures/51224-godzilla-0-150-0-225-crop.jpg',
    releaseDate: '1998-05-20',
    rating: 3.5,
    length: 139,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Mon voisin le tueur',
    director: 'Jonathan Lynn',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl:
      '/movies_pictures/50554-the-whole-nine-yards-0-150-0-225-crop.jpg',
    releaseDate: '2000-02-18',
    rating: 3,
    length: 98,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'La Ligne Verte',
    director: 'Frank Darabont',
    actors: [{ name: 'Tom Hanks' }],
    coverUrl: '/movies_pictures/51613-the-green-mile-0-150-0-225-crop.jpg',
    releaseDate: '1999-12-10',
    rating: 4.25,
    length: 189,
    genre: 'Drama',
    timesWatched: 5,
    lastViewedDate: '',
  },
];
