import { Movie } from './movies_1';

export const moviesLove2: Movie[] = [
  {
    title: 'Eternal Sunshine of the Spotless Mind',
    director: 'Michel Gondry',
    actors: [{ name: 'Jim Carrey' }],
    coverUrl: '/movies_pictures/eternal_sunchine_of_the_spotless_mind.jpg',
    releaseDate: '2004-03-19',
    rating: 3.5,
    length: 108,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Girl Next Door',
    director: 'Luke Greenfield',
    actors: [{ name: 'Emile Hirsch' }],
    coverUrl:
      '/movies_pictures/46081-the-girl-next-door-2004-0-150-0-225-crop.jpg',
    releaseDate: '2004-04-09',
    rating: 3.5,
    length: 109,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Amour & Amnésie',
    director: 'Peter Segal',
    actors: [{ name: 'Adam Sandler' }],
    coverUrl: '/movies_pictures/50773-50-first-dates-0-150-0-225-crop.jpg',
    releaseDate: '2004-02-13',
    rating: 4.25,
    length: 99,
    genre: 'Comedy',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Love Actually',
    director: 'Richard Curtis',
    actors: [{ name: 'Hugh Grant' }],
    coverUrl: '/movies_pictures/51602-love-actually-0-150-0-225-crop.jpg',
    releaseDate: '2003-11-07',
    rating: 3.5,
    length: 135,
    genre: 'Romance',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: "Le temps d'un automne",
    director: 'Adam Shankman',
    actors: [{ name: 'Mandy Moore' }],
    coverUrl: '/movies_pictures/46422-a-walk-to-remember-0-150-0-225-crop.jpg',
    releaseDate: '2002-01-25',
    rating: 4,
    length: 101,
    genre: 'Romance',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Pearl Harbor',
    director: 'Michael Bay',
    actors: [{ name: 'Ben Affleck' }],
    coverUrl: '/movies_pictures/51448-pearl-harbor-0-150-0-225-crop.jpg',
    releaseDate: '2001-05-25',
    rating: 4,
    length: 183,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Ce que Veulent les Femmes',
    director: 'Nancy Meyers',
    actors: [{ name: 'Mel Gibson' }],
    coverUrl: '/movies_pictures/49539-what-women-want-0-150-0-225-crop.jpg',
    releaseDate: '2000-12-15',
    rating: 3.75,
    length: 127,
    genre: 'Comedy',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Coup de foudre à Notting Hill',
    director: 'Roger Michell',
    actors: [{ name: 'Julia Roberts' }],
    coverUrl: '/movies_pictures/notting-hill-0-150-0-225-crop.jpg',
    releaseDate: '1999-05-28',
    rating: 3,
    length: 124,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Rencontre avec Joe Black',
    director: 'Martin Brest',
    actors: [{ name: 'Brad Pitt' }],
    coverUrl: '/movies_pictures/51762-meet-joe-black-0-150-0-225-crop.jpg',
    releaseDate: '1998-11-13',
    rating: 2,
    length: 178,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-04-13',
  },
  {
    title: 'Pretty Woman',
    director: 'Garry Marshall',
    actors: [{ name: 'Julia Roberts' }],
    coverUrl: '/movies_pictures/51936-pretty-woman-0-150-0-225-crop.jpg',
    releaseDate: '1990-03-23',
    rating: 4,
    length: 119,
    genre: 'Romance',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Amour au Carré',
    director: 'Filip Zylber',
    actors: [
      {
        name: 'Adrianna Chlebicka',
      },
    ],
    coverUrl: '/movies_pictures/705695-squared-love-0-150-0-225-crop.jpg',
    releaseDate: '2021-02-11',
    rating: 3,
    length: 105,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'La La Land',
    director: 'Damien Chazelle',
    actors: [{ name: 'Ryan Gosling' }],
    coverUrl: '/movies_pictures/240344-la-la-land-0-150-0-225-crop.jpg',
    releaseDate: '2016-12-09',
    rating: 3.5,
    length: 128,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "L'amour ouf",
    director: 'Claude Zidi Jr.',
    actors: [{ name: 'François Civil' }],
    coverUrl:
      '/movies_pictures/863617-beating-hearts-2024-0-150-0-225-crop.jpg',
    releaseDate: '2024-01-31',
    rating: 3.5,
    length: 95,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '2025-04-31',
  },
  {
    title: 'The Princess Switch : Switched Again',
    director: 'Mike Rohl',
    actors: [
      {
        name: 'Vanessa Hudgens',
      },
    ],
    coverUrl:
      '/movies_pictures/569812-the-princess-switch-switched-again-0-150-0-225-crop.jpg',
    releaseDate: '2020-11-19',
    rating: 2.75,
    length: 97,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Holidate',
    director: 'John Whitesell',
    actors: [
      {
        name: 'Emma Roberts',
      },
    ],
    coverUrl: '/movies_pictures/542464-holidate-0-150-0-225-crop.jpg',
    releaseDate: '2020-10-28',
    rating: 2.75,
    length: 104,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Rich in Love',
    director: 'Bruno Garotti',
    actors: [
      {
        name: 'Maisa Silva',
      },
    ],
    coverUrl: '/movies_pictures/582011-rich-in-love-0-150-0-225-crop.jpg',
    releaseDate: '2020-06-19',
    rating: 3.25,
    length: 104,
    genre: 'Romance',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Isi & Ossi',
    director: 'Oliver Kienle',
    actors: [
      {
        name: 'Lisa Vicari',
      },
    ],
    coverUrl: '/movies_pictures/584262-isi-ossi-0-150-0-225-crop.jpg',
    releaseDate: '2020-02-14',
    rating: 2.5,
    length: 113,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Last Christmas',
    director: 'Paul Feig',
    actors: [
      {
        name: 'Emilia Clarke',
      },
    ],
    coverUrl: '/movies_pictures/477863-last-christmas-0-150-0-225-crop.jpg',
    releaseDate: '2019-11-08',
    rating: 2.5,
    length: 103,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
