import { Movie } from './movies_1';

export const moviesPage4: Movie[] = [
  {
    title: 'Maléfique',
    director: 'Robert Stromberg',
    actors: [{ name: 'Angelina Jolie' }],
    coverUrl: '/movies_pictures/malefique.jpg',
    releaseDate: '2014-05-30',
    rating: 2.75,
    length: 97,
    genre: 'Fantasy',
    timesWatched: 1,
    lastViewedDate: '2014-05-30',
  },
  {
    title: 'Edge of Tomorrow',
    director: 'Doug Liman',
    actors: [{ name: 'Tom Cruise' }],
    coverUrl: '/movies_pictures/105183-edge-of-tomorrow-0-150-0-225-crop.jpg',
    releaseDate: '2014-06-06',
    rating: 4.5,
    length: 113,
    genre: 'Science Fiction',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Robocop',
    director: 'José Padilha',
    actors: [{ name: 'Joel Kinnaman' }],
    coverUrl: '/movies_pictures/79982-robocop-0-150-0-225-crop.jpg',
    releaseDate: '2014-02-12',
    rating: 3,
    length: 117,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le Loup de Wall Street',
    director: 'Martin Scorsese',
    actors: [{ name: 'Leonardo DiCaprio' }],
    coverUrl:
      '/movies_pictures/86114-the-wolf-of-wall-street-0-150-0-225-crop.jpg',
    releaseDate: '2013-12-25',
    rating: 4.25,
    length: 180,
    genre: 'Crime',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'La Vie Rêvée de Walter Mitty',
    director: 'Ben Stiller',
    actors: [{ name: 'Ben Stiller' }],
    coverUrl:
      '/movies_pictures/92619-the-secret-life-of-walter-mitty-0-150-0-225-crop.jpg',
    releaseDate: '2013-12-25',
    rating: 3.5,
    length: 114,
    genre: 'Adventure',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Prisoners',
    director: 'Denis Villeneuve',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl: '/movies_pictures/prisoners.jpg',
    releaseDate: '2013-09-20',
    rating: 4,
    length: 153,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Gravity',
    director: 'Alfonso Cuarón',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/21023233_20130729173134181.webp',
    releaseDate: '2013-10-04',
    rating: 3.25,
    length: 91,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Elysium',
    director: 'Neill Blomkamp',
    actors: [{ name: 'Matt Damon' }],
    coverUrl: '/movies_pictures/elysium.jpg',
    releaseDate: '2013-08-09',
    rating: 3,
    length: 109,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le Majordome',
    director: 'Lee Daniels',
    actors: [{ name: 'Forest Whitaker' }],
    coverUrl: '/movies_pictures/le_majordome.jpg',
    releaseDate: '2013-08-16',
    rating: 3.75,
    length: 132,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Evasion',
    director: 'Mikael Håfström',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/86856-escape-plan-0-150-0-225-crop.jpg',
    releaseDate: '2013-10-18',
    rating: 3.25,
    length: 115,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Pacific Rim',
    director: 'Guillermo del Toro',
    actors: [{ name: 'Charlie Hunnam' }],
    coverUrl: '/movies_pictures/52508-pacific-rim-0-150-0-225-crop.jpg',
    releaseDate: '2013-07-12',
    rating: 2.75,
    length: 131,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'World War Z',
    director: 'Marc Forster',
    actors: [{ name: 'Brad Pitt' }],
    coverUrl: '/movies_pictures/57292-world-war-z-0-150-0-225-crop.jpg',
    releaseDate: '2013-06-21',
    rating: 3,
    length: 116,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Conjuring : Les Dossiers Warren',
    director: 'James Wan',
    actors: [{ name: 'Vera Farmiga' }],
    coverUrl: '/movies_pictures/106262-the-conjuring-0-150-0-225-crop.jpg',
    releaseDate: '2013-07-19',
    rating: 2.5,
    length: 112,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'After Earth',
    director: 'M. Night Shyamalan',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/after_earth.jpg',
    releaseDate: '2013-05-31',
    rating: 2.5,
    length: 100,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '2013-05-31',
  },
  {
    title: 'No pain no gain',
    director: 'Michael Bay',
    actors: [{ name: 'Mark Wahlberg' }],
    coverUrl: '/movies_pictures/103559-pain-gain-0-150-0-225-crop.jpg',
    releaseDate: '2013-04-26',
    rating: 3,
    length: 129,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Oblivion',
    director: 'Joseph Kosinski',
    actors: [{ name: 'Tom Cruise' }],
    coverUrl: '/movies_pictures/62108-oblivion-0-150-0-225-crop.jpg',
    releaseDate: '2013-04-19',
    rating: 3,
    length: 124,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Django Unchained',
    director: 'Quentin Tarantino',
    actors: [{ name: 'Jamie Foxx' }],
    coverUrl: '/movies_pictures/52516-django-unchained-0-150-0-225-crop.jpg',
    releaseDate: '2012-12-25',
    rating: 3.75,
    length: 165,
    genre: 'Western',
    timesWatched: 2,
    lastViewedDate: '2012-12-25',
  },
  {
    title: 'The Dream Team',
    director: 'Thomas Sorriaux',
    actors: [{ name: 'Gérard Lanvin' }],
    coverUrl: '/movies_pictures/103066-the-dream-team-0-150-0-225-crop.jpg',
    releaseDate: '2012-10-03',
    rating: 2.5,
    length: 105,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Dredd',
    director: 'Pete Travis',
    actors: [{ name: 'Karl Urban' }],
    coverUrl: '/movies_pictures/16527-dredd-0-150-0-225-crop.jpg',
    releaseDate: '2012-09-21',
    rating: 2.75,
    length: 95,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Expendables 2',
    director: 'Simon West',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/62593-the-expendables-2-0-150-0-225-crop.jpg',
    releaseDate: '2012-08-17',
    rating: 2.5,
    length: 103,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Dictator',
    director: 'Larry Charles',
    actors: [{ name: 'Sacha Baron Cohen' }],
    coverUrl: '/movies_pictures/62911-the-dictator-0-150-0-225-crop.jpg',
    releaseDate: '2012-05-16',
    rating: 3.25,
    length: 83,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'The Lucky One',
    director: 'Scott Hicks',
    actors: [{ name: 'Zac Efron' }],
    coverUrl: '/movies_pictures/64331-the-lucky-one-0-150-0-225-crop.jpg',
    releaseDate: '2012-04-20',
    rating: 3.25,
    length: 101,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Prometheus',
    director: 'Ridley Scott',
    actors: [{ name: 'Noomi Rapace' }],
    coverUrl: '/movies_pictures/prometheus.jpg',
    releaseDate: '2012-06-08',
    rating: 3,
    length: 124,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: '21 Jump Street',
    director: 'Phil Lord, Christopher Miller',
    actors: [{ name: 'Jonah Hill' }],
    coverUrl: '/movies_pictures/279-21-jump-street-0-150-0-225-crop.jpg',
    releaseDate: '2012-03-16',
    rating: 3.5,
    length: 109,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },

  {
    title: 'Target',
    director: 'McG',
    actors: [{ name: 'Chris Pine' }],
    coverUrl: '/movies_pictures/this-means-war-0-150-0-225-crop.jpg',
    releaseDate: '2012-02-17',
    rating: 2.5,
    length: 98,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Chronicle',
    director: 'Josh Trank',
    actors: [{ name: 'Dane DeHaan' }],
    coverUrl: '/movies_pictures/chronicles.jpg',
    releaseDate: '2012-02-03',
    rating: 3.75,
    length: 84,
    genre: 'Science Fiction',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Time Out',
    director: 'Andrew Niccol',
    actors: [{ name: 'Justin Timberlake' }],
    coverUrl: '/movies_pictures/16082-in-time-0-150-0-225-crop.jpg',
    releaseDate: '2011-10-28',
    rating: 4.75,
    length: 109,
    genre: 'Science Fiction',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Footloose',
    director: 'Craig Brewer',
    actors: [{ name: 'Kenny Wormald' }],
    coverUrl: '/movies_pictures/footloose.jpg',
    releaseDate: '2011-10-14',
    rating: 3,
    length: 113,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Real Steel',
    director: 'Shawn Levy',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl: '/movies_pictures/real_steel.jpg',
    releaseDate: '2011-10-07',
    rating: 3.5,
    length: 127,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '2025-02-07',
  },
  {
    title: 'Intouchables',
    director: 'Olivier Nakache, Éric Toledano',
    actors: [{ name: 'François Cluzet' }],
    coverUrl: '/movies_pictures/intouchables-0-150-0-225-crop.jpg',
    releaseDate: '2011-11-02',
    rating: 5,
    length: 112,
    genre: 'Comedy',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Warrior',
    director: "Gavin O'Connor",
    actors: [{ name: 'Tom Hardy' }],
    coverUrl: '/movies_pictures/6942-warrior-0-150-0-225-crop.jpg',
    releaseDate: '2011-09-09',
    rating: 3.5,
    length: 140,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Never Back Down 2: The Beatdown',
    director: 'Michael Jai White',
    actors: [{ name: 'Michael Jai White' }],
    coverUrl:
      '/movies_pictures/59415-never-back-down-2-the-beatdown-0-150-0-225-crop.jpg',
    releaseDate: '2011-09-13',
    rating: 2.5,
    length: 90,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Raid',
    director: 'Gareth Evans',
    actors: [{ name: 'Iko Uwais' }],
    coverUrl: '/movies_pictures/78266-the-raid-0-150-0-225-crop.jpg',
    releaseDate: '2012-03-23',
    rating: 3,
    length: 101,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Cowboys & Aliens',
    director: 'Jon Favreau',
    actors: [{ name: 'Daniel Craig' }],
    coverUrl: '/movies_pictures/cowboy_and_aliens.jpg',
    releaseDate: '2011-07-29',
    rating: 2,
    length: 118,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Tango & Cash',
    director: 'Andrei Konchalovsky',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/tango_et_cash.jpg',
    releaseDate: '1989-12-22',
    rating: 3.25,
    length: 104,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Le cercle des poètes disparus',
    director: 'Peter Weir',
    actors: [{ name: 'Robin Williams' }],
    coverUrl: '/movies_pictures/51846-dead-poets-society-0-150-0-225-crop.jpg',
    releaseDate: '1989-06-09',
    rating: 3.75,
    length: 128,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Kickboxer',
    director: 'Mark DiSalle, David Worth',
    actors: [{ name: 'Jean-Claude Van Damme' }],
    coverUrl: '/movies_pictures/46429-kickboxer-0-150-0-225-crop.jpg',
    releaseDate: '1989-04-20',
    rating: 3,
    length: 97,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Qui veut la peau de Roger Rabbit',
    director: 'Robert Zemeckis',
    actors: [{ name: 'Bob Hoskins' }],
    coverUrl:
      '/movies_pictures/51296-who-framed-roger-rabbit-0-150-0-225-crop.jpg',
    releaseDate: '1988-06-22',
    rating: 3.75,
    length: 104,
    genre: 'Animation',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Bloodsport',
    director: 'Newt Arnold',
    actors: [{ name: 'Jean-Claude Van Damme' }],
    coverUrl: '/movies_pictures/bloodsport.jpg',
    releaseDate: '1988-02-26',
    rating: 3.25,
    length: 92,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Good Morning, Vietnam',
    director: 'Barry Levinson',
    actors: [{ name: 'Robin Williams' }],
    coverUrl: '/movies_pictures/good_morning_vietnam.jpg',
    releaseDate: '1987-12-23',
    rating: 3.5,
    length: 121,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Running Man',
    director: 'Paul Michael Glaser',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/51287-the-running-man-0-150-0-225-crop.jpg',
    releaseDate: '1987-11-13',
    rating: 3,
    length: 101,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'RoboCop',
    director: 'Paul Verhoeven',
    actors: [{ name: 'Peter Weller' }],
    coverUrl: '/movies_pictures/robocop-0-150-0-225-crop.jpg',
    releaseDate: '1987-07-17',
    rating: 3.5,
    length: 102,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
];
