import { Movie } from "./movies_1";

export const moviesAnimated: Movie[] = [
  {
    title: "Dragons",
    director: "Dean DeBlois, Chris Sanders",
    actors: [{ name: "Jay Baruchel" }],
    coverUrl: "/movies_pictures/validated/dragon.jpg",
    releaseDate: "2010-03-26",
    rating: 0,
    length: 98,
    genre: "Animation",
    timesWatched: 5,
  },
  {
    title: "Dragons 2",
    director: "Dean DeBlois",
    actors: [{ name: "Jay Baruchel" }],
    coverUrl: "/movies_pictures/validated/69142-how-to-train-your-dragon-2-0-150-0-225-crop.jpg",
    releaseDate: "2014-06-13",
    rating: 0,
    length: 102,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Dragons 3: The Hidden World",
    director: "Dean DeBlois",
    actors: [
      {
        name: "Jay Baruchel",
      },
    ],
    coverUrl: "/movies_pictures/validated/123067-how-to-train-your-dragon-the-hidden-world-0-150-0-225-crop.jpg",
    releaseDate: "2019-02-22",
    rating: 0,
    length: 0,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    actors: [
      {
        name: "Shameik Moore",
      },
    ],
    coverUrl: "/movies_pictures/validated/251943-spider-man-into-the-spider-verse-0-150-0-225-crop.jpg",
    releaseDate: "2018-12-14",
    rating: 0,
    length: 0,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Spider-Man : À Travers le Spider-Verse",
    director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
    actors: [
      {
        name: "Shameik Moore",
      },
    ],
    coverUrl: "/movies_pictures/validated/497631-spider-man-across-the-spider-verse-0-150-0-225-crop.jpg",
    releaseDate: "2023-06-02",
    rating: 0,
    length: 0,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Les Mondes de Ralph",
    director: "Rich Moore",
    actors: [{ name: "John C. Reilly" }],
    coverUrl: "/movies_pictures/validated/69154-wreck-it-ralph-0-150-0-225-crop.jpg",
    releaseDate: "2012-11-02",
    rating: 0,
    length: 101,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Ralph Breaks the Internet",
    director: "Rich Moore, Phil Johnston",
    actors: [
      {
        name: "John C. Reilly",
      },
    ],
    coverUrl: "/movies_pictures/validated/338883-ralph-breaks-the-internet-0-150-0-225-crop.jpg",
    releaseDate: "2018-11-21",
    rating: 0,
    length: 0,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Super Mario Bros. le Film",
    director: "Aaron Horvath, Michael Jelenic",
    actors: [
      {
        name: "Chris Pratt",
      },
    ],
    coverUrl: "/movies_pictures/validated/432302-the-super-mario-bros-movie-0-150-0-225-crop.jpg",
    releaseDate: "2023-04-05",
    rating: 3.75,
    length: 0,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Encanto",
    director: "Jared Bush, Byron Howard",
    actors: [
      {
        name: "Stephanie Beatriz",
      },
    ],
    coverUrl: "/movies_pictures/validated/496592-encanto-0-150-0-225-crop.jpg",
    releaseDate: "2021-11-24",
    rating: 0,
    length: 0,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Cars",
    director: "John Lasseter",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies_pictures/validated/dWg33ektXuHmxjSjEulwDPTWbC2-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-09",
    rating: 0,
    length: 117,
    genre: "Animation",
    timesWatched: 10,
  },
  {
    title: "Cars 3",
    director: "Brian Fee",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies_pictures/validated/184062-cars-3-0-150-0-225-crop.jpg",
    releaseDate: "2016-06-16",
    rating: 0,
    length: 102,
    genre: "Animation",
    timesWatched: 5,
  },
  {
    title: "Baby boss",
    director: "Tom McGrath",
    actors: [{ name: "Alec Baldwin" }],
    coverUrl: "/movies_pictures/validated/223050-the-boss-baby-0-150-0-225-crop.jpg",
    releaseDate: "2017-03-31",
    rating: 0,
    length: 97,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Vaiana",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Auli'i Cravalho" }],
    coverUrl: "/movies_pictures/validated/201909-moana-0-150-0-225-crop.jpg",
    releaseDate: "2016-11-23",
    rating: 0,
    length: 107,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Vice-Versa",
    director: "Pete Docter",
    actors: [{ name: "Amy Poehler" }],
    coverUrl: "/movies_pictures/validated/113284-inside-out-0-150-0-225-crop.jpg",
    releaseDate: "2015-06-19",
    rating: 0,
    length: 95,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Les Nouveaux Héros",
    director: "Don Hall, Chris Williams",
    actors: [{ name: "Ryan Potter" }],
    coverUrl: "/movies_pictures/validated/les_nouveaux_heros.jpg",
    releaseDate: "2014-11-07",
    rating: 0,
    length: 102,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "La Reine des Neiges",
    director: "Chris Buck, Jennifer Lee",
    actors: [{ name: "Kristen Bell" }],
    coverUrl: "/movies_pictures/validated/reine_des_neiges.jpg",
    releaseDate: "2013-11-27",
    rating: 0,
    length: 102,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Moi, Moche et Méchant",
    director: "Pierre Coffin, Chris Renaud",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies_pictures/validated/39067-despicable-me-0-150-0-225-crop.jpg",
    releaseDate: "2010-07-09",
    rating: 0,
    length: 95,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Moi, Moche et Méchant 2",
    director: "Pierre Coffin, Chris Renaud",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies_pictures/validated/moi_moi_mechant_2.jpg",
    releaseDate: "2013-07-03",
    rating: 0,
    length: 98,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Les Cinq Légendes",
    director: "Peter Ramsey",
    actors: [{ name: "Chris Pine" }],
    coverUrl: "/movies_pictures/validated/les_cinq_legendes.jpg",
    releaseDate: "2012-11-21",
    rating: 0,
    length: 97,
    genre: "Animation",
    timesWatched: 2,
  },
  {
    title: "L'Âge de Glace",
    director: "Chris Wedge, Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies_pictures/validated/51670-ice-age-0-150-0-225-crop.jpg",
    releaseDate: "2002-03-15",
    rating: 0,
    length: 81,
    genre: "Animation",
    timesWatched: 30,
  },
  {
    title: "L'Âge de Glace 2",
    director: "Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies_pictures/validated/age_de_glace_2.jpg",
    releaseDate: "2006-03-31",
    rating: 0,
    length: 91,
    genre: "Animation",
    timesWatched: 15,
  },
  {
    title: "L'Âge de Glace 3 : Le Temps des Dinosaures",
    director: "Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies_pictures/validated/47781-ice-age-dawn-of-the-dinosaurs-0-150-0-225-crop.jpg",
    releaseDate: "2009-07-01",
    rating: 0,
    length: 94,
    genre: "Animation",
    timesWatched: 15,
  },
  {
    title: "L'Âge de Glace 4 : La Dérive des Continents",
    director: "Steve Martino, Mike Thurmeier",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies_pictures/validated/age_de_glace_4.jpg",
    releaseDate: "2012-07-13",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Rebelle",
    director: "Mark Andrews, Brenda Chapman",
    actors: [{ name: "Kelly Macdonald" }],
    coverUrl: "/movies_pictures/validated/rebelle.jpg",
    releaseDate: "2012-06-22",
    rating: 0,
    length: 93,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Arthur et les Minimoys",
    director: "Luc Besson",
    actors: [{ name: "Freddie Highmore" }],
    coverUrl: "/movies_pictures/validated/46649-arthur-and-the-invisibles-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-13",
    rating: 0,
    length: 94,
    genre: "Fantasy",
    timesWatched: 20,
  },
  {
    title: "Arthur et la Vengeance de Maltazard",
    director: "Luc Besson",
    actors: [{ name: "Freddie Highmore" }],
    coverUrl: "/movies_pictures/validated/35270-arthur-and-the-revenge-of-maltazard-0-150-0-225-crop.jpg",
    releaseDate: "2009-12-02",
    rating: 0,
    length: 94,
    genre: "Adventure",
    timesWatched: 2,
  },
  {
    title: "Arthur 3 : La Guerre des Deux Mondes",
    director: "Luc Besson",
    actors: [{ name: "Freddie Highmore" }],
    coverUrl: "/movies_pictures/validated/22170-arthur-3-the-war-of-the-two-worlds-0-150-0-225-crop.jpg",
    releaseDate: "2010-10-13",
    rating: 0,
    length: 101,
    genre: "Adventure",
    timesWatched: 1,
  },
  {
    title: "La Princesse et la Grenouille",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Anika Noni Rose" }],
    coverUrl: "/movies_pictures/validated/bVRHirC6uIZL9VtRqYRxdedYnOG-0-150-0-225-crop.jpg",
    releaseDate: "2009-12-11",
    rating: 0,
    length: 97,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Tempête de Boulettes Géantes",
    director: "Phil Lord, Christopher Miller",
    actors: [{ name: "Bill Hader" }],
    coverUrl: "/movies_pictures/validated/37696-cloudy-with-a-chance-of-meatballs-0-150-0-225-crop.jpg",
    releaseDate: "2009-09-18",
    rating: 0,
    length: 90,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Monstres contre Aliens",
    director: "Rob Letterman, Conrad Vernon",
    actors: [{ name: "Reese Witherspoon" }],
    coverUrl: "/movies_pictures/validated/42315-monsters-vs-aliens-0-150-0-225-crop.jpg",
    releaseDate: "2009-03-27",
    rating: 4,
    length: 94,
    genre: "Animation",
    timesWatched: 20,
  },
  {
    title: "WALL-E",
    director: "Andrew Stanton",
    actors: [{ name: "Ben Burtt" }],
    coverUrl: "/movies_pictures/validated/45994-walle-0-150-0-225-crop.jpg",
    releaseDate: "2008-06-27",
    rating: 0,
    length: 98,
    genre: "Animation",
    timesWatched: 2,
  },
  {
    title: "Kung Fu Panda",
    director: "Mark Osborne, John Stevenson",
    actors: [{ name: "Jack Black" }],
    coverUrl: "/movies_pictures/validated/mk3UyyaLyXhgIhmLji25OUPXvGR-0-150-0-225-crop.jpg",
    releaseDate: "2008-06-06",
    rating: 0,
    length: 92,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Bee Movie : Drôle d'Abeille",
    director: "Steve Hickner, Simon J. Smith",
    actors: [{ name: "Jerry Seinfeld" }],
    coverUrl: "/movies_pictures/validated/48791-bee-movie-0-150-0-225-crop.jpg",
    releaseDate: "2007-11-02",
    rating: 0,
    length: 91,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Les Simpson, le Film",
    director: "David Silverman",
    actors: [{ name: "Dan Castellaneta" }],
    coverUrl: "/movies_pictures/validated/2684-the-simpsons-movie-0-150-0-225-crop.jpg",
    releaseDate: "2007-07-27",
    rating: 4.5,
    length: 87,
    genre: "Animation",
    timesWatched: 40,
  },
  {
    title: "Ratatouille",
    director: "Brad Bird",
    actors: [{ name: "Patton Oswalt" }],
    coverUrl: "/movies_pictures/validated/ratatouille.jpg",
    releaseDate: "2007-06-29",
    rating: 0,
    length: 111,
    genre: "Animation",
    timesWatched: 5,
  },
  {
    title: "Shrek",
    director: "Andrew Adamson, Vicky Jenson",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies_pictures/validated/51344-shrek-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-18",
    rating: 0,
    length: 90,
    genre: "Animation",
    timesWatched: 10,
  },
  {
    title: "Shrek 2",
    director: "Andrew Adamson, Kelly Asbury, Conrad Vernon",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies_pictures/validated/shrek_2.jpg",
    releaseDate: "2004-05-19",
    rating: 0,
    length: 93,
    genre: "Animation",
    timesWatched: 5,
  },
  {
    title: "Shrek le Troisième",
    director: "Chris Miller",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies_pictures/validated/shrek_3.jpg",
    releaseDate: "2007-05-18",
    rating: 0,
    length: 93,
    genre: "Animation",
    timesWatched: 3,
  },
  {
    title: "Les Indestructibles",
    director: "Brad Bird",
    actors: [{ name: "Craig T. Nelson" }],
    coverUrl: "/movies_pictures/validated/46806-the-incredibles-0-150-0-225-crop.jpg",
    releaseDate: "2004-11-05",
    rating: 4.5,
    length: 115,
    genre: "Animation",
    timesWatched: 30,
  },
  {
    title: "Les Indestructibles 2",
    director: "Brad Bird",
    actors: [
      {
        name: "Craig T. Nelson",
      },
    ],
    coverUrl: "/movies_pictures/validated/184061-incredibles-2-0-150-0-225-crop.jpg",
    releaseDate: "2018-06-15",
    rating: 0,
    length: 0,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Nemo",
    director: "Andrew Stanton",
    actors: [{ name: "Albert Brooks" }],
    coverUrl: "/movies_pictures/validated/2705-finding-nemo-0-150-0-225-crop.jpg",
    releaseDate: "2003-05-30",
    rating: 0,
    length: 100,
    genre: "Animation",
    timesWatched: 5,
  },
  {
    title: "Monstres et Cie",
    director: "Pete Docter",
    actors: [{ name: "John Goodman" }],
    coverUrl: "/movies_pictures/validated/monstres_et_compagnie.jpg",
    releaseDate: "2001-11-02",
    rating: 0,
    length: 92,
    genre: "Animation",
    timesWatched: 3,
  },
  {
    title: "Toy Story",
    director: "John Lasseter",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies_pictures/validated/51290-toy-story-0-150-0-225-crop.jpg",
    releaseDate: "1995-11-22",
    rating: 0,
    length: 81,
    genre: "Animation",
    timesWatched: 5,
  },
  {
    title: "Toy Story 2",
    director: "John Lasseter",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies_pictures/validated/51289-toy-story-2-0-150-0-225-crop.jpg",
    releaseDate: "1999-11-24",
    rating: 0,
    length: 92,
    genre: "Animation",
    timesWatched: 2,
  },
  {
    title: "South Park, le Film",
    director: "Trey Parker",
    actors: [{ name: "Trey Parker" }],
    coverUrl: "/movies_pictures/validated/47125-south-park-bigger-longer-uncut-0-150-0-225-crop.jpg",
    releaseDate: "1999-06-30",
    rating: 0,
    length: 81,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Tarzan",
    director: "Chris Buck, Kevin Lima",
    actors: [{ name: "Tony Goldwyn" }],
    coverUrl: "/movies_pictures/validated/tarzan.jpg",
    releaseDate: "1999-06-18",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 10,
  },
  {
    title: "Fourmiz",
    director: "Eric Darnell, Tim Johnson",
    actors: [{ name: "Woody Allen" }],
    coverUrl: "/movies_pictures/validated/47511-antz-0-150-0-225-crop.jpg",
    releaseDate: "1998-10-02",
    rating: 0,
    length: 83,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Mulan",
    director: "Tony Bancroft, Barry Cook",
    actors: [{ name: "Ming-Na Wen" }],
    coverUrl: "/movies_pictures/validated/266675-mulan-0-150-0-225-crop.jpg",
    releaseDate: "1998-06-19",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Princesse Mononoké",
    director: "Hayao Miyazaki",
    actors: [{ name: "Yôji Matsuda" }],
    coverUrl: "/movies_pictures/validated/mNqZOtJIQfFQPjo3hmYLIn8Qqhf-0-150-0-225-crop.jpg",
    releaseDate: "1997-07-12",
    rating: 0,
    length: 134,
    genre: "Animation",
    timesWatched: 2,
  },
  {
    title: "Hercule",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Tate Donovan" }],
    coverUrl: "/movies_pictures/validated/44838-hercules-0-150-0-225-crop.jpg",
    releaseDate: "1997-06-27",
    rating: 0,
    length: 93,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Pocahontas",
    director: "Mike Gabriel, Eric Goldberg",
    actors: [{ name: "Irene Bedard" }],
    coverUrl: "/movies_pictures/validated/pocahontas.jpg",
    releaseDate: "1995-06-23",
    rating: 0,
    length: 81,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Space Jam",
    director: "Joe Pytka",
    actors: [{ name: "Michael Jordan" }],
    coverUrl: "/movies_pictures/validated/space_jam.jpg",
    releaseDate: "1996-11-15",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Le Roi Lion",
    director: "Roger Allers, Rob Minkoff",
    actors: [{ name: "Matthew Broderick" }],
    coverUrl: "/movies_pictures/validated/le roi lion.jpg",
    releaseDate: "1994-06-24",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Aladdin",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Scott Weinger" }],
    coverUrl: "/movies_pictures/validated/aladdin_film.jpg",
    releaseDate: "1992-11-25",
    rating: 0,
    length: 90,
    genre: "Animation",
    timesWatched: 30,
  },
  {
    title: "La petite sirène",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Jodi Benson" }],
    coverUrl: "/movies_pictures/validated/la_petite_sirene.jpg",
    releaseDate: "1989-11-17",
    rating: 0,
    length: 83,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Peter Pan",
    director: "Clyde Geronimi, Wilfred Jackson, Hamilton Luske",
    actors: [{ name: "Bobby Driscoll" }],
    coverUrl: "/movies_pictures/validated/45983-peter-pan-0-150-0-225-crop.jpg",
    releaseDate: "1953-02-05",
    rating: 0,
    length: 77,
    genre: "Animation",
    timesWatched: 5,
  },
  {
    title: "Pinocchio",
    director: "Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen",
    actors: [{ name: "Dickie Jones" }],
    coverUrl: "/movies_pictures/validated/45797-pinocchio-0-150-0-225-crop.jpg",
    releaseDate: "1940-02-07",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 3,
  },
];