import { Movie } from "./movies_1";

export const moviesMcu: Movie[] = [
  {
    title: "Avengers",
    director: "Joss Whedon",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/validated/avengers.jpg",
    releaseDate: "2012-05-04",
    rating: 0,
    length: 143,
    genre: "Action",
    timesWatched: 30,
  },
  {
    title: "Avengers : L'Ère d'Ultron",
    director: "Joss Whedon",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/validated/81605-avengers-age-of-ultron-0-150-0-225-crop.jpg",
    releaseDate: "2015-05-01",
    rating: 0,
    length: 141,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Avengers: Infinity War",
    director: "Anthony Russo, Joe Russo",
    actors: [
      {
        name: "Robert Downey Jr.",
      },
    ],
    coverUrl: "/movies/validated/226661-avengers-infinity-war-0-150-0-225-crop.jpg",
    releaseDate: "2018-04-27",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Avengers: Endgame",
    director: "Anthony Russo, Joe Russo",
    actors: [
      {
        name: "Robert Downey Jr.",
      },
    ],
    coverUrl: "/movies/validated/226660-avengers-endgame-0-150-0-225-crop.jpg",
    releaseDate: "2019-04-26",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Captain America : First Avenger",
    director: "Joe Johnston",
    actors: [{ name: "Chris Evans" }],
    coverUrl: "/movies/validated/50809-captain-america-the-first-avenger-0-150-0-225-crop.jpg",
    releaseDate: "2011-07-22",
    rating: 0,
    length: 124,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Captain America : Le Soldat de l'Hiver",
    director: "Anthony Russo, Joe Russo",
    actors: [{ name: "Chris Evans" }],
    coverUrl: "/movies/validated/captain_america_le_soldat_de_lhiver.jpg",
    releaseDate: "2014-04-04",
    rating: 0,
    length: 136,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Captain America : Civil War",
    director: "Anthony Russo, Joe Russo",
    actors: [{ name: "Chris Evans" }],
    coverUrl: "/movies/validated/194402-captain-america-civil-war-0-150-0-225-crop.jpg",
    releaseDate: "2016-05-06",
    rating: 0,
    length: 147,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Iron Man",
    director: "Jon Favreau",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/validated/50825-iron-man-0-150-0-225-crop.jpg",
    releaseDate: "2008-05-02",
    rating: 0,
    length: 126,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Iron Man 2",
    director: "Jon Favreau",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/validated/46511-iron-man-2-0-150-0-225-crop.jpg",
    releaseDate: "2010-05-07",
    rating: 0,
    length: 124,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Iron Man 3",
    director: "Shane Black",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/validated/iron_man_3.jpg",
    releaseDate: "2013-05-03",
    rating: 0,
    length: 130,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "L'Incroyable Hulk",
    director: "Louis Leterrier",
    actors: [{ name: "Edward Norton" }],
    coverUrl: "/movies/validated/50827-the-incredible-hulk-0-150-0-225-crop.jpg",
    releaseDate: "2008-06-13",
    rating: 0,
    length: 112,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Thor",
    director: "Kenneth Branagh",
    actors: [{ name: "Chris Hemsworth" }],
    coverUrl: "/movies/validated/46456-thor-0-150-0-225-crop.jpg",
    releaseDate: "2011-05-06",
    rating: 0,
    length: 115,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Thor: The Dark World",
    director: "Alan Taylor",
    actors: [{ name: "Chris Hemsworth" }],
    coverUrl: "/movies/validated/bnX5PqAdQZRXSw3aX3DutDcdso5-0-150-0-225-crop.jpg",
    releaseDate: "2013-11-08",
    rating: 0,
    length: 112,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Thor: Ragnarok",
    director: "Taika Waititi",
    actors: [{ name: "Chris Hemsworth" }],
    coverUrl: "/movies/validated/209382-thor-ragnarok-0-150-0-225-crop.jpg",
    releaseDate: "2017-11-03",
    rating: 0,
    length: 130,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Thor : Love & Thunder",
    director: "Taika Waititi",
    actors: [
      {
        name: "Chris Hemsworth",
      },
    ],
    coverUrl: "/movies/validated/543002-thor-love-and-thunder-0-150-0-225-crop.jpg",
    releaseDate: "2022-07-08",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Captain Marvel",
    director: "Anna Boden, Ryan Fleck",
    actors: [
      {
        name: "Brie Larson",
      },
    ],
    coverUrl: "/movies/validated/226750-captain-marvel-0-150-0-225-crop.jpg",
    releaseDate: "2019-03-08",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Les Marvels",
    director: "Nia DaCosta",
    actors: [
      {
        name: "Brie Larson",
      },
    ],
    coverUrl: "/movies/validated/536970-the-marvels-0-150-0-225-crop.jpg",
    releaseDate: "2023-11-10",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Shang-Chi et la Légende des Dix Anneaux",
    director: "Destin Daniel Cretton",
    actors: [
      {
        name: "Simu Liu",
      },
    ],
    coverUrl: "/movies/validated/494969-shang-chi-and-the-legend-of-the-ten-rings-0-150-0-225-crop.jpg",
    releaseDate: "2021-09-03",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Doctor Strange",
    director: "Scott Derrickson",
    actors: [{ name: "Benedict Cumberbatch" }],
    coverUrl: "/movies/validated/209381-doctor-strange-0-150-0-225-crop.jpg",
    releaseDate: "2016-11-04",
    rating: 0,
    length: 115,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Doctor Strange dans le Multivers de la Folie",
    director: "Sam Raimi",
    actors: [
      {
        name: "Benedict Cumberbatch",
      },
    ],
    coverUrl: "/movies/validated/385511-doctor-strange-in-the-multiverse-of-madness-0-150-0-225-crop.jpg",
    releaseDate: "2022-05-06",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Black Panther",
    director: "Ryan Coogler",
    actors: [
      {
        name: "Chadwick Boseman",
      },
    ],
    coverUrl: "/movies/validated/209383-black-panther-0-150-0-225-crop.jpg",
    releaseDate: "2018-02-16",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Black Panther : Wakanda pour Toujours",
    director: "Ryan Coogler",
    actors: [
      {
        name: "Letitia Wright",
      },
    ],
    coverUrl: "/movies/validated/435460-black-panther-wakanda-forever-0-150-0-225-crop.jpg",
    releaseDate: "2022-11-11",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Les Gardiens de la Galaxie",
    director: "James Gunn",
    actors: [{ name: "Chris Pratt" }],
    coverUrl: "/movies/validated/93676-guardians-of-the-galaxy-0-150-0-225-crop.jpg",
    releaseDate: "2014-08-01",
    rating: 0,
    length: 121,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Les Gardiens de la Galaxie Vol. 2",
    director: "James Gunn",
    actors: [{ name: "Chris Pratt" }],
    coverUrl: "/movies/validated/les_gardiens_de_la_galaxie_2.jpg",
    releaseDate: "2017-05-05",
    rating: 0,
    length: 136,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Les Gardiens de la Galaxie Vol. 3",
    director: "James Gunn",
    actors: [
      {
        name: "Chris Pratt",
      },
    ],
    coverUrl: "/movies/validated/379711-guardians-of-the-galaxy-volume-3-0-150-0-225-crop.jpg",
    releaseDate: "2023-05-05",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Ant-Man",
    director: "Peyton Reed",
    actors: [{ name: "Paul Rudd" }],
    coverUrl: "/movies/validated/83557-ant-man-0-150-0-225-crop.jpg",
    releaseDate: "2015-07-17",
    rating: 0,
    length: 117,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Ant-Man et la Guêpe",
    director: "Peyton Reed",
    actors: [
      {
        name: "Paul Rudd",
      },
    ],
    coverUrl: "/movies/validated/296341-ant-man-and-the-wasp-0-150-0-225-crop.jpg",
    releaseDate: "2018-07-06",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Ant-Man et la Guêpe : Quantumania",
    director: "Peyton Reed",
    actors: [
      {
        name: "Paul Rudd",
      },
    ],
    coverUrl: "/movies/validated/566237-ant-man-and-the-wasp-quantumania-0-150-0-225-crop.jpg",
    releaseDate: "2023-02-17",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Spider-Man: Homecoming",
    director: "Jon Watts",
    actors: [{ name: "Tom Holland" }],
    coverUrl: "/movies/validated/242710-spider-man-homecoming-0-150-0-225-crop.jpg",
    releaseDate: "2017-07-07",
    rating: 0,
    length: 133,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Spider-Man: Far From Home",
    director: "Jon Watts",
    actors: [
      {
        name: "Tom Holland",
      },
    ],
    coverUrl: "/movies/validated/362977-spider-man-far-from-home-0-150-0-225-crop.jpg",
    releaseDate: "2019-07-02",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Spider-Man : No Way Home",
    director: "Jon Watts",
    actors: [
      {
        name: "Tom Holland",
      },
    ],
    coverUrl: "/movies/validated/560787-spider-man-no-way-home-0-150-0-225-crop.jpg",
    releaseDate: "2021-12-17",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Black Widow",
    director: "Cate Shortland",
    actors: [
      {
        name: "Scarlett Johansson",
      },
    ],
    coverUrl: "/movies/validated/427807-black-widow-0-150-0-225-crop.jpg",
    releaseDate: "2021-07-09",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Les Éternels",
    director: "Chloé Zhao",
    actors: [
      {
        name: "Gemma Chan",
      },
    ],
    coverUrl: "/movies/validated/454016-eternals-0-150-0-225-crop.jpg",
    releaseDate: "2021-11-05",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Deadpool et Wolverine",
    director: "Shawn Levy",
    actors: [
      {
        name: "Ryan Reynolds",
      },
      {
        name: "Hugh Jackman",
      },
    ],
    coverUrl: "/movies/validated/462870-deadpool-wolverine-0-150-0-225-crop.jpg",
    releaseDate: "2024-07-26",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
];