import { Movie } from './movies_1';

export const moviesSagaPage5: Movie[] = [
  {
    title: 'Scooby-Doo',
    director: 'Raja Gosnell',
    actors: [{ name: 'Freddie Prinze Jr.' }],
    coverUrl: '/movies_pictures/scooby-doo.jpg',
    releaseDate: '2002-06-14',
    rating: 3,
    length: 86,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Scooby-Doo 2: Monsters Unleashed',
    director: 'Raja Gosnell',
    actors: [{ name: 'Freddie Prinze Jr.' }],
    coverUrl:
      '/movies_pictures/45679-scooby-doo-2-monsters-unleashed-0-150-0-225-crop.jpg',
    releaseDate: '2004-03-26',
    rating: 3,
    length: 93,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Matrix',
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: [{ name: 'Keanu Reeves' }],
    coverUrl: '/movies_pictures/51518-the-matrix-0-150-0-225-crop.jpg',
    releaseDate: '1999-03-31',
    rating: 4.5,
    length: 136,
    genre: 'Science Fiction',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'The Matrix Reloaded',
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: [{ name: 'Keanu Reeves' }],
    coverUrl: '/movies_pictures/51517-the-matrix-reloaded-0-150-0-225-crop.jpg',
    releaseDate: '2003-05-15',
    rating: 3.25,
    length: 138,
    genre: 'Science Fiction',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'The Matrix Revolutions',
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: [{ name: 'Keanu Reeves' }],
    coverUrl:
      '/movies_pictures/51516-the-matrix-revolutions-0-150-0-225-crop.jpg',
    releaseDate: '2003-11-05',
    rating: 3.25,
    length: 129,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Spy Kids',
    director: 'Robert Rodriguez',
    actors: [{ name: 'Alexa Vega' }],
    coverUrl: '/movies_pictures/spy_kids.jpg',
    releaseDate: '2001-03-30',
    rating: 3.25,
    length: 88,
    genre: 'Adventure',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: "Spy Kids 2: L'île des rêves perdus",
    director: 'Robert Rodriguez',
    actors: [{ name: 'Alexa Vega' }],
    coverUrl:
      '/movies_pictures/47110-spy-kids-2-island-of-lost-dreams-0-150-0-225-crop.jpg',
    releaseDate: '2002-08-07',
    rating: 3,
    length: 100,
    genre: 'Adventure',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Spy Kids 3-D: Game Over',
    director: 'Robert Rodriguez',
    actors: [{ name: 'Alexa Vega' }],
    coverUrl:
      '/movies_pictures/44637-spy-kids-3-d-game-over-0-150-0-225-crop.jpg',
    releaseDate: '2003-07-25',
    rating: 3.5,
    length: 84,
    genre: 'Adventure',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Bad Boys',
    director: 'Michael Bay',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/46870-bad-boys-0-150-0-225-crop.jpg',
    releaseDate: '1995-04-07',
    rating: 3.5,
    length: 119,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Bad Boys II',
    director: 'Michael Bay',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/47473-bad-boys-ii-0-150-0-225-crop.jpg',
    releaseDate: '2003-07-18',
    rating: 3.25,
    length: 147,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Men in Black',
    director: 'Barry Sonnenfeld',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/51514-men-in-black-0-150-0-225-crop.jpg',
    releaseDate: '1997-07-02',
    rating: 4,
    length: 98,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Men in Black II',
    director: 'Barry Sonnenfeld',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/51513-men-in-black-ii-0-150-0-225-crop.jpg',
    releaseDate: '2002-07-03',
    rating: 4.25,
    length: 88,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Men in Black 3',
    director: 'Barry Sonnenfeld',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/men_in_black_3.jpg',
    releaseDate: '2012-05-25',
    rating: 3.25,
    length: 106,
    genre: 'Science Fiction',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Lara Croft : Tomb Raider',
    director: 'Simon West',
    actors: [{ name: 'Angelina Jolie' }],
    coverUrl:
      '/movies_pictures/50617-lara-croft-tomb-raider-0-150-0-225-crop.jpg',
    releaseDate: '2001-06-15',
    rating: 3.25,
    length: 100,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'La Momie',
    director: 'Stephen Sommers',
    actors: [{ name: 'Brendan Fraser' }],
    coverUrl: '/movies_pictures/la_momie.jpg',
    releaseDate: '1999-05-07',
    rating: 4.5,
    length: 125,
    genre: 'Adventure',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Le Retour de la Momie',
    director: 'Stephen Sommers',
    actors: [{ name: 'Brendan Fraser' }],
    coverUrl: '/movies_pictures/50818-the-mummy-returns-0-150-0-225-crop.jpg',
    releaseDate: '2001-05-04',
    rating: 3.5,
    length: 130,
    genre: 'Adventure',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: "L'arme fatale",
    director: 'Richard Donner',
    actors: [{ name: 'Mel Gibson' }],
    coverUrl:
      '/movies_pictures/mF2bTqJuxbZPeEJRIMrA2WeQVxu-0-150-0-225-crop.jpg',
    releaseDate: '1987-03-06',
    rating: 4.25,
    length: 110,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: "L'arme fatale 2",
    director: 'Richard Donner',
    actors: [{ name: 'Mel Gibson' }],
    coverUrl: '/movies_pictures/51211-lethal-weapon-2-0-150-0-225-crop.jpg',
    releaseDate: '1989-07-07',
    rating: 4,
    length: 114,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: "L'arme fatale 3",
    director: 'Richard Donner',
    actors: [{ name: 'Mel Gibson' }],
    coverUrl: '/movies_pictures/arme_fatale_3.jpg',
    releaseDate: '1992-05-15',
    rating: 4,
    length: 118,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: "L'arme fatale 4",
    director: 'Richard Donner',
    actors: [{ name: 'Mel Gibson' }],
    coverUrl: '/movies_pictures/51209-lethal-weapon-4-0-150-0-225-crop.jpg',
    releaseDate: '1998-07-10',
    rating: 4,
    length: 127,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Predator',
    director: 'John McTiernan',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/51944-predator-0-150-0-225-crop.jpg',
    releaseDate: '1987-06-12',
    rating: 4,
    length: 107,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Predator 2',
    director: 'Stephen Hopkins',
    actors: [{ name: 'Danny Glover' }],
    coverUrl: '/movies_pictures/predator_2.jpg',
    releaseDate: '1990-11-21',
    rating: 3,
    length: 108,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Predators',
    director: 'Nimród Antal',
    actors: [{ name: 'Adrien Brody' }],
    coverUrl: '/movies_pictures/predators.jpg',
    releaseDate: '2010-07-09',
    rating: 3.5,
    length: 107,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'The Predator',
    director: 'Shane Black',
    actors: [
      {
        name: 'Boyd Holbrook',
      },
    ],
    coverUrl: '/movies_pictures/277351-the-predator-0-150-0-225-crop.jpg',
    releaseDate: '2018-09-14',
    rating: 3.25,
    length: 107,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Alien',
    director: 'Ridley Scott',
    actors: [{ name: 'Sigourney Weaver' }],
    coverUrl: '/movies_pictures/alien.jpg',
    releaseDate: '1979-05-25',
    rating: 3.5,
    length: 117,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Aliens',
    director: 'James Cameron',
    actors: [{ name: 'Sigourney Weaver' }],
    coverUrl: '/movies_pictures/51445-aliens-0-150-0-225-crop.jpg',
    releaseDate: '1986-07-18',
    rating: 3.5,
    length: 137,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Alien 3',
    director: 'David Fincher',
    actors: [{ name: 'Sigourney Weaver' }],
    coverUrl: '/movies_pictures/47888-alien-0-150-0-225-crop.jpg',
    releaseDate: '1992-05-22',
    rating: 3.25,
    length: 114,
    genre: 'Science Fiction',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Alien : La Résurrection',
    director: 'Jean-Pierre Jeunet',
    actors: [{ name: 'Sigourney Weaver' }],
    coverUrl: '/movies_pictures/47887-alien-resurrection-0-150-0-225-crop.jpg',
    releaseDate: '1997-11-26',
    rating: 3.5,
    length: 109,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Alien vs. Predator',
    director: 'Paul W.S. Anderson',
    actors: [{ name: 'Sanaa Lathan' }],
    coverUrl:
      '/movies_pictures/51695-avp-alien-vs-predator-0-150-0-225-crop.jpg',
    releaseDate: '2004-08-13',
    rating: 3.5,
    length: 101,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Alien vs. Predator : Requiem',
    director: 'Colin Strause, Greg Strause',
    actors: [{ name: 'Steven Pasquale' }],
    coverUrl:
      '/movies_pictures/51655-avpr-aliens-vs-predator-requiem-0-150-0-225-crop.jpg',
    releaseDate: '2007-12-25',
    rating: 3,
    length: 94,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Independence Day',
    director: 'Roland Emmerich',
    actors: [{ name: 'Will Smith' }],
    coverUrl:
      '/movies_pictures/bqLlWZJdhrS0knfEJRkquW7L8z2-0-150-0-225-crop.jpg',
    releaseDate: '1996-07-03',
    rating: 4,
    length: 145,
    genre: 'Science Fiction',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Independence Day : Resurgence',
    director: 'Roland Emmerich',
    actors: [{ name: 'Will Smith' }],
    coverUrl:
      '/movies_pictures/507660-independence-day-the-id4-invasion-0-150-0-225-crop.jpg',
    releaseDate: '1996-07-03',
    rating: 3.25,
    length: 145,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "Maman j'ai raté l'avion",
    director: 'Chris Columbus',
    actors: [{ name: 'Macaulay Culkin' }],
    coverUrl: '/movies_pictures/home_alone.jpg',
    releaseDate: '1990-11-16',
    rating: 4,
    length: 103,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: "Maman j'ai raté l'avion 2",
    director: 'Chris Columbus',
    actors: [{ name: 'Macaulay Culkin' }],
    coverUrl: '/movies_pictures/home%20alone%202-0-150-0-225-crop.jpg',
    releaseDate: '1992-11-20',
    rating: 3.25,
    length: 120,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Retour vers le futur',
    director: 'Robert Zemeckis',
    actors: [{ name: 'Michael J. Fox' }],
    coverUrl: '/movies_pictures/51945-back-to-the-future-0-150-0-225-crop.jpg',
    releaseDate: '1985-07-03',
    rating: 5,
    length: 116,
    genre: 'Science Fiction',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Retour vers le futur 2',
    director: 'Robert Zemeckis',
    actors: [{ name: 'Michael J. Fox' }],
    coverUrl:
      '/movies_pictures/51886-back-to-the-future-part-ii-0-150-0-225-crop.jpg',
    releaseDate: '1989-11-22',
    rating: 4,
    length: 108,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Retour vers le futur 3',
    director: 'Robert Zemeckis',
    actors: [{ name: 'Michael J. Fox' }],
    coverUrl:
      '/movies_pictures/51856-back-to-the-future-part-iii-0-150-0-225-crop.jpg',
    releaseDate: '1990-05-25',
    rating: 4.25,
    length: 118,
    genre: 'Science Fiction',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Rambo : First Blood',
    director: 'Ted Kotcheff',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/51088-first-blood-0-150-0-225-crop.jpg',
    releaseDate: '1982-10-22',
    rating: 4.5,
    length: 93,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Rambo 2 : la mission',
    director: 'George P. Cosmatos',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl:
      '/movies_pictures/51087-rambo-first-blood-part-ii-0-150-0-225-crop.jpg',
    releaseDate: '1985-05-22',
    rating: 3.5,
    length: 96,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Rambo 3',
    director: 'Peter MacDonald',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/51086-rambo-iii-0-150-0-225-crop.jpg',
    releaseDate: '1988-05-25',
    rating: 4,
    length: 102,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'John Rambo',
    director: 'Sylvester Stallone',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/47983-rambo-0-150-0-225-crop.jpg',
    releaseDate: '2008-01-25',
    rating: 3.25,
    length: 92,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Le Parrain',
    director: 'Francis Ford Coppola',
    actors: [{ name: 'Marlon Brando' }],
    coverUrl: '/movies_pictures/51818-the-godfather-0-150-0-225-crop.jpg',
    releaseDate: '1972-03-24',
    rating: 4,
    length: 175,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le Parrain 2',
    director: 'Francis Ford Coppola',
    actors: [{ name: 'Al Pacino' }],
    coverUrl:
      '/movies_pictures/51816-the-godfather-part-ii-0-150-0-225-crop.jpg',
    releaseDate: '1974-12-20',
    rating: 3,
    length: 202,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
