import { Movie } from "./movies_1";

export const moviesLove: Movie[] = [
  {
    title: "Mon inconnue",
    director: "Hugo Gélin",
    actors: [
      {
        name: "François Civil",
      },
    ],
    coverUrl: "/movies_pictures/validated/498516-love-at-second-sight-0-150-0-225-crop.jpg",
    releaseDate: "2019-01-30",
    rating: 4.5,
    length: 118,
    genre: "Romance",
    timesWatched: 5,
  },
  {
    title: "The Princess Switch",
    director: "Mike Rohl",
    actors: [
      {
        name: "Vanessa Hudgens",
      },
    ],
    coverUrl: "/movies_pictures/validated/485841-the-princess-switch-0-150-0-225-crop.jpg",
    releaseDate: "2018-11-16",
    rating: 0,
    length: 101,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Petits coups montés",
    director: "Claire Scanlon",
    actors: [
      {
        name: "Zoey Deutch",
      },
    ],
    coverUrl: "/movies_pictures/validated/319550-set-it-up-0-150-0-225-crop.jpg",
    releaseDate: "2018-06-15",
    rating: 0,
    length: 105,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "The life list",
    director: "Liz W. Garcia",
    actors: [
      {
        name: "Katherine Heigl",
      },
    ],
    coverUrl: "/movies_pictures/validated/1138997-the-life-list-0-150-0-225-crop.jpg",
    releaseDate: "2024-07-18",
    rating: 0,
    length: 104,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Tout le Bleu du Ciel",
    director: "João Canijo",
    actors: [
      {
        name: "Rita Blanco",
      },
    ],
    coverUrl: "/movies_pictures/validated/1307347-tout-le-bleu-du-ciel-2025-0-150-0-225-crop.jpg",
    releaseDate: "2022-09-08",
    rating: 3.5,
    length: 127,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Nos coeurs meurtris",
    director: "Elizabeth Allen Rosenbaum",
    actors: [
      {
        name: "Sofia Carson",
      },
    ],
    coverUrl: "/movies_pictures/validated/683195-purple-hearts-0-150-0-225-crop.jpg",
    releaseDate: "2022-07-29",
    rating: 4.25,
    length: 122,
    genre: "Romance",
    timesWatched: 5,
  },
  {
    title: "Au plaisir de se faire trahir",
    director: "Diego Freitas",
    actors: [
      {
        name: "Giovanna Lancellotti",
      },
    ],
    coverUrl: "/movies_pictures/validated/1060546-burning-betrayal-0-150-0-225-crop.jpg",
    releaseDate: "2023-10-25",
    rating: 0,
    length: 104,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "La Probabilité statistique de l'amour au premier regard",
    director: "Vanessa Caswill",
    actors: [
      {
        name: "Haley Lu Richardson",
      },
    ],
    coverUrl: "/movies_pictures/validated/1146306_300x450.webp",
    releaseDate: "2023-09-15",
    rating: 0,
    length: 91,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Ce sera toi",
    director: "Alauda Ruiz de Azúa",
    actors: [
      {
        name: "Silvia Alonso",
      },
    ],
    coverUrl: "/movies_pictures/validated/735234-love-at-first-kiss-0-150-0-225-crop.jpg",
    releaseDate: "2023-02-10",
    rating: 0,
    length: 103,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Hello, goodbye and everything in between",
    director: "Michael Lewen",
    actors: [
      {
        name: "Talia Ryder",
      },
    ],
    coverUrl: "/movies_pictures/validated/666928-hello-goodbye-and-everything-in-between-0-150-0-225-crop.jpg",
    releaseDate: "2022-07-06",
    rating: 0,
    length: 91,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Un Accord Parfait",
    director: "Stuart McDonald",
    actors: [
      {
        name: "Victoria Justice",
      },
    ],
    coverUrl: "/movies_pictures/validated/839735-a-perfect-pairing-0-150-0-225-crop.jpg",
    releaseDate: "2022-05-19",
    rating: 0,
    length: 101,
    genre: "Romance",
    timesWatched: 3,
  },
  {
    title: "The In-between",
    director: "Arie Posin",
    actors: [
      {
        name: "Joey King",
      },
    ],
    coverUrl: "/movies_pictures/validated/735089-the-in-between-0-150-0-225-crop.jpg",
    releaseDate: "2022-02-11",
    rating: 0,
    length: 116,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "À Travers Ma Fenêtre",
    director: "Marçal Forés",
    actors: [
      {
        name: "Julio Peña",
      },
    ],
    coverUrl: "/movies_pictures/validated/735239-through-my-window-0-150-0-225-crop.jpg",
    releaseDate: "2022-02-04",
    rating: 0,
    length: 113,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Love Hard",
    director: "Hernán Jiménez",
    actors: [
      {
        name: "Nina Dobrev",
      },
    ],
    coverUrl: "/movies_pictures/validated/656542-love-hard-0-150-0-225-crop.jpg",
    releaseDate: "2021-11-05",
    rating: 0,
    length: 104,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "L'Amour complexe",
    director: "Steven Tsuchida",
    actors: [
      {
        name: "Christina Milian",
      },
    ],
    coverUrl: "/movies_pictures/validated/704151-resort-to-love-0-150-0-225-crop.jpg",
    releaseDate: "2021-07-29",
    rating: 0,
    length: 101,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "La Belle et la Bête",
    director: "Bill Condon",
    actors: [{ name: "Emma Watson" }],
    coverUrl: "/movies_pictures/validated/248708-beauty-and-the-beast-0-150-0-225-crop.jpg",
    releaseDate: "2017-03-17",
    rating: 0,
    length: 129,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "Un choix",
    director: "Ross Katz",
    actors: [{ name: "Benjamin Walker" }],
    coverUrl: "/movies_pictures/validated/258147-the-choice-0-150-0-225-crop.jpg",
    releaseDate: "2016-02-05",
    rating: 0,
    length: 111,
    genre: "Romance",
    timesWatched: 3,
  },
  {
    title: "L'agence",
    director: "George Nolfi",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies_pictures/validated/the-adjustment-bureau-original-1-0-150-0-225-crop.jpg",
    releaseDate: "2011-03-04",
    rating: 0,
    length: 106,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "Un jour",
    director: "Lone Scherfig",
    actors: [{ name: "Anne Hathaway" }],
    coverUrl: "/movies_pictures/validated/un_jour.jpg",
    releaseDate: "2011-08-19",
    rating: 0,
    length: 107,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Sex Friends",
    director: "Ivan Reitman",
    actors: [{ name: "Natalie Portman" }],
    coverUrl: "/movies_pictures/validated/no-strings-attached-original-0-150-0-225-crop.jpg",
    releaseDate: "2011-01-21",
    rating: 0,
    length: 108,
    genre: "Romance",
    timesWatched: 20,
  },
  {
    title: "Love and Other Drugs",
    director: "Edward Zwick",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies_pictures/validated/21801-love-other-drugs-0-150-0-225-crop.jpg",
    releaseDate: "2010-11-24",
    rating: 0,
    length: 112,
    genre: "Romance",
    timesWatched: 20,
  },
  {
    title: "Sexy Dance",
    director: "Anne Fletcher",
    actors: [{ name: "Channing Tatum" }],
    coverUrl: "/movies_pictures/validated/46848-step-up-0-150-0-225-crop.jpg",
    releaseDate: "2006-08-11",
    rating: 0,
    length: 104,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Sexy Dance 2",
    director: "Jon M. Chu",
    actors: [{ name: "Briana Evigan" }],
    coverUrl: "/movies_pictures/validated/47804-step-up-2-0-150-0-225-crop.jpg",
    releaseDate: "2008-02-14",
    rating: 0,
    length: 98,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Sexy Dance 3D",
    director: "Jon M. Chu",
    actors: [{ name: "Rick Malambri" }],
    coverUrl: "/movies_pictures/validated/23784-step-up-3-0-150-0-225-crop.jpg",
    releaseDate: "2010-08-06",
    rating: 0,
    length: 107,
    genre: "Drama",
    timesWatched: 15,
  },
  {
    title: "L'Arnacœur",
    director: "Pascal Chaumeil",
    actors: [{ name: "Romain Duris" }],
    coverUrl: "/movies_pictures/validated/23804-heartbreaker-0-150-0-225-crop.jpg",
    releaseDate: "2010-03-17",
    rating: 0,
    length: 105,
    genre: "Romance",
    timesWatched: 20,
  },
  {
    title: "Remember Me",
    director: "Allen Coulter",
    actors: [{ name: "Robert Pattinson" }],
    coverUrl: "/movies_pictures/validated/37502-remember-me-0-150-0-225-crop.jpg",
    releaseDate: "2010-03-12",
    rating: 0,
    length: 113,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Valentine's Day",
    director: "Garry Marshall",
    actors: [{ name: "Julia Roberts" }],
    coverUrl: "/movies_pictures/validated/valentine_day.jpg",
    releaseDate: "2010-02-12",
    rating: 0,
    length: 125,
    genre: "Romance",
    timesWatched: 3,
  },
  {
    title: "La proposition",
    director: "Anne Fletcher",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies_pictures/validated/40479-the-proposal-0-150-0-225-crop.jpg",
    releaseDate: "2009-06-19",
    rating: 0,
    length: 108,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "17 Again",
    director: "Burr Steers",
    actors: [{ name: "Zac Efron" }],
    coverUrl: "/movies_pictures/validated/41276-17-again-0-150-0-225-crop.jpg",
    releaseDate: "2009-04-17",
    rating: 0,
    length: 102,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "(500) Jours Ensemble",
    director: "Marc Webb",
    actors: [{ name: "Joseph Gordon-Levitt" }],
    coverUrl: "/movies_pictures/validated/39350--500-days-of-summer-0-150-0-225-crop.jpg",
    releaseDate: "2009-07-17",
    rating: 0,
    length: 95,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Jackpot",
    director: "Tom Vaughan",
    actors: [{ name: "Ashton Kutcher" }],
    coverUrl: "/movies_pictures/validated/47414-what-happens-in-vegas--0-150-0-225-crop.jpg",
    releaseDate: "2008-05-09",
    rating: 0,
    length: 99,
    genre: "Comedy",
    timesWatched: 3,
  },
  {
    title: "Horton",
    director: "Jimmy Hayward, Steve Martino",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies_pictures/validated/horton.jpg",
    releaseDate: "2008-03-14",
    rating: 0,
    length: 86,
    genre: "Animation",
    timesWatched: 1,
  },
  {
    title: "Juno",
    director: "Jason Reitman",
    actors: [{ name: "Ellen Page" }],
    coverUrl: "/movies_pictures/validated/48051-juno-0-150-0-225-crop.jpg",
    releaseDate: "2007-12-25",
    rating: 0,
    length: 96,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Orgueil et Préjugés",
    director: "Joe Wright",
    actors: [{ name: "Keira Knightley" }],
    coverUrl: "/movies_pictures/validated/orgueil_et_prejuges.jpg",
    releaseDate: "2005-09-16",
    rating: 0,
    length: 129,
    genre: "Romance",
    timesWatched: 2,
  },
  {
    title: "Match Point",
    director: "Woody Allen",
    actors: [{ name: "Jonathan Rhys Meyers" }],
    coverUrl: "/movies_pictures/validated/match_point.jpg",
    releaseDate: "2005-05-12",
    rating: 0,
    length: 124,
    genre: "Thriller",
    timesWatched: 5,
  },
  {
    title: "Hitch : Expert en Séduction",
    director: "Andy Tennant",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/validated/47699-hitch-0-150-0-225-crop.jpg",
    releaseDate: "2005-02-11",
    rating: 0,
    length: 118,
    genre: "Comedy",
    timesWatched: 30,
  },
  {
    title: "First Daughter",
    director: "Forest Whitaker",
    actors: [{ name: "Katie Holmes" }],
    coverUrl: "/movies_pictures/validated/43443-first-daughter-0-150-0-225-crop.jpg",
    releaseDate: "2004-09-24",
    rating: 0,
    length: 106,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "The Terminal",
    director: "Steven Spielberg",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies_pictures/validated/51527-the-terminal-0-150-0-225-crop.jpg",
    releaseDate: "2004-06-18",
    rating: 0,
    length: 128,
    genre: "Drama",
    timesWatched: 3,
  },
  {
    title: "Eternal Sunshine of the Spotless Mind",
    director: "Michel Gondry",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies_pictures/validated/eternal_sunchine_of_the_spotless_mind.jpg",
    releaseDate: "2004-03-19",
    rating: 0,
    length: 108,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "The Girl Next Door",
    director: "Luke Greenfield",
    actors: [{ name: "Emile Hirsch" }],
    coverUrl: "/movies_pictures/validated/46081-the-girl-next-door-2004-0-150-0-225-crop.jpg",
    releaseDate: "2004-04-09",
    rating: 0,
    length: 109,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "50 First Dates",
    director: "Peter Segal",
    actors: [{ name: "Adam Sandler" }],
    coverUrl: "/movies_pictures/validated/50773-50-first-dates-0-150-0-225-crop.jpg",
    releaseDate: "2004-02-13",
    rating: 0,
    length: 99,
    genre: "Comedy",
    timesWatched: 30,
  },
  {
    title: "Love Actually",
    director: "Richard Curtis",
    actors: [{ name: "Hugh Grant" }],
    coverUrl: "/movies_pictures/validated/51602-love-actually-0-150-0-225-crop.jpg",
    releaseDate: "2003-11-07",
    rating: 0,
    length: 135,
    genre: "Romance",
    timesWatched: 5,
  },
  {
    title: "Le temps d'un automne",
    director: "Adam Shankman",
    actors: [{ name: "Mandy Moore" }],
    coverUrl: "/movies_pictures/validated/46422-a-walk-to-remember-0-150-0-225-crop.jpg",
    releaseDate: "2002-01-25",
    rating: 4,
    length: 101,
    genre: "Romance",
    timesWatched: 10,
  },
  {
    title: "Pearl Harbor",
    director: "Michael Bay",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies_pictures/validated/51448-pearl-harbor-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-25",
    rating: 0,
    length: 183,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Ce que Veulent les Femmes",
    director: "Nancy Meyers",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies_pictures/validated/49539-what-women-want-0-150-0-225-crop.jpg",
    releaseDate: "2000-12-15",
    rating: 0,
    length: 127,
    genre: "Comedy",
    timesWatched: 20,
  },
  {
    title: "Coup de foudre à Notting Hill",
    director: "Roger Michell",
    actors: [{ name: "Julia Roberts" }],
    coverUrl: "/movies_pictures/validated/notting-hill-0-150-0-225-crop.jpg",
    releaseDate: "1999-05-28",
    rating: 0,
    length: 124,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "Rencontre avec Joe Black",
    director: "Martin Brest",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies_pictures/validated/51762-meet-joe-black-0-150-0-225-crop.jpg",
    releaseDate: "1998-11-13",
    rating: 2,
    length: 178,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Pretty Woman",
    director: "Garry Marshall",
    actors: [{ name: "Julia Roberts" }],
    coverUrl: "/movies_pictures/validated/51936-pretty-woman-0-150-0-225-crop.jpg",
    releaseDate: "1990-03-23",
    rating: 0,
    length: 119,
    genre: "Romance",
    timesWatched: 10,
  },
  {
    title: "Amour au Carré",
    director: "Filip Zylber",
    actors: [
      {
        name: "Adrianna Chlebicka",
      },
    ],
    coverUrl: "/movies_pictures/validated/705695-squared-love-0-150-0-225-crop.jpg",
    releaseDate: "2021-02-11",
    rating: 0,
    length: 105,
    genre: "Romance",
    timesWatched: 1,
  },
  {
    title: "La La Land",
    director: "Damien Chazelle",
    actors: [{ name: "Ryan Gosling" }],
    coverUrl: "/movies_pictures/validated/240344-la-la-land-0-150-0-225-crop.jpg",
    releaseDate: "2016-12-09",
    rating: 0,
    length: 128,
    genre: "Romance",
    timesWatched: 1,
  },
];