import { Movie } from "./movies";

export const moviesPage11: Movie[] = [
  {
    title: "Spaceballs",
    director: "Mel Brooks",
    actors: [{ name: "Mel Brooks" }],
    coverUrl: "/movies/spaceballs.jpg",
    releaseDate: "1987-06-24",
    rating: 0,
    length: 96,
    genre: "Comedy",
  },
  {
    title: "Predator",
    director: "John McTiernan",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/predator.jpg",
    releaseDate: "1987-06-12",
    rating: 0,
    length: 107,
    genre: "Action",
  },
  {
    title: "The Untouchables",
    director: "Brian De Palma",
    actors: [{ name: "Kevin Costner" }],
    coverUrl: "/movies/untouchables.jpg",
    releaseDate: "1987-06-03",
    rating: 0,
    length: 119,
    genre: "Crime",
  },
  {
    title: "Dirty Dancing",
    director: "Emile Ardolino",
    actors: [{ name: "Patrick Swayze" }],
    coverUrl: "/movies/dirty_dancing.jpg",
    releaseDate: "1987-08-21",
    rating: 0,
    length: 100,
    genre: "Romance",
  },
  {
    title: "Lethal Weapon",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies/lethal_weapon.jpg",
    releaseDate: "1987-03-06",
    rating: 0,
    length: 110,
    genre: "Action",
  },
  {
    title: "Over the Top",
    director: "Menahem Golan",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/over_top.jpg",
    releaseDate: "1987-02-13",
    rating: 0,
    length: 93,
    genre: "Drama",
  },
  {
    title: "Aliens",
    director: "James Cameron",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies/aliens.jpg",
    releaseDate: "1986-07-18",
    rating: 0,
    length: 137,
    genre: "Science Fiction",
  },
  {
    title: "Rocky IV",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rocky_4.jpg",
    releaseDate: "1985-11-27",
    rating: 0,
    length: 91,
    genre: "Drama",
  },
  {
    title: "Commando",
    director: "Mark L. Lester",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/commando.jpg",
    releaseDate: "1985-10-04",
    rating: 0,
    length: 90,
    genre: "Action",
  },
  {
    title: "Back to the Future",
    director: "Robert Zemeckis",
    actors: [{ name: "Michael J. Fox" }],
    coverUrl: "/movies/back_future.jpg",
    releaseDate: "1985-07-03",
    rating: 0,
    length: 116,
    genre: "Science Fiction",
  },
  {
    title: "Rambo: First Blood Part II",
    director: "George P. Cosmatos",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rambo_first_blood_2.jpg",
    releaseDate: "1985-05-22",
    rating: 0,
    length: 96,
    genre: "Action",
  },
  {
    title: "Beverly Hills Cop",
    director: "Martin Brest",
    actors: [{ name: "Eddie Murphy" }],
    coverUrl: "/movies/beverly_hills_cop.jpg",
    releaseDate: "1984-12-05",
    rating: 0,
    length: 105,
    genre: "Action",
  },
  {
    title: "The Terminator",
    director: "James Cameron",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/terminator.jpg",
    releaseDate: "1984-10-26",
    rating: 0,
    length: 107,
    genre: "Science Fiction",
  },
  {
    title: "The Karate Kid",
    director: "John G. Avildsen",
    actors: [{ name: "Ralph Macchio" }],
    coverUrl: "/movies/karate_kid.jpg",
    releaseDate: "1984-06-22",
    rating: 0,
    length: 126,
    genre: "Drama",
  },
  {
    title: "Scarface",
    director: "Brian De Palma",
    actors: [{ name: "Al Pacino" }],
    coverUrl: "/movies/scarface.jpg",
    releaseDate: "1983-12-09",
    rating: 0,
    length: 170,
    genre: "Crime",
  },
  {
    title: "The Dead Zone",
    director: "David Cronenberg",
    actors: [{ name: "Christopher Walken" }],
    coverUrl: "/movies/dead_zone.jpg",
    releaseDate: "1983-10-21",
    rating: 0,
    length: 103,
    genre: "Thriller",
  },
  {
    title: "Return of the Jedi",
    director: "Richard Marquand",
    actors: [{ name: "Mark Hamill" }],
    coverUrl: "/movies/return_jedi.jpg",
    releaseDate: "1983-05-25",
    rating: 0,
    length: 131,
    genre: "Science Fiction",
  },
  {
    title: "First Blood",
    director: "Ted Kotcheff",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/first_blood.jpg",
    releaseDate: "1982-10-22",
    rating: 0,
    length: 93,
    genre: "Action",
  },
  {
    title: "Rocky III",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rocky_3.jpg",
    releaseDate: "1982-05-28",
    rating: 0,
    length: 99,
    genre: "Drama",
  },
  {
    title: "E.T. the Extra-Terrestrial",
    director: "Steven Spielberg",
    actors: [{ name: "Henry Thomas" }],
    coverUrl: "/movies/et.jpg",
    releaseDate: "1982-06-11",
    rating: 0,
    length: 115,
    genre: "Science Fiction",
  },
  {
    title: "The Cabbage Soup",
    director: "Jean-Charles Tacchella",
    actors: [{ name: "Philippe Noiret" }],
    coverUrl: "/movies/cabbage_soup.jpg",
    releaseDate: "1981-12-16",
    rating: 0,
    length: 100,
    genre: "Comedy",
  },
  {
    title: "The Shining",
    director: "Stanley Kubrick",
    actors: [{ name: "Jack Nicholson" }],
    coverUrl: "/movies/shining.jpg",
    releaseDate: "1980-05-23",
    rating: 0,
    length: 146,
    genre: "Horror",
  },
  {
    title: "The Empire Strikes Back",
    director: "Irvin Kershner",
    actors: [{ name: "Mark Hamill" }],
    coverUrl: "/movies/empire_strikes_back.jpg",
    releaseDate: "1980-05-21",
    rating: 0,
    length: 124,
    genre: "Science Fiction",
  },
  {
    title: "French Fried Vacation 2",
    director: "Patrice Leconte",
    actors: [{ name: "Josiane Balasko" }],
    coverUrl: "/movies/french_fried_vacation_2.jpg",
    releaseDate: "1979-12-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Rocky II",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rocky_2.jpg",
    releaseDate: "1979-06-15",
    rating: 0,
    length: 119,
    genre: "Drama",
  },
  {
    title: "Alien",
    director: "Ridley Scott",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies/alien.jpg",
    releaseDate: "1979-05-25",
    rating: 0,
    length: 117,
    genre: "Science Fiction",
  },
  {
    title: "French Fried Vacation",
    director: "Patrice Leconte",
    actors: [{ name: "Josiane Balasko" }],
    coverUrl: "/movies/french_fried_vacation.jpg",
    releaseDate: "1978-12-20",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Star Wars",
    director: "George Lucas",
    actors: [{ name: "Mark Hamill" }],
    coverUrl: "/movies/star_wars.jpg",
    releaseDate: "1977-05-25",
    rating: 0,
    length: 121,
    genre: "Science Fiction",
  },
  {
    title: "Rocky",
    director: "John G. Avildsen",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rocky.jpg",
    releaseDate: "1976-11-21",
    rating: 0,
    length: 120,
    genre: "Drama",
  },
  {
    title: "The Wing or the Thigh?",
    director: "Claude Zidi",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies/wing_or_thigh.jpg",
    releaseDate: "1976-10-27",
    rating: 0,
    length: 104,
    genre: "Comedy",
  },
  {
    title: "Taxi Driver",
    director: "Martin Scorsese",
    actors: [{ name: "Robert De Niro" }],
    coverUrl: "/movies/taxi_driver.jpg",
    releaseDate: "1976-02-08",
    rating: 0,
    length: 114,
    genre: "Crime",
  },
  {
    title: "The Godfather Part II",
    director: "Francis Ford Coppola",
    actors: [{ name: "Al Pacino" }],
    coverUrl: "/movies/godfather_2.jpg",
    releaseDate: "1974-12-20",
    rating: 0,
    length: 202,
    genre: "Crime",
  },
  {
    title: "The Exorcist",
    director: "William Friedkin",
    actors: [{ name: "Ellen Burstyn" }],
    coverUrl: "/movies/exorcist.jpg",
    releaseDate: "1973-12-26",
    rating: 0,
    length: 122,
    genre: "Horror",
  },
  {
    title: "The Mad Adventures of Rabbi Jacob",
    director: "Gérard Oury",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies/rabbi_jacob.jpg",
    releaseDate: "1973-10-17",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    actors: [{ name: "Marlon Brando" }],
    coverUrl: "/movies/godfather.jpg",
    releaseDate: "1972-03-24",
    rating: 0,
    length: 175,
    genre: "Crime",
  },
  {
    title: "Delusions of Grandeur",
    director: "Gérard Oury",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies/delusions_grandeur.jpg",
    releaseDate: "1971-12-08",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Oscar",
    director: "Édouard Molinaro",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies/oscar.jpg",
    releaseDate: "1967-10-11",
    rating: 0,
    length: 85,
    genre: "Comedy",
  },
  {
    title: "Fantomas",
    director: "André Hunebelle",
    actors: [{ name: "Jean Marais" }],
    coverUrl: "/movies/fantomas.jpg",
    releaseDate: "1964-11-04",
    rating: 0,
    length: 105,
    genre: "Adventure",
  },
  {
    title: "Le Gendarme de Saint-Tropez",
    director: "Jean Girault",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies/gendarme_saint_tropez.jpg",
    releaseDate: "1964-09-09",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "The Birds",
    director: "Alfred Hitchcock",
    actors: [{ name: "Tippi Hedren" }],
    coverUrl: "/movies/birds.jpg",
    releaseDate: "1963-03-28",
    rating: 0,
    length: 119,
    genre: "Horror",
  },
  {
    title: "Psycho",
    director: "Alfred Hitchcock",
    actors: [{ name: "Anthony Perkins" }],
    coverUrl: "/movies/psycho.jpg",
    releaseDate: "1960-06-16",
    rating: 0,
    length: 109,
    genre: "Horror",
  },
  {
    title: "12 Angry Men",
    director: "Sidney Lumet",
    actors: [{ name: "Henry Fonda" }],
    coverUrl: "/movies/12_angry_men.jpg",
    releaseDate: "1957-04-10",
    rating: 0,
    length: 96,
    genre: "Drama",
  },
  {
    title: "Peter Pan",
    director: "Clyde Geronimi, Wilfred Jackson, Hamilton Luske",
    actors: [{ name: "Bobby Driscoll" }],
    coverUrl: "/movies/peter_pan.jpg",
    releaseDate: "1953-02-05",
    rating: 0,
    length: 77,
    genre: "Animation",
  },
  {
    title: "Citizen Kane",
    director: "Orson Welles",
    actors: [{ name: "Orson Welles" }],
    coverUrl: "/movies/citizen_kane.jpg",
    releaseDate: "1941-05-01",
    rating: 0,
    length: 119,
    genre: "Drama",
  },
  {
    title: "Pinocchio",
    director: "Norman Ferguson, T. Hee, Wilfred Jackson, Jack Kinney, Hamilton Luske, Bill Roberts, Ben Sharpsteen",
    actors: [{ name: "Dickie Jones" }],
    coverUrl: "/movies/pinocchio.jpg",
    releaseDate: "1940-02-07",
    rating: 0,
    length: 88,
    genre: "Animation",
  },
  {
    title: "Modern Times",
    director: "Charles Chaplin",
    actors: [{ name: "Charles Chaplin" }],
    coverUrl: "/movies/modern_times.jpg",
    releaseDate: "1936-02-05",
    rating: 0,
    length: 87,
    genre: "Comedy",
  },
];