import { Movie } from "./movies_1";

export const moviesPage7: Movie[] = [
  {
    title: "Rocky Balboa",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/validated/51134-rocky-balboa-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-20",
    rating: 0,
    length: 102,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Nuit au Musée",
    director: "Shawn Levy",
    actors: [{ name: "Ben Stiller" }],
    coverUrl: "/movies/validated/50941-night-at-the-museum-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-22",
    rating: 0,
    length: 108,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "À la Recherche du Bonheur",
    director: "Gabriele Muccino",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/validated/51061-the-pursuit-of-happyness-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-15",
    rating: 0,
    length: 117,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Arthur et les Minimoys",
    director: "Luc Besson",
    actors: [{ name: "Freddie Highmore" }],
    coverUrl: "/movies/validated/46649-arthur-and-the-invisibles-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-13",
    rating: 0,
    length: 94,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "Hors de Prix",
    director: "Pierre Salvadori",
    actors: [{ name: "Audrey Tautou" }],
    coverUrl: "/movies/validated/48206-priceless-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-27",
    rating: 0,
    length: 104,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "300",
    director: "Zack Snyder",
    actors: [{ name: "Gerard Butler" }],
    coverUrl: "/movies/validated/51111-300-0-150-0-225-crop.jpg",
    releaseDate: "2007-03-09",
    rating: 0,
    length: 117,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Blood Diamond",
    director: "Edward Zwick",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/validated/51084-blood-diamond-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-08",
    rating: 0,
    length: 143,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "American Pie Presents: The Naked Mile",
    director: "Joe Nussbaum",
    actors: [{ name: "John White" }],
    coverUrl: "/movies/validated/47831-american-pie-presents-the-naked-mile-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-19",
    rating: 0,
    length: 97,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Casino Royale",
    director: "Martin Campbell",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies/validated/casino_royal.jpg",
    releaseDate: "2006-11-17",
    rating: 0,
    length: 144,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Le Prestige",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/validated/51147-the-prestige-0-150-0-225-crop.jpg",
    releaseDate: "2006-10-20",
    rating: 0,
    length: 130,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Les Infiltrés",
    director: "Martin Scorsese",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/validated/les_infiltres.jpg",
    releaseDate: "2006-10-06",
    rating: 0,
    length: 151,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "Accepted",
    director: "Steve Pink",
    actors: [{ name: "Justin Long" }],
    coverUrl: "/movies/validated/46823-accepted-0-150-0-225-crop.jpg",
    releaseDate: "2006-08-18",
    rating: 0,
    length: 93,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Sexy Dance",
    director: "Anne Fletcher",
    actors: [{ name: "Channing Tatum" }],
    coverUrl: "/movies/validated/46848-step-up-0-150-0-225-crop.jpg",
    releaseDate: "2006-08-11",
    rating: 0,
    length: 104,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Those Happy Days",
    director: "Claude Zidi Jr.",
    actors: [{ name: "Vincent Claude" }],
    coverUrl: "/movies/validated/39863-those-happy-days-0-150-0-225-crop.jpg",
    releaseDate: "2006-07-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Pirates des Caraïbes : Le Secret du Coffre Maudit",
    director: "Gore Verbinski",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/validated/51989-pirates-of-the-caribbean-dead-man-s-chest-0-150-0-225-crop.jpg",
    releaseDate: "2006-07-07",
    rating: 0,
    length: 151,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "Le Diable s'Habille en Prada",
    director: "David Frankel",
    actors: [{ name: "Anne Hathaway" }],
    coverUrl: "/movies/validated/51712-the-devil-wears-prada-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-30",
    rating: 0,
    length: 109,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Fast and Furious : Tokyo Drift",
    director: "Justin Lin",
    actors: [{ name: "Lucas Black" }],
    coverUrl: "/movies/validated/46986-the-fast-and-the-furious-tokyo-drift-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-16",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "X-Men : L'Affrontement Final",
    director: "Brett Ratner",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/validated/27713-x-men-the-last-stand-0-150-0-225-crop.jpg",
    releaseDate: "2006-05-26",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Babel",
    director: "Alejandro González Iñárritu",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/validated/51140-babel-0-150-0-225-crop.jpg",
    releaseDate: "2006-11-10",
    rating: 0,
    length: 143,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "The Break-Up",
    director: "Peyton Reed",
    actors: [{ name: "Vince Vaughn" }],
    coverUrl: "/movies/validated/46843-the-break-up-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-02",
    rating: 0,
    length: 106,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Da Vinci Code",
    director: "Ron Howard",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/validated/da_vinci_code.jpg",
    releaseDate: "2006-05-19",
    rating: 0,
    length: 149,
    genre: "Mystery",
    timesWatched: 0,
  },
  {
    title: "Camping",
    director: "Fabien Onteniente",
    actors: [{ name: "Gérard Lanvin" }],
    coverUrl: "/movies/validated/44197-camping-0-150-0-225-crop.jpg",
    releaseDate: "2006-04-26",
    rating: 0,
    length: 111,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "OSS 117 : Le Caire, Nid d'Espions",
    director: "Michel Hazanavicius",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies/validated/42559-oss-117-cairo-nest-of-spies-0-150-0-225-crop.jpg",
    releaseDate: "2006-04-19",
    rating: 0,
    length: 99,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Scary Movie 4",
    director: "David Zucker",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/validated/49433-scary-movie-4-0-150-0-225-crop.jpg",
    releaseDate: "2006-04-14",
    rating: 0,
    length: 83,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "L'Âge de Glace 2",
    director: "Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies/validated/age_de_glace_2.jpg",
    releaseDate: "2006-03-31",
    rating: 0,
    length: 91,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Cars",
    director: "John Lasseter",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies/validated/dWg33ektXuHmxjSjEulwDPTWbC2-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-09",
    rating: 0,
    length: 117,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Volver",
    director: "Pedro Almodóvar",
    actors: [{ name: "Penélope Cruz" }],
    coverUrl: "/movies/validated/51837-volver-0-150-0-225-crop.jpg",
    releaseDate: "2006-03-17",
    rating: 0,
    length: 121,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Destination Finale 3",
    director: "James Wong",
    actors: [{ name: "Mary Elizabeth Winstead" }],
    coverUrl: "/movies/validated/47306-final-destination-3-0-150-0-225-crop.jpg",
    releaseDate: "2006-02-10",
    rating: 0,
    length: 93,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "Incontrôlable",
    director: "Raffy Shart",
    actors: [{ name: "Kad Merad" }],
    coverUrl: "/movies/validated/43655-incontrolable-0-150-0-225-crop.jpg",
    releaseDate: "2006-02-01",
    rating: 0,
    length: 90,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Les Bronzés 3 : Amis pour la Vie",
    director: "Patrice Leconte",
    actors: [{ name: "Josiane Balasko" }],
    coverUrl: "/movies/validated/38412-french-fried-vacation-3-0-150-0-225-crop.jpg",
    releaseDate: "2006-01-25",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Underworld : Évolution",
    director: "Len Wiseman",
    actors: [{ name: "Kate Beckinsale" }],
    coverUrl: "/movies/validated/51318-underworld-evolution-0-150-0-225-crop.jpg",
    releaseDate: "2006-01-20",
    rating: 0,
    length: 106,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "V pour Vendetta",
    director: "James McTeigue",
    actors: [{ name: "Hugo Weaving" }],
    coverUrl: "/movies/validated/51400-v-for-vendetta-0-150-0-225-crop.jpg",
    releaseDate: "2006-03-17",
    rating: 0,
    length: 132,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Le Monde de Narnia : Le Lion, la Sorcière Blanche et l'Armoire Magique",
    director: "Andrew Adamson",
    actors: [{ name: "Georgie Henley" }],
    coverUrl: "/movies/validated/narnia.jpg",
    releaseDate: "2005-12-09",
    rating: 0,
    length: 143,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "King Kong",
    director: "Peter Jackson",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies/validated/king_kong.jpg",
    releaseDate: "2005-12-14",
    rating: 0,
    length: 187,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "Harry Potter et la Coupe de Feu",
    director: "Mike Newell",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/validated/51450-harry-potter-and-the-goblet-of-fire-0-150-0-225-crop.jpg",
    releaseDate: "2005-11-18",
    rating: 0,
    length: 157,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "American Pie Presents: Band Camp",
    director: "Steve Rash",
    actors: [{ name: "Tad Hilgenbrink" }],
    coverUrl: "/movies/validated/american_pie_band_camp.jpg",
    releaseDate: "2005-12-26",
    rating: 0,
    length: 97,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Nanny McPhee",
    director: "Kirk Jones",
    actors: [{ name: "Emma Thompson" }],
    coverUrl: "/movies/validated/45448-nanny-mcphee-0-150-0-225-crop.jpg",
    releaseDate: "2005-10-21",
    rating: 0,
    length: 97,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "Lord of War",
    director: "Andrew Niccol",
    actors: [{ name: "Nicolas Cage" }],
    coverUrl: "/movies/validated/50769-lord-of-war-0-150-0-225-crop.jpg",
    releaseDate: "2005-09-16",
    rating: 0,
    length: 122,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "Orgueil et Préjugés",
    director: "Joe Wright",
    actors: [{ name: "Keira Knightley" }],
    coverUrl: "/movies/validated/orgueil_et_prejuges.jpg",
    releaseDate: "2005-09-16",
    rating: 0,
    length: 129,
    genre: "Romance",
    timesWatched: 0,
  },
  {
    title: "Serenity",
    director: "Joss Whedon",
    actors: [{ name: "Nathan Fillion" }],
    coverUrl: "/movies/validated/serenity-0-150-0-225-crop.jpg",
    releaseDate: "2005-09-30",
    rating: 0,
    length: 119,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "The Protector",
    director: "Prachya Pinkaew",
    actors: [{ name: "Tony Jaa" }],
    coverUrl: "/movies/validated/47454-the-protector-0-150-0-225-crop.jpg",
    releaseDate: "2005-08-11",
    rating: 0,
    length: 110,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "40 Ans, Toujours Puceau",
    director: "Judd Apatow",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies/validated/337567-ocean-s-8-0-150-0-225-crop.jpg",
    releaseDate: "2005-08-19",
    rating: 0,
    length: 116,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Red Eye",
    director: "Wes Craven",
    actors: [{ name: "Rachel McAdams" }],
    coverUrl: "/movies/validated/45282-red-eye-0-150-0-225-crop.jpg",
    releaseDate: "2005-08-19",
    rating: 0,
    length: 85,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Le Transporteur 2",
    director: "Louis Leterrier",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/validated/47259-transporter-2-0-150-0-225-crop.jpg",
    releaseDate: "2005-09-02",
    rating: 0,
    length: 87,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Sky High",
    director: "Mike Mitchell",
    actors: [{ name: "Michael Angarano" }],
    coverUrl: "/movies/validated/45283-sky-high-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-29",
    rating: 0,
    length: 100,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Wedding Crashers",
    director: "David Dobkin",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies/validated/47078-wedding-crashers-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-15",
    rating: 0,
    length: 119,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Charlie et la Chocolaterie",
    director: "Tim Burton",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/validated/51932-charlie-and-the-chocolate-factory-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-15",
    rating: 0,
    length: 115,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "Les 4 Fantastiques",
    director: "Tim Story",
    actors: [{ name: "Ioan Gruffudd" }],
    coverUrl: "/movies/validated/123065-fantastic-four-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-08",
    rating: 0,
    length: 106,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Mr. & Mrs. Smith",
    director: "Doug Liman",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/validated/51365-mr-mrs-smith-0-150-0-225-crop.jpg",
    releaseDate: "2005-06-10",
    rating: 0,
    length: 120,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Batman Begins",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/validated/51784-batman-begins-0-150-0-225-crop.jpg",
    releaseDate: "2005-06-15",
    rating: 0,
    length: 140,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Match Point",
    director: "Woody Allen",
    actors: [{ name: "Jonathan Rhys Meyers" }],
    coverUrl: "/movies/validated/match_point.jpg",
    releaseDate: "2005-05-12",
    rating: 0,
    length: 124,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Star Wars : Épisode III - La Revanche des Sith",
    director: "George Lucas",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies/validated/50709-star-wars-episode-iii-revenge-of-the-sith-0-150-0-225-crop.jpg",
    releaseDate: "2005-05-19",
    rating: 0,
    length: 140,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "xXx² : The Next Level",
    director: "Lee Tamahori",
    actors: [{ name: "Ice Cube" }],
    coverUrl: "/movies/validated/45074-xxx-state-of-the-union-0-150-0-225-crop.jpg",
    releaseDate: "2005-04-29",
    rating: 0,
    length: 101,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Sin City",
    director: "Frank Miller, Robert Rodriguez",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/validated/51865-sin-city-0-150-0-225-crop.jpg",
    releaseDate: "2005-04-01",
    rating: 0,
    length: 124,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "The Descent",
    director: "Neil Marshall",
    actors: [{ name: "Shauna Macdonald" }],
    coverUrl: "/movies/validated/47204-the-descent-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-08",
    rating: 0,
    length: 99,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "The Pacifier",
    director: "Adam Shankman",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/validated/46620-the-pacifier-0-150-0-225-crop.jpg",
    releaseDate: "2005-03-04",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Hitch : Expert en Séduction",
    director: "Andy Tennant",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/validated/47699-hitch-0-150-0-225-crop.jpg",
    releaseDate: "2005-02-11",
    rating: 0,
    length: 118,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Ocean's Twelve",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/validated/51888-ocean-s-twelve-0-150-0-225-crop.jpg",
    releaseDate: "2004-12-10",
    rating: 0,
    length: 125,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "Blade : Trinity",
    director: "David S. Goyer",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies/validated/blade_trinity.jpg",
    releaseDate: "2004-12-08",
    rating: 0,
    length: 113,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Million Dollar Baby",
    director: "Clint Eastwood",
    actors: [{ name: "Hilary Swank" }],
    coverUrl: "/movies/validated/51979-million-dollar-baby-0-150-0-225-crop.jpg",
    releaseDate: "2004-12-15",
    rating: 0,
    length: 132,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Banlieue 13",
    director: "Pierre Morel",
    actors: [{ name: "David Belle" }],
    coverUrl: "/movies/validated/46599-district-13-0-150-0-225-crop.jpg",
    releaseDate: "2004-11-10",
    rating: 0,
    length: 84,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Les Indestructibles",
    director: "Brad Bird",
    actors: [{ name: "Craig T. Nelson" }],
    coverUrl: "/movies/validated/46806-the-incredibles-0-150-0-225-crop.jpg",
    releaseDate: "2004-11-05",
    rating: 0,
    length: 115,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "First Daughter",
    director: "Forest Whitaker",
    actors: [{ name: "Katie Holmes" }],
    coverUrl: "/movies/validated/43443-first-daughter-0-150-0-225-crop.jpg",
    releaseDate: "2004-09-24",
    rating: 0,
    length: 106,
    genre: "Romance",
    timesWatched: 0,
  },
  {
    title: "Resident Evil : Apocalypse",
    director: "Alexander Witt",
    actors: [{ name: "Milla Jovovich" }],
    coverUrl: "/movies/validated/50957-resident-evil-apocalypse-0-150-0-225-crop.jpg",
    releaseDate: "2004-09-10",
    rating: 0,
    length: 94,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Alien vs. Predator",
    director: "Paul W.S. Anderson",
    actors: [{ name: "Sanaa Lathan" }],
    coverUrl: "/movies/validated/51695-avp-alien-vs-predator-0-150-0-225-crop.jpg",
    releaseDate: "2004-08-13",
    rating: 0,
    length: 101,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Catwoman",
    director: "Pitof",
    actors: [{ name: "Halle Berry" }],
    coverUrl: "/movies/validated/51745-catwoman-0-150-0-225-crop.jpg",
    releaseDate: "2004-07-23",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "La Mort dans la Peau",
    director: "Paul Greengrass",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/validated/50224-the-bourne-supremacy-0-150-0-225-crop.jpg",
    releaseDate: "2004-07-23",
    rating: 0,
    length: 108,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Spider-Man 2",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies/validated/amazin_spiderman_2.jpg",
    releaseDate: "2004-06-30",
    rating: 0,
    length: 127,
    genre: "Action",
    timesWatched: 0,
  },


];