import { Movie } from "./movies_1";

export const moviesPage7: Movie[] = [

  {
    title: "Nuit au Musée",
    director: "Shawn Levy",
    actors: [{ name: "Ben Stiller" }],
    coverUrl: "/movies_pictures/validated/50941-night-at-the-museum-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-22",
    rating: 0,
    length: 108,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "À la Recherche du Bonheur",
    director: "Gabriele Muccino",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/validated/51061-the-pursuit-of-happyness-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-15",
    rating: 0,
    length: 117,
    genre: "Drama",
    timesWatched: 3,
  },
  {
    title: "Hors de Prix",
    director: "Pierre Salvadori",
    actors: [{ name: "Audrey Tautou" }],
    coverUrl: "/movies_pictures/validated/48206-priceless-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-27",
    rating: 0,
    length: 104,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "300",
    director: "Zack Snyder",
    actors: [{ name: "Gerard Butler" }],
    coverUrl: "/movies_pictures/validated/51111-300-0-150-0-225-crop.jpg",
    releaseDate: "2007-03-09",
    rating: 0,
    length: 117,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Blood Diamond",
    director: "Edward Zwick",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies_pictures/validated/51084-blood-diamond-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-08",
    rating: 0,
    length: 143,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "American Pie Presents: The Naked Mile",
    director: "Joe Nussbaum",
    actors: [{ name: "John White" }],
    coverUrl: "/movies_pictures/validated/47831-american-pie-presents-the-naked-mile-0-150-0-225-crop.jpg",
    releaseDate: "2006-12-19",
    rating: 0,
    length: 97,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "Casino Royale",
    director: "Martin Campbell",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies_pictures/validated/casino_royal.jpg",
    releaseDate: "2006-11-17",
    rating: 0,
    length: 144,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Le Prestige",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies_pictures/validated/51147-the-prestige-0-150-0-225-crop.jpg",
    releaseDate: "2006-10-20",
    rating: 0,
    length: 130,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Les Infiltrés",
    director: "Martin Scorsese",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies_pictures/validated/les_infiltres.jpg",
    releaseDate: "2006-10-06",
    rating: 0,
    length: 151,
    genre: "Crime",
    timesWatched: 2,
  },
  {
    title: "Admis à tout prix",
    director: "Steve Pink",
    actors: [{ name: "Justin Long" }],
    coverUrl: "/movies_pictures/validated/46823-accepted-0-150-0-225-crop.jpg",
    releaseDate: "2006-08-18",
    rating: 0,
    length: 93,
    genre: "Comedy",
    timesWatched: 15,
  },
  {
    title: "Nos Jours heureux",
    director: "Claude Zidi Jr.",
    actors: [{ name: "Vincent Claude" }],
    coverUrl: "/movies_pictures/validated/39863-those-happy-days-0-150-0-225-crop.jpg",
    releaseDate: "2006-07-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 30,
  },
  {
    title: "Pirates des Caraïbes : Le Secret du Coffre Maudit",
    director: "Gore Verbinski",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies_pictures/validated/51989-pirates-of-the-caribbean-dead-man-s-chest-0-150-0-225-crop.jpg",
    releaseDate: "2006-07-07",
    rating: 0,
    length: 151,
    genre: "Adventure",
    timesWatched: 10,
  },
  {
    title: "Le Diable s'Habille en Prada",
    director: "David Frankel",
    actors: [{ name: "Anne Hathaway" }],
    coverUrl: "/movies_pictures/validated/51712-the-devil-wears-prada-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-30",
    rating: 0,
    length: 109,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Babel",
    director: "Alejandro González Iñárritu",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies_pictures/validated/51140-babel-0-150-0-225-crop.jpg",
    releaseDate: "2006-11-10",
    rating: 0,
    length: 143,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "De l'autre côté du lit",
    director: "Peyton Reed",
    actors: [{ name: "Vince Vaughn" }],
    coverUrl: "/movies_pictures/validated/46843-the-break-up-0-150-0-225-crop.jpg",
    releaseDate: "2006-06-02",
    rating: 0,
    length: 106,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Da Vinci Code",
    director: "Ron Howard",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies_pictures/validated/da_vinci_code.jpg",
    releaseDate: "2006-05-19",
    rating: 0,
    length: 149,
    genre: "Mystery",
    timesWatched: 1,
  },
  {
    title: "Camping",
    director: "Fabien Onteniente",
    actors: [{ name: "Gérard Lanvin" }],
    coverUrl: "/movies_pictures/validated/44197-camping-0-150-0-225-crop.jpg",
    releaseDate: "2006-04-26",
    rating: 0,
    length: 111,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "OSS 117 : Le Caire, Nid d'Espions",
    director: "Michel Hazanavicius",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies_pictures/validated/42559-oss-117-cairo-nest-of-spies-0-150-0-225-crop.jpg",
    releaseDate: "2006-04-19",
    rating: 0,
    length: 99,
    genre: "Comedy",
    timesWatched: 30,
  },
  {
    title: "Scary Movie 4",
    director: "David Zucker",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies_pictures/validated/49433-scary-movie-4-0-150-0-225-crop.jpg",
    releaseDate: "2006-04-14",
    rating: 0,
    length: 83,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "Volver",
    director: "Pedro Almodóvar",
    actors: [{ name: "Penélope Cruz" }],
    coverUrl: "/movies_pictures/validated/51837-volver-0-150-0-225-crop.jpg",
    releaseDate: "2006-03-17",
    rating: 0,
    length: 121,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Destination Finale 3",
    director: "James Wong",
    actors: [{ name: "Mary Elizabeth Winstead" }],
    coverUrl: "/movies_pictures/validated/47306-final-destination-3-0-150-0-225-crop.jpg",
    releaseDate: "2006-02-10",
    rating: 0,
    length: 93,
    genre: "Horror",
    timesWatched: 10,
  },
  {
    title: "Incontrôlable",
    director: "Raffy Shart",
    actors: [{ name: "Kad Merad" }],
    coverUrl: "/movies_pictures/validated/43655-incontrolable-0-150-0-225-crop.jpg",
    releaseDate: "2006-02-01",
    rating: 0,
    length: 90,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Les Bronzés 3 : Amis pour la Vie",
    director: "Patrice Leconte",
    actors: [{ name: "Josiane Balasko" }],
    coverUrl: "/movies_pictures/validated/38412-french-fried-vacation-3-0-150-0-225-crop.jpg",
    releaseDate: "2006-01-25",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 3,
  },
  {
    title: "Underworld : Évolution",
    director: "Len Wiseman",
    actors: [{ name: "Kate Beckinsale" }],
    coverUrl: "/movies_pictures/validated/51318-underworld-evolution-0-150-0-225-crop.jpg",
    releaseDate: "2006-01-20",
    rating: 0,
    length: 106,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "V pour Vendetta",
    director: "James McTeigue",
    actors: [{ name: "Hugo Weaving" }],
    coverUrl: "/movies_pictures/validated/51400-v-for-vendetta-0-150-0-225-crop.jpg",
    releaseDate: "2006-03-17",
    rating: 0,
    length: 132,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Le Monde de Narnia : Le Lion, la Sorcière Blanche et l'Armoire Magique",
    director: "Andrew Adamson",
    actors: [{ name: "Georgie Henley" }],
    coverUrl: "/movies_pictures/validated/narnia.jpg",
    releaseDate: "2005-12-09",
    rating: 0,
    length: 143,
    genre: "Fantasy",
    timesWatched: 1,
  },
  {
    title: "King Kong",
    director: "Peter Jackson",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies_pictures/validated/king_kong.jpg",
    releaseDate: "2005-12-14",
    rating: 0,
    length: 187,
    genre: "Adventure",
    timesWatched: 10,
  },
  {
    title: "American Pie Presents: Band Camp",
    director: "Steve Rash",
    actors: [{ name: "Tad Hilgenbrink" }],
    coverUrl: "/movies_pictures/validated/american_pie_band_camp.jpg",
    releaseDate: "2005-12-26",
    rating: 0,
    length: 97,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Nanny McPhee",
    director: "Kirk Jones",
    actors: [{ name: "Emma Thompson" }],
    coverUrl: "/movies_pictures/validated/45448-nanny-mcphee-0-150-0-225-crop.jpg",
    releaseDate: "2005-10-21",
    rating: 0,
    length: 97,
    genre: "Fantasy",
    timesWatched: 1,
  },
  {
    title: "Lord of War",
    director: "Andrew Niccol",
    actors: [{ name: "Nicolas Cage" }],
    coverUrl: "/movies_pictures/validated/50769-lord-of-war-0-150-0-225-crop.jpg",
    releaseDate: "2005-09-16",
    rating: 0,
    length: 122,
    genre: "Crime",
    timesWatched: 2,
  },
  {
    title: "Serenity",
    director: "Joss Whedon",
    actors: [{ name: "Nathan Fillion" }],
    coverUrl: "/movies_pictures/validated/serenity-0-150-0-225-crop.jpg",
    releaseDate: "2005-09-30",
    rating: 0,
    length: 119,
    genre: "Science Fiction",
    timesWatched: 1,
  },
  {
    title: "L'honneur du dragon",
    director: "Prachya Pinkaew",
    actors: [{ name: "Tony Jaa" }],
    coverUrl: "/movies_pictures/validated/47454-the-protector-0-150-0-225-crop.jpg",
    releaseDate: "2005-08-11",
    rating: 0,
    length: 110,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "40 Ans, Toujours Puceau",
    director: "Judd Apatow",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies_pictures/validated/48160-the-40-year-old-virgin-0-150-0-225-crop.jpg",
    releaseDate: "2005-08-19",
    rating: 0,
    length: 116,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Sous haute pression",
    director: "Wes Craven",
    actors: [{ name: "Rachel McAdams" }],
    coverUrl: "/movies_pictures/validated/45282-red-eye-0-150-0-225-crop.jpg",
    releaseDate: "2005-08-19",
    rating: 0,
    length: 85,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Le Transporteur 2",
    director: "Louis Leterrier",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies_pictures/validated/47259-transporter-2-0-150-0-225-crop.jpg",
    releaseDate: "2005-09-02",
    rating: 0,
    length: 87,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Serial Nocers",
    director: "David Dobkin",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies_pictures/validated/47078-wedding-crashers-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-15",
    rating: 0,
    length: 119,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Charlie et la Chocolaterie",
    director: "Tim Burton",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies_pictures/validated/51932-charlie-and-the-chocolate-factory-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-15",
    rating: 0,
    length: 115,
    genre: "Fantasy",
    timesWatched: 10,
  },
  {
    title: "Mr. & Mrs. Smith",
    director: "Doug Liman",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies_pictures/validated/51365-mr-mrs-smith-0-150-0-225-crop.jpg",
    releaseDate: "2005-06-10",
    rating: 0,
    length: 120,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "xXx² : The Next Level",
    director: "Lee Tamahori",
    actors: [{ name: "Ice Cube" }],
    coverUrl: "/movies_pictures/validated/45074-xxx-state-of-the-union-0-150-0-225-crop.jpg",
    releaseDate: "2005-04-29",
    rating: 0,
    length: 101,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Sin City",
    director: "Frank Miller, Robert Rodriguez",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/validated/51865-sin-city-0-150-0-225-crop.jpg",
    releaseDate: "2005-04-01",
    rating: 0,
    length: 124,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "The Descent",
    director: "Neil Marshall",
    actors: [{ name: "Shauna Macdonald" }],
    coverUrl: "/movies_pictures/validated/47204-the-descent-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-08",
    rating: 0,
    length: 99,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Baby Sittor",
    director: "Adam Shankman",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies_pictures/validated/46620-the-pacifier-0-150-0-225-crop.jpg",
    releaseDate: "2005-03-04",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Ocean's Twelve",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies_pictures/validated/51888-ocean-s-twelve-0-150-0-225-crop.jpg",
    releaseDate: "2004-12-10",
    rating: 0,
    length: 125,
    genre: "Crime",
    timesWatched: 5,
  },
  {
    title: "Blade : Trinity",
    director: "David S. Goyer",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies_pictures/validated/blade_trinity.jpg",
    releaseDate: "2004-12-08",
    rating: 0,
    length: 113,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Million Dollar Baby",
    director: "Clint Eastwood",
    actors: [{ name: "Hilary Swank" }],
    coverUrl: "/movies_pictures/validated/51979-million-dollar-baby-0-150-0-225-crop.jpg",
    releaseDate: "2004-12-15",
    rating: 0,
    length: 132,
    genre: "Drama",
    timesWatched: 2,
  },
  {
    title: "Banlieue 13",
    director: "Pierre Morel",
    actors: [{ name: "David Belle" }],
    coverUrl: "/movies_pictures/validated/46599-district-13-0-150-0-225-crop.jpg",
    releaseDate: "2004-11-10",
    rating: 0,
    length: 84,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Resident Evil : Apocalypse",
    director: "Alexander Witt",
    actors: [{ name: "Milla Jovovich" }],
    coverUrl: "/movies_pictures/validated/50957-resident-evil-apocalypse-0-150-0-225-crop.jpg",
    releaseDate: "2004-09-10",
    rating: 0,
    length: 94,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Alien vs. Predator",
    director: "Paul W.S. Anderson",
    actors: [{ name: "Sanaa Lathan" }],
    coverUrl: "/movies_pictures/validated/51695-avp-alien-vs-predator-0-150-0-225-crop.jpg",
    releaseDate: "2004-08-13",
    rating: 0,
    length: 101,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "La Mort dans la Peau",
    director: "Paul Greengrass",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies_pictures/validated/50224-the-bourne-supremacy-0-150-0-225-crop.jpg",
    releaseDate: "2004-07-23",
    rating: 0,
    length: 108,
    genre: "Action",
    timesWatched: 10,
  },
];