import { Movie } from "./movies_1";

export const moviesPage10: Movie[] = [
  {
    title: "Independence Day : Resurgence",
    director: "Roland Emmerich",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/validated/507660-independence-day-the-id4-invasion-0-150-0-225-crop.jpg",
    releaseDate: "1996-07-03",
    rating: 0,
    length: 145,
    genre: "Science Fiction",
    timesWatched: 1,
  },
  {
    title: "Independence Day",
    director: "Roland Emmerich",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/validated/bqLlWZJdhrS0knfEJRkquW7L8z2-0-150-0-225-crop.jpg",
    releaseDate: "1996-07-03",
    rating: 0,
    length: 145,
    genre: "Science Fiction",
    timesWatched: 10,
  },
  {
    title: "Eraser",
    director: "Chuck Russell",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/47324-eraser-0-150-0-225-crop.jpg",
    releaseDate: "1996-06-21",
    rating: 0,
    length: 115,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "The Quest",
    director: "Jean-Claude Van Damme",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies_pictures/validated/47342-the-quest-0-150-0-225-crop.jpg",
    releaseDate: "1996-04-26",
    rating: 0,
    length: 95,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Trainspotting",
    director: "Danny Boyle",
    actors: [{ name: "Ewan McGregor" }],
    coverUrl: "/movies_pictures/validated/51497-trainspotting-0-150-0-225-crop.jpg",
    releaseDate: "1996-02-23",
    rating: 0,
    length: 93,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Jumanji",
    director: "Joe Johnston",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies_pictures/validated/jumanji.jpg",
    releaseDate: "1995-12-15",
    rating: 0,
    length: 104,
    genre: "Adventure",
    timesWatched: 3,
  },
  {
    title: "Seven",
    director: "David Fincher",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies_pictures/validated/51345-se7en-0-150-0-225-crop.jpg",
    releaseDate: "1995-09-22",
    rating: 0,
    length: 127,
    genre: "Crime",
    timesWatched: 3,
  },
  {
    title: "The Net",
    director: "Irwin Winkler",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies_pictures/validated/50900-the-net-0-150-0-225-crop.jpg",
    releaseDate: "1995-07-28",
    rating: 0,
    length: 114,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Waterworld",
    director: "Kevin Reynolds",
    actors: [{ name: "Kevin Costner" }],
    coverUrl: "/movies_pictures/validated/waterworld.jpg",
    releaseDate: "1995-07-28",
    rating: 0,
    length: 135,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Piège à grande vitesse",
    director: "Geoff Murphy",
    actors: [{ name: "Steven Seagal" }],
    coverUrl: "/movies_pictures/validated/49707-under-siege-2-dark-territory-0-150-0-225-crop.jpg",
    releaseDate: "1995-07-14",
    rating: 0,
    length: 100,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Judge Dredd",
    director: "Danny Cannon",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/judge_dredd.jpg",
    releaseDate: "1995-06-30",
    rating: 0,
    length: 96,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Die Hard 3 : une journée en enfer",
    director: "John McTiernan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/validated/50962-die-hard-with-a-vengeance-0-150-0-225-crop.jpg",
    releaseDate: "1995-05-19",
    rating: 0,
    length: 128,
    genre: "Action",
    timesWatched: 30,
  },
  {
    title: "Bad Boys",
    director: "Michael Bay",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/validated/46870-bad-boys-0-150-0-225-crop.jpg",
    releaseDate: "1995-04-07",
    rating: 0,
    length: 119,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "The Usual Suspects",
    director: "Bryan Singer",
    actors: [{ name: "Kevin Spacey" }],
    coverUrl: "/movies_pictures/validated/51495-the-usual-suspects-0-150-0-225-crop.jpg",
    releaseDate: "1995-08-16",
    rating: 0,
    length: 106,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Street Fighter",
    director: "Steven E. de Souza",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies_pictures/validated/45086-street-fighter-0-150-0-225-crop.jpg",
    releaseDate: "1994-12-23",
    rating: 0,
    length: 102,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Un indien dans la ville",
    director: "Hervé Palud",
    actors: [{ name: "Thierry Lhermitte" }],
    coverUrl: "/movies_pictures/validated/45265-little-indian-big-city-0-150-0-225-crop.jpg",
    releaseDate: "1994-12-14",
    rating: 0,
    length: 85,
    genre: "Comedy",
    timesWatched: 15,
  },
  {
    title: "Dumb & Dumber",
    director: "Peter Farrelly, Bobby Farrelly",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies_pictures/validated/st4P2TtPrAfNwu8HLXoPsPPii42-0-150-0-225-crop.jpg",
    releaseDate: "1994-12-16",
    rating: 0,
    length: 107,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Leon",
    director: "Luc Besson",
    actors: [{ name: "Jean Reno" }],
    coverUrl: "/movies_pictures/validated/leon.jpg",
    releaseDate: "1994-11-18",
    rating: 0,
    length: 110,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "The Mask",
    director: "Chuck Russell",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies_pictures/validated/51298-the-mask-0-150-0-225-crop.jpg",
    releaseDate: "1994-07-29",
    rating: 0,
    length: 101,
    genre: "Comedy",
    timesWatched: 20,
  },
  {
    title: "True Lies",
    director: "James Cameron",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/true_lies.jpg",
    releaseDate: "1994-07-15",
    rating: 0,
    length: 141,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies_pictures/validated/2704-forrest-gump-0-150-0-225-crop.jpg",
    releaseDate: "1994-07-06",
    rating: 0,
    length: 142,
    genre: "Drama",
    timesWatched: 10,
  },
  {
    title: "Speed",
    director: "Jan de Bont",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies_pictures/validated/50904-speed-0-150-0-225-crop.jpg",
    releaseDate: "1994-06-10",
    rating: 0,
    length: 116,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    actors: [{ name: "John Travolta" }],
    coverUrl: "/movies_pictures/validated/51444-pulp-fiction-0-150-0-225-crop.jpg",
    releaseDate: "1994-10-14",
    rating: 0,
    length: 154,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "La cité de la peur",
    director: "Alain Berbérian",
    actors: [{ name: "Patrick Timsit" }],
    coverUrl: "/movies_pictures/validated/42599-fear-city-a-family-style-comedy-0-150-0-225-crop.jpg",
    releaseDate: "1994-03-16",
    rating: 0,
    length: 85,
    genre: "Comedy",
    timesWatched: 2,
  },
  {
    title: "Mrs. Doubtfire",
    director: "Chris Columbus",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies_pictures/validated/51364-mrs-doubtfire-0-150-0-225-crop.jpg",
    releaseDate: "1993-11-24",
    rating: 0,
    length: 125,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Demolition Man",
    director: "Marco Brambilla",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/46868-demolition-man-0-150-0-225-crop.jpg",
    releaseDate: "1993-10-08",
    rating: 0,
    length: 115,
    genre: "Action",
    timesWatched: 30,
  },
  {
    title: "Le fugitif",
    director: "Andrew Davis",
    actors: [{ name: "Harrison Ford" }],
    coverUrl: "/movies_pictures/validated/48823-the-fugitive-0-150-0-225-crop.jpg",
    releaseDate: "1993-08-06",
    rating: 0,
    length: 130,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Last Action Hero",
    director: "John McTiernan",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/47008-last-action-hero-0-150-0-225-crop.jpg",
    releaseDate: "1993-06-18",
    rating: 0,
    length: 130,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Jurassic Park",
    director: "Steven Spielberg",
    actors: [{ name: "Sam Neill" }],
    coverUrl: "/movies_pictures/validated/jurassic_park.jpg",
    releaseDate: "1993-06-11",
    rating: 0,
    length: 127,
    genre: "Adventure",
    timesWatched: 5,
  },
  {
    title: "Cliffhanger",
    director: "Renny Harlin",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/47244-cliffhanger-0-150-0-225-crop.jpg",
    releaseDate: "1993-05-28",
    rating: 0,
    length: 113,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Les visiteurs",
    director: "Jean-Marie Poiré",
    actors: [{ name: "Jean Reno" }],
    coverUrl: "/movies_pictures/validated/45066-the-visitors-0-150-0-225-crop.jpg",
    releaseDate: "1993-01-27",
    rating: 0,
    length: 107,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Maman j'ai raté l'avion 2",
    director: "Chris Columbus",
    actors: [{ name: "Macaulay Culkin" }],
    coverUrl: "/movies_pictures/validated/home%20alone%202-0-150-0-225-crop.jpg",
    releaseDate: "1992-11-20",
    rating: 0,
    length: 120,
    genre: "Comedy",
    timesWatched: 3,
  },
  {
    title: "Piège en haute mer",
    director: "Andrew Davis",
    actors: [{ name: "Steven Seagal" }],
    coverUrl: "/movies_pictures/validated/47576-under-siege-0-150-0-225-crop.jpg",
    releaseDate: "1992-10-09",
    rating: 0,
    length: 103,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Alien 3",
    director: "David Fincher",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies_pictures/validated/47888-alien-0-150-0-225-crop.jpg",
    releaseDate: "1992-05-22",
    rating: 0,
    length: 114,
    genre: "Science Fiction",
    timesWatched: 3,
  },
  {
    title: "L'arme fatale 3",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies_pictures/validated/arme_fatale_3.jpg",
    releaseDate: "1992-05-15",
    rating: 0,
    length: 118,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Basic Instinct",
    director: "Paul Verhoeven",
    actors: [{ name: "Michael Douglas" }],
    coverUrl: "/movies_pictures/validated/basic_instinct.jpg",
    releaseDate: "1992-03-20",
    rating: 0,
    length: 128,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Reservoir Dogs",
    director: "Quentin Tarantino",
    actors: [{ name: "Harvey Keitel" }],
    coverUrl: "/movies_pictures/validated/reservoir_dogs.jpg",
    releaseDate: "1992-10-23",
    rating: 0,
    length: 99,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Le dernier samaritain",
    director: "Tony Scott",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/validated/le_dernier_samaritain.jpg",
    releaseDate: "1991-12-13",
    rating: 0,
    length: 105,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Double Impact",
    director: "Sheldon Lettich",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies_pictures/validated/47007-double-impact-0-150-0-225-crop.jpg",
    releaseDate: "1991-08-09",
    rating: 0,
    length: 110,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Point Break",
    director: "Kathryn Bigelow",
    actors: [{ name: "Patrick Swayze" }],
    coverUrl: "/movies_pictures/validated/51157-point-break-0-150-0-225-crop.jpg",
    releaseDate: "1991-07-12",
    rating: 0,
    length: 122,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Predator 2",
    director: "Stephen Hopkins",
    actors: [{ name: "Danny Glover" }],
    coverUrl: "/movies_pictures/validated/predator_2.jpg",
    releaseDate: "1990-11-21",
    rating: 0,
    length: 108,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Maman j'ai raté l'avion",
    director: "Chris Columbus",
    actors: [{ name: "Macaulay Culkin" }],
    coverUrl: "/movies_pictures/validated/home_alone.jpg",
    releaseDate: "1990-11-16",
    rating: 0,
    length: 103,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Les Affranchis",
    director: "Martin Scorsese",
    actors: [{ name: "Robert De Niro" }],
    coverUrl: "/movies_pictures/validated/51383-goodfellas-0-150-0-225-crop.jpg",
    releaseDate: "1990-09-19",
    rating: 0,
    length: 146,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Die Hard 2 : 58 minutes pour vivre",
    director: "Renny Harlin",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/validated/die_hard_2.jpg",
    releaseDate: "1990-07-04",
    rating: 0,
    length: 124,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Total Recall",
    director: "Paul Verhoeven",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/51291-total-recall-0-150-0-225-crop.jpg",
    releaseDate: "1990-06-01",
    rating: 0,
    length: 113,
    genre: "Science Fiction",
    timesWatched: 2,
  },
  {
    title: "Retour vers le futur 3",
    director: "Robert Zemeckis",
    actors: [{ name: "Michael J. Fox" }],
    coverUrl: "/movies_pictures/validated/51856-back-to-the-future-part-iii-0-150-0-225-crop.jpg",
    releaseDate: "1990-05-25",
    rating: 0,
    length: 118,
    genre: "Science Fiction",
    timesWatched: 20,
  },
  {
    title: "Nikita",
    director: "Luc Besson",
    actors: [{ name: "Anne Parillaud" }],
    coverUrl: "/movies_pictures/validated/47271-la-femme-nikita-0-150-0-225-crop.jpg",
    releaseDate: "1990-02-21",
    rating: 0,
    length: 117,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Tango & Cash",
    director: "Andrei Konchalovsky",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/tango_et_cash.jpg",
    releaseDate: "1989-12-22",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Retour vers le futur 2",
    director: "Robert Zemeckis",
    actors: [{ name: "Michael J. Fox" }],
    coverUrl: "/movies_pictures/validated/51886-back-to-the-future-part-ii-0-150-0-225-crop.jpg",
    releaseDate: "1989-11-22",
    rating: 0,
    length: 108,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "L'arme fatale 2",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies_pictures/validated/51211-lethal-weapon-2-0-150-0-225-crop.jpg",
    releaseDate: "1989-07-07",
    rating: 0,
    length: 114,
    genre: "Action",
    timesWatched: 5,
  }, {
    title: "Le cercle des poètes disparus",
    director: "Peter Weir",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies_pictures/validated/51846-dead-poets-society-0-150-0-225-crop.jpg",
    releaseDate: "1989-06-09",
    rating: 0,
    length: 128,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Kickboxer",
    director: "Mark DiSalle, David Worth",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies_pictures/validated/46429-kickboxer-0-150-0-225-crop.jpg",
    releaseDate: "1989-04-20",
    rating: 0,
    length: 97,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Die Hard : Piège de cristal",
    director: "John McTiernan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/validated/51556-die-hard-0-150-0-225-crop.jpg",
    releaseDate: "1988-07-15",
    rating: 0,
    length: 132,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Qui veut la peau de Roger Rabbit",
    director: "Robert Zemeckis",
    actors: [{ name: "Bob Hoskins" }],
    coverUrl: "/movies_pictures/validated/51296-who-framed-roger-rabbit-0-150-0-225-crop.jpg",
    releaseDate: "1988-06-22",
    rating: 0,
    length: 104,
    genre: "Animation",
    timesWatched: 10,
  },
  {
    title: "Rambo 3",
    director: "Peter MacDonald",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/validated/51086-rambo-iii-0-150-0-225-crop.jpg",
    releaseDate: "1988-05-25",
    rating: 0,
    length: 102,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Bloodsport",
    director: "Newt Arnold",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies_pictures/validated/bloodsport.jpg",
    releaseDate: "1988-02-26",
    rating: 0,
    length: 92,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Good Morning, Vietnam",
    director: "Barry Levinson",
    actors: [{ name: "Robin Williams" }],
    coverUrl: "/movies_pictures/validated/good_morning_vietnam.jpg",
    releaseDate: "1987-12-23",
    rating: 0,
    length: 121,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "The Running Man",
    director: "Paul Michael Glaser",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/validated/51287-the-running-man-0-150-0-225-crop.jpg",
    releaseDate: "1987-11-13",
    rating: 0,
    length: 101,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "RoboCop",
    director: "Paul Verhoeven",
    actors: [{ name: "Peter Weller" }],
    coverUrl: "/movies_pictures/validated/robocop-0-150-0-225-crop.jpg",
    releaseDate: "1987-07-17",
    rating: 0,
    length: 102,
    genre: "Action",
    timesWatched: 3,
  },
];