import { Movie } from "./movies_1";

export const moviesPage9: Movie[] = [
  {
    title: "Ocean's Eleven",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/validated/oceans_eleven.jpg",
    releaseDate: "2001-12-07",
    rating: 0,
    length: 116,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "Tanguy",
    director: "Étienne Chatiliez",
    actors: [{ name: "Éric Berger" }],
    coverUrl: "/movies/validated/50585-tanguy-0-150-0-225-crop.jpg",
    releaseDate: "2001-12-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Harry Potter à l'École des Sorciers",
    director: "Chris Columbus",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/validated/harry_potter_ecole_des_sorciers.jpg",
    releaseDate: "2001-11-16",
    rating: 0,
    length: 152,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "The One",
    director: "James Wong",
    actors: [{ name: "Jet Li" }],
    coverUrl: "/movies/validated/45888-the-one-0-150-0-225-crop.jpg",
    releaseDate: "2001-11-02",
    rating: 0,
    length: 87,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Wasabi",
    director: "Gérard Krawczyk",
    actors: [{ name: "Jean Reno" }],
    coverUrl: "/movies/validated/50516-wasabi-0-150-0-225-crop.jpg",
    releaseDate: "2001-10-31",
    rating: 0,
    length: 94,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Monstres et Cie",
    director: "Pete Docter",
    actors: [{ name: "John Goodman" }],
    coverUrl: "/movies/validated/monstres_et_compagnie.jpg",
    releaseDate: "2001-11-02",
    rating: 0,
    length: 92,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Training Day",
    director: "Antoine Fuqua",
    actors: [{ name: "Denzel Washington" }],
    coverUrl: "/movies/validated/50580-training-day-0-150-0-225-crop.jpg",
    releaseDate: "2001-10-05",
    rating: 0,
    length: 122,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "American Pie 2",
    director: "J.B. Rogers",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies/validated/50101-american-pie-2-0-150-0-225-crop.jpg",
    releaseDate: "2001-08-10",
    rating: 0,
    length: 108,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Rush Hour 2",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies/validated/48919-rush-hour-2-0-150-0-225-crop.jpg",
    releaseDate: "2001-08-03",
    rating: 0,
    length: 90,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Shaolin Soccer",
    director: "Stephen Chow",
    actors: [{ name: "Stephen Chow" }],
    coverUrl: "/movies/validated/45025-shaolin-soccer-0-150-0-225-crop.jpg",
    releaseDate: "2001-07-12",
    rating: 0,
    length: 87,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Scary Movie 2",
    director: "Keenen Ivory Wayans",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/validated/49442-scary-movie-2-0-150-0-225-crop.jpg",
    releaseDate: "2001-07-04",
    rating: 0,
    length: 83,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Fast and Furious",
    director: "Rob Cohen",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/validated/46813-the-fast-and-the-furious-0-150-0-225-crop.jpg",
    releaseDate: "2001-06-22",
    rating: 0,
    length: 106,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Lara Croft : Tomb Raider",
    director: "Simon West",
    actors: [{ name: "Angelina Jolie" }],
    coverUrl: "/movies/validated/50617-lara-croft-tomb-raider-0-150-0-225-crop.jpg",
    releaseDate: "2001-06-15",
    rating: 0,
    length: 100,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Pearl Harbor",
    director: "Michael Bay",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies/validated/51448-pearl-harbor-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-25",
    rating: 0,
    length: 183,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Mulholland Drive",
    director: "David Lynch",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies/validated/mulholland_drive.jpg",
    releaseDate: "2001-10-12",
    rating: 0,
    length: 147,
    genre: "Mystery",
    timesWatched: 0,
  },
  {
    title: "Replicant",
    director: "Ringo Lam",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies/validated/46077-replicant-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-04",
    rating: 0,
    length: 100,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Le Retour de la Momie",
    director: "Stephen Sommers",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies/validated/50818-the-mummy-returns-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-04",
    rating: 0,
    length: 130,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "Shrek",
    director: "Andrew Adamson, Vicky Jenson",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies/validated/51344-shrek-0-150-0-225-crop.jpg",
    releaseDate: "2001-05-18",
    rating: 0,
    length: 90,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Spy Kids",
    director: "Robert Rodriguez",
    actors: [{ name: "Alexa Vega" }],
    coverUrl: "/movies/validated/spy_kids.jpg",
    releaseDate: "2001-03-30",
    rating: 0,
    length: 88,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "Battle Royale",
    director: "Kinji Fukasaku",
    actors: [{ name: "Tatsuya Fujiwara" }],
    coverUrl: "/movies/validated/49810-battle-royale-0-150-0-225-crop.jpg",
    releaseDate: "2000-12-16",
    rating: 0,
    length: 114,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Miss Détective",
    director: "Donald Petrie",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/validated/51006-miss-congeniality-0-150-0-225-crop.jpg",
    releaseDate: "2000-12-22",
    rating: 0,
    length: 111,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Ce que Veulent les Femmes",
    director: "Nancy Meyers",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies/validated/49539-what-women-want-0-150-0-225-crop.jpg",
    releaseDate: "2000-12-15",
    rating: 0,
    length: 127,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Incassable",
    director: "M. Night Shyamalan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/validated/46866-unbreakable-0-150-0-225-crop.jpg",
    releaseDate: "2000-11-22",
    rating: 0,
    length: 106,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Le 6ème Jour",
    director: "Roger Spottiswoode",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/validated/a_l_aube_du_sixieme_jour.jpg",
    releaseDate: "2000-11-17",
    rating: 0,
    length: 123,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Memento",
    director: "Christopher Nolan",
    actors: [{ name: "Guy Pearce" }],
    coverUrl: "/movies/validated/memento-0-150-0-225-crop.jpg",
    releaseDate: "2000-09-05",
    rating: 0,
    length: 113,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Snatch",
    director: "Guy Ritchie",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/validated/snatch.jpg",
    releaseDate: "2000-09-01",
    rating: 0,
    length: 104,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "X-Men",
    director: "Bryan Singer",
    actors: [{ name: "Patrick Stewart" }],
    coverUrl: "/movies/validated/27723-x-men-0-150-0-225-crop.jpg",
    releaseDate: "2000-07-14",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Scary Movie",
    director: "Keenen Ivory Wayans",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/validated/49443-scary-movie-0-150-0-225-crop.jpg",
    releaseDate: "2000-07-07",
    rating: 0,
    length: 88,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Requiem for a Dream",
    director: "Darren Aronofsky",
    actors: [{ name: "Ellen Burstyn" }],
    coverUrl: "/movies/validated/requiem_for_a_dream.jpg",
    releaseDate: "2000-10-06",
    rating: 0,
    length: 102,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Gladiator",
    director: "Ridley Scott",
    actors: [{ name: "Russell Crowe" }],
    coverUrl: "/movies/validated/51952-gladiator-2000-0-150-0-225-crop.jpg",
    releaseDate: "2000-05-05",
    rating: 0,
    length: 155,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Taxi 2",
    director: "Gérard Krawczyk",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies/validated/50322-taxi-2-0-150-0-225-crop.jpg",
    releaseDate: "2000-03-31",
    rating: 0,
    length: 88,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Destination Finale",
    director: "James Wong",
    actors: [{ name: "Devon Sawa" }],
    coverUrl: "/movies/validated/47068-final-destination-0-150-0-225-crop.jpg",
    releaseDate: "2000-03-17",
    rating: 0,
    length: 98,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "The Whole Nine Yards",
    director: "Jonathan Lynn",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/validated/50554-the-whole-nine-yards-0-150-0-225-crop.jpg",
    releaseDate: "2000-02-18",
    rating: 0,
    length: 98,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Scream 3",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies/validated/49453-scream-3-0-150-0-225-crop.jpg",
    releaseDate: "2000-02-04",
    rating: 0,
    length: 116,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "La Ligne Verte",
    director: "Frank Darabont",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/validated/51613-the-green-mile-0-150-0-225-crop.jpg",
    releaseDate: "1999-12-10",
    rating: 0,
    length: 189,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Toy Story 2",
    director: "John Lasseter",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/validated/51289-toy-story-2-0-150-0-225-crop.jpg",
    releaseDate: "1999-11-24",
    rating: 0,
    length: 92,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "American Beauty",
    director: "Sam Mendes",
    actors: [{ name: "Kevin Spacey" }],
    coverUrl: "/movies/validated/2703-american-beauty-0-150-0-225-crop.jpg",
    releaseDate: "1999-09-15",
    rating: 0,
    length: 122,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Sixième Sens",
    director: "M. Night Shyamalan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/validated/51407-the-sixth-sense-0-150-0-225-crop.jpg",
    releaseDate: "1999-08-06",
    rating: 0,
    length: 107,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "American Pie",
    director: "Paul Weitz, Chris Weitz",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies/validated/50521-american-pie-0-150-0-225-crop.jpg",
    releaseDate: "1999-07-09",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Wild Wild West",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/validated/wild_wild_west.jpg",
    releaseDate: "1999-06-30",
    rating: 0,
    length: 106,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "South Park, le Film : Plus Long, Plus Grand et Pas Coupe",
    director: "Trey Parker",
    actors: [{ name: "Trey Parker" }],
    coverUrl: "/movies/validated/47125-south-park-bigger-longer-uncut-0-150-0-225-crop.jpg",
    releaseDate: "1999-06-30",
    rating: 0,
    length: 81,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Tarzan",
    director: "Chris Buck, Kevin Lima",
    actors: [{ name: "Tony Goldwyn" }],
    coverUrl: "/movies/validated/tarzan.jpg",
    releaseDate: "1999-06-18",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Star Wars : Épisode I - La Menace Fantôme",
    director: "George Lucas",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies/validated/50711-star-wars-episode-i-the-phantom-menace-0-150-0-225-crop.jpg",
    releaseDate: "1999-05-19",
    rating: 0,
    length: 136,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Notting Hill",
    director: "Roger Michell",
    actors: [{ name: "Julia Roberts" }],
    coverUrl: "/movies/validated/notting-hill-0-150-0-225-crop.jpg",
    releaseDate: "1999-05-28",
    rating: 0,
    length: 124,
    genre: "Romance",
    timesWatched: 0,
  },
  {
    title: "La Momie",
    director: "Stephen Sommers",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies/validated/la_momie.jpg",
    releaseDate: "1999-05-07",
    rating: 0,
    length: 125,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "Matrix",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/validated/51518-the-matrix-0-150-0-225-crop.jpg",
    releaseDate: "1999-03-31",
    rating: 0,
    length: 136,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Cruelles Intentions",
    director: "Roger Kumble",
    actors: [{ name: "Sarah Michelle Gellar" }],
    coverUrl: "/movies/validated/51356-cruel-intentions-0-150-0-225-crop.jpg",
    releaseDate: "1999-03-05",
    rating: 0,
    length: 97,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Rencontre avec Joe Black",
    director: "Martin Brest",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/validated/51762-meet-joe-black-0-150-0-225-crop.jpg",
    releaseDate: "1998-11-13",
    rating: 2,
    length: 178,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Fourmiz",
    director: "Eric Darnell, Tim Johnson",
    actors: [{ name: "Woody Allen" }],
    coverUrl: "/movies/validated/47511-antz-0-150-0-225-crop.jpg",
    releaseDate: "1998-10-02",
    rating: 0,
    length: 83,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Rush Hour",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies/validated/50517-rush-hour-0-150-0-225-crop.jpg",
    releaseDate: "1998-09-18",
    rating: 0,
    length: 98,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Blade",
    director: "Stephen Norrington",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies/validated/27730-blade-0-150-0-225-crop.jpg",
    releaseDate: "1998-08-21",
    rating: 0,
    length: 120,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Arme Fatale 4",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies/validated/51209-lethal-weapon-4-0-150-0-225-crop.jpg",
    releaseDate: "1998-07-10",
    rating: 0,
    length: 127,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Armageddon",
    director: "Michael Bay",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/validated/51955-armageddon-0-150-0-225-crop.jpg",
    releaseDate: "1998-07-01",
    rating: 0,
    length: 151,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Mulan",
    director: "Tony Bancroft, Barry Cook",
    actors: [{ name: "Ming-Na Wen" }],
    coverUrl: "/movies/validated/266675-mulan-0-150-0-225-crop.jpg",
    releaseDate: "1998-06-19",
    rating: 0,
    length: 88,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "The Truman Show",
    director: "Peter Weir",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/validated/the-truman-show-0-150-0-225-crop.jpg",
    releaseDate: "1998-06-05",
    rating: 0,
    length: 103,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Godzilla",
    director: "Roland Emmerich",
    actors: [{ name: "Matthew Broderick" }],
    coverUrl: "/movies/validated/51224-godzilla-0-150-0-225-crop.jpg",
    releaseDate: "1998-05-20",
    rating: 0,
    length: 139,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Le Dîner de Cons",
    director: "Francis Veber",
    actors: [{ name: "Thierry Lhermitte" }],
    coverUrl: "/movies/validated/47176-the-dinner-game-0-150-0-225-crop.jpg",
    releaseDate: "1998-04-15",
    rating: 0,
    length: 80,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Taxi",
    director: "Gérard Pirès",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies/validated/50324-taxi-0-150-0-225-crop.jpg",
    releaseDate: "1998-04-08",
    rating: 0,
    length: 86,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Mercury Rising",
    director: "Harold Becker",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/validated/47583-mercury-rising-0-150-0-225-crop.jpg",
    releaseDate: "1998-04-03",
    rating: 0,
    length: 111,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "The Big Lebowski",
    director: "Joel Coen, Ethan Coen",
    actors: [{ name: "Jeff Bridges" }],
    coverUrl: "/movies/validated/51935-the-big-lebowski-0-150-0-225-crop.jpg",
    releaseDate: "1998-03-06",
    rating: 0,
    length: 117,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Scream 2",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies/validated/scream_2.jpg",
    releaseDate: "1997-12-12",
    rating: 0,
    length: 120,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "Will Hunting",
    director: "Gus Van Sant",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/validated/51621-good-will-hunting-0-150-0-225-crop.jpg",
    releaseDate: "1997-12-05",
    rating: 0,
    length: 126,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Alien : La Résurrection",
    director: "Jean-Pierre Jeunet",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies/validated/47887-alien-resurrection-0-150-0-225-crop.jpg",
    releaseDate: "1997-11-26",
    rating: 0,
    length: 109,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Je Sais ce que Vous Avez Fait l'Été Dernier",
    director: "Jim Gillespie",
    actors: [{ name: "Jennifer Love Hewitt" }],
    coverUrl: "/movies/validated/le_dernier_samaritain.jpg",
    releaseDate: "1997-10-17",
    rating: 0,
    length: 101,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "L'Avocat du Diable",
    director: "Taylor Hackford",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/validated/50780-the-devil-s-advocate-0-150-0-225-crop.jpg",
    releaseDate: "1997-10-17",
    rating: 0,
    length: 144,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Princesse Mononoké",
    director: "Hayao Miyazaki",
    actors: [{ name: "Yôji Matsuda" }],
    coverUrl: "/movies/validated/mNqZOtJIQfFQPjo3hmYLIn8Qqhf-0-150-0-225-crop.jpg",
    releaseDate: "1997-07-12",
    rating: 0,
    length: 134,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Men in Black",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/validated/51514-men-in-black-0-150-0-225-crop.jpg",
    releaseDate: "1997-07-02",
    rating: 0,
    length: 98,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Hercule",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Tate Donovan" }],
    coverUrl: "/movies/validated/44838-hercules-0-150-0-225-crop.jpg",
    releaseDate: "1997-06-27",
    rating: 0,
    length: 93,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Batman & Robin",
    director: "Joel Schumacher",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/validated/batman_and_robin.jpg",
    releaseDate: "1997-06-20",
    rating: 0,
    length: 125,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Le Cinquième Élément",
    director: "Luc Besson",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/validated/le_cinquieme_element.jpg",
    releaseDate: "1997-05-09",
    rating: 0,
    length: 126,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Scream",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies/validated/49455-scream-0-150-0-225-crop.jpg",
    releaseDate: "1996-12-20",
    rating: 0,
    length: 111,
    genre: "Horror",
    timesWatched: 0,
  },


];