import { Movie } from "./movies_1";

export const moviesPage8: Movie[] = [
  {
    title: "DodgeBall: A True Underdog Story",
    director: "Rawson Marshall Thurber",
    actors: [{ name: "Vince Vaughn" }],
    coverUrl: "/movies/validated/dodgeball.jpg",
    releaseDate: "2004-06-18",
    rating: 0,
    length: 92,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "The Terminal",
    director: "Steven Spielberg",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/validated/51527-the-terminal-0-150-0-225-crop.jpg",
    releaseDate: "2004-06-18",
    rating: 0,
    length: 128,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Garfield",
    director: "Peter Hewitt",
    actors: [{ name: "Bill Murray" }],
    coverUrl: "/movies/validated/47508-garfield-0-150-0-225-crop.jpg",
    releaseDate: "2004-06-11",
    rating: 0,
    length: 80,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    director: "Alfonso Cuarón",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/validated/harry_potter_prisonnier_askaban.jpg",
    releaseDate: "2004-06-04",
    rating: 0,
    length: 142,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "Harold & Kumar Go to White Castle",
    director: "Danny Leiner",
    actors: [{ name: "John Cho" }],
    coverUrl: "/movies/validated/harold_et_kumar_white_castle.jpg",
    releaseDate: "2004-07-30",
    rating: 0,
    length: 88,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "The Day After Tomorrow",
    director: "Roland Emmerich",
    actors: [{ name: "Dennis Quaid" }],
    coverUrl: "/movies/validated/le_jour_d_apres.jpg",
    releaseDate: "2004-05-28",
    rating: 0,
    length: 124,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Shrek 2",
    director: "Andrew Adamson, Kelly Asbury, Conrad Vernon",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies/validated/shrek_2.jpg",
    releaseDate: "2004-05-19",
    rating: 0,
    length: 93,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Van Helsing",
    director: "Stephen Sommers",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/validated/48113-van-helsing-0-150-0-225-crop.jpg",
    releaseDate: "2004-05-07",
    rating: 0,
    length: 131,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Man on Fire",
    director: "Tony Scott",
    actors: [{ name: "Denzel Washington" }],
    coverUrl: "/movies/validated/man_on_fire.jpg",
    releaseDate: "2004-04-23",
    rating: 0,
    length: 146,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Kill Bill: Vol. 2",
    director: "Quentin Tarantino",
    actors: [{ name: "Uma Thurman" }],
    coverUrl: "/movies/validated/kill_bill_2.jpg",
    releaseDate: "2004-04-16",
    rating: 0,
    length: 137,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Hellboy",
    director: "Guillermo del Toro",
    actors: [{ name: "Ron Perlman" }],
    coverUrl: "/movies/validated/51012-hellboy-0-150-0-225-crop.jpg",
    releaseDate: "2004-04-02",
    rating: 0,
    length: 122,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Shaun of the Dead",
    director: "Edgar Wright",
    actors: [{ name: "Simon Pegg" }],
    coverUrl: "/movies/validated/shaun_of_the_dead.jpg",
    releaseDate: "2004-04-09",
    rating: 0,
    length: 99,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Scooby-Doo 2: Monsters Unleashed",
    director: "Raja Gosnell",
    actors: [{ name: "Freddie Prinze Jr." }],
    coverUrl: "/movies/validated/45679-scooby-doo-2-monsters-unleashed-0-150-0-225-crop.jpg",
    releaseDate: "2004-03-26",
    rating: 0,
    length: 93,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "The Chorus",
    director: "Christophe Barratier",
    actors: [{ name: "Gérard Jugnot" }],
    coverUrl: "/movies/validated/les_choristes.jpg",
    releaseDate: "2004-03-17",
    rating: 0,
    length: 97,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Eternal Sunshine of the Spotless Mind",
    director: "Michel Gondry",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/validated/eternal_sunchine_of_the_spotless_mind.jpg",
    releaseDate: "2004-03-19",
    rating: 0,
    length: 108,
    genre: "Romance",
    timesWatched: 0,
  },
  {
    title: "EuroTrip",
    director: "Jeff Schaffer",
    actors: [{ name: "Scott Mechlowicz" }],
    coverUrl: "/movies/validated/47243-eurotrip-0-150-0-225-crop.jpg",
    releaseDate: "2004-02-20",
    rating: 0,
    length: 93,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "The Girl Next Door",
    director: "Luke Greenfield",
    actors: [{ name: "Emile Hirsch" }],
    coverUrl: "/movies/validated/46081-the-girl-next-door-2004-0-150-0-225-crop.jpg",
    releaseDate: "2004-04-09",
    rating: 0,
    length: 109,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "50 First Dates",
    director: "Peter Segal",
    actors: [{ name: "Adam Sandler" }],
    coverUrl: "/movies/validated/50773-50-first-dates-0-150-0-225-crop.jpg",
    releaseDate: "2004-02-13",
    rating: 0,
    length: 99,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "The 11 Commandments",
    director: "François Desagnat, Thomas Sorriaux",
    actors: [{ name: "François Desagnat" }],
    coverUrl: "/movies/validated/40754-the-11-commandments-0-150-0-225-crop.jpg",
    releaseDate: "2004-02-11",
    rating: 0,
    length: 90,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "RRRrrrr!!!",
    director: "Alain Chabat",
    actors: [{ name: "Marion Cotillard" }],
    coverUrl: "/movies/validated/38203-rrrrrrr--0-150-0-225-crop.jpg",
    releaseDate: "2004-01-28",
    rating: 0,
    length: 94,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Saw",
    director: "James Wan",
    actors: [{ name: "Cary Elwes" }],
    coverUrl: "/movies/validated/saw.jpg",
    releaseDate: "2004-10-29",
    rating: 0,
    length: 103,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "The Butterfly Effect",
    director: "Eric Bress, J. Mackye Gruber",
    actors: [{ name: "Ashton Kutcher" }],
    coverUrl: "/movies/validated/50654-the-butterfly-effect-0-150-0-225-crop.jpg",
    releaseDate: "2004-01-23",
    rating: 0,
    length: 113,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Oldboy",
    director: "Park Chan-wook",
    actors: [{ name: "Choi Min-sik" }],
    coverUrl: "/movies/validated/51454-oldboy-0-150-0-225-crop.jpg",
    releaseDate: "2003-11-21",
    rating: 0,
    length: 120,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "The Matrix Revolutions",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/validated/51516-the-matrix-revolutions-0-150-0-225-crop.jpg",
    releaseDate: "2003-11-05",
    rating: 0,
    length: 129,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Scary Movie 3",
    director: "David Zucker",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/validated/49434-scary-movie-3-0-150-0-225-crop.jpg",
    releaseDate: "2003-10-24",
    rating: 0,
    length: 84,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Kill Bill: Vol. 1",
    director: "Quentin Tarantino",
    actors: [{ name: "Uma Thurman" }],
    coverUrl: "/movies/validated/kill_bill.jpg",
    releaseDate: "2003-10-10",
    rating: 0,
    length: 111,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Underworld",
    director: "Len Wiseman",
    actors: [{ name: "Kate Beckinsale" }],
    coverUrl: "/movies/validated/underworld_1.jpg",
    releaseDate: "2003-09-19",
    rating: 0,
    length: 121,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Love Actually",
    director: "Richard Curtis",
    actors: [{ name: "Hugh Grant" }],
    coverUrl: "/movies/validated/51602-love-actually-0-150-0-225-crop.jpg",
    releaseDate: "2003-11-07",
    rating: 0,
    length: 135,
    genre: "Romance",
    timesWatched: 0,
  },
  {
    title: "Spy Kids 3-D: Game Over",
    director: "Robert Rodriguez",
    actors: [{ name: "Alexa Vega" }],
    coverUrl: "/movies/validated/44637-spy-kids-3-d-game-over-0-150-0-225-crop.jpg",
    releaseDate: "2003-07-25",
    rating: 0,
    length: 84,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "American Wedding",
    director: "Jesse Dylan",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies/validated/47833-american-wedding-0-150-0-225-crop.jpg",
    releaseDate: "2003-08-01",
    rating: 0,
    length: 96,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Bad Boys II",
    director: "Michael Bay",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/validated/47473-bad-boys-ii-0-150-0-225-crop.jpg",
    releaseDate: "2003-07-18",
    rating: 0,
    length: 147,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Terminator 3: Rise of the Machines",
    director: "Jonathan Mostow",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/validated/51763-terminator-3-rise-of-the-machines-0-150-0-225-crop.jpg",
    releaseDate: "2003-07-02",
    rating: 0,
    length: 109,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    director: "Gore Verbinski",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/validated/2695-pirates-of-the-caribbean-the-curse-of-the-black-pearl-0-150-0-225-crop.jpg",
    releaseDate: "2003-07-09",
    rating: 0,
    length: 143,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "Hulk",
    director: "Ang Lee",
    actors: [{ name: "Eric Bana" }],
    coverUrl: "/movies/validated/50678-hulk-0-150-0-225-crop.jpg",
    releaseDate: "2003-06-20",
    rating: 0,
    length: 138,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "2 Fast 2 Furious",
    director: "John Singleton",
    actors: [{ name: "Paul Walker" }],
    coverUrl: "/movies/validated/51536-2-fast-2-furious-0-150-0-225-crop.jpg",
    releaseDate: "2003-06-06",
    rating: 0,
    length: 107,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Finding Nemo",
    director: "Andrew Stanton",
    actors: [{ name: "Albert Brooks" }],
    coverUrl: "/movies/validated/2705-finding-nemo-0-150-0-225-crop.jpg",
    releaseDate: "2003-05-30",
    rating: 0,
    length: 100,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Bruce Almighty",
    director: "Tom Shadyac",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/validated/51749-bruce-almighty-0-150-0-225-crop.jpg",
    releaseDate: "2003-05-23",
    rating: 0,
    length: 101,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "The Matrix Reloaded",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/validated/51517-the-matrix-reloaded-0-150-0-225-crop.jpg",
    releaseDate: "2003-05-15",
    rating: 0,
    length: 138,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "X-men 2",
    director: "Bryan Singer",
    actors: [{ name: "Patrick Stewart" }],
    coverUrl: "/movies/validated/xmen2-poster-0-150-0-225-crop.jpg",
    releaseDate: "2003-05-02",
    rating: 0,
    length: 134,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "I, Cesar",
    director: "Richard Berry",
    actors: [{ name: "Richard Berry" }],
    coverUrl: "/movies/validated/6543-i-cesar-0-150-0-225-crop.jpg",
    releaseDate: "2003-04-30",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "Cradle 2 the Grave",
    director: "Andrzej Bartkowiak",
    actors: [{ name: "Jet Li" }],
    coverUrl: "/movies/validated/46051-cradle-2-the-grave-0-150-0-225-crop.jpg",
    releaseDate: "2003-02-28",
    rating: 0,
    length: 101,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Daredevil",
    director: "Mark Steven Johnson",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies/validated/daredevil.jpg",
    releaseDate: "2003-02-14",
    rating: 0,
    length: 103,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "La Beuze",
    director: "Éric Rochant",
    actors: [{ name: "Vincent Lindon" }],
    coverUrl: "/movies/validated/la_beuze.jpg",
    releaseDate: "2003-02-05",
    rating: 0,
    length: 95,
    genre: "Drama",
    timesWatched: 0,
  },
  {
    title: "Final Destination 2",
    director: "David R. Ellis",
    actors: [{ name: "A.J. Cook" }],
    coverUrl: "/movies/validated/destination_finale_2.jpg",
    releaseDate: "2003-01-31",
    rating: 0,
    length: 90,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "Taxi 3",
    director: "Gérard Krawczyk",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies/validated/50320-taxi-3-0-150-0-225-crop.jpg",
    releaseDate: "2003-01-29",
    rating: 0,
    length: 84,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Ong Bak",
    director: "Prachya Pinkaew",
    actors: [{ name: "Tony Jaa" }],
    coverUrl: "/movies/validated/47277-ong-bak-0-150-0-225-crop.jpg",
    releaseDate: "2003-01-21",
    rating: 0,
    length: 108,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Catch Me If You Can",
    director: "Steven Spielberg",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/validated/51484-catch-me-if-you-can-0-150-0-225-crop.jpg",
    releaseDate: "2002-12-25",
    rating: 0,
    length: 141,
    genre: "Crime",
    timesWatched: 0,
  },
  {
    title: "Equilibrium",
    director: "Kurt Wimmer",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/validated/equilibrium-0-150-0-225-crop.jpg",
    releaseDate: "2002-12-06",
    rating: 0,
    length: 107,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Die Another Day",
    director: "Lee Tamahori",
    actors: [{ name: "Pierce Brosnan" }],
    coverUrl: "/movies/validated/james_bond_demain_ne_meurs_jamaiis.jpg",
    releaseDate: "2002-11-22",
    rating: 0,
    length: 133,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    director: "Chris Columbus",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/validated/harry_potter_chambre_des_secrets.jpg",
    releaseDate: "2002-11-15",
    rating: 0,
    length: 161,
    genre: "Fantasy",
    timesWatched: 0,
  },
  {
    title: "Cheats",
    director: "Andrew Gurland",
    actors: [{ name: "Trevor Fehrman" }],
    coverUrl: "/movies/validated/41348-cheats-0-150-0-225-crop.jpg",
    releaseDate: "2002-09-13",
    rating: 0,
    length: 85,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "28 Days Later",
    director: "Danny Boyle",
    actors: [{ name: "Cillian Murphy" }],
    coverUrl: "/movies/validated/28_jours_plus_tard.jpg",
    releaseDate: "2002-11-01",
    rating: 0,
    length: 113,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "The Transporter",
    director: "Louis Leterrier, Corey Yuen",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/validated/49510-the-transporter-0-150-0-225-crop.jpg",
    releaseDate: "2002-10-11",
    rating: 0,
    length: 92,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "The Ring",
    director: "Gore Verbinski",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies/validated/the-ring-0-150-0-225-crop.jpg",
    releaseDate: "2002-10-18",
    rating: 0,
    length: 115,
    genre: "Horror",
    timesWatched: 0,
  },
  {
    title: "Phone Booth",
    director: "Joel Schumacher",
    actors: [{ name: "Colin Farrell" }],
    coverUrl: "/movies/validated/phone_game.jpg",
    releaseDate: "2002-09-10",
    rating: 0,
    length: 81,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "xXx",
    director: "Rob Cohen",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/validated/48025-xxx-0-150-0-225-crop.jpg",
    releaseDate: "2002-08-09",
    rating: 0,
    length: 124,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Spy Kids 2: The Island of Lost Dreams",
    director: "Robert Rodriguez",
    actors: [{ name: "Alexa Vega" }],
    coverUrl: "/movies/validated/47110-spy-kids-2-island-of-lost-dreams-0-150-0-225-crop.jpg",
    releaseDate: "2002-08-07",
    rating: 0,
    length: 100,
    genre: "Adventure",
    timesWatched: 0,
  },
  {
    title: "Men in Black II",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/validated/51513-men-in-black-ii-0-150-0-225-crop.jpg",
    releaseDate: "2002-07-03",
    rating: 0,
    length: 88,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Minority Report",
    director: "Steven Spielberg",
    actors: [{ name: "Tom Cruise" }],
    coverUrl: "/movies/validated/minority_report.jpg",
    releaseDate: "2002-06-21",
    rating: 0,
    length: 145,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Scooby-Doo",
    director: "Raja Gosnell",
    actors: [{ name: "Freddie Prinze Jr." }],
    coverUrl: "/movies/validated/scooby-doo.jpg",
    releaseDate: "2002-06-14",
    rating: 0,
    length: 86,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "The Bourne Identity",
    director: "Doug Liman",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/validated/50225-the-bourne-identity-0-150-0-225-crop.jpg",
    releaseDate: "2002-06-14",
    rating: 0,
    length: 119,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Star Wars: Episode II – Attack of the Clones",
    director: "George Lucas",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies/validated/50710-star-wars-episode-ii-attack-of-the-clones-0-150-0-225-crop.jpg",
    releaseDate: "2002-05-16",
    rating: 0,
    length: 142,
    genre: "Science Fiction",
    timesWatched: 0,
  },
  {
    title: "Spider-Man",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies/validated/51561-spider-man-0-150-0-225-crop.jpg",
    releaseDate: "2002-05-03",
    rating: 0,
    length: 121,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Murder by Numbers",
    director: "Barbet Schroeder",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/validated/44914-murder-by-numbers-0-150-0-225-crop.jpg",
    releaseDate: "2002-04-19",
    rating: 0,
    length: 120,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Blade II",
    director: "Guillermo del Toro",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies/validated/27781-blade-ii-0-150-0-225-crop.jpg",
    releaseDate: "2002-03-22",
    rating: 0,
    length: 117,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Panic Room",
    director: "David Fincher",
    actors: [{ name: "Jodie Foster" }],
    coverUrl: "/movies/validated/panic_room.jpg",
    releaseDate: "2002-03-29",
    rating: 0,
    length: 112,
    genre: "Thriller",
    timesWatched: 0,
  },
  {
    title: "Resident Evil",
    director: "Paul W.S. Anderson",
    actors: [{ name: "Milla Jovovich" }],
    coverUrl: "/movies/validated/resident_evil.jpg",
    releaseDate: "2002-03-15",
    rating: 0,
    length: 100,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "L'Âge de Glace",
    director: "Chris Wedge, Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies/validated/51670-ice-age-0-150-0-225-crop.jpg",
    releaseDate: "2002-03-15",
    rating: 0,
    length: 81,
    genre: "Animation",
    timesWatched: 0,
  },
  {
    title: "Rollerball",
    director: "John McTiernan",
    actors: [{ name: "Chris Klein" }],
    coverUrl: "/movies/validated/45213-rollerball-0-150-0-225-crop.jpg",
    releaseDate: "2002-02-08",
    rating: 0,
    length: 98,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Collateral Damage",
    director: "Andrew Davis",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/validated/46749-collateral-damage-0-150-0-225-crop.jpg",
    releaseDate: "2002-02-08",
    rating: 0,
    length: 108,
    genre: "Action",
    timesWatched: 0,
  },
  {
    title: "Astérix & Obélix : Mission Cléopâtre",
    director: "Alain Chabat",
    actors: [{ name: "Gérard Depardieu" }],
    coverUrl: "/movies/validated/50024-asterix-obelix-mission-cleopatra-0-150-0-225-crop.jpg",
    releaseDate: "2002-01-30",
    rating: 0,
    length: 107,
    genre: "Comedy",
    timesWatched: 0,
  },
  {
    title: "A Walk to Remember",
    director: "Adam Shankman",
    actors: [{ name: "Mandy Moore" }],
    coverUrl: "/movies/validated/46422-a-walk-to-remember-0-150-0-225-crop.jpg",
    releaseDate: "2002-01-25",
    rating: 0,
    length: 101,
    genre: "Romance",
    timesWatched: 0,
  },


];