import { Movie } from "./movies_1";

export const moviesOtherSuperheroes: Movie[] = [
  {
    title: "Deadpool",
    director: "Tim Miller",
    actors: [{ name: "Ryan Reynolds" }],
    coverUrl: "/movies_pictures/validated/220575-deadpool-0-150-0-225-crop.jpg",
    releaseDate: "2016-02-12",
    rating: 0,
    length: 108,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Deadpool 2",
    director: "David Leitch",
    actors: [
      {
        name: "Ryan Reynolds",
      },
    ],
    coverUrl: "/movies_pictures/validated/318195-deadpool-2-0-150-0-225-crop.jpg",
    releaseDate: "2018-05-18",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Daredevil",
    director: "Mark Steven Johnson",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies_pictures/validated/daredevil.jpg",
    releaseDate: "2003-02-14",
    rating: 0,
    length: 103,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Green Lantern",
    director: "Martin Campbell",
    actors: [{ name: "Ryan Reynolds" }],
    coverUrl: "/movies_pictures/validated/20293-green-lantern-0-150-0-225-crop.jpg",
    releaseDate: "2011-06-17",
    rating: 0,
    length: 114,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "X-Men",
    director: "Bryan Singer",
    actors: [{ name: "Patrick Stewart" }],
    coverUrl: "/movies_pictures/validated/27723-x-men-0-150-0-225-crop.jpg",
    releaseDate: "2000-07-14",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "X-men 2",
    director: "Bryan Singer",
    actors: [{ name: "Patrick Stewart" }],
    coverUrl: "/movies_pictures/validated/xmen2-poster-0-150-0-225-crop.jpg",
    releaseDate: "2003-05-02",
    rating: 0,
    length: 134,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "X-Men : L'Affrontement Final",
    director: "Brett Ratner",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies_pictures/validated/27713-x-men-the-last-stand-0-150-0-225-crop.jpg",
    releaseDate: "2006-05-26",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "X-Men Origins : Wolverine",
    director: "Gavin Hood",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies_pictures/validated/50544-x-men-origins-wolverine-0-150-0-225-crop.jpg",
    releaseDate: "2009-05-01",
    rating: 0,
    length: 107,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "The Wolverine",
    director: "James Mangold",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies_pictures/validated/62638-the-wolverine-0-150-0-225-crop.jpg",
    releaseDate: "2013-07-26",
    rating: 0,
    length: 126,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Logan",
    director: "James Mangold",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies_pictures/validated/logan.jpg",
    releaseDate: "2017-03-03",
    rating: 0,
    length: 137,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "X-Men : Le Commencement",
    director: "Matthew Vaughn",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies_pictures/validated/16074-x-men-first-class-0-150-0-225-crop.jpg",
    releaseDate: "2011-06-03",
    rating: 0,
    length: 132,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "X-Men : Days of Future Past",
    director: "Bryan Singer",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies_pictures/validated/99507-x-men-days-of-future-past-0-150-0-225-crop.jpg",
    releaseDate: "2014-05-23",
    rating: 0,
    length: 132,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "X-Men : Apocalypse",
    director: "Bryan Singer",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies_pictures/validated/172492-x-men-apocalypse-0-150-0-225-crop.jpg",
    releaseDate: "2016-05-27",
    rating: 0,
    length: 144,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "X-Men :Dark Phoenix",
    director: "Simon Kinberg",
    actors: [
      {
        name: "Sophie Turner",
      },
    ],
    coverUrl: "/movies_pictures/validated/247385-dark-phoenix-0-150-0-225-crop.jpg",
    releaseDate: "2019-06-07",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Batman",
    director: "Tim Burton",
    actors: [{ name: "Michael Keaton" }],
    coverUrl: "/movies_pictures/validated/51788-batman-0-150-0-225-crop.jpg",
    releaseDate: "1989-06-23",
    rating: 0,
    length: 126,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Batman Returns",
    director: "Tim Burton",
    actors: [{ name: "Michael Keaton" }],
    coverUrl: "/movies_pictures/validated/51709-batman-returns-0-150-0-225-crop.jpg",
    releaseDate: "1992-06-19",
    rating: 0,
    length: 126,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Batman Forever",
    director: "Joel Schumacher",
    actors: [{ name: "Val Kilmer" }],
    coverUrl: "/movies_pictures/validated/51678-batman-forever-0-150-0-225-crop.jpg",
    releaseDate: "1995-06-16",
    rating: 0,
    length: 121,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Batman & Robin",
    director: "Joel Schumacher",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies_pictures/validated/batman_and_robin.jpg",
    releaseDate: "1997-06-20",
    rating: 0,
    length: 125,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Batman Begins",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies_pictures/validated/51784-batman-begins-0-150-0-225-crop.jpg",
    releaseDate: "2005-06-15",
    rating: 0,
    length: 140,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "The Dark Knight : Le Chevalier Noir",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies_pictures/validated/the_dark_knight.jpg",
    releaseDate: "2008-07-18",
    rating: 0,
    length: 152,
    genre: "Action",
    timesWatched: 30,
  },
  {
    title: "The Dark Knight Rises",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies_pictures/validated/16550-the-dark-knight-rises-0-150-0-225-crop.jpg",
    releaseDate: "2012-07-20",
    rating: 0,
    length: 164,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "The Batman",
    director: "Matt Reeves",
    actors: [
      {
        name: "Robert Pattinson",
      },
    ],
    coverUrl: "/movies_pictures/validated/348914-the-batman-0-150-0-225-crop.jpg",
    releaseDate: "2022-03-04",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Batman v Superman : L'Aube de la Justice",
    director: "Zack Snyder",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies_pictures/validated/batman_v_superman.jpg",
    releaseDate: "2016-03-25",
    rating: 0,
    length: 151,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Shazam!",
    director: "David F. Sandberg",
    actors: [
      {
        name: "Zachary Levi",
      },
    ],
    coverUrl: "/movies_pictures/validated/213190-shazam--0-150-0-225-crop.jpg",
    releaseDate: "2019-04-05",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Aquaman",
    director: "James Wan",
    actors: [
      {
        name: "Jason Momoa",
      },
    ],
    coverUrl: "/movies_pictures/validated/225060-aquaman-0-150-0-225-crop.jpg",
    releaseDate: "2018-12-21",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Venom",
    director: "Ruben Fleischer",
    actors: [
      {
        name: "Tom Hardy",
      },
    ],
    coverUrl: "/movies_pictures/validated/265438-venom-0-150-0-225-crop.jpg",
    releaseDate: "2018-10-05",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Venom : Let There Be Carnage",
    director: "Andy Serkis",
    actors: [
      {
        name: "Tom Hardy",
      },
    ],
    coverUrl: "/movies_pictures/validated/508638-venom-let-there-be-carnage-0-150-0-225-crop.jpg",
    releaseDate: "2021-10-01",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Black Adam",
    director: "Jaume Collet-Serra",
    actors: [
      {
        name: "Dwayne Johnson",
      },
    ],
    coverUrl: "/movies_pictures/validated/369179-black-adam-0-150-0-225-crop.jpg",
    releaseDate: "2022-10-21",
    rating: 0,
    length: 0,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Justice League",
    director: "Zack Snyder",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies_pictures/validated/107670-justice-league-0-150-0-225-crop.jpg",
    releaseDate: "2017-11-17",
    rating: 0,
    length: 120,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Suicide Squad",
    director: "David Ayer",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/validated/suicide_squad.jpg",
    releaseDate: "2016-08-05",
    rating: 0,
    length: 123,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Spider-Man",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies_pictures/validated/51561-spider-man-0-150-0-225-crop.jpg",
    releaseDate: "2002-05-03",
    rating: 0,
    length: 121,
    genre: "Action",
    timesWatched: 40,
  },
  {
    title: "Spider-Man 2",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies_pictures/validated/amazin_spiderman_2.jpg",
    releaseDate: "2004-06-30",
    rating: 0,
    length: 127,
    genre: "Action",
    timesWatched: 30,
  },
  {
    title: "Spider-Man 3",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies_pictures/validated/spiderman_3.jpg",
    releaseDate: "2007-05-04",
    rating: 0,
    length: 139,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "The Amazing Spider-Man",
    director: "Marc Webb",
    actors: [{ name: "Andrew Garfield" }],
    coverUrl: "/movies_pictures/validated/50677-the-amazing-spider-man-0-150-0-225-crop.jpg",
    releaseDate: "2012-07-03",
    rating: 0,
    length: 136,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "The Amazing Spider-Man : Le Destin d'un Héros",
    director: "Marc Webb",
    actors: [{ name: "Andrew Garfield" }],
    coverUrl: "/movies_pictures/validated/47306-final-destination-3-0-150-0-225-crop.jpg",
    releaseDate: "2014-05-02",
    rating: 0,
    length: 142,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Kick-Ass",
    director: "Matthew Vaughn",
    actors: [{ name: "Aaron Taylor-Johnson" }],
    coverUrl: "/movies_pictures/validated/kick_ass.jpg",
    releaseDate: "2010-04-16",
    rating: 0,
    length: 117,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Kick-Ass 2",
    director: "Jeff Wadlow",
    actors: [{ name: "Aaron Taylor-Johnson" }],
    coverUrl: "/movies_pictures/validated/kick_ass_2.jpg",
    releaseDate: "2013-08-16",
    rating: 0,
    length: 103,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Man of Steel",
    director: "Zack Snyder",
    actors: [{ name: "Henry Cavill" }],
    coverUrl: "/movies_pictures/validated/man_of_steel.jpg",
    releaseDate: "2013-06-14",
    rating: 0,
    length: 143,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Watchmen : Les Gardiens",
    director: "Zack Snyder",
    actors: [{ name: "Jackie Earle Haley" }],
    coverUrl: "/movies_pictures/validated/44070-watchmen-0-150-0-225-crop.jpg",
    releaseDate: "2009-03-06",
    rating: 0,
    length: 162,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Hancock",
    director: "Peter Berg",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/validated/hancock.jpg",
    releaseDate: "2008-07-02",
    rating: 0,
    length: 92,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Les 4 Fantastiques",
    director: "Tim Story",
    actors: [{ name: "Ioan Gruffudd" }],
    coverUrl: "/movies_pictures/validated/123065-fantastic-four-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-08",
    rating: 0,
    length: 106,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Les 4 Fantastiques et le Surfeur d'Argent",
    director: "Tim Story",
    actors: [{ name: "Ioan Gruffudd" }],
    coverUrl: "/movies_pictures/validated/50631-fantastic-four-rise-of-the-silver-surfer-0-150-0-225-crop.jpg",
    releaseDate: "2007-06-15",
    rating: 0,
    length: 92,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Ghost Rider",
    director: "Mark Steven Johnson",
    actors: [{ name: "Nicolas Cage" }],
    coverUrl: "/movies_pictures/validated/51130-ghost-rider-0-150-0-225-crop.jpg",
    releaseDate: "2007-02-16",
    rating: 0,
    length: 114,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Sky High",
    director: "Mike Mitchell",
    actors: [{ name: "Michael Angarano" }],
    coverUrl: "/movies_pictures/validated/45283-sky-high-0-150-0-225-crop.jpg",
    releaseDate: "2005-07-29",
    rating: 0,
    length: 100,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "Catwoman",
    director: "Pitof",
    actors: [{ name: "Halle Berry" }],
    coverUrl: "/movies_pictures/validated/51745-catwoman-0-150-0-225-crop.jpg",
    releaseDate: "2004-07-23",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Hulk",
    director: "Ang Lee",
    actors: [{ name: "Eric Bana" }],
    coverUrl: "/movies_pictures/validated/50678-hulk-0-150-0-225-crop.jpg",
    releaseDate: "2003-06-20",
    rating: 0,
    length: 138,
    genre: "Action",
    timesWatched: 2,
  },
];