import { Movie } from "./movies_1";

export const moviesPage6: Movie[] = [
  {
    title: "OSS 117 : Rio ne Répond Plus",
    director: "Michel Hazanavicius",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies_pictures/42256-oss-117-lost-in-rio-0-150-0-225-crop.jpg",
    releaseDate: "2009-04-15",
    rating: 0,
    length: 101,
    genre: "Comedy",
    timesWatched: 2,
  },
  {
    title: "Knowing",
    director: "Alex Proyas",
    actors: [{ name: "Nicolas Cage" }],
    coverUrl: "/movies_pictures/43577-knowing-0-150-0-225-crop.jpg",
    releaseDate: "2009-03-20",
    rating: 0,
    length: 121,
    genre: "Science Fiction",
    timesWatched: 3,
  },
  {
    title: "Banlieue 13 : Ultimatum",
    director: "Patrick Alessandrin",
    actors: [{ name: "David Belle" }],
    coverUrl: "/movies_pictures/42437-district-13-ultimatum-0-150-0-225-crop.jpg",
    releaseDate: "2009-02-18",
    rating: 0,
    length: 101,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Underworld : Rise of the Lycans",
    director: "Patrick Tatopoulos",
    actors: [{ name: "Michael Sheen" }],
    coverUrl: "/movies_pictures/44587-underworld-rise-of-the-lycans-0-150-0-225-crop.jpg",
    releaseDate: "2009-01-23",
    rating: 0,
    length: 92,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "I Love You Phillip Morris",
    director: "Glenn Ficarra, John Requa",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies_pictures/i_love_you_philipp_morris.jpg",
    releaseDate: "2009-01-30",
    rating: 0,
    length: 98,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Sept Vies",
    director: "Gabriele Muccino",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/45412-seven-pounds-0-150-0-225-crop.jpg",
    releaseDate: "2008-12-19",
    rating: 0,
    length: 123,
    genre: "Drama",
    timesWatched: 3,
  },
  {
    title: "Yes Man",
    director: "Peyton Reed",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies_pictures/yes-man-0-150-0-225-crop.jpg",
    releaseDate: "2008-12-19",
    rating: 0,
    length: 104,
    genre: "Comedy",
    timesWatched: 2,
  },
  {
    title: "Gran Torino",
    director: "Clint Eastwood",
    actors: [{ name: "Clint Eastwood" }],
    coverUrl: "/movies_pictures/gran_torino.jpg",
    releaseDate: "2008-12-12",
    rating: 0,
    length: 116,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Ong Bak 2",
    director: "Tony Jaa",
    actors: [{ name: "Tony Jaa" }],
    coverUrl: "/movies_pictures/41625-ong-bak-2-0-150-0-225-crop.jpg",
    releaseDate: "2008-12-05",
    rating: 0,
    length: 98,
    genre: "Action",
    timesWatched: 1,
  },
  {
    title: "Le Transporteur 3",
    director: "Olivier Megaton",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies_pictures/43931-transporter-3-0-150-0-225-crop.jpg",
    releaseDate: "2008-11-26",
    rating: 0,
    length: 104,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Twilight : Chapitre 1 - Fascination",
    director: "Catherine Hardwicke",
    actors: [{ name: "Kristen Stewart" }],
    coverUrl: "/movies_pictures/47469-twilight-0-150-0-225-crop.jpg",
    releaseDate: "2008-11-21",
    rating: 0,
    length: 122,
    genre: "Fantasy",
    timesWatched: 5,
  },
  {
    title: "Quantum of Solace",
    director: "Marc Forster",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies_pictures/45918-quantum-of-solace-0-150-0-225-crop.jpg",
    releaseDate: "2008-11-14",
    rating: 0,
    length: 106,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Eagle Eye",
    director: "D.J. Caruso",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies_pictures/44201-eagle-eye-0-150-0-225-crop.jpg",
    releaseDate: "2008-09-26",
    rating: 0,
    length: 118,
    genre: "Thriller",
    timesWatched: 15,
  },
  {
    title: "Slumdog Millionaire",
    director: "Danny Boyle",
    actors: [{ name: "Dev Patel" }],
    coverUrl: "/movies_pictures/44613-slumdog-millionaire-0-150-0-225-crop.jpg",
    releaseDate: "2008-12-25",
    rating: 0,
    length: 120,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Death Race",
    director: "Paul W.S. Anderson",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies_pictures/46186-death-race-0-150-0-225-crop.jpg",
    releaseDate: "2008-08-22",
    rating: 0,
    length: 105,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Hellboy 2 : Les Légions d'Or Maudites",
    director: "Guillermo del Toro",
    actors: [{ name: "Ron Perlman" }],
    coverUrl: "/movies_pictures/45459-hellboy-ii-the-golden-army-0-150-0-225-crop.jpg",
    releaseDate: "2008-07-11",
    rating: 0,
    length: 120,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "Voyage au Centre de la Terre",
    director: "Eric Brevig",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies_pictures/74826-journey-to-the-center-of-the-earth-0-150-0-225-crop.jpg",
    releaseDate: "2008-07-11",
    rating: 0,
    length: 93,
    genre: "Adventure",
    timesWatched: 5,
  },
  {
    title: "Wanted : Choisis ton Destin",
    director: "Timur Bekmambetov",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies_pictures/wanted.jpg",
    releaseDate: "2008-06-27",
    rating: 0,
    length: 110,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Rien que pour vos cheveux",
    director: "Dennis Dugan",
    actors: [{ name: "Adam Sandler" }],
    coverUrl: "/movies_pictures/dont-mess-with-the-zohan-0-150-0-225-crop.jpg",
    releaseDate: "2008-06-06",
    rating: 0,
    length: 113,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Speed Racer",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Emile Hirsch" }],
    coverUrl: "/movies_pictures/48018-speed-racer-0-150-0-225-crop.jpg",
    releaseDate: "2008-05-09",
    rating: 0,
    length: 135,
    genre: "Action",
    timesWatched: 2,
  },
  {
    title: "La vague",
    director: "Dennis Gansel",
    actors: [{ name: "Jürgen Vogel" }],
    coverUrl: "/movies_pictures/47981-the-wave-0-150-0-225-crop.jpg",
    releaseDate: "2008-03-13",
    rating: 0,
    length: 107,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Never Back Down",
    director: "Jeff Wadlow",
    actors: [{ name: "Sean Faris" }],
    coverUrl: "/movies_pictures/47713-never-back-down-0-150-0-225-crop.jpg",
    releaseDate: "2008-03-14",
    rating: 0,
    length: 110,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Taken",
    director: "Pierre Morel",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies_pictures/47648-taken-0-230-0-345-crop.jpg",
    releaseDate: "2008-02-27",
    rating: 0,
    length: 93,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Jumper",
    director: "Doug Liman",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies_pictures/47842-jumper-0-150-0-225-crop.jpg",
    releaseDate: "2008-02-14",
    rating: 0,
    length: 88,
    genre: "Science Fiction",
    timesWatched: 1,
  },
  {
    title: "John Rambo",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/47983-rambo-0-150-0-225-crop.jpg",
    releaseDate: "2008-01-25",
    rating: 0,
    length: 92,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "American Pie Presents: Beta House",
    director: "Andrew Waller",
    actors: [{ name: "John White" }],
    coverUrl: "/movies_pictures/american_pie_beta_house.jpg",
    releaseDate: "2007-12-26",
    rating: 0,
    length: 88,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Alien vs. Predator : Requiem",
    director: "Colin Strause, Greg Strause",
    actors: [{ name: "Steven Pasquale" }],
    coverUrl: "/movies_pictures/51655-avpr-aliens-vs-predator-requiem-0-150-0-225-crop.jpg",
    releaseDate: "2007-12-25",
    rating: 0,
    length: 94,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Je Suis une Légende",
    director: "Francis Lawrence",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/48296-i-am-legend-0-150-0-225-crop.jpg",
    releaseDate: "2007-12-14",
    rating: 0,
    length: 101,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "Resident Evil : Extinction",
    director: "Russell Mulcahy",
    actors: [{ name: "Milla Jovovich" }],
    coverUrl: "/movies_pictures/47979-resident-evil-extinction-0-150-0-225-crop.jpg",
    releaseDate: "2007-09-21",
    rating: 0,
    length: 94,
    genre: "Action",
    timesWatched: 3,
  },
  {
    title: "Paranormal Activity",
    director: "Oren Peli",
    actors: [{ name: "Katie Featherston" }],
    coverUrl: "/movies_pictures/paranormal_activity.jpg",
    releaseDate: "2007-10-14",
    rating: 0,
    length: 86,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Gone Baby Gone",
    director: "Ben Affleck",
    actors: [{ name: "Casey Affleck" }],
    coverUrl: "/movies_pictures/gone_baby_gone.jpg",
    releaseDate: "2007-10-19",
    rating: 0,
    length: 114,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Into the Wild",
    director: "Sean Penn",
    actors: [{ name: "Emile Hirsch" }],
    coverUrl: "/movies_pictures/48571-into-the-wild-0-150-0-225-crop.jpg",
    releaseDate: "2007-09-21",
    rating: 0,
    length: 148,
    genre: "Drama",
    timesWatched: 2,
  },
  {
    title: "Rush Hour 3",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies_pictures/48920-rush-hour-3-0-150-0-225-crop.jpg",
    releaseDate: "2007-08-10",
    rating: 0,
    length: 91,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "La Vengeance dans la Peau : L'Héritage Bourne",
    director: "Paul Greengrass",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies_pictures/50223-the-bourne-ultimatum-0-150-0-225-crop.jpg",
    releaseDate: "2007-08-03",
    rating: 0,
    length: 115,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Transformers",
    director: "Michael Bay",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies_pictures/transformers-0-150-0-225-crop.jpg",
    releaseDate: "2007-07-03",
    rating: 0,
    length: 144,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Die Hard 4 : Retour en Enfer",
    director: "Len Wiseman",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies_pictures/50963-live-free-or-die-hard-0-150-0-225-crop.jpg",
    releaseDate: "2007-06-27",
    rating: 0,
    length: 128,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "La chambre 1408",
    director: "Mikael Håfström",
    actors: [{ name: "John Cusack" }],
    coverUrl: "/movies_pictures/49944-1408-0-150-0-225-crop.jpg",
    releaseDate: "2007-06-22",
    rating: 0,
    length: 104,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Evan tout-puissant",
    director: "Tom Shadyac",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies_pictures/50146-evan-almighty-0-150-0-225-crop.jpg",
    releaseDate: "2007-06-22",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Ocean's Thirteen",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies_pictures/51761-ocean-s-thirteen-0-150-0-225-crop.jpg",
    releaseDate: "2007-06-08",
    rating: 0,
    length: 122,
    genre: "Crime",
    timesWatched: 3,
  },
  {
    title: "No Country for Old Men",
    director: "Joel Coen, Ethan Coen",
    actors: [{ name: "Tommy Lee Jones" }],
    coverUrl: "/movies_pictures/no_country_for_old_men.jpg",
    releaseDate: "2007-11-09",
    rating: 3,
    length: 122,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Pirates des Caraïbes : Jusqu'au Bout du Monde",
    director: "Gore Verbinski",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies_pictures/51773-pirates-of-the-caribbean-at-worlds-end-0-150-0-225-crop.jpg",
    releaseDate: "2007-05-25",
    rating: 0,
    length: 169,
    genre: "Adventure",
    timesWatched: 3,
  },
  {
    title: "28 Semaines Plus Tard",
    director: "Juan Carlos Fresnadillo",
    actors: [{ name: "Robert Carlyle" }],
    coverUrl: "/movies_pictures/28_jours_plus_tard.jpg",
    releaseDate: "2007-05-11",
    rating: 0,
    length: 100,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Dangereuse séduction",
    director: "James Foley",
    actors: [{ name: "Halle Berry" }],
    coverUrl: "/movies_pictures/48107-perfect-stranger-0-150-0-225-crop.jpg",
    releaseDate: "2007-04-13",
    rating: 0,
    length: 109,
    genre: "Thriller",
    timesWatched: 2,
  },
  {
    title: "Paranoïaque",
    director: "D.J. Caruso",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies_pictures/47835-disturbia-0-150-0-225-crop.jpg",
    releaseDate: "2007-04-13",
    rating: 0,
    length: 105,
    genre: "Thriller",
    timesWatched: 5,
  },
  {
    title: "Superbad",
    director: "Greg Mottola",
    actors: [{ name: "Jonah Hill" }],
    coverUrl: "/movies_pictures/47776-superbad-0-150-0-225-crop.jpg",
    releaseDate: "2007-08-17",
    rating: 0,
    length: 113,
    genre: "Comedy",
    timesWatched: 2,
  },
  {
    title: "Zodiac",
    director: "David Fincher",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies_pictures/zodiac.jpg",
    releaseDate: "2007-03-02",
    rating: 0,
    length: 157,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Taxi 4",
    director: "Gérard Krawczyk",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies_pictures/50319-taxi-4-0-150-0-225-crop.jpg",
    releaseDate: "2007-02-14",
    rating: 0,
    length: 91,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "Premonition",
    director: "Mennan Yapo",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies_pictures/46675-premonition-0-150-0-225-crop.jpg",
    releaseDate: "2007-03-16",
    rating: 0,
    length: 96,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Ecrire pour exister",
    director: "Richard LaGravenese",
    actors: [{ name: "Hilary Swank" }],
    coverUrl: "/movies_pictures/50896-freedom-writers-0-150-0-225-crop.jpg",
    releaseDate: "2007-01-05",
    rating: 0,
    length: 123,
    genre: "Drama",
    timesWatched: 1,
  },
];