import { Movie } from "./movies";

export const moviesPage8: Movie[] = [
  {
    title: "DodgeBall: A True Underdog Story",
    director: "Rawson Marshall Thurber",
    actors: [{ name: "Vince Vaughn" }],
    coverUrl: "/movies/dodgeball.jpg",
    releaseDate: "2004-06-18",
    rating: 0,
    length: 92,
    genre: "Comedy",
  },
  {
    title: "The Terminal",
    director: "Steven Spielberg",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/terminal.jpg",
    releaseDate: "2004-06-18",
    rating: 0,
    length: 128,
    genre: "Drama",
  },
  {
    title: "Garfield",
    director: "Peter Hewitt",
    actors: [{ name: "Bill Murray" }],
    coverUrl: "/movies/garfield.jpg",
    releaseDate: "2004-06-11",
    rating: 0,
    length: 80,
    genre: "Comedy",
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    director: "Alfonso Cuarón",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_prisoner_azkaban.jpg",
    releaseDate: "2004-06-04",
    rating: 0,
    length: 142,
    genre: "Fantasy",
  },
  {
    title: "Harold & Kumar Go to White Castle",
    director: "Danny Leiner",
    actors: [{ name: "John Cho" }],
    coverUrl: "/movies/harold_kumar_white_castle.jpg",
    releaseDate: "2004-07-30",
    rating: 0,
    length: 88,
    genre: "Comedy",
  },
  {
    title: "The Day After Tomorrow",
    director: "Roland Emmerich",
    actors: [{ name: "Dennis Quaid" }],
    coverUrl: "/movies/day_after_tomorrow.jpg",
    releaseDate: "2004-05-28",
    rating: 0,
    length: 124,
    genre: "Science Fiction",
  },
  {
    title: "Shrek 2",
    director: "Andrew Adamson, Kelly Asbury, Conrad Vernon",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies/shrek_2.jpg",
    releaseDate: "2004-05-19",
    rating: 0,
    length: 93,
    genre: "Animation",
  },
  {
    title: "Van Helsing",
    director: "Stephen Sommers",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/van_helsing.jpg",
    releaseDate: "2004-05-07",
    rating: 0,
    length: 131,
    genre: "Action",
  },
  {
    title: "Man on Fire",
    director: "Tony Scott",
    actors: [{ name: "Denzel Washington" }],
    coverUrl: "/movies/man_on_fire.jpg",
    releaseDate: "2004-04-23",
    rating: 0,
    length: 146,
    genre: "Action",
  },
  {
    title: "Kill Bill: Vol. 2",
    director: "Quentin Tarantino",
    actors: [{ name: "Uma Thurman" }],
    coverUrl: "/movies/kill_bill_vol_2.jpg",
    releaseDate: "2004-04-16",
    rating: 0,
    length: 137,
    genre: "Action",
  },
  {
    title: "Hellboy",
    director: "Guillermo del Toro",
    actors: [{ name: "Ron Perlman" }],
    coverUrl: "/movies/hellboy.jpg",
    releaseDate: "2004-04-02",
    rating: 0,
    length: 122,
    genre: "Action",
  },
  {
    title: "Shaun of the Dead",
    director: "Edgar Wright",
    actors: [{ name: "Simon Pegg" }],
    coverUrl: "/movies/shaun_dead.jpg",
    releaseDate: "2004-04-09",
    rating: 0,
    length: 99,
    genre: "Comedy",
  },
  {
    title: "Scooby-Doo 2: Monsters Unleashed",
    director: "Raja Gosnell",
    actors: [{ name: "Freddie Prinze Jr." }],
    coverUrl: "/movies/scooby_doo_2.jpg",
    releaseDate: "2004-03-26",
    rating: 0,
    length: 93,
    genre: "Comedy",
  },
  {
    title: "The Chorus",
    director: "Christophe Barratier",
    actors: [{ name: "Gérard Jugnot" }],
    coverUrl: "/movies/chorus.jpg",
    releaseDate: "2004-03-17",
    rating: 0,
    length: 97,
    genre: "Drama",
  },
  {
    title: "Eternal Sunshine of the Spotless Mind",
    director: "Michel Gondry",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/eternal_sunshine.jpg",
    releaseDate: "2004-03-19",
    rating: 0,
    length: 108,
    genre: "Romance",
  },
  {
    title: "EuroTrip",
    director: "Jeff Schaffer",
    actors: [{ name: "Scott Mechlowicz" }],
    coverUrl: "/movies/eurotrip.jpg",
    releaseDate: "2004-02-20",
    rating: 0,
    length: 93,
    genre: "Comedy",
  },
  {
    title: "The Girl Next Door",
    director: "Luke Greenfield",
    actors: [{ name: "Emile Hirsch" }],
    coverUrl: "/movies/girl_next_door.jpg",
    releaseDate: "2004-04-09",
    rating: 0,
    length: 109,
    genre: "Comedy",
  },
  {
    title: "50 First Dates",
    director: "Peter Segal",
    actors: [{ name: "Adam Sandler" }],
    coverUrl: "/movies/50_first_dates.jpg",
    releaseDate: "2004-02-13",
    rating: 0,
    length: 99,
    genre: "Comedy",
  },
  {
    title: "The 11 Commandments",
    director: "François Desagnat, Thomas Sorriaux",
    actors: [{ name: "François Desagnat" }],
    coverUrl: "/movies/11_commandments.jpg",
    releaseDate: "2004-02-11",
    rating: 0,
    length: 90,
    genre: "Comedy",
  },
  {
    title: "RRRrrrr!!!",
    director: "Alain Chabat",
    actors: [{ name: "Marion Cotillard" }],
    coverUrl: "/movies/rrrrrrr.jpg",
    releaseDate: "2004-01-28",
    rating: 0,
    length: 94,
    genre: "Comedy",
  },
  {
    title: "Saw",
    director: "James Wan",
    actors: [{ name: "Cary Elwes" }],
    coverUrl: "/movies/saw.jpg",
    releaseDate: "2004-10-29",
    rating: 0,
    length: 103,
    genre: "Horror",
  },
  {
    title: "The Butterfly Effect",
    director: "Eric Bress, J. Mackye Gruber",
    actors: [{ name: "Ashton Kutcher" }],
    coverUrl: "/movies/butterfly_effect.jpg",
    releaseDate: "2004-01-23",
    rating: 0,
    length: 113,
    genre: "Science Fiction",
  },
  {
    title: "Oldboy",
    director: "Park Chan-wook",
    actors: [{ name: "Choi Min-sik" }],
    coverUrl: "/movies/oldboy.jpg",
    releaseDate: "2003-11-21",
    rating: 0,
    length: 120,
    genre: "Thriller",
  },
  {
    title: "The Matrix Revolutions",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/matrix_revolutions.jpg",
    releaseDate: "2003-11-05",
    rating: 0,
    length: 129,
    genre: "Science Fiction",
  },
  {
    title: "Scary Movie 3",
    director: "David Zucker",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/scary_movie_3.jpg",
    releaseDate: "2003-10-24",
    rating: 0,
    length: 84,
    genre: "Comedy",
  },
  {
    title: "Kill Bill: Vol. 1",
    director: "Quentin Tarantino",
    actors: [{ name: "Uma Thurman" }],
    coverUrl: "/movies/kill_bill_vol_1.jpg",
    releaseDate: "2003-10-10",
    rating: 0,
    length: 111,
    genre: "Action",
  },
  {
    title: "Underworld",
    director: "Len Wiseman",
    actors: [{ name: "Kate Beckinsale" }],
    coverUrl: "/movies/underworld.jpg",
    releaseDate: "2003-09-19",
    rating: 0,
    length: 121,
    genre: "Action",
  },
  {
    title: "Love Actually",
    director: "Richard Curtis",
    actors: [{ name: "Hugh Grant" }],
    coverUrl: "/movies/love_actually.jpg",
    releaseDate: "2003-11-07",
    rating: 0,
    length: 135,
    genre: "Romance",
  },
  {
    title: "Spy Kids 3-D: Game Over",
    director: "Robert Rodriguez",
    actors: [{ name: "Alexa Vega" }],
    coverUrl: "/movies/spy_kids_3d.jpg",
    releaseDate: "2003-07-25",
    rating: 0,
    length: 84,
    genre: "Adventure",
  },
  {
    title: "American Wedding",
    director: "Jesse Dylan",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies/american_wedding.jpg",
    releaseDate: "2003-08-01",
    rating: 0,
    length: 96,
    genre: "Comedy",
  },
  {
    title: "Bad Boys II",
    director: "Michael Bay",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/bad_boys_2.jpg",
    releaseDate: "2003-07-18",
    rating: 0,
    length: 147,
    genre: "Action",
  },
  {
    title: "Terminator 3: Rise of the Machines",
    director: "Jonathan Mostow",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/terminator_3.jpg",
    releaseDate: "2003-07-02",
    rating: 0,
    length: 109,
    genre: "Action",
  },
  {
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    director: "Gore Verbinski",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/pirates_black_pearl.jpg",
    releaseDate: "2003-07-09",
    rating: 0,
    length: 143,
    genre: "Adventure",
  },
  {
    title: "Hulk",
    director: "Ang Lee",
    actors: [{ name: "Eric Bana" }],
    coverUrl: "/movies/hulk.jpg",
    releaseDate: "2003-06-20",
    rating: 0,
    length: 138,
    genre: "Action",
  },
  {
    title: "2 Fast 2 Furious",
    director: "John Singleton",
    actors: [{ name: "Paul Walker" }],
    coverUrl: "/movies/2_fast_2_furious.jpg",
    releaseDate: "2003-06-06",
    rating: 0,
    length: 107,
    genre: "Action",
  },
  {
    title: "Finding Nemo",
    director: "Andrew Stanton",
    actors: [{ name: "Albert Brooks" }],
    coverUrl: "/movies/finding_nemo.jpg",
    releaseDate: "2003-05-30",
    rating: 0,
    length: 100,
    genre: "Animation",
  },
  {
    title: "Bruce Almighty",
    director: "Tom Shadyac",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/bruce_almighty.jpg",
    releaseDate: "2003-05-23",
    rating: 0,
    length: 101,
    genre: "Comedy",
  },
  {
    title: "The Matrix Reloaded",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/matrix_reloaded.jpg",
    releaseDate: "2003-05-15",
    rating: 0,
    length: 138,
    genre: "Science Fiction",
  },
  {
    title: "X2",
    director: "Bryan Singer",
    actors: [{ name: "Patrick Stewart" }],
    coverUrl: "/movies/x2.jpg",
    releaseDate: "2003-05-02",
    rating: 0,
    length: 134,
    genre: "Action",
  },
  {
    title: "I, Cesar",
    director: "Richard Berry",
    actors: [{ name: "Richard Berry" }],
    coverUrl: "/movies/i_cesar.jpg",
    releaseDate: "2003-04-30",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Cradle 2 the Grave",
    director: "Andrzej Bartkowiak",
    actors: [{ name: "Jet Li" }],
    coverUrl: "/movies/cradle_2_grave.jpg",
    releaseDate: "2003-02-28",
    rating: 0,
    length: 101,
    genre: "Action",
  },
  {
    title: "Daredevil",
    director: "Mark Steven Johnson",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies/daredevil.jpg",
    releaseDate: "2003-02-14",
    rating: 0,
    length: 103,
    genre: "Action",
  },
  {
    title: "The Dope",
    director: "Éric Rochant",
    actors: [{ name: "Vincent Lindon" }],
    coverUrl: "/movies/dope.jpg",
    releaseDate: "2003-02-05",
    rating: 0,
    length: 95,
    genre: "Drama",
  },
  {
    title: "Final Destination 2",
    director: "David R. Ellis",
    actors: [{ name: "A.J. Cook" }],
    coverUrl: "/movies/final_destination_2.jpg",
    releaseDate: "2003-01-31",
    rating: 0,
    length: 90,
    genre: "Horror",
  },
  {
    title: "Taxi 3",
    director: "Gérard Krawczyk",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies/taxi_3.jpg",
    releaseDate: "2003-01-29",
    rating: 0,
    length: 84,
    genre: "Action",
  },
  {
    title: "Ong Bak",
    director: "Prachya Pinkaew",
    actors: [{ name: "Tony Jaa" }],
    coverUrl: "/movies/ong_bak.jpg",
    releaseDate: "2003-01-21",
    rating: 0,
    length: 108,
    genre: "Action",
  },
  {
    title: "Catch Me If You Can",
    director: "Steven Spielberg",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/catch_me_if_you_can.jpg",
    releaseDate: "2002-12-25",
    rating: 0,
    length: 141,
    genre: "Crime",
  },
  {
    title: "Equilibrium",
    director: "Kurt Wimmer",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/equilibrium.jpg",
    releaseDate: "2002-12-06",
    rating: 0,
    length: 107,
    genre: "Science Fiction",
  },
  {
    title: "Die Another Day",
    director: "Lee Tamahori",
    actors: [{ name: "Pierce Brosnan" }],
    coverUrl: "/movies/die_another_day.jpg",
    releaseDate: "2002-11-22",
    rating: 0,
    length: 133,
    genre: "Action",
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    director: "Chris Columbus",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_chamber_secrets.jpg",
    releaseDate: "2002-11-15",
    rating: 0,
    length: 161,
    genre: "Fantasy",
  },
  {
    title: "Cheats",
    director: "Andrew Gurland",
    actors: [{ name: "Trevor Fehrman" }],
    coverUrl: "/movies/cheats.jpg",
    releaseDate: "2002-09-13",
    rating: 0,
    length: 85,
    genre: "Comedy",
  },
  {
    title: "28 Days Later",
    director: "Danny Boyle",
    actors: [{ name: "Cillian Murphy" }],
    coverUrl: "/movies/28_days_later.jpg",
    releaseDate: "2002-11-01",
    rating: 0,
    length: 113,
    genre: "Horror",
  },
  {
    title: "The Transporter",
    director: "Louis Leterrier, Corey Yuen",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/transporter.jpg",
    releaseDate: "2002-10-11",
    rating: 0,
    length: 92,
    genre: "Action",
  },
  {
    title: "The Ring",
    director: "Gore Verbinski",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies/ring.jpg",
    releaseDate: "2002-10-18",
    rating: 0,
    length: 115,
    genre: "Horror",
  },
  {
    title: "Phone Booth",
    director: "Joel Schumacher",
    actors: [{ name: "Colin Farrell" }],
    coverUrl: "/movies/phone_booth.jpg",
    releaseDate: "2002-09-10",
    rating: 0,
    length: 81,
    genre: "Thriller",
  },
  {
    title: "xXx",
    director: "Rob Cohen",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/xxx.jpg",
    releaseDate: "2002-08-09",
    rating: 0,
    length: 124,
    genre: "Action",
  },
  {
    title: "Spy Kids 2: The Island of Lost Dreams",
    director: "Robert Rodriguez",
    actors: [{ name: "Alexa Vega" }],
    coverUrl: "/movies/spy_kids_2.jpg",
    releaseDate: "2002-08-07",
    rating: 0,
    length: 100,
    genre: "Adventure",
  },
  {
    title: "Men in Black II",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/men_in_black_2.jpg",
    releaseDate: "2002-07-03",
    rating: 0,
    length: 88,
    genre: "Action",
  },
  {
    title: "Minority Report",
    director: "Steven Spielberg",
    actors: [{ name: "Tom Cruise" }],
    coverUrl: "/movies/minority_report.jpg",
    releaseDate: "2002-06-21",
    rating: 0,
    length: 145,
    genre: "Science Fiction",
  },
  {
    title: "Scooby-Doo",
    director: "Raja Gosnell",
    actors: [{ name: "Freddie Prinze Jr." }],
    coverUrl: "/movies/scooby_doo.jpg",
    releaseDate: "2002-06-14",
    rating: 0,
    length: 86,
    genre: "Comedy",
  },
  {
    title: "The Bourne Identity",
    director: "Doug Liman",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/bourne_identity.jpg",
    releaseDate: "2002-06-14",
    rating: 0,
    length: 119,
    genre: "Action",
  },
  {
    title: "Star Wars: Episode II – Attack of the Clones",
    director: "George Lucas",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies/star_wars_attack_clones.jpg",
    releaseDate: "2002-05-16",
    rating: 0,
    length: 142,
    genre: "Science Fiction",
  },
  {
    title: "Spider-Man",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies/spiderman.jpg",
    releaseDate: "2002-05-03",
    rating: 0,
    length: 121,
    genre: "Action",
  },
  {
    title: "Murder by Numbers",
    director: "Barbet Schroeder",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/murder_by_numbers.jpg",
    releaseDate: "2002-04-19",
    rating: 0,
    length: 120,
    genre: "Thriller",
  },
  {
    title: "Blade II",
    director: "Guillermo del Toro",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies/blade_2.jpg",
    releaseDate: "2002-03-22",
    rating: 0,
    length: 117,
    genre: "Action",
  },
  {
    title: "Panic Room",
    director: "David Fincher",
    actors: [{ name: "Jodie Foster" }],
    coverUrl: "/movies/panic_room.jpg",
    releaseDate: "2002-03-29",
    rating: 0,
    length: 112,
    genre: "Thriller",
  },
  {
    title: "Resident Evil",
    director: "Paul W.S. Anderson",
    actors: [{ name: "Milla Jovovich" }],
    coverUrl: "/movies/resident_evil.jpg",
    releaseDate: "2002-03-15",
    rating: 0,
    length: 100,
    genre: "Action",
  },
  {
    title: "Ice Age",
    director: "Chris Wedge, Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies/ice_age.jpg",
    releaseDate: "2002-03-15",
    rating: 0,
    length: 81,
    genre: "Animation",
  },
  {
    title: "Rollerball",
    director: "John McTiernan",
    actors: [{ name: "Chris Klein" }],
    coverUrl: "/movies/rollerball.jpg",
    releaseDate: "2002-02-08",
    rating: 0,
    length: 98,
    genre: "Action",
  },
  {
    title: "Collateral Damage",
    director: "Andrew Davis",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/collateral_damage.jpg",
    releaseDate: "2002-02-08",
    rating: 0,
    length: 108,
    genre: "Action",
  },
  {
    title: "Asterix & Obelix: Mission Cleopatra",
    director: "Alain Chabat",
    actors: [{ name: "Gérard Depardieu" }],
    coverUrl: "/movies/asterix_obelix_cleopatra.jpg",
    releaseDate: "2002-01-30",
    rating: 0,
    length: 107,
    genre: "Comedy",
  },
  {
    title: "A Walk to Remember",
    director: "Adam Shankman",
    actors: [{ name: "Mandy Moore" }],
    coverUrl: "/movies/walk_remember.jpg",
    releaseDate: "2002-01-25",
    rating: 0,
    length: 101,
    genre: "Romance",
  },
];