import { Movie } from "./movies";

export const moviesPage5: Movie[] = [
  {
    title: "Harry Potter and the Deathly Hallows: Part 2",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_deathly_hallows_2.jpg",
    releaseDate: "2011-07-15",
    rating: 0,
    length: 130,
    genre: "Fantasy",
  },
  {
    title: "The Tuche Family",
    director: "Olivier Baroux",
    actors: [{ name: "Jean-Paul Rouve" }],
    coverUrl: "/movies/tuche_family.jpg",
    releaseDate: "2011-06-29",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Horrible Bosses",
    director: "Seth Gordon",
    actors: [{ name: "Jason Bateman" }],
    coverUrl: "/movies/horrible_bosses.jpg",
    releaseDate: "2011-07-08",
    rating: 0,
    length: 98,
    genre: "Comedy",
  },
  {
    title: "Transformers: Dark of the Moon",
    director: "Michael Bay",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies/transformers_dark_moon.jpg",
    releaseDate: "2011-06-29",
    rating: 0,
    length: 154,
    genre: "Action",
  },
  {
    title: "Green Lantern",
    director: "Martin Campbell",
    actors: [{ name: "Ryan Reynolds" }],
    coverUrl: "/movies/green_lantern.jpg",
    releaseDate: "2011-06-17",
    rating: 0,
    length: 114,
    genre: "Action",
  },
  {
    title: "Super 8",
    director: "J.J. Abrams",
    actors: [{ name: "Joel Courtney" }],
    coverUrl: "/movies/super_8.jpg",
    releaseDate: "2011-06-10",
    rating: 0,
    length: 112,
    genre: "Science Fiction",
  },
  {
    title: "X-Men: First Class",
    director: "Matthew Vaughn",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies/xmen_first_class.jpg",
    releaseDate: "2011-06-03",
    rating: 0,
    length: 132,
    genre: "Action",
  },
  {
    title: "Drive",
    director: "Nicolas Winding Refn",
    actors: [{ name: "Ryan Gosling" }],
    coverUrl: "/movies/drive.jpg",
    releaseDate: "2011-09-16",
    rating: 0,
    length: 100,
    genre: "Crime",
  },
  {
    title: "The Hangover Part II",
    director: "Todd Phillips",
    actors: [{ name: "Bradley Cooper" }],
    coverUrl: "/movies/hangover_2.jpg",
    releaseDate: "2011-05-26",
    rating: 0,
    length: 102,
    genre: "Comedy",
  },
  {
    title: "The Artist",
    director: "Michel Hazanavicius",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies/artist.jpg",
    releaseDate: "2011-11-23",
    rating: 0,
    length: 100,
    genre: "Drama",
  },
  {
    title: "Pirates of the Caribbean: On Stranger Tides",
    director: "Rob Marshall",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/pirates_stranger_tides.jpg",
    releaseDate: "2011-05-20",
    rating: 0,
    length: 136,
    genre: "Adventure",
  },
  {
    title: "Thor",
    director: "Kenneth Branagh",
    actors: [{ name: "Chris Hemsworth" }],
    coverUrl: "/movies/thor.jpg",
    releaseDate: "2011-05-06",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "Fast Five",
    director: "Justin Lin",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/fast_five.jpg",
    releaseDate: "2011-04-29",
    rating: 0,
    length: 130,
    genre: "Action",
  },
  {
    title: "Scream 4",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies/scream_4.jpg",
    releaseDate: "2011-04-15",
    rating: 0,
    length: 111,
    genre: "Horror",
  },
  {
    title: "Sucker Punch",
    director: "Zack Snyder",
    actors: [{ name: "Emily Browning" }],
    coverUrl: "/movies/sucker_punch.jpg",
    releaseDate: "2011-03-25",
    rating: 0,
    length: 110,
    genre: "Action",
  },
  {
    title: "The Adjustment Bureau",
    director: "George Nolfi",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/adjustment_bureau.jpg",
    releaseDate: "2011-03-04",
    rating: 0,
    length: 106,
    genre: "Science Fiction",
  },
  {
    title: "One Day",
    director: "Lone Scherfig",
    actors: [{ name: "Anne Hathaway" }],
    coverUrl: "/movies/one_day.jpg",
    releaseDate: "2011-08-19",
    rating: 0,
    length: 107,
    genre: "Romance",
  },
  {
    title: "Paul",
    director: "Greg Mottola",
    actors: [{ name: "Simon Pegg" }],
    coverUrl: "/movies/paul.jpg",
    releaseDate: "2011-03-18",
    rating: 0,
    length: 104,
    genre: "Comedy",
  },
  {
    title: "No Strings Attached",
    director: "Ivan Reitman",
    actors: [{ name: "Natalie Portman" }],
    coverUrl: "/movies/no_strings_attached.jpg",
    releaseDate: "2011-01-21",
    rating: 0,
    length: 108,
    genre: "Romance",
  },
  {
    title: "Harry Potter and the Deathly Hallows: Part 1",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_deathly_hallows_1.jpg",
    releaseDate: "2010-11-19",
    rating: 0,
    length: 146,
    genre: "Fantasy",
  },
  {
    title: "Love & Other Drugs",
    director: "Edward Zwick",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies/love_other_drugs.jpg",
    releaseDate: "2010-11-24",
    rating: 0,
    length: 112,
    genre: "Romance",
  },
  {
    title: "Megamind",
    director: "Tom McGrath",
    actors: [{ name: "Will Ferrell" }],
    coverUrl: "/movies/megamind.jpg",
    releaseDate: "2010-11-05",
    rating: 0,
    length: 95,
    genre: "Animation",
  },
  {
    title: "RED",
    director: "Robert Schwentke",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/red.jpg",
    releaseDate: "2010-10-15",
    rating: 0,
    length: 111,
    genre: "Action",
  },
  {
    title: "The Social Network",
    director: "David Fincher",
    actors: [{ name: "Jesse Eisenberg" }],
    coverUrl: "/movies/social_network.jpg",
    releaseDate: "2010-10-01",
    rating: 0,
    length: 120,
    genre: "Drama",
  },
  {
    title: "127 Hours",
    director: "Danny Boyle",
    actors: [{ name: "James Franco" }],
    coverUrl: "/movies/127_hours.jpg",
    releaseDate: "2010-11-05",
    rating: 0,
    length: 94,
    genre: "Drama",
  },
  {
    title: "Black Swan",
    director: "Darren Aronofsky",
    actors: [{ name: "Natalie Portman" }],
    coverUrl: "/movies/black_swan.jpg",
    releaseDate: "2010-12-03",
    rating: 0,
    length: 108,
    genre: "Drama",
  },
  {
    title: "Arthur 3: The War of the Two Worlds",
    director: "Luc Besson",
    actors: [{ name: "Freddie Highmore" }],
    coverUrl: "/movies/arthur_3.jpg",
    releaseDate: "2010-10-13",
    rating: 0,
    length: 101,
    genre: "Adventure",
  },
  {
    title: "The Expendables",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/expendables.jpg",
    releaseDate: "2010-08-13",
    rating: 0,
    length: 103,
    genre: "Action",
  },
  {
    title: "Step Up 3D",
    director: "Jon M. Chu",
    actors: [{ name: "Rick Malambri" }],
    coverUrl: "/movies/step_up_3d.jpg",
    releaseDate: "2010-08-06",
    rating: 0,
    length: 107,
    genre: "Drama",
  },
  {
    title: "Inception",
    director: "Christopher Nolan",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/inception.jpg",
    releaseDate: "2010-07-16",
    rating: 0,
    length: 148,
    genre: "Science Fiction",
  },
  {
    title: "Predators",
    director: "Nimród Antal",
    actors: [{ name: "Adrien Brody" }],
    coverUrl: "/movies/predators.jpg",
    releaseDate: "2010-07-09",
    rating: 0,
    length: 107,
    genre: "Action",
  },
  {
    title: "The Twilight Saga: Eclipse",
    director: "David Slade",
    actors: [{ name: "Kristen Stewart" }],
    coverUrl: "/movies/twilight_eclipse.jpg",
    releaseDate: "2010-06-30",
    rating: 0,
    length: 124,
    genre: "Fantasy",
  },
  {
    title: "Fatal",
    director: "Michaël Youn",
    actors: [{ name: "Michaël Youn" }],
    coverUrl: "/movies/fatal.jpg",
    releaseDate: "2010-06-30",
    rating: 0,
    length: 85,
    genre: "Comedy",
  },
  {
    title: "Toy Story 3",
    director: "Lee Unkrich",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/toy_story_3.jpg",
    releaseDate: "2010-06-18",
    rating: 0,
    length: 103,
    genre: "Animation",
  },
  {
    title: "The Karate Kid",
    director: "Harald Zwart",
    actors: [{ name: "Jaden Smith" }],
    coverUrl: "/movies/karate_kid.jpg",
    releaseDate: "2010-06-11",
    rating: 0,
    length: 140,
    genre: "Action",
  },
  {
    title: "Despicable Me",
    director: "Pierre Coffin, Chris Renaud",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies/despicable_me.jpg",
    releaseDate: "2010-07-09",
    rating: 0,
    length: 95,
    genre: "Animation",
  },
  {
    title: "Shrek Forever After",
    director: "Mike Mitchell",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies/shrek_forever_after.jpg",
    releaseDate: "2010-05-21",
    rating: 0,
    length: 93,
    genre: "Animation",
  },
  {
    title: "Iron Man 2",
    director: "Jon Favreau",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/iron_man_2.jpg",
    releaseDate: "2010-05-07",
    rating: 0,
    length: 124,
    genre: "Action",
  },
  {
    title: "Clash of the Titans",
    director: "Louis Leterrier",
    actors: [{ name: "Sam Worthington" }],
    coverUrl: "/movies/clash_titans.jpg",
    releaseDate: "2010-04-02",
    rating: 0,
    length: 106,
    genre: "Action",
  },
  {
    title: "How to Train Your Dragon",
    director: "Dean DeBlois, Chris Sanders",
    actors: [{ name: "Jay Baruchel" }],
    coverUrl: "/movies/how_to_train_dragon.jpg",
    releaseDate: "2010-03-26",
    rating: 0,
    length: 98,
    genre: "Animation",
  },
  {
    title: "Heartbreaker",
    director: "Pascal Chaumeil",
    actors: [{ name: "Romain Duris" }],
    coverUrl: "/movies/heartbreaker.jpg",
    releaseDate: "2010-03-17",
    rating: 0,
    length: 105,
    genre: "Romance",
  },
  {
    title: "Kick-Ass",
    director: "Matthew Vaughn",
    actors: [{ name: "Aaron Taylor-Johnson" }],
    coverUrl: "/movies/kick_ass.jpg",
    releaseDate: "2010-04-16",
    rating: 0,
    length: 117,
    genre: "Action",
  },
  {
    title: "Remember Me",
    director: "Allen Coulter",
    actors: [{ name: "Robert Pattinson" }],
    coverUrl: "/movies/remember_me.jpg",
    releaseDate: "2010-03-12",
    rating: 0,
    length: 113,
    genre: "Drama",
  },
  {
    title: "Alice in Wonderland",
    director: "Tim Burton",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/alice_wonderland.jpg",
    releaseDate: "2010-03-05",
    rating: 0,
    length: 108,
    genre: "Fantasy",
  },
  {
    title: "Shutter Island",
    director: "Martin Scorsese",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/shutter_island.jpg",
    releaseDate: "2010-02-19",
    rating: 0,
    length: 138,
    genre: "Thriller",
  },
  {
    title: "Valentine's Day",
    director: "Garry Marshall",
    actors: [{ name: "Julia Roberts" }],
    coverUrl: "/movies/valentines_day.jpg",
    releaseDate: "2010-02-12",
    rating: 0,
    length: 125,
    genre: "Romance",
  },
  {
    title: "Percy Jackson & the Olympians: The Lightning Thief",
    director: "Chris Columbus",
    actors: [{ name: "Logan Lerman" }],
    coverUrl: "/movies/percy_jackson.jpg",
    releaseDate: "2010-02-12",
    rating: 0,
    length: 118,
    genre: "Fantasy",
  },
  {
    title: "Avatar",
    director: "James Cameron",
    actors: [{ name: "Sam Worthington" }],
    coverUrl: "/movies/avatar.jpg",
    releaseDate: "2009-12-18",
    rating: 0,
    length: 162,
    genre: "Science Fiction",
  },
  {
    title: "The Princess and the Frog",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Anika Noni Rose" }],
    coverUrl: "/movies/princess_frog.jpg",
    releaseDate: "2009-12-11",
    rating: 0,
    length: 97,
    genre: "Animation",
  },
  {
    title: "American Pie Presents: The Book of Love",
    director: "John Putch",
    actors: [{ name: "Bug Hall" }],
    coverUrl: "/movies/american_pie_book_love.jpg",
    releaseDate: "2009-12-22",
    rating: 0,
    length: 93,
    genre: "Comedy",
  },
  {
    title: "Arthur and the Revenge of Maltazard",
    director: "Luc Besson",
    actors: [{ name: "Freddie Highmore" }],
    coverUrl: "/movies/arthur_revenge_maltazard.jpg",
    releaseDate: "2009-12-02",
    rating: 0,
    length: 94,
    genre: "Adventure",
  },
  {
    title: "Brothers",
    director: "Jim Sheridan",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies/brothers.jpg",
    releaseDate: "2009-12-04",
    rating: 0,
    length: 105,
    genre: "Drama",
  },
  {
    title: "The Twilight Saga: New Moon",
    director: "Chris Weitz",
    actors: [{ name: "Kristen Stewart" }],
    coverUrl: "/movies/twilight_new_moon.jpg",
    releaseDate: "2009-11-20",
    rating: 0,
    length: 130,
    genre: "Fantasy",
  },
  {
    title: "Lucky Luke",
    director: "James Huth",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies/lucky_luke.jpg",
    releaseDate: "2009-10-21",
    rating: 0,
    length: 103,
    genre: "Comedy",
  },
  {
    title: "The Stepfather",
    director: "Nelson McCormick",
    actors: [{ name: "Dylan Walsh" }],
    coverUrl: "/movies/stepfather.jpg",
    releaseDate: "2009-10-16",
    rating: 0,
    length: 101,
    genre: "Thriller",
  },
  {
    title: "2012",
    director: "Roland Emmerich",
    actors: [{ name: "John Cusack" }],
    coverUrl: "/movies/2012.jpg",
    releaseDate: "2009-11-13",
    rating: 0,
    length: 158,
    genre: "Action",
  },
  {
    title: "Zombieland",
    director: "Ruben Fleischer",
    actors: [{ name: "Jesse Eisenberg" }],
    coverUrl: "/movies/zombieland.jpg",
    releaseDate: "2009-10-02",
    rating: 0,
    length: 88,
    genre: "Comedy",
  },
  {
    title: "The Blind Side",
    director: "John Lee Hancock",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/blind_side.jpg",
    releaseDate: "2009-11-20",
    rating: 0,
    length: 129,
    genre: "Drama",
  },
  {
    title: "Mr. Nobody",
    director: "Jaco Van Dormael",
    actors: [{ name: "Jared Leto" }],
    coverUrl: "/movies/mr_nobody.jpg",
    releaseDate: "2009-09-12",
    rating: 0,
    length: 141,
    genre: "Science Fiction",
  },
  {
    title: "Cloudy with a Chance of Meatballs",
    director: "Phil Lord, Christopher Miller",
    actors: [{ name: "Bill Hader" }],
    coverUrl: "/movies/cloudy_meatballs.jpg",
    releaseDate: "2009-09-18",
    rating: 0,
    length: 90,
    genre: "Animation",
  },
  {
    title: "Coco",
    director: "Lee Unkrich",
    actors: [{ name: "Anthony Gonzalez" }],
    coverUrl: "/movies/coco.jpg",
    releaseDate: "2017-11-22",
    rating: 0,
    length: 105,
    genre: "Animation",
  },
  {
    title: "Harry Potter and the Half-Blood Prince",
    director: "David Yates",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_half_blood_prince.jpg",
    releaseDate: "2009-07-15",
    rating: 0,
    length: 153,
    genre: "Fantasy",
  },
  {
    title: "Ice Age: Dawn of the Dinosaurs",
    director: "Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies/ice_age_dawn_dinosaurs.jpg",
    releaseDate: "2009-07-01",
    rating: 0,
    length: 94,
    genre: "Animation",
  },
  {
    title: "Transformers: Revenge of the Fallen",
    director: "Michael Bay",
    actors: [{ name: "Shia LaBeouf" }],
    coverUrl: "/movies/transformers_revenge_fallen.jpg",
    releaseDate: "2009-06-24",
    rating: 0,
    length: 150,
    genre: "Action",
  },
  {
    title: "The Proposal",
    director: "Anne Fletcher",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/proposal.jpg",
    releaseDate: "2009-06-19",
    rating: 0,
    length: 108,
    genre: "Romance",
  },
  {
    title: "The Hangover",
    director: "Todd Phillips",
    actors: [{ name: "Bradley Cooper" }],
    coverUrl: "/movies/hangover.jpg",
    releaseDate: "2009-06-05",
    rating: 0,
    length: 100,
    genre: "Comedy",
  },
  {
    title: "The Final Destination",
    director: "David R. Ellis",
    actors: [{ name: "Bobby Campo" }],
    coverUrl: "/movies/final_destination.jpg",
    releaseDate: "2009-08-28",
    rating: 0,
    length: 82,
    genre: "Horror",
  },
  {
    title: "Night at the Museum: Battle of the Smithsonian",
    director: "Shawn Levy",
    actors: [{ name: "Ben Stiller" }],
    coverUrl: "/movies/night_museum_2.jpg",
    releaseDate: "2009-05-22",
    rating: 0,
    length: 105,
    genre: "Adventure",
  },
  {
    title: "Inglourious Basterds",
    director: "Quentin Tarantino",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/inglourious_basterds.jpg",
    releaseDate: "2009-08-21",
    rating: 0,
    length: 153,
    genre: "War",
  },
  {
    title: "Terminator Salvation",
    director: "McG",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/terminator_salvation.jpg",
    releaseDate: "2009-05-21",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "X-Men Origins: Wolverine",
    director: "Gavin Hood",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/xmen_origins_wolverine.jpg",
    releaseDate: "2009-05-01",
    rating: 0,
    length: 107,
    genre: "Action",
  },
  {
    title: "Crank: High Voltage",
    director: "Neveldine/Taylor",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/crank_high_voltage.jpg",
    releaseDate: "2009-04-17",
    rating: 0,
    length: 96,
    genre: "Action",
  },
];