import { Movie } from "./movies";

export const moviesPage7: Movie[] = [
  {
    title: "Rocky Balboa",
    director: "Sylvester Stallone",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/rocky_balboa.jpg",
    releaseDate: "2006-12-20",
    rating: 0,
    length: 102,
    genre: "Drama",
  },
  {
    title: "Night at the Museum",
    director: "Shawn Levy",
    actors: [{ name: "Ben Stiller" }],
    coverUrl: "/movies/night_museum.jpg",
    releaseDate: "2006-12-22",
    rating: 0,
    length: 108,
    genre: "Comedy",
  },
  {
    title: "The Pursuit of Happyness",
    director: "Gabriele Muccino",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/pursuit_happyness.jpg",
    releaseDate: "2006-12-15",
    rating: 0,
    length: 117,
    genre: "Drama",
  },
  {
    title: "Arthur and the Invisibles",
    director: "Luc Besson",
    actors: [{ name: "Freddie Highmore" }],
    coverUrl: "/movies/arthur_invisibles.jpg",
    releaseDate: "2006-12-13",
    rating: 0,
    length: 94,
    genre: "Fantasy",
  },
  {
    title: "Priceless",
    director: "Pierre Salvadori",
    actors: [{ name: "Audrey Tautou" }],
    coverUrl: "/movies/priceless.jpg",
    releaseDate: "2006-12-27",
    rating: 0,
    length: 104,
    genre: "Comedy",
  },
  {
    title: "300",
    director: "Zack Snyder",
    actors: [{ name: "Gerard Butler" }],
    coverUrl: "/movies/300.jpg",
    releaseDate: "2007-03-09",
    rating: 0,
    length: 117,
    genre: "Action",
  },
  {
    title: "Blood Diamond",
    director: "Edward Zwick",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/blood_diamond.jpg",
    releaseDate: "2006-12-08",
    rating: 0,
    length: 143,
    genre: "Drama",
  },
  {
    title: "American Pie Presents: The Naked Mile",
    director: "Joe Nussbaum",
    actors: [{ name: "John White" }],
    coverUrl: "/movies/american_pie_naked_mile.jpg",
    releaseDate: "2006-12-19",
    rating: 0,
    length: 97,
    genre: "Comedy",
  },
  {
    title: "Casino Royale",
    director: "Martin Campbell",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies/casino_royale.jpg",
    releaseDate: "2006-11-17",
    rating: 0,
    length: 144,
    genre: "Action",
  },
  {
    title: "The Prestige",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/prestige.jpg",
    releaseDate: "2006-10-20",
    rating: 0,
    length: 130,
    genre: "Thriller",
  },
  {
    title: "Death Note",
    director: "Shusuke Kaneko",
    actors: [{ name: "Tatsuya Fujiwara" }],
    coverUrl: "/movies/death_note.jpg",
    releaseDate: "2006-06-17",
    rating: 0,
    length: 126,
    genre: "Thriller",
  },
  {
    title: "The Departed",
    director: "Martin Scorsese",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/departed.jpg",
    releaseDate: "2006-10-06",
    rating: 0,
    length: 151,
    genre: "Crime",
  },
  {
    title: "Accepted",
    director: "Steve Pink",
    actors: [{ name: "Justin Long" }],
    coverUrl: "/movies/accepted.jpg",
    releaseDate: "2006-08-18",
    rating: 0,
    length: 93,
    genre: "Comedy",
  },
  {
    title: "Step Up",
    director: "Anne Fletcher",
    actors: [{ name: "Channing Tatum" }],
    coverUrl: "/movies/step_up.jpg",
    releaseDate: "2006-08-11",
    rating: 0,
    length: 104,
    genre: "Drama",
  },
  {
    title: "Those Happy Days",
    director: "Claude Zidi Jr.",
    actors: [{ name: "Vincent Claude" }],
    coverUrl: "/movies/those_happy_days.jpg",
    releaseDate: "2006-07-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Pirates of the Caribbean: Dead Man's Chest",
    director: "Gore Verbinski",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/pirates_dead_mans_chest.jpg",
    releaseDate: "2006-07-07",
    rating: 0,
    length: 151,
    genre: "Adventure",
  },
  {
    title: "The Devil Wears Prada",
    director: "David Frankel",
    actors: [{ name: "Anne Hathaway" }],
    coverUrl: "/movies/devil_wears_prada.jpg",
    releaseDate: "2006-06-30",
    rating: 0,
    length: 109,
    genre: "Comedy",
  },
  {
    title: "The Fast and the Furious: Tokyo Drift",
    director: "Justin Lin",
    actors: [{ name: "Lucas Black" }],
    coverUrl: "/movies/fast_furious_tokyo_drift.jpg",
    releaseDate: "2006-06-16",
    rating: 0,
    length: 104,
    genre: "Action",
  },
  {
    title: "X-Men: The Last Stand",
    director: "Brett Ratner",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/xmen_last_stand.jpg",
    releaseDate: "2006-05-26",
    rating: 0,
    length: 104,
    genre: "Action",
  },
  {
    title: "Babel",
    director: "Alejandro González Iñárritu",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/babel.jpg",
    releaseDate: "2006-11-10",
    rating: 0,
    length: 143,
    genre: "Drama",
  },
  {
    title: "The Break-Up",
    director: "Peyton Reed",
    actors: [{ name: "Vince Vaughn" }],
    coverUrl: "/movies/break_up.jpg",
    releaseDate: "2006-06-02",
    rating: 0,
    length: 106,
    genre: "Comedy",
  },
  {
    title: "The Da Vinci Code",
    director: "Ron Howard",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/da_vinci_code.jpg",
    releaseDate: "2006-05-19",
    rating: 0,
    length: 149,
    genre: "Mystery",
  },
  {
    title: "Camping",
    director: "Fabien Onteniente",
    actors: [{ name: "Gérard Lanvin" }],
    coverUrl: "/movies/camping.jpg",
    releaseDate: "2006-04-26",
    rating: 0,
    length: 111,
    genre: "Comedy",
  },
  {
    title: "OSS 117: Cairo, Nest of Spies",
    director: "Michel Hazanavicius",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies/oss_117_cairo.jpg",
    releaseDate: "2006-04-19",
    rating: 0,
    length: 99,
    genre: "Comedy",
  },
  {
    title: "Scary Movie 4",
    director: "David Zucker",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/scary_movie_4.jpg",
    releaseDate: "2006-04-14",
    rating: 0,
    length: 83,
    genre: "Comedy",
  },
  {
    title: "Ice Age: The Meltdown",
    director: "Carlos Saldanha",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies/ice_age_meltdown.jpg",
    releaseDate: "2006-03-31",
    rating: 0,
    length: 91,
    genre: "Animation",
  },
  {
    title: "Cars",
    director: "John Lasseter",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies/cars.jpg",
    releaseDate: "2006-06-09",
    rating: 0,
    length: 117,
    genre: "Animation",
  },
  {
    title: "Volver",
    director: "Pedro Almodóvar",
    actors: [{ name: "Penélope Cruz" }],
    coverUrl: "/movies/volver.jpg",
    releaseDate: "2006-03-17",
    rating: 0,
    length: 121,
    genre: "Drama",
  },
  {
    title: "Final Destination 3",
    director: "James Wong",
    actors: [{ name: "Mary Elizabeth Winstead" }],
    coverUrl: "/movies/final_destination_3.jpg",
    releaseDate: "2006-02-10",
    rating: 0,
    length: 93,
    genre: "Horror",
  },
  {
    title: "Incontrôlable",
    director: "Raffy Shart",
    actors: [{ name: "Kad Merad" }],
    coverUrl: "/movies/incontrollable.jpg",
    releaseDate: "2006-02-01",
    rating: 0,
    length: 90,
    genre: "Comedy",
  },
  {
    title: "French Fried Vacations 3: Friends Forever",
    director: "Patrice Leconte",
    actors: [{ name: "Josiane Balasko" }],
    coverUrl: "/movies/french_fried_vacations_3.jpg",
    releaseDate: "2006-01-25",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Underworld: Evolution",
    director: "Len Wiseman",
    actors: [{ name: "Kate Beckinsale" }],
    coverUrl: "/movies/underworld_evolution.jpg",
    releaseDate: "2006-01-20",
    rating: 0,
    length: 106,
    genre: "Action",
  },
  {
    title: "V for Vendetta",
    director: "James McTeigue",
    actors: [{ name: "Hugo Weaving" }],
    coverUrl: "/movies/v_vendetta.jpg",
    releaseDate: "2006-03-17",
    rating: 0,
    length: 132,
    genre: "Action",
  },
  {
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    director: "Andrew Adamson",
    actors: [{ name: "Georgie Henley" }],
    coverUrl: "/movies/narnia_lion_witch_wardrobe.jpg",
    releaseDate: "2005-12-09",
    rating: 0,
    length: 143,
    genre: "Fantasy",
  },
  {
    title: "King Kong",
    director: "Peter Jackson",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies/king_kong.jpg",
    releaseDate: "2005-12-14",
    rating: 0,
    length: 187,
    genre: "Adventure",
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    director: "Mike Newell",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_goblet_fire.jpg",
    releaseDate: "2005-11-18",
    rating: 0,
    length: 157,
    genre: "Fantasy",
  },
  {
    title: "American Pie Presents: Band Camp",
    director: "Steve Rash",
    actors: [{ name: "Tad Hilgenbrink" }],
    coverUrl: "/movies/american_pie_band_camp.jpg",
    releaseDate: "2005-12-26",
    rating: 0,
    length: 97,
    genre: "Comedy",
  },
  {
    title: "Nanny McPhee",
    director: "Kirk Jones",
    actors: [{ name: "Emma Thompson" }],
    coverUrl: "/movies/nanny_mcphee.jpg",
    releaseDate: "2005-10-21",
    rating: 0,
    length: 97,
    genre: "Fantasy",
  },
  {
    title: "Lord of War",
    director: "Andrew Niccol",
    actors: [{ name: "Nicolas Cage" }],
    coverUrl: "/movies/lord_of_war.jpg",
    releaseDate: "2005-09-16",
    rating: 0,
    length: 122,
    genre: "Crime",
  },
  {
    title: "Pride & Prejudice",
    director: "Joe Wright",
    actors: [{ name: "Keira Knightley" }],
    coverUrl: "/movies/pride_prejudice.jpg",
    releaseDate: "2005-09-16",
    rating: 0,
    length: 129,
    genre: "Romance",
  },
  {
    title: "Serenity",
    director: "Joss Whedon",
    actors: [{ name: "Nathan Fillion" }],
    coverUrl: "/movies/serenity.jpg",
    releaseDate: "2005-09-30",
    rating: 0,
    length: 119,
    genre: "Science Fiction",
  },
  {
    title: "The Protector",
    director: "Prachya Pinkaew",
    actors: [{ name: "Tony Jaa" }],
    coverUrl: "/movies/protector.jpg",
    releaseDate: "2005-08-11",
    rating: 0,
    length: 110,
    genre: "Action",
  },
  {
    title: "The 40 Year Old Virgin",
    director: "Judd Apatow",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies/40_year_old_virgin.jpg",
    releaseDate: "2005-08-19",
    rating: 0,
    length: 116,
    genre: "Comedy",
  },
  {
    title: "Red Eye",
    director: "Wes Craven",
    actors: [{ name: "Rachel McAdams" }],
    coverUrl: "/movies/red_eye.jpg",
    releaseDate: "2005-08-19",
    rating: 0,
    length: 85,
    genre: "Thriller",
  },
  {
    title: "Transporter 2",
    director: "Louis Leterrier",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/transporter_2.jpg",
    releaseDate: "2005-09-02",
    rating: 0,
    length: 87,
    genre: "Action",
  },
  {
    title: "Sky High",
    director: "Mike Mitchell",
    actors: [{ name: "Michael Angarano" }],
    coverUrl: "/movies/sky_high.jpg",
    releaseDate: "2005-07-29",
    rating: 0,
    length: 100,
    genre: "Comedy",
  },
  {
    title: "Wedding Crashers",
    director: "David Dobkin",
    actors: [{ name: "Owen Wilson" }],
    coverUrl: "/movies/wedding_crashers.jpg",
    releaseDate: "2005-07-15",
    rating: 0,
    length: 119,
    genre: "Comedy",
  },
  {
    title: "Charlie and the Chocolate Factory",
    director: "Tim Burton",
    actors: [{ name: "Johnny Depp" }],
    coverUrl: "/movies/charlie_chocolate_factory.jpg",
    releaseDate: "2005-07-15",
    rating: 0,
    length: 115,
    genre: "Fantasy",
  },
  {
    title: "Fantastic Four",
    director: "Tim Story",
    actors: [{ name: "Ioan Gruffudd" }],
    coverUrl: "/movies/fantastic_four.jpg",
    releaseDate: "2005-07-08",
    rating: 0,
    length: 106,
    genre: "Action",
  },
  {
    title: "Mr. & Mrs. Smith",
    director: "Doug Liman",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/mr_mrs_smith.jpg",
    releaseDate: "2005-06-10",
    rating: 0,
    length: 120,
    genre: "Action",
  },
  {
    title: "Batman Begins",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/batman_begins.jpg",
    releaseDate: "2005-06-15",
    rating: 0,
    length: 140,
    genre: "Action",
  },
  {
    title: "Match Point",
    director: "Woody Allen",
    actors: [{ name: "Jonathan Rhys Meyers" }],
    coverUrl: "/movies/match_point.jpg",
    releaseDate: "2005-05-12",
    rating: 0,
    length: 124,
    genre: "Thriller",
  },
  {
    title: "Star Wars: Episode III – Revenge of the Sith",
    director: "George Lucas",
    actors: [{ name: "Hayden Christensen" }],
    coverUrl: "/movies/star_wars_revenge_sith.jpg",
    releaseDate: "2005-05-19",
    rating: 0,
    length: 140,
    genre: "Science Fiction",
  },
  {
    title: "xXx: State of the Union",
    director: "Lee Tamahori",
    actors: [{ name: "Ice Cube" }],
    coverUrl: "/movies/xxx_state_union.jpg",
    releaseDate: "2005-04-29",
    rating: 0,
    length: 101,
    genre: "Action",
  },
  {
    title: "The Brice Man",
    director: "James Huth",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies/brice_man.jpg",
    releaseDate: "2005-04-20",
    rating: 0,
    length: 84,
    genre: "Comedy",
  },
  {
    title: "Sin City",
    director: "Frank Miller, Robert Rodriguez",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/sin_city.jpg",
    releaseDate: "2005-04-01",
    rating: 0,
    length: 124,
    genre: "Crime",
  },
  {
    title: "The Descent",
    director: "Neil Marshall",
    actors: [{ name: "Shauna Macdonald" }],
    coverUrl: "/movies/descent.jpg",
    releaseDate: "2005-07-08",
    rating: 0,
    length: 99,
    genre: "Horror",
  },
  {
    title: "The Pacifier",
    director: "Adam Shankman",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/pacifier.jpg",
    releaseDate: "2005-03-04",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Hitch",
    director: "Andy Tennant",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/hitch.jpg",
    releaseDate: "2005-02-11",
    rating: 0,
    length: 118,
    genre: "Comedy",
  },
  {
    title: "Ocean's Twelve",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/oceans_twelve.jpg",
    releaseDate: "2004-12-10",
    rating: 0,
    length: 125,
    genre: "Crime",
  },
  {
    title: "Blade: Trinity",
    director: "David S. Goyer",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies/blade_trinity.jpg",
    releaseDate: "2004-12-08",
    rating: 0,
    length: 113,
    genre: "Action",
  },
  {
    title: "Million Dollar Baby",
    director: "Clint Eastwood",
    actors: [{ name: "Hilary Swank" }],
    coverUrl: "/movies/million_dollar_baby.jpg",
    releaseDate: "2004-12-15",
    rating: 0,
    length: 132,
    genre: "Drama",
  },
  {
    title: "District B13",
    director: "Pierre Morel",
    actors: [{ name: "David Belle" }],
    coverUrl: "/movies/district_b13.jpg",
    releaseDate: "2004-11-10",
    rating: 0,
    length: 84,
    genre: "Action",
  },
  {
    title: "Lucky Luke and the Daltons",
    director: "Haj Satrapi",
    actors: [{ name: "Lambert Wilson" }],
    coverUrl: "/movies/lucky_luke_daltons.jpg",
    releaseDate: "2004-12-15",
    rating: 0,
    length: 85,
    genre: "Animation",
  },
  {
    title: "The Incredibles",
    director: "Brad Bird",
    actors: [{ name: "Craig T. Nelson" }],
    coverUrl: "/movies/incredibles.jpg",
    releaseDate: "2004-11-05",
    rating: 0,
    length: 115,
    genre: "Animation",
  },
  {
    title: "First Daughter",
    director: "Forest Whitaker",
    actors: [{ name: "Katie Holmes" }],
    coverUrl: "/movies/first_daughter.jpg",
    releaseDate: "2004-09-24",
    rating: 0,
    length: 106,
    genre: "Romance",
  },
  {
    title: "Resident Evil: Apocalypse",
    director: "Alexander Witt",
    actors: [{ name: "Milla Jovovich" }],
    coverUrl: "/movies/resident_evil_apocalypse.jpg",
    releaseDate: "2004-09-10",
    rating: 0,
    length: 94,
    genre: "Action",
  },
  {
    title: "AVP: Alien vs. Predator",
    director: "Paul W.S. Anderson",
    actors: [{ name: "Sanaa Lathan" }],
    coverUrl: "/movies/avp_alien_vs_predator.jpg",
    releaseDate: "2004-08-13",
    rating: 0,
    length: 101,
    genre: "Action",
  },
  {
    title: "Catwoman",
    director: "Pitof",
    actors: [{ name: "Halle Berry" }],
    coverUrl: "/movies/catwoman.jpg",
    releaseDate: "2004-07-23",
    rating: 0,
    length: 104,
    genre: "Action",
  },
  {
    title: "The Bourne Supremacy",
    director: "Paul Greengrass",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/bourne_supremacy.jpg",
    releaseDate: "2004-07-23",
    rating: 0,
    length: 108,
    genre: "Action",
  },
  {
    title: "I, Robot",
    director: "Alex Proyas",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/i_robot.jpg",
    releaseDate: "2004-07-16",
    rating: 5,
    length: 115,
    genre: "Science Fiction",
  },
  {
    title: "Spider-Man 2",
    director: "Sam Raimi",
    actors: [{ name: "Tobey Maguire" }],
    coverUrl: "/movies/spiderman_2.jpg",
    releaseDate: "2004-06-30",
    rating: 0,
    length: 127,
    genre: "Action",
  },
];