import { Movie } from "./movies_1";

export const moviesPage11: Movie[] = [
  {
    title: "Spaceballs",
    director: "Mel Brooks",
    actors: [{ name: "Mel Brooks" }],
    coverUrl: "/movies_pictures/51203-spaceballs-0-150-0-225-crop.jpg",
    releaseDate: "1987-06-24",
    rating: 0,
    length: 96,
    genre: "Comedy",
    timesWatched: 3,
  },
  {
    title: "Predator",
    director: "John McTiernan",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/51944-predator-0-150-0-225-crop.jpg",
    releaseDate: "1987-06-12",
    rating: 0,
    length: 107,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Les Incorruptibles",
    director: "Brian De Palma",
    actors: [{ name: "Kevin Costner" }],
    coverUrl: "/movies_pictures/bDcqwNTwhEDfQHFj7jpt18N6Giz-0-150-0-225-crop.jpg",
    releaseDate: "1987-06-03",
    rating: 0,
    length: 119,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Dirty Dancing",
    director: "Emile Ardolino",
    actors: [{ name: "Patrick Swayze" }],
    coverUrl: "/movies_pictures/51962-dirty-dancing-0-150-0-225-crop.jpg",
    releaseDate: "1987-08-21",
    rating: 0,
    length: 100,
    genre: "Romance",
    timesWatched: 3,
  },
  {
    title: "L'arme fatale",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies_pictures/mF2bTqJuxbZPeEJRIMrA2WeQVxu-0-150-0-225-crop.jpg",
    releaseDate: "1987-03-06",
    rating: 0,
    length: 110,
    genre: "Action",
    timesWatched: 15,
  },
  {
    title: "Over the Top",
    director: "Menahem Golan",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/50772-over-the-top-0-150-0-225-crop.jpg",
    releaseDate: "1987-02-13",
    rating: 0,
    length: 93,
    genre: "Drama",
    timesWatched: 3,
  },
  {
    title: "Aliens",
    director: "James Cameron",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies_pictures/51445-aliens-0-150-0-225-crop.jpg",
    releaseDate: "1986-07-18",
    rating: 0,
    length: 137,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "Commando",
    director: "Mark L. Lester",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/45703-commando-0-150-0-225-crop.jpg",
    releaseDate: "1985-10-04",
    rating: 0,
    length: 90,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Retour vers le futur",
    director: "Robert Zemeckis",
    actors: [{ name: "Michael J. Fox" }],
    coverUrl: "/movies_pictures/51945-back-to-the-future-0-150-0-225-crop.jpg",
    releaseDate: "1985-07-03",
    rating: 0,
    length: 116,
    genre: "Science Fiction",
    timesWatched: 30,
  },
  {
    title: "Rambo 2 : la mission",
    director: "George P. Cosmatos",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/51087-rambo-first-blood-part-ii-0-150-0-225-crop.jpg",
    releaseDate: "1985-05-22",
    rating: 0,
    length: 96,
    genre: "Action",
    timesWatched: 5,
  },
  {
    title: "Le flic de Beverly Hills",
    director: "Martin Brest",
    actors: [{ name: "Eddie Murphy" }],
    coverUrl: "/movies_pictures/le_flic_de_beverly_hills.jpg",
    releaseDate: "1984-12-05",
    rating: 0,
    length: 105,
    genre: "Action",
    timesWatched: 1,
  }, {
    title: "Karate Kid",
    director: "John G. Avildsen",
    actors: [{ name: "Ralph Macchio" }],
    coverUrl: "/movies_pictures/50718-the-karate-kid-0-150-0-225-crop.jpg",
    releaseDate: "1984-06-22",
    rating: 0,
    length: 126,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Scarface",
    director: "Brian De Palma",
    actors: [{ name: "Al Pacino" }],
    coverUrl: "/movies_pictures/71wr6ah15sL._UF1000,1000_QL80_.jpg",
    releaseDate: "1983-12-09",
    rating: 0,
    length: 170,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "The Dead Zone",
    director: "David Cronenberg",
    actors: [{ name: "Christopher Walken" }],
    coverUrl: "/movies_pictures/45398-the-dead-zone-0-150-0-225-crop.jpg",
    releaseDate: "1983-10-21",
    rating: 0,
    length: 103,
    genre: "Thriller",
    timesWatched: 1,
  },
  {
    title: "Rambo : First Blood",
    director: "Ted Kotcheff",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies_pictures/51088-first-blood-0-150-0-225-crop.jpg",
    releaseDate: "1982-10-22",
    rating: 0,
    length: 93,
    genre: "Action",
    timesWatched: 20,
  },
  {
    title: "E.T. the Extra-Terrestrial",
    director: "Steven Spielberg",
    actors: [{ name: "Henry Thomas" }],
    coverUrl: "/movies_pictures/51520-e-t-the-extra-terrestrial-0-150-0-225-crop.jpg",
    releaseDate: "1982-06-11",
    rating: 0,
    length: 115,
    genre: "Science Fiction",
    timesWatched: 2,
  },
  {
    title: "La soupe aux choux",
    director: "Jean-Charles Tacchella",
    actors: [{ name: "Philippe Noiret" }],
    coverUrl: "/movies_pictures/47276-the-cabbage-soup-0-150-0-225-crop.jpg",
    releaseDate: "1981-12-16",
    rating: 0,
    length: 100,
    genre: "Comedy",
    timesWatched: 3,
  },
  {
    title: "The Shining",
    director: "Stanley Kubrick",
    actors: [{ name: "Jack Nicholson" }],
    coverUrl: "/movies_pictures/the_shining.jpg",
    releaseDate: "1980-05-23",
    rating: 0,
    length: 146,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Les bronzés font du ski",
    director: "Patrice Leconte",
    actors: [{ name: "Josiane Balasko" }],
    coverUrl: "/movies_pictures/29599-french-fried-vacation-2-the-bronzes-go-skiing-0-150-0-225-crop.jpg",
    releaseDate: "1979-12-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "Alien",
    director: "Ridley Scott",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies_pictures/alien.jpg",
    releaseDate: "1979-05-25",
    rating: 0,
    length: 117,
    genre: "Science Fiction",
    timesWatched: 5,
  },
  {
    title: "Les bronzés",
    director: "Patrice Leconte",
    actors: [{ name: "Josiane Balasko" }],
    coverUrl: "/movies_pictures/45526-french-fried-vacation-0-150-0-225-crop.jpg",
    releaseDate: "1978-12-20",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 2,
  },
  {
    title: "L'aile ou la cuisse",
    director: "Claude Zidi",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies_pictures/51391-the-wing-or-the-thigh--0-150-0-225-crop.jpg",
    releaseDate: "1976-10-27",
    rating: 0,
    length: 104,
    genre: "Comedy",
    timesWatched: 5,
  },
  {
    title: "Taxi Driver",
    director: "Martin Scorsese",
    actors: [{ name: "Robert De Niro" }],
    coverUrl: "/movies_pictures/51947-taxi-driver-0-150-0-225-crop.jpg",
    releaseDate: "1976-02-08",
    rating: 0,
    length: 114,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "Le Parrain 2",
    director: "Francis Ford Coppola",
    actors: [{ name: "Al Pacino" }],
    coverUrl: "/movies_pictures/51816-the-godfather-part-ii-0-150-0-225-crop.jpg",
    releaseDate: "1974-12-20",
    rating: 0,
    length: 202,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "L'exorciste",
    director: "William Friedkin",
    actors: [{ name: "Ellen Burstyn" }],
    coverUrl: "/movies_pictures/47048-the-exorcist-0-150-0-225-crop.jpg",
    releaseDate: "1973-12-26",
    rating: 0,
    length: 122,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Les aventures de Rabbi Jacob",
    director: "Gérard Oury",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies_pictures/51392-the-mad-adventures-of-rabbi-jacob-0-150-0-225-crop.jpg",
    releaseDate: "1973-10-17",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 3,
  },
  {
    title: "Le Parrain",
    director: "Francis Ford Coppola",
    actors: [{ name: "Marlon Brando" }],
    coverUrl: "/movies_pictures/51818-the-godfather-0-150-0-225-crop.jpg",
    releaseDate: "1972-03-24",
    rating: 0,
    length: 175,
    genre: "Crime",
    timesWatched: 1,
  },
  {
    title: "La Folie des grandeurs",
    director: "Gérard Oury",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies_pictures/43223-delusions-of-grandeur-0-150-0-225-crop.jpg",
    releaseDate: "1971-12-08",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Oscar",
    director: "Édouard Molinaro",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies_pictures/50079-oscar-0-150-0-225-crop.jpg",
    releaseDate: "1967-10-11",
    rating: 0,
    length: 85,
    genre: "Comedy",
    timesWatched: 10,
  },
  {
    title: "Fantomas",
    director: "André Hunebelle",
    actors: [{ name: "Jean Marais" }],
    coverUrl: "/movies_pictures/50732-fantomas-0-150-0-225-crop.jpg",
    releaseDate: "1964-11-04",
    rating: 0,
    length: 105,
    genre: "Adventure",
    timesWatched: 1,
  },
  {
    title: "Le Gendarme de Saint-Tropez",
    director: "Jean Girault",
    actors: [{ name: "Louis de Funès" }],
    coverUrl: "/movies_pictures/49168-le-gendarme-de-saint-tropez-0-150-0-225-crop.jpg",
    releaseDate: "1964-09-09",
    rating: 0,
    length: 95,
    genre: "Comedy",
    timesWatched: 2,
  },
  {
    title: "Les oiseaux",
    director: "Alfred Hitchcock",
    actors: [{ name: "Tippi Hedren" }],
    coverUrl: "/movies_pictures/51549-the-birds-0-150-0-225-crop.jpg",
    releaseDate: "1963-03-28",
    rating: 0,
    length: 119,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "Psychose",
    director: "Alfred Hitchcock",
    actors: [{ name: "Anthony Perkins" }],
    coverUrl: "/movies_pictures/51578-psycho-0-150-0-225-crop.jpg",
    releaseDate: "1960-06-16",
    rating: 0,
    length: 109,
    genre: "Horror",
    timesWatched: 1,
  },
  {
    title: "12 hommes en colère",
    director: "Sidney Lumet",
    actors: [{ name: "Henry Fonda" }],
    coverUrl: "/movies_pictures/51700-12-angry-men-0-150-0-225-crop.jpg",
    releaseDate: "1957-04-10",
    rating: 4,
    length: 96,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Citizen Kane",
    director: "Orson Welles",
    actors: [{ name: "Orson Welles" }],
    coverUrl: "/movies_pictures/2702-citizen-kane-0-150-0-225-crop.jpg",
    releaseDate: "1941-05-01",
    rating: 0,
    length: 119,
    genre: "Drama",
    timesWatched: 1,
  },
  {
    title: "Les temps modernes",
    director: "Charles Chaplin",
    actors: [{ name: "Charles Chaplin" }],
    coverUrl: "/movies_pictures/49889-modern-times-0-150-0-225-crop.jpg",
    releaseDate: "1936-02-05",
    rating: 0,
    length: 87,
    genre: "Comedy",
    timesWatched: 1,
  },


  {
    title: "Babylon A.D",
    director: "Mathieu Kassovitz",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies_pictures/3YXtGZ0jKHhh2bhqr0lu8qefKLr-0-1000-0-1500-crop.jpg",
    releaseDate: "2008-02-05",
    rating: 0,
    length: 101,
    genre: "Action",
    timesWatched: 10,
  },
  {
    title: "Maman je m'occupe des méchants",
    director: "Raja Gosnell",
    actors: [{ name: "" }],
    coverUrl: "/movies_pictures/46891-home-alone-3-0-1000-0-1500-crop.jpg",
    releaseDate: "1997-02-05",
    rating: 0,
    length: 102,
    genre: "Comedy",
    timesWatched: 20,
  },
  {
    title: "Yamakasi",
    director: "Julien Seri",
    actors: [{ name: "" }],
    coverUrl: "/movies_pictures/48171-yamakasi-0-1000-0-1500-crop.jpg",
    releaseDate: "2001-02-05",
    rating: 0,
    length: 90,
    genre: "Comedy",
    timesWatched: 40,
  },
  {
    title: "Jackie chan dans le bronx",
    director: "Stanley Tong Gwai-Lai",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies_pictures/y7AxKPPCtZyrGQKvxzn5zTQ8wFm-0-1000-0-1500-crop.jpg",
    releaseDate: "1995-02-05",
    rating: 0,
    length: 106,
    genre: "Comedy",
    timesWatched: 30,
  },
  {
    title: "Le médaillon",
    director: "Gordon Chan",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies_pictures/46064-the-medallion-0-1000-0-1500-crop.jpg",
    releaseDate: "2003-02-05",
    rating: 0,
    length: 88,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Smoking",
    director: "Kevin Donovan",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies_pictures/45912-the-tuxedo-0-1000-0-1500-crop.jpg",
    releaseDate: "2002-02-05",
    rating: 0,
    length: 98,
    genre: "Comedy",
    timesWatched: 1,
  },
  {
    title: "Brice de Nice",
    director: "James Huth",
    actors: [{ name: "Jean Dujardin" }],
    coverUrl: "/movies_pictures/41053-the-brice-man-0-150-0-225-crop.jpg",
    releaseDate: "2005-02-02",
    rating: 0,
    length: 94,
    genre: "Comedy",
    timesWatched: 3,
  },
];