import { Movie } from "./movies_1";

export const moviesPage3: Movie[] = [


  {
    title: "Kingsman: The Golden Circle",
    director: "Matthew Vaughn",
    actors: [{ name: "Taron Egerton" }],
    coverUrl: "/movies_pictures/kingsman_the_golden_circle.jpg",
    releaseDate: "2017-09-22",
    rating: 3,
    length: 141,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Death Note",
    director: "Adam Wingard",
    actors: [{ name: "Nat Wolff" }],
    coverUrl: "/movies_pictures/281716-death-note-0-150-0-225-crop.jpg",
    releaseDate: "2017-08-25",
    rating: 2.5,
    length: 101,
    genre: "Thriller",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "The Hitman's Bodyguard",
    director: "Patrick Hughes",
    actors: [{ name: "Ryan Reynolds" }],
    coverUrl: "/movies_pictures/hitman_bodyguard.jpg",
    releaseDate: "2017-08-18",
    rating: 3,
    length: 118,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: "The Hitman's Bodyguard"
  },
  {
    title: "Valerian and the City of a Thousand Planets",
    director: "Luc Besson",
    actors: [{ name: "Dane DeHaan" }],
    coverUrl: "/movies_pictures/269458-valerian-and-the-city-of-a-thousand-planets-0-150-0-225-crop.jpg",
    releaseDate: "2017-07-21",
    rating: 3.25,
    length: 137,
    genre: "Science Fiction",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Atomic Blonde",
    director: "David Leitch",
    actors: [{ name: "Charlize Theron" }],
    coverUrl: "/movies_pictures/270477-atomic-blonde-0-150-0-225-crop.jpg",
    releaseDate: "2017-07-28",
    rating: 3,
    length: 115,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Baby Driver",
    director: "Edgar Wright",
    actors: [{ name: "Ansel Elgort" }],
    coverUrl: "/movies_pictures/268950-baby-driver-0-150-0-225-crop.jpg",
    releaseDate: "2017-06-28",
    rating: 4,
    length: 113,
    genre: "Action",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "Aftermath",
    director: "Elliott Lester",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies_pictures/aftermath.jpg",
    releaseDate: "2017-04-07",
    rating: 3.5,
    length: 94,
    genre: "Drama",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "John Wick : Chapitre 2",
    director: "Chad Stahelski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies_pictures/jonh_wick.jpg",
    releaseDate: "2017-02-10",
    rating: 3.25,
    length: 122,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Les Animaux Fantastiques",
    director: "David Yates",
    actors: [{ name: "Eddie Redmayne" }],
    coverUrl: "/movies_pictures/182910-fantastic-beasts-and-where-to-find-them-0-150-0-225-crop.jpg",
    releaseDate: "2016-11-18",
    rating: 3.75,
    length: 133,
    genre: "Fantasy",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "Jack Reacher : Never Go Back",
    director: "Edward Zwick",
    actors: [{ name: "Tom Cruise" }],
    coverUrl: "/movies_pictures/jack_reacher_never_go_back.jpg",
    releaseDate: "2016-10-21",
    rating: 3.5,
    length: 118,
    genre: "Action",
    timesWatched: 2,
    lastViewedDate: ""
  },
  {
    title: "Split",
    director: "M. Night Shyamalan",
    actors: [{ name: "James McAvoy" }],
    coverUrl: "/movies_pictures/split.jpg",
    releaseDate: "2017-01-20",
    rating: 4.5,
    length: 117,
    genre: "Thriller",
    timesWatched: 5,
    lastViewedDate: ""
  },
  {
    title: "Il a Déjà Tes Yeux",
    director: "Lucien Jean-Baptiste",
    actors: [{ name: "Lucien Jean-Baptiste" }],
    coverUrl: "/movies_pictures/333161-he-even-has-your-eyes-0-150-0-225-crop.jpg",
    releaseDate: "2016-12-07",
    rating: 3,
    length: 98,
    genre: "Comedy",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Jason Bourne",
    director: "Paul Greengrass",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies_pictures/251773-jason-bourne-0-150-0-225-crop.jpg",
    releaseDate: "2016-07-29",
    rating: 3.75,
    length: 123,
    genre: "Action",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "Now You See Me 2",
    director: "Jon M. Chu",
    actors: [{ name: "Jesse Eisenberg" }],
    coverUrl: "/movies_pictures/218051-now-you-see-me-2-0-150-0-225-crop.jpg",
    releaseDate: "2016-06-10",
    rating: 3.25,
    length: 129,
    genre: "Thriller",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Divergente 3 : Au-delà du Mur",
    director: "Robert Schwentke",
    actors: [{ name: "Shailene Woodley" }],
    coverUrl: "/movies_pictures/divergente.jpg",
    releaseDate: "2016-03-18",
    rating: 3,
    length: 121,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Un choix",
    director: "Ross Katz",
    actors: [{ name: "Benjamin Walker" }],
    coverUrl: "/movies_pictures/258147-the-choice-0-150-0-225-crop.jpg",
    releaseDate: "2016-02-05",
    rating: 3.75,
    length: 111,
    genre: "Romance",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "Swiss Army Man",
    director: "Dan Kwan, Daniel Scheinert",
    actors: [{ name: "Paul Dano" }],
    coverUrl: "/movies_pictures/swiss_army_man.jpg",
    releaseDate: "2016-07-01",
    rating: 3.25,
    length: 97,
    genre: "Comedy",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Comment c'est loin",
    director: "Orelsan",
    actors: [{ name: "Orelsan" }],
    coverUrl: "/movies_pictures/302633-comment-c-est-loin-0-150-0-225-crop.jpg",
    releaseDate: "2015-12-09",
    rating: 3.25,
    length: 95,
    genre: "Comedy",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Creed",
    director: "Ryan Coogler",
    actors: [{ name: "Michael B. Jordan" }],
    coverUrl: "/movies_pictures/239260-creed-0-150-0-225-crop.jpg",
    releaseDate: "2015-11-25",
    rating: 4,
    length: 133,
    genre: "Drama",
    timesWatched: 2,
    lastViewedDate: ""
  },
  {
    title: "Spectre",
    director: "Sam Mendes",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies_pictures/spectre.jpg",
    releaseDate: "2015-11-06",
    rating: 4,
    length: 148,
    genre: "Action",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "Demolition",
    director: "Jean-Marc Vallée",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies_pictures/demolition.jpg",
    releaseDate: "2016-04-08",
    rating: 3.5,
    length: 101,
    genre: "Drama",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "The Visit",
    director: "M. Night Shyamalan",
    actors: [{ name: "Olivia DeJonge" }],
    coverUrl: "/movies_pictures/225437-the-visit-0-150-0-225-crop.jpg",
    releaseDate: "2015-09-11",
    rating: 2.5,
    length: 94,
    genre: "Horror",
    timesWatched: 1,
    lastViewedDate: "2015-09-11"
  },
  {
    title: "Le Labyrinthe : La Terre Brûlée",
    director: "Wes Ball",
    actors: [{ name: "Dylan O'Brien" }],
    coverUrl: "/movies_pictures/221232-maze-runner-the-scorch-trials-0-150-0-225-crop.jpg",
    releaseDate: "2015-09-18",
    rating: 2.5,
    length: 132,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Room",
    director: "Lenny Abrahamson",
    actors: [{ name: "Brie Larson" }],
    coverUrl: "/movies_pictures/room.jpg",
    releaseDate: "2016-01-22",
    rating: 3.5,
    length: 118,
    genre: "Drama",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Pixels",
    director: "Chris Columbus",
    actors: [{ name: "Adam Sandler" }],
    coverUrl: "/movies_pictures/181118-pixels-0-150-0-225-crop.jpg",
    releaseDate: "2015-07-24",
    rating: 3.25,
    length: 105,
    genre: "Comedy",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "La rage au ventre",
    director: "Antoine Fuqua",
    actors: [{ name: "Jake Gyllenhaal" }],
    coverUrl: "/movies_pictures/234208-southpaw-0-150-0-225-crop.jpg",
    releaseDate: "2015-07-24",
    rating: 3.5,
    length: 124,
    genre: "Drama",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Divergente 2 : L'Insurrection",
    director: "Robert Schwentke",
    actors: [{ name: "Shailene Woodley" }],
    coverUrl: "/movies_pictures/185970-insurgent-0-150-0-225-crop.jpg",
    releaseDate: "2015-03-20",
    rating: 3.25,
    length: 119,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Diversion",
    director: "Glenn Ficarra, John Requa",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies_pictures/180414-focus-0-150-0-225-crop.jpg",
    releaseDate: "2015-02-27",
    rating: 3.75,
    length: 105,
    genre: "Crime",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Cinquante Nuances de Grey",
    director: "Sam Taylor-Johnson",
    actors: [{ name: "Dakota Johnson" }],
    coverUrl: "/movies_pictures/cinquante_nuances_de_grey.jpg",
    releaseDate: "2015-02-13",
    rating: 2,
    length: 125,
    genre: "Drama",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Knock Knock",
    director: "Eli Roth",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies_pictures/186877-knock-knock-0-150-0-225-crop.jpg",
    releaseDate: "2015-10-09",
    rating: 2.5,
    length: 99,
    genre: "Thriller",
    timesWatched: 1,
    lastViewedDate: "2025-04-09"
  },
  {
    title: "Taken 3",
    director: "Olivier Megaton",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies_pictures/183907-taken-3-0-150-0-225-crop.jpg",
    releaseDate: "2015-01-09",
    rating: 2.5,
    length: 109,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Kingsman : Services Secrets",
    director: "Matthew Vaughn",
    actors: [{ name: "Taron Egerton" }],
    coverUrl: "/movies_pictures/148200-kingsman-the-secret-service-0-150-0-225-crop.jpg",
    releaseDate: "2015-02-13",
    rating: 4.5,
    length: 129,
    genre: "Action",
    timesWatched: 5,
    lastViewedDate: ""
  },
  {
    title: "Hunger Games : La Révolte - Partie 1",
    director: "Francis Lawrence",
    actors: [{ name: "Jennifer Lawrence" }],
    coverUrl: "/movies_pictures/101991-the-hunger-games-mockingjay-part-1-0-150-0-225-crop.jpg",
    releaseDate: "2014-11-21",
    rating: 3,
    length: 123,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Interstellar",
    director: "Christopher Nolan",
    actors: [{ name: "Matthew McConaughey" }],
    coverUrl: "/movies_pictures/117621-interstellar-0-150-0-225-crop.jpg",
    releaseDate: "2014-11-07",
    rating: 3.5,
    length: 169,
    genre: "Science Fiction",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Gone Girl",
    director: "David Fincher",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies_pictures/149857-gone-girl-0-150-0-225-crop.jpg",
    releaseDate: "2014-10-03",
    rating: 3,
    length: 149,
    genre: "Thriller",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "John Wick",
    director: "Chad Stahelski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies_pictures/172076-john-wick-0-150-0-225-crop.jpg",
    releaseDate: "2014-10-24",
    rating: 4,
    length: 101,
    genre: "Action",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "Le Labyrinthe",
    director: "Wes Ball",
    actors: [{ name: "Dylan O'Brien" }],
    coverUrl: "/movies_pictures/142549-the-maze-runner-0-150-0-225-crop.jpg",
    releaseDate: "2014-09-19",
    rating: 4,
    length: 113,
    genre: "Action",
    timesWatched: 5,
    lastViewedDate: ""
  },
  {
    title: "Birdman",
    director: "Alejandro G. Iñárritu",
    actors: [{ name: "Michael Keaton" }],
    coverUrl: "/movies_pictures/139795-birdman-0-150-0-225-crop.jpg",
    releaseDate: "2014-10-17",
    rating: 3,
    length: 119,
    genre: "Drama",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Sin City : J'ai Tué pour Elle",
    director: "Frank Miller, Robert Rodriguez",
    actors: [{ name: "Mickey Rourke" }],
    coverUrl: "/movies_pictures/51863-sin-city-a-dame-to-kill-for-0-150-0-225-crop.jpg",
    releaseDate: "2014-08-22",
    rating: 3.25,
    length: 102,
    genre: "Crime",
    timesWatched: 1,
    lastViewedDate: ""
  },
  {
    title: "Lucy",
    director: "Luc Besson",
    actors: [{ name: "Scarlett Johansson" }],
    coverUrl: "/movies_pictures/168860-lucy-0-150-0-225-crop.jpg",
    releaseDate: "2014-07-25",
    rating: 4.5,
    length: 89,
    genre: "Action",
    timesWatched: 3,
    lastViewedDate: ""
  },
  {
    title: "Transformers : L'Âge de l'Extinction",
    director: "Michael Bay",
    actors: [{ name: "Mark Wahlberg" }],
    coverUrl: "/movies_pictures/76504-transformers-age-of-extinction-0-150-0-225-crop.jpg",
    releaseDate: "2014-06-27",
    rating: 3,
    length: 165,
    genre: "Action",
    timesWatched: 1,
    lastViewedDate: ""
  },
];