import { Movie } from "./movies";

export const moviesPage4: Movie[] = [
  {
    title: "Maleficent",
    director: "Robert Stromberg",
    actors: [{ name: "Angelina Jolie" }],
    coverUrl: "/movies/maleficent.jpg",
    releaseDate: "2014-05-30",
    rating: 0,
    length: 97,
    genre: "Fantasy",
  },
  {
    title: "Edge of Tomorrow",
    director: "Doug Liman",
    actors: [{ name: "Tom Cruise" }],
    coverUrl: "/movies/edge_of_tomorrow.jpg",
    releaseDate: "2014-06-06",
    rating: 0,
    length: 113,
    genre: "Science Fiction",
  },
  {
    title: "How to Train Your Dragon 2",
    director: "Dean DeBlois",
    actors: [{ name: "Jay Baruchel" }],
    coverUrl: "/movies/how_to_train_dragon_2.jpg",
    releaseDate: "2014-06-13",
    rating: 0,
    length: 102,
    genre: "Animation",
  },
  {
    title: "X-Men: Days of Future Past",
    director: "Bryan Singer",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/xmen_days_future_past.jpg",
    releaseDate: "2014-05-23",
    rating: 0,
    length: 132,
    genre: "Action",
  },
  {
    title: "The Amazing Spider-Man 2",
    director: "Marc Webb",
    actors: [{ name: "Andrew Garfield" }],
    coverUrl: "/movies/amazing_spiderman_2.jpg",
    releaseDate: "2014-05-02",
    rating: 0,
    length: 142,
    genre: "Action",
  },
  {
    title: "Divergent",
    director: "Neil Burger",
    actors: [{ name: "Shailene Woodley" }],
    coverUrl: "/movies/divergent.jpg",
    releaseDate: "2014-03-21",
    rating: 0,
    length: 139,
    genre: "Action",
  },
  {
    title: "Captain America: The Winter Soldier",
    director: "Anthony Russo, Joe Russo",
    actors: [{ name: "Chris Evans" }],
    coverUrl: "/movies/captain_america_winter_soldier.jpg",
    releaseDate: "2014-04-04",
    rating: 0,
    length: 136,
    genre: "Action",
  },
  {
    title: "RoboCop",
    director: "José Padilha",
    actors: [{ name: "Joel Kinnaman" }],
    coverUrl: "/movies/robocop.jpg",
    releaseDate: "2014-02-12",
    rating: 0,
    length: 117,
    genre: "Action",
  },
  {
    title: "The Wolf of Wall Street",
    director: "Martin Scorsese",
    actors: [{ name: "Leonardo DiCaprio" }],
    coverUrl: "/movies/wolf_wall_street.jpg",
    releaseDate: "2013-12-25",
    rating: 0,
    length: 180,
    genre: "Crime",
  },
  {
    title: "The Secret Life of Walter Mitty",
    director: "Ben Stiller",
    actors: [{ name: "Ben Stiller" }],
    coverUrl: "/movies/secret_life_walter_mitty.jpg",
    releaseDate: "2013-12-25",
    rating: 0,
    length: 114,
    genre: "Adventure",
  },
  {
    title: "Frozen",
    director: "Chris Buck, Jennifer Lee",
    actors: [{ name: "Kristen Bell" }],
    coverUrl: "/movies/frozen.jpg",
    releaseDate: "2013-11-27",
    rating: 0,
    length: 102,
    genre: "Animation",
  },
  {
    title: "Thor: The Dark World",
    director: "Alan Taylor",
    actors: [{ name: "Chris Hemsworth" }],
    coverUrl: "/movies/thor_dark_world.jpg",
    releaseDate: "2013-11-08",
    rating: 0,
    length: 112,
    genre: "Action",
  },
  {
    title: "Prisoners",
    director: "Denis Villeneuve",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/prisoners.jpg",
    releaseDate: "2013-09-20",
    rating: 0,
    length: 153,
    genre: "Thriller",
  },
  {
    title: "Gravity",
    director: "Alfonso Cuarón",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/gravity.jpg",
    releaseDate: "2013-10-04",
    rating: 0,
    length: 91,
    genre: "Science Fiction",
  },
  {
    title: "Elysium",
    director: "Neill Blomkamp",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/elysium.jpg",
    releaseDate: "2013-08-09",
    rating: 0,
    length: 109,
    genre: "Science Fiction",
  },
  {
    title: "The Butler",
    director: "Lee Daniels",
    actors: [{ name: "Forest Whitaker" }],
    coverUrl: "/movies/butler.jpg",
    releaseDate: "2013-08-16",
    rating: 0,
    length: 132,
    genre: "Drama",
  },
  {
    title: "The Wolverine",
    director: "James Mangold",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/wolverine.jpg",
    releaseDate: "2013-07-26",
    rating: 0,
    length: 126,
    genre: "Action",
  },
  {
    title: "RED 2",
    director: "Dean Parisot",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/red_2.jpg",
    releaseDate: "2013-07-19",
    rating: 0,
    length: 116,
    genre: "Action",
  },
  {
    title: "Escape Plan",
    director: "Mikael Håfström",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/escape_plan.jpg",
    releaseDate: "2013-10-18",
    rating: 0,
    length: 115,
    genre: "Action",
  },
  {
    title: "Kick-Ass 2",
    director: "Jeff Wadlow",
    actors: [{ name: "Aaron Taylor-Johnson" }],
    coverUrl: "/movies/kick_ass_2.jpg",
    releaseDate: "2013-08-16",
    rating: 0,
    length: 103,
    genre: "Action",
  },
  {
    title: "Pacific Rim",
    director: "Guillermo del Toro",
    actors: [{ name: "Charlie Hunnam" }],
    coverUrl: "/movies/pacific_rim.jpg",
    releaseDate: "2013-07-12",
    rating: 0,
    length: 131,
    genre: "Action",
  },
  {
    title: "World War Z",
    director: "Marc Forster",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/world_war_z.jpg",
    releaseDate: "2013-06-21",
    rating: 0,
    length: 116,
    genre: "Action",
  },
  {
    title: "Despicable Me 2",
    director: "Pierre Coffin, Chris Renaud",
    actors: [{ name: "Steve Carell" }],
    coverUrl: "/movies/despicable_me_2.jpg",
    releaseDate: "2013-07-03",
    rating: 0,
    length: 98,
    genre: "Animation",
  },
  {
    title: "Man of Steel",
    director: "Zack Snyder",
    actors: [{ name: "Henry Cavill" }],
    coverUrl: "/movies/man_of_steel.jpg",
    releaseDate: "2013-06-14",
    rating: 0,
    length: 143,
    genre: "Action",
  },
  {
    title: "The Conjuring",
    director: "James Wan",
    actors: [{ name: "Vera Farmiga" }],
    coverUrl: "/movies/conjuring.jpg",
    releaseDate: "2013-07-19",
    rating: 0,
    length: 112,
    genre: "Horror",
  },
  {
    title: "After Earth",
    director: "M. Night Shyamalan",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/after_earth.jpg",
    releaseDate: "2013-05-31",
    rating: 0,
    length: 100,
    genre: "Science Fiction",
  },
  {
    title: "Now You See Me",
    director: "Louis Leterrier",
    actors: [{ name: "Jesse Eisenberg" }],
    coverUrl: "/movies/now_you_see_me.jpg",
    releaseDate: "2013-05-31",
    rating: 0,
    length: 115,
    genre: "Thriller",
  },
  {
    title: "The Hangover Part III",
    director: "Todd Phillips",
    actors: [{ name: "Bradley Cooper" }],
    coverUrl: "/movies/hangover_3.jpg",
    releaseDate: "2013-05-23",
    rating: 0,
    length: 100,
    genre: "Comedy",
  },
  {
    title: "Fast & Furious 6",
    director: "Justin Lin",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/fast_furious_6.jpg",
    releaseDate: "2013-05-24",
    rating: 0,
    length: 130,
    genre: "Action",
  },
  {
    title: "Iron Man 3",
    director: "Shane Black",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/iron_man_3.jpg",
    releaseDate: "2013-05-03",
    rating: 0,
    length: 130,
    genre: "Action",
  },
  {
    title: "Pain & Gain",
    director: "Michael Bay",
    actors: [{ name: "Mark Wahlberg" }],
    coverUrl: "/movies/pain_gain.jpg",
    releaseDate: "2013-04-26",
    rating: 0,
    length: 129,
    genre: "Crime",
  },
  {
    title: "Oblivion",
    director: "Joseph Kosinski",
    actors: [{ name: "Tom Cruise" }],
    coverUrl: "/movies/oblivion.jpg",
    releaseDate: "2013-04-19",
    rating: 0,
    length: 124,
    genre: "Science Fiction",
  },
  {
    title: "Black Mirror: White Bear",
    director: "Carl Tibbetts",
    actors: [{ name: "Lenora Crichlow" }],
    coverUrl: "/movies/black_mirror_white_bear.jpg",
    releaseDate: "2013-02-18",
    rating: 0,
    length: 42,
    genre: "Science Fiction",
  },
  {
    title: "A Good Day to Die Hard",
    director: "John Moore",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/good_day_die_hard.jpg",
    releaseDate: "2013-02-14",
    rating: 0,
    length: 98,
    genre: "Action",
  },
  {
    title: "Django Unchained",
    director: "Quentin Tarantino",
    actors: [{ name: "Jamie Foxx" }],
    coverUrl: "/movies/django_unchained.jpg",
    releaseDate: "2012-12-25",
    rating: 0,
    length: 165,
    genre: "Western",
  },
  {
    title: "Jack Reacher",
    director: "Christopher McQuarrie",
    actors: [{ name: "Tom Cruise" }],
    coverUrl: "/movies/jack_reacher.jpg",
    releaseDate: "2012-12-21",
    rating: 0,
    length: 130,
    genre: "Action",
  },
  {
    title: "Ending the Knight",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/ending_knight.jpg",
    releaseDate: "2012-12-07",
    rating: 0,
    length: 164,
    genre: "Action",
  },
  {
    title: "Rise of the Guardians",
    director: "Peter Ramsey",
    actors: [{ name: "Chris Pine" }],
    coverUrl: "/movies/rise_guardians.jpg",
    releaseDate: "2012-11-21",
    rating: 0,
    length: 97,
    genre: "Animation",
  },
  {
    title: "The Twilight Saga: Breaking Dawn – Part 2",
    director: "Bill Condon",
    actors: [{ name: "Kristen Stewart" }],
    coverUrl: "/movies/twilight_breaking_dawn_2.jpg",
    releaseDate: "2012-11-16",
    rating: 0,
    length: 115,
    genre: "Fantasy",
  },
  {
    title: "Wreck-It Ralph",
    director: "Rich Moore",
    actors: [{ name: "John C. Reilly" }],
    coverUrl: "/movies/wreck_it_ralph.jpg",
    releaseDate: "2012-11-02",
    rating: 0,
    length: 101,
    genre: "Animation",
  },
  {
    title: "Skyfall",
    director: "Sam Mendes",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies/skyfall.jpg",
    releaseDate: "2012-11-09",
    rating: 0,
    length: 143,
    genre: "Action",
  },
  {
    title: "Taken 2",
    director: "Olivier Megaton",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies/taken_2.jpg",
    releaseDate: "2012-10-05",
    rating: 0,
    length: 92,
    genre: "Action",
  },
  {
    title: "The Dream Team",
    director: "Thomas Sorriaux",
    actors: [{ name: "Gérard Lanvin" }],
    coverUrl: "/movies/dream_team.jpg",
    releaseDate: "2012-10-03",
    rating: 0,
    length: 105,
    genre: "Comedy",
  },
  {
    title: "Dredd",
    director: "Pete Travis",
    actors: [{ name: "Karl Urban" }],
    coverUrl: "/movies/dredd.jpg",
    releaseDate: "2012-09-21",
    rating: 0,
    length: 95,
    genre: "Action",
  },
  {
    title: "The Expendables 2",
    director: "Simon West",
    actors: [{ name: "Sylvester Stallone" }],
    coverUrl: "/movies/expendables_2.jpg",
    releaseDate: "2012-08-17",
    rating: 0,
    length: 103,
    genre: "Action",
  },
  {
    title: "The Dark Knight Rises",
    director: "Christopher Nolan",
    actors: [{ name: "Christian Bale" }],
    coverUrl: "/movies/dark_knight_rises.jpg",
    releaseDate: "2012-07-20",
    rating: 0,
    length: 164,
    genre: "Action",
  },
  {
    title: "Ice Age: Continental Drift",
    director: "Steve Martino, Mike Thurmeier",
    actors: [{ name: "Ray Romano" }],
    coverUrl: "/movies/ice_age_continental_drift.jpg",
    releaseDate: "2012-07-13",
    rating: 0,
    length: 88,
    genre: "Animation",
  },
  {
    title: "The Amazing Spider-Man",
    director: "Marc Webb",
    actors: [{ name: "Andrew Garfield" }],
    coverUrl: "/movies/amazing_spiderman.jpg",
    releaseDate: "2012-07-03",
    rating: 0,
    length: 136,
    genre: "Action",
  },
  {
    title: "Brave",
    director: "Mark Andrews, Brenda Chapman",
    actors: [{ name: "Kelly Macdonald" }],
    coverUrl: "/movies/brave.jpg",
    releaseDate: "2012-06-22",
    rating: 0,
    length: 93,
    genre: "Animation",
  },
  {
    title: "The Dictator",
    director: "Larry Charles",
    actors: [{ name: "Sacha Baron Cohen" }],
    coverUrl: "/movies/dictator.jpg",
    releaseDate: "2012-05-16",
    rating: 0,
    length: 83,
    genre: "Comedy",
  },
  {
    title: "Men in Black 3",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/men_in_black_3.jpg",
    releaseDate: "2012-05-25",
    rating: 0,
    length: 106,
    genre: "Science Fiction",
  },
  {
    title: "The Avengers",
    director: "Joss Whedon",
    actors: [{ name: "Robert Downey Jr." }],
    coverUrl: "/movies/avengers.jpg",
    releaseDate: "2012-05-04",
    rating: 0,
    length: 143,
    genre: "Action",
  },
  {
    title: "The Lucky One",
    director: "Scott Hicks",
    actors: [{ name: "Zac Efron" }],
    coverUrl: "/movies/lucky_one.jpg",
    releaseDate: "2012-04-20",
    rating: 0,
    length: 101,
    genre: "Romance",
  },
  {
    title: "Prometheus",
    director: "Ridley Scott",
    actors: [{ name: "Noomi Rapace" }],
    coverUrl: "/movies/prometheus.jpg",
    releaseDate: "2012-06-08",
    rating: 0,
    length: 124,
    genre: "Science Fiction",
  },
  {
    title: "American Reunion",
    director: "Jon Hurwitz, Hayden Schlossberg",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies/american_reunion.jpg",
    releaseDate: "2012-04-06",
    rating: 0,
    length: 113,
    genre: "Comedy",
  },
  {
    title: "21 Jump Street",
    director: "Phil Lord, Christopher Miller",
    actors: [{ name: "Jonah Hill" }],
    coverUrl: "/movies/21_jump_street.jpg",
    releaseDate: "2012-03-16",
    rating: 0,
    length: 109,
    genre: "Comedy",
  },
  {
    title: "The Hunger Games",
    director: "Gary Ross",
    actors: [{ name: "Jennifer Lawrence" }],
    coverUrl: "/movies/hunger_games.jpg",
    releaseDate: "2012-03-23",
    rating: 0,
    length: 142,
    genre: "Action",
  },
  {
    title: "This Means War",
    director: "McG",
    actors: [{ name: "Chris Pine" }],
    coverUrl: "/movies/this_means_war.jpg",
    releaseDate: "2012-02-17",
    rating: 0,
    length: 98,
    genre: "Action",
  },
  {
    title: "Chronicle",
    director: "Josh Trank",
    actors: [{ name: "Dane DeHaan" }],
    coverUrl: "/movies/chronicle.jpg",
    releaseDate: "2012-02-03",
    rating: 0,
    length: 84,
    genre: "Science Fiction",
  },
  {
    title: "Underworld: Awakening",
    director: "Måns Mårlind, Björn Stein",
    actors: [{ name: "Kate Beckinsale" }],
    coverUrl: "/movies/underworld_awakening.jpg",
    releaseDate: "2012-01-20",
    rating: 0,
    length: 88,
    genre: "Action",
  },
  {
    title: "Black Mirror: The National Anthem",
    director: "Otto Bathurst",
    actors: [{ name: "Rory Kinnear" }],
    coverUrl: "/movies/black_mirror_national_anthem.jpg",
    releaseDate: "2011-12-04",
    rating: 0,
    length: 44,
    genre: "Science Fiction",
  },
  {
    title: "The Twilight Saga: Breaking Dawn – Part 1",
    director: "Bill Condon",
    actors: [{ name: "Kristen Stewart" }],
    coverUrl: "/movies/twilight_breaking_dawn_1.jpg",
    releaseDate: "2011-11-18",
    rating: 0,
    length: 117,
    genre: "Fantasy",
  },
  {
    title: "In Time",
    director: "Andrew Niccol",
    actors: [{ name: "Justin Timberlake" }],
    coverUrl: "/movies/in_time.jpg",
    releaseDate: "2011-10-28",
    rating: 0,
    length: 109,
    genre: "Science Fiction",
  },
  {
    title: "Footloose",
    director: "Craig Brewer",
    actors: [{ name: "Kenny Wormald" }],
    coverUrl: "/movies/footloose.jpg",
    releaseDate: "2011-10-14",
    rating: 0,
    length: 113,
    genre: "Drama",
  },
  {
    title: "Real Steel",
    director: "Shawn Levy",
    actors: [{ name: "Hugh Jackman" }],
    coverUrl: "/movies/real_steel.jpg",
    releaseDate: "2011-10-07",
    rating: 0,
    length: 127,
    genre: "Action",
  },
  {
    title: "The Intouchables",
    director: "Olivier Nakache, Éric Toledano",
    actors: [{ name: "François Cluzet" }],
    coverUrl: "/movies/intouchables.jpg",
    releaseDate: "2011-11-02",
    rating: 0,
    length: 112,
    genre: "Comedy",
  },
  {
    title: "Warrior",
    director: "Gavin O'Connor",
    actors: [{ name: "Tom Hardy" }],
    coverUrl: "/movies/warrior.jpg",
    releaseDate: "2011-09-09",
    rating: 0,
    length: 140,
    genre: "Drama",
  },
  {
    title: "Never Back Down 2: The Beatdown",
    director: "Michael Jai White",
    actors: [{ name: "Michael Jai White" }],
    coverUrl: "/movies/never_back_down_2.jpg",
    releaseDate: "2011-09-13",
    rating: 0,
    length: 90,
    genre: "Action",
  },
  {
    title: "The Raid",
    director: "Gareth Evans",
    actors: [{ name: "Iko Uwais" }],
    coverUrl: "/movies/raid.jpg",
    releaseDate: "2012-03-23",
    rating: 0,
    length: 101,
    genre: "Action",
  },
  {
    title: "Final Destination 5",
    director: "Steven Quale",
    actors: [{ name: "Nicholas D'Agosto" }],
    coverUrl: "/movies/final_destination_5.jpg",
    releaseDate: "2011-08-12",
    rating: 0,
    length: 92,
    genre: "Horror",
  },
  {
    title: "Cowboys & Aliens",
    director: "Jon Favreau",
    actors: [{ name: "Daniel Craig" }],
    coverUrl: "/movies/cowboys_aliens.jpg",
    releaseDate: "2011-07-29",
    rating: 0,
    length: 118,
    genre: "Science Fiction",
  },
  {
    title: "Captain America: The First Avenger",
    director: "Joe Johnston",
    actors: [{ name: "Chris Evans" }],
    coverUrl: "/movies/captain_america_first_avenger.jpg",
    releaseDate: "2011-07-22",
    rating: 0,
    length: 124,
    genre: "Action",
  },
];