import { Movie } from "./movies";

export const moviesPage9: Movie[] = [
  {
    title: "Ocean's Eleven",
    director: "Steven Soderbergh",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/oceans_eleven.jpg",
    releaseDate: "2001-12-07",
    rating: 0,
    length: 116,
    genre: "Crime",
  },
  {
    title: "Tanguy",
    director: "Étienne Chatiliez",
    actors: [{ name: "Éric Berger" }],
    coverUrl: "/movies/tanguy.jpg",
    releaseDate: "2001-12-19",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    director: "Chris Columbus",
    actors: [{ name: "Daniel Radcliffe" }],
    coverUrl: "/movies/harry_potter_philosophers_stone.jpg",
    releaseDate: "2001-11-16",
    rating: 0,
    length: 152,
    genre: "Fantasy",
  },
  {
    title: "The One",
    director: "James Wong",
    actors: [{ name: "Jet Li" }],
    coverUrl: "/movies/one.jpg",
    releaseDate: "2001-11-02",
    rating: 0,
    length: 87,
    genre: "Science Fiction",
  },
  {
    title: "Wasabi",
    director: "Gérard Krawczyk",
    actors: [{ name: "Jean Reno" }],
    coverUrl: "/movies/wasabi.jpg",
    releaseDate: "2001-10-31",
    rating: 0,
    length: 94,
    genre: "Action",
  },
  {
    title: "Monsters, Inc.",
    director: "Pete Docter",
    actors: [{ name: "John Goodman" }],
    coverUrl: "/movies/monsters_inc.jpg",
    releaseDate: "2001-11-02",
    rating: 0,
    length: 92,
    genre: "Animation",
  },
  {
    title: "Training Day",
    director: "Antoine Fuqua",
    actors: [{ name: "Denzel Washington" }],
    coverUrl: "/movies/training_day.jpg",
    releaseDate: "2001-10-05",
    rating: 0,
    length: 122,
    genre: "Crime",
  },
  {
    title: "American Pie 2",
    director: "J.B. Rogers",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies/american_pie_2.jpg",
    releaseDate: "2001-08-10",
    rating: 0,
    length: 108,
    genre: "Comedy",
  },
  {
    title: "Rush Hour 2",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies/rush_hour_2.jpg",
    releaseDate: "2001-08-03",
    rating: 0,
    length: 90,
    genre: "Action",
  },
  {
    title: "Shaolin Soccer",
    director: "Stephen Chow",
    actors: [{ name: "Stephen Chow" }],
    coverUrl: "/movies/shaolin_soccer.jpg",
    releaseDate: "2001-07-12",
    rating: 0,
    length: 87,
    genre: "Comedy",
  },
  {
    title: "Scary Movie 2",
    director: "Keenen Ivory Wayans",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/scary_movie_2.jpg",
    releaseDate: "2001-07-04",
    rating: 0,
    length: 83,
    genre: "Comedy",
  },
  {
    title: "The Fast and the Furious",
    director: "Rob Cohen",
    actors: [{ name: "Vin Diesel" }],
    coverUrl: "/movies/fast_furious.jpg",
    releaseDate: "2001-06-22",
    rating: 0,
    length: 106,
    genre: "Action",
  },
  {
    title: "Lara Croft: Tomb Raider",
    director: "Simon West",
    actors: [{ name: "Angelina Jolie" }],
    coverUrl: "/movies/lara_croft_tomb_raider.jpg",
    releaseDate: "2001-06-15",
    rating: 0,
    length: 100,
    genre: "Action",
  },
  {
    title: "Pearl Harbor",
    director: "Michael Bay",
    actors: [{ name: "Ben Affleck" }],
    coverUrl: "/movies/pearl_harbor.jpg",
    releaseDate: "2001-05-25",
    rating: 0,
    length: 183,
    genre: "Drama",
  },
  {
    title: "Mulholland Drive",
    director: "David Lynch",
    actors: [{ name: "Naomi Watts" }],
    coverUrl: "/movies/mulholland_drive.jpg",
    releaseDate: "2001-10-12",
    rating: 0,
    length: 147,
    genre: "Mystery",
  },
  {
    title: "Replicant",
    director: "Ringo Lam",
    actors: [{ name: "Jean-Claude Van Damme" }],
    coverUrl: "/movies/replicant.jpg",
    releaseDate: "2001-05-04",
    rating: 0,
    length: 100,
    genre: "Action",
  },
  {
    title: "The Mummy Returns",
    director: "Stephen Sommers",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies/mummy_returns.jpg",
    releaseDate: "2001-05-04",
    rating: 0,
    length: 130,
    genre: "Adventure",
  },
  {
    title: "Shrek",
    director: "Andrew Adamson, Vicky Jenson",
    actors: [{ name: "Mike Myers" }],
    coverUrl: "/movies/shrek.jpg",
    releaseDate: "2001-05-18",
    rating: 0,
    length: 90,
    genre: "Animation",
  },
  {
    title: "Spy Kids",
    director: "Robert Rodriguez",
    actors: [{ name: "Alexa Vega" }],
    coverUrl: "/movies/spy_kids.jpg",
    releaseDate: "2001-03-30",
    rating: 0,
    length: 88,
    genre: "Adventure",
  },
  {
    title: "Battle Royale",
    director: "Kinji Fukasaku",
    actors: [{ name: "Tatsuya Fujiwara" }],
    coverUrl: "/movies/battle_royale.jpg",
    releaseDate: "2000-12-16",
    rating: 0,
    length: 114,
    genre: "Thriller",
  },
  {
    title: "Miss Congeniality",
    director: "Donald Petrie",
    actors: [{ name: "Sandra Bullock" }],
    coverUrl: "/movies/miss_congeniality.jpg",
    releaseDate: "2000-12-22",
    rating: 0,
    length: 111,
    genre: "Comedy",
  },
  {
    title: "What Women Want",
    director: "Nancy Meyers",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies/what_women_want.jpg",
    releaseDate: "2000-12-15",
    rating: 0,
    length: 127,
    genre: "Comedy",
  },
  {
    title: "Unbreakable",
    director: "M. Night Shyamalan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/unbreakable.jpg",
    releaseDate: "2000-11-22",
    rating: 0,
    length: 106,
    genre: "Thriller",
  },
  {
    title: "The 6th Day",
    director: "Roger Spottiswoode",
    actors: [{ name: "Arnold Schwarzenegger" }],
    coverUrl: "/movies/6th_day.jpg",
    releaseDate: "2000-11-17",
    rating: 0,
    length: 123,
    genre: "Science Fiction",
  },
  {
    title: "Memento",
    director: "Christopher Nolan",
    actors: [{ name: "Guy Pearce" }],
    coverUrl: "/movies/memento.jpg",
    releaseDate: "2000-09-05",
    rating: 0,
    length: 113,
    genre: "Thriller",
  },
  {
    title: "Snatch",
    director: "Guy Ritchie",
    actors: [{ name: "Jason Statham" }],
    coverUrl: "/movies/snatch.jpg",
    releaseDate: "2000-09-01",
    rating: 0,
    length: 104,
    genre: "Crime",
  },
  {
    title: "X-Men",
    director: "Bryan Singer",
    actors: [{ name: "Patrick Stewart" }],
    coverUrl: "/movies/xmen.jpg",
    releaseDate: "2000-07-14",
    rating: 0,
    length: 104,
    genre: "Action",
  },
  {
    title: "Scary Movie",
    director: "Keenen Ivory Wayans",
    actors: [{ name: "Anna Faris" }],
    coverUrl: "/movies/scary_movie.jpg",
    releaseDate: "2000-07-07",
    rating: 0,
    length: 88,
    genre: "Comedy",
  },
  {
    title: "Requiem for a Dream",
    director: "Darren Aronofsky",
    actors: [{ name: "Ellen Burstyn" }],
    coverUrl: "/movies/requiem_dream.jpg",
    releaseDate: "2000-10-06",
    rating: 0,
    length: 102,
    genre: "Drama",
  },
  {
    title: "O Brother, Where Art Thou?",
    director: "Joel Coen, Ethan Coen",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/o_brother.jpg",
    releaseDate: "2000-12-22",
    rating: 0,
    length: 107,
    genre: "Comedy",
  },
  {
    title: "Gladiator",
    director: "Ridley Scott",
    actors: [{ name: "Russell Crowe" }],
    coverUrl: "/movies/gladiator.jpg",
    releaseDate: "2000-05-05",
    rating: 0,
    length: 155,
    genre: "Action",
  },
  {
    title: "Taxi 2",
    director: "Gérard Krawczyk",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies/taxi_2.jpg",
    releaseDate: "2000-03-31",
    rating: 0,
    length: 88,
    genre: "Action",
  },
  {
    title: "Final Destination",
    director: "James Wong",
    actors: [{ name: "Devon Sawa" }],
    coverUrl: "/movies/final_destination.jpg",
    releaseDate: "2000-03-17",
    rating: 0,
    length: 98,
    genre: "Horror",
  },
  {
    title: "The Whole Nine Yards",
    director: "Jonathan Lynn",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/whole_nine_yards.jpg",
    releaseDate: "2000-02-18",
    rating: 0,
    length: 98,
    genre: "Comedy",
  },
  {
    title: "Scream 3",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies/scream_3.jpg",
    releaseDate: "2000-02-04",
    rating: 0,
    length: 116,
    genre: "Horror",
  },
  {
    title: "The Green Mile",
    director: "Frank Darabont",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/green_mile.jpg",
    releaseDate: "1999-12-10",
    rating: 0,
    length: 189,
    genre: "Drama",
  },
  {
    title: "Toy Story 2",
    director: "John Lasseter",
    actors: [{ name: "Tom Hanks" }],
    coverUrl: "/movies/toy_story_2.jpg",
    releaseDate: "1999-11-24",
    rating: 0,
    length: 92,
    genre: "Animation",
  },
  {
    title: "American Beauty",
    director: "Sam Mendes",
    actors: [{ name: "Kevin Spacey" }],
    coverUrl: "/movies/american_beauty.jpg",
    releaseDate: "1999-09-15",
    rating: 0,
    length: 122,
    genre: "Drama",
  },
  {
    title: "The Sixth Sense",
    director: "M. Night Shyamalan",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/sixth_sense.jpg",
    releaseDate: "1999-08-06",
    rating: 0,
    length: 107,
    genre: "Thriller",
  },
  {
    title: "American Pie",
    director: "Paul Weitz, Chris Weitz",
    actors: [{ name: "Jason Biggs" }],
    coverUrl: "/movies/american_pie.jpg",
    releaseDate: "1999-07-09",
    rating: 0,
    length: 95,
    genre: "Comedy",
  },
  {
    title: "Wild Wild West",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/wild_wild_west.jpg",
    releaseDate: "1999-06-30",
    rating: 0,
    length: 106,
    genre: "Comedy",
  },
  {
    title: "South Park: Bigger, Longer & Uncut",
    director: "Trey Parker",
    actors: [{ name: "Trey Parker" }],
    coverUrl: "/movies/south_park_movie.jpg",
    releaseDate: "1999-06-30",
    rating: 0,
    length: 81,
    genre: "Animation",
  },
  {
    title: "Tarzan",
    director: "Chris Buck, Kevin Lima",
    actors: [{ name: "Tony Goldwyn" }],
    coverUrl: "/movies/tarzan.jpg",
    releaseDate: "1999-06-18",
    rating: 0,
    length: 88,
    genre: "Animation",
  },
  {
    title: "Star Wars: Episode I – The Phantom Menace",
    director: "George Lucas",
    actors: [{ name: "Liam Neeson" }],
    coverUrl: "/movies/star_wars_phantom_menace.jpg",
    releaseDate: "1999-05-19",
    rating: 0,
    length: 136,
    genre: "Science Fiction",
  },
  {
    title: "Notting Hill",
    director: "Roger Michell",
    actors: [{ name: "Julia Roberts" }],
    coverUrl: "/movies/notting_hill.jpg",
    releaseDate: "1999-05-28",
    rating: 0,
    length: 124,
    genre: "Romance",
  },
  {
    title: "The Mummy",
    director: "Stephen Sommers",
    actors: [{ name: "Brendan Fraser" }],
    coverUrl: "/movies/mummy.jpg",
    releaseDate: "1999-05-07",
    rating: 0,
    length: 125,
    genre: "Adventure",
  },
  {
    title: "The Matrix",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/matrix.jpg",
    releaseDate: "1999-03-31",
    rating: 0,
    length: 136,
    genre: "Science Fiction",
  },
  {
    title: "Cruel Intentions",
    director: "Roger Kumble",
    actors: [{ name: "Sarah Michelle Gellar" }],
    coverUrl: "/movies/cruel_intentions.jpg",
    releaseDate: "1999-03-05",
    rating: 0,
    length: 97,
    genre: "Drama",
  },
  {
    title: "Meet Joe Black",
    director: "Martin Brest",
    actors: [{ name: "Brad Pitt" }],
    coverUrl: "/movies/meet_joe_black.jpg",
    releaseDate: "1998-11-13",
    rating: 2,
    length: 178,
    genre: "Drama",
  },
  {
    title: "Antz",
    director: "Eric Darnell, Tim Johnson",
    actors: [{ name: "Woody Allen" }],
    coverUrl: "/movies/antz.jpg",
    releaseDate: "1998-10-02",
    rating: 0,
    length: 83,
    genre: "Animation",
  },
  {
    title: "Rush Hour",
    director: "Brett Ratner",
    actors: [{ name: "Jackie Chan" }],
    coverUrl: "/movies/rush_hour.jpg",
    releaseDate: "1998-09-18",
    rating: 0,
    length: 98,
    genre: "Action",
  },
  {
    title: "Blade",
    director: "Stephen Norrington",
    actors: [{ name: "Wesley Snipes" }],
    coverUrl: "/movies/blade.jpg",
    releaseDate: "1998-08-21",
    rating: 0,
    length: 120,
    genre: "Action",
  },
  {
    title: "Lethal Weapon 4",
    director: "Richard Donner",
    actors: [{ name: "Mel Gibson" }],
    coverUrl: "/movies/lethal_weapon_4.jpg",
    releaseDate: "1998-07-10",
    rating: 0,
    length: 127,
    genre: "Action",
  },
  {
    title: "Armageddon",
    director: "Michael Bay",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/armageddon.jpg",
    releaseDate: "1998-07-01",
    rating: 0,
    length: 151,
    genre: "Action",
  },
  {
    title: "Mulan",
    director: "Tony Bancroft, Barry Cook",
    actors: [{ name: "Ming-Na Wen" }],
    coverUrl: "/movies/mulan.jpg",
    releaseDate: "1998-06-19",
    rating: 0,
    length: 88,
    genre: "Animation",
  },
  {
    title: "The Truman Show",
    director: "Peter Weir",
    actors: [{ name: "Jim Carrey" }],
    coverUrl: "/movies/truman_show.jpg",
    releaseDate: "1998-06-05",
    rating: 0,
    length: 103,
    genre: "Drama",
  },
  {
    title: "Godzilla",
    director: "Roland Emmerich",
    actors: [{ name: "Matthew Broderick" }],
    coverUrl: "/movies/godzilla.jpg",
    releaseDate: "1998-05-20",
    rating: 0,
    length: 139,
    genre: "Action",
  },
  {
    title: "The Dinner Game",
    director: "Francis Veber",
    actors: [{ name: "Thierry Lhermitte" }],
    coverUrl: "/movies/dinner_game.jpg",
    releaseDate: "1998-04-15",
    rating: 0,
    length: 80,
    genre: "Comedy",
  },
  {
    title: "Taxi",
    director: "Gérard Pirès",
    actors: [{ name: "Samy Naceri" }],
    coverUrl: "/movies/taxi.jpg",
    releaseDate: "1998-04-08",
    rating: 0,
    length: 86,
    genre: "Action",
  },
  {
    title: "Mercury Rising",
    director: "Harold Becker",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/mercury_rising.jpg",
    releaseDate: "1998-04-03",
    rating: 0,
    length: 111,
    genre: "Thriller",
  },
  {
    title: "The Big Lebowski",
    director: "Joel Coen, Ethan Coen",
    actors: [{ name: "Jeff Bridges" }],
    coverUrl: "/movies/big_lebowski.jpg",
    releaseDate: "1998-03-06",
    rating: 0,
    length: 117,
    genre: "Comedy",
  },
  {
    title: "Scream 2",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies/scream_2.jpg",
    releaseDate: "1997-12-12",
    rating: 0,
    length: 120,
    genre: "Horror",
  },
  {
    title: "Good Will Hunting",
    director: "Gus Van Sant",
    actors: [{ name: "Matt Damon" }],
    coverUrl: "/movies/good_will_hunting.jpg",
    releaseDate: "1997-12-05",
    rating: 0,
    length: 126,
    genre: "Drama",
  },
  {
    title: "Alien Resurrection",
    director: "Jean-Pierre Jeunet",
    actors: [{ name: "Sigourney Weaver" }],
    coverUrl: "/movies/alien_resurrection.jpg",
    releaseDate: "1997-11-26",
    rating: 0,
    length: 109,
    genre: "Science Fiction",
  },
  {
    title: "I Know What You Did Last Summer",
    director: "Jim Gillespie",
    actors: [{ name: "Jennifer Love Hewitt" }],
    coverUrl: "/movies/i_know_what_you_did.jpg",
    releaseDate: "1997-10-17",
    rating: 0,
    length: 101,
    genre: "Horror",
  },
  {
    title: "The Devil's Advocate",
    director: "Taylor Hackford",
    actors: [{ name: "Keanu Reeves" }],
    coverUrl: "/movies/devils_advocate.jpg",
    releaseDate: "1997-10-17",
    rating: 0,
    length: 144,
    genre: "Thriller",
  },
  {
    title: "Princess Mononoke",
    director: "Hayao Miyazaki",
    actors: [{ name: "Yôji Matsuda" }],
    coverUrl: "/movies/princess_mononoke.jpg",
    releaseDate: "1997-07-12",
    rating: 0,
    length: 134,
    genre: "Animation",
  },
  {
    title: "Men in Black",
    director: "Barry Sonnenfeld",
    actors: [{ name: "Will Smith" }],
    coverUrl: "/movies/men_in_black.jpg",
    releaseDate: "1997-07-02",
    rating: 0,
    length: 98,
    genre: "Action",
  },
  {
    title: "Hercules",
    director: "Ron Clements, John Musker",
    actors: [{ name: "Tate Donovan" }],
    coverUrl: "/movies/hercules.jpg",
    releaseDate: "1997-06-27",
    rating: 0,
    length: 93,
    genre: "Animation",
  },
  {
    title: "Batman & Robin",
    director: "Joel Schumacher",
    actors: [{ name: "George Clooney" }],
    coverUrl: "/movies/batman_robin.jpg",
    releaseDate: "1997-06-20",
    rating: 0,
    length: 125,
    genre: "Action",
  },
  {
    title: "The Fifth Element",
    director: "Luc Besson",
    actors: [{ name: "Bruce Willis" }],
    coverUrl: "/movies/fifth_element.jpg",
    releaseDate: "1997-05-09",
    rating: 0,
    length: 126,
    genre: "Science Fiction",
  },
  {
    title: "Scream",
    director: "Wes Craven",
    actors: [{ name: "Neve Campbell" }],
    coverUrl: "/movies/scream.jpg",
    releaseDate: "1996-12-20",
    rating: 0,
    length: 111,
    genre: "Horror",
  },
];