import { Movie } from './movies_1';

export const moviesOtherSuperheroes: Movie[] = [
  {
    title: 'Deadpool',
    director: 'Tim Miller',
    actors: [{ name: 'Ryan Reynolds' }],
    coverUrl: '/movies_pictures/220575-deadpool-0-150-0-225-crop.jpg',
    releaseDate: '2016-02-12',
    rating: 3.75,
    length: 108,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Deadpool 2',
    director: 'David Leitch',
    actors: [
      {
        name: 'Ryan Reynolds',
      },
    ],
    coverUrl: '/movies_pictures/318195-deadpool-2-0-150-0-225-crop.jpg',
    releaseDate: '2018-05-18',
    rating: 3.25,
    length: 119,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Daredevil',
    director: 'Mark Steven Johnson',
    actors: [{ name: 'Ben Affleck' }],
    coverUrl: '/movies_pictures/daredevil.jpg',
    releaseDate: '2003-02-14',
    rating: 3.5,
    length: 103,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'X-Men',
    director: 'Bryan Singer',
    actors: [{ name: 'Patrick Stewart' }],
    coverUrl: '/movies_pictures/27723-x-men-0-150-0-225-crop.jpg',
    releaseDate: '2000-07-14',
    rating: 3.5,
    length: 104,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'X-men 2',
    director: 'Bryan Singer',
    actors: [{ name: 'Patrick Stewart' }],
    coverUrl: '/movies_pictures/xmen2-poster-0-150-0-225-crop.jpg',
    releaseDate: '2003-05-02',
    rating: 3.25,
    length: 134,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: "X-Men : L'Affrontement Final",
    director: 'Brett Ratner',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl:
      '/movies_pictures/27713-x-men-the-last-stand-0-150-0-225-crop.jpg',
    releaseDate: '2006-05-26',
    rating: 3.75,
    length: 104,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'X-Men Origins : Wolverine',
    director: 'Gavin Hood',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl:
      '/movies_pictures/50544-x-men-origins-wolverine-0-150-0-225-crop.jpg',
    releaseDate: '2009-05-01',
    rating: 3,
    length: 107,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'The Wolverine',
    director: 'James Mangold',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl: '/movies_pictures/62638-the-wolverine-0-150-0-225-crop.jpg',
    releaseDate: '2013-07-26',
    rating: 3.25,
    length: 126,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Logan',
    director: 'James Mangold',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl: '/movies_pictures/logan.jpg',
    releaseDate: '2017-03-03',
    rating: 3.75,
    length: 137,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'X-Men : Le Commencement',
    director: 'Matthew Vaughn',
    actors: [{ name: 'James McAvoy' }],
    coverUrl: '/movies_pictures/16074-x-men-first-class-0-150-0-225-crop.jpg',
    releaseDate: '2011-06-03',
    rating: 4,
    length: 132,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'X-Men : Days of Future Past',
    director: 'Bryan Singer',
    actors: [{ name: 'Hugh Jackman' }],
    coverUrl:
      '/movies_pictures/99507-x-men-days-of-future-past-0-150-0-225-crop.jpg',
    releaseDate: '2014-05-23',
    rating: 3.75,
    length: 132,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'X-Men : Apocalypse',
    director: 'Bryan Singer',
    actors: [{ name: 'James McAvoy' }],
    coverUrl: '/movies_pictures/172492-x-men-apocalypse-0-150-0-225-crop.jpg',
    releaseDate: '2016-05-27',
    rating: 3.5,
    length: 144,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'X-Men :Dark Phoenix',
    director: 'Simon Kinberg',
    actors: [
      {
        name: 'Sophie Turner',
      },
    ],
    coverUrl: '/movies_pictures/247385-dark-phoenix-0-150-0-225-crop.jpg',
    releaseDate: '2019-06-07',
    rating: 3.25,
    length: 114,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Venom',
    director: 'Ruben Fleischer',
    actors: [
      {
        name: 'Tom Hardy',
      },
    ],
    coverUrl: '/movies_pictures/265438-venom-0-150-0-225-crop.jpg',
    releaseDate: '2018-10-05',
    rating: 3.5,
    length: 112,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Venom : Let There Be Carnage',
    director: 'Andy Serkis',
    actors: [
      {
        name: 'Tom Hardy',
      },
    ],
    coverUrl:
      '/movies_pictures/508638-venom-let-there-be-carnage-0-150-0-225-crop.jpg',
    releaseDate: '2021-10-01',
    rating: 3.25,
    length: 97,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Spider-Man',
    director: 'Sam Raimi',
    actors: [{ name: 'Tobey Maguire' }],
    coverUrl: '/movies_pictures/51561-spider-man-0-150-0-225-crop.jpg',
    releaseDate: '2002-05-03',
    rating: 4.5,
    length: 121,
    genre: 'Action',
    timesWatched: 40,
    lastViewedDate: '',
  },
  {
    title: 'Spider-Man 2',
    director: 'Sam Raimi',
    actors: [{ name: 'Tobey Maguire' }],
    coverUrl: '/movies_pictures/amazin_spiderman_2.jpg',
    releaseDate: '2004-06-30',
    rating: 4.25,
    length: 127,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Spider-Man 3',
    director: 'Sam Raimi',
    actors: [{ name: 'Tobey Maguire' }],
    coverUrl: '/movies_pictures/spiderman_3.jpg',
    releaseDate: '2007-05-04',
    rating: 3.75,
    length: 139,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'The Amazing Spider-Man',
    director: 'Marc Webb',
    actors: [{ name: 'Andrew Garfield' }],
    coverUrl:
      '/movies_pictures/50677-the-amazing-spider-man-0-150-0-225-crop.jpg',
    releaseDate: '2012-07-03',
    rating: 4,
    length: 136,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: "The Amazing Spider-Man : Le Destin d'un Héros",
    director: 'Marc Webb',
    actors: [{ name: 'Andrew Garfield' }],
    coverUrl: '/movies_pictures/47306-final-destination-3-0-150-0-225-crop.jpg',
    releaseDate: '2014-05-02',
    rating: 3.5,
    length: 142,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Kick-Ass',
    director: 'Matthew Vaughn',
    actors: [{ name: 'Aaron Taylor-Johnson' }],
    coverUrl: '/movies_pictures/kick_ass.jpg',
    releaseDate: '2010-04-16',
    rating: 3.75,
    length: 117,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Kick-Ass 2',
    director: 'Jeff Wadlow',
    actors: [{ name: 'Aaron Taylor-Johnson' }],
    coverUrl: '/movies_pictures/kick_ass_2.jpg',
    releaseDate: '2013-08-16',
    rating: 3.25,
    length: 103,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Hancock',
    director: 'Peter Berg',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/hancock.jpg',
    releaseDate: '2008-07-02',
    rating: 3.75,
    length: 92,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Les 4 Fantastiques',
    director: 'Tim Story',
    actors: [{ name: 'Ioan Gruffudd' }],
    coverUrl: '/movies_pictures/46869-fantastic-four-0-150-0-225-crop.jpg',
    releaseDate: '2005-07-08',
    rating: 3.75,
    length: 106,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: "Les 4 Fantastiques et le Surfeur d'Argent",
    director: 'Tim Story',
    actors: [{ name: 'Ioan Gruffudd' }],
    coverUrl:
      '/movies_pictures/50631-fantastic-four-rise-of-the-silver-surfer-0-150-0-225-crop.jpg',
    releaseDate: '2007-06-15',
    rating: 3.75,
    length: 92,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Ghost Rider',
    director: 'Mark Steven Johnson',
    actors: [{ name: 'Nicolas Cage' }],
    coverUrl: '/movies_pictures/51130-ghost-rider-0-150-0-225-crop.jpg',
    releaseDate: '2007-02-16',
    rating: 3.25,
    length: 114,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Sky High',
    director: 'Mike Mitchell',
    actors: [{ name: 'Michael Angarano' }],
    coverUrl: '/movies_pictures/45283-sky-high-0-150-0-225-crop.jpg',
    releaseDate: '2005-07-29',
    rating: 3.25,
    length: 100,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Hulk',
    director: 'Ang Lee',
    actors: [{ name: 'Eric Bana' }],
    coverUrl: '/movies_pictures/50678-hulk-0-150-0-225-crop.jpg',
    releaseDate: '2003-06-20',
    rating: 3,
    length: 138,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'The Punisher',
    director: 'Jonathan Hensleigh',
    actors: [{ name: 'John Travolta' }],
    coverUrl: '/movies_pictures/18379323.jpg',
    releaseDate: '2004-04-16',
    rating: 4,
    length: 124,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Les 4 Fantastiques',
    director: 'Josh Trank',
    actors: [{ name: 'Miles Teller' }],
    coverUrl: '/movies_pictures/123065-fantastic-four-0-150-0-225-crop.jpg',
    releaseDate: '2015-08-07',
    rating: 2.75,
    length: 100,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
