import { Movie } from '../../../models/movie-model';

export const moviesPage5: Movie[] = [
  {
    title: 'Les Tuche',
    director: 'Olivier Baroux',
    actors: [{ name: 'Jean-Paul Rouve' }],
    coverUrl: '/movies_pictures/les_tuche.jpg',
    releaseDate: '2011-06-29',
    rating: 3.75,
    length: 95,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Comment tuer son boss',
    director: 'Seth Gordon',
    actors: [{ name: 'Jason Bateman' }],
    coverUrl: '/movies_pictures/horrible_bosses.jpg',
    releaseDate: '2011-07-08',
    rating: 2.75,
    length: 98,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Super 8',
    director: 'J.J. Abrams',
    actors: [{ name: 'Joel Courtney' }],
    coverUrl: '/movies_pictures/super_8.jpg',
    releaseDate: '2011-06-10',
    rating: 3.75,
    length: 112,
    genre: 'Science Fiction',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Drive',
    director: 'Nicolas Winding Refn',
    actors: [{ name: 'Ryan Gosling' }],
    coverUrl: '/movies_pictures/drive.jpg',
    releaseDate: '2011-09-16',
    rating: 1,
    length: 100,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Artist',
    director: 'Michel Hazanavicius',
    actors: [{ name: 'Jean Dujardin' }],
    coverUrl: '/movies_pictures/the_artist.jpg',
    releaseDate: '2011-11-23',
    rating: 3,
    length: 100,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2011-11-23',
  },
  {
    title: 'Sucker Punch',
    director: 'Zack Snyder',
    actors: [{ name: 'Emily Browning' }],
    coverUrl: '/movies_pictures/sucker-punch-original-0-150-0-225-crop.jpg',
    releaseDate: '2011-03-25',
    rating: 2.5,
    length: 110,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Paul',
    director: 'Greg Mottola',
    actors: [{ name: 'Simon Pegg' }],
    coverUrl: '/movies_pictures/paul.jpg',
    releaseDate: '2011-03-18',
    rating: 3.25,
    length: 104,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'The Social Network',
    director: 'David Fincher',
    actors: [{ name: 'Jesse Eisenberg' }],
    coverUrl: '/movies_pictures/the_social_network.jpg',
    releaseDate: '2010-10-01',
    rating: 4.25,
    length: 120,
    genre: 'Drama',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: '127 Heures',
    director: 'Danny Boyle',
    actors: [{ name: 'James Franco' }],
    coverUrl: '/movies_pictures/21050-127-hours-0-150-0-225-crop.jpg',
    releaseDate: '2010-11-05',
    rating: 3.25,
    length: 94,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Black Swan',
    director: 'Darren Aronofsky',
    actors: [{ name: 'Natalie Portman' }],
    coverUrl: '/movies_pictures/black_swan.jpg',
    releaseDate: '2010-12-03',
    rating: 3.25,
    length: 108,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Expendables : Unité Spéciale',
    director: 'Sylvester Stallone',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/34395-the-expendables-0-150-0-225-crop.jpg',
    releaseDate: '2010-08-13',
    rating: 2.75,
    length: 103,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Inception',
    director: 'Christopher Nolan',
    actors: [{ name: 'Leonardo DiCaprio' }],
    coverUrl: '/movies_pictures/inception-0-150-0-225-crop.jpg',
    releaseDate: '2010-07-16',
    rating: 3.75,
    length: 148,
    genre: 'Science Fiction',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Fatal',
    director: 'Michaël Youn',
    actors: [{ name: 'Michaël Youn' }],
    coverUrl: '/movies_pictures/19718-fatal-0-150-0-225-crop.jpg',
    releaseDate: '2010-06-30',
    rating: 4.25,
    length: 85,
    genre: 'Comedy',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'The Karate Kid',
    director: 'Harald Zwart',
    actors: [{ name: 'Jaden Smith' }],
    coverUrl: '/movies_pictures/26025-the-karate-kid-0-150-0-225-crop.jpg',
    releaseDate: '2010-06-11',
    rating: 3.5,
    length: 140,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Le Choc des Titans',
    director: 'Louis Leterrier',
    actors: [{ name: 'Sam Worthington' }],
    coverUrl: '/movies_pictures/40075-clash-of-the-titans-0-150-0-225-crop.jpg',
    releaseDate: '2010-04-02',
    rating: 3,
    length: 106,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Alice au Pays des Merveilles',
    director: 'Tim Burton',
    actors: [{ name: 'Johnny Depp' }],
    coverUrl:
      '/movies_pictures/alice-in-wonderland-original-0-150-0-225-crop.jpg',
    releaseDate: '2010-03-05',
    rating: 3.25,
    length: 108,
    genre: 'Fantasy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Shutter Island',
    director: 'Martin Scorsese',
    actors: [{ name: 'Leonardo DiCaprio' }],
    coverUrl: '/movies_pictures/45409-shutter-island-0-150-0-225-crop.jpg',
    releaseDate: '2010-02-19',
    rating: 2.75,
    length: 138,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Percy Jackson : Le Voleur de Foudre',
    director: 'Chris Columbus',
    actors: [{ name: 'Logan Lerman' }],
    coverUrl:
      '/movies_pictures/30264-percy-jackson-the-olympians-the-lightning-thief-0-150-0-225-crop.jpg',
    releaseDate: '2010-02-12',
    rating: 2.75,
    length: 118,
    genre: 'Fantasy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Brothers',
    director: 'Jim Sheridan',
    actors: [{ name: 'Tobey Maguire' }],
    coverUrl: '/movies_pictures/48031-brothers-0-150-0-225-crop.jpg',
    releaseDate: '2009-12-04',
    rating: 3.5,
    length: 105,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Lucky Luke',
    director: 'James Huth',
    actors: [{ name: 'Jean Dujardin' }],
    coverUrl: '/movies_pictures/28805-lucky-luke-0-150-0-225-crop.jpg',
    releaseDate: '2009-10-21',
    rating: 2.75,
    length: 103,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le beau-père',
    director: 'Nelson McCormick',
    actors: [{ name: 'Dylan Walsh' }],
    coverUrl: '/movies_pictures/39354-the-stepfather-0-150-0-225-crop.jpg',
    releaseDate: '2009-10-16',
    rating: 3.25,
    length: 101,
    genre: 'Thriller',
    timesWatched: 5,
    lastViewedDate: '2025-04-16',
  },
  {
    title: '2012',
    director: 'Roland Emmerich',
    actors: [{ name: 'John Cusack' }],
    coverUrl: '/movies_pictures/43301-2012-0-150-0-225-crop.jpg',
    releaseDate: '2009-11-13',
    rating: 3.5,
    length: 158,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Zombieland',
    director: 'Ruben Fleischer',
    actors: [{ name: 'Jesse Eisenberg' }],
    coverUrl: '/movies_pictures/39352-zombieland-0-150-0-225-crop.jpg',
    releaseDate: '2009-10-02',
    rating: 3.75,
    length: 88,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'The Blind Side',
    director: 'John Lee Hancock',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/the-blind-side-0-150-0-225-crop.jpg',
    releaseDate: '2009-11-20',
    rating: 5,
    length: 129,
    genre: 'Drama',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Mr. Nobody',
    director: 'Jaco Van Dormael',
    actors: [{ name: 'Jared Leto' }],
    coverUrl: '/movies_pictures/mr_nobody.jpg',
    releaseDate: '2009-09-12',
    rating: 3.25,
    length: 141,
    genre: 'Science Fiction',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Coco',
    director: 'Lee Unkrich',
    actors: [{ name: 'Anthony Gonzalez' }],
    coverUrl: '/movies_pictures/39968-coco-0-150-0-225-crop.jpg',
    releaseDate: '2017-11-22',
    rating: 3,
    length: 105,
    genre: 'Animation',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Inglourious Basterds',
    director: 'Quentin Tarantino',
    actors: [{ name: 'Brad Pitt' }],
    coverUrl:
      '/movies_pictures/41352-inglourious-basterds-0-150-0-225-crop.jpg',
    releaseDate: '2009-08-21',
    rating: 3.5,
    length: 153,
    genre: 'War',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Hypertension',
    director: 'Neveldine/Taylor',
    actors: [{ name: 'Jason Statham' }],
    coverUrl: '/movies_pictures/42603-crank-high-voltage-0-150-0-225-crop.jpg',
    releaseDate: '2009-04-17',
    rating: 3,
    length: 96,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Piège en haute mer',
    director: 'Andrew Davis',
    actors: [{ name: 'Steven Seagal' }],
    coverUrl: '/movies_pictures/47576-under-siege-0-150-0-225-crop.jpg',
    releaseDate: '1992-10-09',
    rating: 3,
    length: 103,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Basic Instinct',
    director: 'Paul Verhoeven',
    actors: [{ name: 'Michael Douglas' }],
    coverUrl: '/movies_pictures/basic_instinct.jpg',
    releaseDate: '1992-03-20',
    rating: 3.25,
    length: 128,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Reservoir Dogs',
    director: 'Quentin Tarantino',
    actors: [{ name: 'Harvey Keitel' }],
    coverUrl: '/movies_pictures/reservoir_dogs.jpg',
    releaseDate: '1992-10-23',
    rating: 3.25,
    length: 99,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le dernier samaritain',
    director: 'Tony Scott',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/le_dernier_samaritain.jpg',
    releaseDate: '1991-12-13',
    rating: 3.75,
    length: 105,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Double Impact',
    director: 'Sheldon Lettich',
    actors: [{ name: 'Jean-Claude Van Damme' }],
    coverUrl: '/movies_pictures/47007-double-impact-0-150-0-225-crop.jpg',
    releaseDate: '1991-08-09',
    rating: 3,
    length: 110,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Point Break',
    director: 'Kathryn Bigelow',
    actors: [{ name: 'Patrick Swayze' }],
    coverUrl: '/movies_pictures/51157-point-break-0-150-0-225-crop.jpg',
    releaseDate: '1991-07-12',
    rating: 3.5,
    length: 122,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Les Affranchis',
    director: 'Martin Scorsese',
    actors: [{ name: 'Robert De Niro' }],
    coverUrl: '/movies_pictures/51383-goodfellas-0-150-0-225-crop.jpg',
    releaseDate: '1990-09-19',
    rating: 3.5,
    length: 146,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Total Recall',
    director: 'Paul Verhoeven',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/51291-total-recall-0-150-0-225-crop.jpg',
    releaseDate: '1990-06-01',
    rating: 3,
    length: 113,
    genre: 'Science Fiction',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Nikita',
    director: 'Luc Besson',
    actors: [{ name: 'Anne Parillaud' }],
    coverUrl: '/movies_pictures/47271-la-femme-nikita-0-150-0-225-crop.jpg',
    releaseDate: '1990-02-21',
    rating: 3.5,
    length: 117,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Last Action Hero',
    director: 'John McTiernan',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/47008-last-action-hero-0-150-0-225-crop.jpg',
    releaseDate: '1993-06-18',
    rating: 3.75,
    length: 130,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Jurassic Park',
    director: 'Steven Spielberg',
    actors: [{ name: 'Sam Neill' }],
    coverUrl: '/movies_pictures/jurassic_park.jpg',
    releaseDate: '1993-06-11',
    rating: 3.25,
    length: 127,
    genre: 'Adventure',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Cliffhanger',
    director: 'Renny Harlin',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/47244-cliffhanger-0-150-0-225-crop.jpg',
    releaseDate: '1993-05-28',
    rating: 3.25,
    length: 113,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Les visiteurs',
    director: 'Jean-Marie Poiré',
    actors: [{ name: 'Jean Reno' }],
    coverUrl: '/movies_pictures/45066-the-visitors-0-150-0-225-crop.jpg',
    releaseDate: '1993-01-27',
    rating: 3.5,
    length: 107,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Demolition Man',
    director: 'Marco Brambilla',
    actors: [{ name: 'Sylvester Stallone' }],
    coverUrl: '/movies_pictures/46868-demolition-man-0-150-0-225-crop.jpg',
    releaseDate: '1993-10-08',
    rating: 4.5,
    length: 115,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Le fugitif',
    director: 'Andrew Davis',
    actors: [{ name: 'Harrison Ford' }],
    coverUrl: '/movies_pictures/48823-the-fugitive-0-150-0-225-crop.jpg',
    releaseDate: '1993-08-06',
    rating: 3.25,
    length: 130,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
];
