import { Movie } from '../../../models/movie-model';

export const moviesPage2: Movie[] = [
  {
    title: 'Chaos Walking',
    director: 'Doug Liman',
    actors: [
      {
        name: 'Tom Holland',
      },
    ],
    coverUrl: '/movies_pictures/346746-chaos-walking-0-150-0-225-crop.jpg',
    releaseDate: '2021-03-05',
    rating: 3,
    length: 109,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Love and Monsters',
    director: 'Michael Matthews',
    actors: [
      {
        name: "Dylan O'Brien",
      },
    ],
    coverUrl: '/movies_pictures/517828-love-and-monsters-0-150-0-225-crop.jpg',
    releaseDate: '2020-10-16',
    rating: 3.75,
    length: 109,
    genre: 'Adventure',
    timesWatched: 2,
    lastViewedDate: '2025-03-16',
  },
  {
    title: 'Tenet',
    director: 'Christopher Nolan',
    actors: [
      {
        name: 'John David Washington',
      },
    ],
    coverUrl:
      '/movies_pictures/aCIFMriQh8rvhxpN1IWGgvH0Tlg-0-150-0-225-crop.jpg',
    releaseDate: '2020-09-03',
    rating: 3.25,
    length: 150,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Ava',
    director: 'Tate Taylor',
    actors: [
      {
        name: 'Jessica Chastain',
      },
    ],
    coverUrl: '/movies_pictures/468851-ava-0-150-0-225-crop.jpg',
    releaseDate: '2020-07-02',
    rating: 3,
    length: 96,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Mulan',
    director: 'Niki Caro',
    actors: [
      {
        name: 'Yifei Liu',
      },
    ],
    coverUrl: '/movies_pictures/mulan.jpg',
    releaseDate: '2020-09-04',
    rating: 3.25,
    length: 115,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Palm Springs',
    director: 'Max Barbakow',
    actors: [
      {
        name: 'Andy Samberg',
      },
    ],
    coverUrl: '/movies_pictures/515467-palm-springs-0-150-0-225-crop.jpg',
    releaseDate: '2020-07-10',
    rating: 4,
    length: 90,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '2022-02-10',
  },
  {
    title: 'Guns Akimbo',
    director: 'Jason Lei Howden',
    actors: [
      {
        name: 'Daniel Radcliffe',
      },
    ],
    coverUrl: '/movies_pictures/389270-guns-akimbo-0-150-0-225-crop.jpg',
    releaseDate: '2020-02-28',
    rating: 3.5,
    length: 95,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2020-02-28',
  },
  {
    title: 'Joker',
    director: 'Todd Phillips',
    actors: [
      {
        name: 'Joaquin Phoenix',
      },
    ],
    coverUrl: '/movies_pictures/406775-joker-0-150-0-225-crop.jpg',
    releaseDate: '2019-10-04',
    rating: 3.5,
    length: 122,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '2019-10-04',
  },
  {
    title: 'Someone, Somewhere',
    director: 'Cédric Klapisch',
    actors: [
      {
        name: 'Ana Girardot',
      },
    ],
    coverUrl: '/movies_pictures/511412-someone-somewhere-0-150-0-225-crop.jpg',
    releaseDate: '2019-09-25',
    rating: 3,
    length: 110,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Escape Plan: The Extractors',
    director: 'John Herzfeld',
    actors: [
      {
        name: 'Sylvester Stallone',
      },
    ],
    coverUrl:
      '/movies_pictures/411041-escape-plan-the-extractors-0-150-0-225-crop.jpg',
    releaseDate: '2019-07-02',
    rating: 2.5,
    length: 97,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Aladdin',
    director: 'Guy Ritchie',
    actors: [
      {
        name: 'Will Smith',
      },
    ],
    coverUrl: '/movies_pictures/354538-aladdin-0-150-0-225-crop.jpg',
    releaseDate: '2019-05-24',
    rating: 3.5,
    length: 128,
    genre: 'Fantasy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Alita: Battle Angel',
    director: 'Robert Rodriguez',
    actors: [
      {
        name: 'Rosa Salazar',
      },
    ],
    coverUrl: '/movies_pictures/333832-alita-battle-angel-0-150-0-225-crop.jpg',
    releaseDate: '2019-02-14',
    rating: 3.75,
    length: 122,
    genre: 'Science Fiction',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Le chant du loup',
    director: 'Antonin Baudry',
    actors: [
      {
        name: 'François Civil',
      },
    ],
    coverUrl: '/movies_pictures/415280-the-wolf-s-call-0-150-0-225-crop.jpg',
    releaseDate: '2019-02-20',
    rating: 4,
    length: 115,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Bird Box',
    director: 'Susanne Bier',
    actors: [
      {
        name: 'Sandra Bullock',
      },
    ],
    coverUrl: '/movies_pictures/340202-bird-box-0-150-0-225-crop.jpg',
    releaseDate: '2018-12-21',
    rating: 3.5,
    length: 124,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'A Star Is Born',
    director: 'Bradley Cooper',
    actors: [
      {
        name: 'Lady Gaga',
      },
    ],
    coverUrl: '/movies_pictures/261108-a-star-is-born-0-150-0-225-crop.jpg',
    releaseDate: '2018-10-05',
    rating: 3.5,
    length: 136,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Escape Plan 2: Hades',
    director: 'Steven C. Miller',
    actors: [
      {
        name: 'Sylvester Stallone',
      },
    ],
    coverUrl:
      '/movies_pictures/373180-escape-plan-2-hades-0-150-0-225-crop.jpg',
    releaseDate: '2018-06-29',
    rating: 2.75,
    length: 93,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Ready Player One',
    director: 'Steven Spielberg',
    actors: [
      {
        name: 'Tye Sheridan',
      },
    ],
    coverUrl: '/movies_pictures/261866-ready-player-one-0-150-0-225-crop.jpg',
    releaseDate: '2018-03-29',
    rating: 5,
    length: 140,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },

  {
    title: 'E.T. the Extra-Terrestrial',
    director: 'Steven Spielberg',
    actors: [{ name: 'Henry Thomas' }],
    coverUrl:
      '/movies_pictures/51520-e-t-the-extra-terrestrial-0-150-0-225-crop.jpg',
    releaseDate: '1982-06-11',
    rating: 3.75,
    length: 115,
    genre: 'Science Fiction',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'La soupe aux choux',
    director: 'Jean-Charles Tacchella',
    actors: [{ name: 'Philippe Noiret' }],
    coverUrl: '/movies_pictures/47276-the-cabbage-soup-0-150-0-225-crop.jpg',
    releaseDate: '1981-12-16',
    rating: 3.25,
    length: 100,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'The Shining',
    director: 'Stanley Kubrick',
    actors: [{ name: 'Jack Nicholson' }],
    coverUrl: '/movies_pictures/the_shining.jpg',
    releaseDate: '1980-05-23',
    rating: 3.25,
    length: 146,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "L'aile ou la cuisse",
    director: 'Claude Zidi',
    actors: [{ name: 'Louis de Funès' }],
    coverUrl:
      '/movies_pictures/51391-the-wing-or-the-thigh--0-150-0-225-crop.jpg',
    releaseDate: '1976-10-27',
    rating: 3,
    length: 104,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Taxi Driver',
    director: 'Martin Scorsese',
    actors: [{ name: 'Robert De Niro' }],
    coverUrl: '/movies_pictures/51947-taxi-driver-0-150-0-225-crop.jpg',
    releaseDate: '1976-02-08',
    rating: 2,
    length: 114,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "L'exorciste",
    director: 'William Friedkin',
    actors: [{ name: 'Ellen Burstyn' }],
    coverUrl: '/movies_pictures/47048-the-exorcist-0-150-0-225-crop.jpg',
    releaseDate: '1973-12-26',
    rating: 2.5,
    length: 122,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les aventures de Rabbi Jacob',
    director: 'Gérard Oury',
    actors: [{ name: 'Louis de Funès' }],
    coverUrl:
      '/movies_pictures/51392-the-mad-adventures-of-rabbi-jacob-0-150-0-225-crop.jpg',
    releaseDate: '1973-10-17',
    rating: 2.75,
    length: 95,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'La Folie des grandeurs',
    director: 'Gérard Oury',
    actors: [{ name: 'Louis de Funès' }],
    coverUrl:
      '/movies_pictures/43223-delusions-of-grandeur-0-150-0-225-crop.jpg',
    releaseDate: '1971-12-08',
    rating: 3,
    length: 95,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Oscar',
    director: 'Édouard Molinaro',
    actors: [{ name: 'Louis de Funès' }],
    coverUrl: '/movies_pictures/50079-oscar-0-150-0-225-crop.jpg',
    releaseDate: '1967-10-11',
    rating: 4,
    length: 85,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Fantomas',
    director: 'André Hunebelle',
    actors: [{ name: 'Jean Marais' }],
    coverUrl: '/movies_pictures/50732-fantomas-0-150-0-225-crop.jpg',
    releaseDate: '1964-11-04',
    rating: 3,
    length: 105,
    genre: 'Adventure',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Le Gendarme de Saint-Tropez',
    director: 'Jean Girault',
    actors: [{ name: 'Louis de Funès' }],
    coverUrl:
      '/movies_pictures/49168-le-gendarme-de-saint-tropez-0-150-0-225-crop.jpg',
    releaseDate: '1964-09-09',
    rating: 3,
    length: 95,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Les oiseaux',
    director: 'Alfred Hitchcock',
    actors: [{ name: 'Tippi Hedren' }],
    coverUrl: '/movies_pictures/51549-the-birds-0-150-0-225-crop.jpg',
    releaseDate: '1963-03-28',
    rating: 3.25,
    length: 119,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Psychose',
    director: 'Alfred Hitchcock',
    actors: [{ name: 'Anthony Perkins' }],
    coverUrl: '/movies_pictures/51578-psycho-0-150-0-225-crop.jpg',
    releaseDate: '1960-06-16',
    rating: 3.5,
    length: 109,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: '12 hommes en colère',
    director: 'Sidney Lumet',
    actors: [{ name: 'Henry Fonda' }],
    coverUrl: '/movies_pictures/51700-12-angry-men-0-150-0-225-crop.jpg',
    releaseDate: '1957-04-10',
    rating: 4,
    length: 96,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-04-10',
  },
  {
    title: 'Citizen Kane',
    director: 'Orson Welles',
    actors: [{ name: 'Orson Welles' }],
    coverUrl: '/movies_pictures/2702-citizen-kane-0-150-0-225-crop.jpg',
    releaseDate: '1941-05-01',
    rating: 3,
    length: 119,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les temps modernes',
    director: 'Charles Chaplin',
    actors: [{ name: 'Charles Chaplin' }],
    coverUrl: '/movies_pictures/49889-modern-times-0-150-0-225-crop.jpg',
    releaseDate: '1936-02-05',
    rating: 3,
    length: 87,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Babylon A.D',
    director: 'Mathieu Kassovitz',
    actors: [{ name: 'Vin Diesel' }],
    coverUrl:
      '/movies_pictures/3YXtGZ0jKHhh2bhqr0lu8qefKLr-0-1000-0-1500-crop.jpg',
    releaseDate: '2008-02-05',
    rating: 3.25,
    length: 101,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: "Maman je m'occupe des méchants",
    director: 'Raja Gosnell',
    actors: [{ name: '' }],
    coverUrl: '/movies_pictures/46891-home-alone-3-0-1000-0-1500-crop.jpg',
    releaseDate: '1997-02-05',
    rating: 4,
    length: 102,
    genre: 'Comedy',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Yamakasi',
    director: 'Julien Seri',
    actors: [{ name: '' }],
    coverUrl: '/movies_pictures/48171-yamakasi-0-1000-0-1500-crop.jpg',
    releaseDate: '2001-02-05',
    rating: 4.75,
    length: 90,
    genre: 'Comedy',
    timesWatched: 40,
    lastViewedDate: '2025-02-05',
  },
  {
    title: 'Jackie chan dans le bronx',
    director: 'Stanley Tong Gwai-Lai',
    actors: [{ name: 'Jackie Chan' }],
    coverUrl:
      '/movies_pictures/y7AxKPPCtZyrGQKvxzn5zTQ8wFm-0-1000-0-1500-crop.jpg',
    releaseDate: '1995-02-05',
    rating: 3.25,
    length: 106,
    genre: 'Comedy',
    timesWatched: 30,
    lastViewedDate: '',
  },
];
