import { Movie } from '../../../models/movie-model';

export const moviesSagaPage2: Movie[] = [
  {
    title: 'Dune',
    director: 'Denis Villeneuve',
    actors: [
      {
        name: 'Timothée Chalamet',
      },
    ],
    coverUrl: '/movies_pictures/617443-dune-part-two-0-150-0-225-crop.jpg',
    releaseDate: '2021-10-22',
    rating: 3,
    length: 155,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Dune : Partie 2',
    director: 'Denis Villeneuve',
    actors: [
      {
        name: 'Timothée Chalamet',
      },
    ],
    coverUrl: '/movies_pictures/617443-dune-part-two-0-150-0-225-crop.jpg',
    releaseDate: '2024-03-01',
    rating: 3.75,
    length: 166,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '2024-03-01',
  },
  {
    title: 'Murder Mystery',
    director: 'Kyle Newacheck',
    actors: [
      {
        name: 'Adam Sandler',
      },
      {
        name: 'Jennifer Aniston',
      },
    ],
    coverUrl: '/movies_pictures/444598-murder-mystery-0-150-0-225-crop.jpg',
    releaseDate: '2019-06-14',
    rating: 3,
    length: 97,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Murder Mystery 2',
    director: 'Jeremy Garelick',
    actors: [
      {
        name: 'Adam Sandler',
      },
      {
        name: 'Jennifer Aniston',
      },
    ],
    coverUrl: '/movies_pictures/564996-murder-mystery-2-0-150-0-225-crop.jpg',
    releaseDate: '2023-03-31',
    rating: 3,
    length: 89,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'John Wick',
    director: 'Chad Stahelski',
    actors: [{ name: 'Keanu Reeves' }],
    coverUrl: '/movies_pictures/172076-john-wick-0-150-0-225-crop.jpg',
    releaseDate: '2014-10-24',
    rating: 4,
    length: 101,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'John Wick : Chapitre 2',
    director: 'Chad Stahelski',
    actors: [{ name: 'Keanu Reeves' }],
    coverUrl: '/movies_pictures/jonh_wick.jpg',
    releaseDate: '2017-02-10',
    rating: 3.25,
    length: 122,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'John Wick: Chapter 3 - Parabellum',
    director: 'Chad Stahelski',
    actors: [
      {
        name: 'Keanu Reeves',
      },
    ],
    coverUrl:
      '/movies_pictures/390039-john-wick-chapter-3-parabellum-0-150-0-225-crop.jpg',
    releaseDate: '2019-05-17',
    rating: 3.25,
    length: 131,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'John Wick : Chapitre 4',
    director: 'Chad Stahelski',
    actors: [
      {
        name: 'Keanu Reeves',
      },
    ],
    coverUrl:
      '/movies_pictures/530882-john-wick-chapter-4-0-150-0-225-crop.jpg',
    releaseDate: '2023-03-24',
    rating: 2.75,
    length: 169,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Les Animaux Fantastiques',
    director: 'David Yates',
    actors: [{ name: 'Eddie Redmayne' }],
    coverUrl:
      '/movies_pictures/182910-fantastic-beasts-and-where-to-find-them-0-150-0-225-crop.jpg',
    releaseDate: '2016-11-18',
    rating: 3.75,
    length: 133,
    genre: 'Fantasy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Les Animaux Fantastiques 2 : Les crimes de Grindelwald',
    director: 'David Yates',
    actors: [
      {
        name: 'Eddie Redmayne',
      },
    ],
    coverUrl:
      '/movies_pictures/268365-fantastic-beasts-the-crimes-of-grindelwald-0-150-0-225-crop.jpg',
    releaseDate: '2018-11-16',
    rating: 3.25,
    length: 134,
    genre: 'Fantasy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Les Animaux Fantastiques 3 : Les Secrets de Dumbledore',
    director: 'David Yates',
    actors: [
      {
        name: 'Eddie Redmayne',
      },
    ],
    coverUrl:
      '/movies_pictures/268366-fantastic-beasts-the-secrets-of-dumbledore-0-150-0-225-crop.jpg',
    releaseDate: '2022-04-15',
    rating: 3.25,
    length: 142,
    genre: 'Fantasy',
    timesWatched: 1,
    lastViewedDate: '2025-04-15',
  },
  {
    title: 'Jack Reacher',
    director: 'Christopher McQuarrie',
    actors: [{ name: 'Tom Cruise' }],
    coverUrl: '/movies_pictures/jack_reacher.jpg',
    releaseDate: '2012-12-21',
    rating: 4,
    length: 130,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Jack Reacher : Never Go Back',
    director: 'Edward Zwick',
    actors: [{ name: 'Tom Cruise' }],
    coverUrl: '/movies_pictures/jack_reacher_never_go_back.jpg',
    releaseDate: '2016-10-21',
    rating: 3.5,
    length: 118,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Enola Holmes',
    director: 'Harry Bradbeer',
    actors: [
      {
        name: 'Millie Bobby Brown',
      },
    ],
    coverUrl: '/movies_pictures/427852-enola-holmes-0-150-0-225-crop.jpg',
    releaseDate: '2020-09-23',
    rating: 4,
    length: 123,
    genre: 'Enquête',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Enola Holmes 2',
    director: 'Harry Bradbeer',
    actors: [
      {
        name: 'Millie Bobby Brown',
      },
    ],
    coverUrl: '/movies_pictures/744826-enola-holmes-2-0-150-0-225-crop.jpg',
    releaseDate: '2022-11-04',
    rating: 3.25,
    length: 129,
    genre: 'Enquête',
    timesWatched: 2,
    lastViewedDate: '2022-11-04',
  },
  {
    title: 'A couteaux tirés',
    director: 'Rian Johnson',
    actors: [
      {
        name: 'Daniel Craig',
      },
    ],
    coverUrl: '/movies_pictures/475370-knives-out-0-150-0-225-crop.jpg',
    releaseDate: '2019-11-27',
    rating: 4.25,
    length: 130,
    genre: 'Enquête',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'A couteaux tirés 2 : Glass Onion',
    director: 'Rian Johnson',
    actors: [
      {
        name: 'Daniel Craig',
      },
    ],
    coverUrl:
      '/movies_pictures/586723-glass-onion-a-knives-out-mystery-0-150-0-225-crop.jpg',
    releaseDate: '2022-12-23',
    rating: 3.25,
    length: 139,
    genre: 'Enquête',
    timesWatched: 1,
    lastViewedDate: '2022-12-23',
  },
  {
    title: 'James Bond: Meurs un autre jour',
    director: 'Lee Tamahori',
    actors: [{ name: 'Pierce Brosnan' }],
    coverUrl: '/movies_pictures/james_bond_demain_ne_meurs_jamaiis.jpg',
    releaseDate: '2002-11-22',
    rating: 3,
    length: 133,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'James Bond : Casino Royale',
    director: 'Martin Campbell',
    actors: [{ name: 'Daniel Craig' }],
    coverUrl: '/movies_pictures/casino_royal.jpg',
    releaseDate: '2006-11-17',
    rating: 5,
    length: 144,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'James Bond : Quantum of Solace',
    director: 'Marc Forster',
    actors: [{ name: 'Daniel Craig' }],
    coverUrl: '/movies_pictures/45918-quantum-of-solace-0-150-0-225-crop.jpg',
    releaseDate: '2008-11-14',
    rating: 3.25,
    length: 106,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'James Bond : Skyfall',
    director: 'Sam Mendes',
    actors: [{ name: 'Daniel Craig' }],
    coverUrl: '/movies_pictures/dune_1.jpg',
    releaseDate: '2012-11-09',
    rating: 4,
    length: 143,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'James Bond : Spectre',
    director: 'Sam Mendes',
    actors: [{ name: 'Daniel Craig' }],
    coverUrl: '/movies_pictures/spectre.jpg',
    releaseDate: '2015-11-06',
    rating: 4,
    length: 148,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'James Bond : Mourir Peut Attendre',
    director: 'Cary Joji Fukunaga',
    actors: [
      {
        name: 'Daniel Craig',
      },
    ],
    coverUrl: '/movies_pictures/305964-no-time-to-die-0-150-0-225-crop.jpg',
    releaseDate: '2021-10-08',
    rating: 4.25,
    length: 163,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: "OSS 117 : Le Caire, Nid d'Espions",
    director: 'Michel Hazanavicius',
    actors: [{ name: 'Jean Dujardin' }],
    coverUrl:
      '/movies_pictures/42559-oss-117-cairo-nest-of-spies-0-150-0-225-crop.jpg',
    releaseDate: '2006-04-19',
    rating: 4.5,
    length: 99,
    genre: 'Comedy',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'OSS 117 : Rio ne Répond Plus',
    director: 'Michel Hazanavicius',
    actors: [{ name: 'Jean Dujardin' }],
    coverUrl: '/movies_pictures/42256-oss-117-lost-in-rio-0-150-0-225-crop.jpg',
    releaseDate: '2009-04-15',
    rating: 3,
    length: 101,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'OSS 117 : Alerte Rouge en Afrique Noire',
    director: 'Nicolas Bedos',
    actors: [
      {
        name: 'Jean Dujardin',
      },
    ],
    coverUrl:
      '/movies_pictures/531701-oss-117-red-alert-in-black-africa-0-150-0-225-crop.jpg',
    releaseDate: '2021-07-14',
    rating: 2.75,
    length: 116,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Incassable',
    director: 'M. Night Shyamalan',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/46866-unbreakable-0-150-0-225-crop.jpg',
    releaseDate: '2000-11-22',
    rating: 4.75,
    length: 106,
    genre: 'Thriller',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Split',
    director: 'M. Night Shyamalan',
    actors: [{ name: 'James McAvoy' }],
    coverUrl: '/movies_pictures/split.jpg',
    releaseDate: '2017-01-20',
    rating: 4.5,
    length: 117,
    genre: 'Thriller',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Glass',
    director: 'M. Night Shyamalan',
    actors: [
      {
        name: 'James McAvoy',
      },
    ],
    coverUrl: '/movies_pictures/382669-glass-0-150-0-225-crop.jpg',
    releaseDate: '2019-01-18',
    rating: 4.25,
    length: 129,
    genre: 'Thriller',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Creed II',
    director: 'Steven Caple Jr.',
    actors: [
      {
        name: 'Michael B. Jordan',
      },
    ],
    coverUrl: '/movies_pictures/411439-creed-ii-0-150-0-225-crop.jpg',
    releaseDate: '2018-11-21',
    rating: 3.75,
    length: 130,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'La mémoire dans la peau',
    director: 'Doug Liman',
    actors: [{ name: 'Matt Damon' }],
    coverUrl: '/movies_pictures/50225-the-bourne-identity-0-150-0-225-crop.jpg',
    releaseDate: '2002-06-14',
    rating: 4,
    length: 119,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'La Mort dans la Peau',
    director: 'Paul Greengrass',
    actors: [{ name: 'Matt Damon' }],
    coverUrl:
      '/movies_pictures/50224-the-bourne-supremacy-0-150-0-225-crop.jpg',
    releaseDate: '2004-07-23',
    rating: 4,
    length: 108,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'La Vengeance dans la Peau',
    director: 'Paul Greengrass',
    actors: [{ name: 'Matt Damon' }],
    coverUrl:
      '/movies_pictures/50223-the-bourne-ultimatum-0-150-0-225-crop.jpg',
    releaseDate: '2007-08-03',
    rating: 4,
    length: 115,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Jason Bourne',
    director: 'Paul Greengrass',
    actors: [{ name: 'Matt Damon' }],
    coverUrl: '/movies_pictures/251773-jason-bourne-0-150-0-225-crop.jpg',
    releaseDate: '2016-07-29',
    rating: 3.75,
    length: 123,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Inssaisissables',
    director: 'Louis Leterrier',
    actors: [{ name: 'Jesse Eisenberg' }],
    coverUrl: '/movies_pictures/insaisissables.jpg',
    releaseDate: '2013-05-31',
    rating: 4.5,
    length: 115,
    genre: 'Thriller',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Inssaisissables 2',
    director: 'Jon M. Chu',
    actors: [{ name: 'Jesse Eisenberg' }],
    coverUrl: '/movies_pictures/218051-now-you-see-me-2-0-150-0-225-crop.jpg',
    releaseDate: '2016-06-10',
    rating: 3.25,
    length: 129,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Divergente',
    director: 'Neil Burger',
    actors: [{ name: 'Shailene Woodley' }],
    coverUrl: '/movies_pictures/117583-divergent-0-150-0-225-crop.jpg',
    releaseDate: '2014-03-21',
    rating: 3.75,
    length: 139,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: "Divergente 2 : L'Insurrection",
    director: 'Robert Schwentke',
    actors: [{ name: 'Shailene Woodley' }],
    coverUrl: '/movies_pictures/185970-insurgent-0-150-0-225-crop.jpg',
    releaseDate: '2015-03-20',
    rating: 3.25,
    length: 119,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Divergente 3 : Au-delà du Mur',
    director: 'Robert Schwentke',
    actors: [{ name: 'Shailene Woodley' }],
    coverUrl: '/movies_pictures/divergente.jpg',
    releaseDate: '2016-03-18',
    rating: 3,
    length: 121,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Taken',
    director: 'Pierre Morel',
    actors: [{ name: 'Liam Neeson' }],
    coverUrl: '/movies_pictures/47648-taken-0-230-0-345-crop.jpg',
    releaseDate: '2008-02-27',
    rating: 4.5,
    length: 93,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Taken 2',
    director: 'Olivier Megaton',
    actors: [{ name: 'Liam Neeson' }],
    coverUrl: '/movies_pictures/69169-taken-2-0-150-0-225-crop.jpg',
    releaseDate: '2012-10-05',
    rating: 3,
    length: 92,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Taken 3',
    director: 'Olivier Megaton',
    actors: [{ name: 'Liam Neeson' }],
    coverUrl: '/movies_pictures/183907-taken-3-0-150-0-225-crop.jpg',
    releaseDate: '2015-01-09',
    rating: 2.5,
    length: 109,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
