import { Movie } from '../../../models/movie-model';

export const moviesDc: Movie[] = [
  {
    title: 'Green Lantern',
    director: 'Martin Campbell',
    actors: [{ name: 'Ryan Reynolds' }],
    coverUrl: '/movies_pictures/20293-green-lantern-0-150-0-225-crop.jpg',
    releaseDate: '2011-06-17',
    rating: 3.25,
    length: 114,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Batman',
    director: 'Tim Burton',
    actors: [{ name: 'Michael Keaton' }],
    coverUrl: '/movies_pictures/51788-batman-0-150-0-225-crop.jpg',
    releaseDate: '1989-06-23',
    rating: 3.5,
    length: 126,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Batman Returns',
    director: 'Tim Burton',
    actors: [{ name: 'Michael Keaton' }],
    coverUrl: '/movies_pictures/51709-batman-returns-0-150-0-225-crop.jpg',
    releaseDate: '1992-06-19',
    rating: 3.5,
    length: 126,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Batman Forever',
    director: 'Joel Schumacher',
    actors: [{ name: 'Val Kilmer' }],
    coverUrl: '/movies_pictures/51678-batman-forever-0-150-0-225-crop.jpg',
    releaseDate: '1995-06-16',
    rating: 3.75,
    length: 121,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Batman & Robin',
    director: 'Joel Schumacher',
    actors: [{ name: 'George Clooney' }],
    coverUrl: '/movies_pictures/batman_and_robin.jpg',
    releaseDate: '1997-06-20',
    rating: 3.25,
    length: 125,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Batman Begins',
    director: 'Christopher Nolan',
    actors: [{ name: 'Christian Bale' }],
    coverUrl: '/movies_pictures/51784-batman-begins-0-150-0-225-crop.jpg',
    releaseDate: '2005-06-15',
    rating: 4.25,
    length: 140,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'The Dark Knight : Le Chevalier Noir',
    director: 'Christopher Nolan',
    actors: [{ name: 'Christian Bale' }],
    coverUrl: '/movies_pictures/the_dark_knight.jpg',
    releaseDate: '2008-07-18',
    rating: 5,
    length: 152,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'The Dark Knight Rises',
    director: 'Christopher Nolan',
    actors: [{ name: 'Christian Bale' }],
    coverUrl:
      '/movies_pictures/16550-the-dark-knight-rises-0-150-0-225-crop.jpg',
    releaseDate: '2012-07-20',
    rating: 4.5,
    length: 164,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'The Batman',
    director: 'Matt Reeves',
    actors: [
      {
        name: 'Robert Pattinson',
      },
    ],
    coverUrl: '/movies_pictures/348914-the-batman-0-150-0-225-crop.jpg',
    releaseDate: '2022-03-04',
    rating: 4,
    length: 176,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '2025-05-04',
  },
  {
    title: "Batman v Superman : L'Aube de la Justice",
    director: 'Zack Snyder',
    actors: [{ name: 'Ben Affleck' }],
    coverUrl: '/movies_pictures/batman_v_superman.jpg',
    releaseDate: '2016-03-25',
    rating: 3.75,
    length: 151,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Shazam!',
    director: 'David F. Sandberg',
    actors: [
      {
        name: 'Zachary Levi',
      },
    ],
    coverUrl: '/movies_pictures/213190-shazam--0-150-0-225-crop.jpg',
    releaseDate: '2019-04-05',
    rating: 3,
    length: 132,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Aquaman',
    director: 'James Wan',
    actors: [
      {
        name: 'Jason Momoa',
      },
    ],
    coverUrl: '/movies_pictures/225060-aquaman-0-150-0-225-crop.jpg',
    releaseDate: '2018-12-21',
    rating: 3.75,
    length: 143,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Black Adam',
    director: 'Jaume Collet-Serra',
    actors: [
      {
        name: 'Dwayne Johnson',
      },
    ],
    coverUrl: '/movies_pictures/369179-black-adam-0-150-0-225-crop.jpg',
    releaseDate: '2022-10-21',
    rating: 3.75,
    length: 125,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "Zack Snyder's Justice League",
    director: 'Zack Snyder',
    actors: [
      {
        name: 'Ben Affleck',
      },
    ],
    coverUrl:
      '/movies_pictures/709530-zack-snyder-s-justice-league-0-150-0-225-crop.jpg',
    releaseDate: '2021-03-18',
    rating: 3.75,
    length: 242,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2021-03-18',
  },
  {
    title: 'Suicide Squad',
    director: 'David Ayer',
    actors: [{ name: 'Will Smith' }],
    coverUrl: '/movies_pictures/suicide_squad.jpg',
    releaseDate: '2016-08-05',
    rating: 3.25,
    length: 123,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Man of Steel',
    director: 'Zack Snyder',
    actors: [{ name: 'Henry Cavill' }],
    coverUrl: '/movies_pictures/man_of_steel.jpg',
    releaseDate: '2013-06-14',
    rating: 4.5,
    length: 143,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Superman',
    director: 'James Gunn',
    actors: [{ name: 'David Corenswet' }],
    coverUrl: '/movies_pictures/superman_2025.jpg',
    releaseDate: '2025-07-11',
    rating: 3.75,
    length: 150,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2025-07-13',
  },
  {
    title: 'Watchmen : Les Gardiens',
    director: 'Zack Snyder',
    actors: [{ name: 'Jackie Earle Haley' }],
    coverUrl: '/movies_pictures/44070-watchmen-0-150-0-225-crop.jpg',
    releaseDate: '2009-03-06',
    rating: 3.75,
    length: 162,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Catwoman',
    director: 'Pitof',
    actors: [{ name: 'Halle Berry' }],
    coverUrl: '/movies_pictures/51745-catwoman-0-150-0-225-crop.jpg',
    releaseDate: '2004-07-23',
    rating: 3.5,
    length: 104,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Wonder Woman',
    director: 'Patty Jenkins',
    actors: [{ name: 'Gal Gadot' }],
    coverUrl: '/movies_pictures/225027-wonder-woman-0-150-0-225-crop.jpg',
    releaseDate: '2017-06-02',
    rating: 3.75,
    length: 141,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Wonder Woman 1984',
    director: 'Patty Jenkins',
    actors: [
      {
        name: 'Gal Gadot',
      },
    ],
    coverUrl: '/movies_pictures/395731-wonder-woman-1984-0-150-0-225-crop.jpg',
    releaseDate: '2020-12-25',
    rating: 2.75,
    length: 151,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'The Flash',
    director: 'Andy Muschietti',
    actors: [
      {
        name: 'Ezra Miller',
      },
    ],
    coverUrl: '/movies_pictures/225845-the-flash-0-150-0-225-crop.jpg',
    releaseDate: '2023-06-16',
    rating: 3,
    length: 144,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Birds of Prey',
    director: 'Cathy Yan',
    actors: [
      {
        name: 'Margot Robbie',
      },
    ],
    coverUrl:
      '/movies_pictures/426131-birds-of-prey-and-the-fantabulous-emancipation-of-one-har-0-150-0-225-crop.jpg',
    releaseDate: '2020-02-07',
    rating: 3.75,
    length: 109,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
