import { Movie } from '../../../models/movie-model';

export const moviesSagaPage3: Movie[] = [
  {
    title: 'Le Labyrinthe',
    director: 'Wes Ball',
    actors: [{ name: "Dylan O'Brien" }],
    coverUrl: '/movies_pictures/142549-the-maze-runner-0-150-0-225-crop.jpg',
    releaseDate: '2014-09-19',
    rating: 4,
    length: 113,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Le Labyrinthe 2 : Le remède mortel',
    director: 'Wes Ball',
    actors: [
      {
        name: "Dylan O'Brien",
      },
    ],
    coverUrl:
      '/movies_pictures/266132-maze-runner-the-death-cure-0-150-0-225-crop.jpg',
    releaseDate: '2018-01-26',
    rating: 2.75,
    length: 143,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Hunger Games',
    director: 'Gary Ross',
    actors: [{ name: 'Jennifer Lawrence' }],
    coverUrl: '/movies_pictures/hunger_games_1.jpg',
    releaseDate: '2012-03-23',
    rating: 3.25,
    length: 142,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '2025-03-23',
  },
  {
    title: 'Hunger Games : La Révolte - Partie 1',
    director: 'Francis Lawrence',
    actors: [{ name: 'Jennifer Lawrence' }],
    coverUrl:
      '/movies_pictures/101991-the-hunger-games-mockingjay-part-1-0-150-0-225-crop.jpg',
    releaseDate: '2014-11-21',
    rating: 3,
    length: 123,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Transformers',
    director: 'Michael Bay',
    actors: [{ name: 'Shia LaBeouf' }],
    coverUrl: '/movies_pictures/transformers-0-150-0-225-crop.jpg',
    releaseDate: '2007-07-03',
    rating: 4.25,
    length: 144,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Transformers 2 : La Revanche',
    director: 'Michael Bay',
    actors: [{ name: 'Shia LaBeouf' }],
    coverUrl:
      '/movies_pictures/47769-transformers-revenge-of-the-fallen-0-150-0-225-crop.jpg',
    releaseDate: '2009-06-24',
    rating: 3.5,
    length: 150,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Transformers 3 : La Face Cachée de la Lune',
    director: 'Michael Bay',
    actors: [{ name: 'Shia LaBeouf' }],
    coverUrl: '/movies_pictures/transforms_face_cachee_de_la_lune.jpg',
    releaseDate: '2011-06-29',
    rating: 2.75,
    length: 154,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "Transformers 4 : L'Âge de l'Extinction",
    director: 'Michael Bay',
    actors: [{ name: 'Mark Wahlberg' }],
    coverUrl:
      '/movies_pictures/76504-transformers-age-of-extinction-0-150-0-225-crop.jpg',
    releaseDate: '2014-06-27',
    rating: 3,
    length: 165,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'RED',
    director: 'Robert Schwentke',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/25175-red-0-150-0-225-crop.jpg',
    releaseDate: '2010-10-15',
    rating: 3.75,
    length: 111,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'RED 2',
    director: 'Dean Parisot',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/110736-red-2-0-150-0-225-crop.jpg',
    releaseDate: '2013-07-19',
    rating: 3,
    length: 116,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Very Bad Trip',
    director: 'Todd Phillips',
    actors: [{ name: 'Bradley Cooper' }],
    coverUrl: '/movies_pictures/40100-the-hangover-0-150-0-225-crop.jpg',
    releaseDate: '2009-06-05',
    rating: 4,
    length: 100,
    genre: 'Comedy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Very Bad Trip 2',
    director: 'Todd Phillips',
    actors: [{ name: 'Bradley Cooper' }],
    coverUrl: '/movies_pictures/very_bad_trip_2.jpg',
    releaseDate: '2011-05-26',
    rating: 3.25,
    length: 102,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Very Bad Trip 3',
    director: 'Todd Phillips',
    actors: [{ name: 'Bradley Cooper' }],
    coverUrl:
      '/movies_pictures/87953-the-hangover-part-iii-0-150-0-225-crop.jpg',
    releaseDate: '2013-05-23',
    rating: 3.5,
    length: 100,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '2013-05-23',
  },
  {
    title: 'Die Hard : Piège de cristal',
    director: 'John McTiernan',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/51556-die-hard-0-150-0-225-crop.jpg',
    releaseDate: '1988-07-15',
    rating: 4.5,
    length: 132,
    genre: 'Action',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'Die Hard 2 : 58 minutes pour vivre',
    director: 'Renny Harlin',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/die_hard_2.jpg',
    releaseDate: '1990-07-04',
    rating: 4,
    length: 124,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Die Hard 3 : une journée en enfer',
    director: 'John McTiernan',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl:
      '/movies_pictures/50962-die-hard-with-a-vengeance-0-150-0-225-crop.jpg',
    releaseDate: '1995-05-19',
    rating: 5,
    length: 128,
    genre: 'Action',
    timesWatched: 30,
    lastViewedDate: '',
  },
  {
    title: 'Die Hard 4 : Retour en Enfer',
    director: 'Len Wiseman',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl:
      '/movies_pictures/50963-live-free-or-die-hard-0-150-0-225-crop.jpg',
    releaseDate: '2007-06-27',
    rating: 4.5,
    length: 128,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Die Hard : Belle Journée pour Mourir',
    director: 'John Moore',
    actors: [{ name: 'Bruce Willis' }],
    coverUrl: '/movies_pictures/die_hard_5.jpg',
    releaseDate: '2013-02-14',
    rating: 2.75,
    length: 98,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2013-02-14',
  },
  {
    title: 'Twilight : Chapitre 1 - Fascination',
    director: 'Catherine Hardwicke',
    actors: [{ name: 'Kristen Stewart' }],
    coverUrl: '/movies_pictures/47469-twilight-0-150-0-225-crop.jpg',
    releaseDate: '2008-11-21',
    rating: 3.25,
    length: 122,
    genre: 'Fantasy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Twilight : Chapitre 2 - Tentation',
    director: 'Chris Weitz',
    actors: [{ name: 'Kristen Stewart' }],
    coverUrl:
      '/movies_pictures/40480-the-twilight-saga-new-moon-0-150-0-225-crop.jpg',
    releaseDate: '2009-11-20',
    rating: 2.75,
    length: 130,
    genre: 'Fantasy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Twilight : Chapitre 3 - Hésitation',
    director: 'David Slade',
    actors: [{ name: 'Kristen Stewart' }],
    coverUrl: '/movies_pictures/hesitation.jpg',
    releaseDate: '2010-06-30',
    rating: 2.5,
    length: 124,
    genre: 'Fantasy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Twilight : Chapitre 4 - Révélation - Partie 1',
    director: 'Bill Condon',
    actors: [{ name: 'Kristen Stewart' }],
    coverUrl:
      '/movies_pictures/15077-the-twilight-saga-breaking-dawn-part-1-0-1000-0-1500-crop.jpg',
    releaseDate: '2011-11-18',
    rating: 3.25,
    length: 117,
    genre: 'Fantasy',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Twilight : Chapitre 4 - Révélation - Partie 2',
    director: 'Bill Condon',
    actors: [{ name: 'Kristen Stewart' }],
    coverUrl:
      '/movies_pictures/15076-the-twilight-saga-breaking-dawn-part-2-0-150-0-225-crop.jpg',
    releaseDate: '2012-11-16',
    rating: 3.5,
    length: 115,
    genre: 'Fantasy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Underworld',
    director: 'Len Wiseman',
    actors: [{ name: 'Kate Beckinsale' }],
    coverUrl: '/movies_pictures/underworld_1.jpg',
    releaseDate: '2003-09-19',
    rating: 4.25,
    length: 121,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Underworld : Évolution',
    director: 'Len Wiseman',
    actors: [{ name: 'Kate Beckinsale' }],
    coverUrl:
      '/movies_pictures/51318-underworld-evolution-0-150-0-225-crop.jpg',
    releaseDate: '2006-01-20',
    rating: 3.75,
    length: 106,
    genre: 'Action',
    timesWatched: 15,
    lastViewedDate: '',
  },
  {
    title: 'Underworld : Rise of the Lycans',
    director: 'Patrick Tatopoulos',
    actors: [{ name: 'Michael Sheen' }],
    coverUrl:
      '/movies_pictures/44587-underworld-rise-of-the-lycans-0-150-0-225-crop.jpg',
    releaseDate: '2009-01-23',
    rating: 3.25,
    length: 92,
    genre: 'Action',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Underworld : Éveil',
    director: 'Måns Mårlind, Björn Stein',
    actors: [{ name: 'Kate Beckinsale' }],
    coverUrl:
      '/movies_pictures/13370-underworld-awakening-0-150-0-225-crop.jpg',
    releaseDate: '2012-01-20',
    rating: 3.5,
    length: 88,
    genre: 'Action',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Destination Finale',
    director: 'James Wong',
    actors: [{ name: 'Devon Sawa' }],
    coverUrl: '/movies_pictures/47068-final-destination-0-150-0-225-crop.jpg',
    releaseDate: '2000-03-17',
    rating: 3.5,
    length: 98,
    genre: 'Horror',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Destination Finale 2',
    director: 'David R. Ellis',
    actors: [{ name: 'A.J. Cook' }],
    coverUrl: '/movies_pictures/destination_finale_2.jpg',
    releaseDate: '2003-01-31',
    rating: 3,
    length: 90,
    genre: 'Horror',
    timesWatched: 3,
    lastViewedDate: '',
  },
  {
    title: 'Destination Finale 3',
    director: 'James Wong',
    actors: [{ name: 'Mary Elizabeth Winstead' }],
    coverUrl: '/movies_pictures/47306-final-destination-3-0-150-0-225-crop.jpg',
    releaseDate: '2006-02-10',
    rating: 3.75,
    length: 93,
    genre: 'Horror',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Destination Finale 4',
    director: 'David R. Ellis',
    actors: [{ name: 'Bobby Campo' }],
    coverUrl: '/movies_pictures/destination_finale_4.jpg',
    releaseDate: '2009-08-28',
    rating: 3.5,
    length: 82,
    genre: 'Horror',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Destination Finale 5',
    director: 'Steven Quale',
    actors: [{ name: "Nicholas D'Agosto" }],
    coverUrl: '/movies_pictures/destination_finale_5.jpg',
    releaseDate: '2011-08-12',
    rating: 2.75,
    length: 92,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Scream',
    director: 'Wes Craven',
    actors: [{ name: 'Neve Campbell' }],
    coverUrl: '/movies_pictures/49455-scream-0-150-0-225-crop.jpg',
    releaseDate: '1996-12-20',
    rating: 3.5,
    length: 111,
    genre: 'Horror',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Scream 2',
    director: 'Wes Craven',
    actors: [{ name: 'Neve Campbell' }],
    coverUrl: '/movies_pictures/scream_2.jpg',
    releaseDate: '1997-12-12',
    rating: 3,
    length: 120,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Scream 3',
    director: 'Wes Craven',
    actors: [{ name: 'Neve Campbell' }],
    coverUrl: '/movies_pictures/49453-scream-3-0-150-0-225-crop.jpg',
    releaseDate: '2000-02-04',
    rating: 3,
    length: 116,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Scream 4',
    director: 'Wes Craven',
    actors: [{ name: 'Neve Campbell' }],
    coverUrl: '/movies_pictures/scream_4.jpg',
    releaseDate: '2011-04-15',
    rating: 3,
    length: 111,
    genre: 'Horror',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Avatar',
    director: 'James Cameron',
    actors: [{ name: 'Sam Worthington' }],
    coverUrl: '/movies_pictures/avatar.jpg',
    releaseDate: '2009-12-18',
    rating: 5,
    length: 162,
    genre: 'Science Fiction',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: "Avatar 2 : La Voie de l'Eau",
    director: 'James Cameron',
    actors: [
      {
        name: 'Sam Worthington',
      },
    ],
    coverUrl:
      '/movies_pictures/63058-avatar-the-way-of-water-0-150-0-225-crop.jpg',
    releaseDate: '2022-12-16',
    rating: 3.5,
    length: 192,
    genre: 'Science Fiction',
    timesWatched: 1,
    lastViewedDate: '2022-12-16',
  },
  {
    title: 'American Pie',
    director: 'Paul Weitz, Chris Weitz',
    actors: [{ name: 'Jason Biggs' }],
    coverUrl: '/movies_pictures/50521-american-pie-0-150-0-225-crop.jpg',
    releaseDate: '1999-07-09',
    rating: 3.75,
    length: 95,
    genre: 'Comedy',
    timesWatched: 20,
    lastViewedDate: '',
  },
  {
    title: 'American Pie 2',
    director: 'J.B. Rogers',
    actors: [{ name: 'Jason Biggs' }],
    coverUrl: '/movies_pictures/50101-american-pie-2-0-150-0-225-crop.jpg',
    releaseDate: '2001-08-10',
    rating: 3.25,
    length: 108,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'American Pie 3 : Marions-les',
    director: 'Jesse Dylan',
    actors: [{ name: 'Jason Biggs' }],
    coverUrl: '/movies_pictures/47833-american-wedding-0-150-0-225-crop.jpg',
    releaseDate: '2003-08-01',
    rating: 3,
    length: 96,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'American Pie Presents: Beta House',
    director: 'Andrew Waller',
    actors: [{ name: 'John White' }],
    coverUrl: '/movies_pictures/american_pie_beta_house.jpg',
    releaseDate: '2007-12-26',
    rating: 3.25,
    length: 88,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'American Pie Presents: The Naked Mile',
    director: 'Joe Nussbaum',
    actors: [{ name: 'John White' }],
    coverUrl:
      '/movies_pictures/47831-american-pie-presents-the-naked-mile-0-150-0-225-crop.jpg',
    releaseDate: '2006-12-19',
    rating: 3,
    length: 97,
    genre: 'Comedy',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'American Pie Presents: Band Camp',
    director: 'Steve Rash',
    actors: [{ name: 'Tad Hilgenbrink' }],
    coverUrl: '/movies_pictures/american_pie_band_camp.jpg',
    releaseDate: '2005-12-26',
    rating: 3,
    length: 97,
    genre: 'Comedy',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'American Pie Presents: The Book of Love',
    director: 'John Putch',
    actors: [{ name: 'Bug Hall' }],
    coverUrl:
      '/movies_pictures/35567-american-pie-presents-the-book-of-love-0-150-0-225-crop.jpg',
    releaseDate: '2009-12-22',
    rating: 2.5,
    length: 93,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'American Pie 4',
    director: 'Jon Hurwitz, Hayden Schlossberg',
    actors: [{ name: 'Jason Biggs' }],
    coverUrl: '/movies_pictures/57927-american-reunion-0-150-0-225-crop.jpg',
    releaseDate: '2012-04-06',
    rating: 2.5,
    length: 113,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
