import { Movie } from '../../../models/movie-model';

export const moviesPage9: Movie[] = [
  {
    title: 'Tanguy',
    director: 'Étienne Chatiliez',
    actors: [{ name: 'Éric Berger' }],
    coverUrl: '/movies_pictures/50585-tanguy-0-150-0-225-crop.jpg',
    releaseDate: '2001-12-19',
    rating: 3.25,
    length: 95,
    genre: 'Comedy',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'The One',
    director: 'James Wong',
    actors: [{ name: 'Jet Li' }],
    coverUrl: '/movies_pictures/45888-the-one-0-150-0-225-crop.jpg',
    releaseDate: '2001-11-02',
    rating: 3.5,
    length: 87,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Wasabi',
    director: 'Gérard Krawczyk',
    actors: [{ name: 'Jean Reno' }],
    coverUrl: '/movies_pictures/50516-wasabi-0-150-0-225-crop.jpg',
    releaseDate: '2001-10-31',
    rating: 3,
    length: 94,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Training Day',
    director: 'Antoine Fuqua',
    actors: [{ name: 'Denzel Washington' }],
    coverUrl: '/movies_pictures/50580-training-day-0-150-0-225-crop.jpg',
    releaseDate: '2001-10-05',
    rating: 3.25,
    length: 122,
    genre: 'Crime',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Shaolin Soccer',
    director: 'Stephen Chow',
    actors: [{ name: 'Stephen Chow' }],
    coverUrl: '/movies_pictures/45025-shaolin-soccer-0-150-0-225-crop.jpg',
    releaseDate: '2001-07-12',
    rating: 3,
    length: 87,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Mulholland Drive',
    director: 'David Lynch',
    actors: [{ name: 'Naomi Watts' }],
    coverUrl: '/movies_pictures/mulholland_drive.jpg',
    releaseDate: '2001-10-12',
    rating: 2.5,
    length: 147,
    genre: 'Enquête',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Replicant',
    director: 'Ringo Lam',
    actors: [{ name: 'Jean-Claude Van Damme' }],
    coverUrl: '/movies_pictures/46077-replicant-0-150-0-225-crop.jpg',
    releaseDate: '2001-05-04',
    rating: 3,
    length: 100,
    genre: 'Action',
    timesWatched: 5,
    lastViewedDate: '',
  },

  {
    title: 'Battle Royale',
    director: 'Kinji Fukasaku',
    actors: [{ name: 'Tatsuya Fujiwara' }],
    coverUrl: '/movies_pictures/49810-battle-royale-0-150-0-225-crop.jpg',
    releaseDate: '2000-12-16',
    rating: 2.75,
    length: 114,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Miss Détective',
    director: 'Donald Petrie',
    actors: [{ name: 'Sandra Bullock' }],
    coverUrl: '/movies_pictures/51006-miss-congeniality-0-150-0-225-crop.jpg',
    releaseDate: '2000-12-22',
    rating: 3,
    length: 111,
    genre: 'Comedy',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: "A l'aube du 6ème jour",
    director: 'Roger Spottiswoode',
    actors: [{ name: 'Arnold Schwarzenegger' }],
    coverUrl: '/movies_pictures/a_l_aube_du_sixieme_jour.jpg',
    releaseDate: '2000-11-17',
    rating: 3.75,
    length: 123,
    genre: 'Science Fiction',
    timesWatched: 5,
    lastViewedDate: '',
  },
  {
    title: 'Memento',
    director: 'Christopher Nolan',
    actors: [{ name: 'Guy Pearce' }],
    coverUrl: '/movies_pictures/memento-0-150-0-225-crop.jpg',
    releaseDate: '2000-09-05',
    rating: 3.25,
    length: 113,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Snatch',
    director: 'Guy Ritchie',
    actors: [{ name: 'Jason Statham' }],
    coverUrl: '/movies_pictures/snatch.jpg',
    releaseDate: '2000-09-01',
    rating: 3,
    length: 104,
    genre: 'Crime',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Requiem for a Dream',
    director: 'Darren Aronofsky',
    actors: [{ name: 'Ellen Burstyn' }],
    coverUrl: '/movies_pictures/requiem_for_a_dream.jpg',
    releaseDate: '2000-10-06',
    rating: 2.5,
    length: 102,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '',
  },
  {
    title: 'Gladiator',
    director: 'Ridley Scott',
    actors: [{ name: 'Russell Crowe' }],
    coverUrl: '/movies_pictures/51952-gladiator-2000-0-150-0-225-crop.jpg',
    releaseDate: '2000-05-05',
    rating: 3.25,
    length: 155,
    genre: 'Action',
    timesWatched: 2,
    lastViewedDate: '2025-02-17',
  },
  {
    title: 'Rebel Ridge',
    director: 'Jeremy Saulnier',
    actors: [{ name: 'John Boyega' }],
    coverUrl: '/movies_pictures/rebel_ridge.jpg',
    releaseDate: '2024-05-31',
    rating: 3.25,
    length: 120,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '2025-03-23',
  },
  {
    title: '84 m²',
    director: 'Inconnu',
    actors: [{ name: 'Acteur principal' }],
    coverUrl: '/movies_pictures/b8e7d5e682836c190da279d7aa0c23b4.webp',
    releaseDate: '2024-01-01',
    rating: 2.5,
    length: 90,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-08-18',
  },
  {
    title: 'Brick',
    director: 'Philip Koch',
    actors: [{ name: 'Matthias Schweighöfer' }, { name: 'Ruby O. Fee' }],
    coverUrl: '/movies_pictures/cdfeb09ef9b1b5e1d5b35269efd5735a.webp',
    releaseDate: '2025-07-10',
    rating: 3,
    length: 105,
    genre: 'Thriller, Science Fiction',
    timesWatched: 1,
    lastViewedDate: '2025-07-15',
  },
  {
    title: 'La carte qui mène à toi',
    director: 'Inconnu',
    actors: [{ name: 'Acteur principal' }],
    coverUrl: '/movies_pictures/1254072.webp',
    releaseDate: '2024-01-01',
    rating: 3.5,
    length: 100,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '2025-07-13',
  },
  {
    title: 'Les 4 fantastiques',
    director: 'Matt Shakman',
    actors: [
      { name: 'Pedro Pascal' },
      { name: 'Vanessa Kirby' },
      { name: 'Joseph Quinn' },
      { name: 'Ebon Moss-Bachrach' },
    ],
    coverUrl:
      '/movies_pictures/les-4-fantastiques-premiers-pas-affiche-officielle-scaled.jpg',
    releaseDate: '2025-07-25',
    rating: 3.75,
    length: 130,
    genre: 'Action, Adventure',
    timesWatched: 1,
    lastViewedDate: '2025-07-27',
  },
  {
    title: 'Premier contact',
    director: 'Denis Villeneuve',
    actors: [
      { name: 'Amy Adams' },
      { name: 'Jeremy Renner' },
      { name: 'Forest Whitaker' },
    ],
    coverUrl: '/movies_pictures/109206907.webp',
    releaseDate: '2016-11-11',
    rating: 4.25,
    length: 116,
    genre: 'Science Fiction, Drama',
    timesWatched: 1,
    lastViewedDate: '2025-07-08',
  },
  {
    title: 'Sexe entre amis',
    director: 'Will Gluck',
    actors: [
      { name: 'Justin Timberlake' },
      { name: 'Mila Kunis' },
      { name: 'Patricia Clarkson' },
    ],
    coverUrl: '/movies_pictures/19757410.webp',
    releaseDate: '2011-07-22',
    rating: 3.5,
    length: 109,
    genre: 'Comedy, Romance',
    timesWatched: 1,
    lastViewedDate: '2025-07-22',
  },
  {
    title: 'Source Code',
    director: 'Duncan Jones',
    actors: [
      { name: 'Jake Gyllenhaal' },
      { name: 'Michelle Monaghan' },
      { name: 'Vera Farmiga' },
    ],
    coverUrl: '/movies_pictures/81JgsD1EoIL._UF894,1000_QL80_ .jpg',
    releaseDate: '2011-04-01',
    rating: 4.25,
    length: 93,
    genre: 'Science Fiction, Thriller',
    timesWatched: 1,
    lastViewedDate: '2025-09-01',
  },
  {
    title: 'Le témoin amoureux',
    director: 'Paul Weiland',
    actors: [
      { name: 'Patrick Dempsey' },
      { name: 'Michelle Monaghan' },
      { name: 'Kevin McKidd' },
    ],
    coverUrl: '/movies_pictures/18926251.jpg',
    releaseDate: '2008-05-02',
    rating: 2.5,
    length: 101,
    genre: 'Comedy, Romance',
    timesWatched: 1,
    lastViewedDate: '2025-07-04',
  },
  {
    title: 'Une femme en jeu',
    director: 'Inconnu',
    actors: [{ name: 'Acteur principal' }],
    coverUrl: '/movies_pictures/96870dc4da3356ac6b13fb5359f5cd56.jpg',
    releaseDate: '2024-01-01',
    rating: 3.25,
    length: 95,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-08-19',
  },
  {
    title: 'Lettres à Juliette',
    director: 'Gary Winick',
    actors: [{ name: 'Amanda Seyfried' }, { name: 'Gael García Bernal' }],
    coverUrl: '/movies_pictures/19241233.webp',
    releaseDate: '2010-05-14',
    rating: 3.25,
    length: 105,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '2025-10-30',
  },
  {
    title: 'My Oxford Year',
    director: 'Sarah Treem',
    actors: [{ name: 'Aisling Franciosi' }],
    coverUrl: '/movies_pictures/f1c06582c665ba69d863934d8b176d25.jpg',
    releaseDate: '2024-01-01',
    rating: 3.25,
    length: 100,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '2025-10-30',
  },
  {
    title: 'Ordinary Angels',
    director: 'Jon Gunn',
    actors: [{ name: 'Hilary Swank' }, { name: 'Alan Ritchson' }],
    coverUrl: '/movies_pictures/1684889.jpg',
    releaseDate: '2024-02-23',
    rating: 3.75,
    length: 118,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-10-28',
  },
  {
    title: 'French Lover',
    director: 'Inconnu',
    actors: [{ name: 'Acteur principal' }],
    coverUrl:
      '/movies_pictures/AAAABWVgN_6qNZk70MFWrIUY6kiYXI907aDytmsBt7M1eQ_o.jpg',
    releaseDate: '2024-01-01',
    rating: 3.25,
    length: 95,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '2025-10-10',
  },
  {
    title: 'Thunderbolts',
    director: 'Jake Schreier',
    actors: [
      { name: 'Florence Pugh' },
      { name: 'Sebastian Stan' },
      { name: 'David Harbour' },
    ],
    coverUrl: '/movies_pictures/72b74175dd05a704ebed57975b0f6487.jpg',
    releaseDate: '2025-05-02',
    rating: 3.25,
    length: 130,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2025-10-20',
  },
  {
    title: 'Le silence des agneaux',
    director: 'Jonathan Demme',
    actors: [{ name: 'Jodie Foster' }, { name: 'Anthony Hopkins' }],
    coverUrl: '/movies_pictures/4218638.jpg',
    releaseDate: '1991-02-14',
    rating: 3.5,
    length: 118,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '2025-10-29',
  },
  {
    title: 'Maintenance Required',
    director: 'Inconnu',
    actors: [{ name: 'Acteur principal' }],
    coverUrl:
      '/movies_pictures/MV5BNGZlN2Y5ZGEtMmU0MS00ZWI0L_FMjpg_UX1000_.jpg',
    releaseDate: '2024-01-01',
    rating: 3.75,
    length: 95,
    genre: 'Drama',
    timesWatched: 1,
    lastViewedDate: '2025-10-13',
  },
  {
    title: 'Nocturnal Animals',
    director: 'Tom Ford',
    actors: [{ name: 'Amy Adams' }, { name: 'Jake Gyllenhaal' }],
    coverUrl: '/movies_pictures/415908.webp',
    releaseDate: '2016-11-04',
    rating: 3.75,
    length: 116,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '2025-09-25',
  },
  {
    title: 'Superman',
    director: 'Richard Donner',
    actors: [{ name: 'Christopher Reeve' }, { name: 'Margot Kidder' }],
    coverUrl: '/movies_pictures/Superman_affiche_film_1.webp',
    releaseDate: '1978-12-15',
    rating: 3.25,
    length: 143,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2025-09-10',
  },
  {
    title: 'Superman II',
    director: 'Richard Lester',
    actors: [{ name: 'Christopher Reeve' }, { name: 'Margot Kidder' }],
    coverUrl: '/movies_pictures/61a2Wp8ylUL._AC_UF894,1000_QL80_.jpg',
    releaseDate: '1980-12-12',
    rating: 3,
    length: 127,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2025-09-10',
  },
  {
    title: 'Superman Returns',
    director: 'Bryan Singer',
    actors: [{ name: 'Brandon Routh' }, { name: 'Kate Bosworth' }],
    coverUrl: '/movies_pictures/18648048.jpg',
    releaseDate: '2006-06-28',
    rating: 3.75,
    length: 154,
    genre: 'Action',
    timesWatched: 1,
    lastViewedDate: '2025-09-10',
  },
  {
    title: 'Enemy',
    director: 'Denis Villeneuve',
    actors: [{ name: 'Jake Gyllenhaal' }, { name: 'Mélanie Laurent' }],
    coverUrl: '/movies_pictures/317481.webp',
    releaseDate: '2013-09-08',
    rating: 3.25,
    length: 91,
    genre: 'Thriller',
    timesWatched: 1,
    lastViewedDate: '2025-09-08',
  },
  {
    title: 'Forever My Girl',
    director: 'Bethany Ashton Wolf',
    actors: [{ name: 'Alex Roe' }, { name: 'Jessica Rothe' }],
    coverUrl: '/movies_pictures/forever_my_girl.jpg',
    releaseDate: '2018-01-19',
    rating: 3.25,
    length: 108,
    genre: 'Romance',
    timesWatched: 1,
    lastViewedDate: '2025-08-28',
  },
  {
    title: 'Dans tes rêves',
    director: 'Denis Thybaud',
    actors: [
      { name: 'Disiz' },
      { name: 'Béatrice Dalle' },
      { name: 'Vincent Elbaz' },
    ],
    coverUrl: '/movies_pictures/dans_tes_reves.jpg',
    releaseDate: '2005-10-05',
    rating: 0,
    length: 95,
    genre: 'Comedy, Drama',
    timesWatched: 0,
    lastViewedDate: '',
  },
];
