import { Music } from '../../../../models/music-model';

export const musicsRapFrVarious: Music[] = [
  {
    title: 'Elle te rend dingue - poom poom short radio edit',
    artist: 'Nuttea',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 37,
  },
  {
    title: 'Ma femme',
    artist: 'GaÃ«l Faye',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 18,
  },
  {
    title: 'La Boulette (Génération Nan Nan)',
    artist: "Diam's",
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 20,
  },
  {
    title: 'Au summum',
    artist: '113',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 16,
  },
  {
    title: 'La tribu de Dana',
    artist: 'Manau',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: 'Wati by Night',
    artist: "Sexion d'Assaut",
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 25,
  },
  {
    title: 'Le bilan',
    artist: "Nèg' Marrons",
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 17,
  },
  {
    title: 'Petit Martien',
    artist: 'La Fanfare En Pétard',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 16,
  },
  {
    title: 'Le Vice',
    artist: 'La Fanfare En Pétard',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 2,
  },
  {
    title: 'La gagne (feat. Tonton David)',
    artist: 'Intouchable',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 1,
  },
  {
    title: 'La source',
    artist: '1995',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 15,
  },
  {
    title: 'La Suite',
    artist: '1995',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 10,
  },
  {
    title: 'à chaque ligne',
    artist: '1995',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Réel',
    artist: '1995',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'On gère',
    artist: 'Deen Burbigo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: 'Surnakkurel 3',
    artist: 'Nakk Mendosa',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 16,
  },
];
