import { Music } from '../../../../models/music-model';

export const musicsCasseursFlowters: Music[] = [
  // Album : Orelsan et Gringe sont les Casseurs Flowters (2013) - Casseurs Flowters
  {
    title: '14h58 - Casseurs Flowters Opening',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 103,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: '15h02 - Regarde comme il fait beau (dehors)',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 204,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },
  {
    title: '15h45 - Stupide ! Stupide ! Stupide !',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 256,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },
  {
    title: "16h00 - Tu m'dois d'l'oseille",
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 137,
    genre: 'Rap/Hip-Hop',
    timesListened: 180,
  },
  {
    title: '16h22 - Deux connards dans un abribus',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 274,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },
  {
    title: '17h04 - Prends des pièces',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },
  {
    title: '18h30 - Bloqué',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 229,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },
  {
    title: '19h26 - La mort du disque',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 162,
    genre: 'Rap/Hip-Hop',
    timesListened: 180,
  },
  {
    title: '20h08 - Dans la place pour être',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },
  {
    title: '20h13 - La nouvelle paire',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 328,
    genre: 'Rap/Hip-Hop',
    timesListened: 180,
  },
  {
    title: '22h31 - Fais les backs',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 183,
    genre: 'Rap/Hip-Hop',
    timesListened: 180,
  },
  {
    title: '01h16 - Les putes et moi',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 379,
    genre: 'Rap/Hip-Hop',
    timesListened: 200,
  },
  {
    title: '01h25 - Johnny Galoche',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 116,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: '01h47 - Change de pote',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 190,
    genre: 'Rap/Hip-Hop',
    timesListened: 200,
  },
  {
    title: "03h53 - Manger c'est tricher",
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 264,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },
  {
    title: '04h41 - Greenje et Orselane',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 200,
  },
  {
    title: '06h16 - Des histoires à raconter',
    artist: 'Casseurs Flowters',
    album: 'Orelsan et Gringe sont les Casseurs Flowters',
    coverUrl: '/musics_pictures/Orelsan-et-Gringe-sont-les-Caeurs-Flowters.jpg',
    releaseDate: '2013-11-15',
    rating: 0,
    duration: 404,
    genre: 'Rap/Hip-Hop',
    timesListened: 250,
  },

  // Album : Comment c'est loin (2015) - Casseurs Flowters
  {
    title: 'Nouvelle journée',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 104,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Au bout du compte',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 178,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: "À l'heure où je me couche",
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 220,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: "Quand ton père t'engueule",
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: 'En boucle',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 236,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: "Faut qu'on rentre bosser",
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 102,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Freestyle Radio Phoenix',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 252,
    genre: 'Rap/Hip-Hop',
    timesListened: 120,
  },
  {
    title: 'Le mal est fait',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 186,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: "C'est toujours 2 connards dans un abribus",
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 157,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: "Pas n'importe quel toon",
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: "J'essaye, j'essaye",
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 233,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Promenade imprévue',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 90,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Xavier',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Wondercash',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 78,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: "On est resté à l'hôtel",
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 97,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Si facile',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 236,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Inachevés',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Quand on descend vers le centre',
    artist: 'Casseurs Flowters',
    album: "Comment c'est loin",
    coverUrl: '/musics_pictures/Comment-c-est-loin.jpg',
    releaseDate: '2015-12-04',
    rating: 0,
    duration: 174,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
];
