import { Music } from '../../../../models/music-model';

export const musicsZippo: Music[] = [
  // Album : Zippo contre les robots (2023)
  {
    title: 'Noeud de cravate',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 194,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Le meilleur des mondes',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 222,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Google',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 133,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: "L'homme a la tete creuse",
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Greenwashing',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Charlie',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: "Palme d'or",
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'La mer monte',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Hemorragie',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Cap 3000',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 160,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Le dernier cri',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 141,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'In girum imus nocte',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 154,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'i-monde',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 396,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'In mars we trust',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 284,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Etincelle',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2023-03-17',
    rating: 0,
    duration: 249,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
];
