import { Music } from '../../../../models/music-model';

export const musicsSoprano: Music[] = [
  // Album : Puisqu'il faut vivre (2007)
  {
    title: 'Donc',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 83,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Le divan',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 188,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: "Mélancolique anonyme (feat Diam's)",
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bombe humaine',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 338,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Halla Halla',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 284,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Dans ma tête',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: "Moi j'ai pas",
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 222,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La famille (feat Léa Castel)',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 252,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Tant que Dieu (Remix) (feat Mino)',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 274,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Juste fais le (feat Le Rat Luciano)',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 253,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Le bistro du coin',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 82,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'À la bien!',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 238,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: 'Welcome (feat Psy 4 de la rime)',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 285,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Parle-moi',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 331,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Ferme les yeux et imagine-toi (feat Blacko)',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 276,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Passe-moi le mic',
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 253,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: "Puisqu'il faut vivre",
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 356,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "L'hiver d'un été (Bonus)",
    artist: 'Soprano',
    album: "Puisqu'il faut vivre",
    coverUrl: '/musics_pictures/61cpKtauaxL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-10-22',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Cosmopolitanie (2009)
  {
    title: 'Préface',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Cosmo',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 181,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Ils nous connaissent pas',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Clown',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 269,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Fresh Prince (featuring Uncle Phil)',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Hello',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Justice',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 260,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le pain',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Danse ce soir / Midnightlude',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 391,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Kalash & Roses',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 300,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ti Amo',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 246,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Même pas un peu',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'M. et Mme Smith (featuring Kayna Samet)',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 288,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Luna',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mélancolie',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bomb [Titre Bonus iTunes]',
    artist: 'Soprano',
    album: 'Cosmopolitanie',
    coverUrl: '/musics_pictures/61zeTvl+AsL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-18',
    rating: 0,
    duration: 165,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : E = 2 MC's (2011)
  {
    title: 'Le labo',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Flow siamois',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Avant de s'en aller",
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Meskine',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "J'ai vu",
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Simple constat 5',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Rêves et illusions',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Le temps d'une pause (avec Sarah Riani)",
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Afrika',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Je rappe comme ça me chante',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Secret de polichinelle (avec Carpe Diem)',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'A plumes ouvertes',
    artist: 'Soprano',
    album: "E = 2 MC's",
    coverUrl: '/musics_pictures/91XcmBZQgWL.jpg',
    releaseDate: '2011-11-21',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'En feu',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },

  // Psy 4 de la Rime
  {
    title: 'Le son des bandits',
    artist: 'Psy 4 de la Rime',
    album: 'Block Party',
    coverUrl: '/musics_pictures/psy4-block-party.jpg',
    releaseDate: '2002-07-08',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le monde est stone',
    artist: 'Psy 4 de la Rime',
    album: '4ème Dimension',
    coverUrl: '/musics_pictures/psy4-4eme-dimension.jpg',
    releaseDate: '2005-05-30',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Autres sorties
  {
    title: 'Tant que Dieu (feat. Mino) - Remix',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Ferme les yeux et imagine toi (feat.Blacko)',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Soprakountach',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Juste fais-le (feat. Le Rat Luciano)',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Le bistrot du coin',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Millionnaire',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Hiro (feat. Indila)',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'La Boulette (Génération Nan Nan) - Live 2006',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Intro (Renaissance)',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Zoum (feat. Niska)',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'La force de reconstruire (feat. Don Diego et K-Rlos)',
    artist: 'Soprano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
