import { Music } from '../../../../models/music-model';

export const musicsKik: Music[] = [
  // Album : Puzzle (2019)
  {
    title: 'Intro (Puzzle)',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Démonté (feat. De La Hoz)',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Algie',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: '4 millions',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 38,
  },
  {
    title: 'Par habitude',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Ikigai',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: "Quand j'étais petit",
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Adieu',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'SOS',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "T'es la meilleure",
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bandana Mauve',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 39,
  },
  {
    title: 'Dernier texto',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Megazord (feat. P.Prod)',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: '1000 façons',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Très loin',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tous les jours',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La Paix',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Oui',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },

  // Album : Rubi (2022)
  {
    title: "L'histoire commence comme ça",
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Rubi (feat. Rubi)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Encore une',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'rap_machinev2.1.exe',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Ma tess',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Tout ira bien (feat. Soprano)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Nul au foot',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Interlude : 5 étoiles',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 120,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Poudre dodo (feat. Rubi)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Interlude : l'enveloppe verte",
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 120,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Lettre a mon ex',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Pachémwa (feat. Bigflo & Oli)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 29,
  },
  {
    title: 'Jamais content',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ça va ?',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Au fond du miroir',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "L'anniversaire de Julie (feat. Rubi)",
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
];
