import { Music } from '../../../../models/music-model';

export const musicsKizito: Music[] = [
  // Album : Fallait pas me chercher (2008)
  {
    title: 'Kizintro',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Scorpion noir',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Émeutes',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'La famille',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ma life',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Brandon & Brenda (Clash Sinik & Diam's)",
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ghetto Girls',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "La plume et l'enclume",
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Lettre à Mélanie',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Le monde m'appartient",
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Bienvenue',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Challenger',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Le plus vrai',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Touche pas',
    artist: 'Kizito',
    album: 'Fallait pas me chercher',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-03-24',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
];

