import { Music } from '../../../../models/music-model';

export const musicsDiams: Music[] = [
  // Album : Brut de femme (2003)
  {
    title: 'Intro',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 38,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Incassables',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 244,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Mon répertoire',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 329,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Cruelle à vie',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 392,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'DJ',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 269,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Madame qui ?',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 236,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: '1980',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 220,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Où je vais',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 291,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Vénus',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 166,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ma souffrance',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 344,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Évasion',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 303,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Amoré',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 259,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Daddy',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 270,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Parce que',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 242,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Suzy (2003)',
    artist: "Diam's",
    album: 'Brut de femme',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2003-03-03',
    rating: 0,
    duration: 253,
    genre: 'Rap français',
    timesListened: 0,
  },

  // Album : Dans ma bulle (2006)
  {
    title: 'Introduction',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 72,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'La Boulette (Génération nan nan)',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 231,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ma France à moi',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 273,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Feuille blanche',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 320,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Jeune Demoiselle',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 291,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Car tu portes mon nom',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 341,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Marine',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 341,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Dans ma bulle',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 315,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Par amour',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 403,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Big up',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 333,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Confessions nocturnes',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 360,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'T.S.',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 272,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Me revoilà',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 287,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Cause à effet',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 319,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Petite banlieusarde',
    artist: "Diam's",
    album: 'Dans ma bulle',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-02-27',
    rating: 0,
    duration: 412,
    genre: 'Rap français',
    timesListened: 0,
  },
];

