import { Music } from '../../../../models/music-model';

export const musicsFatalBazooka: Music[] = [
  {
    title:
      'Ce matin va être une pure soirée (feat. Big Ali, PZK, Dogg SoSo, Chris Prolls)',
    artist: 'Fatal Bazooka',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 213,
    genre: 'Unknown',
    timesListened: 120,
  },
  {
    title: 'Stach Stach',
    artist: 'Bratisla Boys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 164,
    genre: 'Unknown',
    timesListened: 80,
  },
  // Album : T'as vu ? (2007) - Fatal Bazooka
  {
    title: "Intro : T'as vu",
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 97,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: 'Fous ta cagoule',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 205,
    genre: 'Rap Parodique',
    timesListened: 200,
  },
  {
    title: 'Viens bégère',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 227,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: "J'aime trop ton boule",
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 217,
    genre: 'Rap Parodique',
    timesListened: 180,
  },
  {
    title: 'MC Chamallow',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 66,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: 'Viva Bazooka',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 277,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: 'Saturday Night Kebab',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 214,
    genre: 'Rap Parodique',
    timesListened: 100,
  },
  {
    title: 'Ouais ma gueule',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 222,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: 'Ego trip',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 256,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: 'MC Introverti',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 39,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: 'Mauvaise foi nocturne',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 367,
    genre: 'Rap Parodique',
    timesListened: 250,
  },
  {
    title: 'Sale connasse',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 237,
    genre: 'Rap Parodique',
    timesListened: 80,
  },
  {
    title: 'Chienne de vie',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 224,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: "C'est une pute !",
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 94,
    genre: 'Rap Parodique',
    timesListened: 80,
  },
  {
    title: 'Auto-clash',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 292,
    genre: 'Rap Parodique',
    timesListened: 100,
  },
  {
    title: 'MC Québec City',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 105,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
  {
    title: 'Parle à ma main',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 252,
    genre: 'Rap Parodique',
    timesListened: 100,
  },
  {
    title: 'Trankillement',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 206,
    genre: 'Rap Parodique',
    timesListened: 120,
  },
  {
    title: 'Crêpes au froment',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 356,
    genre: 'Rap Parodique',
    timesListened: 10,
  },
];
