import { Music } from '../../../../models/music-model';

export const musicsOrelsan2: Music[] = [
  // Album : Civilisation (2021)
  {
    title: 'Shonen',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 185,
    genre: 'Rap/Hip-Hop',
    timesListened: 77,
  },
  {
    title: 'La Quête',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 66,
  },
  {
    title: "L'odeur de l'essence",
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Du propre',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 67,
  },
  {
    title: 'Rêve mieux',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 48,
  },
  {
    title: 'Bébéboa',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 36,
  },
  {
    title: 'Manifeste',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 59,
  },
  {
    title: 'Dernier verre',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 206,
    genre: 'Rap/Hip-Hop',
    timesListened: 32,
  },
  {
    title: 'Ensemble',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 190,
    genre: 'Rap/Hip-Hop',
    timesListened: 46,
  },
  {
    title: 'Casseurs Flowters Infinity',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 46,
  },
  {
    title: 'Athéna',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 45,
  },
  {
    title: 'Baise le monde',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 55,
  },
  {
    title: 'Jour meilleur',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 40,
  },
  {
    title: 'Seul avec du monde autour',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 84,
  },
  {
    title: 'Civilisation',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 235,
    genre: 'Rap/Hip-Hop',
    timesListened: 48,
  },

  // Album : Civilisation Perdue (Réédition 2022)
  {
    title: 'Intro Civilisation perdue',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 142,
    genre: 'Rap/Hip-Hop',
    timesListened: 59,
  },
  {
    title: 'Les aventures de Minisan',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Toujours perdu quand même',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Juste un dernier',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Ok... Super...',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Ah la France',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Point de rupture',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Nous contre le monde',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 226,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Évidemment',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'On a gagné',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },

  // Album : La fuite en avant (2025)
  {
    title: 'Le pacte',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 268,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Plus rien (feat. Lilas)',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Ailleurs',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Boss',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Deux et demi',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 228,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Osaka',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 191,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Encore une fois (feat. Yamê)',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 181,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Internet',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 101,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Dans quelques mois',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Oulalalala (feat. Fifty Fifty)',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 162,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Tellement d'amis",
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 228,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'La petite voix',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 242,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Sama',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Soleil levant (feat. SDM)',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 204,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Les monstres',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 191,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Épiphanie',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 267,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Yoroï (feat. Thomas Bangalter)',
    artist: 'Orelsan',
    album: 'La fuite en avant',
    coverUrl: '/musics_pictures/La-fuite-en-avant.jpg',
    releaseDate: '2025-10-31',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  {
    title: 'Qui dit mieux (feat. Orelsan, Vald & Suikon Blaz AD)',
    artist: 'Gringe',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
];
