import { Music } from '../../../../models/music-model';

export const musicsOrelsan: Music[] = [
  // Album : Perdu d'avance (2009)
  {
    title: 'Étoiles Invisibles',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 274,
    genre: 'Rap/Hip-Hop',
    timesListened: 34,
  },
  {
    title: 'Changement',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Soirée ratée',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 185,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Différent',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'No Life',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Pour le pire',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: "Perdu d'avance",
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Gros poisson dans une petite mare',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 273,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Logo dans le ciel',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: '50 pour cent',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 280,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: 'Jimmy Punchline',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 246,
    genre: 'Rap/Hip-Hop',
    timesListened: 26,
  },
  {
    title: 'Entre bien et mal (feat. Gringe)',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 281,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: 'Courez courez',
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 243,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: "La peur de l'échec (feat. Ron Thal)",
    artist: 'Orelsan',
    album: "Perdu d'avance",
    coverUrl: '/musics_pictures/71gsm0h2ksL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-10-19',
    rating: 0,
    duration: 314,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },

  // Album : Le Chant des sirènes (2011)
  {
    title: 'Raelsan',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 36,
  },
  {
    title: 'Le Chant des sirènes',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: "Plus rien ne m'étonne",
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mauvaise idée',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Double vie',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Finir mal',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 220,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Si seul',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Des trous dans la tête',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 188,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'La Petite Marchande de porte-clefs',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: '1990',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 194,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: '2010',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 164,
    genre: 'Rap/Hip-Hop',
    timesListened: 33,
  },
  {
    title: 'La Morale',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Elle viendra quand même',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: 'Suicide social',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'La Terre est ronde',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 34,
  },
  {
    title: 'Ils sont cools',
    artist: 'Orelsan',
    album: 'Le Chant des sirènes',
    coverUrl: '/musics_pictures/71Usm9m43ML._UF894,1000_QL80_.jpg',
    releaseDate: '2011-09-26',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },

  // Album : La fête est finie (2017)
  {
    title: 'San',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 54,
  },
  {
    title: 'La fête est finie',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 36,
  },
  {
    title: 'Basique',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Tout va bien',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Défaite de famille',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 41,
  },
  {
    title: 'La lumière',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Bonne meuf',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'Zone',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Dans ma ville, on traîne',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La pluie',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 232,
    genre: 'Rap/Hip-Hop',
    timesListened: 38,
  },
  {
    title: 'Paradis',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: "Quand est-ce que ça s'arrête",
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Christophe',
    artist: 'Orelsan',
    album: 'La fête est finie',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2017-10-20',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 34,
  },
  {
    title: 'Notes pour trop tard',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/71sP99FzAJL.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 39,
  },

  // Album : La fête est finie - Épilogue (2018)
  {
    title: 'Rêves bizarres',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 226,
    genre: 'Rap/Hip-Hop',
    timesListened: 26,
  },
  {
    title: 'Fantômes',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 41,
  },
  {
    title: 'Discipline',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 194,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Adieu les filles',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 45,
  },
  {
    title: 'Tout ce que je sais',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 34,
  },
  {
    title: 'Épilogue',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Mes grands-parents',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 53,
  },
  {
    title: 'Excuses ou mensonges',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 210,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'La famille, la famille',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 222,
    genre: 'Rap/Hip-Hop',
    timesListened: 53,
  },
  {
    title: 'Dis-moi',
    artist: 'Orelsan',
    album: 'La fête est finie - Épilogue',
    coverUrl: '/musics_pictures/La-fete-est-finie-epilogue.jpg',
    releaseDate: '2018-11-23',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },

  // Album : Civilisation (2021)
  {
    title: 'Shonen',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 185,
    genre: 'Rap/Hip-Hop',
    timesListened: 77,
  },
  {
    title: 'La Quête',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 66,
  },
  {
    title: "L'odeur de l'essence",
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Du propre',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 67,
  },
  {
    title: 'Rêve mieux',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 48,
  },
  {
    title: 'Bébéboa',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 36,
  },
  {
    title: 'Manifeste',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 59,
  },
  {
    title: 'Dernier verre',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 206,
    genre: 'Rap/Hip-Hop',
    timesListened: 32,
  },
  {
    title: 'Ensemble',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 190,
    genre: 'Rap/Hip-Hop',
    timesListened: 46,
  },
  {
    title: 'Casseurs Flowters Infinity',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 46,
  },
  {
    title: 'Athéna',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 45,
  },
  {
    title: 'Baise le monde',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 55,
  },
  {
    title: 'Jour meilleur',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 40,
  },
  {
    title: 'Seul avec du monde autour',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 84,
  },
  {
    title: 'Civilisation',
    artist: 'Orelsan',
    album: 'Civilisation',
    coverUrl: '/musics_pictures/71BgEe4BtLL._UF894,1000_QL80_.jpg',
    releaseDate: '2021-11-19',
    rating: 0,
    duration: 235,
    genre: 'Rap/Hip-Hop',
    timesListened: 48,
  },

  // Album : Civilisation Perdue (Réédition 2022)
  {
    title: 'Intro Civilisation perdue',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 142,
    genre: 'Rap/Hip-Hop',
    timesListened: 48,
  },
  {
    title: 'Les aventures de Minisan',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Toujours perdu quand même',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Juste un dernier',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Ok... Super...',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Ah la France',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Point de rupture',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Nous contre le monde',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 226,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Évidemment',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'On a gagné',
    artist: 'Orelsan',
    album: 'Civilisation Perdue',
    coverUrl: '/musics_pictures/orelsan_civilisation_perdue.jpg',
    releaseDate: '2022-02-04',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  {
    title: 'Qui dit mieux (feat. Orelsan, Vald & Suikon Blaz AD)',
    artist: 'Gringe',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
];
