import { Music } from '../../../../models/music-model';

export const musicsKenyArkana: Music[] = [
  // Album : Entre ciment et belle étoile (2006)
  {
    title: 'Entre Les Mots : Enfant De La Terre',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 68,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le Missile Suit Sa Lancée',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 199,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "J'Viens De L'Incendie",
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 254,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "J'Me Barre",
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'La Mère Des Enfants Perdus',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Entre Les Lignes : Clouée Au Sol',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Eh Connard',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 241,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'La Rage',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 242,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Le Fardeau',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 330,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Cueille Ta Vie',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Nettoyage Au Kärcher',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Victoria',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Entre Les Mots : Du Local Au Global',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 112,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Jeunesse Du Monde',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 325,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ils Ont Peur De La Liberté',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Je Suis La Solitaire',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 286,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: "Sans Terre D'Asile",
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 247,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Entre Les Lignes : Une Goutte De Plus',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 200,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Entre Les Lignes : Prière',
    artist: 'Keny Arkana',
    album: 'Entre ciment et belle étoile',
    coverUrl: '/musics_pictures/71hZnXQGLYL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-10-23',
    rating: 0,
    duration: 258,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Tout tourne autour du soleil (2012)
  {
    title: 'Intro : Tout tourne autour du soleil',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Esprits libres',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 237,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Le Syndrome de l'exclu (feat. RPZ)",
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 222,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Capitale de la rupture',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 169,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Entre les lignes #1 : Car nous sommes le monde',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Vie d'artiste",
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 268,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Gens pressés',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 243,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Cynisme vous a tué ?',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 305,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Indignados',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 241,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Casse le schéma',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "J'ai osé",
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 259,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Entre les lignes #2 : 20.12',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 322,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Y a urgence !',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 226,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le monde est notre reflet',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Cherche en toi',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 220,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Fille du vent',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 235,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tout tourne autour du soleil',
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 237,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Retour à la terre / Le Retour de l'enfant prodigue",
    artist: 'Keny Arkana',
    album: 'Tout tourne autour du soleil',
    coverUrl: '/musics_pictures/81BH3H3CB7L._UF894,1000_QL80_.jpg',
    releaseDate: '2012-10-29',
    rating: 0,
    duration: 515,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
];
