import { Music } from '../../../../models/music-model';

export const musicsBooba: Music[] = [
  // Album : Mauvais oeil (2000)
  {
    title: 'Introduction',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 120,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Pas l'temps pour les regrets",
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 281,
    genre: 'Rap français',
    timesListened: 10,
  },
  {
    title: 'Groupe sanguin',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 213,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "L'effort de paix",
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 273,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'La lettre',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 290,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Si tu kiffes pas...',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 270,
    genre: 'Rap français',
    timesListened: 20,
  },
  {
    title: 'Têtes brûlées',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 258,
    genre: 'Rap français',
    timesListened: 20,
  },
  {
    title: '92 I',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 347,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'HLM 3',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 319,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Le son qui met la pression',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 260,
    genre: 'Rap français',
    timesListened: 20,
  },
  {
    title: 'Avertisseurs',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 270,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Le silence n'est pas un oubli",
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 297,
    genre: 'Rap français',
    timesListened: 5,
  },
  {
    title: 'Mauvais Œil',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 206,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Civilisé',
    artist: 'Booba',
    album: 'Mauvais oeil',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-10-24',
    rating: 0,
    duration: 274,
    genre: 'Rap français',
    timesListened: 0,
  },

  // Album : Temps mort (2002)
  {
    title: 'Temps mort',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 144,
    genre: 'Rap français',
    timesListened: 10,
  },
  {
    title: 'Indépendants',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 233,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Écoute bien',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 272,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ma définition',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 216,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Jusqu'ici tout va bien",
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 288,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Repose en paix',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 172,
    genre: 'Rap français',
    timesListened: 30,
  },
  {
    title: 'Le bitume avec une plume',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 284,
    genre: 'Rap français',
    timesListened: 10,
  },
  {
    title: 'Animals',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 276,
    genre: 'Rap français',
    timesListened: 10,
  },
  {
    title: 'Sans ratures',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 276,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: '100-8 Zoo',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 402,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "On m'a dit",
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 255,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Nouvelle école',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 253,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'De mauvais augure',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 214,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Strass et paillettes',
    artist: 'Booba',
    album: 'Temps mort',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2002-12-23',
    rating: 0,
    duration: 289,
    genre: 'Rap français',
    timesListened: 20,
  },

  // Album : Panthéon (2004)
  {
    title: 'Tallac',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 244,
    genre: 'Rap français',
    timesListened: 10,
  },
  {
    title: 'Le mal par le mal',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 129,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Commis d'office",
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 309,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'N°10',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 279,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: 'Hors-saison',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 283,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'R.A.P.',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 236,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Baby',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 271,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'La Faucheuse',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 282,
    genre: 'Rap français',
    timesListened: 20,
  },
  {
    title: 'Mon son',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 169,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Alter égo',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 255,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Pazalaza pour sazamuser',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 165,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Bâtiment C',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 223,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Avant de partir',
    artist: 'Booba',
    album: 'Panthéon',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 325,
    genre: 'Rap français',
    timesListened: 20,
  },

  // Album : Ouest side (2006)
  {
    title: 'Mauvais garçon',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 87,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Garde la pêche',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 171,
    genre: 'Rap français',
    timesListened: 180,
  },
  {
    title: 'Le Duc de Boulogne',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 218,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: 'Boîte vocale',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 209,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Boulbi',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 243,
    genre: 'Rap français',
    timesListened: 180,
  },
  {
    title: 'Ouest Side',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 220,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: '92izi',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 302,
    genre: 'Rap français',
    timesListened: 30,
  },
  {
    title: 'Ouais ouais',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 274,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Pitbull',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 229,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: 'Je me souviens',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 210,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Le météore',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 224,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Au bout des rêves',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 264,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: 'Gun in Hand',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 282,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: 'Au fond de la classe',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 235,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Couleur ébène',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 220,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Outro',
    artist: 'Booba',
    album: 'Ouest side',
    coverUrl: '/musics_pictures/81JUKn3FiSL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-02-20',
    rating: 0,
    duration: 174,
    genre: 'Rap français',
    timesListened: 30,
  },

  // Album : Autopsie Vol. 2 (2007)
  {
    title: 'Intro',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 12,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Garcimore',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 181,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Le D.U.C.',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 262,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Boulbi (Freestyle Cut Killer Show)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 83,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Intro (Mixtape Evolution)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 69,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Tu m'connais pas",
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 268,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ouais ouais (Freestyle Planète Rap)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 24,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Me And You (Remix)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 175,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'All I Have',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 204,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Du biff',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 308,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Freestyle',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 61,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Nique sa mère',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 211,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Mauvais garçon (Remix)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 162,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Je me souviens (Freestyle)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 77,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Quoi qu'il arrive",
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 115,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Hustlin' (Remix)",
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 238,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ouest Side (Freestyle)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 50,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Momma',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 126,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Intro (Patrimoine du Ghetto)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 104,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "On sait l'faire",
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 67,
    genre: 'Rap français',
    timesListened: 30,
  },
  {
    title: 'Boîte vocale (Freestyle)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 45,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Monnaie dans l'crâne",
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 132,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Tout et tout d'suite",
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 147,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Au bout des rêves (Freestyle)',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 122,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Outro',
    artist: 'Booba',
    album: 'Autopsie Vol. 2',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2007-10-15',
    rating: 0,
    duration: 44,
    genre: 'Rap français',
    timesListened: 0,
  },

  // Album : Autopsie Vol. 3 (2008)
  {
    title: 'Intro',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 68,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'A3',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 126,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Double Poney',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 322,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: 'Non Stop',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 257,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Bienvenue dans le Texas',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 55,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Ne me parle pas de rue',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 332,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Trashhh',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 249,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'La vie en rouge',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 156,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Murderer',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 152,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Liberation Time (Remix)',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 192,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Millionnaire',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 272,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Diamond Girl',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 67,
    genre: 'Rap français',
    timesListened: 50,
  },
  {
    title: 'Rats des villes',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 224,
    genre: 'Rap français',
    timesListened: 100,
  },
  {
    title: 'Reste en chien',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 72,
    genre: 'Rap français',
    timesListened: 120,
  },
  {
    title: 'Salade, tomates, oignons (Yuksek Remix)',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 194,
    genre: 'Rap français',
    timesListened: 80,
  },
  {
    title: 'Ride',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 243,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Un grand de demain',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 215,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'On contrôle la zone',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 229,
    genre: 'Rap français',
    timesListened: 30,
  },
  {
    title: 'Démarrer',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 187,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'El Dorado',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 220,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Maman dort',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 53,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Fœtus',
    artist: 'Booba',
    album: 'Autopsie Vol. 3',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 297,
    genre: 'Rap français',
    timesListened: 80,
  },
];
