import { Music } from '../../../../models/music-model';

export const musicsMcSolaar: Music[] = [
  // Album : Géopoétique (2017)
  {
    title: 'Intronisation',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 195,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Sonotone',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 229,
    genre: 'Rap français',
    timesListened: 7,
  },
  {
    title: "L'attrape-nigaud",
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 237,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Frozen Fire - Осторожно',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 194,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Jane et Tarzan',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 192,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'EKSASSAUTE',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 206,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'La clé',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 107,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Les mirabelles',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 244,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Mephisto Iblis',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 233,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: "J.A.Z.Z - Kiffez l'âme",
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 171,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Super Gainsbarre',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 207,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'I Need Gloves',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 215,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Adam et Ève',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 257,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'On se lève',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 196,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Zonmé des zombies',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 135,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Aiwa',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 183,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Géopoétique',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 244,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Pili-pili',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 168,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'La venue du MC',
    artist: 'MC Solaar',
    album: 'Géopoétique',
    coverUrl: '/musics_pictures/7_0190295763619.jpg',
    releaseDate: '2017-06-02',
    rating: 0,
    duration: 152,
    genre: 'Rap français',
    timesListened: 1,
  },

  // Autres sorties
  {
    title: 'Caroline',
    artist: 'MC Solaar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 10,
  },
  {
    title: 'Da Vinci Claude',
    artist: 'MC Solaar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 6,
  },
];
