import { Music } from '../../../../models/music-model';

export const musicsKeryJames: Music[] = [
  // Single : Lettre à la république
  {
    title: 'Lettre à la république',
    artist: 'Kery James',
    album: 'Lettre à la république',
    coverUrl: '/musics_pictures/kery-james-lettre-a-la-republique.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 300,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },

  // Album : À l'ombre du show business (2008)
  {
    title: 'Banlieusards',
    artist: 'Kery James',
    album: "À l'ombre du show business",
    coverUrl: '/musics_pictures/kery-james-a-lombre-du-show-business.jpg',
    releaseDate: '2008-01-28',
    rating: 0,
    duration: 470,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },

  // Album : Réel (2009)
  {
    title: 'Je représente',
    artist: 'Kery James',
    album: 'Réel',
    coverUrl: '/musics_pictures717k+HStnyL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-11-30',
    rating: 0,
    duration: 266,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le respect du silence (feat. Le Rat Luciano)',
    artist: 'Kery James',
    album: 'Réel',
    coverUrl: '/musics_pictures717k+HStnyL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-11-30',
    rating: 0,
    duration: 330,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Dernier MC (2013)
  {
    title: 'Dernier MC',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 400,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: "Vent d'État",
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 333,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "À l'horizon (feat. Corneille)",
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 268,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Y'a rien (feat. Niro)",
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Quatre Saisons',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 389,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Love Music',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 347,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: "94 c'est le Barça",
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 254,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La vie en rêve (feat. Zaho)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 284,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Jamais sans mon poto',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Le mystère féminin (feat. Imany)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 186,
    genre: 'Rap/Hip-Hop',
    timesListened: 45,
  },
  {
    title: 'La mort qui va avec...',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 294,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Des mots (feat. LFDV aka Laura Léda)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 252,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Contre nous (feat. La Ligue: Médine et Youssoupha)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 371,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: 'Constat Amer',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 411,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Post Scriptum (écrit par Brav)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 374,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Parti de loin (feat. Kenyon Dixon)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 270,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: '9Trap Music',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 273,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Soldier (feat. Capleton)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 315,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title:
      'Dernier MC Remix pt. 1 (feat. Lino, Tunisiano, REDK, Médine, 2e France, Scylla, Ladea, Fababy, Orelsan)',
    artist: 'Kery James',
    album: 'Dernier MC',
    coverUrl: '/musics_pictures/81skCGZ7i7L._UF894,1000_QL80_.jpg',
    releaseDate: '2013-09-02',
    rating: 0,
    duration: 341,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },

  // Album : Mouhammad Alix (2016)
  {
    title: 'Mouhammad Alix',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 266,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Douleur ébène',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 313,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Pense à moi (featuring Madame Monsieur)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 252,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Jamais (featuring Nov)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 285,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La rue ça fait mal',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 283,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Des morceaux de nous (featuring Cléo)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "D'où j'viens",
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 291,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Prends le temps (featuring Faada Freddy)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 305,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Paradoxal (featuring Cléo)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 294,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Rue de la peine (featuring Toma)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 251,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Vivre ou mourir ensemble',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 375,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Musique nègre (featuring Lino & Youssoupha)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ailleurs (featuring Toma)',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "N'importe quoi",
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Racailles',
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 396,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: "J'suis pas un héros",
    artist: 'Kery James',
    album: 'Mouhammad Alix',
    coverUrl: '/musics_pictures/Mouhammad-Alix.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 249,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
];
