import { Music } from '../../../../models/music-model';

export const musicsYoussoupha: Music[] = [
  {
    title: 'B.A.O. - Bouche à oreille',
    artist: 'Youssoupha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 22,
  },
  // Album : À chaque frère (2007) - Youssoupha
  {
    title: 'À chaque frère',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Ma destinée',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Les apparences nous mentent',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Macadam',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Dangereux',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Les meilleurs ennemis',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Nouveau désordre',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ma sueur et mes larmes',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'One love',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Scénario',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'En marge',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Dans une autre vie',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Le monde est à vendre',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Rendons à Césaire...',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Classique (plus rien ne m'étonne)",
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Éternel recommencement',
    artist: 'Youssoupha',
    album: 'À chaque frère',
    coverUrl: '/musics_pictures/81BnFdzu3fL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },

  // Album : Sur les chemins du retour (2009) - Youssoupha
  {
    title: 'Aéroport (intro)',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 125,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Apprentissage',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: "Itinéraire d'un blédard devenu banlieusard",
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 235,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'A force de le dire',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: "Le ghetto n'est pas un abri",
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Calmement',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Escale (interlude)',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 95,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'La même adresse',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Le message',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: "L'effet papillon",
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Check de l'épaule",
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Dans la légende',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Quinze ans en arrière',
    artist: 'Youssoupha',
    album: 'Sur les chemins du retour',
    coverUrl: '/musics_pictures/81zjMa7D-vL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-03-30',
    rating: 0,
    duration: 229,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },

  // Album : Noir Désir (2012) - Youssoupha
  {
    title: "L'Amour",
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 246,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Viens',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 241,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: "J'ai changé",
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 254,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Menace de mort',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Histoires vraies',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 278,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Irréversible',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 243,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Les Disques de mon père',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 296,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: "L'enfer c'est les autres",
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 335,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'B.A.O.',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 269,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Gestelude, Pt. 1',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 280,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Noir désir',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: "Tout l'amour du monde",
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 256,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: "Dreamin'",
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 304,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Gestelude, Pt. 2',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 176,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'La vie est belle',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 331,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Espérance de vie',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 325,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: '4h37 (Outro)',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 335,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Poids plume Remix (Bonus Itunes Version)',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 287,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'On se connaît (Bonus Version Deluxe)',
    artist: 'Youssoupha',
    album: 'Noir Désir',
    coverUrl: '/musics_pictures/Noir-d.jpg',
    releaseDate: '2012-03-05',
    rating: 0,
    duration: 274,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },

  // Album : NGRTD (2015) - Youssoupha
  {
    title: "Où est l'amour ?",
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 191,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Salaam',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 277,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Points communs',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 279,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: "Maman m'a dit",
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Memento',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Love Musik',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'À cause de moi',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 199,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Chanson française',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Entourage',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 300,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Le score',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Niquer ma vie',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 269,
    genre: 'Rap/Hip-Hop',
    timesListened: 60,
  },
  {
    title: 'Mannschaft',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 293,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Black Out',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Smile',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: 'Négritude',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 267,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: 'Mourir mille fois',
    artist: 'Youssoupha',
    album: 'NGRTD',
    coverUrl: '/musics_pictures/NGRTD.jpg',
    releaseDate: '2015-10-16',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },

  // Album : Polaroïd Experience (2018) - Youssoupha
  {
    title: 'Polaroid experience',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 330,
    genre: 'Rap/Hip-Hop',
    timesListened: 36,
  },
  {
    title: 'La cassette',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 94,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Devenir vieux',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 302,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: "M'en aller",
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 194,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: "Avoir de l'argent",
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 253,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Les sentiments à l'envers",
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 228,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Alléluia / 1989',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 282,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Par amour',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Niama na yo',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 120,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Devant',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Mourir ensemble',
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 266,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: "Le jour où j'ai arrêté le rap",
    artist: 'Youssoupha',
    album: 'Polaroïd Experience',
    coverUrl: '/musics_pictures/91kbLnSVUFL._UF894,1000_QL80_.jpg',
    releaseDate: '2018-10-12',
    rating: 0,
    duration: 275,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Neptune Terminus (2021) - Youssoupha
  {
    title: 'HOUSTON - INTRO',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 12,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'ASTRONAUTE',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'SOLAAR PLEURE',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'GOSPEL',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 166,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'KASH',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'BAGARRER',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 186,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'MARYAM',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'NEPTUNE TERMINUS',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'INTERSTELLAR',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'MON ROI',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 60,
  },
  {
    title: 'AMBITION - GUINÉE CONAKRY',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 165,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'COLLISION',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 170,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'APRÈS-SOIRÉE',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'À CHAQUE JOUR...',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 226,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'BOOMERANG',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 116,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'LA FIN DU MONDE',
    artist: 'Youssoupha',
    album: 'Neptune Terminus',
    coverUrl: '/musics_pictures/Neptune-Terminus-Origines.jpg',
    releaseDate: '2021-06-18',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },

  // Album : Amour Suprême (2025) - Youssoupha
  {
    title: 'Suprême',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 140,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Zequin theory',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Nouveau karaté',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 160,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Les Almadies (interlude)',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 91,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Dieu est grande',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 176,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Faire mieux',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 191,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Gospel Molotov',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 130,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Grand boubou des ancêtres',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Prose Combat',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Amour Suprême',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 134,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'God Bless',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 171,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Gigi',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 174,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Prier sans crainte',
    artist: 'Youssoupha',
    album: 'Amour Suprême',
    coverUrl: '/musics_pictures/ab67616d0000b273202591c956989a984bd93147.jpg',
    releaseDate: '2025-01-24',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },

  // Autres sorties
  {
    title: 'Aéroport',
    artist: 'Youssoupha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'I Know - Street Remix',
    artist: 'Youssoupha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'AMAPIANO',
    artist: 'Youssoupha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Youssoupha est mort',
    artist: 'Youssoupha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
