import { Music } from '../../../../models/music-model';

export const musicsDisiz1: Music[] = [
  // Album : Le Poisson Rouge (2000) - Disiz La Peste
  {
    title: 'Intro',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 86,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Le challenger',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 164,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Un scratch, un beat, un rap',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 235,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "J'pète les plombs",
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "C'est ça la France",
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 275,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Dieu seul sait quand le glas sonne',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 182,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "J'irai cracher sur vos tombes",
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 362,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Ghetto sitcom',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 292,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Fuck Disiz',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 87,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Klash pas quand même',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 452,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Plus l'temps",
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "L'associé du diable",
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 150,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "L'avocat des anges",
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 270,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Lyrics de gamin',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 278,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Gnibi',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 228,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'La philosophie du hall',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 303,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Le poisson rouge',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 285,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Les rumeurs',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Le 6e sens',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 332,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Outro',
    artist: 'Disiz La Peste',
    album: 'Le Poisson Rouge',
    coverUrl: '/musics_pictures/Le-poisson-rouge.jpg',
    releaseDate: '2000-10-09',
    rating: 0,
    duration: 57,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },

  // Album : Jeu de Société (2003) - Disiz La Peste
  {
    title: 'Force ou faiblesse',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 264,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Déjà-vu',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 300,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Jeu de société',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 293,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "C'est toujours ça, la France",
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Oh, le ouf !',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 188,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Evry Slang',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 56,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Trop de chichis',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 242,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Le Réveil',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 290,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Nébuleuse',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 370,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'MC Pikachu (interlude)',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 106,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Système D',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 276,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'La Trêve',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: '91 Unda',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'À nos actes manqués',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 272,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Cours d'histoire",
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 415,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Insécurité sociale',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 290,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Je suis guèze !',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Viens, on discute',
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 237,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Le bien, c'est ma cible",
    artist: 'Disiz La Peste',
    album: 'Jeu de Société',
    coverUrl: '/musics_pictures/61eS2p2WuAL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-10-06',
    rating: 0,
    duration: 267,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Itinéraire d'un Enfant Bronzé (2004) - Disiz La Peste
  {
    title: "N'Jillou",
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Gnibi',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Sant Yalla',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 371,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Ayoh Neneh',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Djiguën',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 400,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Môm',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "N'Dioukel",
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 256,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Voix du Sénégal',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 342,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Sama Ajana',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Sénégalais de France',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 382,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Soldat de la paix',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 271,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "L'homme rendra des comptes",
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 427,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Aime ton prochain comme toi-même',
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "N'Jillou (Part II)",
    artist: 'Disiz La Peste',
    album: "Itinéraire d'un Enfant Bronzé",
    coverUrl: '/musics_pictures/41DC80VQTDL._UF350,350_QL50_.jpg',
    releaseDate: '2004-11-15',
    rating: 0,
    duration: 199,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Les Histoires Extraordinaires d'un Jeune de Banlieue (2006) - Disiz La Peste
  {
    title: 'Intro (Robin des Halls)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Une Histoire Extraordinaire',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 235,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Inspecteur Disiz (Street Fabulous Remix)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Fuck You (Part 1)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Jeune de Banlieue',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 332,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Lily',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 262,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Mélissa',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 264,
    genre: 'Rap/Hip-Hop',
    timesListened: 26,
  },
  {
    title: 'Bo Gosse',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 243,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'La Fille Facile',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Miss Désillusion',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Mc Pikachou (Ping Pong & King Kong) (interlude)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 87,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Fuck You (Part 2)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 283,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Juste Kiffer',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 230,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Outro (Les Mille Et une Nuits)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Inspecteur Disiz (Titres bonus)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 233,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Métis(Se) (Remix)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 204,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Dans Tes Rêves (Radar Mix) (Titres bonus)',
    artist: 'Disiz La Peste',
    album: "Les Histoires Extraordinaires d'un Jeune de Banlieue",
    coverUrl: '/musics_pictures/81q1t8bf4FL._UF894,1000_QL80_.jpg',
    releaseDate: '2006-03-27',
    rating: 0,
    duration: 206,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },

  // Autres sorties
  {
    title: 'Mahboul',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Disizilla',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Kaïju',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Mastodonte',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Splash',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Terre promise',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Autre espèce',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Hendek',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'POIDS LOURD',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'CASINO',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'RENCONTRE',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Transe-lucide',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
