import { Music } from '../../../../models/music-model';

export const musicsSniper: Music[] = [
  {
    title: 'Panam Hall Starz',
    artist: 'SNIPER',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  // Album : Du rire aux larmes (2001) - Sniper
  {
    title: 'Intro',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 92,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Sniper processus',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 258,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Pris pour cible',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Faut de tout pour faire un monde',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 288,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Intro "Le crew est de sortie"',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 29,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Le crew est de sortie',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 271,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Intro "Tribal poursuite"',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 41,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Tribal poursuite',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 281,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'La France (solo Tunisiano)',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 378,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Intro "Du rire aux larmes"',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 64,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Du rire aux larmes',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Aketo vs. Tunisiano',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'La sentence',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 241,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Quand on te dit',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 236,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Aketo solo (solo Aketo)',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 255,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Fait divers',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'La rumba',
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 259,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "On s'en sort bien",
    artist: 'Sniper',
    album: 'Du rire aux larmes',
    coverUrl: '/musics_pictures/61grGckcuaL.jpg',
    releaseDate: '2001-06-25',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Gravé dans la roche (2003) - Sniper
  {
    title: 'Intro',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 127,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Processus 2003',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 325,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Visions chaotiques',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 442,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Gravé dans la roche',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 285,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Pourquoi',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 307,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Recette maison',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 230,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: "Y'a pas de mérite",
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 246,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Sans (re)pères',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: "Ce que j'ai sur le cœur",
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 312,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: '35 heures',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Hall Story',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 352,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Entre deux',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Trop vite (solo Blacko)',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 337,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Jeteur de pierres',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 377,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Interlude micro ouvert',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 109,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Panam All Starz',
    artist: 'Sniper',
    album: 'Gravé dans la roche',
    coverUrl: '/musics_pictures/61imI6sBCgL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-11-24',
    rating: 0,
    duration: 468,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Trait pour trait (2006) - Sniper
  {
    title: 'S.N.I',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Dans mon monde',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Trait pour trait',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 270,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Eldorado',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 395,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Zamalia (solo Blacko)',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 257,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Génération Tanguy',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 282,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Donne tout',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 271,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "La France (itinéraire d'une polémique) (solo Tunisiano)",
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 401,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Hommes de loi',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 331,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Il était une foi',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 338,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Radio',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 75,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Retour aux sources (solo Aketo)',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 325,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Elle',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 335,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Brûle',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 281,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Fallait que je te dise',
    artist: 'Sniper',
    album: 'Trait pour trait',
    coverUrl: '/musics_pictures/Trait-pour-trait.jpg',
    releaseDate: '2006-10-02',
    rating: 0,
    duration: 577,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Le Regard des gens (2008) - Tunisiano
  {
    title: "Effet d'une bombe",
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Equivoque',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Le regard des gens',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Dégouté',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Toucher mes rêves (feat. Lyricson)',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Nos rues',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Marlich',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Citoyen du monde (feat. Zaho)',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Je porte plainte',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Biographie',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "On s'en fiche (feat. Akil)",
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Qui es tu ?',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Solitude (feat. Amel Bent)',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Carte Postale',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Ensemble',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Répondez-moi',
    artist: 'Tunisiano',
    album: 'Le Regard des gens',
    coverUrl: '/musics_pictures/Le-regard-des-gens.jpg',
    releaseDate: '2008-11-24',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Marqué à vie (2014) - Tunisiano
  {
    title: 'Hurricane Carter',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Marque A Vie (feat. Dokou)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Jeune De Tess',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Etat Sauvage',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Paris (feat. Charles Pasi)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Elle Donne (feat. Klem)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Val 2 Zoive (feat. Lino)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: 'Je Voulais Un Monde',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Ils Nous Condamnent (feat. Youssoupha)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'JCVD',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 29,
  },
  {
    title: 'Fer De Lance',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Amour Poison (feat. Thomas Mignot)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Mout',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Mariage Force (feat. Nassi)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Les Oreilles Qui Sifflent',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Carre (feat. Sofiane, Ol Kainry & Vald)',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Si On Se Disait Tout',
    artist: 'Tunisiano',
    album: 'Marqué à vie',
    coverUrl: '/musics_pictures/Marque-a-vie.jpg',
    releaseDate: '2014-10-27',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },

  // Autres sorties
  {
    title: 'Adama',
    artist: 'SNIPER',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Etat sauvage',
    artist: 'Tunisiano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 9,
  },
  {
    title: 'Mariage forcé',
    artist: 'Tunisiano',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 9,
  },
];
