import { Music } from '../../../../models/music-model';

export const musicsSinik: Music[] = [
  // Album : La main sur le coeur (2004)
  {
    title: 'Une époque formidable',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: '2 victimes / Un coupable',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Mots pour maux',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Viens',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Men in block',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Rêves et cauchemars',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'D 3.3.2.',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Le même sang',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Sombre',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Règlement extérieur',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Rue du paradis',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Pardonnez-moi',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: '100 mesures de haines',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Cœur de pierre',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "L'assassin",
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Dis-leur 2 ma part',
    artist: 'Sinik',
    album: 'La main sur le coeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-10-18',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },

  // Album : Sang froid (2006)
  {
    title: 'Dans le vif',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Autodestruction',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Sarkozik',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Descente aux enfers',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Un monde meilleur',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Mon pire ennemi',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Ne dis jamais',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Précieuse',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: "Rien n'a changé",
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Bonhomme',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Il faut toujours un drame',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'La cité des anges',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Si proche des miens',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Démence',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Zone interdite',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Mon pire ennemi (Remix)',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
  {
    title: 'Le mot de la fin',
    artist: 'Sinik',
    album: 'Sang froid',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-12-11',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 0,
  },
];

