import { Music } from '../../../../models/music-model';

export const musicsHippocampeFou: Music[] = [
  // Album : Aquatrip (2015) - Hippocampe Fou
  {
    title: 'Aquatrip',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le Dindon',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le Marchand de sable',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'H&M',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 187,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Papa au foyer',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Hymne au cinéma',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le condor et la taupe',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Qui aime bien, châtie bien',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Retroman',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Nul en sport',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Crise de nerfs optiques',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "J'sais pas rouler",
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Aquabadtrip',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Jour de fête',
    artist: 'Hippocampe Fou',
    album: 'Aquatrip',
    coverUrl: '/musics_pictures/Aquatrip.jpg',
    releaseDate: '2015-10-09',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Céleste (2017) - Hippocampe Fou
  {
    title: 'Las Estrellas',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mes échecs',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Obélix',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Si j'étais",
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Pubis ennemi',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Presque rien',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 74,
  },
  {
    title: 'La grande évasion',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Dream',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Chasse aux sorcières',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Chorale des orphelins à la langue coupée',
    artist: 'Hippocampe Fou',
    album: 'Céleste',
    coverUrl: '/musics_pictures/Celeste.jpg',
    releaseDate: '2017-11-03',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Terminus (2019) - Hippocampe Fou
  {
    title: 'Trou',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 183,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Du bout des doigts',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Dans le fond',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Triste',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Fallait pas rigoler',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 41,
  },
  {
    title: 'Lent',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Dormez-vous',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 32,
  },
  {
    title: 'Pas le temps',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mes voisins',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 31,
  },
  {
    title: 'Underground',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 188,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le mal du pays',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 67,
  },
  {
    title: 'Langue paternelle',
    artist: 'Hippocampe Fou',
    album: 'Terminus',
    coverUrl: '/musics_pictures/Terminus.jpg',
    releaseDate: '2019-09-13',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },

  // Album : Pas pour les jeunes (2021) - Hippocampe Fou
  {
    title: 'Pas pour les jeunes',
    artist: 'Hippocampe Fou',
    album: 'Pas pour les jeunes',
    coverUrl: '/musics_pictures/ab67616d0000b2733961dec7f2a2e581eded748d.jpg',
    releaseDate: '2021-06-04',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La thune de ma femme',
    artist: 'Hippocampe Fou',
    album: 'Pas pour les jeunes',
    coverUrl: '/musics_pictures/ab67616d0000b2733961dec7f2a2e581eded748d.jpg',
    releaseDate: '2021-06-04',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Swipe right',
    artist: 'Hippocampe Fou',
    album: 'Pas pour les jeunes',
    coverUrl: '/musics_pictures/ab67616d0000b2733961dec7f2a2e581eded748d.jpg',
    releaseDate: '2021-06-04',
    rating: 0,
    duration: 187,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Wiki freestyle',
    artist: 'Hippocampe Fou',
    album: 'Pas pour les jeunes',
    coverUrl: '/musics_pictures/ab67616d0000b2733961dec7f2a2e581eded748d.jpg',
    releaseDate: '2021-06-04',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tiens-moi la main',
    artist: 'Hippocampe Fou',
    album: 'Pas pour les jeunes',
    coverUrl: '/musics_pictures/ab67616d0000b2733961dec7f2a2e581eded748d.jpg',
    releaseDate: '2021-06-04',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : Présent (2023) - Hippocampe Fou
  {
    title: 'Demi-vieux',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: "J'ai fini le taf",
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Un peu de magie',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Berceuse',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'DJ PS',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Pool',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 187,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Sieste',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tapalaref',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Tout seul',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Écho (Élodie)',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'On a beau dire',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },
  {
    title: "L'éternité (Papa)",
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Respire',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Au revoir',
    artist: 'Hippocampe Fou',
    album: 'Présent',
    coverUrl: '/musics_pictures/HIPPOCAMPEFOU-PRESENT-Cover_3000x.webp',
    releaseDate: '2023-11-17',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },

  // Autres sorties
  {
    title: 'Sieste',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Berceuse',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Dream',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Aquatrip',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Pool',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Un peu de magie',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Underground',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Dans le fond',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Du bout des doigts',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Pubis ennemi',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Lent',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Obélix',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Chorale des orphelins à la langue coupée',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'écho (élodie)',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Trou',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Triste',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Le dindon',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Pas le temps',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Retroman',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Pas Pour Les Jeunes',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Le marchand de sable',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Arbuste généalogique',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Mes échecs',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Las Estrellas',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Au nom du Père... Noël',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Nul en sport',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Cligne des yeux',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Papa Au Foyer',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'H&M',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Qui aime bien, châtie bien',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Pool',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Underground',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Pas Pour Les Jeunes',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Arbuste généalogique',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Tiens-moi la main',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Crise de nerfs optiques',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Aurore boréale',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'La calvitie',
    artist: 'Hippocampe Fou',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
