import { Music } from '../../../../models/music-model';

export const musicsKik: Music[] = [
  // Album : Puzzle (2019)
  {
    title: 'Intro (Puzzle)',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 41,
  },
  {
    title: 'Démonté (feat. De La Hoz)',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Algie',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: '4 millions',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 38,
  },
  {
    title: 'Par habitude',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Ikigai',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: "Quand j'étais petit",
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Adieu',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'SOS',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: "T'es la meilleure",
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bandana Mauve',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 39,
  },
  {
    title: 'Dernier texto',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Megazord (feat. P.Prod)',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: '1000 façons',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Très loin',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Tous les jours',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'La Paix',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Oui',
    artist: 'Kik',
    album: 'Puzzle',
    coverUrl: '/musics_pictures/91L5dGZFFlL.jpg',
    releaseDate: '2019-06-14',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },

  // Album : Rubi (2022)
  {
    title: "L'histoire commence comme ça",
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Rubi (feat. Rubi)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Encore une',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'rap_machinev2.1.exe',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Ma tess',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Tout ira bien (feat. Soprano)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Nul au foot',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Interlude : 5 étoiles',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 120,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Poudre dodo (feat. Rubi)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: "Interlude : l'enveloppe verte",
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 120,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Lettre a mon ex',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Pachémwa (feat. Bigflo & Oli)',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 29,
  },
  {
    title: 'Jamais content',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Ça va ?',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Au fond du miroir',
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: "L'anniversaire de Julie (feat. Rubi)",
    artist: 'Kik',
    album: 'Rubi',
    coverUrl: '/musics_pictures/Rubi-Edition-Limitee.jpg',
    releaseDate: '2022-04-08',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Elle sait',
    artist: 'KIK',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 21,
  },
  {
    title: 'BlaBla',
    artist: 'KIK',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },

  // Singles et autres sorties
  {
    title: 'Challenge incroyable',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Quoi de neuf?',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Rose',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'À ma place',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Plage 80',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Rayon de soleil',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Mort de rire',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Rêve encore',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Bang Bang',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Toujours en retard',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Christophe (Remix Orelsan)',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'La dernière fois que je parle de toi',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Les nouveaux Hippies, Pt. 1',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Fuegolando (Kikesa Remix)',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Bisou',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Brothers (Remix Rilès)',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'La marelle',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Nouveaux Hippies, Pt. 3',
    artist: 'Kik',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
