import { Music } from '../../../../models/music-model';

export const musicsZippo: Music[] = [
  // Album : Zippo contre les robots (2023)
  {
    title: 'Noeud de cravate',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 194,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Le meilleur des mondes',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 222,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Google',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 133,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: "L'homme a la tete creuse",
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 40,
  },
  {
    title: 'Greenwashing',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Charlie',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: "Palme d'or",
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 40,
  },
  {
    title: 'La mer monte',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Hemorragie',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Cap 3000',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 160,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Le dernier cri',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 141,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'In girum imus nocte',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 154,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'i-monde',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 396,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'In mars we trust',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 284,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Etincelle',
    artist: 'Zippo',
    album: 'Zippo contre les robots',
    coverUrl: '/musics_pictures/a3226378720_16.jpg',
    releaseDate: '2018-03-09',
    rating: 0,
    duration: 249,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },

  // Autres sorties
  {
    title: 'James Webb',
    artist: 'Zippo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Chiens sauvages',
    artist: 'Zippo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Echo',
    artist: 'Zippo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Pouces rouges',
    artist: 'Zippo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Lego',
    artist: 'Zippo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'JDD',
    artist: 'Zippo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
