import { Music } from '../../../../models/music-model';

export const musicsBigfloOli: Music[] = [
  // Album : Le Trac (2014) - Bigflo & Oli
  {
    title: 'Atlantis',
    artist: 'Bigflo & Oli',
    album: 'Le Trac',
    coverUrl: '/musics_pictures/81OQpOe+wiL._UF894,1000_QL80_.jpg',
    releaseDate: '2014-07-14',
    rating: 0,
    duration: 284,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Gangsta',
    artist: 'Bigflo & Oli',
    album: 'Le Trac',
    coverUrl: '/musics_pictures/81OQpOe+wiL._UF894,1000_QL80_.jpg',
    releaseDate: '2014-07-14',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Quand même',
    artist: 'Bigflo & Oli',
    album: 'Le Trac',
    coverUrl: '/musics_pictures/81OQpOe+wiL._UF894,1000_QL80_.jpg',
    releaseDate: '2014-07-14',
    rating: 0,
    duration: 216,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Jeunesse influençable',
    artist: 'Bigflo & Oli',
    album: 'Le Trac',
    coverUrl: '/musics_pictures/81OQpOe+wiL._UF894,1000_QL80_.jpg',
    releaseDate: '2014-07-14',
    rating: 0,
    duration: 301,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Monsieur tout le monde',
    artist: 'Bigflo & Oli',
    album: 'Le Trac',
    coverUrl: '/musics_pictures/81OQpOe+wiL._UF894,1000_QL80_.jpg',
    releaseDate: '2014-07-14',
    rating: 0,
    duration: 276,
    genre: 'Rap/Hip-Hop',
    timesListened: 17,
  },

  // Album : La Cour des grands (2015) - Bigflo & Oli
  {
    title: 'La cour des grands',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: "C'est qui ces deux-là ?",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Comme d'hab",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Le bouchon',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 26,
  },
  {
    title: 'Marco',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: "J'attends la vague (solo Bigflo)",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Raccroche',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Le cordon',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: "Aujourd'hui",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ça coûte rien',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Le bijoutier',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Nous aussi',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 206,
    genre: 'Rap/Hip-Hop',
    timesListened: 55,
  },
  {
    title: 'Nik ta mère',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Le philosophe sans la barbe (solo Oli)',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: 'Miroir',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: "C'est pas du rap…",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mytho',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'À mon retour',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 33,
  },
  {
    title: "Début d'empire",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Demain c'est nous",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La tempête',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: "Du disque dur au disque d'or",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "C'est que le début",
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Pourquoi pas nous ?',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Héritage',
    artist: 'Bigflo & Oli',
    album: 'La Cour des grands',
    coverUrl: '/musics_pictures/81jmfo73xAL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-06-01',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },

  // Album : La Vraie Vie (2017) - Bigflo & Oli
  {
    title: 'La vraie vie',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 29,
  },
  {
    title: 'Alors alors',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 187,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: 'Personne',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'Sal*pe !',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Trop tard',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Papa',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 33,
  },
  {
    title: 'Répondez-moi',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Olivio (solo Oli)',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'La vie normale',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 54,
  },
  {
    title: 'Autre part',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Dommage',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'Ça va trop vite',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 31,
  },
  {
    title: 'Sac à dos',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 31,
  },
  {
    title: 'Dans mon lit',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Je suis',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Toulouse',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 216,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Cigarette',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Dites rien à ma mère',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Pour un pote',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Shape of You (de Berywam)',
    artist: 'Bigflo & Oli',
    album: 'La Vraie Vie',
    coverUrl: '/musics_pictures/La-vraie-vie.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },

  // Album : La Vie de rêve (2020) - Bigflo & Oli
  {
    title: 'Nous aussi 2',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 55,
  },
  {
    title: 'Plus tard',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 39,
  },
  {
    title: 'Demain',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'Rentrez chez vous',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 187,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'Bienvenue chez moi',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 206,
    genre: 'Rap/Hip-Hop',
    timesListened: 64,
  },
  {
    title: 'Maman',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 57,
  },
  {
    title: 'La seule',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 36,
  },
  {
    title: 'Florian',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Ferme les yeux',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'Rendez-vous là-haut',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Sur la lune',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 45,
  },
  {
    title: "C'est que du rap",
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Château de sable',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 204,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Il est où ton frère ?',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'La vie de rêve',
    artist: 'Bigflo & Oli',
    album: 'La Vie de rêve',
    coverUrl: '/musics_pictures/La-vie-de-reve.jpg',
    releaseDate: '2020-03-06',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 34,
  },

  // Album : Les autres c'est nous (2022) - Bigflo & Oli
  {
    title: "La vie d'après",
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "J'étais pas là",
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bons élèves',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 33,
  },
  {
    title: 'Booba',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Tant pis ou tant mieux',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 32,
  },
  {
    title: 'Trust Myself',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Super-héros',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Fan',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Coup de vieux',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 41,
  },
  {
    title: 'Lili',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Une belle chanson',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Ça va beaucoup trop vite',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'José et Amar',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Le son préféré de mes potes',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 56,
  },
  {
    title: 'Sacré bordel',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 197,
    genre: 'Rap/Hip-Hop',
    timesListened: 42,
  },
  {
    title: 'Trèfle',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'La familia',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Copier / Coller',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Les gens tristes',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 209,
    genre: 'Rap/Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Dernière',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Sans transition',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Stade',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 51,
  },
  {
    title: 'Promesses',
    artist: 'Bigflo & Oli',
    album: "Les autres c'est nous",
    coverUrl: '/musics_pictures/Les-autres-c-est-nous.jpg',
    releaseDate: '2022-06-24',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
];
