import { Music } from '../../../../models/music-model';

export const musicsNekfeu: Music[] = [
  // Album : Feu (2015) - Nekfeu
  {
    title: 'Martin Eden',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 295,
    genre: 'Rap/Hip-Hop',
    timesListened: 67,
  },
  {
    title: 'Mon âme',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 267,
    genre: 'Rap/Hip-Hop',
    timesListened: 91,
  },
  {
    title: 'Le horla',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 46,
  },
  {
    title: 'Nique les clones, Pt. II',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 66,
  },
  {
    title: "Rêve d'avoir des rêves",
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 296,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tempête',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 59,
  },
  {
    title: 'Égérie',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 210,
    genre: 'Rap/Hip-Hop',
    timesListened: 56,
  },
  {
    title: 'Reuf',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 327,
    genre: 'Rap/Hip-Hop',
    timesListened: 52,
  },
  {
    title: 'La moue des morts',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 272,
    genre: 'Rap/Hip-Hop',
    timesListened: 37,
  },
  {
    title: 'Laisse aller',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 273,
    genre: 'Rap/Hip-Hop',
    timesListened: 69,
  },
  {
    title: 'On verra',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 54,
  },
  {
    title: 'Ma dope',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 227,
    genre: 'Rap/Hip-Hop',
    timesListened: 52,
  },
  {
    title: "Jeux d'ombres",
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 229,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Elle en avait envie',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 62,
  },
  {
    title: 'Princesse',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 265,
    genre: 'Rap/Hip-Hop',
    timesListened: 51,
  },
  {
    title: 'Risibles amours/Des astres',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 526,
    genre: 'Rap/Hip-Hop',
    timesListened: 76,
  },
  {
    title: "Point d'interrogation",
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Être humain',
    artist: 'Nekfeu',
    album: 'Feu',
    coverUrl: '/musics_pictures/Feu.jpg',
    releaseDate: '2015-06-08',
    rating: 0,
    duration: 290,
    genre: 'Rap/Hip-Hop',
    timesListened: 49,
  },

  // Album : Cyborg (2016) - Nekfeu
  {
    title: 'Humanoïde',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 386,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mauvaise graine',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 69,
  },
  {
    title: 'Squa',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 242,
    genre: 'Rap/Hip-Hop',
    timesListened: 62,
  },
  {
    title: 'Réalité augmentée',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 44,
  },
  {
    title: 'Avant tu riais',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 306,
    genre: 'Rap/Hip-Hop',
    timesListened: 42,
  },
  {
    title: 'Esquimaux',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 204,
    genre: 'Rap/Hip-Hop',
    timesListened: 32,
  },
  {
    title: 'O.D',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 242,
    genre: 'Rap/Hip-Hop',
    timesListened: 56,
  },
  {
    title: 'Vinyle',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 292,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Saturne',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 363,
    genre: 'Rap/Hip-Hop',
    timesListened: 39,
  },
  {
    title: 'Galatée',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 47,
  },
  {
    title: 'Le regard des gens',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 210,
    genre: 'Rap/Hip-Hop',
    timesListened: 29,
  },
  {
    title: 'Programmé',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 219,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Besoin de sens',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 230,
    genre: 'Rap/Hip-Hop',
    timesListened: 33,
  },
  {
    title: 'Nekketsu',
    artist: 'Nekfeu',
    album: 'Cyborg',
    coverUrl: '/musics_pictures/Cyborg-Edition-Numerotee.jpg',
    releaseDate: '2016-12-02',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
];
