import { Music } from '../../../../models/music-model';

export const musicsDisiz3: Music[] = [
  // Album : Rap Machine (2015) - Disiz
  {
    title: 'Basic Instinct',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 200,
  },
  {
    title: 'Comme un rappeur (Wa ever)',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 180,
  },
  {
    title: 'Oto Moto',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Abuzeur',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 210,
    genre: 'Rap/Hip-Hop',
    timesListened: 180,
  },
  {
    title: 'En réunion',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Arrête la voiture / Elle attend son fils',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 120,
  },
  {
    title: "Un jour j'ai fait un tag",
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Bitchiz',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Bonnie sans Clyde',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 120,
  },
  {
    title: 'Souveraine',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 180,
  },
  {
    title: 'La promesse',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 130,
  },
  {
    title: 'Chaque week-end',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Les 10 Commandements du MC',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Bête de bombe 6',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 130,
  },
  {
    title: 'Heureusement',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 193,
    genre: 'Rap/Hip-Hop',
    timesListened: 130,
  },
  {
    title: "On s'comprend pas",
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Year of the Dragon (Bonus Track)',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Malcolm (Bonus Track)',
    artist: 'Disiz',
    album: 'Rap Machine',
    coverUrl: '/musics_pictures/719h+43ACqL._UF894,1000_QL80_.jpg',
    releaseDate: '2015-09-25',
    rating: 0,
    duration: 211,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Pacifique (2017) - Disiz
  {
    title: 'Radeau',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 205,
    genre: 'Rap/Pop',
    timesListened: 1,
  },
  {
    title: 'Passage secret (Soma)',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 198,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: 'La fille de la piscine',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 212,
    genre: 'Rap/Pop',
    timesListened: 4,
  },
  {
    title: 'Carré bleu',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 203,
    genre: 'Rap/Pop',
    timesListened: 1,
  },
  {
    title: 'À petit feu',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 218,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: 'Menteur menteuse',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 207,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: 'Marquises',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 215,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: 'Compliqué',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 201,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: 'Meulé meulé / Aighttt',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 223,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: 'Watcha',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 195,
    genre: 'Rap/Pop',
    timesListened: 1,
  },
  {
    title: 'L.U.T.T.E',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 210,
    genre: 'Rap/Pop',
    timesListened: 3,
  },
  {
    title: 'Quand je serai chaos',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 208,
    genre: 'Rap/Pop',
    timesListened: 1,
  },
  {
    title: 'Vibe',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 192,
    genre: 'Rap/Pop',
    timesListened: 1,
  },
  {
    title: 'ADN',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 217,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: 'Poisson étrange',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 204,
    genre: 'Rap/Pop',
    timesListened: 2,
  },
  {
    title: "Qu'ils ont de la chance",
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 199,
    genre: 'Rap/Pop',
    timesListened: 1,
  },
  {
    title: 'Autre espèce',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 207,
    genre: 'Rap/Pop',
    timesListened: 7,
  },
  {
    title: 'Ça va aller (secret RMX)',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 211,
    genre: 'Rap/Pop',
    timesListened: 1,
  },
  {
    title: 'Auto-Dance',
    artist: 'Disiz',
    album: 'Pacifique',
    coverUrl: '/musics_pictures/Pacific-Digisleeve-Edition-limitee.jpg',
    releaseDate: '2017-06-23',
    rating: 0,
    duration: 218,
    genre: 'Rap/Pop',
    timesListened: 3,
  },

  // Album : Disizilla (2018) - Disiz
  {
    title: 'Kaïju',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Disizilla',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Hendek',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Mahboul',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Terre promise',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Hiroshima',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Enfant des rues',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'N*Q**R la fac',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 195,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: "Fuck l'époque",
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Dialogue entre monstres',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Monstrueuse',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Owi',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 189,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Cercle rouge',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Mastodonte',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Tout partira',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Ulysse',
    artist: 'Disiz',
    album: 'Disizilla',
    coverUrl: '/musics_pictures/Disizilla.jpg',
    releaseDate: '2018-09-21',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },

  // Autres sorties
  {
    title: 'POIDS LOURD',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Transe-lucide',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Splash',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'CASINO',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'RENCONTRE',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
];
