import { Music } from '../../../../models/music-model';

export const musicsKamini: Music[] = [
  // Album : Psychostar World (2007) - Kamini
  {
    title: 'Marly-Gomont',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 309,
    genre: 'Rap/Hip-Hop',
    timesListened: 32,
  },
  {
    title: "Un P'tit Coup de Motherfuck",
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 141,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Psychostar Show',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Chevalier',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 173,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Frustration',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Bien Gamin',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 175,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: "J'suis Blanc",
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Psychostar World',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 266,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Schizophrène',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Faisons Quéquette',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 196,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Le Déni',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 202,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Petits Patelins',
    artist: 'Kamini',
    album: 'Psychostar World',
    coverUrl: '/musics_pictures/Psychostar-world.jpg',
    releaseDate: '2007-03-12',
    rating: 0,
    duration: 305,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },

  // Album : Extraterrien (2015) - Kamini
  {
    title: 'Les Raps',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: "Parce qu'on est Con",
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'La Bagarre',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 194,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'En ce moment même',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 333,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Y'a l'Aziz",
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 247,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Ça c'est Showbizz",
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Faut que ça Fuck',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 204,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'La Maladie des Hommes',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 249,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Interlude',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 45,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Les Gens',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 221,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Night Club System',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 278,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Ovni',
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: "Ce que j'aurais aimé être",
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Son de l'Campagne dans ta Gueule",
    artist: 'Kamini',
    album: 'Extraterrien',
    coverUrl: '/musics_pictures/Extraterrien.jpg',
    releaseDate: '2015-11-09',
    rating: 0,
    duration: 251,
    genre: 'Rap/Hip-Hop',
    timesListened: 0,
  },
];
