import { Music } from '../../../../models/music-model';

export const musicsIAM: Music[] = [
  {
    title: 'Independenza',
    artist: 'IAM',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
  // Album : L'École du micro d'argent (1997) - IAM
  {
    title: "L'École du micro d'argent",
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 232,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Dangereux',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 226,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Nés sous la même étoile',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 230,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'La Saga',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 242,
    genre: 'Rap/Hip-Hop',
    timesListened: 60,
  },
  {
    title: 'Petit frère',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 284,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: 'Elle donne son corps avant son nom',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 252,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: "L'Empire du côté obscur",
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 267,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Regarde',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 237,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: "L'Enfer",
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 292,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Quand tu allais, on revenait',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 288,
    genre: 'Rap/Hip-Hop',
    timesListened: 50,
  },
  {
    title: 'Chez le mac',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 282,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },
  {
    title: 'Un bon son brut pour les truands',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 230,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Bouger la tête',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 283,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Un cri court dans la nuit',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 232,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Libère mon imagination',
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 320,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Demain, c'est loin",
    artist: 'IAM',
    album: "L'École du micro d'argent",
    coverUrl: '/musics_pictures/71w0l+-FboL._UF894,1000_QL80_.jpg',
    releaseDate: '1997-03-18',
    rating: 0,
    duration: 540,
    genre: 'Rap/Hip-Hop',
    timesListened: 100,
  },

  // Album : Arts Martiens (2013) - IAM
  {
    title: 'Spartiate Spirit',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 262,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Les raisons de la colère',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 240,
    genre: 'Rap/Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Tous les saints de la terre',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 212,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'La part du démon',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Benkei et Minamoto',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 260,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: '4.2.1',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 245,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Marvel',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 275,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Misère',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 244,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: "L'Amour qu'on me donne",
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Habitude',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 251,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Mon encre, si amère',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Debout les braves',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 261,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Après la fête...',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 220,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Pain au chocolat',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 224,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Sombres manœuvres / Manœuvres sombres',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 404,
    genre: 'Rap/Hip-Hop',
    timesListened: 80,
  },
  {
    title: 'Notre dame veille',
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 179,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: "Dernier coup d'éclat",
    artist: 'IAM',
    album: 'Arts Martiens',
    coverUrl: '/musics_pictures/81uPTJLRhxL._UF894,1000_QL80_.jpg',
    releaseDate: '2013-04-22',
    rating: 0,
    duration: 322,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },

  // Album : Yasuke (2024) - IAM
  {
    title: 'Omotesando',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Yasuke',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 178,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Mosaïque',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Self Made Men',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 270,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Les choses, telles qu'elles paraissent",
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 243,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'On va tous les zinguer',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Eldorado',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 222,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Le train de l'argent",
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 317,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Qui est ?',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 242,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Remember',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 231,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Rap Warrior',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 302,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Good Morning Song',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 239,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Fin des illusions',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 437,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Quand est-ce qu'on s'aime",
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 230,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'MC, tu perds ton sang froid',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 213,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Once Upon a Time',
    artist: 'IAM',
    album: 'Yasuke',
    coverUrl: '/musics_pictures/81YxZBLGcBL.jpg',
    releaseDate: '2024-10-25',
    rating: 0,
    duration: 308,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Autres sorties

  {
    title: 'La fin de leur monde',
    artist: 'IAM',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
