import { Music } from '../../../../models/music-model';

export const musicsFatalBazooka: Music[] = [
  {
    title:
      'Ce matin va être une pure soirée (feat. Big Ali, PZK, Dogg SoSo, Chris Prolls)',
    artist: 'Fatal Bazooka',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 31,
  },
  {
    title: 'Stach Stach',
    artist: 'Bratisla Boys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 30,
  },
  // Album : T'as vu ? (2007) - Fatal Bazooka
  {
    title: "T'as vu ?",
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Fous ta cagoule',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 20,
  },
  {
    title: 'Viens bégère',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: "J'aime trop ton boule",
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'MC Chamallow',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Viva Bazooka',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Saturday Night Kebab',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Ouais ma gueule',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Ego trip',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'MC Introverti',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Mauvaise foi nocturne',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 14,
  },
  {
    title: 'Sale connasse',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Chienne de vie',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: "C'est une pute !",
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Auto-clash',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 3,
  },
  {
    title: 'MC Québec City',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Parle à ma main',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Trankillement',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 3,
  },
  {
    title: 'Crêpes au froment',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Trankillement (Remix)',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Parle à ma main (Remix)',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
  {
    title: 'Bouge !',
    artist: 'Fatal Bazooka',
    album: "T'as vu ?",
    coverUrl: '/musics_pictures/T-as-vu-Inclus-DVD-bonus.jpg',
    releaseDate: '2007-03-19',
    rating: 0,
    duration: 180,
    genre: 'Rap Parodique',
    timesListened: 0,
  },
];
