import { Music } from '../../../../models/music-model';

export const musicsDisiz2: Music[] = [
  // Album : Disiz the End (2009) - Disiz La Peste
  {
    title: 'La fin du début (intro)',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 268,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Alors tu veux rapper ? / Flowmatic',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 410,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Bête de bombe 4',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 164,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: "C'est la vérité",
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 188,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Quand le peuple va se lever',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 262,
    genre: 'Rap/Hip-Hop',
    timesListened: 34,
  },
  {
    title: 'Odyssée',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 352,
    genre: 'Rap/Hip-Hop',
    timesListened: 34,
  },
  {
    title: "...Derrière l'arbre (interlude)",
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 50,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'L.O.V.E.',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 300,
    genre: 'Rap/Hip-Hop',
    timesListened: 40,
  },
  {
    title: 'Papa lova',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 258,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Le temps précieux',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 314,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: '27 octobre',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 288,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Il est déjà trop tard',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 276,
    genre: 'Rap/Hip-Hop',
    timesListened: 22,
  },
  {
    title: "J'ai changé",
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 270,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Le monde sur mesure',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 214,
    genre: 'Rap/Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'Disiz the end.',
    artist: 'Disiz La Peste',
    album: 'Disiz the End',
    coverUrl: '/musics_pictures/Disiz-the-end.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },

  // Album : Dans le Ventre du Crocodile (2010) - Disiz Peter Punk
  {
    title: 'Mutation (Intro)',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 125,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Dans le ventre du crocodile',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 207,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Rien comme les autres',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 217,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Yeah Yeah Yeah',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 228,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: "Je t'aime mais je te quitte",
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 185,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Jolies planètes',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 182,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Faire la mer',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 209,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Trans-Mauritania',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 244,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Problème XXX',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 129,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Les monstres',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 255,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Paradoxe',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 220,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'La luciole',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 238,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  {
    title: 'Les équilibristes (Bonus Track)',
    artist: 'Disiz Peter Punk',
    album: 'Dans le Ventre du Crocodile',
    coverUrl: '/musics_pictures/Dans-le-ventre-du-crocodile.jpg',
    releaseDate: '2010-05-11',
    rating: 0,
    duration: 165,
    genre: 'Rap Rock',
    timesListened: 1,
  },
  // Album : Lucide (2012) - Disiz
  {
    title: 'Toussa Toussa',
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 210,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Moïse',
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 205,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "J'ai la haine",
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 198,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Mon amour',
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 215,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Un frigo un cœur et des couilles',
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 192,
    genre: 'Rap/Hip-Hop',
    timesListened: 28,
  },
  {
    title: 'Bête de bombe 5',
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 203,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Gagne pain',
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Validé',
    artist: 'Disiz',
    album: 'Lucide',
    coverUrl:
      '/musics_pictures/image_2721041_20241116_ob_90d4cd_disiz-lucide-logo.png',
    releaseDate: '2012-02-20',
    rating: 0,
    duration: 225,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },

  // Album : Extra-Lucide (2012) - Disiz
  {
    title: 'Coda vide',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 36,
    genre: 'Rap/Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Combien de temps ?',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 207,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: 'Everything',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 217,
    genre: 'Rap/Hip-Hop',
    timesListened: 35,
  },
  {
    title: 'Best day',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 218,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: "Pour l'homme",
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 277,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Extra-lucide',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 296,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: 'Tu brilles',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 204,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Toussa toussa (Remix)',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 178,
    genre: 'Rap/Hip-Hop',
    timesListened: 15,
  },
  {
    title: 'Go Go Gadget',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 249,
    genre: 'Rap/Hip-Hop',
    timesListened: 52,
  },
  {
    title: 'Porte disparue',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 357,
    genre: 'Rap/Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Actarus',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 117,
    genre: 'Rap/Hip-Hop',
    timesListened: 24,
  },
  {
    title: 'Je les garde',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 273,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Les bienveillants',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 254,
    genre: 'Rap/Hip-Hop',
    timesListened: 33,
  },
  {
    title: "C'est ma tournée",
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 250,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Fête foraine',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 269,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: "Salauds d'pauvres",
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 257,
    genre: 'Rap/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Les moyens du bord',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 275,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Fukushima',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 308,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Life is good',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 46,
  },
  {
    title: 'Polyuréthane (Plastic life)',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 234,
    genre: 'Rap/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Bullshitter',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Coeur Gangster',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Prélude A La Rébellion Des Coeurs',
    artist: 'Disiz',
    album: 'Extra-Lucide',
    coverUrl: '/musics_pictures/Extra-lucide.jpg',
    releaseDate: '2012-11-05',
    rating: 0,
    duration: 201,
    genre: 'Rap/Hip-Hop',
    timesListened: 16,
  },

  // Album : Transe-Lucide (2014) - Disiz
  {
    title: 'Terre (Intro)',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 48,
    genre: 'Rap/Hip-Hop',
    timesListened: 6,
  },
  {
    title: 'Banlieusard Syndrome',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 146,
    genre: 'Rap/Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Miskine',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 222,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Kamikaze',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 237,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Rap Genius',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 451,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Fuck Les Problèmes',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 223,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'MC Kissinger',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 134,
    genre: 'Rap/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Spirales',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 266,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Burn Out (Sayonara)',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 208,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Eau (Interlude)',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 20,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'King of Cool',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 251,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Kadija',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 263,
    genre: 'Rap/Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Echo',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 257,
    genre: 'Rap/Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Ciel (Interlude)',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 22,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Luv (Prends Le Risque)',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 210,
    genre: 'Rap/Hip-Hop',
    timesListened: 19,
  },
  {
    title: 'Complexité Française',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 368,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Happy End',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 298,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Lotus',
    artist: 'Disiz',
    album: 'Transe-Lucide',
    coverUrl: '/musics_pictures/disiz-transe-lucide-cover_0_5.jpg',
    releaseDate: '2014-09-29',
    rating: 0,
    duration: 277,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },

  // Autres sorties
  {
    title: 'Mahboul',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Disizilla',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Kaïju',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Mastodonte',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Splash',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Terre promise',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Autre espèce',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Hendek',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'POIDS LOURD',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'CASINO',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'RENCONTRE',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Transe-lucide',
    artist: 'Disiz',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
