import { Music } from '../../../../models/music-model';

export const musicsDace: Music[] = [
  // Album : Inévitable (2020)
  {
    title: 'Inévitable',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Musique Hip Hop',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Rêve',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Payer Comptant',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'PTR',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 6,
  },
  {
    title: "J'ai la flemme",
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Le temps ne nous appartient pas',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Mangas 2',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 20,
  },
  {
    title: 'Petite sœur',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 5,
  },
  {
    title: 'Zouzou',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Et si',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'LTQT - La tête qui tourne',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Pardonne-moi',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Commercial',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Viking',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'Le sang',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },
  {
    title: 'La concurrence',
    artist: 'D.ACE',
    album: 'Inévitable',
    coverUrl: '/musics_pictures/Inevitable.jpg',
    releaseDate: '2020-06-12',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 1,
  },

  // Autres sorties
  {
    title: 'Mangas',
    artist: 'D.ACE',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap français',
    timesListened: 40,
  },
];
