import { Movie } from '../../../models/movie-model';

export const williamMovies: Movie[] = [
  {
    title: 'Cars',
    director: 'John Lasseter',
    actors: [{ name: 'Owen Wilson' }],
    coverUrl:
      '/movies_pictures/dWg33ektXuHmxjSjEulwDPTWbC2-0-150-0-225-crop.jpg',
    releaseDate: '2006-06-09',
    rating: 6,
    length: 117,
    genre: 'Animation',
    timesWatched: 10,
    lastViewedDate: '',
  },
  {
    title: 'Cars 3',
    director: 'Brian Fee',
    actors: [{ name: 'Owen Wilson' }],
    coverUrl: '/movies_pictures/184062-cars-3-0-150-0-225-crop.jpg',
    releaseDate: '2016-06-16',
    rating: 4.5,
    length: 102,
    genre: 'Animation',
    timesWatched: 6,
    lastViewedDate: '',
  },
  {
    title: 'Planes',
    director: 'Klay Hall',
    actors: [{ name: 'Dane Cook' }, { name: 'Stacy Keach' }],
    coverUrl: '/movies_pictures/81RXWeS2Y4L._AC_UF894,1000_QL80_.jpg',
    releaseDate: '2013-08-09',
    rating: 0,
    length: 91,
    genre: 'Animation',
    timesWatched: 2,
    lastViewedDate: '',
  },
  {
    title: 'Planes 2',
    director: 'Roberts Gannaway',
    actors: [{ name: 'Dane Cook' }, { name: 'Ed Harris' }],
    coverUrl: '/movies_pictures/218398.jpg',
    releaseDate: '2014-07-18',
    rating: 0,
    length: 83,
    genre: 'Animation',
    timesWatched: 4,
    lastViewedDate: '',
  },
  {
    title: 'Le monde de Nemo',
    director: 'Andrew Stanton',
    actors: [{ name: 'Albert Brooks' }, { name: 'Ellen DeGeneres' }],
    coverUrl: '/movies_pictures/monde_de_nemo.webp',
    releaseDate: '2003-05-30',
    rating: 4,
    length: 100,
    genre: 'Animation',
    timesWatched: 1,
    lastViewedDate: '',
  },
];
