import { Game } from "./games_1";

export const games2: Game[] = [
  // Naruto Storm
  {
    title: "Naruto: Ultimate Ninja Storm",
    editor: "CyberConnect2",
    hero: "Naruto Uzumaki",
    coverUrl: "/games_pictures/MV5BNzg5OTZhZjUtMmEwOC00ZGI1LTljOTgtNDMzMTA1YjlhNDA2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "2008-11-04",
    rating: 4,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 30,
    platform: "PlayStation 3",
    saga: "Naruto Storm",
  },
  {
    title: "Naruto Shippuden: Ultimate Ninja Storm 2",
    editor: "CyberConnect2",
    hero: "Naruto Uzumaki",
    coverUrl: "/games_pictures/MV5BMWMwMjMyZWYtZTJkOC00MzM0LTg3OGQtZmY3ZTBmNWRjNDhhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "2010-10-19",
    rating: 4,
    averageTimeToFinish: 35,
    timesFinished: 1,
    additionnalEstimatedTime: 30,
    platform: "PlayStation 3",
    saga: "Naruto Storm",
  },
  {
    title: "Naruto Shippuden: Ultimate Ninja Storm 3",
    editor: "CyberConnect2",
    hero: "Naruto Uzumaki",
    coverUrl: "/games_pictures/Naruto_Ultimate_Ninja_Storm_3_Full_Burst_Standard_Edition_Packshot__88947.jpg",
    releaseDate: "2013-03-05",
    rating: 3.75,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 30,
    platform: "PlayStation 3",
    saga: "Naruto Storm",
  },
  {
    title: "Naruto Shippuden: Ultimate Ninja Storm 4",
    editor: "CyberConnect2",
    hero: "Naruto Uzumaki",
    coverUrl: "/games_pictures/1428916387-2799-jaquette-avant.webp",
    releaseDate: "2016-02-09",
    rating: 3.75,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 15,
    platform: "PlayStation 4",
    saga: "Naruto Storm",
  },
  // Infamous
  {
    title: "Infamous",
    editor: "Sucker Punch Productions",
    hero: "Cole MacGrath",
    coverUrl: "/games_pictures/MV5BOGJlNmVkM2EtNjM5Ni00MTFkLTkwOTAtZjU3YTJkNWU1NjI2XkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2009-05-26",
    rating: 4.5,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Infamous",
  },
  {
    title: "Infamous 2",
    editor: "Sucker Punch Productions",
    hero: "Cole MacGrath",
    coverUrl: "/games_pictures/MV5BZTg1NDY1MzUtMGI1Mi00Nzg1LThhOGMtM2RlNTZkODJhNzQwXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2011-06-07",
    rating: 4.25,
    averageTimeToFinish: 25,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Infamous",
  },
  {
    title: "Infamous: Second Son",
    editor: "Sucker Punch Productions",
    hero: "Delsin Rowe",
    coverUrl: "/games_pictures/KXv6VplN1r1bNPdfR4r29w0m.webp",
    releaseDate: "2014-03-21",
    rating: 4.25,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 4",
    saga: "Infamous",
  },
  {
    title: "Infamous: First Light",
    editor: "Sucker Punch Productions",
    hero: "Abigail Walker",
    coverUrl: "/games_pictures/MV5BNWE2MGU3MzYtZjk4Yi00ZGU1LTk5MmMtMWMzY2MxY2IyYjc4XkEyXkFqcGc@._V1_QL75_UX190_CR0,4,190,281_.jpg",
    releaseDate: "2014-08-26",
    rating: 4,
    averageTimeToFinish: 12,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 4",
    saga: "Infamous",
  },
  // Super Smash Bros
  {
    title: "Super Smash Bros. Melee",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/Super_Smash_Bros_Melee_box_art.png",
    releaseDate: "2001-12-03",
    rating: 5,
    averageTimeToFinish: 50,
    timesFinished: 1,
    additionnalEstimatedTime: 300,
    platform: "GameCube",
    saga: "Super Smash Bros",
  },
  {
    title: "Super Smash Bros. Ultimate",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/81QiNb1LIjL._UF1000,1000_QL80_.jpg",
    releaseDate: "2018-12-07",
    rating: 4.5,
    averageTimeToFinish: 100,
    timesFinished: 1,
    additionnalEstimatedTime: 400,
    platform: "Nintendo Switch",
    saga: "Super Smash Bros",
  },
  // LittleBigPlanet
  {
    title: "LittleBigPlanet",
    editor: "Media Molecule",
    hero: "Sackboy",
    coverUrl: "/games_pictures/MV5BNmFiNGYxMTQtMzE5Mi00MDZmLWFiZDgtNDNmMGViNDY1MzMwXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2008-10-27",
    rating: 3.5,
    averageTimeToFinish: 25,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "LittleBigPlanet",
  },
  // Brutal Legend
  {
    title: "Brutal Legend",
    editor: "Double Fine Productions",
    hero: "Eddie Riggs",
    coverUrl: "/games_pictures/BrutalLegendCover.jpg",
    releaseDate: "2009-10-13",
    rating: 3.75,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 10,
    platform: "PlayStation 3",
    saga: "Brutal Legend",
  },
  // Batman Arkham
  {
    title: "Batman: Arkham Asylum",
    editor: "Rocksteady Studios",
    hero: "Batman",
    coverUrl: "/games_pictures/batman-arkham-asylum-i167596.jpg",
    releaseDate: "2009-08-25",
    rating: 3.75,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Batman Arkham",
  },
  // Spider-Man
  {
    title: "The Amazing Spider-Man",
    editor: "Beenox",
    hero: "Spider-Man",
    coverUrl: "/games_pictures/71q1hH3EijL._UF1000,1000_QL80_.jpg",
    releaseDate: "2012-06-26",
    rating: 3.75,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Spider-Man",
  },
  {
    title: "Marvel's Spider-Man",
    editor: "Insomniac Games",
    hero: "Spider-Man",
    coverUrl: "/games_pictures/A28f38dd49ebd424aa41257fd9ae45f9dY.webp",
    releaseDate: "2018-09-07",
    rating: 4.25,
    averageTimeToFinish: 25,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 4",
    saga: "Spider-Man",
  },
  {
    title: "Marvel's Spider-Man: Miles Morales",
    editor: "Insomniac Games",
    hero: "Miles Morales",
    coverUrl: "/games_pictures/PRfYtTZQsuj3ALrBXGL8MjAH.avif",
    releaseDate: "2020-11-12",
    rating: 4,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 5",
    saga: "Spider-Man",
  },
  {
    title: "Marvel's Spider-Man 2",
    editor: "Insomniac Games",
    hero: "Spider-Man",
    coverUrl: "/games_pictures/60eca3ac155247e21850c7d075d01ebf0f3f5dbf19ccd2a1.avif",
    releaseDate: "2023-10-20",
    rating: 4,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 5",
    saga: "Spider-Man",
  },
  // Dead Nation
  {
    title: "Dead Nation",
    editor: "Housemarque",
    hero: "Marco",
    coverUrl: "/games_pictures/1518686841-8541-jaquette-avant.webp",
    releaseDate: "2010-11-30",
    rating: 3,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Dead Nation",
  },
  // BioShock
  {
    title: "BioShock Infinite",
    editor: "Irrational Games",
    hero: "Booker DeWitt",
    coverUrl: "/games_pictures/jaquette-bioshock-infinite-pc-cover-avant-g-1354632827.jpg",
    releaseDate: "2013-03-26",
    rating: 4.5,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "BioShock",
  },
  // Brothers
  {
    title: "Brothers: A Tale of Two Sons",
    editor: "Starbreeze Studios",
    hero: "Naiee & Naia",
    coverUrl: "/games_pictures/Brothers_Port_1200x1600_1200x1600-ee43c7558877b4470f607a0c140ee3d5.jpg",
    releaseDate: "2013-08-28",
    rating: 3.5,
    averageTimeToFinish: 4,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Brothers",
  },
  // Injustice
  {
    title: "Injustice: Gods Among Us Ultimate Edition",
    editor: "NetherRealm Studios",
    hero: "Superman",
    coverUrl: "/games_pictures/Injustice_Gods_Among_Us_cover_art.webp",
    releaseDate: "2013-11-12",
    rating: 3,
    averageTimeToFinish: 8,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Injustice",
  },
  // Mirror's Edge
  {
    title: "Mirror's Edge",
    editor: "DICE",
    hero: "Faith Connors",
    coverUrl: "/games_pictures/Mirror's_Edge.jpg",
    releaseDate: "2008-11-11",
    rating: 4.25,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Mirror's Edge",
  },
  // PlayStation All-Stars
  {
    title: "PlayStation All-Stars Battle Royale",
    editor: "SuperBot Entertainment",
    hero: "Kratos",
    coverUrl: "/games_pictures/71JqJ1aj5fS.jpg",
    releaseDate: "2012-11-20",
    rating: 3,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "PlayStation All-Stars",
  },
  // Stick It to the Man
  {
    title: "Stick It to the Man",
    editor: "Zoink Games",
    hero: "Ray",
    coverUrl: "/games_pictures/s-l1200.jpg",
    releaseDate: "2013-11-19",
    rating: 3.25,
    averageTimeToFinish: 10,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Stick It to the Man",
  },
  // Watch Dogs
  {
    title: "Watch Dogs",
    editor: "Ubisoft",
    hero: "Aiden Pearce",
    coverUrl: "/games_pictures/56c494ae88a7e300458b4d72.jpg",
    releaseDate: "2014-05-27",
    rating: 4.25,
    averageTimeToFinish: 50,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 4",
    saga: "Watch Dogs",
  },
  // Super Meat Boy
  {
    title: "Super Meat Boy",
    editor: "Team Meat",
    hero: "Meat Boy",
    coverUrl: "/games_pictures/cANQICFpF9rI44-medium.webp",
    releaseDate: "2010-10-20",
    rating: 4.5,
    averageTimeToFinish: 15,
    timesFinished: 10,
    additionnalEstimatedTime: 250,
    platform: "PlayStation 4",
    saga: "Super Meat Boy",
  },
  // J-Stars Victory
  {
    title: "J-Stars Victory VS",
    editor: "Spike Chunsoft",
    hero: "Goku",
    coverUrl: "/games_pictures/kl2fcl0fcka71.jpg",
    releaseDate: "2014-03-19",
    rating: 3.5,
    averageTimeToFinish: 40,
    timesFinished: 1,
    additionnalEstimatedTime: 15,
    platform: "PlayStation 3",
    saga: "J-Stars Victory",
  },
  // Dragon Ball
  {
    title: "Dragon Ball Z: Budokai 2",
    editor: "Dimps",
    hero: "Goku",
    coverUrl: "/games_pictures/dbz2p20f.webp",
    releaseDate: "2003-12-04",
    rating: 4,
    averageTimeToFinish: 12,
    timesFinished: 5,
    additionnalEstimatedTime: 30,
    platform: "PlayStation 2",
    saga: "Dragon Ball",
  },
  {
    title: "Dragon Ball Z: Budokai 3",
    editor: "Dimps",
    hero: "Goku",
    coverUrl: "/games_pictures/71QBu0YcCcL.jpg",
    releaseDate: "2004-11-16",
    rating: 3.75,
    averageTimeToFinish: 15,
    timesFinished: 3,
    additionnalEstimatedTime: 30,
    platform: "PlayStation 2",
    saga: "Dragon Ball",
  },
  {
    title: "Dragon Ball Z: Budokai Tenkaichi 2",
    editor: "Spike",
    hero: "Goku",
    coverUrl: "/games_pictures/dragon-ball-z-budokai-tenkaichi-2-i-2-3296580803279_0.jpg",
    releaseDate: "2006-10-03",
    rating: 3.75,
    averageTimeToFinish: 18,
    timesFinished: 1,
    additionnalEstimatedTime: 50,
    platform: "PlayStation 2",
    saga: "Dragon Ball",
  },
  {
    title: "Dragon Ball Z: Dokkan Battle",
    editor: "Bandai Namco",
    hero: "Goku",
    coverUrl: "/games_pictures/Dragon-Ball-Z-Dokkan-Battle.jpg",
    releaseDate: "2015-03-19",
    rating: 4.25,
    averageTimeToFinish: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 1800,
    platform: "Android",
    saga: "Dragon Ball",
  },
  // Ratchet & Clank
  {
    title: "Ratchet & Clank",
    editor: "Insomniac Games",
    hero: "Ratchet",
    coverUrl: "/games_pictures/MV5BYTJlYWY1M2EtMDlkOC00ZmViLTgyYWEtOWRhZWM0MmRkNzRjXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2002-11-04",
    rating: 4,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 2",
    saga: "Ratchet & Clank",
  },
  // South Park
  {
    title: "South Park: Le Bâton de la Vérité",
    editor: "Obsidian Entertainment",
    hero: "Le Nouveau",
    coverUrl: "/games_pictures/southparklebatondelaveritepccover0458778.jpg",
    releaseDate: "2014-03-04",
    rating: 4,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 20,
    platform: "PlayStation 3",
    saga: "South Park",
  },
  // God of War
  {
    title: "God of War",
    editor: "Santa Monica Studio",
    hero: "Kratos",
    coverUrl: "/games_pictures/85407.jpg",
    releaseDate: "2018-04-20",
    rating: 4.5,
    averageTimeToFinish: 45,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 4",
    saga: "God of War",
  },
  {
    title: "God of War Ragnarök",
    editor: "Santa Monica Studio",
    hero: "Kratos",
    coverUrl: "/games_pictures/0711719409397_1.png",
    releaseDate: "2022-11-09",
    rating: 4.25,
    averageTimeToFinish: 40,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 5",
    saga: "God of War",
  },
  // Hogwarts Legacy
  {
    title: "Hogwarts Legacy",
    editor: "Avalanche Software",
    hero: "Élève de Poudlard",
    coverUrl: "/games_pictures/f6b1e4512ee6061913f7d604da8f5f39566be56ca32a68ee.avif",
    releaseDate: "2023-02-10",
    rating: 4.5,
    averageTimeToFinish: 50,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 5",
    saga: "Hogwarts Legacy",
  },
];