import { Game } from "./games_1";

export const games3: Game[] = [
  // Metroid
  {
    title: "Metroid Fusion",
    editor: "Nintendo",
    hero: "Samus Aran",
    coverUrl: "/games_pictures/MV5BMjNhNGQyMjgtODAyZi00YTgzLTk3ZDMtNWFkNjI4MmJiZjdkXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2002-11-17",
    rating: 4.5,
    averageTimeToFinish: 15,
    timesFinished: 10,
    additionnalEstimatedTime: 100,
    platform: "Game Boy Advance",
    saga: "Metroid",
  },
  {
    title: "Metroid: Zero Mission",
    editor: "Nintendo",
    hero: "Samus Aran",
    coverUrl: "/games_pictures/MV5BNGQ1MzY0NjktNGI1Yi00YTc4LWFkMWUtNGM2YmRiZWI4MDZkXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2004-02-09",
    rating: 4,
    averageTimeToFinish: 10,
    timesFinished: 2,
    additionnalEstimatedTime: 0,
    platform: "Game Boy Advance",
    saga: "Metroid",
  },
  {
    title: "Metroid Prime",
    editor: "Retro Studios",
    hero: "Samus Aran",
    coverUrl: "/games_pictures/metroid-prime-wii.jpg",
    releaseDate: "2002-11-17",
    rating: 4,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "GameCube",
    saga: "Metroid",
  },
  {
    title: "Metroid Prime 2: Echoes",
    editor: "Retro Studios",
    hero: "Samus Aran",
    coverUrl: "/games_pictures/mep2gc0f.jpg",
    releaseDate: "2004-11-15",
    rating: 3.5,
    averageTimeToFinish: 25,
    timesFinished: 0,
    additionnalEstimatedTime: 5,
    platform: "GameCube",
    saga: "Metroid",
  },
  {
    title: "Metroid Prime 3: Corruption",
    editor: "Retro Studios",
    hero: "Samus Aran",
    coverUrl: "/games_pictures/Metroidprime3corruption.webp",
    releaseDate: "2007-08-27",
    rating: 4.25,
    averageTimeToFinish: 22,
    timesFinished: 2,
    additionnalEstimatedTime: 20,
    platform: "Wii",
    saga: "Metroid",
  },
  {
    title: "Metroid Dread",
    editor: "MercurySteam",
    hero: "Samus Aran",
    coverUrl: "/games_pictures/81ygZZVdUvS.jpg",
    releaseDate: "2021-10-08",
    rating: 3.75,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Nintendo Switch",
    saga: "Metroid",
  },
  // Super Mario
  {
    title: "Super Mario 64",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/super_mario_64_2.webp",
    releaseDate: "1996-06-23",
    rating: 4,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Nintendo 64",
    saga: "Super Mario",
  },
  {
    title: "Super Mario Galaxy",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/il_570xN.5937744444_j3z5.webp",
    releaseDate: "2007-11-12",
    rating: 3.75,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Wii",
    saga: "Super Mario",
  },
  {
    title: "Super Mario Odyssey",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/81TksYoxfQL._UF1000,1000_QL80_.jpg",
    releaseDate: "2017-10-27",
    rating: 3.25,
    averageTimeToFinish: 40,
    timesFinished: 0,
    additionnalEstimatedTime: 10,
    platform: "Nintendo Switch",
    saga: "Super Mario",
  },

  // Mario Kart
  {
    title: "Mario Kart: Double Dash!!",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/81e0IWNn5eL._UF1000,1000_QL80_.jpg",
    releaseDate: "2003-11-07",
    rating: 4.25,
    averageTimeToFinish: 12,
    timesFinished: 1,
    additionnalEstimatedTime: 200,
    platform: "GameCube",
    saga: "Mario Kart",
  },
  {
    title: "Mario Kart Wii",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/mario-kart-wii-e2671.jpg",
    releaseDate: "2008-04-10",
    rating: 4,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 200,
    platform: "Wii",
    saga: "Mario Kart",
  },
  {
    title: "Mario Kart 8 Deluxe",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/81EdgFXOWWL._UF1000,1000_QL80_.jpg",
    releaseDate: "2017-04-28",
    rating: 3.75,
    averageTimeToFinish: 25,
    timesFinished: 1,
    additionnalEstimatedTime: 80,
    platform: "Nintendo Switch",
    saga: "Mario Kart",
  },
  // Mario Party
  {
    title: "Mario Party 5",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/81byWQum9AL.jpg",
    releaseDate: "2003-11-10",
    rating: 3.75,
    averageTimeToFinish: 12,
    timesFinished: 1,
    additionnalEstimatedTime: 100,
    platform: "GameCube",
    saga: "Mario Party",
  },
  {
    title: "Mario Party 6",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/Mario_Party_6_capa.png",
    releaseDate: "2004-12-06",
    rating: 3.75,
    averageTimeToFinish: 12,
    timesFinished: 1,
    additionnalEstimatedTime: 100,
    platform: "GameCube",
    saga: "Mario Party",
  },
  {
    title: "Mario Party 7",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/Mario_Party_7_Coverart.png",
    releaseDate: "2005-11-07",
    rating: 3.75,
    averageTimeToFinish: 12,
    timesFinished: 1,
    additionnalEstimatedTime: 100,
    platform: "GameCube",
    saga: "Mario Party",
  },
  {
    title: "Mario Party 8",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/91FQxPuzTQL.jpg",
    releaseDate: "2007-05-29",
    rating: 3.5,
    averageTimeToFinish: 10,
    timesFinished: 1,
    additionnalEstimatedTime: 50,
    platform: "Wii",
    saga: "Mario Party",
  },

  {
    title: "Super Mario Party",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/81XdRd9UNZL.jpg",
    releaseDate: "2018-10-05",
    rating: 3.5,
    averageTimeToFinish: 12,
    timesFinished: 1,
    additionnalEstimatedTime: 30,
    platform: "Nintendo Switch",
    saga: "Mario Party",
  },
  // Paper Mario
  {
    title: "Super Paper Mario",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/71GK7PP0tFL.jpg",
    releaseDate: "2007-04-09",
    rating: 4,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Wii",
    saga: "Paper Mario",
  },
  // Mario & Luigi
  {
    title: "Mario & Luigi: Superstar Saga",
    editor: "Nintendo",
    hero: "Mario & Luigi",
    coverUrl: "/games_pictures/MarioAndLuigiSuperstarSagaGBACoverArtUS.jpg",
    releaseDate: "2003-11-17",
    rating: 3,
    averageTimeToFinish: 20,
    timesFinished: 0,
    additionnalEstimatedTime: 5,
    platform: "Game Boy Advance",
    saga: "Mario & Luigi",
  },

  // Need for Speed
  {
    title: "Need for Speed: Most Wanted",
    editor: "Electronic Arts",
    hero: "Pilote",
    coverUrl: "/games_pictures/71-WJMXvaLL._UF1000,1000_QL80_.jpg",
    releaseDate: "2005-11-15",
    rating: 4.25,
    averageTimeToFinish: 30,
    timesFinished: 3,
    additionnalEstimatedTime: 50,
    platform: "PlayStation 2",
    saga: "Need for Speed",
  },
  {
    title: "Need for Speed: Carbon",
    editor: "Electronic Arts",
    hero: "Pilote",
    coverUrl: "/games_pictures/nfs-carbon-psp-e7802 (1).jpg",
    releaseDate: "2006-10-31",
    rating: 3.75,
    averageTimeToFinish: 20,
    timesFinished: 10,
    additionnalEstimatedTime: 50,
    platform: "PlayStation 2",
    saga: "Need for Speed",
  },
  // Yu-Gi-Oh!
  {
    title: "Yu-Gi-Oh! Duel des ténèbres",
    editor: "Konami",
    hero: "Yugi Muto",
    coverUrl: "/games_pictures/yugioh-duel-des-tenebres-e59476.jpg",
    releaseDate: "2002-03-08",
    rating: 3.5,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 20,
    platform: "Game Boy Advance",
    saga: "Yu-Gi-Oh!",
  },
  {
    title: "Yu-Gi-Oh! The Sacred Cards",
    editor: "Konami",
    hero: "Yugi Muto",
    coverUrl: "/games_pictures/91qzoCTEX4L._UF1000,1000_QL80_.jpg",
    releaseDate: "2003-10-28",
    rating: 3,
    averageTimeToFinish: 18,
    timesFinished: 2,
    additionnalEstimatedTime: 20,
    platform: "Game Boy Advance",
    saga: "Yu-Gi-Oh!",
  },
  {
    title: "Yu-Gi-Oh! Reshef of Destruction",
    editor: "Konami",
    hero: "Yugi Muto",
    coverUrl: "/games_pictures/51EQWD3DTRL._UF1000,1000_QL80_.jpg",
    releaseDate: "2004-03-23",
    rating: 3,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Game Boy Advance",
    saga: "Yu-Gi-Oh!",
  },
];
