
export interface Game {
  title: string;
  editor: string;
  hero: string;
  coverUrl: string;
  releaseDate: string;
  rating: number;
  averageTimeToFinish: number;
  timesFinished: number;
  additionnalEstimatedTime: number;
  platform: string;
  saga: string;
}

export const games1: Game[] = [
  // The Legend of Zelda
  {
    title: "The Legend of Zelda: Ocarina of Time",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/oot.jpg",
    releaseDate: "1998-11-21",
    rating: 5,
    averageTimeToFinish: 101,
    timesFinished: 5,
    additionnalEstimatedTime: 0,
    platform: "Nintendo 64",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: The Wind Waker",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/MV5BOWFhZGZmMDctYjFmNC00YzQzLWE5ODktYTBhNmE1MmRiZTM4XkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2002-12-13",
    rating: 5,
    averageTimeToFinish: 95,
    timesFinished: 5,
    additionnalEstimatedTime: 0,
    platform: "GameCube",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: Twilight Princess",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/The_Legend_of_Zelda_Twilight_Princess_Game_Cover.jpg",
    releaseDate: "2006-11-19",
    rating: 4.25,
    averageTimeToFinish: 120,
    timesFinished: 2,
    additionnalEstimatedTime: 0,
    platform: "Wii",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: Skyward Sword",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/MV5BOGMxMDRjMzUtN2FiYS00ZmFlLWJmM2ItY2VhY2RiMDdhNzViXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "2011-11-18",
    rating: 4.5,
    averageTimeToFinish: 110,
    timesFinished: 2,
    additionnalEstimatedTime: 0,
    platform: "Wii",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: Breath of the Wild",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/40519.jpg",
    releaseDate: "2017-03-03",
    rating: 4,
    averageTimeToFinish: 150,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Nintendo Switch",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: A Link to the Past",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/mixcollage-23-dec-2024-08-34-am-8166.avif",
    releaseDate: "1991-11-21",
    rating: 3 / 75,
    averageTimeToFinish: 45,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "SNES",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: Link's Awakening",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/MV5BZjg2MzY1ZDItOTUzNS00MTVjLTkyZTktMzVjMmM1NTZkMDdiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "1993-06-06",
    rating: 3 / 75,
    averageTimeToFinish: 35,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Game Boy",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: Oracle of Seasons",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/10039_The_Legend_of_Zelda_Oracle_of_Seasons.webp",
    releaseDate: "2001-02-27",
    rating: 4,
    averageTimeToFinish: 40,
    timesFinished: 3,
    additionnalEstimatedTime: 0,
    platform: "Game Boy Color",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: Oracle of Ages",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/10038_The_Legend_of_Zelda_Oracle_of_Ages.webp",
    releaseDate: "2001-02-27",
    rating: 4,
    averageTimeToFinish: 40,
    timesFinished: 3,
    additionnalEstimatedTime: 0,
    platform: "Game Boy Color",
    saga: "The Legend of Zelda",
  },
  {
    title: "The Legend of Zelda: The Minish Cap",
    editor: "Nintendo",
    hero: "Link",
    coverUrl: "/games_pictures/MV5BODlmOTk0MzQtYzI1MS00MzYzLThiYTctNjFkOTY4ZDA1NDllXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "2004-11-04",
    rating: 4.25,
    averageTimeToFinish: 50,
    timesFinished: 2,
    additionnalEstimatedTime: 0,
    platform: "Game Boy Advance",
    saga: "The Legend of Zelda",
  },
  // Call of Duty
  {
    title: "Call of Duty 4: Modern Warfare",
    editor: "Infinity Ward",
    hero: "Captain Price",
    coverUrl: "/games_pictures/cod4pc0f.webp",
    releaseDate: "2007-11-05",
    rating: 4.5,
    averageTimeToFinish: 10,
    timesFinished: 1,
    additionnalEstimatedTime: 250,
    platform: "PlayStation 3",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: World at War",
    editor: "Treyarch",
    hero: "Captain Price",
    coverUrl: "/games_pictures/WAW_Cover_Art.jpg",
    releaseDate: "2008-11-11",
    rating: 4.5,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 300,
    platform: "PlayStation 3",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Modern Warfare 2",
    editor: "Infinity Ward",
    hero: "Captain Price",
    coverUrl: "/games_pictures/Call_of_Duty_Modern_Warfare_2_(2009)_cover.png",
    releaseDate: "2009-11-10",
    rating: 3.75,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 250,
    platform: "PlayStation 3",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Black Ops",
    editor: "Treyarch",
    hero: "Captain Price",
    coverUrl: "/games_pictures/CoD_Black_Ops_cover.png",
    releaseDate: "2010-11-09",
    rating: 4.5,
    averageTimeToFinish: 25,
    timesFinished: 1,
    additionnalEstimatedTime: 800,
    platform: "PlayStation 3",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Modern Warfare 3",
    editor: "Infinity Ward",
    hero: "Captain Price",
    coverUrl: "/games_pictures/call-of-duty-modern-warfare-3_cover_original.webp",
    releaseDate: "2011-11-08",
    rating: 3.75,
    averageTimeToFinish: 60,
    timesFinished: 1,
    additionnalEstimatedTime: 250,
    platform: "PlayStation 3",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Black Ops II",
    editor: "Treyarch",
    hero: "Captain Price",
    coverUrl: "/games_pictures/F9JqxCJQ0SaqaP-big.webp",
    releaseDate: "2012-11-13",
    rating: 3.75,
    averageTimeToFinish: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 150,
    platform: "PlayStation 3",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Black Ops III",
    editor: "Treyarch",
    hero: "Captain Price",
    coverUrl: "/games_pictures/BO301.webp",
    releaseDate: "2015-11-06",
    rating: 5,
    averageTimeToFinish: 80,
    timesFinished: 1,
    additionnalEstimatedTime: 871,
    platform: "PlayStation 4",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Infinite Warfare",
    editor: "Infinity Ward",
    hero: "Captain Price",
    coverUrl: "/games_pictures/81Xel1A4iWL.jpg",
    releaseDate: "2016-11-04",
    rating: 3.75,
    averageTimeToFinish: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 40,
    platform: "PlayStation 4",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: WWII",
    editor: "Sledgehammer Games",
    hero: "Captain Price",
    coverUrl: "/games_pictures/MV5BMTUyNDY4NDY5MF5BMl5BanBnXkFtZTgwMjg3NDQwNDI@._V1_.jpg",
    releaseDate: "2017-11-03",
    rating: 3.5,
    averageTimeToFinish: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 90,
    platform: "PlayStation 4",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Black Ops 4",
    editor: "Treyarch",
    hero: "Captain Price",
    coverUrl: "/games_pictures/61rUFXM8-DL._UF1000,1000_QL80_.jpg",
    releaseDate: "2018-10-12",
    rating: 4.5,
    averageTimeToFinish: 100,
    timesFinished: 1,
    additionnalEstimatedTime: 494,
    platform: "PlayStation 4",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Black Ops Cold War",
    editor: "Treyarch",
    hero: "Captain Price",
    coverUrl: "/games_pictures/epqD0ZAsuCMkSYVBRMUp5bYk.avif",
    releaseDate: "2020-11-13",
    rating: 4,
    averageTimeToFinish: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 380,
    platform: "PlayStation 5",
    saga: "Call of Duty",
  },
  {
    title: "Call of Duty: Black Ops 6",
    editor: "Treyarch",
    hero: "Captain Price",
    coverUrl: "/games_pictures/call-of-duty-black-ops-6-smartcdkeys-cheap-cd-key-cover-390x580.webp",
    releaseDate: "2024-10-03",
    rating: 4.25,
    averageTimeToFinish: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 245,
    platform: "PlayStation 5",
    saga: "Call of Duty",
  },
  // Pokémon
  {
    title: "Pokémon Bleu",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/pokemon-bleu-gb-e106882.jpg",
    releaseDate: "1996-10-15",
    rating: 5,
    averageTimeToFinish: 30,
    timesFinished: 10,
    additionnalEstimatedTime: 240,
    platform: "Game Boy",
    saga: "Pokémon",
  },
  {
    title: "Pokémon Or",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/1515055561-186-jaquette-avant.webp",
    releaseDate: "1999-11-21",
    rating: 4.25,
    averageTimeToFinish: 40,
    timesFinished: 5,
    additionnalEstimatedTime: 150,
    platform: "Game Boy Color",
    saga: "Pokémon",
  },
  {
    title: "Pokémon Cristal",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/s-l640.jpg",
    releaseDate: "2000-12-14",
    rating: 4.5,
    averageTimeToFinish: 45,
    timesFinished: 5,
    additionnalEstimatedTime: 150,
    platform: "Game Boy Color",
    saga: "Pokémon",
  },
  {
    title: "Pokémon Saphir",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/Pokemon-Version-Saphir.jpg",
    releaseDate: "2002-11-21",
    rating: 4.25,
    averageTimeToFinish: 50,
    timesFinished: 5,
    additionnalEstimatedTime: 240,
    platform: "Game Boy Advance",
    saga: "Pokémon",
  },
  {
    title: "Pokémon Émeraude",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/1200px-Jaquette_de_Pokémon_Émeraude.png",
    releaseDate: "2004-09-16",
    rating: 4.5,
    averageTimeToFinish: 55,
    timesFinished: 5,
    additionnalEstimatedTime: 100,
    platform: "Game Boy Advance",
    saga: "Pokémon",
  },
  {
    title: "Pokémon Rouge Feu",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/pkfrga0f.jpg",
    releaseDate: "2004-01-29",
    rating: 3.75,
    averageTimeToFinish: 45,
    timesFinished: 2,
    additionnalEstimatedTime: 50,
    platform: "Game Boy Advance",
    saga: "Pokémon",
  },
  {
    title: "Pokémon Bouclier",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/819sd2k1sCL.jpg",
    releaseDate: "2019-11-15",
    rating: 4.25,
    averageTimeToFinish: 90,
    timesFinished: 1,
    additionnalEstimatedTime: 150,
    platform: "Nintendo Switch",
    saga: "Pokémon",
  },
  {
    title: "Pokémon Violet",
    editor: "Game Freak",
    hero: "Dresseur",
    coverUrl: "/games_pictures/Pokemon-Violet-Nintendo-Switch.jpg",
    releaseDate: "2022-11-18",
    rating: 4.25,
    averageTimeToFinish: 100,
    timesFinished: 1,
    additionnalEstimatedTime: 150,
    platform: "Nintendo Switch",
    saga: "Pokémon",
  },
  // One Piece
  {
    title: "One Piece: Unlimited Cruise Episode 1",
    editor: "Ganbarion",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/jaquette-one-piece-unlimited-cruise-1-le-tresor-sous-les-flots-wii-cover-avant-g.jpg",
    releaseDate: "2008-09-11",
    rating: 4.25,
    averageTimeToFinish: 30,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Wii",
    saga: "One Piece",
  },
  {
    title: "One Piece: Unlimited Cruise Episode 2",
    editor: "Ganbarion",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/one-piece-unlimited-cruise-episode-2-l-eveil-d-un-heros-wii.webp",
    releaseDate: "2009-02-26",
    rating: 4.25,
    averageTimeToFinish: 35,
    timesFinished: 3,
    additionnalEstimatedTime: 100,
    platform: "Wii",
    saga: "One Piece",
  },
  {
    title: "One Piece: Pirate Warriors",
    editor: "Omega Force",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/jaquette-one-piece-pirate-warriors-playstation-3-ps3-cover-avant-g-1348560699.webp",
    releaseDate: "2012-03-01",
    rating: 3.5,
    averageTimeToFinish: 50,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "One Piece",
  },
  {
    title: "One Piece: Pirate Warriors 2",
    editor: "Omega Force",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/71w8-P0uWQS._UF1000,1000_QL80_.jpg",
    releaseDate: "2013-03-20",
    rating: 3.5,
    averageTimeToFinish: 50,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "One Piece",
  },
  {
    title: "One Piece: Unlimited World Red",
    editor: "Ganbarion",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/One-piece-Unlimited-World-Red-Deluxe-edition-Nintendo-Switch.jpg",
    releaseDate: "2014-06-12",
    rating: 4,
    averageTimeToFinish: 80,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Nintendo 3DS",
    saga: "One Piece",
  },
  {
    title: "One Piece: Pirate Warriors 3",
    editor: "Omega Force",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/9672f572e25f1eea69b2827641a2b59d9918485c1c8bfefe792fdcbff385c8a6.avif",
    releaseDate: "2015-03-26",
    rating: 3.5,
    averageTimeToFinish: 100,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 4",
    saga: "One Piece",
  },
  {
    title: "One Piece: Burning Blood",
    editor: "Spike Chunsoft",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/One Piece_ Burning Blood.jpg",
    releaseDate: "2016-04-21",
    rating: 3.75,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 50,
    platform: "PlayStation 4",
    saga: "One Piece",
  },
  {
    title: "One Piece: Treasure Cruise",
    editor: "Ganbarion",
    hero: "Monkey D. Luffy",
    coverUrl: "/games_pictures/efa276cc4b2d4cbc8299081963d464eae3ff6667-hq-1000x1244-1654756315.jpg",
    releaseDate: "2016-04-21",
    rating: 4.5,
    averageTimeToFinish: 0,
    timesFinished: 0,
    additionnalEstimatedTime: 2500,
    platform: "Android",
    saga: "One Piece",
  },
];