import { Game } from "./games_1";

export const games4: Game[] = [
  // Medal of Honor
  {
    title: "Medal of Honor : En première ligne",
    editor: "Electronic Arts",
    hero: "Soldat",
    coverUrl: "/games_pictures/Medal-Of-Honor-En-premiere-ligne.jpg",
    releaseDate: "1999-10-31",
    rating: 4,
    averageTimeToFinish: 8,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation",
    saga: "Medal of Honor",
  },
  // Guitar Hero
  {
    title: "Guitar Hero III: Legends of Rock",
    editor: "Activision",
    hero: "Guitariste",
    coverUrl: "/games_pictures/81VZXSoqNbL.jpg",
    releaseDate: "2007-10-28",
    rating: 4.5,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 200,
    platform: "PlayStation 2",
    saga: "Guitar Hero",
  },
  // Luigi's Mansion
  {
    title: "Luigi's Mansion",
    editor: "Nintendo",
    hero: "Luigi",
    coverUrl: "/games_pictures/Lmbox.jpg",
    releaseDate: "2001-11-18",
    rating: 4,
    averageTimeToFinish: 12,
    timesFinished: 2,
    additionnalEstimatedTime: 0,
    platform: "GameCube",
    saga: "Luigi's Mansion",
  },
  // Tekken
  {
    title: "Tekken: Dark Resurrection",
    editor: "Bandai Namco",
    hero: "Fighter",
    coverUrl: "/games_pictures/71kxx1mB1nL.jpg",
    releaseDate: "2006-07-25",
    rating: 4,
    averageTimeToFinish: 10,
    timesFinished: 1,
    additionnalEstimatedTime: 80,
    platform: "PlayStation Portable",
    saga: "Tekken",
  },
  // Grand Theft Auto
  {
    title: "Grand Theft Auto: San Andreas",
    editor: "Rockstar Games",
    hero: "Carl Johnson",
    coverUrl: "/games_pictures/10_5026555302623_jm.jpg",
    releaseDate: "2004-10-26",
    rating: 5,
    averageTimeToFinish: 40,
    timesFinished: 2,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 2",
    saga: "Grand Theft Auto",
  },
  {
    title: "Grand Theft Auto: Vice City",
    editor: "Rockstar Games",
    hero: "Tommy Vercetti",
    coverUrl: "/games_pictures/61e6sU9SIzL._UF1000,1000_QL80_.jpg",
    releaseDate: "2002-10-27",
    rating: 4.5,
    averageTimeToFinish: 25,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 2",
    saga: "Grand Theft Auto",
  },
  {
    title: "Grand Theft Auto: Vice City Stories",
    editor: "Rockstar Games",
    hero: "Tommy Vercetti",
    coverUrl: "/games_pictures/71qnLo5SrLS.jpg",
    releaseDate: "2002-10-27",
    rating: 4.5,
    averageTimeToFinish: 25,
    timesFinished: 2,
    additionnalEstimatedTime: 80,
    platform: "PlayStation 2",
    saga: "Grand Theft Auto",
  },
  {
    title: "Grand Theft Auto: Liberty City Stories",
    editor: "Rockstar Games",
    hero: "Tommy Vercetti",
    coverUrl: "/games_pictures/71XZGiY69MS._UF1000,1000_QL80_.jpg",
    releaseDate: "2002-10-27",
    rating: 4.5,
    averageTimeToFinish: 25,
    timesFinished: 2,
    additionnalEstimatedTime: 80,
    platform: "PlayStation 2",
    saga: "Grand Theft Auto",
  },
  // Star Wars
  {
    title: "Star Wars: Le Pouvoir de la Force",
    editor: "LucasArts",
    hero: "Jedi",
    coverUrl: "/games_pictures/81idoSKM3BL._UF1000,1000_QL80_.jpg",
    releaseDate: "2008-11-04",
    rating: 4,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 3",
    saga: "Star Wars",
  },
  {
    title: "Lego Star Wars",
    editor: "LucasArts",
    hero: "Luke Skywalker",
    coverUrl: "/games_pictures/51PIJcSrsnL._UF1000,1000_QL80_.jpg",
    releaseDate: "2005-04-02",
    rating: 4.5,
    averageTimeToFinish: 15,
    timesFinished: 2,
    additionnalEstimatedTime: 0,
    platform: "PlayStation 2",
    saga: "Star Wars",
  },
  {
    title: "Star Wars: Rebel Strike",
    editor: "LucasArts",
    hero: "Pilote",
    coverUrl: "/games_pictures/rgs3gc0f.jpg",
    releaseDate: "2003-10-21",
    rating: 4,
    averageTimeToFinish: 18,
    timesFinished: 1,
    additionnalEstimatedTime: 50,
    platform: "GameCube",
    saga: "Star Wars",
  },
  // Wario Ware
  {
    title: "WarioWare: Smooth Moves",
    editor: "Nintendo",
    hero: "Wario",
    coverUrl: "/games_pictures/813wBVf7BXL.jpg",
    releaseDate: "2007-01-15",
    rating: 4,
    averageTimeToFinish: 8,
    timesFinished: 1,
    additionnalEstimatedTime: 80,
    platform: "Wii",
    saga: "WarioWare",
  },
  // Gunbound
  {
    title: "Gunbound World Champion",
    editor: "Softnyx",
    hero: "Artilleur",
    coverUrl: "/games_pictures/11820829.jpg",
    releaseDate: "2005-01-01",
    rating: 3.5,
    averageTimeToFinish: 5,
    timesFinished: 1,
    additionnalEstimatedTime: 300,
    platform: "PC",
    saga: "Gunbound",
  },
  // GoldenEye
  {
    title: "GoldenEye 007",
    editor: "Nintendo",
    hero: "James Bond",
    coverUrl: "/games_pictures/MV5BZWIwYWJmNzQtNWZiNC00Njc3LWI2YTUtYTJiMDFlYTc2YWRhXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "1997-08-25",
    rating: 5,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 20,
    platform: "Nintendo 64",
    saga: "GoldenEye",
  },
  // Wii Sports
  {
    title: "Wii Sports",
    editor: "Nintendo",
    hero: "Mii",
    coverUrl: "/games_pictures/wii-sport-e15224.jpg",
    releaseDate: "2006-11-19",
    rating: 4.5,
    averageTimeToFinish: 10,
    timesFinished: 1,
    additionnalEstimatedTime: 150,
    platform: "Wii",
    saga: "Wii Sports",
  },
  // Harry Potter
  {
    title: "Harry Potter: Coupe du Monde de Quidditch",
    editor: "Electronic Arts",
    hero: "Harry Potter",
    coverUrl: "/games_pictures/hpqupc0f.jpg",
    releaseDate: "2003-10-28",
    rating: 4,
    averageTimeToFinish: 12,
    timesFinished: 1,
    additionnalEstimatedTime: 20,
    platform: "GameCube",
    saga: "Harry Potter",
  },
  // Les Simpsons
  {
    title: "Les Simpsons: Le Jeu",
    editor: "Electronic Arts",
    hero: "Homer Simpson",
    coverUrl: "/games_pictures/lsljwi0f.webp",
    releaseDate: "2007-07-30",
    rating: 4,
    averageTimeToFinish: 15,
    timesFinished: 1,
    additionnalEstimatedTime: 15,
    platform: "Wii",
    saga: "Les Simpsons",
  },
  // Sonic
  {
    title: "Sonic Adventure 2 Battle",
    editor: "Sega",
    hero: "Sonic",
    coverUrl: "/games_pictures/jaquette-sonic-adventure-2-battle-gamecube-ngc-cover-avant-g-1361810227.webp",
    releaseDate: "2001-12-20",
    rating: 4.5,
    averageTimeToFinish: 20,
    timesFinished: 1,
    additionnalEstimatedTime: 10,
    platform: "GameCube",
    saga: "Sonic",
  },
  {
    title: "Sonic Unleashed",
    editor: "Sega",
    hero: "Sonic",
    coverUrl: "/games_pictures/71xgwF1QaLL.jpg",
    releaseDate: "2008-11-18",
    rating: 4,
    averageTimeToFinish: 18,
    timesFinished: 1,
    additionnalEstimatedTime: 0,
    platform: "Wii",
    saga: "Sonic",
  },
  // Super Smash Bros
  {
    title: "Super Smash Bros. Brawl",
    editor: "Nintendo",
    hero: "Mario",
    coverUrl: "/games_pictures/71aV0SbNGCL.jpg",
    releaseDate: "2008-01-31",
    rating: 4.5,
    averageTimeToFinish: 25,
    timesFinished: 1,
    additionnalEstimatedTime: 150,
    platform: "Wii",
    saga: "Super Smash Bros",
  },
];