import { Book } from '../../../models/book-model';

export const kevinBooks1: Book[] = [
  {
    title: "L'étranger",
    author: 'Albert Camus',
    coverUrl: '/books_pictures/l_etranger.jpg',
    readDate: '2024-01-01',
    rating: 0,
    pages: 159,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: "L'Alchimiste",
    author: 'Paulo Coelho',
    coverUrl: '/books_pictures/l_alchimiste.jpg',
    readDate: '2024-01-15',
    rating: 0,
    pages: 224,
    genre: 'Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Le porteur de lumière, tome 1 : Le prisme noir',
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/le_prisme_noir.jpg',
    readDate: '2024-02-01',
    rating: 0,
    pages: 688,
    genre: 'Fantasy',
    saga: 'Le porteur de lumière',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Sherlock Holmes : Le signe des Quatre (La marque des Quatre)',
    author: 'Arthur Conan Doyle',
    coverUrl: '/books_pictures/le_signe_des_quatre.jpg',
    readDate: '2024-02-15',
    rating: 0,
    pages: 240,
    genre: 'Enquête',
    saga: 'Sherlock Holmes',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 1 : Le Voleur de foudre',
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/percy_jackson_1.jpg',
    readDate: '2024-03-01',
    rating: 0,
    pages: 416,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 2 : La mer des monstres',
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/percy_jackson_2.jpg',
    readDate: '2024-03-10',
    rating: 0,
    pages: 320,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 3 : Le sort du titan',
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/percy_jackson_3.jpg',
    readDate: '2024-03-20',
    rating: 0,
    pages: 352,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 4 : La bataille du labyrinthe',
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/percy_jackson_4.jpg',
    readDate: '2024-04-01',
    rating: 0,
    pages: 448,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 5 : Le dernier Olympien',
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/percy_jackson_5.jpg',
    readDate: '2024-04-15',
    rating: 0,
    pages: 448,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "Héros de l'Olympe, tome 1 : Le héros perdu",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/heros_olympe_1.jpg',
    readDate: '2025-05-15',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "Héros de l'Olympe",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'La Horde du Contrevent',
    author: 'Alain Damasio',
    coverUrl: '/books_pictures/la_horde_du_contrevent.jpg',
    readDate: '2024-05-01',
    rating: 0,
    pages: 704,
    genre: 'Science Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Ils étaient dix (Dix petits nègres)',
    author: 'Agatha Christie',
    coverUrl: '/books_pictures/ils_etaient_dix.webp',
    readDate: '2024-06-01',
    rating: 0,
    pages: 264,
    genre: 'Enquête',
    saga: 'Agatha Christie',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    coverUrl: '/books_pictures/madame-bovary.jpg',
    readDate: '2024-06-15',
    rating: 0,
    pages: 528,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Candide',
    author: 'Voltaire',
    coverUrl: '/books_pictures/candide.jpg',
    readDate: '2024-07-01',
    rating: 0,
    pages: 129,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Hunger Games, tome 1',
    author: 'Suzanne Collins',
    coverUrl: '/books_pictures/hunger_games_1.jpg',
    readDate: '2024-05-15',
    rating: 0,
    pages: 399,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Hunger Games, tome 2 : L'embrasement",
    author: 'Suzanne Collins',
    coverUrl: '/books_pictures/hunger_games_2.jpg',
    readDate: '2024-07-15',
    rating: 0,
    pages: 400,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Hunger Games, tome 3 : La révolte',
    author: 'Suzanne Collins',
    coverUrl: '/books_pictures/hunger_games_3.jpg',
    readDate: '2024-08-01',
    rating: 0,
    pages: 400,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Hunger Games : La Ballade du serpent et de l'Oiseau chanteur",
    author: 'Suzanne Collins',
    coverUrl: '/books_pictures/hunger_games_ballade.jpg',
    readDate: '2024-11-01',
    rating: 0,
    pages: 640,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Croc-Blanc',
    author: 'Jack London',
    coverUrl: '/books_pictures/croc_blanc.jpg',
    readDate: '2024-08-15',
    rating: 0,
    pages: 288,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Robinson Crusoé',
    author: 'Daniel Defoe',
    coverUrl: '/books_pictures/robinson_crusoe.jpg',
    readDate: '2024-09-15',
    rating: 0,
    pages: 352,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 1 : L'Apprenti assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_1.jpg',
    readDate: '2024-09-01',
    rating: 0,
    pages: 576,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 2 : L'Assassin du roi",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_2.jpg',
    readDate: '2024-10-01',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 3 : La Nef du crépuscule",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_3.jpg',
    readDate: '2024-10-15',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 4 : Le Poison de la vengeance",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_4.jpg',
    readDate: '2024-11-15',
    rating: 0,
    pages: 560,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 5 : La voie magique",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_5.jpg',
    readDate: '2024-12-01',
    rating: 0,
    pages: 576,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 6 : La Reine solitaire",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_6.jpg',
    readDate: '2024-12-15',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 6,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 7 : Le Prophète blanc",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_7.jpg',
    readDate: '2025-01-01',
    rating: 0,
    pages: 528,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 7,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 8 : La Secte maudite",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_8.jpg',
    readDate: '2025-01-15',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 8,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 9 : Les Secrets de Castelcerf",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_9.jpg',
    readDate: '2025-02-01',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 9,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 10 : Serments et deuils",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_10.jpg',
    readDate: '2025-02-15',
    rating: 0,
    pages: 624,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 10,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 11 : Le Dragon des glaces",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_11.jpg',
    readDate: '2025-03-01',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 11,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 12 : L'Homme noir",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_12.jpg',
    readDate: '2025-03-15',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 12,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 13 : Adieux et retrouvailles",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/assassin_royal_13.jpg',
    readDate: '2025-04-01',
    rating: 0,
    pages: 656,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 13,
    readTimes: 1,
  },
  {
    title: "Le Fou et l'Assassin, tome 1",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/fou_assassin_1.jpg',
    readDate: '2025-08-15',
    rating: 0,
    pages: 592,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 2 : La fille de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/fou_assassin_2.jpg',
    readDate: '2025-11-01',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 3 : En quête de vengeance",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/fou_assassin_3.jpg',
    readDate: '2020-02-01',
    rating: 0,
    pages: 624,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 4 : Le retour de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/fou_assassin_4.jpg',
    readDate: '2020-02-15',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 5 : Sur les rives de l'Art",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/fou_assassin_5.jpg',
    readDate: '2020-05-15',
    rating: 0,
    pages: 656,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 6 : Le destin de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/fou_assassin_6.jpg',
    readDate: '2020-06-01',
    rating: 0,
    pages: 672,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 6,
    readTimes: 1,
  },
  {
    title: 'Quand vient la horde',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/quand_vient_la_horde.jpg',
    readDate: '2021-09-01',
    rating: 0,
    pages: 352,
    genre: 'Fantasy',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Les annales du Disque-Monde, tome 1 : La huitième couleur',
    author: 'Terry Pratchett',
    coverUrl: '/books_pictures/disque_monde_1.jpg',
    readDate: '2025-04-15',
    rating: 0,
    pages: 288,
    genre: 'Fantasy',
    saga: 'Les annales du Disque-Monde',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Nevernight, tome 1 : N'oublie jamais",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/nevernight_1.jpg',
    readDate: '2025-05-01',
    rating: 0,
    pages: 512,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Nevernight, tome 2 : Les grands jeux',
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/nevernight_2.jpg',
    readDate: '2020-01-15',
    rating: 0,
    pages: 576,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Nevernight, tome 3 : L'aube obscure",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/nevernight_3.jpg',
    readDate: '2020-04-01',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Fils des brumes, tome 1 : L'Empire ultime",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/fils_des_brumes_1.jpg',
    readDate: '2025-06-01',
    rating: 0,
    pages: 672,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Fils des brumes, tome 2 : Le puits de l'ascension",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/fils_des_brumes_2.jpg',
    readDate: '2020-03-01',
    rating: 0,
    pages: 768,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Fils des brumes, tome 3 : Le héros des siècles',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/fils_des_brumes_3.jpg',
    readDate: '2020-04-15',
    rating: 0,
    pages: 800,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les Voleurs de fumée, tome 1',
    author: 'Sally Green',
    coverUrl: '/books_pictures/voleurs_fumee_1.jpg',
    readDate: '2025-09-15',
    rating: 0,
    pages: 480,
    genre: 'Fantasy',
    saga: 'Les Voleurs de fumée',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Le Démon et mademoiselle Prym',
    author: 'Paulo Coelho',
    coverUrl: '/books_pictures/demon_mlle_prym.jpg',
    readDate: '2025-10-01',
    rating: 0,
    pages: 224,
    genre: 'Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Les Maîtres enlumineurs, tome 1',
    author: 'David Moody',
    coverUrl: '/books_pictures/maitres_enlumineurs_1.jpg',
    readDate: '2025-10-15',
    rating: 0,
    pages: 400,
    genre: 'Fantasy',
    saga: 'Les Maîtres enlumineurs',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Ange de la Nuit, Tome 1 : La Voie des ombres",
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/ange_nuit_1.jpg',
    readDate: '2020-03-15',
    rating: 0,
    pages: 672,
    genre: 'Fantasy',
    saga: "L'Ange de la Nuit",
    sagaOrder: 1,
    readTimes: 1,
  },
];
