import { Book } from '../../../models/book-model';

export const kevinBooks2: Book[] = [
  {
    title: "Le royaume de Pierre d'Angle, tome 1 : L'art du naufrage",
    author: 'Mark Lawrence',
    coverUrl: '/books_pictures/royaume_pierre_angle_1.jpg',
    readDate: '2020-05-01',
    rating: 0,
    pages: 416,
    genre: 'Fantasy',
    saga: "Le royaume de Pierre d'Angle",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Cycle de Tschai - Intégrale',
    author: 'Jack Vance',
    coverUrl: '/books_pictures/cycle_tschai.jpg',
    readDate: '2020-06-15',
    rating: 0,
    pages: 800,
    genre: 'Science Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Les salauds gentilshommes, tome 1 : Les mensonges de Locke Lamora',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/salauds_gentilshommes_1.jpg',
    readDate: '2025-06-15',
    rating: 0,
    pages: 672,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les salauds gentilshommes, tome 2 : Des horizons rouge sang',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/salauds_gentilshommes_2.jpg',
    readDate: '2020-07-01',
    rating: 0,
    pages: 704,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les salauds gentilshommes, tome 3 : La république des voleurs',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/salauds_gentilshommes_3.jpg',
    readDate: '2020-10-01',
    rating: 0,
    pages: 768,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 1 : La compagnie noire',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/compagnie_noire_1.jpg',
    readDate: '2025-09-01',
    rating: 0,
    pages: 320,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 2 : Le château noir',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/compagnie_noire_2.jpg',
    readDate: '2020-08-15',
    rating: 0,
    pages: 352,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 3 : La rose blanche',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/compagnie_noire_3.jpg',
    readDate: '2020-10-15',
    rating: 0,
    pages: 384,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Le Cycle de Syffe, tome 1 : L'Enfant de poussière",
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/cycle_syffe_1.jpg',
    readDate: '2025-08-01',
    rating: 0,
    pages: 624,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Le cycle de Syffe, tome 2 : La peste et la vigne',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/cycle_syffe_2.jpg',
    readDate: '2020-11-01',
    rating: 0,
    pages: 656,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Le cycle de Syffe, tome 3 : Les chiens et la charrue',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/cycle_syffe_3.jpg',
    readDate: '2021-01-01',
    rating: 0,
    pages: 688,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Le cycle de Syffe, tome 4 : La Maison des veilleurs',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/cycle_syffe_4.jpg',
    readDate: '2021-06-01',
    rating: 0,
    pages: 720,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Les faucons de Raverra, tome 1 : La sorcière captive',
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/faucons_raverra_1.jpg',
    readDate: '2020-12-15',
    rating: 0,
    pages: 480,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Les faucons de Raverra, tome 2 : L'héritière rebelle",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/faucons_raverra_2.jpg',
    readDate: '2021-09-15',
    rating: 0,
    pages: 512,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Les faucons de Raverra, tome 3 : L'empire libéré",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/faucons_raverra_3.jpg',
    readDate: '2022-01-15',
    rating: 0,
    pages: 544,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 1 : La voie des rois (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/voie_des_rois_1.jpg',
    readDate: '2025-07-01',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 1 : La voie des rois (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/voie_des_rois_2.jpg',
    readDate: '2025-07-15',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 2 : Le livre des Radieux (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/livre_radieux_1.jpg',
    readDate: '2020-09-01',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 2 : Le livre des Radieux (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/livre_radieux_2.jpg',
    readDate: '2020-09-15',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 3 : Justicière (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/justiciere_1.jpg',
    readDate: '2020-11-15',
    rating: 0,
    pages: 656,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 3 : Justicière (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/justiciere_2.jpg',
    readDate: '2020-12-01',
    rating: 0,
    pages: 656,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 4 : Rythme de guerre (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/rythme_guerre_1.jpg',
    readDate: '2021-02-15',
    rating: 0,
    pages: 720,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 4 : Rythme de guerre (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/rythme_guerre_2.jpg',
    readDate: '2021-03-15',
    rating: 0,
    pages: 720,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 1 : Le don de mort (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/guilde_ombres_1_1.jpg',
    readDate: '2020-07-15',
    rating: 0,
    pages: 400,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 1 : Le don de mort (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/guilde_ombres_1_2.jpg',
    readDate: '2020-08-01',
    rating: 0,
    pages: 400,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 2 : Le don de vie (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/guilde_ombres_2_1.jpg',
    readDate: '2021-04-15',
    rating: 0,
    pages: 432,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 2 : Le don de vie (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/guilde_ombres_2_2.jpg',
    readDate: '2021-05-01',
    rating: 0,
    pages: 432,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 3 : La guerre céleste (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/guilde_ombres_3_1.jpg',
    readDate: '2021-12-01',
    rating: 0,
    pages: 464,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 3 : La guerre céleste (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/guilde_ombres_3_2.jpg',
    readDate: '2021-12-15',
    rating: 0,
    pages: 464,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Le Livre des Martyrs, tome 1 : Les Jardins de la Lune',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/livre_martyrs_1.jpg',
    readDate: '2020-01-01',
    rating: 0,
    pages: 752,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Le livre des martyrs, tome 2 : Les portes de la maison des morts',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/livre_martyrs_2.jpg',
    readDate: '2021-02-01',
    rating: 0,
    pages: 976,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Le Livre des Martyrs, tome 3 : Les Souvenirs de la Glace',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/livre_martyrs_3.jpg',
    readDate: '2021-04-01',
    rating: 0,
    pages: 1056,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Le Livre des martyrs, tome 4 : La Maison des chaînes',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/livre_martyrs_4.jpg',
    readDate: '2021-05-15',
    rating: 0,
    pages: 1072,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Le Livre des martyrs, tome 5 : Les Marées de minuit',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/livre_martyrs_5.jpg',
    readDate: '2021-08-01',
    rating: 0,
    pages: 1136,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "Wax et Wayne, tome 1 : L'alliage de la justice",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/wax_wayne_1.jpg',
    readDate: '2021-03-01',
    rating: 0,
    pages: 416,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Wax et Wayne, tome 2 : Jeux de masques',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/wax_wayne_2.jpg',
    readDate: '2021-08-15',
    rating: 0,
    pages: 448,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Wax et Wayne, tome 3 : Les bracelets des larmes',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/wax_wayne_3.jpg',
    readDate: '2021-11-01',
    rating: 0,
    pages: 480,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Les Princes d'Ambre - Cycle 1",
    author: 'Roger Zelazny',
    coverUrl: '/books_pictures/princes_ambre_1.jpg',
    readDate: '2022-01-01',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "Les Princes d'Ambre",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 1 : Le trône du dragon",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_1.jpg',
    readDate: '2021-01-15',
    rating: 0,
    pages: 768,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 2 : Le roi de l'orage",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_2.jpg',
    readDate: '2021-06-15',
    rating: 0,
    pages: 800,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 3 : La maison de l'ancêtre",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_3.jpg',
    readDate: '2021-07-01',
    rating: 0,
    pages: 832,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "L'arcane des épées, tome 4 : La pierre de l'adieu",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_4.jpg',
    readDate: '2021-07-15',
    rating: 0,
    pages: 848,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 5 : Le livre du nécromant",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_5.jpg',
    readDate: '2021-10-01',
    rating: 0,
    pages: 864,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 6 : Le cri de Camaris",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_6.jpg',
    readDate: '2021-11-15',
    rating: 0,
    pages: 880,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 6,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 7 : L'ombre de la roue",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_7.jpg',
    readDate: '2022-02-01',
    rating: 0,
    pages: 896,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 7,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 8 : La tour de l'ange vert",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/arcane_epees_8.jpg',
    readDate: '2022-02-15',
    rating: 0,
    pages: 912,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 8,
    readTimes: 1,
  },
  {
    title: "Une couronne d'épines, tome 1 : Tuer la reine",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/couronne_epines_1.jpg',
    readDate: '2021-10-15',
    rating: 0,
    pages: 480,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Une couronne d'épines, tome 2 : Défendre le prince",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/couronne_epines_2.jpg',
    readDate: '2022-03-01',
    rating: 0,
    pages: 496,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Une couronne d'épines, tome 3 : Écraser le roi",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/couronne_epines_3.jpg',
    readDate: '2022-03-15',
    rating: 0,
    pages: 512,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 3,
    readTimes: 1,
  },
];
