import { Book } from '../../../models/book-model';

export const kevinBooks1: Book[] = [
  {
    title: "L'étranger",
    author: 'Albert Camus',
    coverUrl: '/books_pictures/25_9782070360024_1_75.jpg',
    readDate: '',
    rating: 0,
    pages: 159,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: "L'Alchimiste",
    author: 'Paulo Coelho',
    coverUrl: '/books_pictures/24_9782290258064_1_75.jpg',
    readDate: '',
    rating: 5,
    pages: 224,
    genre: 'Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Le porteur de lumière, tome 1 : Le prisme noir',
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/9161wIQDCzL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 688,
    genre: 'Fantasy',
    saga: 'Le porteur de lumière',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Sherlock Holmes : Le signe des Quatre (La marque des Quatre)',
    author: 'Arthur Conan Doyle',
    coverUrl: '/books_pictures/le_signe_des_quatre-778479-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 240,
    genre: 'Enquête',
    saga: 'Sherlock Holmes',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 1 : Le Voleur de foudre',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_1_le_voleur_de_foudre-997184-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 416,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 2 : La mer des monstres',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_2_la_mer_des_monstres-48633-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 320,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 3 : Le sort du titan',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_3_le_sort_du_titan-70591-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 352,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 4 : La bataille du labyrinthe',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_4_la_bataille_du_labyrinthe-380098-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 448,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Percy Jackson et les Olympiens, tome 5 : Le dernier Olympien',
    author: 'Rick Riordan',
    coverUrl:
      '/books_pictures/percy_jackson_tome_5_le_dernier_olympien-77283-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 448,
    genre: 'Fantasy',
    saga: 'Percy Jackson et les Olympiens',
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "Héros de l'Olympe, tome 1 : Le héros perdu",
    author: 'Rick Riordan',
    coverUrl: '/books_pictures/815Gg+369GL.jpg',
    readDate: '',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "Héros de l'Olympe",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'La Horde du Contrevent',
    author: 'Alain Damasio',
    coverUrl: '/books_pictures/la_horde_du_contrevent.jpg',
    readDate: '',
    rating: 2.5,
    pages: 704,
    genre: 'Science Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Ils étaient dix (Dix petits nègres)',
    author: 'Agatha Christie',
    coverUrl: '/books_pictures/ils_etaient_dix.webp',
    readDate: '',
    rating: 0,
    pages: 264,
    genre: 'Enquête',
    saga: 'Agatha Christie',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    coverUrl: '/books_pictures/madame-bovary.jpg',
    readDate: '',
    rating: 0,
    pages: 528,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Candide',
    author: 'Voltaire',
    coverUrl: '/books_pictures/candide.jpg',
    readDate: '',
    rating: 0,
    pages: 129,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Hunger Games, tome 1',
    author: 'Suzanne Collins',
    coverUrl: '/books_pictures/hunger_games_tome_1-337660-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 399,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Hunger Games, tome 2 : L'embrasement",
    author: 'Suzanne Collins',
    coverUrl:
      '/books_pictures/hunger_games_tome_2_lembrasement-54688-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 400,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Hunger Games, tome 3 : La révolte',
    author: 'Suzanne Collins',
    coverUrl:
      '/books_pictures/hunger_games_tome_3_la_revolte-132534-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 400,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Hunger Games : La Ballade du serpent et de l'Oiseau chanteur",
    author: 'Suzanne Collins',
    coverUrl:
      '/books_pictures/hunger_games_tome_0_la_ballade_du_serpent_et_de_loiseau_chanteur-1349048-264-432.jpg',
    readDate: '',
    rating: 0,
    pages: 640,
    genre: 'Science Fiction',
    saga: 'Hunger Games',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Croc-Blanc',
    author: 'Jack London',
    coverUrl: '/books_pictures/A65190.jpg',
    readDate: '',
    rating: 0,
    pages: 288,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Robinson Crusoé',
    author: 'Daniel Defoe',
    coverUrl: '/books_pictures/61_9782011611536_1_75.jpg',
    readDate: '',
    rating: 0,
    pages: 352,
    genre: 'Classiques',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 1 : L'Apprenti assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal.jpg',
    readDate: '',
    rating: 5,
    pages: 576,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 2 : L'Assassin du roi",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/50_9782290383353_1_75.jpg',
    readDate: '',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 3 : La Nef du crépuscule",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B17ujV8KQ3L._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 4 : Le Poison de la vengeance",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/71tHCd+juBL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 560,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 5 : La voie magique",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (1).jpg',
    readDate: '',
    rating: 0,
    pages: 576,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 6 : La Reine solitaire",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290383315.jpg',
    readDate: '',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 6,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 7 : Le Prophète blanc",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290383360.jpg',
    readDate: '',
    rating: 0,
    pages: 528,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 7,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 8 : La Secte maudite",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (2).jpg',
    readDate: '',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 8,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 9 : Les Secrets de Castelcerf",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1toxBHfsJL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 9,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 10 : Serments et deuils",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1lUlSj6qbL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 624,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 10,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 11 : Le Dragon des glaces",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/B1q-2ak7erL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 11,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 12 : L'Homme noir",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (3).jpg',
    readDate: '',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 12,
    readTimes: 1,
  },
  {
    title: "L'Assassin royal, tome 13 : Adieux et retrouvailles",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/L-Aain-royal (4).jpg',
    readDate: '',
    rating: 0,
    pages: 656,
    genre: 'Fantasy',
    saga: "L'Assassin royal",
    sagaOrder: 13,
    readTimes: 1,
  },
  {
    title: "Le Fou et l'Assassin, tome 1",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403303_1_75.jpg',
    readDate: '',
    rating: 0,
    pages: 592,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 2 : La fille de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/La-fille-de-l-aain.jpg',
    readDate: '',
    rating: 0,
    pages: 608,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 3 : En quête de vengeance",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403341-475x500-1.webp',
    readDate: '',
    rating: 0,
    pages: 624,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 4 : Le retour de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/9782290403327-475x500-1.jpg',
    readDate: '',
    rating: 0,
    pages: 640,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 5 : Sur les rives de l'Art",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/Sur-les-rives-de-l-Art.jpg',
    readDate: '',
    rating: 0,
    pages: 656,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "Le fou et l'assassin, tome 6 : Le destin de l'assassin",
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/Le-destin-de-l-aain.jpg',
    readDate: '',
    rating: 0,
    pages: 672,
    genre: 'Fantasy',
    saga: "Le Fou et l'Assassin",
    sagaOrder: 6,
    readTimes: 1,
  },
  {
    title: 'Quand vient la horde',
    author: 'Robin Hobb',
    coverUrl: '/books_pictures/61JJS7F1YLL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 3,
    pages: 352,
    genre: 'Fantasy',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Les annales du Disque-Monde, tome 1 : La huitième couleur',
    author: 'Terry Pratchett',
    coverUrl: '/books_pictures/9782266211819_1_75.jpg',
    readDate: '',
    rating: 3.5,
    pages: 288,
    genre: 'Fantasy',
    saga: 'Les annales du Disque-Monde',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Nevernight, tome 1 : N'oublie jamais",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/Nevernight-Tome-01-N-oublie-jamais-broche.jpg',
    readDate: '',
    rating: 4.5,
    pages: 512,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Nevernight, tome 2 : Les grands jeux',
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/Nevernight-Tome-02-Les-grands-jeux-broche.jpg',
    readDate: '',
    rating: 5,
    pages: 576,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Nevernight, tome 3 : L'aube obscure",
    author: 'Jay Kristoff',
    coverUrl: '/books_pictures/83_9782378761615_1_75.jpg',
    readDate: '',
    rating: 4.5,
    pages: 608,
    genre: 'Fantasy',
    saga: 'Nevernight',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Fils des brumes, tome 1 : L'Empire ultime",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/L-Empire-Ultime-Fils-des-Brumes.jpg',
    readDate: '',
    rating: 5,
    pages: 672,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Fils des brumes, tome 2 : Le puits de l'ascension",
    author: 'Brandon Sanderson',
    coverUrl:
      '/books_pictures/fils_des_brumes_tome_2_le_puits_de_lascension-997086-264-432.jpg',
    readDate: '',
    rating: 5,
    pages: 768,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Fils des brumes, tome 3 : Le héros des siècles',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/Le-Heros-des-siecles-Fils-des-brumes.jpg',
    readDate: '',
    rating: 5,
    pages: 800,
    genre: 'Fantasy',
    saga: 'Fils des brumes',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les Voleurs de fumée, tome 1',
    author: 'Sally Green',
    coverUrl: '/books_pictures/81zTGf5yQtL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 2.5,
    pages: 480,
    genre: 'Fantasy',
    saga: 'Les Voleurs de fumée',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Le Démon et mademoiselle Prym',
    author: 'Paulo Coelho',
    coverUrl: '/books_pictures/71kpyKFhtIL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 5,
    pages: 224,
    genre: 'Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Les Maîtres enlumineurs, tome 1',
    author: 'David Moody',
    coverUrl:
      '/books_pictures/les_maitres_enlumineurs_tome_1-1482893-264-432.jpg',
    readDate: '',
    rating: 3.5,
    pages: 400,
    genre: 'Fantasy',
    saga: 'Les Maîtres enlumineurs',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Ange de la Nuit, Tome 1 : La Voie des ombres",
    author: 'Brent Weeks',
    coverUrl: '/books_pictures/61eW9gkl4ZL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 672,
    genre: 'Fantasy',
    saga: "L'Ange de la Nuit",
    sagaOrder: 1,
    readTimes: 1,
  },
];
