import { Book } from '../../../models/book-model';

export const kevinBooks2: Book[] = [
  {
    title: "Le royaume de Pierre d'Angle, tome 1 : L'art du naufrage",
    author: 'Mark Lawrence',
    coverUrl: '/books_pictures/9782072999123-475x500-1.webp',
    readDate: '',
    rating: 2.5,
    pages: 416,
    genre: 'Fantasy',
    saga: "Le royaume de Pierre d'Angle",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Cycle de Tschai - Intégrale',
    author: 'Jack Vance',
    coverUrl: '/books_pictures/71ukooWJDFL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 0,
    pages: 800,
    genre: 'Science Fiction',
    saga: '',
    sagaOrder: 0,
    readTimes: 1,
  },
  {
    title: 'Les salauds gentilshommes, tome 1 : Les mensonges de Locke Lamora',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/images.jpg',
    readDate: '',
    rating: 0,
    pages: 672,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les salauds gentilshommes, tome 2 : Des horizons rouge sang',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/817mO9uCDEL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 4,
    pages: 704,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les salauds gentilshommes, tome 3 : La république des voleurs',
    author: 'Scott Lynch',
    coverUrl: '/books_pictures/9791028117948_1_75.jpg',
    readDate: '',
    rating: 4,
    pages: 768,
    genre: 'Fantasy',
    saga: 'Les salauds gentilshommes',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 1 : La compagnie noire',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/71pAU06PgBL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 4,
    pages: 320,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 2 : Le château noir',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/Le-chateau-noir.jpg',
    readDate: '',
    rating: 4,
    pages: 352,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les Annales de la Compagnie Noire, Tome 3 : La rose blanche',
    author: 'Glen Cook',
    coverUrl: '/books_pictures/9782290330685_1_75.jpg',
    readDate: '',
    rating: 4,
    pages: 384,
    genre: 'Fantasy',
    saga: 'Les Annales de la Compagnie Noire',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Le Cycle de Syffe, tome 1 : L'Enfant de poussière",
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/41INjyFCoVL._SX195_.jpg',
    readDate: '',
    rating: 3,
    pages: 624,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Le cycle de Syffe, tome 2 : La peste et la vigne',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/La-peste-et-la-vigne.jpg',
    readDate: '',
    rating: 3,
    pages: 656,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Le cycle de Syffe, tome 3 : Les chiens et la charrue',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/Les-chiens-et-la-charrue.jpg',
    readDate: '',
    rating: 3,
    pages: 688,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Le cycle de Syffe, tome 4 : La Maison des veilleurs',
    author: 'Peter V. Brett',
    coverUrl: '/books_pictures/71Kz3M-hJAL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 4,
    pages: 720,
    genre: 'Fantasy',
    saga: 'Le Cycle de Syffe',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Les faucons de Raverra, tome 1 : La sorcière captive',
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81xvgxW2aXL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 5,
    pages: 480,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Les faucons de Raverra, tome 2 : L'héritière rebelle",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81ayZbT8cVL.jpg',
    readDate: '',
    rating: 5,
    pages: 512,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Les faucons de Raverra, tome 3 : L'empire libéré",
    author: 'Melissa Caruso',
    coverUrl: '/books_pictures/81F4mKgR4iL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 5,
    pages: 544,
    genre: 'Fantasy',
    saga: 'Les faucons de Raverra',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 1 : La voie des rois (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81pXYzQn+8L.jpg',
    readDate: '',
    rating: 5,
    pages: 608,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 1 : La voie des rois (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/9782253191247_1_75.jpg',
    readDate: '',
    rating: 4.5,
    pages: 608,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 2 : Le livre des Radieux (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81EE84gozJL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 4,
    pages: 640,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 2 : Le livre des Radieux (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/couv43194286.jpg',
    readDate: '',
    rating: 4,
    pages: 640,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 3 : Justicière (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/813UwoQCTXL.jpg',
    readDate: '',
    rating: 4.5,
    pages: 656,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 3 : Justicière (2/2)',
    author: 'Brandon Sanderson',
    coverUrl:
      '/books_pictures/justiciere-brandon-sanderson-les-archives-de-roshar-tome-3-partie-2.jpg',
    readDate: '',
    rating: 4.5,
    pages: 656,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 4 : Rythme de guerre (1/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/81slChiIC6L.jpg',
    readDate: '',
    rating: 4.5,
    pages: 720,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Les archives de Roshar, tome 4 : Rythme de guerre (2/2)',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/1_metadata-image-51642058.jpeg',
    readDate: '',
    rating: 4.5,
    pages: 720,
    genre: 'Fantasy',
    saga: 'Les archives de Roshar',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 1 : Le don de mort (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/81gPgtNVULL.jpg',
    readDate: '',
    rating: 3.5,
    pages: 400,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 1 : Le don de mort (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/La-Guilde-des-Ombres-T1P2.jpg',
    readDate: '',
    rating: 4,
    pages: 400,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 2 : Le don de vie (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/La-Guilde-des-Ombres-T2P1.jpg',
    readDate: '',
    rating: 3.5,
    pages: 432,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 2 : Le don de vie (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/La-Guilde-des-Ombres-T2P2.jpg',
    readDate: '',
    rating: 3.5,
    pages: 432,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 3 : La guerre céleste (1/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/81xnG84J08L.jpg',
    readDate: '',
    rating: 3.5,
    pages: 464,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'La guilde des ombres, tome 3 : La guerre céleste (2/2)',
    author: 'Anthony Ryan',
    coverUrl: '/books_pictures/81diNDSbQBL.jpg',
    readDate: '',
    rating: 3.5,
    pages: 464,
    genre: 'Fantasy',
    saga: 'La guilde des ombres',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Le Livre des Martyrs, tome 1 : Les Jardins de la Lune',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81zDX6N6vnL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 3,
    pages: 752,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Le livre des martyrs, tome 2 : Les portes de la maison des morts',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/LELIVREDESMARTYRST2_CVR-scaled.jpg',
    readDate: '',
    rating: 5,
    pages: 976,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Le Livre des Martyrs, tome 3 : Les Souvenirs de la Glace',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81J7joBVIVL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 5,
    pages: 1056,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: 'Le Livre des martyrs, tome 4 : La Maison des chaînes',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81rNfvdkuOL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 3.5,
    pages: 1072,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: 'Le Livre des martyrs, tome 5 : Les Marées de minuit',
    author: 'Steven Erikson',
    coverUrl: '/books_pictures/81tv6LF9r1L._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 4,
    pages: 1136,
    genre: 'Fantasy',
    saga: 'Le Livre des Martyrs',
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "Wax et Wayne, tome 1 : L'alliage de la justice",
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/libriweb.jpg',
    readDate: '',
    rating: 4,
    pages: 416,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: 'Wax et Wayne, tome 2 : Jeux de masques',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/71xSe0x62eL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 4.5,
    pages: 448,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: 'Wax et Wayne, tome 3 : Les bracelets des larmes',
    author: 'Brandon Sanderson',
    coverUrl: '/books_pictures/71mv6VCdFbL.jpg',
    readDate: '',
    rating: 4.5,
    pages: 480,
    genre: 'Fantasy',
    saga: 'Wax et Wayne',
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "Les Princes d'Ambre - Cycle 1",
    author: 'Roger Zelazny',
    coverUrl: '/books_pictures/81q5MDrRD5L._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 2,
    pages: 640,
    genre: 'Fantasy',
    saga: "Les Princes d'Ambre",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 1 : Le trône du dragon",
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/larcane_des_epees_tome_1_le_trone_du_dragon-1161-264-432.jpg',
    readDate: '',
    rating: 3.5,
    pages: 768,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 2 : Le roi de l'orage",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266170147-475x500-1.webp',
    readDate: '',
    rating: 4,
    pages: 800,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 3 : La maison de l'ancêtre",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266169660_1_75.jpg',
    readDate: '',
    rating: 4.5,
    pages: 832,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 3,
    readTimes: 1,
  },
  {
    title: "L'arcane des épées, tome 4 : La pierre de l'adieu",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/71am-Hy+7QL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 4,
    pages: 848,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 4,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 5 : Le livre du nécromant",
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/CVT_cvt_LArcane-des-Epees-T5-le-Livre-du-Necromant_8686.webp',
    readDate: '',
    rating: 3.5,
    pages: 864,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 5,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 6 : Le cri de Camaris",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/libriweb (1).jpg',
    readDate: '',
    rating: 4.5,
    pages: 880,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 6,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 7 : L'ombre de la roue",
    author: 'Tad Williams',
    coverUrl: '/books_pictures/9782266196796-475x500-1.webp',
    readDate: '',
    rating: 4.5,
    pages: 896,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 7,
    readTimes: 1,
  },
  {
    title: "L'Arcane des Epées, tome 8 : La tour de l'ange vert",
    author: 'Tad Williams',
    coverUrl:
      '/books_pictures/CVT_cvt_LArcane-des-Epees-T8-la-Tour-de-lAnge-Vert_1326.webp',
    readDate: '',
    rating: 3.5,
    pages: 912,
    genre: 'Fantasy',
    saga: "L'Arcane des Epées",
    sagaOrder: 8,
    readTimes: 1,
  },
  {
    title: "Une couronne d'épines, tome 1 : Tuer la reine",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/71lmtW2SGuL._AC_UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 2.5,
    pages: 480,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 1,
    readTimes: 1,
  },
  {
    title: "Une couronne d'épines, tome 2 : Défendre le prince",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/81hqx4l8WSL._UF1000,1000_QL80_.jpg',
    readDate: '',
    rating: 2.5,
    pages: 496,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 2,
    readTimes: 1,
  },
  {
    title: "Une couronne d'épines, tome 3 : Écraser le roi",
    author: 'Jennifer Estep',
    coverUrl: '/books_pictures/81mj9OqmjiL.jpg',
    readDate: '',
    rating: 2.5,
    pages: 512,
    genre: 'Fantasy',
    saga: "Une couronne d'épines",
    sagaOrder: 3,
    readTimes: 1,
  },
];
