export interface Book {
  title: string;
  author: string;
  coverUrl: string;
  readDate: string;
  rating?: number;
  pages?: number;
  genre: string;
  saga: string;
  sagaOrder?: number;
  nbTomes?: number;
  isFinished?: boolean;
}

export const books: Book[] = [
  {
    title: "Une enfance en nORd",
    author: "Marion Cuerq",
    coverUrl: "/books_pictures/une_enfance_en_nord.webp",
    readDate: "2025-05-13",
    rating: 4.5,
    pages: 256,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Les liaisons dangereuses",
    author: "Eny Heli",
    coverUrl: "/books_pictures/les-liaisons-dangereuses-5536921.jpg",
    readDate: "2024-12-15",
    rating: 4,
    pages: 400,
    genre: "Classic",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "En bons pères de famille",
    author: "Rose Lamy",
    coverUrl: "/books_pictures/en_bons_peres_de_famille.webp",
    readDate: "2025-05-15",
    rating: 4.5,
    pages: 194,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Où va l'argent des pauvres",
    author: "Denis Colombi",
    coverUrl: "/books_pictures/ou_va_l_argent_des_pauvres.jpg",
    readDate: "2025-01-01",
    rating: 3.5,
    pages: 352,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "L'Arnaque des nouveaux pères",
    author: "Stephane Jourdain",
    coverUrl: "/books_pictures/arnaque_des_nouveaux_peres.jpeg",
    readDate: "2024-11-11",
    rating: 4,
    pages: 184,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Les tout-petits face aux écrans",
    author: "Dr Anne-Lise Ducanda",
    coverUrl: "/books_pictures/les_tout_petit_face_aux_ecrans.jpg",
    readDate: "2023-10-16",
    rating: 4,
    pages: 288,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Les serres sous le velours noir",
    author: "Charlène Ferlay",
    coverUrl: "/books_pictures/les_serres_sous_le_velours_noir.jpg",
    readDate: "2025-01-14",
    rating: 4,
    pages: 312,
    genre: "Fiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Ne tirez pas sur l'oiseau moqueur",
    author: "Harper Lee",
    coverUrl: "/books_pictures/ne_tirez_pas_sur_l_oiseau_moqueur.jpg",
    readDate: "2024-03-11",
    rating: 3,
    pages: 323,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Les Hauts de Hurlevent",
    author: "Emily Brontë",
    coverUrl: "/books_pictures/les_hauts_de_hurlevent.jpg",
    readDate: "2024-02-24",
    rating: 2.5,
    pages: 464,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Voyage au centre de la terre",
    author: "Jules Verne",
    coverUrl: "/books_pictures/voyage_au_centre_de_la_terre.jpg",
    readDate: "2024-01-10",
    rating: 4,
    pages: 240,
    genre: "Science Fiction",
    saga: "Les voyages extraordinaires",
    sagaOrder: 0,
  },
  {
    title: "Le tour du monde en 80 jours",
    author: "Jules Verne",
    coverUrl: "/books_pictures/le_tour_du_monde_80_jours.jpg",
    readDate: "2024-01-05",
    rating: 3.5,
    pages: 247,
    genre: "Science Fiction",
    saga: "Les voyages extraordinaires",
    sagaOrder: 0,
  },
  {
    title: "Vingt Mille Lieues sous les mers",
    author: "Jules Verne",
    coverUrl: "/books_pictures/20000_lieues_sous_les_mers.jpg",
    readDate: "2024-01-25",
    rating: 4.5,
    pages: 640,
    genre: "Science Fiction",
    saga: "Les voyages extraordinaires",
    sagaOrder: 0,
  },
  {
    title: "L'Île mystérieuse",
    author: "Jules Verne",
    coverUrl: "/books_pictures/l_ile_mysterieuse.webp",
    readDate: "2024-01-15",
    rating: 4,
    pages: 640,
    genre: "Science Fiction",
    saga: "Les voyages extraordinaires",
    sagaOrder: 0,
  },
  {
    title: "De la Terre à la Lune",
    author: "Jules Verne",
    coverUrl: "/books_pictures/de_la_terre_a_la_lune.jpg",
    readDate: "2024-01-08",
    rating: 3.5,
    pages: 240,
    genre: "Science Fiction",
    saga: "Les voyages extraordinaires",
    sagaOrder: 0,
  },
  {
    title: "Le Comte de Monte-Cristo",
    author: "Alexandre Dumas",
    coverUrl: "/books_pictures/le_comte_de_monte_cristo.jpg",
    readDate: "2024-10-15",
    rating: 5,
    pages: 1056,
    genre: "Classic",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    coverUrl: "/books_pictures/frankenstein.jpg",
    readDate: "2024-05-16",
    rating: 2,
    pages: 260,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Le Portrait de Dorian Gray",
    author: "Oscar Wilde",
    coverUrl: "/books_pictures/le_portrait_de_dorian_gray.jpg",
    readDate: "2024-01-07",
    rating: 3.5,
    pages: 272,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "La Ferme des animaux",
    author: "George Orwell",
    coverUrl: "/books_pictures/la_ferme_des_animaux.jpg",
    readDate: "2024-06-12",
    rating: 4,
    pages: 141,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Orgueil et Préjugés",
    author: "Jane Austen",
    coverUrl: "/books_pictures/orgueil_et_prejuges.jpg",
    readDate: "2024-01-03",
    rating: 3.5,
    pages: 279,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "1984",
    author: "George Orwell",
    coverUrl: "/books_pictures/1984.jpg",
    readDate: "2024-11-20",
    rating: 4,
    pages: 376,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Fondation",
    author: "Isaac Asimov",
    coverUrl: "/books_pictures/fondation_asimov.jpg",
    readDate: "2024-11-15",
    rating: 4,
    pages: 255,
    genre: "Science Fiction",
    saga: "Fondation",
    sagaOrder: 1,
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    coverUrl: "/books_pictures/farenheit_451.jpg",
    readDate: "2024-02-15",
    rating: 2.5,
    pages: 176,
    genre: "Science Fiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Miss Marple au club du mardi",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/miss_marple_club_du_mardi.webp",
    readDate: "2024-02-05",
    rating: 3,
    pages: 256,
    genre: "Mystery",
    saga: "Agatha Christie",
    sagaOrder: 0,
  },
  {
    title: "L'Affaire Protheroe",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/affaire_protheroe.jpg",
    readDate: "2024-01-30",
    rating: 3,
    pages: 288,
    genre: "Mystery",
    saga: "Agatha Christie",
    sagaOrder: 0,
  },
  {
    title: "Le crime de l'Orient Express",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/crime_orient_express.jpg",
    readDate: "2024-01-20",
    rating: 3.5,
    pages: 274,
    genre: "Mystery",
    saga: "Agatha Christie",
    sagaOrder: 0,
  },
  {
    title: "Mort sur le Nil",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/mort_sur_le_nil.webp",
    readDate: "2024-02-10",
    rating: 3,
    pages: 352,
    genre: "Mystery",
    saga: "Hercule Poirot",
    sagaOrder: 0,
  },
  {
    title: "Ils étaient dix",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/ils_etaient_dix.webp",
    readDate: "2024-02-19",
    rating: 5,
    pages: 264,
    genre: "Mystery",
    saga: "Agatha Christie",
    sagaOrder: 0,
  },
  {
    title: "Le Meurtre de Roger Ackroyd",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/meutre_roger_acroyd.jpg",
    readDate: "2024-02-15",
    rating: 3.5,
    pages: 288,
    genre: "Mystery",
    saga: "Agatha Christie",
    sagaOrder: 0,
  },
  {
    title: "Meurtre en Mésopotamie",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/meutre_en_mesopotamie.jpg",
    readDate: "2024-02-25",
    rating: 2.5,
    pages: 288,
    genre: "Mystery",
    saga: "Agatha Christie",
    sagaOrder: 0,
  },

  {
    title: "Cinq petits cochons",
    author: "Agatha Christie",
    coverUrl: "/books_pictures/cinq_petits_cochons.webp",
    readDate: "2024-02-10",
    rating: 3.5,
    pages: 288,
    genre: "Mystery",
    saga: "Agatha Christie",
    sagaOrder: 0,
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    coverUrl: "/books_pictures/dracula.jpg",
    readDate: "2024-03-15",
    rating: 3,
    pages: 488,
    genre: "Horror",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    coverUrl: "/books_pictures/jane_eyre.jpg",
    readDate: "2024-04-15",
    rating: 4.5,
    pages: 532,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },

  {
    title: "Une vie",
    author: "Guy de Maupassant",
    coverUrl: "/books_pictures/une_vie.jpg",
    readDate: "2024-02-20",
    rating: 1,
    pages: 272,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "La tête sur les épaules",
    author: "Henri Troyat",
    coverUrl: "/books_pictures/la_tete_sur_les_epaules.jpg",
    readDate: "2024-02-25",
    rating: 3,
    pages: 224,
    genre: "Fiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "La Nuit des temps",
    author: "René Barjavel",
    coverUrl: "/books_pictures/la_nuit_des_temps.jpg",
    readDate: "2024-03-10",
    rating: 3.5,
    pages: 320,
    genre: "Science Fiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "La Horde du Contrevent",
    author: "Alain Damasio",
    coverUrl: "/books_pictures/la_horde_du_contrevent.jpg",
    readDate: "2024-06-20",
    rating: 4.5,
    pages: 704,
    genre: "Science Fiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    coverUrl: "/books_pictures/madame-bovary.jpg",
    readDate: "2024-04-10",
    rating: 1,
    pages: 528,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Bel-Ami",
    author: "Guy de Maupassant",
    coverUrl: "/books_pictures/bel_ami.jpg",
    readDate: "2024-03-05",
    rating: 3,
    pages: 432,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Résister",
    author: "Salomé Saqué",
    coverUrl: "/books_pictures/resister.jpg",
    readDate: "2024-11-15",
    rating: 4.5,
    pages: 200,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Le coût de la virilité",
    author: "Lucile Peytavin",
    coverUrl: "/books_pictures/le_cout_de_la_virilite.webp",
    readDate: "2024-10-20",
    rating: 4,
    pages: 320,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Sois jeune et tais-toi",
    author: "Salomé Saqué",
    coverUrl: "/books_pictures/Sois-jeune-et-tais-toi.jpg",
    readDate: "2024-09-10",
    rating: 4.5,
    pages: 180,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "L'Île au trésor",
    author: "Robert Louis Stevenson",
    coverUrl: "/books_pictures/l_ile_au_tresor.jpg",
    readDate: "2024-03-20",
    rating: 2.5,
    pages: 272,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Faites-les lire !",
    author: "Michel Desmurget",
    coverUrl: "/books_pictures/faites_les_lire.jpg",
    readDate: "2023-12-10",
    rating: 3.5,
    pages: 391,
    genre: "Nonfiction",
    saga: "",
    sagaOrder: 0,
  },
  {
    title: "Candide",
    author: "Voltaire",
    coverUrl: "/books_pictures/candide.jpg",
    readDate: "2011-03-10",
    rating: 3.5,
    pages: 129,
    genre: "Classics",
    saga: "",
    sagaOrder: 0,
  },
];