import { Serie } from "./series_1";

export const series2: Serie[] = [

  {
    title: "Jessica Jones",
    director: "Melissa Rosenberg",
    actors: [
      { name: "Krysten Ritter" },
      { name: "Mike Colter" },
      { name: "Rachael Taylor" }
    ],
    coverUrl: "/series_pictures/2217403.webp",
    releaseDate: "2015-11-20",
    endDate: "2019-06-14",
    rating: 0,
    totalLength: 2340,
    genre: "Action, Crime, Drama",
    nbSeasons: 3,
    nbEpisodesTotal: 39,
    timesWatched: 1,
  },
  {
    title: "Luke Cage",
    director: "Cheo Hodari Coker",
    actors: [
      { name: "Mike Colter" },
      { name: "Mahershala Ali" },
      { name: "Simone Missick" }
    ],
    coverUrl: "/series_pictures/MV5BMTcyMzc1MjI5MF5BMl5BanBnXkFtZTgwMzE4ODY2OTE@._V1_.jpg",
    releaseDate: "2016-09-30",
    endDate: "2018-06-22",
    rating: 0,
    totalLength: 1560,
    genre: "Action, Crime, Drama",
    nbSeasons: 2,
    nbEpisodesTotal: 26,
    timesWatched: 1,
  },
  {
    title: "Iron Fist",
    director: "Scott Buck",
    actors: [
      { name: "Finn Jones" },
      { name: "Jessica Henwick" },
      { name: "Tom Pelphrey" }
    ],
    coverUrl: "/series_pictures/046195.webp",
    releaseDate: "2017-03-17",
    endDate: "2018-09-07",
    rating: 0,
    totalLength: 1380,
    genre: "Action, Adventure, Crime",
    nbSeasons: 2,
    nbEpisodesTotal: 23,
    timesWatched: 1,
  },
  {
    title: "The Defenders",
    director: "Douglas Petrie, Marco Ramirez",
    actors: [
      { name: "Charlie Cox" },
      { name: "Krysten Ritter" },
      { name: "Mike Colter" }
    ],
    coverUrl: "/series_pictures/488673.jpg",
    releaseDate: "2017-08-18",
    endDate: "2017-08-18",
    rating: 0,
    totalLength: 480,
    genre: "Action, Adventure, Crime",
    nbSeasons: 1,
    nbEpisodesTotal: 8,
    timesWatched: 2,
  },
  {
    title: "The Last of Us",
    director: "Craig Mazin, Neil Druckmann",
    actors: [
      { name: "Pedro Pascal" },
      { name: "Bella Ramsey" },
      { name: "Gabriel Luna" }
    ],
    coverUrl: "/series_pictures/MV5BYWI3ODJlMzktY2U5NC00ZjdlLWE1MGItNWQxZDk3NWNjN2RhXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2023-01-15",
    endDate: "",
    rating: 0,
    totalLength: 540,
    genre: "Action, Adventure, Drama",
    nbSeasons: 1,
    nbEpisodesTotal: 9,
    timesWatched: 1,
  },
  {
    title: "Obsession",
    director: "Morgan Lloyd Malcolm",
    actors: [
      { name: "Richard Armitage" },
      { name: "Charlie Murphy" },
      { name: "Indira Varma" }
    ],
    coverUrl: "/series_pictures/MV5BZjA4YjFkMTAtOWJkZi00MDI0LWFkZTAtMDM1YzgyOTE5YTc3XkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2023-04-13",
    endDate: "2023-04-13",
    rating: 0,
    totalLength: 240,
    genre: "Drama, Romance, Thriller",
    nbSeasons: 1,
    nbEpisodesTotal: 4,
    timesWatched: 1,
  },
  {
    title: "13 Reasons Why",
    director: "Brian Yorkey",
    actors: [
      { name: "Dylan Minnette" },
      { name: "Katherine Langford" },
      { name: "Christian Navarro" }
    ],
    coverUrl: "/series_pictures/MV5BNThjYzQ3ZjYtM2I0ZC00OGNjLTlmNGItYjE3ZWI5MWIyMWYyXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2017-03-31",
    endDate: "2020-06-05",
    rating: 0,
    totalLength: 2940,
    genre: "Drama, Mystery",
    nbSeasons: 4,
    nbEpisodesTotal: 49,
    timesWatched: 1,
  },
  {
    title: "Castle",
    director: "Andrew W. Marlowe",
    actors: [
      { name: "Nathan Fillion" },
      { name: "Stana Katic" },
      { name: "Susan Sullivan" }
    ],
    coverUrl: "/series_pictures/61H6Z0tsRUL._UF894,1000_QL80_.jpg",
    releaseDate: "2009-03-09",
    endDate: "2016-05-16",
    rating: 0,
    totalLength: 6920,
    genre: "Comedy, Crime, Drama",
    nbSeasons: 8,
    nbEpisodesTotal: 173,
    timesWatched: 20,
  },
  {
    title: "Mentalist",
    director: "Bruno Heller",
    actors: [
      { name: "Simon Baker" },
      { name: "Robin Tunney" },
      { name: "Tim Kang" }
    ],
    coverUrl: "/series_pictures/MV5BMTQ5OTgzOTczM15BMl5BanBnXkFtZTcwMDM2OTY4MQ@@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "2008-09-23",
    endDate: "2015-02-18",
    rating: 0,
    totalLength: 6040,
    genre: "Crime, Drama, Mystery",
    nbSeasons: 7,
    nbEpisodesTotal: 151,
    timesWatched: 15,
  },
  {
    title: "Brooklyn Nine-Nine",
    director: "Dan Goor, Michael Schur",
    actors: [
      { name: "Andy Samberg" },
      { name: "Stephanie Beatriz" },
      { name: "Terry Crews" }
    ],
    coverUrl: "/series_pictures/0734068.jpg",
    releaseDate: "2013-09-17",
    endDate: "2021-09-16",
    rating: 0,
    totalLength: 6120,
    genre: "Comedy, Crime",
    nbSeasons: 8,
    nbEpisodesTotal: 153,
    timesWatched: 1,
  },
  {
    title: "Cobra Kai",
    director: "Jon Hurwitz, Hayden Schlossberg",
    actors: [
      { name: "Ralph Macchio" },
      { name: "William Zabka" },
      { name: "Xolo Maridueña" }
    ],
    coverUrl: "/series_pictures/MV5BYjA3NDkwNzktNjJkYi00ODNhLWFhYzQtYzk5NjU4MDM0OWZmXkEyXkFqcGc@._V1_.jpg",
    releaseDate: "2018-05-02",
    endDate: "",
    rating: 0,
    totalLength: 3600,
    genre: "Action, Comedy, Drama",
    nbSeasons: 6,
    nbEpisodesTotal: 60,
    timesWatched: 1,
  },
  {
    title: "Montre jamais ça à personne",
    director: "Hugo Benamozig, David Caviglioli",
    actors: [
      { name: "Jérémie Elkaïm" },
      { name: "Camille Chamoux" },
      { name: "Léa Drucker" }
    ],
    coverUrl: "/series_pictures/2490457.webp",
    releaseDate: "2023-01-06",
    endDate: "",
    rating: 0,
    totalLength: 360,
    genre: "Comedy, Drama",
    nbSeasons: 1,
    nbEpisodesTotal: 6,
    timesWatched: 1,
  },
  {
    title: "Arrow",
    director: "Greg Berlanti, Marc Guggenheim",
    actors: [
      { name: "Stephen Amell" },
      { name: "Katie Cassidy" },
      { name: "David Ramsey" }
    ],
    coverUrl: "/series_pictures/arrow-affiche_hd.jpg",
    releaseDate: "2012-10-10",
    endDate: "2020-01-28",
    rating: 0,
    totalLength: 6800,
    genre: "Action, Adventure, Crime",
    nbSeasons: 8,
    nbEpisodesTotal: 170,
    timesWatched: 2,
  },
  {
    title: "The Flash",
    director: "Greg Berlanti, Andrew Kreisberg",
    actors: [
      { name: "Grant Gustin" },
      { name: "Candice Patton" },
      { name: "Danielle Panabaker" }
    ],
    coverUrl: "/series_pictures/81lGgNZx70L._UF894,1000_QL80_.jpg",
    releaseDate: "2014-10-07",
    endDate: "2023-05-24",
    rating: 0,
    totalLength: 7360,
    genre: "Action, Adventure, Drama",
    nbSeasons: 9,
    nbEpisodesTotal: 184,
    timesWatched: 1,
  },
  {
    title: "Reacher",
    director: "Nick Santora",
    actors: [
      { name: "Alan Ritchson" },
      { name: "Malcolm Goodwin" },
      { name: "Willa Fitzgerald" }
    ],
    coverUrl: "/series_pictures/5056453204200.webp",
    releaseDate: "2022-02-04",
    endDate: "",
    rating: 0,
    totalLength: 960,
    genre: "Action, Crime, Drama",
    nbSeasons: 2,
    nbEpisodesTotal: 16,
    timesWatched: 1,
  },
  {
    title: "iZombie",
    director: "Rob Thomas, Diane Ruggiero-Wright",
    actors: [
      { name: "Rose McIver" },
      { name: "Malcolm Goodwin" },
      { name: "Rahul Kohli" }
    ],
    coverUrl: "/series_pictures/61SFGl90eIL._UF894,1000_QL80_.jpg",
    releaseDate: "2015-03-17",
    endDate: "2019-08-01",
    rating: 0,
    totalLength: 4260,
    genre: "Comedy, Crime, Drama",
    nbSeasons: 5,
    nbEpisodesTotal: 71,
    timesWatched: 1,
  },
  {
    title: "La Casa de Papel",
    director: "Álex Pina",
    actors: [
      { name: "Úrsula Corberó" },
      { name: "Álvaro Morte" },
      { name: "Itziar Ituño" }
    ],
    coverUrl: "/series_pictures/1706767.jpg",
    releaseDate: "2017-05-02",
    endDate: "2021-12-03",
    rating: 0,
    totalLength: 2460,
    genre: "Action, Crime, Drama",
    nbSeasons: 5,
    nbEpisodesTotal: 41,
    timesWatched: 1,
  },
  {
    title: "Lucifer",
    director: "Tom Kapinos",
    actors: [
      { name: "Tom Ellis" },
      { name: "Lauren German" },
      { name: "Kevin Alejandro" }
    ],
    coverUrl: "/series_pictures/MV5BYzMwNzI3MWItZTIzYi00YjkxLThhOWQtYmUwYjg4NWM0ZWI1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "2016-01-25",
    endDate: "2021-09-10",
    rating: 0,
    totalLength: 5580,
    genre: "Crime, Drama, Fantasy",
    nbSeasons: 6,
    nbEpisodesTotal: 93,
    timesWatched: 2,
  },
  {
    title: "The Punisher",
    director: "Steve Lightfoot",
    actors: [
      { name: "Jon Bernthal" },
      { name: "Ebon Moss-Bachrach" },
      { name: "Ben Barnes" }
    ],
    coverUrl: "/series_pictures/313669.jpg",
    releaseDate: "2017-11-17",
    endDate: "2019-01-18",
    rating: 0,
    totalLength: 1560,
    genre: "Action, Crime, Drama",
    nbSeasons: 2,
    nbEpisodesTotal: 26,
    timesWatched: 1,
  },
  {
    title: "Rick and Morty",
    director: "Justin Roiland, Dan Harmon",
    actors: [
      { name: "Justin Roiland" },
      { name: "Chris Parnell" },
      { name: "Spencer Grammer" }
    ],
    coverUrl: "/series_pictures/MV5BZGQyZjk2MzMtMTcyNC00NGU3LTlmNjItNDExMWM4ZDFhYmQ2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    releaseDate: "2013-12-02",
    endDate: "",
    rating: 0,
    totalLength: 2130,
    genre: "Animation, Adventure, Comedy",
    nbSeasons: 7,
    nbEpisodesTotal: 71,
    timesWatched: 1,
  },
  {
    title: "Sense8",
    director: "Lana Wachowski, Lilly Wachowski",
    actors: [
      { name: "Tuppence Middleton" },
      { name: "Brian J. Smith" },
      { name: "Doona Bae" }
    ],
    coverUrl: "/series_pictures/AAAABX05v5MVbTLkzvDTsRJ1tmoZ7J4vwgiJL0YYkPP6wPjY_mxA4p6Igs-Yd6-B3OZzD_wtFWhipXfIjL2lSON0tkn9VmNysxo8CiAyqCXmIVgz0y-AV4Ak6Uy5MSErRfMwOVExRA.jpg",
    releaseDate: "2015-06-05",
    endDate: "2018-06-08",
    rating: 0,
    totalLength: 1440,
    genre: "Action, Drama, Sci-Fi",
    nbSeasons: 2,
    nbEpisodesTotal: 24,
    timesWatched: 1,
  },
  {
    title: "Suits, Avocats sur mesure",
    director: "Aaron Korsh",
    actors: [
      { name: "Gabriel Macht" },
      { name: "Patrick J. Adams" },
      { name: "Meghan Markle" }
    ],
    coverUrl: "/series_pictures/aaa_512.jpg",
    releaseDate: "2011-06-23",
    endDate: "2019-09-25",
    rating: 0,
    totalLength: 5360,
    genre: "Comedy, Drama",
    nbSeasons: 9,
    nbEpisodesTotal: 134,
    timesWatched: 3,
  },
  {
    title: "The End of the F***ing World",
    director: "Jonathan Entwistle",
    actors: [
      { name: "Alex Lawther" },
      { name: "Jessica Barden" },
      { name: "Steve Oram" }
    ],
    coverUrl: "/series_pictures/thendofthe.jpg",
    releaseDate: "2017-10-24",
    endDate: "2019-11-04",
    rating: 0,
    totalLength: 960,
    genre: "Comedy, Crime, Drama",
    nbSeasons: 2,
    nbEpisodesTotal: 16,
    timesWatched: 1,
  },
  {
    title: "Under the Dome",
    director: "Brian K. Vaughan",
    actors: [
      { name: "Mike Vogel" },
      { name: "Rachelle Lefevre" },
      { name: "Dean Norris" }
    ],
    coverUrl: "/series_pictures/51oOnLQb0iL._UF894,1000_QL80_.jpg",
    releaseDate: "2013-06-24",
    endDate: "2015-09-10",
    rating: 0,
    totalLength: 2340,
    genre: "Drama, Mystery, Sci-Fi",
    nbSeasons: 3,
    nbEpisodesTotal: 39,
    timesWatched: 1,
  }
];