import { Music } from '../../../../models/music-model';

export const musicsDrDre: Music[] = [
  // Album : 2001 (1999)
  {
    title: 'Lolo (Intro)',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 40,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'The Watcher',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 206,
    genre: 'Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Fuck You',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 205,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Still D.R.E.',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 270,
    genre: 'Hip-Hop',
    timesListened: 48,
  },
  {
    title: "Big Ego's",
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 237,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Xxplosive',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 215,
    genre: 'Hip-Hop',
    timesListened: 4,
  },
  {
    title: "What's the Difference",
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 244,
    genre: 'Hip-Hop',
    timesListened: 24,
  },
  {
    title: 'Bar One',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 51,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Light Speed',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 160,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Forgot About Dre',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 222,
    genre: 'Hip-Hop',
    timesListened: 20,
  },
  {
    title: 'The Next Episode',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 161,
    genre: 'Hip-Hop',
    timesListened: 53,
  },
  {
    title: "Let's Get High",
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 147,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Bitch Niggaz',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 253,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'The Car Bomb',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 60,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Murder Ink',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 148,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Ed-Ucation',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 92,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Some L.A. Niggaz',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 265,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Pause 4 Porno',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 92,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Housewife',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 242,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Ackrite',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 219,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Bang Bang',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 222,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'The Message',
    artist: 'Dr. Dre',
    album: '2001',
    coverUrl: '/musics_pictures/51CxkcsoefL.jpg',
    releaseDate: '1999-11-16',
    rating: 0,
    duration: 330,
    genre: 'Hip-Hop',
    timesListened: 1,
  },
];
