import { Music } from '../../../../models/music-model';

export const musicsAkon: Music[] = [
  // Album: Konvicted (2006)
  {
    title: 'Shake Down',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 232,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Blown Away',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 209,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Smack That',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 213,
    genre: 'R&B/Hip-Hop',
    timesListened: 84,
  },
  {
    title: 'I Wanna Love You',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 247,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'The Rain',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 207,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Never Took the Time',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 237,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Mama Africa',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 266,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "I Can't Wait",
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 226,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Gangsta Bop',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 246,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Tired of Runnin'",
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 273,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Once in a While',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 237,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Don't Matter",
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 293,
    genre: 'R&B/Hip-Hop',
    timesListened: 53,
  },
  {
    title: 'Sorry, Blame It On Me',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 296,
    genre: 'R&B/Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Rush',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 254,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Don't Matter (Calypso Remix)",
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 337,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Gringo',
    artist: 'Akon',
    album: 'Konvicted',
    coverUrl: '/musics_pictures/81BgwRiMlUL.jpg',
    releaseDate: '2006-11-14',
    rating: 0,
    duration: 270,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },

  // Album: Trouble (2004)
  {
    title: 'Locked Up',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 236,
    genre: 'R&B/Hip-Hop',
    timesListened: 18,
  },
  {
    title: 'Trouble Nobody',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 203,
    genre: 'R&B/Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Bananza (Belly Dancer)',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 240,
    genre: 'R&B/Hip-Hop',
    timesListened: 34,
  },
  {
    title: 'Gangsta',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 255,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Ghetto',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 235,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Pot of Gold',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 216,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Show Out',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 205,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Lonely',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 237,
    genre: 'R&B/Hip-Hop',
    timesListened: 23,
  },
  {
    title: "When the Time's Right",
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 224,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Journey',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 258,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: "Don't Let Up",
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 244,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Easy Road',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 196,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },
  {
    title: 'Locked Up (Remix)',
    artist: 'Akon',
    album: 'Trouble',
    coverUrl: '/musics_pictures/Trouble.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 230,
    genre: 'R&B/Hip-Hop',
    timesListened: 1,
  },

  // Album: Freedom (2008)
  {
    title: 'Right Now (Na Na Na)',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 242,
    genre: 'R&B/Hip-Hop',
    timesListened: 10,
  },
  {
    title: 'Beautiful',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 319,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Keep You Much Longer',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 227,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Troublemaker',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 224,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "We Don't Care",
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 214,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: "I'm So Paid",
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 253,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Holla Holla',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 232,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Against the Grain',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 243,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Be With You',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 239,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Sunny Day',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 254,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Birthmark',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 228,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Over the Edge',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 228,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Freedom',
    artist: 'Akon',
    album: 'Freedom',
    coverUrl: '/musics_pictures/811X7cNCGIL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-12-02',
    rating: 0,
    duration: 198,
    genre: 'R&B/Hip-Hop',
    timesListened: 0,
  },

  // Chanson "Dangerous" (album non spécifié dans les données)
  {
    title: 'Dangerous',
    artist: 'Akon',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'R&B/Hip-Hop',
    timesListened: 5,
  },
];
