import { Music } from '../../../../models/music-model';

export const musicsVarietyUsVarious: Music[] = [
  {
    title: 'Break the Ice',
    artist: 'Britney Spears',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 16,
  },
  {
    title: 'Yeah! (feat. Lil Jon & Ludacris)',
    artist: 'USHER',
    album: 'Confessions',
    coverUrl: '/musics_pictures/R-2306427-1275783321.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 61,
  },
  {
    title: 'Bad Romance',
    artist: 'Lady Gaga',
    album: 'The Fame Monster',
    coverUrl: '/musics_pictures/0x1900-000000-80-0-0 (2).jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 60,
  },
  {
    title: 'LoveGame',
    artist: 'Lady Gaga',
    album: 'The Fame Monster',
    coverUrl: '/musics_pictures/0x1900-000000-80-0-0 (2).jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 31,
  },
  {
    title: 'Telephone',
    artist: 'Lady Gaga',
    album: 'The Fame Monster',
    coverUrl: '/musics_pictures/0x1900-000000-80-0-0 (2).jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 29,
  },
  {
    title: 'Just Dance',
    artist: 'Lady Gaga',
    album: 'The Fame Monster',
    coverUrl: '/musics_pictures/0x1900-000000-80-0-0 (2).jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 58,
  },
  {
    title: 'Rich Girl',
    artist: 'Gwen Stefani',
    album: 'Love',
    coverUrl: '/musics_pictures/71cmU+8ypML.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 56,
  },
  {
    title: 'The Sweet Escape',
    artist: 'Gwen Stefani',
    album: 'The Sweet Escape',
    coverUrl: '/musics_pictures/71lpX4BgwVL._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 78,
  },
  {
    title: 'Hollaback Girl',
    artist: 'Gwen Stefani',
    album: 'Love',
    coverUrl: '/musics_pictures/71cmU+8ypML.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 76,
  },
  {
    title: 'What You Waiting For?',
    artist: 'Gwen Stefani',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'Luxurious',
    artist: 'Gwen Stefani',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 2,
  },
  {
    title: 'I Like To Move It',
    artist: 'will.i.am',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 53,
  },
  {
    title: "Don't Matter",
    artist: 'Akon',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 53,
  },
  {
    title: 'TiK ToK',
    artist: 'Kesha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 48,
  },
  {
    title: 'Blah Blah Blah (feat. 3OH!3)',
    artist: 'Kesha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 15,
  },
  {
    title: 'Your Love Is My Drug',
    artist: 'Kesha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 28,
  },
  {
    title: 'We Will Rock You',
    artist: 'Queen',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 48,
  },
  {
    title: 'Pump It',
    artist: 'Black Eyed Peas',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 44,
  },
  {
    title: 'Temperature',
    artist: 'Sean Paul',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 43,
  },
  {
    title: 'Paparazzi',
    artist: 'Lady Gaga',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 42,
  },
  {
    title: 'What Goes Around.../...Comes Around (Interlude)',
    artist: 'Justin Timberlake',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 41,
  },
  {
    title: 'Poker Face',
    artist: 'Lady Gaga',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 41,
  },

  {
    title: 'The Magic Key',
    artist: 'One-T',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 41,
  },
  {
    title: 'Right Round',
    artist: 'Flo Rida',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 41,
  },
  {
    title: "Hips Don't Lie (feat. Wyclef Jean)",
    artist: 'Shakira',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 40,
  },
  {
    title: "Let's Get Loud",
    artist: 'Jennifer Lopez',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 39,
  },
  {
    title: 'Girlfriend',
    artist: 'Avril Lavigne',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 37,
  },

  {
    title: 'Rock This Party (Everybody Dance Now)',
    artist: 'Bob Sinclar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 36,
  },
  {
    title: 'Who Let The Dogs Out',
    artist: 'Baha Men',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 34,
  },
  {
    title: 'Bananza (Belly Dancer)',
    artist: 'Akon',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 34,
  },
  {
    title: 'Trouble Nobody',
    artist: 'Akon',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: 'Locked Up',
    artist: 'Akon',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 18,
  },
  {
    title: 'Lonely',
    artist: 'Akon',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 23,
  },
  {
    title: 'Sorry, Blame It On Me',
    artist: 'Akon',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 22,
  },
  {
    title: 'Hey Ya!',
    artist: 'Outkast',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 25,
  },
  {
    title: 'Promiscuous',
    artist: 'Nelly Furtado',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 23,
  },
  {
    title: 'Run the World (Girls)',
    artist: 'Beyoncé',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 22,
  },

  {
    title: 'Crazy In Love (feat. Jay-Z)',
    artist: 'Beyoncé',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 21,
  },
  {
    title: 'The Final Countdown',
    artist: 'Europe',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 20,
  },
  {
    title: 'You Give Love A Bad Name',
    artist: 'Bon Jovi',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 20,
  },
  {
    title: 'My Boo',
    artist: 'USHER',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 20,
  },
  {
    title: 'Uptown Girl',
    artist: 'Billy Joel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'You Rock My World',
    artist: 'Michael Jackson',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
  {
    title: 'Like a Boy',
    artist: 'Ciara',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 19,
  },
  {
    title: 'Rock This Party - Everybody Dance Now',
    artist: 'Bob Sinclar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 33,
  },
  {
    title: 'When I Grow Up',
    artist: 'The Pussycat Dolls',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 32,
  },
  {
    title: 'Get Busy',
    artist: 'Sean Paul',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 31,
  },
  {
    title: 'Cotton Eye Joe',
    artist: 'Rednex',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 28,
  },
  {
    title: 'Me & U',
    artist: 'Cassie',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 27,
  },
  {
    title: "Can't Hold Us (feat. Ray Dalton)",
    artist: 'Macklemore & Ryan Lewis',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 26,
  },
  {
    title: 'Empire State Of Mind',
    artist: 'JAY-Z',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 26,
  },
  {
    title: 'Jenny from the Block',
    artist: 'Jennifer Lopez',
    album: 'Jenny from the Block',
    coverUrl: '/musics_pictures/Jenny_from_the_Block.png',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 82,
  },
  {
    title: 'Low (feat. T-Pain)',
    artist: 'Flo Rida',
    album: 'Mail on Sunday',
    coverUrl: '/musics_pictures/61gXJHD8Y4L._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 76,
  },
  {
    title: 'Super Bass',
    artist: 'Nicki Minaj',
    album: 'Pink Friday',
    coverUrl: '/musics_pictures/Nicki-Minaj-Pink-Friday.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 74,
  },
  {
    title: "Who's That Girl?",
    artist: 'Eve',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 30,
  },
  {
    title: 'Let Me Blow Ya Mind',
    artist: 'Eve',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 29,
  },
  {
    title: 'Homeless',
    artist: 'Marina Kaye',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 18,
  },
  {
    title: "Can't Hold Us (feat. Ray Dalton)",
    artist: 'Macklemore',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 17,
  },
  {
    title: 'Hey Mama',
    artist: 'Black Eyed Peas',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 16,
  },
  {
    title: 'Wannabe',
    artist: 'Spice Girls',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 15,
  },
  {
    title: 'Bring Me To Life',
    artist: 'Evanescence',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 15,
  },
  {
    title: 'Always On Time',
    artist: 'Ja Rule',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'Eye of the Tiger',
    artist: 'Survivor',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'End Of The Road',
    artist: 'Boyz II Men',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'Sweet Dreams (Are Made of This) - Remastered',
    artist: 'Eurythmics',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: 'Umbrella',
    artist: 'Rihanna',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: 'Single Ladies (Put a Ring on It)',
    artist: 'Beyoncé',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
  {
    title: 'Every Breath You Take',
    artist: 'The Police',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
  {
    title: "If I Ain't Got You",
    artist: 'Alicia Keys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: 'No One',
    artist: 'Alicia Keys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: 'Girl on Fire',
    artist: 'Alicia Keys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 47,
  },
  {
    title: 'Toxic',
    artist: 'Britney Spears',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: 'Cry Me a River',
    artist: 'Justin Timberlake',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: "Don't Stop Me Now",
    artist: 'Queen',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },

  {
    title: 'I Only Have Eyes For You',
    artist: 'Boyz II Men',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'Summer Jam 2003 - Remix',
    artist: 'The Underdog Project',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 8,
  },
];
