import { Music } from '../../../../models/music-model';

export const musicsEminem2: Music[] = [
  // Album : Relapse (2009) - Eminem
  {
    title: 'Dr. West (skit)',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 89,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: '3 a.m.',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 319,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'My Mom',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 319,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Insane',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 181,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bagpipes From Baghdad',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 283,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Hello',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 248,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Tonya (skit)',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 42,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Same Song & Dance',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 246,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'We Made You',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 270,
    genre: 'Hip-Hop',
    timesListened: 29,
  },
  {
    title: 'Medicine Ball',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 237,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Paul (skit)',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 19,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Stay Wide Awake',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 319,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: "Old Time's Sake",
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 278,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Must Be the Ganja',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 242,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Mr. Mathers (skit)',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 42,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Déjà Vu',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 283,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Beautiful',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 392,
    genre: 'Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Crack a Bottle',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 297,
    genre: 'Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Steve berman (skit)',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 89,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Underground',
    artist: 'Eminem',
    album: 'Relapse',
    coverUrl: '/musics_pictures/81ba5sXLvOL._UF894,1000_QL80_.jpg',
    releaseDate: '2009-05-15',
    rating: 0,
    duration: 371,
    genre: 'Hip-Hop',
    timesListened: 0,
  },

  // Album : Recovery (2010) - Eminem
  {
    title: 'Cold Wind Blows',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 303,
    genre: 'Hip-Hop',
    timesListened: 3,
  },
  {
    title: "Talkin' 2 Myself",
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 300,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'On Fire',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 213,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: "Won't Back Down",
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 265,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'W.T.P.',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 238,
    genre: 'Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Going Through Changes',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 298,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Not Afraid',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 248,
    genre: 'Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Seduction',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 275,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'No Love',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 299,
    genre: 'Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Space Bound',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 278,
    genre: 'Hip-Hop',
    timesListened: 24,
  },
  {
    title: 'Cinderella Man',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 279,
    genre: 'Hip-Hop',
    timesListened: 7,
  },
  {
    title: '25 to Life',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 241,
    genre: 'Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'So Bad',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 325,
    genre: 'Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Almost Famous',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 292,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Love the Way You Lie',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 263,
    genre: 'Hip-Hop',
    timesListened: 25,
  },
  {
    title: "You're Never Over",
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 305,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Untitled',
    artist: 'Eminem',
    album: 'Recovery',
    coverUrl: '/musics_pictures/61fXEwg-lAL.jpg',
    releaseDate: '2010-06-18',
    rating: 0,
    duration: 194,
    genre: 'Hip-Hop',
    timesListened: 0,
  },

  // Album : The Marshall Mathers LP 2 (2013) - Eminem
  {
    title: 'Bad Guy',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 434,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Parking Lot (skit)',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 55,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Rhyme or Reason',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 301,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'So Much Better',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 261,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Survival',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 272,
    genre: 'Hip-Hop',
    timesListened: 14,
  },
  {
    title: 'Legacy',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 296,
    genre: 'Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Asshole',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 288,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Berzerk',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 238,
    genre: 'Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Rap God',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 363,
    genre: 'Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Brainless',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 286,
    genre: 'Hip-Hop',
    timesListened: 7,
  },
  {
    title: 'Stronger Than I Was',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 336,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'The Monster',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 250,
    genre: 'Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'So Far...',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 317,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Love Game',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 296,
    genre: 'Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Headlights',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 343,
    genre: 'Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Evil Twin',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP 2',
    coverUrl: '/musics_pictures/81RhoiUQbfL.jpg',
    releaseDate: '2013-11-05',
    rating: 0,
    duration: 356,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
];
