import { Music } from '../../../../models/music-model';

export const musicsMichaelJackson: Music[] = [
  {
    title: 'You Rock My World',
    artist: 'Michael Jackson',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 50,
  },
  {
    title: 'Smooth Criminal',
    artist: 'Michael Jackson',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 100,
  },
  {
    title: 'Beat It',
    artist: 'Michael Jackson',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 100,
  },
  {
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 200,
  },
  {
    title: 'Thriller',
    artist: 'Michael Jackson',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 100,
  },
  {
    title: 'Bad - 2012 Remaster',
    artist: 'Michael Jackson',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 80,
  },
];
