import { Music } from '../../../../models/music-model';

export const musicsRapUsVarious: Music[] = [
  {
    title: 'Party Up',
    artist: 'DMX',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 80,
  },
  {
    title: 'Hey Sexy Lady',
    artist: 'Shaggy',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'Angel',
    artist: 'Shaggy',
    album: 'Hot Shot',
    coverUrl: '/musics_pictures/71XAKy9eSfL._UF1000,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Reggae',
    timesListened: 250,
  },
  {
    title: "It Wasn't Me",
    artist: 'Shaggy',
    album: 'Hot Shot',
    coverUrl: '/musics_pictures/71XAKy9eSfL._UF1000,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Reggae',
    timesListened: 250,
  },
  {
    title: 'Live Your Life',
    artist: 'T.I.',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'My Love (feat. T.I.)',
    artist: 'Justin Timberlake',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 250,
  },
  {
    title: 'Whatever You Like',
    artist: 'T.I.',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 200,
  },
  {
    title: 'Ms. Jackson',
    artist: 'Outkast',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: "Drop It Like It's Hot",
    artist: 'Snoop Dogg',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 80,
  },
  {
    title: 'Hate It Or Love It',
    artist: 'The Game',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 80,
  },
  {
    title: 'Stronger',
    artist: 'Kanye West',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'DNA.',
    artist: 'Kendrick Lamar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 30,
  },
  {
    title: 'King Kunta',
    artist: 'Kendrick Lamar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 80,
  },
  {
    title: 'Crank That (Soulja Boy)',
    artist: 'Soulja Boy',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'Family Affair',
    artist: 'Mary J. Blige',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 80,
  },
  {
    title: 'How We Do',
    artist: 'The Game',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 50,
  },
  {
    title: 'Bump, Bump, Bump (feat. P. Diddy)',
    artist: 'B2K',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'You Be Killin Em',
    artist: 'Fabolous',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 180,
  },
  {
    title: 'Disco Inferno',
    artist: '50 Cent',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 100,
  },
  {
    title: 'Candy Shop',
    artist: '50 Cent',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 200,
  },
  {
    title: 'In Da Club',
    artist: '50 Cent',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 100,
  },
  {
    title: '21 Questions',
    artist: '50 Cent',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'P.I.M.P.',
    artist: '50 Cent',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'Snitch',
    artist: 'Obie Trice',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 50,
  },
  {
    title: 'Bar One',
    artist: 'Dr. Dre',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Super Bass',
    artist: 'Nicki Minaj',
    album: 'Pink Friday',
    coverUrl: '/musics_pictures/Nicki-Minaj-Pink-Friday.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 74,
  },
  {
    title: 'Barbie World (with Aqua) [From Barbie The Album]',
    artist: 'Nicki Minaj',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Moment 4 Life',
    artist: 'Nicki Minaj',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 24,
  },
];
