import { Music } from '../../../../models/music-model';

export const musicsEminem3: Music[] = [
  // Album : Revival (2017) - Eminem
  {
    title: 'Walk on Water',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 304,
    genre: 'Hip-Hop',
    timesListened: 33,
  },
  {
    title: 'Believe',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 315,
    genre: 'Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Chloraseptic',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 301,
    genre: 'Hip-Hop',
    timesListened: 13,
  },
  {
    title: 'Untouchable',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 370,
    genre: 'Hip-Hop',
    timesListened: 17,
  },
  {
    title: 'River',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 221,
    genre: 'Hip-Hop',
    timesListened: 29,
  },
  {
    title: 'Remind Me (intro)',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 26,
    genre: 'Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Remind Me',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 225,
    genre: 'Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Revival (interlude)',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 51,
    genre: 'Hip-Hop',
    timesListened: 25,
  },
  {
    title: 'Like Home',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 245,
    genre: 'Hip-Hop',
    timesListened: 43,
  },
  {
    title: 'Bad Husband',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 287,
    genre: 'Hip-Hop',
    timesListened: 47,
  },
  {
    title: 'Tragic Endings',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 252,
    genre: 'Hip-Hop',
    timesListened: 42,
  },
  {
    title: 'Framed',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 253,
    genre: 'Hip-Hop',
    timesListened: 31,
  },
  {
    title: 'Nowhere Fast',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 264,
    genre: 'Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Heat',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 250,
    genre: 'Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Offended',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 320,
    genre: 'Hip-Hop',
    timesListened: 21,
  },
  {
    title: 'Need Me',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 265,
    genre: 'Hip-Hop',
    timesListened: 38,
  },
  {
    title: 'In Your Head',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 182,
    genre: 'Hip-Hop',
    timesListened: 22,
  },
  {
    title: 'Castle',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 254,
    genre: 'Hip-Hop',
    timesListened: 23,
  },
  {
    title: 'Arose',
    artist: 'Eminem',
    album: 'Revival',
    coverUrl: '/musics_pictures/71sXWR7fziL.jpg',
    releaseDate: '2017-12-15',
    rating: 0,
    duration: 274,
    genre: 'Hip-Hop',
    timesListened: 16,
  },

  // Album : Kamikaze (2018) - Eminem
  {
    title: 'The Ringer',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 337,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Greatest',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 226,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Lucky You',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 246,
    genre: 'Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Paul (skit)',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 35,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Normal',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 222,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Em Calls Paul (skit)',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 50,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Stepping Stone',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 309,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Not Alike',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 288,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Kamikaze',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 216,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Fall',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 262,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Nice Guy',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 150,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Good Guy',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 142,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Venom',
    artist: 'Eminem',
    album: 'Kamikaze',
    coverUrl: '/musics_pictures/91AMfe72gCL.jpg',
    releaseDate: '2018-08-31',
    rating: 0,
    duration: 269,
    genre: 'Hip-Hop',
    timesListened: 0,
  },

  // Album : Music to Be Murdered By (2020) - Eminem
  {
    title: 'Premonition (Intro)',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 174,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Unaccommodating',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 217,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: "You Gon' Learn",
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 235,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Alfred (interlude)',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 30,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Those Kinda Nights',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 178,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'In Too Deep',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 195,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Godzilla',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 211,
    genre: 'Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Darkness',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 337,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Leaving Heaven',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 266,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Yah Yah',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 287,
    genre: 'Hip-Hop',
    timesListened: 12,
  },
  {
    title: 'Stepdad (Intro)',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 15,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Stepdad',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 213,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Marsh',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 201,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Never Love Again',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 178,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Little Engine',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 177,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Lock It Up',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 170,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Farewell',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 248,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'No Regrets',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 201,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'I Will',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 303,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Alfred (Outro)',
    artist: 'Eminem',
    album: 'Music to Be Murdered By',
    coverUrl: '/musics_pictures/Eminem_-_Music_to_Be_Murdered_By.png',
    releaseDate: '2020-01-17',
    rating: 0,
    duration: 39,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
];
