import { Music } from '../../../../models/music-model';

export const musicsGwenStefani: Music[] = [
  {
    title: 'Rich Girl',
    artist: 'Gwen Stefani',
    album: 'Love',
    coverUrl: '/musics_pictures/71cmU+8ypML.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 56,
  },
  {
    title: 'The Sweet Escape',
    artist: 'Gwen Stefani',
    album: 'The Sweet Escape',
    coverUrl: '/musics_pictures/71lpX4BgwVL._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 78,
  },
  {
    title: 'Hollaback Girl',
    artist: 'Gwen Stefani',
    album: 'Love',
    coverUrl: '/musics_pictures/71cmU+8ypML.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 76,
  },
  {
    title: 'What You Waiting For?',
    artist: 'Gwen Stefani',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'Luxurious',
    artist: 'Gwen Stefani',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 2,
  },
];
