import { Music } from '../../../../models/music-model';

export const musicsKesha: Music[] = [
  // Album: Animal (2010)
  {
    title: 'Your Love Is My Drug',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 187,
    genre: 'Pop',
    timesListened: 150,
  },
  {
    title: 'Tik Tok',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 199,
    genre: 'Pop',
    timesListened: 200,
  },
  {
    title: 'Take It Off',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 215,
    genre: 'Pop',
    timesListened: 20,
  },
  {
    title: 'Kiss N Tell',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 207,
    genre: 'Pop',
    timesListened: 30,
  },
  {
    title: 'Stephen',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 212,
    genre: 'Pop',
    timesListened: 20,
  },
  {
    title: 'Blah Blah Blah (feat. 3OH!3)',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 172,
    genre: 'Pop',
    timesListened: 120,
  },
  {
    title: 'Hungover',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 232,
    genre: 'Pop',
    timesListened: 10,
  },
  {
    title: "Party at a Rich Dude's House",
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 175,
    genre: 'Pop',
    timesListened: 1,
  },
  {
    title: 'Backstabber',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 186,
    genre: 'Pop',
    timesListened: 1,
  },
  {
    title: 'Blind',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 197,
    genre: 'Pop',
    timesListened: 1,
  },
  {
    title: 'Dinosaur',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 174,
    genre: 'Pop',
    timesListened: 1,
  },
  {
    title: 'Dancing with Tears in My Eyes',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 209,
    genre: 'Pop',
    timesListened: 1,
  },
  {
    title: 'Boots & Boys',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 176,
    genre: 'Pop',
    timesListened: 1,
  },
  {
    title: 'Animal',
    artist: 'Kesha',
    album: 'Animal',
    coverUrl: '/musics_pictures/61CUCJsRevL._UF894,1000_QL80_.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 237,
    genre: 'Pop',
    timesListened: 10,
  },

  // Autres
  {
    title: 'Die Young',
    artist: 'Kesha',
    album: 'Warrior',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-12-04',
    rating: 0,
    duration: 180,
    genre: 'Pop',
    timesListened: 9,
  },
];
