import { Music } from '../../../../models/music-model';

export const musicsVarietyUsVarious: Music[] = [
  {
    title: 'I Like To Move It',
    artist: 'will.i.am',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 53,
  },
  {
    title: 'We Will Rock You',
    artist: 'Queen',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 48,
  },
  {
    title: 'Temperature',
    artist: 'Sean Paul',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 43,
  },
  {
    title: 'What Goes Around.../...Comes Around (Interlude)',
    artist: 'Justin Timberlake',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 41,
  },
  {
    title: 'The Magic Key',
    artist: 'One-T',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 41,
  },
  {
    title: 'Right Round',
    artist: 'Flo Rida',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 41,
  },
  {
    title: "Hips Don't Lie (feat. Wyclef Jean)",
    artist: 'Shakira',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 40,
  },
  {
    title: "Let's Get Loud",
    artist: 'Jennifer Lopez',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 39,
  },
  {
    title: 'Girlfriend',
    artist: 'Avril Lavigne',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 37,
  },
  {
    title: 'Complicated',
    artist: 'Avril Lavigne',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 4,
  },

  {
    title: 'Who Let The Dogs Out',
    artist: 'Baha Men',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 34,
  },
  {
    title: 'Hey Ya!',
    artist: 'Outkast',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 25,
  },
  {
    title: 'Promiscuous',
    artist: 'Nelly Furtado',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 23,
  },
  {
    title: 'The Final Countdown',
    artist: 'Europe',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 20,
  },
  {
    title: 'You Give Love A Bad Name',
    artist: 'Bon Jovi',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 20,
  },
  {
    title: 'Uptown Girl',
    artist: 'Billy Joel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'Like a Boy',
    artist: 'Ciara',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 19,
  },
  {
    title: 'When I Grow Up',
    artist: 'The Pussycat Dolls',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 32,
  },
  {
    title: 'Get Busy',
    artist: 'Sean Paul',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 31,
  },
  {
    title: 'Cotton Eye Joe',
    artist: 'Rednex',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 28,
  },
  {
    title: 'Me & U',
    artist: 'Cassie',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 27,
  },
  {
    title: "Can't Hold Us (feat. Ray Dalton)",
    artist: 'Macklemore & Ryan Lewis',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 26,
  },
  {
    title: 'Empire State Of Mind',
    artist: 'JAY-Z',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 26,
  },
  {
    title: 'Jenny from the Block',
    artist: 'Jennifer Lopez',
    album: 'Jenny from the Block',
    coverUrl: '/musics_pictures/Jenny_from_the_Block.png',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 82,
  },
  {
    title: 'Low (feat. T-Pain)',
    artist: 'Flo Rida',
    album: 'Mail on Sunday',
    coverUrl: '/musics_pictures/61gXJHD8Y4L._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 76,
  },
  {
    title: 'Super Bass',
    artist: 'Nicki Minaj',
    album: 'Pink Friday',
    coverUrl: '/musics_pictures/Nicki-Minaj-Pink-Friday.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 74,
  },
  {
    title: "Who's That Girl?",
    artist: 'Eve',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 30,
  },
  {
    title: 'Let Me Blow Ya Mind',
    artist: 'Eve',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 29,
  },
  {
    title: 'Homeless',
    artist: 'Marina Kaye',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 18,
  },
  {
    title: "Can't Hold Us (feat. Ray Dalton)",
    artist: 'Macklemore',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 17,
  },
  {
    title: 'Wannabe',
    artist: 'Spice Girls',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 15,
  },
  {
    title: 'Bring Me To Life',
    artist: 'Evanescence',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 15,
  },
  {
    title: 'Always On Time',
    artist: 'Ja Rule',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'Eye of the Tiger',
    artist: 'Survivor',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'End Of The Road',
    artist: 'Boyz II Men',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'Sweet Dreams (Are Made of This) - Remastered',
    artist: 'Eurythmics',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: 'Umbrella',
    artist: 'Rihanna',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: 'Every Breath You Take',
    artist: 'The Police',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
  {
    title: "If I Ain't Got You",
    artist: 'Alicia Keys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: 'No One',
    artist: 'Alicia Keys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: 'Girl on Fire',
    artist: 'Alicia Keys',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 47,
  },
  {
    title: 'Cry Me a River',
    artist: 'Justin Timberlake',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: "Don't Stop Me Now",
    artist: 'Queen',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },

  {
    title: 'I Only Have Eyes For You',
    artist: 'Boyz II Men',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 14,
  },
  {
    title: 'Summer Jam 2003 - Remix',
    artist: 'The Underdog Project',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 8,
  },
  {
    title: 'Sweet Dreams (Are Made of This) - 2005 Remaster',
    artist: 'Eurythmics',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 10,
  },
  {
    title: 'thank u, next',
    artist: 'Ariana Grande',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 10,
  },
  {
    title: 'Beautiful Girls',
    artist: 'Sean Kingston',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 10,
  },
  {
    title: 'Paper Planes',
    artist: 'M.I.A.',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 9,
  },
  {
    title: 'American Boy',
    artist: 'Estelle',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 9,
  },
  {
    title: 'Starships',
    artist: 'Nicki Minaj',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 9,
  },
  {
    title: 'Rude Boy',
    artist: 'Rihanna',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 8,
  },
  {
    title: 'Whenever, Wherever',
    artist: 'Shakira',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 8,
  },
  {
    title: 'SexyBack (feat. Timbaland)',
    artist: 'Justin Timberlake',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'What About Us',
    artist: 'P!nk',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Kiss Kiss (feat. T-Pain)',
    artist: 'Chris Brown',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Call Me Maybe',
    artist: 'Carly Rae Jepsen',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Buttons',
    artist: 'The Pussycat Dolls',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Anyone Who Knows What Love Is (feat. Amber Riley)',
    artist: 'Boyz II Men',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'No One Else Comes Close',
    artist: 'Joe',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Numb',
    artist: 'Linkin Park',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: '7 rings',
    artist: 'Ariana Grande',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Macarena',
    artist: 'Los Del Mar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 7,
  },
  {
    title: 'Crazy',
    artist: 'Gnarls Barkley',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'Swish Swish',
    artist: 'Katy Perry',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'Take on Me',
    artist: 'a-ha',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'The Way I Are',
    artist: 'Timbaland',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'We Will Rock You - Remastered 2011',
    artist: 'Queen',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'Beep',
    artist: 'The Pussycat Dolls',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'Apologize',
    artist: 'Timbaland',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
  {
    title: 'Butterfly',
    artist: 'Superbus',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'So What',
    artist: 'P!nk',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Girls Just Want to Have Fun',
    artist: 'Cyndi Lauper',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'I Want To Hold Your Hand - Remastered 2015',
    artist: 'The Beatles',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Promiscuous - Radio Edit',
    artist: 'Nelly Furtado',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'I Kissed A Girl',
    artist: 'Katy Perry',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Get Lucky (Radio Edit) [feat. Pharrell Williams and Nile Rodgers]',
    artist: 'Daft Punk',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Twist And Shout - Remastered 2009',
    artist: 'The Beatles',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'This Love',
    artist: 'Maroon 5',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Pon de Replay',
    artist: 'Rihanna',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Boléro (Ravel)',
    artist: 'London Symphony Orchestra',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Scream & Shout',
    artist: 'will.i.am',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Waka Waka',
    artist: 'Shakira',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'You Will Never Find (with Cristina Bianchi)',
    artist: 'Max Lodini',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'On The Floor',
    artist: 'Jennifer Lopez',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Ebony And Ivory',
    artist: 'Paul McCartney',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Sounds Like Heaven',
    artist: 'Marina Kaye',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 5,
  },
  {
    title: 'Yesterday - Remastered 2009',
    artist: 'The Beatles',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 2,
  },
];
