import { Music } from '../../../../models/music-model';

export const musicsEminem1: Music[] = [
  // Album : The Slim Shady LP (1999) - Eminem
  {
    title: 'Lose Yourself',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 180,
    genre: 'Hip-Hop',
    timesListened: 11,
  },
  {
    title: 'Remind Me (Intro)',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 180,
    genre: 'Hip-Hop',
    timesListened: 16,
  },
  {
    title: 'Public Service Announcement (skit)',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 33,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'My Name Is',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 268,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Guilty Conscience',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 199,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Brain Damage',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 226,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Paul (skit)',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 15,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'If I Had',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 245,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: "'97 Bonnie and Clyde",
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 316,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bitch (skit)',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 19,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Role Model',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 205,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Lounge (skit)',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 46,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'My Fault',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 241,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Ken Kaniff (skit)',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 76,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Cum on Everybody',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 219,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Rock Bottom',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 214,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Just Don't Give a Fuck",
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 242,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Soap (skit)',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 34,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'As the World Turns',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 265,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: "I'm Shady",
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 211,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bad Meets Evil',
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 253,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: "Still Don't Give a Fuck",
    artist: 'Eminem',
    album: 'The Slim Shady LP',
    coverUrl: '/musics_pictures/815UbQWSslL._UF894,1000_QL80_.jpg',
    releaseDate: '1999-02-23',
    rating: 0,
    duration: 252,
    genre: 'Hip-Hop',
    timesListened: 0,
  },

  // Album : The Marshall Mathers LP (2000) - Eminem
  {
    title: 'Public Service Announcement 2000',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 25,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Kill You',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 264,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Stan',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 404,
    genre: 'Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Paul (skit)',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 11,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Who Knew',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 228,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Steve Berman (skit)',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 54,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'The Way I Am',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 290,
    genre: 'Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'The Real Slim Shady',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 284,
    genre: 'Hip-Hop',
    timesListened: 57,
  },
  {
    title: 'Remember Me?',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 218,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: "I'm Back",
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 309,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Marshall Mathers',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 320,
    genre: 'Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Ken Kaniff (skit)',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 62,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Drug Ballad',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 300,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Amityville',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 254,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Bitch Please II',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 287,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Kim',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 378,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Under the Influence',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 322,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Criminal',
    artist: 'Eminem',
    album: 'The Marshall Mathers LP',
    coverUrl: '/musics_pictures/71IkskatruL.jpg',
    releaseDate: '2000-05-23',
    rating: 0,
    duration: 320,
    genre: 'Hip-Hop',
    timesListened: 0,
  },

  // Album : The Eminem Show (2002) - Eminem
  {
    title: 'Curtains Up (skit)',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 30,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'White America',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 324,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Business',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 251,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: "Cleanin' Out My Closet",
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 298,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Square Dance',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 324,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'The Kiss (skit)',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 76,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Soldier',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 226,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Say Goodbye Hollywood',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 273,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Drips',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 285,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Without Me',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 290,
    genre: 'Hip-Hop',
    timesListened: 27,
  },
  {
    title: 'Paul Rosenberg (skit)',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 23,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Sing for the Moment',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 340,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Superman',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 350,
    genre: 'Hip-Hop',
    timesListened: 17,
  },
  {
    title: "Hailie's Song",
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 321,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Steve Berman (skit)',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 33,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'When the Music Stops',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 269,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Say What You Say',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 309,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: "'Till I Collapse",
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 297,
    genre: 'Hip-Hop',
    timesListened: 4,
  },
  {
    title: "My Dad's Gone Crazy",
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 268,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Curtains Close (skit)',
    artist: 'Eminem',
    album: 'The Eminem Show',
    coverUrl: '/musics_pictures/71n0xmxpw7L.jpg',
    releaseDate: '2002-05-26',
    rating: 0,
    duration: 60,
    genre: 'Hip-Hop',
    timesListened: 0,
  },

  // Album : Encore (2004) - Eminem
  {
    title: 'Curtains Up (skit)',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 47,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Evil Deeds',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 260,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Never Enough',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 159,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Yellow Brick Road',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 346,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Like Toy Soldiers',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 297,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mosh',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 318,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Puke',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 248,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'My 1st Single',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 303,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Paul (skit)',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 32,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Rain Man',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 314,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Big Weenie',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 267,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Em Calls Paul (skit)',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 72,
    genre: 'Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Just Lose It',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 249,
    genre: 'Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Ass Like That',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 266,
    genre: 'Hip-Hop',
    timesListened: 4,
  },
  {
    title: 'Spend Some Time',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 311,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Mockingbird',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 251,
    genre: 'Hip-Hop',
    timesListened: 30,
  },
  {
    title: 'Crazy in Love',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 242,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'One Shot 2 Shot',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 267,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Final Thought (skit)',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 30,
    genre: 'Hip-Hop',
    timesListened: 0,
  },
  {
    title: 'Encore/Curtains Down (skit)',
    artist: 'Eminem',
    album: 'Encore',
    coverUrl: '/musics_pictures/61iN2uEt2ML._UF894,1000_QL80_.jpg',
    releaseDate: '2004-11-12',
    rating: 0,
    duration: 348,
    genre: 'Hip-Hop',
    timesListened: 0,
  },

  // Autres sorties
  {
    title: 'Those Kinda Nights (feat. Ed Sheeran)',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 9,
  },
  {
    title: 'Unaccommodating (feat. Young M.A)',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Lock It Up (feat. Anderson .Paak)',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'You Gon',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 8,
  },
  {
    title: 'Go To Sleep',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 5,
  },
  {
    title: 'Higher',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 3,
  },
  {
    title: 'Beautiful Pain',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Good Guy (feat. Jessie Reyez)',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Zeus (feat. White Gold)',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Talkin',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Groundhog Day',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Desperation',
    artist: 'Eminem',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
