import { Music } from '../../../../models/music-model';

export const musicsJenaLee: Music[] = [
  // Album : Vous remercier (2009)
  {
    title: 'Je me perds',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 267,
    genre: 'Pop/R&B',
    timesListened: 50,
  },
  {
    title: 'Du style',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 197,
    genre: 'Pop/R&B',
    timesListened: 50,
  },
  {
    title: "J'aimerais tellement",
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 232,
    genre: 'Pop/R&B',
    timesListened: 50,
  },
  {
    title: 'Banalité',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 202,
    genre: 'Pop/R&B',
    timesListened: 0,
  },
  {
    title: 'Redeviens toi-même',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 221,
    genre: 'Pop/R&B',
    timesListened: 0,
  },
  {
    title: 'Je rêve en enfer',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 198,
    genre: 'Pop/R&B',
    timesListened: 80,
  },
  {
    title: 'Dépendance',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 226,
    genre: 'Pop/R&B',
    timesListened: 0,
  },
  {
    title: 'Emo/Rnb',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 209,
    genre: 'Pop/R&B',
    timesListened: 0,
  },
  {
    title: 'Je suis',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 196,
    genre: 'Pop/R&B',
    timesListened: 30,
  },
  {
    title: 'Je préfère',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 297,
    genre: 'Pop/R&B',
    timesListened: 30,
  },
  {
    title: 'Victime idéale',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 208,
    genre: 'Pop/R&B',
    timesListened: 0,
  },
  {
    title: 'Vous remercier / remerciements',
    artist: 'Jena Lee',
    album: 'Vous remercier',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2009-03-02',
    rating: 0,
    duration: 757,
    genre: 'Pop/R&B',
    timesListened: 0,
  },
];
