import { Music } from '../../../../models/music-model';

export const musicsMaxBoublil: Music[] = [
  {
    title: 'Ce soir, tu vas prendre',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 50,
  },
  {
    title: 'Une larme qui coule',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 30,
  },
  {
    title: 'Montrez les nous',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 20,
  },
  {
    title: 'Susan Boyle',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 200,
  },
  {
    title: 'Chatroulette',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 100,
  },
  {
    title: "L'Inconnue du boulevard Bessières",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 10,
  },
  {
    title: "Depuis que tu n'es plus là",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 20,
  },
  {
    title: 'Chanson raciste',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 10,
  },
  {
    title: 'Clash gentil',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 150,
  },
  {
    title: 'Joyeux Noël',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 100,
  },
  {
    title: "J'aime les moches",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 80,
  },
  {
    title: "Mon coloc'",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 80,
  },
  {
    title: "J'kiffe ton tugudu",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 0,
  },
  {
    title: 'Tous des mythos',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 0,
  },
  {
    title: 'Moyen Moyenne',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 20,
  },
  {
    title: 'Bois !',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 150,
  },
  {
    title: 'En couple',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 120,
  },
  {
    title: 'Boom Boom Boom',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 0,
  },
  {
    title: 'Exhibitiodance',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 120,
  },
  {
    title: "T'es bonne…",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 100,
  },
  {
    title: "J'entends rien !",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 100,
  },
  {
    title: 'Prête-moi ta meuf',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 20,
  },
  {
    title: 'Put Your Sex in the Air',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 0,
  },
  {
    title: 'Addict',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 0,
  },
  {
    title: "FREDDY (C'est trop gros)",
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 80,
  },
  {
    title: 'En boîte',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 0,
  },
  {
    title: 'Pâte à crêpe',
    artist: 'Max Boublil',
    album: "Max Boublil, l'album",
    coverUrl: '/musics_pictures/images.jpg',
    releaseDate: '2010-01-01',
    rating: 0,
    duration: 180,
    genre: 'Humour/Chanson française',
    timesListened: 10,
  },
];
