import { Music } from '../../../../models/music-model';

export const musicsBenabar: Music[] = [
  {
    title: 'La berceuse',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 218,
    genre: 'Variété',
    timesListened: 19,
  },
  {
    title: 'Le fou rire',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété',
    timesListened: 25,
  },
  {
    title: 'Vélo',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 37,
  },
  {
    title: 'Quatre murs et un toit',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété',
    timesListened: 41,
  },
  {
    title: 'Tu peux compter sur moi',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété',
    timesListened: 41,
  },
  {
    title: 'Coup du lapin',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
  {
    title: 'Bruxelles',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété',
    timesListened: 52,
  },
  {
    title: "Y'a une fille qu'habite chez moi",
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 54,
  },
  {
    title: 'Politiquement correct',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 12,
  },
  {
    title: 'Monospace',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété',
    timesListened: 52,
  },
  {
    title: 'Le dîner',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété',
    timesListened: 50,
  },
];
