import { Music } from '../../../../models/music-model';

export const musicsBalavoine: Music[] = [
  {
    title: 'Tous les cris les S.O.S.',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 29,
  },
  {
    title: 'Je ne suis pas un héros',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 26,
  },
  {
    title: 'Le chanteur',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 36,
  },
  {
    title: 'Mon fils ma bataille',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 60,
  },
  {
    title: "Aimer est plus fort que d'être aimé",
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 11,
  },
  {
    title: "Dieu que c'est beau",
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 21,
  },
  {
    title: "L'Aziza",
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: "La vie ne m'apprend rien",
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 20,
  },
];
