import { Music } from '../../../../models/music-model';

export const musicsFrancisCabrel: Music[] = [
  // Album : Samedi soir sur la Terre (1994)
  {
    title: 'La Corrida',
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 339,
    genre: 'Variété française',
    timesListened: 200,
  },
  {
    title: 'Assis sur le rebord du monde',
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 206,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'La Cabane du pêcheur',
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 306,
    genre: 'Variété française',
    timesListened: 30,
  },
  {
    title: 'Samedi soir sur la Terre',
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 412,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: "Je t'aimais, je t'aime, je t'aimerai",
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 276,
    genre: 'Variété française',
    timesListened: 30,
  },
  {
    title: 'Les Vidanges du diable',
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 288,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: "L'arbre va tomber",
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 330,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Octobre',
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 212,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Le Noceur',
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 413,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: "Tôt ou tard s'en aller",
    artist: 'Francis Cabrel',
    album: 'Samedi soir sur la Terre',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '1994-10-17',
    rating: 0,
    duration: 239,
    genre: 'Variété française',
    timesListened: 0,
  },

  // Autres sorties
  {
    title: 'Petite Marie',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 150,
  },
  {
    title: 'Sarbacane',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 50,
  },
  {
    title: "L'encre de tes yeux",
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 120,
  },
  {
    title: "Je l'aime à mourir",
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 150,
  },
  {
    title: 'Encore et encore',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 50,
  },
  {
    title: 'Gardien de nuit',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 30,
  },
];
