import { Music } from '../../../../models/music-model';

export const musicsBalavoine: Music[] = [
  {
    title: 'Tous les cris les S.O.S.',
    artist: 'Daniel Balavoine',
    album: "Sauver l'amour",
    coverUrl: '/musics_pictures/Sauver-l-amour.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 250,
  },
  {
    title: 'Je ne suis pas un héros',
    artist: 'Daniel Balavoine',
    album: 'Un autre monde',
    coverUrl: '/musics_pictures/61BSCldzDNL.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 250,
  },
  {
    title: 'Le chanteur',
    artist: 'Daniel Balavoine',
    album: 'Le Chanteur',
    coverUrl: '/musics_pictures/71Sa-W5yxkL._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 300,
  },
  {
    title: 'Lucie',
    artist: 'Daniel Balavoine',
    album: 'Le Chanteur',
    coverUrl: '/musics_pictures/71Sa-W5yxkL._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: 'Mon fils ma bataille',
    artist: 'Daniel Balavoine',
    album: 'Un autre monde',
    coverUrl: '/musics_pictures/61BSCldzDNL.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 300,
  },
  {
    title: "Aimer est plus fort que d'être aimé",
    artist: 'Daniel Balavoine',
    album: "Sauver l'amour",
    coverUrl: '/musics_pictures/Sauver-l-amour.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 200,
  },
  {
    title: "Dieu que c'est beau",
    artist: 'Daniel Balavoine',
    album: "Sauver l'amour",
    coverUrl: '/musics_pictures/Sauver-l-amour.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: "L'Aziza",
    artist: 'Daniel Balavoine',
    album: "Sauver l'amour",
    coverUrl: '/musics_pictures/Sauver-l-amour.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 150,
  },
  {
    title: "La vie ne m'apprend rien",
    artist: 'Daniel Balavoine',
    album: 'un autre monde',
    coverUrl: '/musics_pictures/61BSCldzDNL.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 120,
  },
  {
    title: 'Vivre ou survivre',
    artist: 'Daniel Balavoine',
    album: 'Vendeur de larmes',
    coverUrl: '/musics_pictures/71wIFtZvXnL._UF894,1000_QL80_.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 120,
  },

  // Autres sorties
  {
    title: 'Quand on arrive en ville - Remastered',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 150,
  },
  {
    title: 'Soulève-moi',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Petit homme mort au combat',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Rien à Foutre',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
  {
    title: 'Partir avant les miens',
    artist: 'Daniel Balavoine',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Rap/Hip-Hop',
    timesListened: 2,
  },
];
