import { Music } from '../../../../models/music-model';

export const musicsTryo: Music[] = [
  {
    title: 'Monsieur Bibendum',
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 36,
  },
  {
    title: 'Serre-moi',
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 29,
  },
  {
    title: 'Pompafric',
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 15,
  },

  {
    title: 'Pas pareil',
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 29,
  },
  {
    title: 'Toi et moi',
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 16,
  },
  {
    title: "Ce que l'on s'aime",
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 27,
  },
  {
    title: "L'air du plastique",
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 26,
  },
  {
    title: 'Sortez-les',
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 26,
  },
  {
    title: "J'ai un but",
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 23,
  },
  {
    title: 'Désolé pour hier soir',
    artist: 'Tryo',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 25,
  },
];
