import { Music } from '../../../../models/music-model';

export const musicsTryo: Music[] = [
  // Album : Mamagubida (1998)
  {
    title: "L'Hymne de nos campagnes",
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 205,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Pour un flirt avec la crise',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 227,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: "C'est du roots",
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 246,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Salut ô',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 432,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'La révolution',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 216,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Regardez-les',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 224,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: "La misère d'en face",
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 298,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Un homme qui aime les femmes',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 276,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'La main verte',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 133,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'France Télécom',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 168,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Yakamonéyé',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 459,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Les soldats de plomb',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 285,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Suprématie',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 329,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Babylone',
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 394,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: "J'ai rien prévu pour demain (+ Bonus)",
    artist: 'Tryo',
    album: 'Mamagubida',
    coverUrl: '/musics_pictures/81DsvaHY-RL._UF894,1000_QL80_.jpg',
    releaseDate: '1998-01-01',
    rating: 0,
    duration: 661,
    genre: 'Chanson française',
    timesListened: 0,
  },

  // Album : Grain de sable (2003)
  {
    title: 'G8',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 174,
    genre: 'Chanson française',
    timesListened: 3,
  },
  {
    title: 'Sortez-les',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 226,
    genre: 'Chanson française',
    timesListened: 26,
  },
  {
    title: 'Comme les journées',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 209,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Pompafric',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 230,
    genre: 'Chanson française',
    timesListened: 15,
  },
  {
    title: "Si la vie m'a mis là",
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 335,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Dans les nuages',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 260,
    genre: 'Chanson française',
    timesListened: 3,
  },
  {
    title: 'Monsieur Bibendum',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 162,
    genre: 'Chanson française',
    timesListened: 36,
  },
  {
    title: 'Serre-moi',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 230,
    genre: 'Chanson française',
    timesListened: 29,
  },
  {
    title: 'Ta réalité',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 230,
    genre: 'Chanson française',
    timesListened: 3,
  },
  {
    title: 'Récréaction',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 204,
    genre: 'Chanson française',
    timesListened: 3,
  },
  {
    title: 'Ballade en forêt',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 246,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Désolé pour hier soir',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 221,
    genre: 'Chanson française',
    timesListened: 25,
  },
  {
    title: 'Pas pareil',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 216,
    genre: 'Chanson française',
    timesListened: 29,
  },
  {
    title: 'Apocalypticodramatic',
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 232,
    genre: 'Chanson française',
    timesListened: 6,
  },
  {
    title: "J'ai un but",
    artist: 'Tryo',
    album: 'Grain de sable',
    coverUrl: '/musics_pictures/Grain-de-Sable.jpg',
    releaseDate: '2003-01-01',
    rating: 0,
    duration: 232,
    genre: 'Chanson française',
    timesListened: 23,
  },

  // Album : Ce que l'on sème (2008)
  {
    title: "Ce que l'on s'aime",
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 174,
    genre: 'Chanson française',
    timesListened: 27,
  },
  {
    title: 'Tombé Mal',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 234,
    genre: 'Chanson française',
    timesListened: 2,
  },
  {
    title: 'Jocelyne',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 167,
    genre: 'Chanson française',
    timesListened: 2,
  },
  {
    title: 'El dulce de leche',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 271,
    genre: 'Chanson française',
    timesListened: 5,
  },
  {
    title: 'Toi et moi',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 209,
    genre: 'Chanson française',
    timesListened: 16,
  },
  {
    title: "L'air du plastique",
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 213,
    genre: 'Chanson française',
    timesListened: 26,
  },
  {
    title: "Quand les hommes s'ennuient",
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 307,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Bye bye',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 177,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Marcher droit',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 186,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Mrs Roy',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 206,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Le Temps',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 306,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Abdallâh',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 210,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Une saison de trop',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 234,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: 'Travailler plus',
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 152,
    genre: 'Chanson française',
    timesListened: 0,
  },
  {
    title: "Poussière d'étoile",
    artist: 'Tryo',
    album: "Ce que l'on sème",
    coverUrl: '/musics_pictures/813yvqpVZJL._UF894,1000_QL80_.jpg',
    releaseDate: '2008-01-01',
    rating: 0,
    duration: 261,
    genre: 'Chanson française',
    timesListened: 0,
  },
];
