import { Music } from '../../../../models/music-model';

export const musicsBenabar: Music[] = [
  // Album : Reprise des négociations (2005)
  {
    title: 'Le Dîner',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 181,
    genre: 'Variété française',
    timesListened: 250,
  },
  {
    title: 'Maritie et Gilbert Carpentier',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 230,
    genre: 'Variété française',
    timesListened: 20,
  },
  {
    title: 'Quatre murs et un toit',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 211,
    genre: 'Variété française',
    timesListened: 120,
  },
  {
    title: 'Bruxelles',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 207,
    genre: 'Variété française',
    timesListened: 150,
  },
  {
    title: 'Triste compagne',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 171,
    genre: 'Variété française',
    timesListened: 10,
  },
  {
    title: 'La Berceuse',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 300,
    genre: 'Variété française',
    timesListened: 120,
  },
  {
    title: 'Les Épices du souk du Caire',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 283,
    genre: 'Variété française',
    timesListened: 10,
  },
  {
    title: "Qu'est-ce que tu voulais que je lui dise ?",
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 302,
    genre: 'Variété française',
    timesListened: 10,
  },
  {
    title: 'Le Méchant de James Bond',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 191,
    genre: 'Variété française',
    timesListened: 20,
  },
  {
    title: 'Le Fou Rire',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 216,
    genre: 'Variété française',
    timesListened: 120,
  },
  {
    title: 'Tu peux compter sur moi',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 189,
    genre: 'Variété française',
    timesListened: 120,
  },
  {
    title: 'Le Cahier de solfège',
    artist: 'Bénabar',
    album: 'Reprise des négociations',
    coverUrl: '/musics_pictures/Reprise-des-negociations.jpg',
    releaseDate: '2005-06-06',
    rating: 0,
    duration: 158,
    genre: 'Variété française',
    timesListened: 10,
  },

  // Album : Bénabar (2001)
  {
    title: 'Bon anniversaire',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 9,
  },
  {
    title: "Y'a une fille qu'habite chez moi",
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 120,
  },
  {
    title: 'Vélo',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 100,
  },
  {
    title: 'Porcelaine',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 7,
  },
  {
    title: 'À notre santé',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 10,
  },
  {
    title: 'Majorette',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 9,
  },
  {
    title: 'Couche-tard et lève-tôt',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 8,
  },
  {
    title: 'Coup du lapin',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 12,
  },
  {
    title: 'Saturne',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 9,
  },
  {
    title: 'Dramelet',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 6,
  },
  {
    title: 'Approchez',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 7,
  },
  {
    title: 'À poings fermés',
    artist: 'Bénabar',
    album: 'Bénabar',
    coverUrl: '/musics_pictures/Benabar.jpg',
    releaseDate: '2001-06-12',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 5,
  },

  // Album : Les risques du métier (2003)
  {
    title: 'Monospace',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 100,
  },
  {
    title: 'Dis-lui oui',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 50,
  },
  {
    title: 'Paresseuse',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 2,
  },
  {
    title: 'Je suis de celles',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 4,
  },
  {
    title: 'Vade retro téléphone',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: "L'Itinéraire",
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Sac à main',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'La Station Mir',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'La Coquette',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: "Les Mots d'amour",
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Monsieur René',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 2,
  },
  {
    title: 'Le zoo de Vincennes',
    artist: 'Bénabar',
    album: 'Les risques du métier',
    coverUrl: '/musics_pictures/71FHWjEBwjL._UF894,1000_QL80_.jpg',
    releaseDate: '2003-09-23',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 2,
  },

  // Album : Les bénéfices du doute (2007)
  {
    title: 'Politiquement correct',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 12,
  },
  {
    title: 'Les Râteaux',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 8,
  },
  {
    title: "L'Agneau",
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: "La phrase qu'on n'a pas dite",
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: "Alors, c'est ça ma vie !",
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Moins vite',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 7,
  },
  {
    title: 'Les Mirabelles',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 6,
  },
  {
    title: 'Perdre la raison',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 7,
  },
  {
    title: 'Faute de goût',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 5,
  },
  {
    title: 'Après de près',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Différents ?',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 7,
  },
  {
    title: 'Quelle histoire !',
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 6,
  },
  {
    title: "C'est d'l'amour",
    artist: 'Bénabar',
    album: 'Les bénéfices du doute',
    coverUrl: '/musics_pictures/61vuuImsNzL._UF894,1000_QL80_.jpg',
    releaseDate: '2007-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },

  // Album : Infréquentable (2012)
  {
    title: "L'Effet papillon",
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 20,
  },
  {
    title: 'Allez !',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Les numéros',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 2,
  },
  {
    title: 'Malgré tout',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 3,
  },
  {
    title: 'Tout vu tout lu',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 7,
  },
  {
    title: 'Pas du tout',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 4,
  },
  {
    title: "Où t'étais passé ?",
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Voir sans être vu',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 2,
  },
  {
    title: 'À la campagne',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 3,
  },
  {
    title: 'Les Reflets verts',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 2,
  },
  {
    title: "Si j'avais su",
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },
  {
    title: 'Infréquentable',
    artist: 'Bénabar',
    album: 'Infréquentable',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2012-11-19',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 0,
  },

  // Autres sorties
  {
    title: 'Les belles histoires - Radio edit',
    artist: 'Bénabar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 7,
  },
  {
    title: 'Chez les Corses',
    artist: 'Bénabar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 5,
  },
  {
    title: 'Adolescente - Version 2007',
    artist: 'Bénabar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 30,
  },
  {
    title: 'Christelle est une ordure',
    artist: 'Bénabar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 4,
  },
  {
    title: 'Tous les divorcés - Radio Edit',
    artist: 'Bénabar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 2,
  },
  {
    title:
      'Mon Coeur Fait Vroum (My Heart Goes Vroom) - From "Cars 2"/Soundtrack Version',
    artist: 'Bénabar',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Variété française',
    timesListened: 3,
  },
];
