import { Music } from '../../../../models/music-model';

export const musicsSinguila: Music[] = [
  // Album : Ghetto Compositeur (2006)
  {
    title: 'Intro',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 60,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Ghetto compositeur',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 2,
  },
  {
    title: 'Ma nature',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 8,
  },
  {
    title: 'Le misérable',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Reste Telle Que Tu Es',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Le Temps Passe Trop Vite',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Interlude Outsider',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 45,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Outsider',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Femme pressée',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: "L'Enfant Du Pays",
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Apprendre à pardonner',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: "Interlude l'imposteur",
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 45,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: "L'imposteur",
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Les amoureux du hip-hop',
    artist: 'Singuila',
    album: 'Ghetto Compositeur',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2006-06-19',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 3,
  },

  // Album : On ne vit qu'une fois (2004)
  {
    title: "C'est pour le Ä",
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Ma conscience',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: "J'avance en chantant",
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Préparatifs',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Aïcha',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Moi et mes gars',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Comme personne',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Elle me saoule',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Je doute',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Tournons la page',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: "C'est trop",
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Malédiction',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Le roi des connards',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'En bas de ma fenêtre',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Evité',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
  {
    title: 'Trop tard',
    artist: 'Singuila',
    album: "On ne vit qu'une fois",
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2004-06-29',
    rating: 0,
    duration: 180,
    genre: 'R&B/Soul',
    timesListened: 0,
  },
];
