import { Music } from '../../../../models/music-model';

export const musicsFrancisCabrel: Music[] = [
  {
    title: 'Petite Marie',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 21,
  },
  {
    title: 'La corrida',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 36,
  },
  {
    title: 'Sarbacane',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 27,
  },
  {
    title: "L'encre de tes yeux",
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 13,
  },
  {
    title: "Je l'aime à mourir",
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 31,
  },
  {
    title: 'Encore et encore',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 9,
  },
  {
    title: 'Gardien de nuit',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 8,
  },
  {
    title: 'La cabane du pêcheur',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 8,
  },
  {
    title: 'Petite Marie',
    artist: 'Francis Cabrel',
    album: 'Unknown',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2000-01-01',
    rating: 0,
    duration: 180,
    genre: 'Unknown',
    timesListened: 6,
  },
];
