import { Music } from '../../../../models/music-model';

export const musicsAngele: Music[] = [
  // Album : Brol (2018)
  {
    title: 'La Thune',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 201,
    genre: 'Pop française',
    timesListened: 30,
  },
  {
    title: 'Balance ton quoi',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 189,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Jalousie',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 225,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Tout oublier',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 202,
    genre: 'Pop française',
    timesListened: 3,
  },
  {
    title: 'La Loi de Murphy',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 195,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Nombreux',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 192,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Victime des réseaux',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 202,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Les matins',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 175,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Je veux tes yeux',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 205,
    genre: 'Pop française',
    timesListened: 3,
  },
  {
    title: 'Ta reine',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 213,
    genre: 'Pop française',
    timesListened: 16,
  },
  {
    title: 'Flemme',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 256,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Flou',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 197,
    genre: 'Pop française',
    timesListened: 2,
  },
  {
    title: 'Perdus',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 183,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Oui ou non',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 196,
    genre: 'Pop française',
    timesListened: 10,
  },
  {
    title: 'Insomnies',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 213,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Tu me regardes',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 192,
    genre: 'Pop française',
    timesListened: 4,
  },
  {
    title: "J'entends",
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 217,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Que du love',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 153,
    genre: 'Pop française',
    timesListened: 2,
  },
  {
    title: 'Ta reine (Version orchestrale)',
    artist: 'Angèle',
    album: 'Brol',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2018-10-05',
    rating: 0,
    duration: 271,
    genre: 'Pop française',
    timesListened: 0,
  },

  // Album : Nonante-cinq (2021)
  {
    title: "Bruxelles je t'aime",
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 228,
    genre: 'Pop française',
    timesListened: 5,
  },
  {
    title: 'Libre',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 164,
    genre: 'Pop française',
    timesListened: 35,
  },
  {
    title: "On s'habitue",
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 158,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Solo',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 220,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Pensées positives',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 211,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Taxi',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 258,
    genre: 'Pop française',
    timesListened: 4,
  },
  {
    title: 'Démons',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 251,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Plus de sens',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 209,
    genre: 'Pop française',
    timesListened: 3,
  },
  {
    title: 'Tempête',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 220,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Profite',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 249,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Mots justes',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 190,
    genre: 'Pop française',
    timesListened: 0,
  },
  {
    title: 'Mauvais rêves',
    artist: 'Angèle',
    album: 'Nonante-cinq',
    coverUrl: '/musics_pictures/default.jpg',
    releaseDate: '2021-12-10',
    rating: 0,
    duration: 235,
    genre: 'Pop française',
    timesListened: 0,
  },
];
