import { Book } from "./books";

export const booksSaga: Book[] = [
  {
    title: "Hunger Games",
    author: "Suzanne Collins",
    coverUrl: "/books/hunger_games_tome_1-337660-264-432.jpg",
    readDate: "2025-02-12",
    rating: 4,
    pages: 374,
    genre: "Young Adult",
    saga: "Hunger Games",
    sagaOrder: 1
  },
  {
    title: "L'Embrasement",
    author: "Suzanne Collins",
    coverUrl: "/books/hunger_games_tome_2_lembrasement-54688-264-432.jpg",
    readDate: "2025-02-14",
    rating: 4,
    pages: 391,
    genre: "Young Adult",
    saga: "Hunger Games",
    sagaOrder: 2
  },
  {
    title: "La Révolte",
    author: "Suzanne Collins",
    coverUrl: "/books/hunger_games_tome_3_la_revolte-132534-264-432.jpg",
    readDate: "2025-02-15",
    rating: 4,
    pages: 390,
    genre: "Young Adult",
    saga: "Hunger Games",
    sagaOrder: 3
  },
  {
    title: "La Ballade du serpent et de l'oiseau chanteur",
    author: "Suzanne Collins",
    coverUrl: "/books/hunger_games_tome_0_la_ballade_du_serpent_et_de_loiseau_chanteur-1349048-264-432.jpg",
    readDate: "2020-05-19",
    rating: 3.5,
    pages: 517,
    genre: "Young Adult",
    saga: "Hunger Games",
    sagaOrder: 4
  },
  {
    title: "Le grand éveil",
    author: "Sara Schneider",
    coverUrl: "/books/les_enfants_daliel_tome_1_le_grand_eveil-1301631-264-432.jpg",
    readDate: "2012-11-01",
    rating: 3.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Les enfants d'Aliel",
    sagaOrder: 1
  },
  {
    title: "Le cheval de feu",
    author: "Sara Schneider",
    coverUrl: "/books/les_enfants_daliel_tome_2_le_cheval_de_feu-1235625-264-432.jpg",
    readDate: "2012-12-01",
    rating: 3.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Les enfants d'Aliel",
    sagaOrder: 2
  },
  {
    title: "Mâchoires d'écume",
    author: "Sara Schneider",
    coverUrl: "/books/les_enfants_daliel_tome_3_machoires_decume-1347405-264-432.jpg",
    readDate: "2012-12-15",
    rating: 4,
    pages: 411,
    genre: "Fantasy",
    saga: "Les enfants d'Aliel",
    sagaOrder: 3
  },
  {
    title: "Le porteur d'espoir",
    author: "Sara Schneider",
    coverUrl: "/books/les_enfants_daliel_tome_4_le_porteur_despoir-1497527-264-432.jpg",
    readDate: "2013-01-01",
    rating: 4.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Les enfants d'Aliel",
    sagaOrder: 4
  },
  {
    title: "Ciel de cendres",
    author: "Sara Schneider",
    coverUrl: "/books/les_enfants_daliel_tome_5_ciel_de_cendres-5009301-264-432.jpg",
    readDate: "2013-01-15",
    rating: 3.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Les enfants d'Aliel",
    sagaOrder: 5
  },
  {
    title: "Harry Potter à l'école des sorciers",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_1_harry_potter_a_lecole_des_sorciers-835229-264-432.jpg",
    readDate: "2024-09-15",
    rating: 4,
    pages: 320,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 1
  },
  {
    title: "Harry Potter et la Chambre des secrets",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_2_harry_potter_et_la_chambre_des_secrets-835227-264-432.jpg",
    readDate: "2007-07-02",
    rating: 4,
    pages: 352,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 2
  },
  {
    title: "Harry Potter et le Prisonnier d'Azkaban",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_3_harry_potter_et_le_prisonnier_dazkaban-835226-264-432.jpg",
    readDate: "2007-07-03",
    rating: 4.5,
    pages: 435,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 3
  },
  {
    title: "Harry Potter et la Coupe de feu",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_4_harry_potter_et_la_coupe_de_feu-835225-264-432.jpg",
    readDate: "2007-07-04",
    rating: 5,
    pages: 734,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 4
  },
  {
    title: "Harry Potter et l'Ordre du Phénix",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_5_harry_potter_et_lordre_du_phenix-835224-264-432.jpg",
    readDate: "2007-07-05",
    rating: 4,
    pages: 912,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 5
  },
  {
    title: "Harry Potter et le Prince de sang-mêlé",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_6_harry_potter_et_le_prince_de_sang_mele-835223-264-432.jpg",
    readDate: "2007-07-06",
    rating: 5,
    pages: 652,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 6
  },
  {
    title: "Harry Potter et les Reliques de la Mort",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_7_harry_potter_et_les_reliques_de_la_mort-835220-264-432.jpg",
    readDate: "2007-07-07",
    rating: 5,
    pages: 759,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 7
  },
  {
    title: "Harry Potter et l'Enfant maudit",
    author: "J.K. Rowling",
    coverUrl: "/books/harry_potter_tome_8_enfant_maudit.jpg",
    readDate: "2016-07-31",
    rating: 3,
    pages: 330,
    genre: "Fantasy",
    saga: "Harry Potter",
    sagaOrder: 8
  },
  {
    title: "Fascination",
    author: "Stephenie Meyer",
    coverUrl: "/books/twilight_tome_1_fascination-524543-264-432.jpg",
    readDate: "2010-07-16",
    rating: 4.5,
    pages: 498,
    genre: "Young Adult",
    saga: "Twilight",
    sagaOrder: 1
  },
  {
    title: "Tentation",
    author: "Stephenie Meyer",
    coverUrl: "/books/twilight_tome_2_tentation-888-264-432.jpg",
    readDate: "2010-07-17",
    rating: 3.5,
    pages: 563,
    genre: "Young Adult",
    saga: "Twilight",
    sagaOrder: 2
  },
  {
    title: "Hésitation",
    author: "Stephenie Meyer",
    coverUrl: "/books/twilight_tome_3_hesitation-890-264-432.jpg",
    readDate: "2010-07-19",
    rating: 3.5,
    pages: 629,
    genre: "Young Adult",
    saga: "Twilight",
    sagaOrder: 3
  },
  {
    title: "Révélation",
    author: "Stephenie Meyer",
    coverUrl: "/books/twilight_tome_4_revelation-889-264-432.jpg",
    readDate: "2010-07-18",
    rating: 4.5,
    pages: 756,
    genre: "Young Adult",
    saga: "Twilight",
    sagaOrder: 4
  },
  {
    title: "Midnight Sun",
    author: "Stephenie Meyer",
    coverUrl: "/books/midnight_sun-5006281-264-432.jpg",
    readDate: "2020-08-04",
    rating: 5,
    pages: 662,
    genre: "Young Adult",
    saga: "Twilight",
    sagaOrder: 5
  },
  {
    title: "Le Voleur de foudre",
    author: "Rick Riordan",
    coverUrl: "/books/percy_jackson_tome_1_le_voleur_de_foudre-997184-264-432.jpg",
    readDate: "2010-08-15",
    rating: 3.5,
    pages: 377,
    genre: "Young Adult",
    saga: "Percy Jackson",
    sagaOrder: 1
  },
  {
    title: "La Mer des monstres",
    author: "Rick Riordan",
    coverUrl: "/books/percy_jackson_tome_2_la_mer_des_monstres-48633-264-432.jpg",
    readDate: "2010-08-20",
    rating: 3,
    pages: 279,
    genre: "Young Adult",
    saga: "Percy Jackson",
    sagaOrder: 2
  },
  {
    title: "Le Sort du titan",
    author: "Rick Riordan",
    coverUrl: "/books/percy_jackson_tome_3_le_sort_du_titan-70591-264-432.jpg",
    readDate: "2010-08-25",
    rating: 3.5,
    pages: 312,
    genre: "Young Adult",
    saga: "Percy Jackson",
    sagaOrder: 3
  },
  {
    title: "La Bataille du labyrinthe",
    author: "Rick Riordan",
    coverUrl: "/books/percy_jackson_tome_4_la_bataille_du_labyrinthe-380098-264-432.jpg",
    readDate: "2010-09-05",
    rating: 4,
    pages: 361,
    genre: "Young Adult",
    saga: "Percy Jackson",
    sagaOrder: 4
  },
  {
    title: "Le Dernier Olympien",
    author: "Rick Riordan",
    coverUrl: "/books/percy_jackson_tome_5_le_dernier_olympien-77283-264-432.jpg",
    readDate: "2010-09-15",
    rating: 4,
    pages: 381,
    genre: "Young Adult",
    saga: "Percy Jackson",
    sagaOrder: 5
  },
  {
    title: "Le Calice des dieux",
    author: "Rick Riordan",
    coverUrl: "/books/percy_jackson_tome_6_le_calice_des_dieux-5319264-264-432.jpg",
    readDate: "2023-09-26",
    rating: 2,
    pages: 288,
    genre: "Young Adult",
    saga: "Percy Jackson",
    sagaOrder: 6
  },
  {
    title: "D'un monde à l'autre",
    author: "Pierre Bottero",
    coverUrl: "/books/la_quete_dewilan_tome_1_dun_monde_a_lautre-605310-264-432.jpg",
    readDate: "2012-08-01",
    rating: 3.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 1
  },
  {
    title: "Les frontières de glace",
    author: "Pierre Bottero",
    coverUrl: "/books/la_quete_dewilan_tome_2_les_frontieres_de_glace-605311-264-432.jpg",
    readDate: "2012-08-15",
    rating: 3,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 2
  },
  {
    title: "L'île du destin",
    author: "Pierre Bottero",
    coverUrl: "/books/la_quete_dewilan_tome_3_lile_du_destin-605313-264-432.jpg",
    readDate: "2012-09-01",
    rating: 3.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 3
  },
  {
    title: "La Forêt des captifs",
    author: "Pierre Bottero",
    coverUrl: "/books/les_mondes_dewilan_tome_1_la_foret_des_captifs-686716-264-432.jpg",
    readDate: "2012-07-01",
    rating: 3.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 4
  },
  {
    title: "L'Œil d'Otolep",
    author: "Pierre Bottero",
    coverUrl: "/books/les_mondes_dewilan_tome_2_loeil_dotolep-6550-264-432.jpg",
    readDate: "2012-07-15",
    rating: 4,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 5
  },
  {
    title: "Les Tentacules du mal",
    author: "Pierre Bottero",
    coverUrl: "/books/les_mondes_dewilan_tome_3_les_tentacules_du_mal-6551-264-432.jpg",
    readDate: "2025-01-05",
    rating: 4.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 6
  },
  {
    title: "Ellana",
    author: "Pierre Bottero",
    coverUrl: "/books/le_pacte_des_marchombres_tome_1_ellana-54302-264-432.jpg",
    readDate: "2012-09-15",
    rating: 4.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 7
  },
  {
    title: "Ellana, l'Envol",
    author: "Pierre Bottero",
    coverUrl: "/books/le_pacte_des_marchombres_tome_2_ellana_lenvol-6778-264-432.jpg",
    readDate: "2012-10-01",
    rating: 4.5,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 8
  },
  {
    title: "Ellana, la Prophétie",
    author: "Pierre Bottero",
    coverUrl: "/books/le_pacte_des_marchombres_tome_3_ellana_la_prophetie-6781-264-432.jpg",
    readDate: "2012-10-15",
    rating: 5,
    pages: 411,
    genre: "Fantasy",
    saga: "Ewilan",
    sagaOrder: 9
  },
  {
    title: "Les sortceliers",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_1_les_sortceliers-2285542-264-432.jpg",
    readDate: "2012-07-31",
    rating: 4,
    pages: 501,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 1
  },
  {
    title: "Le livre interdit",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_2_le_livre_interdit-52137-264-432.jpg",
    readDate: "2012-08-01",
    rating: 4,
    pages: 502,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 2
  },
  {
    title: "Le sceptre maudit",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_3_le_sceptre_maudit-236537-264-432.jpg",
    readDate: "2012-08-02",
    rating: 4,
    pages: 503,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 3
  },
  {
    title: "Le dragon renégat",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_4_le_dragon_renegat-9381-264-432.jpg",
    readDate: "2012-08-03",
    rating: 3.5,
    pages: 507,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 4
  },
  {
    title: "Le continent interdit",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_5_le_continent_interdit-39259-264-432.jpg",
    readDate: "2012-08-04",
    rating: 5,
    pages: 506,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 5
  },
  {
    title: "Dans le piège de Magister",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_6_dans_le_piege_de_magister-100912-264-432.jpg",
    readDate: "2012-08-06",
    rating: 4,
    pages: 508,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 6
  },
  {
    title: "Tara Duncan et l'invasion fantôme",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_7_linvasion_fantome-118545-264-432.jpg",
    readDate: "2012-08-05",
    rating: 4,
    pages: 504,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 7
  },
  {
    title: "L'impératrice maléfique",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_8_limperatrice_malefique-68463-264-432.jpg",
    readDate: "2012-08-08",
    rating: 4.5,
    pages: 505,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 8
  },
  {
    title: "Tara Duncan contre la reine noire",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_9_tara_duncan_contre_la_reine_noire-233246-264-432.jpg",
    readDate: "2012-08-09",
    rating: 4.5,
    pages: 503,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 9
  },
  {
    title: "Dragons contre Démons",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_10_dragons_contre_demons-2576032-264-432.jpg",
    readDate: "2012-09-27",
    rating: 4.5,
    pages: 527,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 10
  },
  {
    title: "La Guerre des planètes",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_11_la_guerre_des_planetes-323656-264-432.jpg",
    readDate: "2013-09-19",
    rating: 4.5,
    pages: 519,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 11
  },
  {
    title: "L'Ultime Combat",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_12_lultime_combat-493535-264-432.jpg",
    readDate: "2014-09-18",
    rating: 4.5,
    pages: 518,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 12
  },
  {
    title: "Tara et Cal",
    author: "Sophie Audouin-Mamikonian",
    coverUrl: "/books/tara_duncan_tome_13_tara_et_cal-684594-264-432.jpg",
    readDate: "2015-09-20",
    rating: 3,
    pages: 520,
    genre: "Fantasy",
    saga: "Tara Duncan",
    sagaOrder: 13
  },
  {
    title: "Divergente",
    author: "Veronica Roth",
    coverUrl: "/books/divergente.jpg",
    readDate: "2025-06-25",
    rating: 3.5,
    pages: 487,
    genre: "Young Adult",
    saga: "Divergente",
    sagaOrder: 1,
  },
  {
    title: "Le Labyrinthe",
    author: "James Dashner",
    coverUrl: "/books/le_labyrinthe_tome_1.jpg",
    readDate: "2025-02-11",
    rating: 3.5,
    pages: 384,
    genre: "Young Adult",
    saga: "Le Labyrinthe",
    sagaOrder: 1,
  },
  {
    title: "Une étude en rouge",
    author: "Arthur Conan Doyle",
    coverUrl: "/books/une_etude_en_rouge-1179327-264-432.jpg",
    readDate: "2024-01-20",
    rating: 4,
    pages: 192,
    genre: "Mystery",
    saga: "Sherlock Holmes",
    sagaOrder: 1
  },
  {
    title: "Le Signe des quatre",
    author: "Arthur Conan Doyle",
    coverUrl: "/books/le_signe_des_quatre-778479-264-432.jpg",
    readDate: "2024-01-30",
    rating: 4,
    pages: 240,
    genre: "Mystery",
    saga: "Sherlock Holmes",
    sagaOrder: 2
  },
  {
    title: "Le Chien des Baskerville",
    author: "Arthur Conan Doyle",
    coverUrl: "/books/le_chien_des_baskerville-1048754-264-432.jpg",
    readDate: "2024-02-05",
    rating: 4,
    pages: 256,
    genre: "Mystery",
    saga: "Sherlock Holmes",
    sagaOrder: 3
  },
  {
    title: "La vallée de la peur",
    author: "Arthur Conan Doyle",
    coverUrl: "/books/la_vallee_de_la_peur-599895-264-432.jpg",
    readDate: "2024-01-25",
    rating: 4,
    pages: 256,
    genre: "Mystery",
    saga: "Sherlock Holmes",
    sagaOrder: 4
  },
  {
    title: "Les Mobilisés",
    author: "Margot Dessenne",
    coverUrl: "/books/absolu_tome_1_les_mobilises-5068580-264-432.jpg",
    readDate: "2024-02-26",
    rating: 4,
    pages: 540,
    genre: "Fiction",
    saga: "Absolu",
    sagaOrder: 1
  },
  {
    title: "Les Effacés",
    author: "Margot Dessenne",
    coverUrl: "/books/absolu_tome_2_les_effaces-5229178-264-432.jpg",
    readDate: "2024-02-27",
    rating: 3.5,
    pages: 608,
    genre: "Fiction",
    saga: "Absolu",
    sagaOrder: 2
  },
  {
    title: "Les Éveillés",
    author: "Margot Dessenne",
    coverUrl: "/books/absolu_tome_3_les_eveilles-5515539-264-432.jpg",
    readDate: "2024-03-15",
    rating: 4,
    pages: 600,
    genre: "Fiction",
    saga: "Absolu",
    sagaOrder: 3
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 1",
    author: "George R.R. Martin",
    coverUrl: "/books/le_trone_de_fer_integrale_tome_1-89278-264-432.jpg",
    readDate: "2024-08-15",
    rating: 3,
    pages: 835,
    genre: "Fantasy",
    saga: "Le Trône de fer",
    sagaOrder: 1
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 2",
    author: "George R.R. Martin",
    coverUrl: "/books/le_trone_de_fer_integrale_tome_2-1235271-264-432.jpg",
    readDate: "2024-10-11",
    rating: 3,
    pages: 960,
    genre: "Fantasy",
    saga: "Le Trône de fer",
    sagaOrder: 2
  },
  {
    title: "Le Trône de fer, L'Intégrale Tome 3",
    author: "George R.R. Martin",
    coverUrl: "/books/le_trone_de_fer_integrale_tome_3-4198983-264-432.jpg",
    readDate: "2024-12-04",
    rating: 3.5,
    pages: 1149,
    genre: "Fantasy",
    saga: "Le Trône de fer",
    sagaOrder: 3
  },
  {
    title: "Inside Mac: Tome 1",
    author: "Eny Heli",
    coverUrl: "/books/inside_mac_tome_1-5310515-264-432.jpg",
    readDate: "2024-05-20",
    rating: 5,
    pages: 380,
    genre: "Fiction",
    saga: "Inside Mac",
    sagaOrder: 1
  },
  {
    title: "Inside Mac: Tome 2",
    author: "Eny Heli",
    coverUrl: "/books/inside_mac_tome_2-5453083-264-432.jpg",
    readDate: "2024-06-19",
    rating: 4.5,
    pages: 404,
    genre: "Fiction",
    saga: "Inside Mac",
    sagaOrder: 2
  },
];