export const mangas = [
  {
    _type: 'manga',
    _id: 'AVQP8pBozTdbq0wiqMev',
    _score: 7,
    _source: {
      manga: {
        name: 'Naruto',
        slug: 'naruto',
        authors: [
          {
            name: 'Masashi Kishimoto',
          },
        ],
        closeMangas: ['black_clover', 'satan_666'],
        country: 'Japan',
        description:
          "Naruto est un jeune ninja turbulent et orphelin. Seul depuis tout petit, il multiplie les bêtises en tout genre pour se faire remarquer mais n'en arrive qu'à se faire détester par le village de Konoha. Par le biais de son professeur Iruka et du traître Mizuki, il découvre que cette haine collective n'est autre que le fruit du démon qu'il abrite en lui. Kyubi, le démon renard à neuf queues ayant attaqué le village et scellé en lui par le 4ème Hokage. Mais loin de se laisser abattre, Naruto parvient à devenir un vrai ninja et part en missions accompagné du professeur Kakashi, de son amie Sakura et de son rival, Sasuke Uchiwa.",
        hasAnime: true,
        isFinished: true,
        keywords: 'ninja',
        lastUpdate: '05/10/2017',
        nbEpisodes: 500,
        type: 'Shonen',
        mainHero: {
          name: 'Naruto Uzumaki',
        },
        france: {
          editor: 'Kana',
          logo: 'img/france/naruto.png',
          nbBooks: 72,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 72,
          logo: 'img/japan/naruto.png',
          nbChapters: 700,
          publicationEnd: '2014',
          publicationStart: '1999',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMe2',
    _score: 7.5,
    _source: {
      manga: {
        name: 'Kingdom',
        slug: 'kingdom',
        authors: [
          {
            name: 'Yasuhisa Hara',
          },
        ],
        closeMangas: [],
        country: 'Japan',
        description:
          "Des centaines d'années auparavant en Chine, Shin et Hyou sont deux paysans esclaves et le coeur rempli de rêves et d'espoir. Un seul objectif en tête, les deux garçons s'entraînent sans relâche pour devenir Grand Général dans l'armée et ainsi prouver leur force et faire résonner leur nom dans tout le pays. A la suite de la mort de Hyou, Shin jure d'accomplir ce dessein coûte que coûte en accompagnant le jeune Ei Sei qui tente de regagner son trône de roi de Qin, le plus grand état de Chine.",
        hasAnime: true,
        isFinished: false,
        keywords: 'war, general, qin, china',
        lastUpdate: '05/10/2017',
        nbEpisodes: 0,
        type: 'Seinen',
        mainHero: {
          name: 'Shin',
        },
        france: {
          editor: '',
          logo: 'img/france/kingdom.png',
          nbBooks: 0,
        },
        japan: {
          editor: 'Shueisha',
          magazine: 'Weekly Young Jump',
          nbBooks: 49,
          nbChapters: 532,
          publicationEnd: null,
          publicationStart: '2006',
          logo: 'img/japan/kingdom.png',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pCEzTdbq0wiqMe3',
    _score: 8.5,
    _source: {
      manga: {
        name: 'Eyeshield 21',
        slug: 'eyeshield_21',
        authors: [
          {
            name: 'Riichirō Inagaki',
          },
          {
            name: 'Yusuke Murata',
          },
        ],
        closeMangas: [],
        description:
          "Sena Kobayakawa est un jeune lycéen petit et par-dessus tout, craintif. Souffre-douleur et préposé aux basses besognes des Caïds de sa classe, il est constamment en train de courir pour aller chercher ce qu'ils demandent. Un jour, Yoichi Hiruma, terreur du lycée et membre du club de football Américain avec son ami Kurita, s'aperçoit de son extraordinaire vitesse et cherche à tout prix à le recruter dans le club en tant que Running Back. Mais l'amie d'enfance de Sena, Mamori, n'est pas de cet avis.",
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'sport, american football',
        lastUpdate: '16/04/2016',
        nbEpisodes: 145,
        type: 'Shonen',
        mainHero: {
          name: 'Kobayakawa Sena',
        },
        france: {
          editor: 'Glénat',
          logo: 'img/eyeshield21.png',
          nbBooks: 37,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/eyeshield21.png',
          nbBooks: 37,
          nbChapters: 333,
          publicationEnd: '2009',
          publicationStart: '2002',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJizTdbq0wiqMfG',
    _score: 6,
    _source: {
      manga: {
        name: 'Boku No Hero Academia',
        slug: 'boku_no_hero_academia',
        authors: [
          {
            name: 'Horikoshi Kouhei',
          },
        ],
        closeMangas: ['black_clover'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: 'hero, super heroes',
        lastUpdate: '05/10/2017',
        nbEpisodes: 13,
        type: 'Shonen',
        mainHero: {
          name: 'Midoriya Izuku',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/bokunoheroacademia.png',
          nbBooks: 8,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/bokunoheroacademia.png',
          nbBooks: 15,
          nbChapters: 153,
          publicationEnd: null,
          publicationStart: '2014',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKOzTdbq0wiqMfJ',
    _score: 6.5,
    _source: {
      manga: {
        name: 'The Gamer',
        slug: 'the_gamer',
        authors: [
          {
            name: 'Sung San-Young',
          },
        ],
        closeMangas: ['solo_leveling', 'dice'],
        description:
          "Jee Han est un lycéen tout ce qu'il y a de plus normal. Passionné de jeux vidéos, il se réveille un jour en se découvrant des pouvoirs surnaturels. Le pouvoir du maître de jeu vidéo. Augmentation de son intellect, apprentissage de nouveaux coups, pop-ups pour accepter des défis... Cependant ces pouvoirs vont rapidement lui apprendre l'existence d'un réseau souterrain et empli de clans aux pouvoirs surnaturels.",
        hasAnime: true,
        country: 'Corea',
        isFinished: true,
        keywords: 'video game',
        lastUpdate: '05/10/2017',
        nbEpisodes: 0,
        type: 'Shonen',
        mainHero: {
          name: 'Jee Han',
        },
        france: {
          editor: '',
          logo: 'img/thegamer.jpg',
          nbBooks: 0,
        },
        corea: {
          editor: 'Naver',
          logo: 'img/thegamer.jpg',
          nbBooks: 0,
          nbChapters: 193,
          publicationEnd: null,
          publicationStart: '2013',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKSzTdbq0wiqMfK',
    _score: 5,
    _source: {
      manga: {
        name: 'Black Clover',
        slug: 'black_clover',
        authors: [
          {
            name: 'Tabata Yuuki',
          },
        ],
        closeMangas: ['naruto', 'boku_no_hero_academia'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Aster',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 0,
          logo: 'img/france/blackclover.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 11,
          logo: 'img/japan/blackclover.jpg',
          nbChapters: 51,
          publicationEnd: null,
          publicationStart: '2015',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKszTdbq0wiqMfL',
    _score: 4.5,
    _source: {
      manga: {
        name: 'Nisekoi',
        slug: 'nisekoi',
        authors: [
          {
            name: 'Komi Naoshi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Raku Ishijou',
        },
        france: {
          editor: '',
          logo: 'img/nisekoi.png',
          nbBooks: 0,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/nisekoi.png',
          nbBooks: 0,
          nbChapters: 212,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNEzTdbq0wiqMfZ',
    _score: 6,
    _source: {
      manga: {
        name: 'Dreamland',
        slug: 'dreamland',
        authors: [
          {
            name: 'Reno Lemaire',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '05/10/2017',
        type: 'Shonen',
        mainHero: {
          name: 'Terrence Meyer',
        },
        france: {
          editor: 'Pika',
          logo: 'img/france/dreamland.svg',
          nbBooks: 16,
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pPZzTdbq0wiqMfk',
    _score: 5.5,
    _source: {
      manga: {
        name: 'City Hunter',
        slug: 'city_hunter',
        frenchName: 'Nicky Larson',
        authors: [
          {
            name: '',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Ryo Saeba',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/france/cityhunter.png',
          nbBooks: 0,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/japan/cityhunter.png',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: '',
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfp',
    _score: 5,
    _source: {
      manga: {
        name: 'Saru Lock',
        slug: 'saru_lock',
        authors: [
          {
            name: 'Naoki Serizawa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Seinen',
        mainHero: {
          name: 'Yutaro Sarumaru',
        },
        france: {
          editor: '',
          logo: 'img/france/sarulock.png',
          nbBooks: 22,
        },
        japan: {
          editor: '',
          logo: 'img/japan/sarulock.png',
          nbBooks: 22,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQnzTdbq0wiqMfv',
    _score: 4,
    _source: {
      manga: {
        name: 'Young GTO',
        slug: 'young_gto',
        authors: [
          {
            name: 'Tōru Fujisawa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Shonen',
        mainHero: {
          name: 'Eiikichi Onizuka',
        },
        france: {
          editor: 'Pika',
          logo: 'img/younggto.gif',
          nbBooks: 0,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/younggto.gif',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQ6zTdbq0wiqMfx',
    _score: 3.5,
    _source: {
      manga: {
        name: 'Kubera',
        slug: 'kubera',
        authors: [
          {
            name: '',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Corea',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Shonen',
        mainHero: {
          name: 'Kubera',
        },
        france: {
          editor: '',
          logo: 'img/france/kubera.jpg',
          nbBooks: 0,
        },
        corea: {
          editor: '',
          logo: 'img/japan/kubera.jpg',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pRszTdbq0wiqMf1',
    _score: 4,
    _source: {
      manga: {
        name: 'Fairy Tail',
        slug: 'fairy_tail',
        authors: [
          {
            name: 'Hiro Mashima',
          },
        ],
        closeMangas: ['Rave'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: 'magic',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Shonen',
        mainHero: {
          name: 'Natsu Dragnir',
        },
        france: {
          editor: '',
          logo: 'img/france/fairytail.png',
          nbBooks: 0,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/japan/fairytail.png',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pSfzTdbq0wiqMf4',
    _score: 5,
    _source: {
      manga: {
        name: 'Hi No Tori',
        slug: 'hi_no_tori',
        authors: [
          {
            name: 'Ozamu Tezuka',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Seinen',
        mainHero: {
          name: 'Hino',
        },
        france: {
          editor: '',
          logo: 'img/france/hinotori.png',
          nbBooks: 21,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/japan/hinotori.png',
          nbBooks: 21,
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB3zTdbq0wiqMew',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Pretty Face',
        slug: 'pretty_face',
        authors: [
          {
            name: 'Yasuhiro Kanô',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        lastUpdate: '16/04/2016',
        nbEpisodes: 0,
        type: 'Shonen',
        mainHero: {
          name: 'Masashi Rando',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          editor: 'Tonkam',
          logo: 'img/france/prettyface.png',
          nbBooks: 6,
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          logo: 'img/',
          nbBooks: 6,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMe0',
    _score: 7.5,
    _source: {
      manga: {
        name: 'Dragon Ball',
        slug: 'dragon_ball',
        authors: [
          {
            name: 'Akira Toriyama',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/france.png',
        mainHero: {
          name: 'Sangoku',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 42,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 42,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pGjzTdbq0wiqMe6',
    _score: 4.5,
    _source: {
      manga: {
        name: 'Red Storm',
        slug: 'red_storm',
        authors: [
          {
            name: 'Cyungchan Noh',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Corea',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/',
        mainHero: {
          name: 'Yulian Provoke',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
        nbBooks: 0,
        nbChapters: 189,
        publicationEnd: null,
        publicationStart: '',
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pHuzTdbq0wiqMe-',
    _score: 6.5,
    _source: {
      manga: {
        name: 'OnePunch-Man',
        slug: 'one_punch_man',
        authors: [
          {
            name: 'Yûsuke Murata',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Saitama',
        },
        france: {
          editor: 'Kurokawa',
          nbBooks: 8,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Tonari no Young Jump',
          editor: 'Shueisha',
          nbBooks: 14,
          logo: 'img/france.png',
          nbChapters: 98,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKwzTdbq0wiqMfM',
    _score: 7,
    _source: {
      manga: {
        name: 'Noblesse',
        slug: 'noblesse',
        authors: [
          {
            name: 'Son Jae-Ho',
          },
          {
            name: 'Lee Gwang-Su',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Corea',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/france/noblesse.png',
        mainHero: {
          name: 'Cadis Etrama Di Raizel',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/noblesse.png',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/corea/noblesse.png',
          nbChapters: 400,
          publicationEnd: null,
          publicationStart: '2007',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pL5zTdbq0wiqMfT',
    _score: 5.5,
    _source: {
      manga: {
        name: 'GTO',
        authors: [
          {
            name: '',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Eiikichi Onizuka',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/gto.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/gto.png',
          nbChapters: 0,
          publicationEnd: '2002',
          publicationStart: '1997',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pM7zTdbq0wiqMfY',
    _score: 7.5,
    _source: {
      manga: {
        name: 'Tower Of God',
        slug: 'tower_of_god',
        authors: [
          {
            name: 'Slave In Utero',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/towerofgod.png',
        mainHero: {
          name: '25th Baam',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/towerofgod.png',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 349,
          publicationEnd: null,
          publicationStart: '2010',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMSzTdbq0wiqMfU',
    _score: 6,
    _source: {
      manga: {
        name: 'Captain Tsubasa',
        slug: 'captain_tsubasa',
        frenchName: 'Olive Et Tom',
        authors: [
          {
            name: 'Yōichi Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'sport, football',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Tsubasa Ohzora',
        },
        france: {
          editor: '',
          nbBooks: 37,
          logo: 'img/france/captaintsubasa.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 37,
          logo: 'img/japan/captaintsubasa.png',
          nbChapters: 0,
          publicationEnd: '1988',
          publicationStart: '1981',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pN9zTdbq0wiqMfd',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Slam Dunk',
        slug: 'slam_dunk',
        authors: [
          {
            name: 'Takehiko Inoue',
          },
        ],
        closeMangas: ['Kuroko No Basket', 'Crows'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'basket, sport',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Hanamichi Sakuragi',
        },
        france: {
          editor: '',
          nbBooks: 31,
          logo: 'img/france/slamdunk.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 31,
          logo: 'img/japan/slamdunk.png',
          nbChapters: 0,
          publicationEnd: '1996',
          publicationStart: '1990',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pPZzTdbq0wiqMfl',
    _score: 5,
    _source: {
      manga: {
        name: "Darwin's Game",
        slug: 'darwin_game',
        authors: [
          {
            name: 'Flipf lops',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Sudo Kaname',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/darwinsgame.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/darwinsgame.png',
          nbChapters: 21,
          publicationEnd: null,
          publicationStart: '2015',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfo',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Hikaru No Go',
        slug: 'hikaru_no_go',
        authors: [
          {
            name: 'Yumi Hotta',
          },
          {
            name: 'Tsugumi Ohba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/hikarunogo.gif',
        mainHero: {
          name: 'Hikaru',
        },
        france: {
          editor: 'Tonkam',
          nbBooks: 23,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 23,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: '2003',
          publicationStart: '1998',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQ6zTdbq0wiqMfw',
    _score: 5.5,
    _source: {
      manga: {
        name: 'Rave',
        slug: 'rave',
        authors: [
          {
            name: 'Hiro Mashima',
          },
        ],
        closeMangas: ['fairy_tail'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Haru Glory',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 35,
          logo: 'img/france/rave.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 35,
          logo: 'img/japan/rave.png',
          nbChapters: 0,
          publicationEnd: '2005',
          publicationStart: '1999',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pRfzTdbq0wiqMfz',
    _score: 4.5,
    _source: {
      manga: {
        name: 'Kuroko No Basket',
        slug: 'kuroko_no_basket',
        authors: [
          {
            name: 'Tadatoshi Fujimaki',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'sport',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Kuroko',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/kurokonobasket.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/kurokonobasket.png',
          nbChapters: 0,
          publicationEnd: '2014',
          publicationStart: '2008',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pRozTdbq0wiqMf0',
    _score: 4,
    _source: {
      manga: {
        name: 'Code:breaker',
        slug: 'code_breaker',
        authors: [
          {
            name: 'Akimine Kamijō',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/codebreaker.png',
        mainHero: {
          name: 'Rei Ôgami',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/codebreaker.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/codebreaker.png',
          nbChapters: 200,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTMzTdbq0wiqMf7',
    _score: 3.5,
    _source: {
      manga: {
        name: 'Reborn',
        slug: 'reborn',
        authors: [
          {
            name: 'Akira Amano',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/reborn.jpg',
        mainHero: {
          name: 'Reborn',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/reborn.jpg',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/reborn.jpg',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB4zTdbq0wiqMex',
    _score: 8.5,
    _source: {
      manga: {
        name: 'Bakuman',
        slug: 'bakuman',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsugumi Ōba',
          },
        ],
        closeMangas: [],
        description: 'manga, editor',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Mashiro Moritaka',
        },
        france: {
          editor: 'Kana',
          nbBooks: 20,
          logo: 'img/france/bakuman.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 20,
          logo: 'img/japan/bakuman.png',
          nbChapters: 822,
          publicationEnd: '2012',
          publicationStart: '2008',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMe1',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Jackals',
        slug: 'jackals',
        authors: [
          {
            name: 'Kim Byung Jin',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        logo: 'img/jackals.png',
        mainHero: {
          name: 'Alligator Nihol',
        },
        france: {
          editor: '',
          nbBooks: 6,
          logo: 'img/france/jackals.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 6,
          logo: 'img/japan/jackals.png',
          nbChapters: 56,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pGwzTdbq0wiqMe7',
    _score: 6,
    _source: {
      manga: {
        name: 'Magi The Labyrinth of Magic',
        slug: 'magi',
        authors: [
          {
            name: 'Ohtaka Shinobu',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/magi.png',
        mainHero: {
          name: 'Aladin',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/frane/magi.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/magi.png',
          nbChapters: 300,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKIzTdbq0wiqMfH',
    _score: 7,
    _source: {
      manga: {
        name: 'Yu Yu Hakusho',
        slug: 'yu_yu_hakusho',
        authors: [
          {
            name: 'Yoshihiro Togashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yusuke Urameshi',
        },
        france: {
          editor: 'Kana',
          nbBooks: 0,
          logo: 'img/france/yuyuhakusho.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/yuyuhakusho.png',
          nbChapters: 0,
          publicationEnd: '1994',
          publicationStart: '1990',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLgzTdbq0wiqMfP',
    _score: 6,
    _source: {
      manga: {
        name: 'Fullmetal Alchemist',
        slug: 'full_metal_alchemist',
        authors: [
          {
            name: 'Hiromu Arakawa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Edward Elric',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/fullmetalalchemist.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/fullmetalalchemist.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLhzTdbq0wiqMfR',
    _score: 5,
    _source: {
      manga: {
        name: 'Ginga Patrol Jako',
        slug: 'ginga_patrol_jako',
        authors: [
          {
            name: 'Akira Toriyama',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Jako',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/gingapatroljako.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/gingapatroljako.png',
          nbChapters: 12,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMWzTdbq0wiqMfV',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Gamble fish',
        slug: 'gamble_fish',
        authors: [
          {
            name: 'Aoyama Hiromi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Ecchi',
        mainHero: {
          name: 'Tomu Shirasagi',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/gamblefish.png',
        },
        japan: {
          editor: 'Akita Shoten',
          magazine: 'Weekly Shōnen Champion',
          nbBooks: 19,
          logo: 'img/japan/gamblefish.png',
          nbChapters: 167,
          publicationEnd: '2010',
          publicationStart: '2007',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMvzTdbq0wiqMfX',
    _score: 4,
    _source: {
      manga: {
        name: 'Tonari no Seki-kun',
        slug: 'tonari_no_seki_kun',
        authors: [
          {
            name: 'Takuma Morishige',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Seki',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/tonarinosekikun.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: 'img/japan/tonarinosekikun.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNzzTdbq0wiqMfc',
    _score: 5,
    _source: {
      manga: {
        name: 'Puella Magi Madoka Magica',
        slug: 'puella_magi_madoka_magica',
        authors: [
          {
            name: 'Hanokage',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        mainHero: {
          name: 'Madoka Kaname',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france/puellamagimadokamagica.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/puellamagimadokamagica.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pN_zTdbq0wiqMfe',
    _score: 6,
    _source: {
      manga: {
        name: 'Nanatsu No Taizai',
        slug: 'nanatsu_no_taizai',
        authors: [
          {
            name: 'Suzuki Nakaba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'M',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france/nanatsunotaizai.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/nanatsunotaizai.png',
          nbChapters: 167,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pO8zTdbq0wiqMfj',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Black Cat',
        slug: 'black_cat',
        authors: [
          {
            name: 'Kentaro Yabuki',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Train Heartnet',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 0,
          logo: 'img/france/blackcat.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/blackcat.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfr',
    _score: 5.5,
    _source: {
      manga: {
        name: 'Shaman king',
        slug: 'shaman_king',
        authors: [
          {
            name: 'Hiroyuki Takei',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yo',
        },
        france: {
          editor: 'Kana',
          nbBooks: 0,
          logo: 'img/france/shamanking.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/shamanking.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQjzTdbq0wiqMfu',
    _score: 4,
    _source: {
      manga: {
        name: 'Doubt',
        slug: 'doubt',
        authors: [
          {
            name: 'Yoshiki Tonogai',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        mainHero: {
          name: 'Yū Aikawa',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 6,
          logo: 'img/france/doubt.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 6,
          logo: 'img/japan/doubt.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pR8zTdbq0wiqMf2',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Shokugeki no Soma',
        slug: 'shokugeki_no_soma',
        authors: [
          {
            name: 'Tsukuda Yuuto',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Souma Yukihira',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/shokugekinosoma.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/shokugekinosoma.png',
          nbChapters: 161,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTbzTdbq0wiqMf8',
    _score: 4.5,
    _source: {
      manga: {
        name: 'Blue Dragon : Ral Ω Grad',
        slug: 'blue_dragon',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsuneo Takano',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shu',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/bluedragon.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: 'img/japan/bluedragon.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTzzTdbq0wiqMf9',
    _score: 3,
    _source: {
      manga: {
        name: 'Blazing Ninjaman',
        slug: 'blazing_ninjaman',
        authors: [
          {
            name: '',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shinobi Mantaro',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMez',
    _score: 10,
    _source: {
      manga: {
        name: 'One Piece',
        slug: 'one_piece',
        authors: [
          {
            name: 'Eiichirō Oda',
          },
        ],
        closeMangas: [],
        description:
          "Luffy est un jeune garçon qui rêve de devenir un pirate, comme son idole Shanks. Par innatention, il mange un jour un fruit du démon qui le rend élastique mais lui confère l'impossibilité de nager. Après s'être fait sauver la vie par Shanks, il jure à ce dernier de devenir le Seigneur des Pirates et s'entraîne pendant 10 ans à utiliser son pouvoir. Il prend la mer à 17 ans pour trouver de valeureux compagnons, la tête pleine de rêves qu'il fera tout pour réaliser.",
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 737,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Monkey D. Luffy',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 78,
          logo: 'img/onepiece.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 81,
          logo: 'img/onepiece.png',
          nbChapters: 852,
          publicationEnd: null,
          publicationStart: '1997',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pCIzTdbq0wiqMe5',
    _score: 9,
    _source: {
      manga: {
        name: 'Rurouni No Kenshin',
        slug: 'kenshin',
        frenchName: 'Kenshin le Vagabond',
        authors: [
          {
            name: 'Nobuhiro Watsuki',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'samourai, samurai, sword, vagabond',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Kenshin Himura',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 28,
          logo: 'img/france/kenshinlevagabond.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 28,
          logo: 'img/japan/kenshinlevagabond.png',
          nbChapters: 0,
          publicationEnd: '1999',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pB8zTdbq0wiqMey',
    _score: 8,
    _source: {
      manga: {
        name: 'Feng Shen Ji',
        slug: 'feng_shen_ji',
        authors: [
          {
            name: 'Zeng Jian He',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: 'gods, manhua',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Ah Gou',
        },
        japaneseEditor: '',
        frenchEditor: '',
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/fengshenji.svg',
        },
        china: {
          editor: '',
          nbBooks: 0,
          logo: 'img/china/fengshenji.svg',
          nbChapters: 180,
          publicationEnd: '2016',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pHSzTdbq0wiqMe9',
    _score: 7,
    _source: {
      manga: {
        name: 'Toriko',
        slug: 'toriko',
        authors: [
          {
            name: 'Shimabukuro Mitsutoshi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: 'food, gourmet, animals',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Toriko',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          editor: '',
          nbBooks: 40,
          logo: 'img/france/toriko.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 43,
          logo: 'img/japan/toriko.png',
          nbChapters: 366,
          publicationEnd: '2016',
          publicationStart: '2008',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pIezTdbq0wiqMfB',
    _score: 7,
    _source: {
      manga: {
        name: 'Satan 666',
        slug: 'satan_666',
        authors: [
          {
            name: 'Seishi Kishimoto',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Jio Freed',
        },
        france: {
          editor: 'Kurokawa',
          nbBooks: 19,
          logo: 'img/france/satan666.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 19,
          logo: 'img/japan/satan666.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJCzTdbq0wiqMfC',
    _score: 7,
    _source: {
      manga: {
        name: 'Worst',
        slug: 'worst',
        authors: [
          {
            name: 'Hiroshi Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'furyo',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Hana Tsukihima',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/worst.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: 'img/japan/worst.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJizTdbq0wiqMfF',
    _score: 6,
    _source: {
      manga: {
        name: 'Akame Ga Kill',
        slug: 'akame_ga_kill',
        authors: [
          {
            name: 'Takahiro',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Tatsumi',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france/akamegakill.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/akamegakill.png',
          nbChapters: 69,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pK-zTdbq0wiqMfN',
    _score: 8.5,
    _source: {
      manga: {
        name: 'Death Note',
        slug: 'death_note',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsugumi Ohba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Raito Yagami',
        },
        france: {
          editor: 'Kana',
          nbBooks: 13,
          logo: 'img/france.png',
        },
        japan: {
          editor: '',
          nbBooks: 13,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLLzTdbq0wiqMfO',
    _score: 7.5,
    _source: {
      manga: {
        name: 'Assassination Classroom',
        slug: 'assassination_classroom',
        authors: [
          {
            name: 'Matsui Yuusei',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Korosensei',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france/assassinationclassroom.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/assassinationclassroom.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pKMzTdbq0wiqMfI',
    _score: 6,
    _source: {
      manga: {
        name: 'Karate Shoukoushi Kohinata Minoru',
        slug: 'karate_shoukoushi_kohinata_minoru',
        authors: [
          {
            name: 'Yasushi Baba',
          },
        ],
        closeMangas: ['Kenichi'],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Kohinata Minoru',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/kohinataminoru.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: 'img/japan/kohinataminoru.png',
          nbChapters: 388,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLgzTdbq0wiqMfQ',
    _score: 7,
    _source: {
      manga: {
        name: 'Hunter X Hunter',
        slug: 'hunter_x_hunter',
        authors: [
          {
            name: 'Yoshihiro Togashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Gon Freecs',
        },
        france: {
          editor: 'Kana',
          nbBooks: 0,
          logo: 'img/france/hunterxhunter.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/hunterxhunter.png',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pLtzTdbq0wiqMfS',
    _score: 7,
    _source: {
      manga: {
        name: 'Beelzebub',
        slug: 'beelzebub',
        authors: [
          {
            name: 'Ryūhei Tamura',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Oga Tatsumi',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/beelzebub.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/japan/beelzebub.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pMbzTdbq0wiqMfW',
    _score: 6,
    _source: {
      manga: {
        name: 'Shingeki No Kyojin',
        slug: 'shingeki_no_kyojin',
        frenchName: "L'attaque des titans",
        authors: [
          {
            name: 'Isayama Hajime',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Seinen',
        mainHero: {
          name: 'Eren Jaeger',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france/shingekinokyojin.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: 'img/japan/shingekinokyojin.png',
          nbChapters: 80,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNjzTdbq0wiqMfb',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Claymore',
        slug: 'claymore',
        authors: [
          {
            name: 'Yagu Norihiro',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        logo: 'img/',
        mainHero: {
          name: 'Claire',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
        nbBooks: 0,
        nbChapters: 155,
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        publicationEnd: '',
        publicationStart: '',
        type: 'Shonen',
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pOUzTdbq0wiqMfg',
    _score: 7,
    _source: {
      manga: {
        name: 'Ashita No Joe',
        slug: 'ashita_no_joe',
        frenchName: "Tomorrow's Joe",
        authors: [
          {
            name: 'Takamori Asao',
          },
        ],
        closeMangas: [],
        description: 'sport, boxe',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        logo: 'img/',
        mainHero: {
          name: 'Joe Yabuki',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
        nbBooks: 20,
        nbChapters: 108,
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        publicationEnd: '',
        publicationStart: '',
        type: 'Shonen',
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pOszTdbq0wiqMfh',
    _score: 6,
    _source: {
      manga: {
        name: 'Gamaran',
        slug: 'gamaran',
        authors: [
          {
            name: 'Yōsuke Nakamaru',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        logo: 'img/',
        mainHero: {
          name: 'Gama',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
        nbBooks: 0,
        nbChapters: 0,
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        publicationEnd: '',
        publicationStart: '',
        type: 'Shonen',
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pO0zTdbq0wiqMfi',
    _score: 4.5,
    _source: {
      manga: {
        name: 'Terra Formars',
        slug: 'terra_formars',
        authors: [
          {
            name: 'Yu Sagusa',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shôkichi Komachi',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 172,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pPezTdbq0wiqMfn',
    _score: 5.5,
    _source: {
      manga: {
        name: 'World Trigger',
        slug: 'world_trigger',
        authors: [
          {
            name: 'Daisuke Ashihara',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yûma Kuga',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 129,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pP7zTdbq0wiqMfq',
    _score: 7,
    _source: {
      manga: {
        name: 'The Breaker',
        slug: 'the_breaker',
        authors: [
          {
            name: 'Jeon Geuk-Jin',
          },
          {
            name: 'Park Jin-Hwan',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Li Shioon',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        corea: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQizTdbq0wiqMft',
    _score: 4.5,
    _source: {
      manga: {
        name: 'Asu No Yoichi',
        slug: 'asu_no_yoichi',
        authors: [
          {
            name: 'Yū Minamoto',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Ecchi',
        mainHero: {
          name: 'Yoichi Karasuma',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pCIzTdbq0wiqMe4',
    _score: 7,
    _source: {
      manga: {
        name: "Shijō Saikyō no Deshi Ken'ichi",
        slug: 'kenichi',
        frenchName: 'Ken-ichi, le disciple ultime',
        authors: [
          {
            name: 'Matsuena Syun',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: 'martial arts, fight',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Shirahama Kenichi',
        },
        france: {
          editor: 'Kurokawa',
          nbBooks: 61,
          logo: 'img/france.png',
        },
        japan: {
          editor: '',
          nbBooks: 61,
          logo: 'img/japan.png',
          nbChapters: 583,
          publicationEnd: '2014',
          publicationStart: '2002',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJGzTdbq0wiqMfD',
    _score: 7,
    _source: {
      manga: {
        name: 'Yu-Gi-Oh!',
        slug: 'yu_gi_oh',
        authors: [
          {
            name: 'Kazuki Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Yugi Muto',
        },
        france: {
          editor: 'Kana',
          nbBooks: 37,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 37,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pPdzTdbq0wiqMfm',
    _score: 7,
    _source: {
      manga: {
        name: 'Bleach',
        slug: 'bleach',
        authors: [
          {
            name: 'Tite Kubo',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Ichigo Kurosaki',
        },
        france: {
          editor: 'Glénat',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 670,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pSczTdbq0wiqMf3',
    _score: 6.5,
    _source: {
      manga: {
        name: "Girls of The Wild's",
        slug: 'girls_of_the_wild',
        authors: [
          {
            name: 'Hun',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Song Jae Gu',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        corea: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 230,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pTHzTdbq0wiqMf6',
    _score: 5.5,
    _source: {
      manga: {
        name: 'Lui Ou Rien !',
        slug: 'lui_ou_rien',
        authors: [
          {
            name: 'Yū Watase',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        logo: 'img/',
        mainHero: {
          name: 'Riiko Izawa',
        },
        japaneseEditor: '',
        frenchEditor: 'Glénat',
        france: {
          editor: '',
          nbBooks: 6,
          logo: 'img/france.png',
        },
        japan: {
          editor: '',
          nbBooks: 6,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pHQzTdbq0wiqMe8',
    _score: 6.5,
    _source: {
      manga: {
        name: 'DICE: The Cube that Changes Everything',
        slug: 'dice',
        authors: [
          {
            name: 'Yun Hyun Suk',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        nbEpisodes: 0,
        lastUpdate: '16/04/2016',
        type: 'Shonen',
        mainHero: {
          name: 'Dongtae',
        },
        france: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        corea: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 134,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 5.5,
    _source: {
      manga: {
        name: 'Dr. Frost',
        slug: 'dr_frost',
        authors: [
          {
            name: 'Lee Jong-bym',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Dr Frost',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        corea: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 87,
          publicationEnd: null,
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pJZzTdbq0wiqMfE',
    _score: 7.5,
    _source: {
      manga: {
        name: 'All You Need Is Kill',
        slug: 'all_you_need_is_kill',
        authors: [
          {
            name: 'Takeshi Obata',
          },
          {
            name: 'Tsugumi Ohba',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Keiji Kiriya',
        },
        france: {
          editor: 'Kazé',
          nbBooks: 2,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 2,
          logo: 'img/france.png',
          nbChapters: 17,
          publicationEnd: '2014',
          publicationStart: '2014',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pNXzTdbq0wiqMfa',
    _score: 7,
    _source: {
      manga: {
        name: 'Crows',
        slug: 'crows',
        authors: [
          {
            name: 'Hiroshi Takahashi',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Boya Harumichi',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pORzTdbq0wiqMff',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Meitantei Konan',
        frenchName: 'Détective Conan',
        slug: 'detective_conan',
        authors: [
          {
            name: 'Gōshō Aoyama',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: true,
        keywords: '',
        mainHero: {
          name: 'Shinichi Kudo',
        },
        france: {
          editor: 'Kana',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          editor: '',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pQezTdbq0wiqMfs',
    _score: 6,
    _source: {
      manga: {
        name: 'Hinomaru Zumou',
        slug: 'hinomaru_zumou',
        authors: [
          {
            name: 'Kawada',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        logo: 'img/',
        mainHero: {
          name: 'Ushio Hinomaru',
        },
        japaneseEditor: 'Weekly Shōnen Jump',
        frenchEditor: 'Glénat',
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          nbChapters: 61,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pRczTdbq0wiqMfy',
    _score: 6,
    _source: {
      manga: {
        name: 'Haikyū!!',
        slug: 'haikyu',
        authors: [
          {
            name: 'Haruichi Furudate',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: 'sport, volleyball, ',
        mainHero: {
          name: 'Shōyō Hinata',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: 'img/france.png',
        },
        japan: {
          magazine: 'Weekly Shōnen Jump',
          editor: 'Shueisha',
          nbBooks: 0,
          nbChapters: 0,
          publicationEnd: 'null',
          publicationStart: '1994',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 6.5,
    _source: {
      manga: {
        name: 'Unordinary',
        slug: 'unordinary',
        authors: [
          {
            name: 'uru-chan',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'John Doe',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 66,
          publicationEnd: null,
          publicationStart: '2016',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 5.5,
    _source: {
      manga: {
        name: 'I Love Yoo',
        slug: 'i_love_yoo',
        authors: [
          {
            name: 'Quimchee',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Shin-Ae',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 23,
          publicationEnd: null,
          publicationStart: '2017',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 6,
    _source: {
      manga: {
        name: 'The Promised Neverland',
        slug: 'the_promised_neverland',
        authors: [
          {
            name: 'Kaiu Shirai',
          },
          {
            name: 'Posuka Demizu',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: true,
        country: 'Japan',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Emma',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        japan: {
          editor: 'Shueisha',
          nbBooks: 14,
          logo: 'img/france.png',
          nbChapters: 139,
          publicationEnd: null,
          publicationStart: '2016',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 7,
    _source: {
      manga: {
        name: 'Solo Leveling',
        slug: 'solo_leveling',
        authors: [
          {
            name: 'Jang Sung-Lak',
          },
          {
            name: 'Gee So-Lyung',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Sung Jin-Woo',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 76,
          publicationEnd: null,
          publicationStart: '2018',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 6,
    _source: {
      manga: {
        name: 'Wind Breaker',
        slug: 'wind_breaker',
        authors: [
          {
            name: 'Yongseok Jo',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Jay',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 6,
    _source: {
      manga: {
        name: 'Lookism',
        slug: 'lookism',
        authors: [
          {
            name: 'Park Tae-joon',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Daniel Park',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 7,
    _source: {
      manga: {
        name: 'Bastard',
        slug: 'bastard',
        authors: [
          {
            name: 'YoungChan Hwang',
          },
          {
            name: 'Carnby Kim',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: '',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
  {
    _type: 'manga',
    _id: 'AVQP8pILzTdbq0wiqMfA',
    _score: 7,
    _source: {
      manga: {
        name: 'Sidekicks',
        slug: 'sidekicks',
        authors: [
          {
            name: 'Iron Shin',
          },
        ],
        closeMangas: [],
        description: '',
        hasAnime: false,
        country: 'Corea',
        isFinished: false,
        keywords: '',
        mainHero: {
          name: 'Dream Girl',
        },
        france: {
          editor: '',
          nbBooks: 0,
          logo: '',
        },
        corea: {
          editor: 'Naver',
          nbBooks: 0,
          logo: 'img/france.png',
          nbChapters: 0,
          publicationEnd: null,
          publicationStart: '',
        },
      },
    },
  },
];
